# "교과 > 기본 단어·반의어" subtab -- 반의어 (antonym pairs), 99 entries,
# transcribed verbatim from pages 97-98 ("반대어") of the course booklet, with a
# few hand-corrections to the Vietnamese word choice/Korean gloss on some pairs
# (and one duplicate near-synonym pair, lọ/chai, removed).
# (모든 대화를 구성하는 기본 단어 glossary lives in basic_words_list.py.)
#
# "kr1"/"kr2" are stored as {"ko","zh","en","ja"} dicts so js_json() (see build_app.py)
# serializes them straight into JS objects app_logic.js's T() helper can read directly.

ANTONYM_PAIRS = [{'vi1': 'ăn',
  'kr1': {'ko': '먹다', 'zh': '吃', 'en': 'eat', 'ja': '食べる', 'de': 'essen', 'fr': 'manger'},
  'vi2': 'uống',
  'kr2': {'ko': '마시다', 'zh': '喝', 'en': 'drink', 'ja': '飲む', 'de': 'trinken', 'fr': 'boire'}},
 {'vi1': 'ba',
  'kr1': {'ko': '아빠', 'zh': '爸爸', 'en': 'dad', 'ja': 'パパ', 'de': 'Papa', 'fr': 'papa'},
  'vi2': 'má',
  'kr2': {'ko': '엄마', 'zh': '媽媽', 'en': 'mom', 'ja': 'ママ', 'de': 'Mama', 'fr': 'maman'}},
 {'vi1': 'bán',
  'kr1': {'ko': '팔다', 'zh': '賣', 'en': 'to sell', 'ja': '売る', 'de': 'verkaufen', 'fr': 'vendre'},
  'vi2': 'mua',
  'kr2': {'ko': '사다', 'zh': '買', 'en': 'to buy', 'ja': '買う', 'de': 'kaufen', 'fr': 'acheter'}},
 {'vi1': 'bận',
  'kr1': {'ko': '바쁜', 'zh': '忙碌的', 'en': 'busy', 'ja': '忙しい', 'de': 'beschäftigt', 'fr': 'occupé'},
  'vi2': 'rảnh rỗi',
  'kr2': {'ko': '한가한',
          'zh': '空閒的',
          'en': 'free, available',
          'ja': '暇な',
          'de': 'frei, Zeit haben',
          'fr': 'libre, disponible'}},
 {'vi1': 'bắt đầu',
  'kr1': {'ko': '시작하다', 'zh': '開始', 'en': 'to start', 'ja': '始める', 'de': 'anfangen, beginnen', 'fr': 'commencer'},
  'vi2': 'kết thúc',
  'kr2': {'ko': '끝나다', 'zh': '結束', 'en': 'end', 'ja': '終わる', 'de': 'enden, beenden', 'fr': 'finir, se terminer'}},
 {'vi1': 'bên trái',
  'kr1': {'ko': '왼쪽', 'zh': '左邊', 'en': 'left', 'ja': '左', 'de': 'links', 'fr': 'gauche'},
  'vi2': 'bên phải',
  'kr2': {'ko': '오른쪽', 'zh': '右邊', 'en': 'right', 'ja': '右', 'de': 'rechts', 'fr': 'droite'}},
 {'vi1': 'béo, mập',
  'kr1': {'ko': '뚱뚱한', 'zh': '胖的', 'en': 'fat', 'ja': '太った', 'de': 'dick', 'fr': 'gros'},
  'vi2': 'gầy, ốm',
  'kr2': {'ko': '마른', 'zh': '瘦的', 'en': 'thin', 'ja': '痩せた', 'de': 'dünn, schlank', 'fr': 'maigre, mince'}},
 {'vi1': 'cao',
  'kr1': {'ko': '높은', 'zh': '高的', 'en': 'high', 'ja': '高い', 'de': 'hoch', 'fr': 'haut, grand'},
  'vi2': 'thấp',
  'kr2': {'ko': '낮은', 'zh': '低的', 'en': 'low', 'ja': '低い', 'de': 'niedrig', 'fr': 'bas, petit'}},
 {'vi1': '(cái) bàn',
  'kr1': {'ko': '책상', 'zh': '書桌', 'en': 'desk', 'ja': '机', 'de': 'Schreibtisch', 'fr': 'table, bureau'},
  'vi2': '(cái) ghế',
  'kr2': {'ko': '의자', 'zh': '椅子', 'en': 'chair', 'ja': '椅子', 'de': 'Stuhl', 'fr': 'chaise'}},
 {'vi1': '(cái) này',
  'kr1': {'ko': '이(것)', 'zh': '這(個)', 'en': 'this (thing)', 'ja': 'これ', 'de': 'dies(es)', 'fr': 'ceci'},
  'vi2': '(cái) kia',
  'kr2': {'ko': '저(것)', 'zh': '那（個）', 'en': 'that', 'ja': 'あれ', 'de': 'jenes', 'fr': 'cela, celui-là'}},
 {'vi1': 'cần thiết',
  'kr1': {'ko': '필요한', 'zh': '必要的', 'en': 'necessary', 'ja': '必要な', 'de': 'notwendig', 'fr': 'nécessaire'},
  'vi2': 'không cần thiết',
  'kr2': {'ko': '불필요한',
          'zh': '不必要的',
          'en': 'unnecessary',
          'ja': '不必要な',
          'de': 'unnötig',
          'fr': 'inutile, non nécessaire'}},
 {'vi1': 'chậm',
  'kr1': {'ko': '천천히', 'zh': '慢慢地', 'en': 'slowly', 'ja': 'ゆっくり', 'de': 'langsam', 'fr': 'lentement'},
  'vi2': 'nhanh',
  'kr2': {'ko': '빨리', 'zh': '快點，迅速地', 'en': 'quickly', 'ja': '速く', 'de': 'schnell', 'fr': 'vite, rapidement'}},
 {'vi1': 'chật',
  'kr1': {'ko': '좁은', 'zh': '狹窄的', 'en': 'narrow', 'ja': '狭い', 'de': 'eng', 'fr': 'étroit, serré'},
  'vi2': 'rộng',
  'kr2': {'ko': '넓은', 'zh': '寬闊的', 'en': 'wide', 'ja': '広い', 'de': 'weit, breit', 'fr': 'large, spacieux'}},
 {'vi1': 'chết',
  'kr1': {'ko': '죽다', 'zh': '死', 'en': 'to die', 'ja': '死ぬ', 'de': 'sterben', 'fr': 'mourir'},
  'vi2': 'sống',
  'kr2': {'ko': '살다', 'zh': '生活·居住', 'en': 'to live', 'ja': '住む·生きる', 'de': 'leben', 'fr': 'vivre'}},
 {'vi1': 'cho phép',
  'kr1': {'ko': '허락하다', 'zh': '允許', 'en': 'to allow', 'ja': '許可する', 'de': 'erlauben', 'fr': 'permettre, autoriser'},
  'vi2': 'cấm',
  'kr2': {'ko': '금지하다', 'zh': '禁止', 'en': 'to prohibit', 'ja': '禁止する', 'de': 'verbieten', 'fr': 'interdire'}},
 {'vi1': 'cho thấy',
  'kr1': {'ko': '보여주다', 'zh': '給…看，展示', 'en': 'to show', 'ja': '見せる', 'de': 'zeigen', 'fr': 'montrer'},
  'vi2': 'cho biết',
  'kr2': {'ko': '알려주다',
          'zh': '告訴',
          'en': 'to let know, inform',
          'ja': '知らせる',
          'de': 'mitteilen, informieren',
          'fr': 'faire savoir, informer'}},
 {'vi1': 'chưa',
  'kr1': {'ko': '아직', 'zh': '還、仍然', 'en': 'still, yet', 'ja': 'まだ', 'de': 'noch nicht', 'fr': 'pas encore'},
  'vi2': 'rồi',
  'kr2': {'ko': '이미', 'zh': '已經', 'en': 'already', 'ja': 'すでに', 'de': 'schon, bereits', 'fr': 'déjà'}},
 {'vi1': 'có',
  'kr1': {'ko': '있다',
          'zh': '有·存在',
          'en': 'to exist/have',
          'ja': 'ある・いる',
          'de': 'haben, existieren',
          'fr': 'avoir, exister'},
  'vi2': 'không có',
  'kr2': {'ko': '없다',
          'zh': '沒有',
          'en': 'to not exist, not have',
          'ja': 'ない',
          'de': 'nicht haben, nicht da',
          'fr': 'ne pas avoir, ne pas être'}},
 {'vi1': 'cố gắng',
  'kr1': {'ko': '노력하다', 'zh': '努力', 'en': 'make an effort', 'ja': '努力する', 'de': 'sich anstrengen', 'fr': 's’efforcer'},
  'vi2': 'từ bỏ',
  'kr2': {'ko': '포기하다', 'zh': '放棄', 'en': 'to give up', 'ja': '諦める', 'de': 'aufgeben', 'fr': 'abandonner'}},
 {'vi1': 'có thể',
  'kr1': {'ko': '할 수 있다', 'zh': '能夠', 'en': 'can', 'ja': 'できる', 'de': 'können', 'fr': 'pouvoir'},
  'vi2': 'không thể',
  'kr2': {'ko': '할 수 없다', 'zh': '不能', 'en': 'cannot', 'ja': 'できない', 'de': 'nicht können', 'fr': 'ne pas pouvoir'}},
 {'vi1': 'cười',
  'kr1': {'ko': '웃다', 'zh': '笑', 'en': 'to laugh', 'ja': '笑う', 'de': 'lachen', 'fr': 'rire'},
  'vi2': 'khóc',
  'kr2': {'ko': '울다', 'zh': '哭', 'en': 'to cry', 'ja': '泣く', 'de': 'weinen', 'fr': 'pleurer'}},
 {'vi1': 'dài',
  'kr1': {'ko': '긴', 'zh': '長的', 'en': 'long', 'ja': '長い', 'de': 'lang', 'fr': 'long'},
  'vi2': 'ngắn',
  'kr2': {'ko': '짧은', 'zh': '短的', 'en': 'short', 'ja': '短い', 'de': 'kurz', 'fr': 'court'}},
 {'vi1': 'đắt, mắc',
  'kr1': {'ko': '비싼', 'zh': '昂貴的', 'en': 'expensive', 'ja': '高価な', 'de': 'teuer', 'fr': 'cher'},
  'vi2': 'rẻ',
  'kr2': {'ko': '싼', 'zh': '便宜的', 'en': 'cheap', 'ja': '安い', 'de': 'billig', 'fr': 'bon marché'}},
 {'vi1': 'dày',
  'kr1': {'ko': '두꺼운', 'zh': '厚的', 'en': 'thick', 'ja': '厚い', 'de': 'dick', 'fr': 'épais'},
  'vi2': 'mỏng',
  'kr2': {'ko': '얇은', 'zh': '薄的', 'en': 'thin', 'ja': '薄い', 'de': 'dünn', 'fr': 'mince'}},
 {'vi1': 'dậy',
  'kr1': {'ko': '깨다', 'zh': '醒來', 'en': 'to wake up', 'ja': '目覚める', 'de': 'aufwachen', 'fr': 'se réveiller'},
  'vi2': 'ngủ',
  'kr2': {'ko': '자다', 'zh': '睡覺', 'en': 'to sleep', 'ja': '寝る', 'de': 'schlafen', 'fr': 'dormir'}},
 {'vi1': 'đặc biệt',
  'kr1': {'ko': '특별한', 'zh': '特別的', 'en': 'special', 'ja': '特別な', 'de': 'besonders', 'fr': 'spécial, particulier'},
  'vi2': 'bình thường',
  'kr2': {'ko': '평범한',
          'zh': '平凡的',
          'en': 'ordinary',
          'ja': '平凡な',
          'de': 'gewöhnlich, normal',
          'fr': 'ordinaire, normal'}},
 {'vi1': 'đẹp',
  'kr1': {'ko': '아름다운', 'zh': '美麗的', 'en': 'beautiful', 'ja': '美しい', 'de': 'schön', 'fr': 'beau'},
  'vi2': 'xấu',
  'kr2': {'ko': '추한', 'zh': '醜陋的', 'en': 'ugly', 'ja': '醜い', 'de': 'hässlich', 'fr': 'laid, mauvais'}},
 {'vi1': 'đi',
  'kr1': {'ko': '가다', 'zh': '去', 'en': 'to go', 'ja': '行く', 'de': 'gehen', 'fr': 'aller'},
  'vi2': 'đến',
  'kr2': {'ko': '오다', 'zh': '來', 'en': 'to come', 'ja': '来る', 'de': 'kommen', 'fr': 'venir, arriver'}},
 {'vi1': 'đi bộ',
  'kr1': {'ko': '걷다', 'zh': '走路', 'en': 'to walk', 'ja': '歩く', 'de': 'zu Fuß gehen', 'fr': 'marcher à pied'},
  'vi2': 'chạy',
  'kr2': {'ko': '뛰다', 'zh': '跑・跳', 'en': 'run, jump', 'ja': '走る・跳ぶ', 'de': 'laufen, rennen', 'fr': 'courir'}},
 {'vi1': 'địa đàng',
  'kr1': {'ko': '낙원', 'zh': '樂園', 'en': 'paradise', 'ja': '楽園', 'de': 'Paradies', 'fr': 'paradis'},
  'vi2': 'địa ngục',
  'kr2': {'ko': '지옥', 'zh': '地獄', 'en': 'hell', 'ja': '地獄', 'de': 'Hölle', 'fr': 'enfer'}},
 {'vi1': 'đọc',
  'kr1': {'ko': '읽다', 'zh': '讀', 'en': 'to read', 'ja': '読む', 'de': 'lesen', 'fr': 'lire'},
  'vi2': 'nghe',
  'kr2': {'ko': '듣다', 'zh': '聽', 'en': 'listen', 'ja': '聞く', 'de': 'hören', 'fr': 'écouter, entendre'}},
 {'vi1': 'đóng',
  'kr1': {'ko': '닫다', 'zh': '關閉', 'en': 'close', 'ja': '閉める', 'de': 'schließen', 'fr': 'fermer'},
  'vi2': 'mở',
  'kr2': {'ko': '열다', 'zh': '打開', 'en': 'to open', 'ja': '開ける', 'de': 'öffnen', 'fr': 'ouvrir'}},
 {'vi1': 'đồng ý',
  'kr1': {'ko': '동의하다', 'zh': '同意', 'en': 'to agree', 'ja': '同意する', 'de': 'zustimmen', 'fr': 'être d’accord'},
  'vi2': 'chống đối',
  'kr2': {'ko': '반대하다',
          'zh': '反對',
          'en': 'to oppose',
          'ja': '反対する',
          'de': 'dagegen sein, widersprechen',
          'fr': 's’opposer'}},
 {'vi1': 'đủ',
  'kr1': {'ko': '충분한',
          'zh': '充分的',
          'en': 'sufficient',
          'ja': '十分な',
          'de': 'ausreichend, genug',
          'fr': 'suffisant, assez'},
  'vi2': 'kém',
  'kr2': {'ko': '부족한',
          'zh': '不足的，缺乏的',
          'en': 'insufficient',
          'ja': '不足した',
          'de': 'unzureichend',
          'fr': 'insuffisant, médiocre'}},
 {'vi1': 'đúng',
  'kr1': {'ko': '맞는', 'zh': '正確的', 'en': 'correct, right', 'ja': '正しい', 'de': 'richtig', 'fr': 'vrai, correct'},
  'vi2': 'sai',
  'kr2': {'ko': '틀린', 'zh': '錯的', 'en': 'wrong', 'ja': '間違った', 'de': 'falsch', 'fr': 'faux'}},
 {'vi1': 'ghét',
  'kr1': {'ko': '싫어하다',
          'zh': '討厭',
          'en': 'to dislike',
          'ja': '嫌う',
          'de': 'nicht mögen, hassen',
          'fr': 'ne pas aimer, détester'},
  'vi2': 'thích',
  'kr2': {'ko': '좋아하다', 'zh': '喜歡', 'en': 'to like', 'ja': '好む', 'de': 'mögen, gern haben', 'fr': 'aimer, apprécier'}},
 {'vi1': 'giả',
  'kr1': {'ko': '가짜', 'zh': '假的', 'en': 'fake', 'ja': '偽物', 'de': 'gefälscht, falsch', 'fr': 'faux, artificiel'},
  'vi2': 'thật',
  'kr2': {'ko': '진짜', 'zh': '真的', 'en': 'real', 'ja': '本物', 'de': 'echt, wahr', 'fr': 'vrai, réel'}},
 {'vi1': 'nhận',
  'kr1': {'ko': '받다', 'zh': '收，接受', 'en': 'to receive', 'ja': '受け取る', 'de': 'bekommen, empfangen', 'fr': 'recevoir'},
  'vi2': 'gửi',
  'kr2': {'ko': '보내다', 'zh': '送，寄', 'en': 'to send', 'ja': '送る', 'de': 'senden, schicken', 'fr': 'envoyer'}},
 {'vi1': 'hay, thú vị',
  'kr1': {'ko': '재미있다',
          'zh': '有趣',
          'en': 'fun',
          'ja': '面白い',
          'de': 'interessant, unterhaltsam',
          'fr': 'intéressant, amusant'},
  'vi2': 'dở, chán',
  'kr2': {'ko': '시시하다, 따분하다',
          'zh': '無聊，乏味',
          'en': 'boring, dull',
          'ja': 'つまらない、退屈だ',
          'de': 'langweilig',
          'fr': 'ennuyeux'}},
 {'vi1': 'hiền',
  'kr1': {'ko': '착한', 'zh': '善良的', 'en': 'kind', 'ja': '優しい', 'de': 'gut, freundlich', 'fr': 'doux, gentil'},
  'vi2': 'ác',
  'kr2': {'ko': '악한', 'zh': '邪惡的', 'en': 'evil, wicked', 'ja': '悪い', 'de': 'böse', 'fr': 'mauvais, méchant'}},
 {'vi1': 'hiện đại',
  'kr1': {'ko': '현대', 'zh': '現代', 'en': 'modern era', 'ja': '現代', 'de': 'modern, Neuzeit', 'fr': 'moderne'},
  'vi2': 'cổ đại',
  'kr2': {'ko': '고대', 'zh': '古代', 'en': 'ancient times', 'ja': '古代', 'de': 'antik, Antike', 'fr': 'antique, ancien'}},
 {'vi1': 'hiểu',
  'kr1': {'ko': '이해하다', 'zh': '理解', 'en': 'to understand', 'ja': '理解する', 'de': 'verstehen', 'fr': 'comprendre'},
  'vi2': 'không hiểu',
  'kr2': {'ko': '이해 못하다',
          'zh': '不理解',
          'en': 'to not understand',
          'ja': '理解できない',
          'de': 'nicht verstehen',
          'fr': 'ne pas comprendre'}},
 {'vi1': 'hoàn hảo',
  'kr1': {'ko': '완전한', 'zh': '完美的', 'en': 'perfect', 'ja': '完璧な', 'de': 'vollkommen', 'fr': 'parfait'},
  'vi2': 'bất toàn',
  'kr2': {'ko': '불완전한', 'zh': '不完全的', 'en': 'imperfect', 'ja': '不完全な', 'de': 'unvollkommen', 'fr': 'imparfait'}},
 {'vi1': 'học',
  'kr1': {'ko': '공부하다',
          'zh': '學習',
          'en': 'to study',
          'ja': '勉強する',
          'de': 'lernen, studieren',
          'fr': 'étudier, apprendre'},
  'vi2': 'chơi',
  'kr2': {'ko': '놀다', 'zh': '玩', 'en': 'to play', 'ja': '遊ぶ', 'de': 'spielen', 'fr': 'jouer'}},
 {'vi1': 'hỏi',
  'kr1': {'ko': '묻다', 'zh': '問', 'en': 'ask', 'ja': '尋ねる', 'de': 'fragen', 'fr': 'demander'},
  'vi2': 'trả lời',
  'kr2': {'ko': '대답하다', 'zh': '回答', 'en': 'answer', 'ja': '答える', 'de': 'antworten', 'fr': 'répondre'}},
 {'vi1': 'hôm qua',
  'kr1': {'ko': '어제', 'zh': '昨天', 'en': 'yesterday', 'ja': '昨日', 'de': 'gestern', 'fr': 'hier'},
  'vi2': 'ngày mai',
  'kr2': {'ko': '내일', 'zh': '明天', 'en': 'tomorrow', 'ja': '明日', 'de': 'morgen', 'fr': 'demain'}},
 {'vi1': 'hợp pháp',
  'kr1': {'ko': '합법적인', 'zh': '合法的', 'en': 'legal', 'ja': '合法的な', 'de': 'legal, rechtmäßig', 'fr': 'légal, légitime'},
  'vi2': 'bất hợp pháp',
  'kr2': {'ko': '불법의',
          'zh': '不合法的，非法的',
          'en': 'illegal',
          'ja': '不法の',
          'de': 'illegal, ungesetzlich',
          'fr': 'illégal, illégitime'}},
 {'vi1': 'khác (nhau)',
  'kr1': {'ko': '다른', 'zh': '不同的', 'en': 'different', 'ja': '違う', 'de': 'verschieden', 'fr': 'différent'},
  'vi2': 'giống (nhau)',
  'kr2': {'ko': '비슷한', 'zh': '相似的', 'en': 'similar', 'ja': '似ている', 'de': 'ähnlich, gleich', 'fr': 'semblable, pareil'}},
 {'vi1': 'khó',
  'kr1': {'ko': '어렵다', 'zh': '困難', 'en': 'to be difficult', 'ja': '難しい', 'de': 'schwer, schwierig', 'fr': 'difficile'},
  'vi2': 'dễ',
  'kr2': {'ko': '쉽다', 'zh': '容易', 'en': 'to be easy', 'ja': '易しい', 'de': 'leicht, einfach', 'fr': 'facile'}},
 {'vi1': 'lo lắng',
  'kr1': {'ko': '걱정하다', 'zh': '擔心', 'en': 'to worry', 'ja': '心配する', 'de': 'sich sorgen', 'fr': 's’inquiéter'},
  'vi2': 'an tâm',
  'kr2': {'ko': '안심하다',
          'zh': '安心',
          'en': 'to feel relieved',
          'ja': '安心する',
          'de': 'beruhigt sein',
          'fr': 'être rassuré'}},
 {'vi1': 'hữu ích',
  'kr1': {'ko': '유익한',
          'zh': '有益的',
          'en': 'beneficial',
          'ja': '有益な',
          'de': 'nützlich, heilsam',
          'fr': 'utile, bénéfique'},
  'vi2': 'có hại',
  'kr2': {'ko': '해로운', 'zh': '有害的', 'en': 'harmful', 'ja': '有害な', 'de': 'schädlich', 'fr': 'nuisible, nocif'}},
 {'vi1': 'lúc trước',
  'kr1': {'ko': '전에는', 'zh': '以前是', 'en': 'previously', 'ja': '以前は', 'de': 'früher', 'fr': 'auparavant, avant'},
  'vi2': 'sau này',
  'kr2': {'ko': '앞으로',
          'zh': '以後、向前',
          'en': 'in the future, forward',
          'ja': '今後、前へ',
          'de': 'später, in Zukunft',
          'fr': 'plus tard, à l’avenir'}},
 {'vi1': 'mạnh',
  'kr1': {'ko': '강한', 'zh': '強的', 'en': 'strong', 'ja': '強い', 'de': 'stark', 'fr': 'fort'},
  'vi2': 'yếu',
  'kr2': {'ko': '약한', 'zh': '虛弱的', 'en': 'weak', 'ja': '弱い', 'de': 'schwach', 'fr': 'faible'}},
 {'vi1': 'mới',
  'kr1': {'ko': '새로운', 'zh': '新的', 'en': 'new', 'ja': '新しい', 'de': 'neu', 'fr': 'nouveau'},
  'vi2': 'cũ',
  'kr2': {'ko': '헌', 'zh': '舊的', 'en': 'old/worn', 'ja': '古い', 'de': 'alt', 'fr': 'vieux, ancien'}},
 {'vi1': 'một số',
  'kr1': {'ko': '일부', 'zh': '一部分', 'en': 'part', 'ja': '一部', 'de': 'einige, Teil', 'fr': 'quelques-uns, une partie'},
  'vi2': 'tất cả, toàn bộ',
  'kr2': {'ko': '모두, 전부',
          'zh': '全部，全體',
          'en': 'all, entirely',
          'ja': 'すべて、全部',
          'de': 'alle, gesamt',
          'fr': 'tous, entier'}},
 {'vi1': 'mua',
  'kr1': {'ko': '사다', 'zh': '買', 'en': 'to buy', 'ja': '買う', 'de': 'kaufen', 'fr': 'acheter'},
  'vi2': 'bán',
  'kr2': {'ko': '팔다', 'zh': '賣', 'en': 'to sell', 'ja': '売る', 'de': 'verkaufen', 'fr': 'vendre'}},
 {'vi1': 'nặng',
  'kr1': {'ko': '무거운', 'zh': '重的', 'en': 'heavy', 'ja': '重い', 'de': 'schwer', 'fr': 'lourd'},
  'vi2': 'nhẹ',
  'kr2': {'ko': '가벼운', 'zh': '輕的', 'en': 'light (weight)', 'ja': '軽い', 'de': 'leicht', 'fr': 'léger'}},
 {'vi1': 'nóng',
  'kr1': {'ko': '뜨거운', 'zh': '熱的', 'en': 'hot', 'ja': '熱い', 'de': 'heiß', 'fr': 'chaud'},
  'vi2': 'lạnh',
  'kr2': {'ko': '찬', 'zh': '冷的', 'en': 'cold', 'ja': '冷たい', 'de': 'kalt', 'fr': 'froid'}},
 {'vi1': 'nữ',
  'kr1': {'ko': '여자', 'zh': '女生、女人', 'en': 'woman, girl', 'ja': '女性', 'de': 'weiblich, Frau', 'fr': 'femme, féminin'},
  'vi2': 'nam',
  'kr2': {'ko': '남자', 'zh': '男人', 'en': 'man', 'ja': '男性', 'de': 'männlich, Mann', 'fr': 'homme, masculin'}},
 {'vi1': 'nghèo',
  'kr1': {'ko': '가난하다', 'zh': '貧窮', 'en': 'to be poor', 'ja': '貧しい', 'de': 'arm', 'fr': 'pauvre'},
  'vi2': 'giàu có',
  'kr2': {'ko': '부유하다', 'zh': '富有', 'en': 'to be wealthy', 'ja': '裕福だ', 'de': 'reich, wohlhabend', 'fr': 'riche'}},
 {'vi1': 'nghỉ',
  'kr1': {'ko': '쉬다', 'zh': '休息', 'en': 'to rest', 'ja': '休む', 'de': 'sich ausruhen', 'fr': 'se reposer'},
  'vi2': 'làm',
  'kr2': {'ko': '일하다', 'zh': '工作', 'en': 'to work', 'ja': '働く', 'de': 'arbeiten', 'fr': 'travailler'}},
 {'vi1': 'ngồi',
  'kr1': {'ko': '앉다', 'zh': '坐', 'en': 'to sit', 'ja': '座る', 'de': 'sitzen', 'fr': 's’asseoir'},
  'vi2': 'đứng',
  'kr2': {'ko': '서다', 'zh': '站立', 'en': 'to stand', 'ja': '立つ', 'de': 'stehen', 'fr': 'se tenir debout'}},
 {'vi1': 'ngủ',
  'kr1': {'ko': '자다', 'zh': '睡覺', 'en': 'to sleep', 'ja': '寝る', 'de': 'schlafen', 'fr': 'dormir'},
  'vi2': 'dậy',
  'kr2': {'ko': '(잠에서) 깨다',
          'zh': '(從睡夢中)醒來',
          'en': 'to wake up (from sleep)',
          'ja': '(眠りから)覚める',
          'de': 'aufwachen',
          'fr': 'se réveiller'}},
 {'vi1': 'nguyên nhân',
  'kr1': {'ko': '원인', 'zh': '原因', 'en': 'cause', 'ja': '原因', 'de': 'Ursache', 'fr': 'cause, raison'},
  'vi2': 'kết quả',
  'kr2': {'ko': '결과', 'zh': '結果', 'en': 'result', 'ja': '結果', 'de': 'Ergebnis, Folge', 'fr': 'résultat, conséquence'}},
 {'vi1': 'nguy hiểm',
  'kr1': {'ko': '위험한', 'zh': '危險的', 'en': 'dangerous', 'ja': '危険な', 'de': 'gefährlich', 'fr': 'dangereux'},
  'vi2': 'an toàn',
  'kr2': {'ko': '안전한', 'zh': '安全的', 'en': 'safe', 'ja': '安全な', 'de': 'sicher', 'fr': 'sûr, en sécurité'}},
 {'vi1': 'nhiều',
  'kr1': {'ko': '많은', 'zh': '許多的', 'en': 'many', 'ja': '多い', 'de': 'viel', 'fr': 'beaucoup'},
  'vi2': 'ít',
  'kr2': {'ko': '적은', 'zh': '少的', 'en': 'few', 'ja': '少ない', 'de': 'wenig', 'fr': 'peu'}},
 {'vi1': 'nhỏ',
  'kr1': {'ko': '작은', 'zh': '小的', 'en': 'small', 'ja': '小さい', 'de': 'klein', 'fr': 'petit'},
  'vi2': 'to',
  'kr2': {'ko': '큰', 'zh': '大的', 'en': 'big', 'ja': '大きい', 'de': 'groß', 'fr': 'grand, gros'}},
 {'vi1': 'ồn',
  'kr1': {'ko': '시끄러운', 'zh': '吵鬧的', 'en': 'noisy', 'ja': 'うるさい', 'de': 'laut', 'fr': 'bruyant'},
  'vi2': 'im lặng',
  'kr2': {'ko': '조용한', 'zh': '安靜的', 'en': 'quiet', 'ja': '静かな', 'de': 'leise, still', 'fr': 'silencieux, calme'}},
 {'vi1': 'phát triển',
  'kr1': {'ko': '발전', 'zh': '發展', 'en': 'development', 'ja': '発展', 'de': 'Entwicklung', 'fr': 'développement'},
  'vi2': 'suy thoái',
  'kr2': {'ko': '쇠퇴', 'zh': '衰退', 'en': 'decline', 'ja': '衰退', 'de': 'Rückgang, Verfall', 'fr': 'déclin, régression'}},
 {'vi1': 'quá khứ',
  'kr1': {'ko': '과거', 'zh': '過去', 'en': 'the past', 'ja': '過去', 'de': 'Vergangenheit', 'fr': 'passé'},
  'vi2': 'tương lai',
  'kr2': {'ko': '미래', 'zh': '未來', 'en': 'future', 'ja': '未来', 'de': 'Zukunft', 'fr': 'avenir, futur'}},
 {'vi1': 'sáng',
  'kr1': {'ko': '밝은', 'zh': '明亮的', 'en': 'bright', 'ja': '明るい', 'de': 'hell', 'fr': 'clair, lumineux'},
  'vi2': 'tối',
  'kr2': {'ko': '어두운', 'zh': '黑暗的', 'en': 'dark', 'ja': '暗い', 'de': 'dunkel', 'fr': 'sombre'}},
 {'vi1': 'sắc',
  'kr1': {'ko': '날카로운', 'zh': '尖銳的', 'en': 'sharp', 'ja': '鋭い', 'de': 'scharf', 'fr': 'aiguisé, tranchant'},
  'vi2': 'cùn',
  'kr2': {'ko': '무딘', 'zh': '鈍的', 'en': 'dull, blunt', 'ja': '鈍い', 'de': 'stumpf', 'fr': 'émoussé'}},
 {'vi1': 'sạch sẽ',
  'kr1': {'ko': '깨끗한', 'zh': '乾淨的', 'en': 'clean', 'ja': '清潔な', 'de': 'sauber', 'fr': 'propre'},
  'vi2': 'bẩn',
  'kr2': {'ko': '더러운', 'zh': '骯髒的', 'en': 'dirty', 'ja': '汚い', 'de': 'schmutzig', 'fr': 'sale'}},
 {'vi1': 'sâu',
  'kr1': {'ko': '깊은', 'zh': '深的', 'en': 'deep', 'ja': '深い', 'de': 'tief', 'fr': 'profond'},
  'vi2': 'cạn',
  'kr2': {'ko': '얕은', 'zh': '淺的', 'en': 'shallow', 'ja': '浅い', 'de': 'seicht, flach', 'fr': 'peu profond'}},
 {'vi1': 'siêng năng',
  'kr1': {'ko': '부지런한', 'zh': '勤勞的，勤奮的', 'en': 'diligent', 'ja': '勤勉な', 'de': 'fleißig', 'fr': 'diligent, travailleur'},
  'vi2': 'lười',
  'kr2': {'ko': '게으른', 'zh': '懶惰的', 'en': 'lazy', 'ja': '怠惰な', 'de': 'faul', 'fr': 'paresseux'}},
 {'vi1': 'sinh viên',
  'kr1': {'ko': '학생', 'zh': '學生', 'en': 'student', 'ja': '学生', 'de': 'Student', 'fr': 'étudiant'},
  'vi2': 'giáo viên',
  'kr2': {'ko': '교원',
          'zh': '教員',
          'en': 'teacher, faculty',
          'ja': '教員',
          'de': 'Lehrer',
          'fr': 'enseignant, professeur'}},
 {'vi1': 'sớm',
  'kr1': {'ko': '일찍', 'zh': '早', 'en': 'early', 'ja': '早く', 'de': 'früh', 'fr': 'tôt'},
  'vi2': 'muộn = trễ',
  'kr2': {'ko': '늦게', 'zh': '晚地', 'en': 'late', 'ja': '遅く', 'de': 'spät', 'fr': 'tard'}},
 {'vi1': 'thành công',
  'kr1': {'ko': '성공', 'zh': '成功', 'en': 'success', 'ja': '成功', 'de': 'Erfolg', 'fr': 'succès, réussite'},
  'vi2': 'thất bại',
  'kr2': {'ko': '실패', 'zh': '失敗', 'en': 'failure', 'ja': '失敗', 'de': 'Misserfolg', 'fr': 'échec'}},
 {'vi1': 'thầy giáo',
  'kr1': {'ko': '남자 선생', 'zh': '男老師', 'en': 'male teacher', 'ja': '男の先生', 'de': 'Lehrer', 'fr': 'professeur (homme)'},
  'vi2': 'cô giáo',
  'kr2': {'ko': '여선생',
          'zh': '女老師',
          'en': 'female teacher',
          'ja': '女性教師',
          'de': 'Lehrerin',
          'fr': 'professeure (femme)'}},
 {'vi1': 'thích',
  'kr1': {'ko': '좋아하다', 'zh': '喜歡', 'en': 'to like', 'ja': '好む', 'de': 'mögen', 'fr': 'aimer, apprécier'},
  'vi2': 'ghét',
  'kr2': {'ko': '미워하다', 'zh': '討厭・恨', 'en': 'hate', 'ja': '憎む', 'de': 'hassen', 'fr': 'détester, haïr'}},
 {'vi1': 'muốn',
  'kr1': {'ko': '원하다', 'zh': '想要', 'en': 'to want', 'ja': '望む', 'de': 'wollen', 'fr': 'vouloir'},
  'vi2': 'không muốn',
  'kr2': {'ko': '원치 않다', 'zh': '不想要', 'en': 'to not want', 'ja': '望まない', 'de': 'nicht wollen', 'fr': 'ne pas vouloir'}},
 {'vi1': 'thuốc tây',
  'kr1': {'ko': '양약',
          'zh': '西藥',
          'en': 'Western medicine',
          'ja': '西洋薬',
          'de': 'westliche Medizin',
          'fr': 'médecine occidentale'},
  'vi2': 'thuốc bắc',
  'kr2': {'ko': '한약',
          'zh': '中藥',
          'en': 'herbal medicine',
          'ja': '漢方薬',
          'de': 'traditionelle Medizin',
          'fr': 'médecine traditionnelle'}},
 {'vi1': 'tiễn',
  'kr1': {'ko': '배웅하다',
          'zh': '送行',
          'en': 'to see off',
          'ja': '見送る',
          'de': 'verabschieden',
          'fr': 'raccompagner, dire au revoir'},
  'vi2': 'đón',
  'kr2': {'ko': '마중하다',
          'zh': '迎接',
          'en': 'go to meet, welcome',
          'ja': '出迎える',
          'de': 'abholen, empfangen',
          'fr': 'accueillir, aller chercher'}},
 {'vi1': 'tiện',
  'kr1': {'ko': '편한',
          'zh': '舒服的',
          'en': 'comfortable',
          'ja': '楽な',
          'de': 'praktisch, bequem',
          'fr': 'pratique, commode'},
  'vi2': 'bất tiện',
  'kr2': {'ko': '불편한',
          'zh': '不方便的，不舒服的',
          'en': 'uncomfortable; inconvenient',
          'ja': '不便な',
          'de': 'unpraktisch, unbequem',
          'fr': 'incommode, peu pratique'}},
 {'vi1': 'tốt',
  'kr1': {'ko': '좋은', 'zh': '好的', 'en': 'good', 'ja': '良い', 'de': 'gut', 'fr': 'bon'},
  'vi2': 'xấu',
  'kr2': {'ko': '나쁜', 'zh': '壞的', 'en': 'bad', 'ja': '悪い', 'de': 'schlecht', 'fr': 'mauvais'}},
 {'vi1': 'thịt',
  'kr1': {'ko': '고기', 'zh': '肉', 'en': 'meat', 'ja': '肉', 'de': 'Fleisch', 'fr': 'viande'},
  'vi2': 'rau',
  'kr2': {'ko': '야채', 'zh': '蔬菜', 'en': 'vegetable', 'ja': '野菜', 'de': 'Gemüse', 'fr': 'légume'}},
 {'vi1': 'trắng',
  'kr1': {'ko': '하얀', 'zh': '白色的', 'en': 'white', 'ja': '白い', 'de': 'weiß', 'fr': 'blanc'},
  'vi2': 'đen',
  'kr2': {'ko': '검은', 'zh': '黑色的', 'en': 'black', 'ja': '黒い', 'de': 'schwarz', 'fr': 'noir'}},
 {'vi1': 'trẻ',
  'kr1': {'ko': '젊은', 'zh': '年輕的', 'en': 'young', 'ja': '若い', 'de': 'jung', 'fr': 'jeune'},
  'vi2': 'già',
  'kr2': {'ko': '늙은', 'zh': '年老的', 'en': 'old (aged)', 'ja': '老いた', 'de': 'alt', 'fr': 'vieux, âgé'}},
 {'vi1': 'trên',
  'kr1': {'ko': '위', 'zh': '上面', 'en': 'above/top', 'ja': '上', 'de': 'oben, auf', 'fr': 'sur, au-dessus'},
  'vi2': 'dưới',
  'kr2': {'ko': '아래', 'zh': '下面', 'en': 'below, under', 'ja': '下', 'de': 'unten, unter', 'fr': 'sous, au-dessous'}},
 {'vi1': 'trong',
  'kr1': {'ko': '안에', 'zh': '裡面', 'en': 'inside', 'ja': '中に', 'de': 'drinnen, in', 'fr': 'dans, à l’intérieur'},
  'vi2': 'ngoài',
  'kr2': {'ko': '밖에',
          'zh': '外面',
          'en': 'outside',
          'ja': '外に',
          'de': 'draußen, außerhalb',
          'fr': 'dehors, à l’extérieur'}},
 {'vi1': 'trước khi~',
  'kr1': {'ko': '~하기 전에', 'zh': '在~之前', 'en': 'before ~ing', 'ja': '~する前に', 'de': 'bevor ~', 'fr': 'avant de ~'},
  'vi2': 'sau khi~',
  'kr2': {'ko': '~한 후에', 'zh': '~之後', 'en': 'after ~ing', 'ja': '~した後に', 'de': 'nachdem ~', 'fr': 'après avoir ~'}},
 {'vi1': 'và',
  'kr1': {'ko': '그리고', 'zh': '而且', 'en': 'and', 'ja': 'そして', 'de': 'und', 'fr': 'et'},
  'vi2': 'nhưng mà',
  'kr2': {'ko': '그러나', 'zh': '但是', 'en': 'but, however', 'ja': 'しかし', 'de': 'aber, jedoch', 'fr': 'mais, cependant'}},
 {'vi1': 'vào',
  'kr1': {'ko': '들어가다', 'zh': '進去', 'en': 'enter', 'ja': '入る', 'de': 'hineingehen', 'fr': 'entrer'},
  'vi2': 'ra',
  'kr2': {'ko': '나오다', 'zh': '出來', 'en': 'come out', 'ja': '出てくる', 'de': 'hinausgehen', 'fr': 'sortir'}},
 {'vi1': 'về nước',
  'kr1': {'ko': '귀국하다',
          'zh': '回國',
          'en': "to return to one's country",
          'ja': '帰国する',
          'de': 'ins Heimatland zurückkehren',
          'fr': 'retourner dans son pays'},
  'vi2': 'xuất cảnh',
  'kr2': {'ko': '출국하다',
          'zh': '出國',
          'en': 'to leave the country',
          'ja': '出国する',
          'de': 'ausreisen',
          'fr': 'quitter le pays'}},
 {'vi1': 'vui mừng',
  'kr1': {'ko': '기쁜', 'zh': '高興的', 'en': 'glad, happy', 'ja': 'うれしい', 'de': 'froh, glücklich', 'fr': 'joyeux, content'},
  'vi2': 'buồn',
  'kr2': {'ko': '슬픈', 'zh': '悲傷的', 'en': 'sad', 'ja': '悲しい', 'de': 'traurig', 'fr': 'triste'}},
 {'vi1': 'xa',
  'kr1': {'ko': '먼', 'zh': '遠的', 'en': 'far', 'ja': '遠い', 'de': 'weit, fern', 'fr': 'loin'},
  'vi2': 'gần',
  'kr2': {'ko': '가까운', 'zh': '近的', 'en': 'near', 'ja': '近い', 'de': 'nah', 'fr': 'près, proche'}},
 {'vi1': 'xuất khẩu',
  'kr1': {'ko': '수출', 'zh': '出口', 'en': 'export', 'ja': '輸出', 'de': 'Export', 'fr': 'exportation'},
  'vi2': 'nhập khẩu',
  'kr2': {'ko': '수입', 'zh': '收入', 'en': 'income', 'ja': '収入', 'de': 'Import', 'fr': 'importation'}},
 {'vi1': 'xuất phát',
  'kr1': {'ko': '출발', 'zh': '出發', 'en': 'departure', 'ja': '出発', 'de': 'Abreise, Abfahrt', 'fr': 'départ'},
  'vi2': 'đến nơi',
  'kr2': {'ko': '도착', 'zh': '到達', 'en': 'arrival', 'ja': '到着', 'de': 'Ankunft', 'fr': 'arrivée'}},
 {'vi1': 'xuống',
  'kr1': {'ko': '내려가다', 'zh': '下去', 'en': 'go down', 'ja': '下がる', 'de': 'hinuntergehen', 'fr': 'descendre'},
  'vi2': 'lên',
  'kr2': {'ko': '올라가다', 'zh': '上去', 'en': 'to go up', 'ja': '上がる', 'de': 'hinaufgehen', 'fr': 'monter'}}]
