# "교과 > 기본 단어·반의어" subtab -- 반의어 (antonym pairs), 99 entries,
# transcribed verbatim from pages 97-98 ("반대어") of the course booklet, with a
# few hand-corrections to the Vietnamese word choice/Korean gloss on some pairs
# (and one duplicate near-synonym pair, lọ/chai, removed).
# (모든 대화를 구성하는 기본 단어 glossary lives in basic_words_list.py.)
#
# "kr1"/"kr2" are stored as {"ko","zh","en","ja"} dicts so js_json() (see build_app.py)
# serializes them straight into JS objects app_logic.js's T() helper can read directly.

ANTONYM_PAIRS = [{'vi1': 'ăn',
  'kr1': {'ko': '먹다', 'zh': '吃', 'en': 'eat', 'ja': '食べる'},
  'vi2': 'uống',
  'kr2': {'ko': '마시다', 'zh': '喝', 'en': 'drink', 'ja': '飲む'}},
 {'vi1': 'ba',
  'kr1': {'ko': '아빠', 'zh': '爸爸', 'en': 'dad', 'ja': 'パパ'},
  'vi2': 'má',
  'kr2': {'ko': '엄마', 'zh': '媽媽', 'en': 'mom', 'ja': 'ママ'}},
 {'vi1': 'bán',
  'kr1': {'ko': '팔다', 'zh': '賣', 'en': 'to sell', 'ja': '売る'},
  'vi2': 'mua',
  'kr2': {'ko': '사다', 'zh': '買', 'en': 'to buy', 'ja': '買う'}},
 {'vi1': 'bận',
  'kr1': {'ko': '바쁜', 'zh': '忙碌的', 'en': 'busy', 'ja': '忙しい'},
  'vi2': 'rảnh rỗi',
  'kr2': {'ko': '한가한', 'zh': '空閒的', 'en': 'free, available', 'ja': '暇な'}},
 {'vi1': 'bắt đầu',
  'kr1': {'ko': '시작하다', 'zh': '開始', 'en': 'to start', 'ja': '始める'},
  'vi2': 'kết thúc',
  'kr2': {'ko': '끝나다', 'zh': '結束', 'en': 'end', 'ja': '終わる'}},
 {'vi1': 'bên trái',
  'kr1': {'ko': '왼쪽', 'zh': '左邊', 'en': 'left', 'ja': '左'},
  'vi2': 'bên phải',
  'kr2': {'ko': '오른쪽', 'zh': '右邊', 'en': 'right', 'ja': '右'}},
 {'vi1': 'béo, mập',
  'kr1': {'ko': '뚱뚱한', 'zh': '胖的', 'en': 'fat', 'ja': '太った'},
  'vi2': 'gầy, ốm',
  'kr2': {'ko': '마른', 'zh': '瘦的', 'en': 'thin', 'ja': '痩せた'}},
 {'vi1': 'cao',
  'kr1': {'ko': '높은', 'zh': '高的', 'en': 'high', 'ja': '高い'},
  'vi2': 'thấp',
  'kr2': {'ko': '낮은', 'zh': '低的', 'en': 'low', 'ja': '低い'}},
 {'vi1': '(cái) bàn',
  'kr1': {'ko': '책상', 'zh': '書桌', 'en': 'desk', 'ja': '机'},
  'vi2': '(cái) ghế',
  'kr2': {'ko': '의자', 'zh': '椅子', 'en': 'chair', 'ja': '椅子'}},
 {'vi1': '(cái) này',
  'kr1': {'ko': '이(것)', 'zh': '這(個)', 'en': 'this (thing)', 'ja': 'これ'},
  'vi2': '(cái) kia',
  'kr2': {'ko': '저(것)', 'zh': '那（個）', 'en': 'that', 'ja': 'あれ'}},
 {'vi1': 'cần thiết',
  'kr1': {'ko': '필요한', 'zh': '必要的', 'en': 'necessary', 'ja': '必要な'},
  'vi2': 'không cần thiết',
  'kr2': {'ko': '불필요한', 'zh': '不必要的', 'en': 'unnecessary', 'ja': '不必要な'}},
 {'vi1': 'chậm',
  'kr1': {'ko': '천천히', 'zh': '慢慢地', 'en': 'slowly', 'ja': 'ゆっくり'},
  'vi2': 'nhanh',
  'kr2': {'ko': '빨리', 'zh': '快點，迅速地', 'en': 'quickly', 'ja': '速く'}},
 {'vi1': 'chật',
  'kr1': {'ko': '좁은', 'zh': '狹窄的', 'en': 'narrow', 'ja': '狭い'},
  'vi2': 'rộng',
  'kr2': {'ko': '넓은', 'zh': '寬闊的', 'en': 'wide', 'ja': '広い'}},
 {'vi1': 'chết',
  'kr1': {'ko': '죽다', 'zh': '死', 'en': 'to die', 'ja': '死ぬ'},
  'vi2': 'sống',
  'kr2': {'ko': '살다', 'zh': '生活·居住', 'en': 'to live', 'ja': '住む·生きる'}},
 {'vi1': 'cho phép',
  'kr1': {'ko': '허락하다', 'zh': '允許', 'en': 'to allow', 'ja': '許可する'},
  'vi2': 'cấm',
  'kr2': {'ko': '금지하다', 'zh': '禁止', 'en': 'to prohibit', 'ja': '禁止する'}},
 {'vi1': 'cho thấy',
  'kr1': {'ko': '보여주다', 'zh': '給…看，展示', 'en': 'to show', 'ja': '見せる'},
  'vi2': 'cho biết',
  'kr2': {'ko': '알려주다', 'zh': '告訴', 'en': 'to let know, inform', 'ja': '知らせる'}},
 {'vi1': 'chưa',
  'kr1': {'ko': '아직', 'zh': '還、仍然', 'en': 'still, yet', 'ja': 'まだ'},
  'vi2': 'rồi',
  'kr2': {'ko': '이미', 'zh': '已經', 'en': 'already', 'ja': 'すでに'}},
 {'vi1': 'có',
  'kr1': {'ko': '있다', 'zh': '有·存在', 'en': 'to exist/have', 'ja': 'ある・いる'},
  'vi2': 'không có',
  'kr2': {'ko': '없다', 'zh': '沒有', 'en': 'to not exist, not have', 'ja': 'ない'}},
 {'vi1': 'cố gắng',
  'kr1': {'ko': '노력하다', 'zh': '努力', 'en': 'make an effort', 'ja': '努力する'},
  'vi2': 'từ bỏ',
  'kr2': {'ko': '포기하다', 'zh': '放棄', 'en': 'to give up', 'ja': '諦める'}},
 {'vi1': 'có thể',
  'kr1': {'ko': '할 수 있다', 'zh': '能夠', 'en': 'can', 'ja': 'できる'},
  'vi2': 'không thể',
  'kr2': {'ko': '할 수 없다', 'zh': '不能', 'en': 'cannot', 'ja': 'できない'}},
 {'vi1': 'cười',
  'kr1': {'ko': '웃다', 'zh': '笑', 'en': 'to laugh', 'ja': '笑う'},
  'vi2': 'khóc',
  'kr2': {'ko': '울다', 'zh': '哭', 'en': 'to cry', 'ja': '泣く'}},
 {'vi1': 'dài',
  'kr1': {'ko': '긴', 'zh': '長的', 'en': 'long', 'ja': '長い'},
  'vi2': 'ngắn',
  'kr2': {'ko': '짧은', 'zh': '短的', 'en': 'short', 'ja': '短い'}},
 {'vi1': 'đắt, mắc',
  'kr1': {'ko': '비싼', 'zh': '昂貴的', 'en': 'expensive', 'ja': '高価な'},
  'vi2': 'rẻ',
  'kr2': {'ko': '싼', 'zh': '便宜的', 'en': 'cheap', 'ja': '安い'}},
 {'vi1': 'dày',
  'kr1': {'ko': '두꺼운', 'zh': '厚的', 'en': 'thick', 'ja': '厚い'},
  'vi2': 'mỏng',
  'kr2': {'ko': '얇은', 'zh': '薄的', 'en': 'thin', 'ja': '薄い'}},
 {'vi1': 'dậy',
  'kr1': {'ko': '깨다', 'zh': '醒來', 'en': 'to wake up', 'ja': '目覚める'},
  'vi2': 'ngủ',
  'kr2': {'ko': '자다', 'zh': '睡覺', 'en': 'to sleep', 'ja': '寝る'}},
 {'vi1': 'đặc biệt',
  'kr1': {'ko': '특별한', 'zh': '特別的', 'en': 'special', 'ja': '特別な'},
  'vi2': 'bình thường',
  'kr2': {'ko': '평범한', 'zh': '平凡的', 'en': 'ordinary', 'ja': '平凡な'}},
 {'vi1': 'đẹp',
  'kr1': {'ko': '아름다운', 'zh': '美麗的', 'en': 'beautiful', 'ja': '美しい'},
  'vi2': 'xấu',
  'kr2': {'ko': '추한', 'zh': '醜陋的', 'en': 'ugly', 'ja': '醜い'}},
 {'vi1': 'đi',
  'kr1': {'ko': '가다', 'zh': '去', 'en': 'to go', 'ja': '行く'},
  'vi2': 'đến',
  'kr2': {'ko': '오다', 'zh': '來', 'en': 'to come', 'ja': '来る'}},
 {'vi1': 'đi bộ',
  'kr1': {'ko': '걷다', 'zh': '走路', 'en': 'to walk', 'ja': '歩く'},
  'vi2': 'chạy',
  'kr2': {'ko': '뛰다', 'zh': '跑・跳', 'en': 'run, jump', 'ja': '走る・跳ぶ'}},
 {'vi1': 'địa đàng',
  'kr1': {'ko': '낙원', 'zh': '樂園', 'en': 'paradise', 'ja': '楽園'},
  'vi2': 'địa ngục',
  'kr2': {'ko': '지옥', 'zh': '地獄', 'en': 'hell', 'ja': '地獄'}},
 {'vi1': 'đọc',
  'kr1': {'ko': '읽다', 'zh': '讀', 'en': 'to read', 'ja': '読む'},
  'vi2': 'nghe',
  'kr2': {'ko': '듣다', 'zh': '聽', 'en': 'listen', 'ja': '聞く'}},
 {'vi1': 'đóng',
  'kr1': {'ko': '닫다', 'zh': '關閉', 'en': 'close', 'ja': '閉める'},
  'vi2': 'mở',
  'kr2': {'ko': '열다', 'zh': '打開', 'en': 'to open', 'ja': '開ける'}},
 {'vi1': 'đồng ý',
  'kr1': {'ko': '동의하다', 'zh': '同意', 'en': 'to agree', 'ja': '同意する'},
  'vi2': 'chống đối',
  'kr2': {'ko': '반대하다', 'zh': '反對', 'en': 'to oppose', 'ja': '反対する'}},
 {'vi1': 'đủ',
  'kr1': {'ko': '충분한', 'zh': '充分的', 'en': 'sufficient', 'ja': '十分な'},
  'vi2': 'kém',
  'kr2': {'ko': '부족한', 'zh': '不足的，缺乏的', 'en': 'insufficient', 'ja': '不足した'}},
 {'vi1': 'đúng',
  'kr1': {'ko': '맞는', 'zh': '正確的', 'en': 'correct, right', 'ja': '正しい'},
  'vi2': 'sai',
  'kr2': {'ko': '틀린', 'zh': '錯的', 'en': 'wrong', 'ja': '間違った'}},
 {'vi1': 'ghét',
  'kr1': {'ko': '싫어하다', 'zh': '討厭', 'en': 'to dislike', 'ja': '嫌う'},
  'vi2': 'thích',
  'kr2': {'ko': '좋아하다', 'zh': '喜歡', 'en': 'to like', 'ja': '好む'}},
 {'vi1': 'giả',
  'kr1': {'ko': '가짜', 'zh': '假的', 'en': 'fake', 'ja': '偽物'},
  'vi2': 'thật',
  'kr2': {'ko': '진짜', 'zh': '真的', 'en': 'real', 'ja': '本物'}},
 {'vi1': 'nhận',
  'kr1': {'ko': '받다', 'zh': '收，接受', 'en': 'to receive', 'ja': '受け取る'},
  'vi2': 'gửi',
  'kr2': {'ko': '보내다', 'zh': '送，寄', 'en': 'to send', 'ja': '送る'}},
 {'vi1': 'hay, thú vị',
  'kr1': {'ko': '재미있다', 'zh': '有趣', 'en': 'fun', 'ja': '面白い'},
  'vi2': 'dở, chán',
  'kr2': {'ko': '시시하다, 따분하다', 'zh': '無聊，乏味', 'en': 'boring, dull', 'ja': 'つまらない、退屈だ'}},
 {'vi1': 'hiền',
  'kr1': {'ko': '착한', 'zh': '善良的', 'en': 'kind', 'ja': '優しい'},
  'vi2': 'ác',
  'kr2': {'ko': '악한', 'zh': '邪惡的', 'en': 'evil, wicked', 'ja': '悪い'}},
 {'vi1': 'hiện đại',
  'kr1': {'ko': '현대', 'zh': '現代', 'en': 'modern era', 'ja': '現代'},
  'vi2': 'cổ đại',
  'kr2': {'ko': '고대', 'zh': '古代', 'en': 'ancient times', 'ja': '古代'}},
 {'vi1': 'hiểu',
  'kr1': {'ko': '이해하다', 'zh': '理解', 'en': 'to understand', 'ja': '理解する'},
  'vi2': 'không hiểu',
  'kr2': {'ko': '이해 못하다', 'zh': '不理解', 'en': 'to not understand', 'ja': '理解できない'}},
 {'vi1': 'hoàn hảo',
  'kr1': {'ko': '완전한', 'zh': '完美的', 'en': 'perfect', 'ja': '完璧な'},
  'vi2': 'bất toàn',
  'kr2': {'ko': '불완전한', 'zh': '不完全的', 'en': 'imperfect', 'ja': '不完全な'}},
 {'vi1': 'học',
  'kr1': {'ko': '공부하다', 'zh': '學習', 'en': 'to study', 'ja': '勉強する'},
  'vi2': 'chơi',
  'kr2': {'ko': '놀다', 'zh': '玩', 'en': 'to play', 'ja': '遊ぶ'}},
 {'vi1': 'hỏi',
  'kr1': {'ko': '묻다', 'zh': '問', 'en': 'ask', 'ja': '尋ねる'},
  'vi2': 'trả lời',
  'kr2': {'ko': '대답하다', 'zh': '回答', 'en': 'answer', 'ja': '答える'}},
 {'vi1': 'hôm qua',
  'kr1': {'ko': '어제', 'zh': '昨天', 'en': 'yesterday', 'ja': '昨日'},
  'vi2': 'ngày mai',
  'kr2': {'ko': '내일', 'zh': '明天', 'en': 'tomorrow', 'ja': '明日'}},
 {'vi1': 'hợp pháp',
  'kr1': {'ko': '합법적인', 'zh': '合法的', 'en': 'legal', 'ja': '合法的な'},
  'vi2': 'bất hợp pháp',
  'kr2': {'ko': '불법의', 'zh': '不合法的，非法的', 'en': 'illegal', 'ja': '不法の'}},
 {'vi1': 'khác (nhau)',
  'kr1': {'ko': '다른', 'zh': '不同的', 'en': 'different', 'ja': '違う'},
  'vi2': 'giống (nhau)',
  'kr2': {'ko': '비슷한', 'zh': '相似的', 'en': 'similar', 'ja': '似ている'}},
 {'vi1': 'khó',
  'kr1': {'ko': '어렵다', 'zh': '困難', 'en': 'to be difficult', 'ja': '難しい'},
  'vi2': 'dễ',
  'kr2': {'ko': '쉽다', 'zh': '容易', 'en': 'to be easy', 'ja': '易しい'}},
 {'vi1': 'lo lắng',
  'kr1': {'ko': '걱정하다', 'zh': '擔心', 'en': 'to worry', 'ja': '心配する'},
  'vi2': 'an tâm',
  'kr2': {'ko': '안심하다', 'zh': '安心', 'en': 'to feel relieved', 'ja': '安心する'}},
 {'vi1': 'hữu ích',
  'kr1': {'ko': '유익한', 'zh': '有益的', 'en': 'beneficial', 'ja': '有益な'},
  'vi2': 'có hại',
  'kr2': {'ko': '해로운', 'zh': '有害的', 'en': 'harmful', 'ja': '有害な'}},
 {'vi1': 'lúc trước',
  'kr1': {'ko': '전에는', 'zh': '以前是', 'en': 'previously', 'ja': '以前は'},
  'vi2': 'sau này',
  'kr2': {'ko': '앞으로', 'zh': '以後、向前', 'en': 'in the future, forward', 'ja': '今後、前へ'}},
 {'vi1': 'mạnh',
  'kr1': {'ko': '강한', 'zh': '強的', 'en': 'strong', 'ja': '強い'},
  'vi2': 'yếu',
  'kr2': {'ko': '약한', 'zh': '虛弱的', 'en': 'weak', 'ja': '弱い'}},
 {'vi1': 'mới',
  'kr1': {'ko': '새로운', 'zh': '新的', 'en': 'new', 'ja': '新しい'},
  'vi2': 'cũ',
  'kr2': {'ko': '헌', 'zh': '舊的', 'en': 'old/worn', 'ja': '古い'}},
 {'vi1': 'một số',
  'kr1': {'ko': '일부', 'zh': '一部分', 'en': 'part', 'ja': '一部'},
  'vi2': 'tất cả, toàn bộ',
  'kr2': {'ko': '모두, 전부', 'zh': '全部，全體', 'en': 'all, entirely', 'ja': 'すべて、全部'}},
 {'vi1': 'mua',
  'kr1': {'ko': '사다', 'zh': '買', 'en': 'to buy', 'ja': '買う'},
  'vi2': 'bán',
  'kr2': {'ko': '팔다', 'zh': '賣', 'en': 'to sell', 'ja': '売る'}},
 {'vi1': 'nặng',
  'kr1': {'ko': '무거운', 'zh': '重的', 'en': 'heavy', 'ja': '重い'},
  'vi2': 'nhẹ',
  'kr2': {'ko': '가벼운', 'zh': '輕的', 'en': 'light (weight)', 'ja': '軽い'}},
 {'vi1': 'nóng',
  'kr1': {'ko': '뜨거운', 'zh': '熱的', 'en': 'hot', 'ja': '熱い'},
  'vi2': 'lạnh',
  'kr2': {'ko': '찬', 'zh': '冷的', 'en': 'cold', 'ja': '冷たい'}},
 {'vi1': 'nữ',
  'kr1': {'ko': '여자', 'zh': '女生、女人', 'en': 'woman, girl', 'ja': '女性'},
  'vi2': 'nam',
  'kr2': {'ko': '남자', 'zh': '男人', 'en': 'man', 'ja': '男性'}},
 {'vi1': 'nghèo',
  'kr1': {'ko': '가난하다', 'zh': '貧窮', 'en': 'to be poor', 'ja': '貧しい'},
  'vi2': 'giàu có',
  'kr2': {'ko': '부유하다', 'zh': '富有', 'en': 'to be wealthy', 'ja': '裕福だ'}},
 {'vi1': 'nghỉ',
  'kr1': {'ko': '쉬다', 'zh': '休息', 'en': 'to rest', 'ja': '休む'},
  'vi2': 'làm',
  'kr2': {'ko': '일하다', 'zh': '工作', 'en': 'to work', 'ja': '働く'}},
 {'vi1': 'ngồi',
  'kr1': {'ko': '앉다', 'zh': '坐', 'en': 'to sit', 'ja': '座る'},
  'vi2': 'đứng',
  'kr2': {'ko': '서다', 'zh': '站立', 'en': 'to stand', 'ja': '立つ'}},
 {'vi1': 'ngủ',
  'kr1': {'ko': '자다', 'zh': '睡覺', 'en': 'to sleep', 'ja': '寝る'},
  'vi2': 'dậy',
  'kr2': {'ko': '(잠에서) 깨다', 'zh': '(從睡夢中)醒來', 'en': 'to wake up (from sleep)', 'ja': '(眠りから)覚める'}},
 {'vi1': 'nguyên nhân',
  'kr1': {'ko': '원인', 'zh': '原因', 'en': 'cause', 'ja': '原因'},
  'vi2': 'kết quả',
  'kr2': {'ko': '결과', 'zh': '結果', 'en': 'result', 'ja': '結果'}},
 {'vi1': 'nguy hiểm',
  'kr1': {'ko': '위험한', 'zh': '危險的', 'en': 'dangerous', 'ja': '危険な'},
  'vi2': 'an toàn',
  'kr2': {'ko': '안전한', 'zh': '安全的', 'en': 'safe', 'ja': '安全な'}},
 {'vi1': 'nhiều',
  'kr1': {'ko': '많은', 'zh': '許多的', 'en': 'many', 'ja': '多い'},
  'vi2': 'ít',
  'kr2': {'ko': '적은', 'zh': '少的', 'en': 'few', 'ja': '少ない'}},
 {'vi1': 'nhỏ',
  'kr1': {'ko': '작은', 'zh': '小的', 'en': 'small', 'ja': '小さい'},
  'vi2': 'to',
  'kr2': {'ko': '큰', 'zh': '大的', 'en': 'big', 'ja': '大きい'}},
 {'vi1': 'ồn',
  'kr1': {'ko': '시끄러운', 'zh': '吵鬧的', 'en': 'noisy', 'ja': 'うるさい'},
  'vi2': 'im lặng',
  'kr2': {'ko': '조용한', 'zh': '安靜的', 'en': 'quiet', 'ja': '静かな'}},
 {'vi1': 'phát triển',
  'kr1': {'ko': '발전', 'zh': '發展', 'en': 'development', 'ja': '発展'},
  'vi2': 'suy thoái',
  'kr2': {'ko': '쇠퇴', 'zh': '衰退', 'en': 'decline', 'ja': '衰退'}},
 {'vi1': 'quá khứ',
  'kr1': {'ko': '과거', 'zh': '過去', 'en': 'the past', 'ja': '過去'},
  'vi2': 'tương lai',
  'kr2': {'ko': '미래', 'zh': '未來', 'en': 'future', 'ja': '未来'}},
 {'vi1': 'sáng',
  'kr1': {'ko': '밝은', 'zh': '明亮的', 'en': 'bright', 'ja': '明るい'},
  'vi2': 'tối',
  'kr2': {'ko': '어두운', 'zh': '黑暗的', 'en': 'dark', 'ja': '暗い'}},
 {'vi1': 'sắc',
  'kr1': {'ko': '날카로운', 'zh': '尖銳的', 'en': 'sharp', 'ja': '鋭い'},
  'vi2': 'cùn',
  'kr2': {'ko': '무딘', 'zh': '鈍的', 'en': 'dull, blunt', 'ja': '鈍い'}},
 {'vi1': 'sạch sẽ',
  'kr1': {'ko': '깨끗한', 'zh': '乾淨的', 'en': 'clean', 'ja': '清潔な'},
  'vi2': 'bẩn',
  'kr2': {'ko': '더러운', 'zh': '骯髒的', 'en': 'dirty', 'ja': '汚い'}},
 {'vi1': 'sâu',
  'kr1': {'ko': '깊은', 'zh': '深的', 'en': 'deep', 'ja': '深い'},
  'vi2': 'cạn',
  'kr2': {'ko': '얕은', 'zh': '淺的', 'en': 'shallow', 'ja': '浅い'}},
 {'vi1': 'siêng năng',
  'kr1': {'ko': '부지런한', 'zh': '勤勞的，勤奮的', 'en': 'diligent', 'ja': '勤勉な'},
  'vi2': 'lười',
  'kr2': {'ko': '게으른', 'zh': '懶惰的', 'en': 'lazy', 'ja': '怠惰な'}},
 {'vi1': 'sinh viên',
  'kr1': {'ko': '학생', 'zh': '學生', 'en': 'student', 'ja': '学生'},
  'vi2': 'giáo viên',
  'kr2': {'ko': '교원', 'zh': '教員', 'en': 'teacher, faculty', 'ja': '教員'}},
 {'vi1': 'sớm',
  'kr1': {'ko': '일찍', 'zh': '早', 'en': 'early', 'ja': '早く'},
  'vi2': 'muộn = trễ',
  'kr2': {'ko': '늦게', 'zh': '晚地', 'en': 'late', 'ja': '遅く'}},
 {'vi1': 'thành công',
  'kr1': {'ko': '성공', 'zh': '成功', 'en': 'success', 'ja': '成功'},
  'vi2': 'thất bại',
  'kr2': {'ko': '실패', 'zh': '失敗', 'en': 'failure', 'ja': '失敗'}},
 {'vi1': 'thầy giáo',
  'kr1': {'ko': '남자 선생', 'zh': '男老師', 'en': 'male teacher', 'ja': '男の先生'},
  'vi2': 'cô giáo',
  'kr2': {'ko': '여선생', 'zh': '女老師', 'en': 'female teacher', 'ja': '女性教師'}},
 {'vi1': 'thích',
  'kr1': {'ko': '좋아하다', 'zh': '喜歡', 'en': 'to like', 'ja': '好む'},
  'vi2': 'ghét',
  'kr2': {'ko': '미워하다', 'zh': '討厭・恨', 'en': 'hate', 'ja': '憎む'}},
 {'vi1': 'muốn',
  'kr1': {'ko': '원하다', 'zh': '想要', 'en': 'to want', 'ja': '望む'},
  'vi2': 'không muốn',
  'kr2': {'ko': '원치 않다', 'zh': '不想要', 'en': 'to not want', 'ja': '望まない'}},
 {'vi1': 'thuốc tây',
  'kr1': {'ko': '양약', 'zh': '西藥', 'en': 'Western medicine', 'ja': '西洋薬'},
  'vi2': 'thuốc bắc',
  'kr2': {'ko': '한약', 'zh': '中藥', 'en': 'herbal medicine', 'ja': '漢方薬'}},
 {'vi1': 'tiễn',
  'kr1': {'ko': '배웅하다', 'zh': '送行', 'en': 'to see off', 'ja': '見送る'},
  'vi2': 'đón',
  'kr2': {'ko': '마중하다', 'zh': '迎接', 'en': 'go to meet, welcome', 'ja': '出迎える'}},
 {'vi1': 'tiện',
  'kr1': {'ko': '편한', 'zh': '舒服的', 'en': 'comfortable', 'ja': '楽な'},
  'vi2': 'bất tiện',
  'kr2': {'ko': '불편한', 'zh': '不方便的，不舒服的', 'en': 'uncomfortable; inconvenient', 'ja': '不便な'}},
 {'vi1': 'tốt',
  'kr1': {'ko': '좋은', 'zh': '好的', 'en': 'good', 'ja': '良い'},
  'vi2': 'xấu',
  'kr2': {'ko': '나쁜', 'zh': '壞的', 'en': 'bad', 'ja': '悪い'}},
 {'vi1': 'thịt',
  'kr1': {'ko': '고기', 'zh': '肉', 'en': 'meat', 'ja': '肉'},
  'vi2': 'rau',
  'kr2': {'ko': '야채', 'zh': '蔬菜', 'en': 'vegetable', 'ja': '野菜'}},
 {'vi1': 'trắng',
  'kr1': {'ko': '하얀', 'zh': '白色的', 'en': 'white', 'ja': '白い'},
  'vi2': 'đen',
  'kr2': {'ko': '검은', 'zh': '黑色的', 'en': 'black', 'ja': '黒い'}},
 {'vi1': 'trẻ',
  'kr1': {'ko': '젊은', 'zh': '年輕的', 'en': 'young', 'ja': '若い'},
  'vi2': 'già',
  'kr2': {'ko': '늙은', 'zh': '年老的', 'en': 'old (aged)', 'ja': '老いた'}},
 {'vi1': 'trên',
  'kr1': {'ko': '위', 'zh': '上面', 'en': 'above/top', 'ja': '上'},
  'vi2': 'dưới',
  'kr2': {'ko': '아래', 'zh': '下面', 'en': 'below, under', 'ja': '下'}},
 {'vi1': 'trong',
  'kr1': {'ko': '안에', 'zh': '裡面', 'en': 'inside', 'ja': '中に'},
  'vi2': 'ngoài',
  'kr2': {'ko': '밖에', 'zh': '外面', 'en': 'outside', 'ja': '外に'}},
 {'vi1': 'trước khi~',
  'kr1': {'ko': '~하기 전에', 'zh': '在~之前', 'en': 'before ~ing', 'ja': '~する前に'},
  'vi2': 'sau khi~',
  'kr2': {'ko': '~한 후에', 'zh': '~之後', 'en': 'after ~ing', 'ja': '~した後に'}},
 {'vi1': 'và',
  'kr1': {'ko': '그리고', 'zh': '而且', 'en': 'and', 'ja': 'そして'},
  'vi2': 'nhưng mà',
  'kr2': {'ko': '그러나', 'zh': '但是', 'en': 'but, however', 'ja': 'しかし'}},
 {'vi1': 'vào',
  'kr1': {'ko': '들어가다', 'zh': '進去', 'en': 'enter', 'ja': '入る'},
  'vi2': 'ra',
  'kr2': {'ko': '나오다', 'zh': '出來', 'en': 'come out', 'ja': '出てくる'}},
 {'vi1': 'về nước',
  'kr1': {'ko': '귀국하다', 'zh': '回國', 'en': "to return to one's country", 'ja': '帰国する'},
  'vi2': 'xuất cảnh',
  'kr2': {'ko': '출국하다', 'zh': '出國', 'en': 'to leave the country', 'ja': '出国する'}},
 {'vi1': 'vui mừng',
  'kr1': {'ko': '기쁜', 'zh': '高興的', 'en': 'glad, happy', 'ja': 'うれしい'},
  'vi2': 'buồn',
  'kr2': {'ko': '슬픈', 'zh': '悲傷的', 'en': 'sad', 'ja': '悲しい'}},
 {'vi1': 'xa',
  'kr1': {'ko': '먼', 'zh': '遠的', 'en': 'far', 'ja': '遠い'},
  'vi2': 'gần',
  'kr2': {'ko': '가까운', 'zh': '近的', 'en': 'near', 'ja': '近い'}},
 {'vi1': 'xuất khẩu',
  'kr1': {'ko': '수출', 'zh': '出口', 'en': 'export', 'ja': '輸出'},
  'vi2': 'nhập khẩu',
  'kr2': {'ko': '수입', 'zh': '收入', 'en': 'income', 'ja': '収入'}},
 {'vi1': 'xuất phát',
  'kr1': {'ko': '출발', 'zh': '出發', 'en': 'departure', 'ja': '出発'},
  'vi2': 'đến nơi',
  'kr2': {'ko': '도착', 'zh': '到達', 'en': 'arrival', 'ja': '到着'}},
 {'vi1': 'xuống',
  'kr1': {'ko': '내려가다', 'zh': '下去', 'en': 'go down', 'ja': '下がる'},
  'vi2': 'lên',
  'kr2': {'ko': '올라가다', 'zh': '上去', 'en': 'to go up', 'ja': '上がる'}}]
