# "교과 > 기본 단어·반의어" subtab -- "모든 대화를 구성하는 기본 단어" glossary,
# transcribed verbatim from page ~52-60 of the course booklet.

# The source table has no category subheadings -- just two columns, "단어"
# (word) and "예문" (example sentence), roughly ordered by the Korean word's
# alphabetical order. Only the "단어" column (headword + its Vietnamese
# equivalent(s)) is transcribed here as entries; the "예문" example-sentence
# column is not, since it illustrates usage rather than listing vocabulary.
# Two entries near "어디" (đấu, đầu) have no Korean headword of their own in
# the source -- they appear as a small aside pairing each Vietnamese word
# directly with its Korean gloss -- and are included verbatim as printed.
#
# Each word's "kr" is stored as a {"ko","zh","en","ja"} dict so js_json() (see build_app.py)
# serializes it straight into a JS object app_logic.js's T() helper can read directly.

BASIC_WORD_GROUPS = [{'title': None,
  'words': [{'vi': 'đi', 'kr': {'ko': '가다', 'zh': '去', 'en': 'to go', 'ja': '行く'}},
            {'vi': 'nhất', 'kr': {'ko': '가장', 'zh': '最', 'en': 'most', 'ja': '最も'}},
            {'vi': 'có',
             'kr': {'ko': '가지다, 있다, 그렇다',
                    'zh': '擁有，有，是如此',
                    'en': 'to have, to exist, to be so',
                    'ja': '持つ、ある、そうだ'}},
            {'vi': 'cám ơn', 'kr': {'ko': '감사하다', 'zh': '感謝', 'en': 'to be thankful', 'ja': '感謝する'}},
            {'vi': 'như', 'kr': {'ko': '같은', 'zh': '相同的', 'en': 'same', 'ja': '同じ'}},
            {'vi': 'như vậy', 'kr': {'ko': '그처럼', 'zh': '那樣', 'en': 'like that', 'ja': 'そのように'}},
            {'vi': 'hầu như, gần như', 'kr': {'ko': '거의', 'zh': '幾乎', 'en': 'almost', 'ja': 'ほとんど'}},
            {'vi': 'đó, cái đó(장소), ấy, cái ấy(사람)',
             'kr': {'ko': '그 (그것)', 'zh': '那(它)', 'en': 'that (it)', 'ja': 'それ'}},
            {'vi': 'chị ấy', 'kr': {'ko': '그녀', 'zh': '她', 'en': 'she', 'ja': '彼女'}},
            {'vi': 'họ', 'kr': {'ko': '그들', 'zh': '他們', 'en': 'they', 'ja': '彼ら'}},
            {'vi': 'lúc đó, lúc ấy', 'kr': {'ko': '그때', 'zh': '那時', 'en': 'then, at that time', 'ja': 'その時'}},
            {'vi': 'vì thế, như thế, cho nên, vì vậy',
             'kr': {'ko': '그래서', 'zh': '所以', 'en': 'so, therefore', 'ja': 'だから'}},
            {'vi': 'nhưng, mà', 'kr': {'ko': '그러나', 'zh': '但是', 'en': 'but, however', 'ja': 'しかし'}},
            {'vi': 'như thế, như vậy',
             'kr': {'ko': '그러한(~같은)', 'zh': '那樣的(~一樣的)', 'en': 'such (like ~)', 'ja': 'そのような(~のような)'}},
            {'vi': 'tuy nhiên',
             'kr': {'ko': '그런데, 하지만', 'zh': '不過、但是', 'en': 'by the way, but', 'ja': 'ところで、しかし'}},
            {'vi': 'và', 'kr': {'ko': '그리고', 'zh': '而且', 'en': 'and', 'ja': 'そして'}},
            {'vi': 'tôi', 'kr': {'ko': '나', 'zh': '我', 'en': 'I', 'ja': '私'}},
            {'vi': 'ra', 'kr': {'ko': '나가다', 'zh': '出去', 'en': 'go out', 'ja': '出る'}},
            {'vi': 'ai', 'kr': {'ko': '누구', 'zh': '誰', 'en': 'who', 'ja': '誰'}},
            {'vi': 'khác', 'kr': {'ko': '다른', 'zh': '不同的', 'en': 'different', 'ja': '違う'}},
            {'vi': 'lại', 'kr': {'ko': '다시', 'zh': '再次', 'en': 'again', 'ja': '再び'}},
            {'vi': 'nữa, hơn', 'kr': {'ko': '더', 'zh': '更', 'en': 'more', 'ja': 'もっと'}},
            {'vi': 'thành, trở thành, trở nên', 'kr': {'ko': '되다', 'zh': '成為', 'en': 'become', 'ja': 'なる'}},
            {'vi': 'đôi khi, có khi', 'kr': {'ko': '때때로', 'zh': '有時', 'en': 'sometimes', 'ja': '時々'}},
            {'vi': 'cuối cùng', 'kr': {'ko': '마지막', 'zh': '最後', 'en': 'last', 'ja': '最後'}},
            {'vi': 'làm', 'kr': {'ko': '만들다', 'zh': '製作・做', 'en': 'make', 'ja': '作る'}},
            {'vi': 'nếu (~thì)', 'kr': {'ko': '만약', 'zh': '如果', 'en': 'if', 'ja': 'もし'}},
            {'vi': 'nói', 'kr': {'ko': '말하다', 'zh': '說・說話', 'en': 'speak, say', 'ja': '話す'}},
            {'vi': 'nhiều', 'kr': {'ko': '많은', 'zh': '許多的', 'en': 'many', 'ja': '多い'}},
            {'vi': 'rất, lắm, quá', 'kr': {'ko': '매우', 'zh': '非常', 'en': 'very', 'ja': 'とても'}},
            {'vi': 'ăn', 'kr': {'ko': '먹다', 'zh': '吃', 'en': 'eat', 'ja': '食べる'}},
            {'vi': 'một số', 'kr': {'ko': '몇몇, 약간의', 'zh': '一些・若干的', 'en': 'some, a few', 'ja': 'いくつかの・若干の'}},
            {'vi': 'tất cả', 'kr': {'ko': '모두', 'zh': '全部・大家', 'en': 'all, everyone', 'ja': 'みんな・すべて'}},
            {'vi': 'gì', 'kr': {'ko': '무엇', 'zh': '什麼', 'en': 'what', 'ja': '何'}},
            {'vi': 'xem, nhìn thấy', 'kr': {'ko': '보다', 'zh': '看', 'en': 'to see', 'ja': '見る'}},
            {'vi': 'rõ ràng', 'kr': {'ko': '분명한', 'zh': '清楚的，明確的', 'en': 'clear; obvious', 'ja': '明確な'}},
            {'vi': 'từ~', 'kr': {'ko': '~부터', 'zh': '從~', 'en': 'from ~', 'ja': '~から'}},
            {'vi': 'cho dù, mặc dù', 'kr': {'ko': '비록~해도', 'zh': '即使~也', 'en': 'even if ~', 'ja': 'たとえ～しても'}},
            {'vi': 'người (ngươi)',
             'kr': {'ko': '사람 (너, 당신)', 'zh': '人（你）', 'en': 'person (you)', 'ja': '人（あなた）'}},
            {'vi': 'yêu thương', 'kr': {'ko': '사랑하다', 'zh': '愛', 'en': 'to love', 'ja': '愛する'}},
            {'vi': 'dùng', 'kr': {'ko': '사용하다', 'zh': '使用', 'en': 'to use', 'ja': '使う'}},
            {'vi': 'mới', 'kr': {'ko': '새로운', 'zh': '新的', 'en': 'new', 'ja': '新しい'}},
            {'vi': 'suy nghĩ',
             'kr': {'ko': '생각하다, 숙고하다', 'zh': '想, 深思', 'en': 'to think, to ponder', 'ja': '考える、熟考する'}},
            {'vi': 'nghĩa', 'kr': {'ko': '의미', 'zh': '意義', 'en': 'meaning', 'ja': '意味'}},
            {'vi': 'thì giờ', 'kr': {'ko': '시간', 'zh': '時間', 'en': 'time', 'ja': '時間'}},
            {'vi': 'bắt đầu', 'kr': {'ko': '시작하다', 'zh': '開始', 'en': 'to start', 'ja': '始める'}},
            {'vi': 'không thích, ghét', 'kr': {'ko': '싫어하다', 'zh': '討厭、不喜歡', 'en': 'to dislike', 'ja': '嫌う'}},
            {'vi': 'không', 'kr': {'ko': '아니다', 'zh': '不是', 'en': 'to not be', 'ja': '〜ではない'}},
            {'vi': 'dưới', 'kr': {'ko': '아래', 'zh': '下面', 'en': 'below, under', 'ja': '下'}},
            {'vi': 'trong', 'kr': {'ko': '~안에', 'zh': '在~之內', 'en': 'within ~', 'ja': '~の中に'}},
            {'vi': 'biết', 'kr': {'ko': '알다', 'zh': '知道', 'en': 'to know', 'ja': '知る'}},
            {'vi': 'viết', 'kr': {'ko': '쓰다', 'zh': '寫', 'en': 'to write', 'ja': '書く'}},
            {'vi': 'đâu', 'kr': {'ko': '어디', 'zh': '哪裡', 'en': 'where', 'ja': 'どこ'}},
            {'vi': 'đấu', 'kr': {'ko': '싸우다', 'zh': '打架、爭鬥', 'en': 'to fight', 'ja': '戦う'}},
            {'vi': 'đầu', 'kr': {'ko': '머리, 시초', 'zh': '頭・起始', 'en': 'head, beginning', 'ja': '頭・始まり'}},
            {'vi': 'nào', 'kr': {'ko': '어떤', 'zh': '某個、哪個', 'en': 'which, some', 'ja': 'どんな、ある'}},
            {'vi': 'thế nào, như thế nào', 'kr': {'ko': '어떻게', 'zh': '怎麼、如何', 'en': 'how', 'ja': 'どう、どのように'}},
            {'vi': 'khi nào, lúc nào', 'kr': {'ko': '언제', 'zh': '何時', 'en': 'when', 'ja': 'いつ'}},
            {'vi': 'cũng', 'kr': {'ko': '역시, 또한', 'zh': '也、同樣', 'en': 'also, too', 'ja': '〜もまた、同様に'}},
            {'vi': 'cùng', 'kr': {'ko': '함께 ~하자', 'zh': '一起～吧', 'en': "let's ~ together", 'ja': '一緒に～しよう'}},
            {'vi': 'đây', 'kr': {'ko': '여기', 'zh': '這裡', 'en': 'here', 'ja': 'ここ'}},
            {'vi': 'đến',
             'kr': {'ko': '오다, 도착하다', 'zh': '來，到達', 'en': 'to come, to arrive', 'ja': '来る、到着する'}},
            {'vi': 'đến cùng', 'kr': {'ko': '끝까지', 'zh': '到底', 'en': 'to the end', 'ja': '最後まで'}},
            {'vi': 'đúng, (chính xác)',
             'kr': {'ko': '옳다 (정확하다)', 'zh': '正確(對的)', 'en': 'right (correct)', 'ja': '正しい(正確である)'}},
            {'vi': 'chúng ta(tôi)', 'kr': {'ko': '우리', 'zh': '我們', 'en': 'we', 'ja': '私たち'}},
            {'vi': 'duy nhất', 'kr': {'ko': '유일한', 'zh': '唯一的', 'en': 'only, sole', 'ja': '唯一の'}},
            {'vi': 'trên', 'kr': {'ko': '~위에', 'zh': '在~上面', 'en': 'on ~', 'ja': '~の上に'}},
            {'vi': 'tại vì', 'kr': {'ko': '왜냐하면', 'zh': '因為', 'en': 'because', 'ja': 'なぜなら'}},
            {'vi': 'cho, do, vì', 'kr': {'ko': '~을 위해 (~for)', 'zh': '為了~', 'en': 'for ~', 'ja': '~のために'}},
            {'vi': 'của', 'kr': {'ko': '~의', 'zh': '~的', 'en': 'of ~', 'ja': '~の'}},
            {'vi': 'này(cái này) / đây', 'kr': {'ko': '이(이것)', 'zh': '這（這個）', 'en': 'this', 'ja': 'これ'}},
            {'vi': 'có',
             'kr': {'ko': '~이 있다, 가지다', 'zh': '有~，擁有', 'en': 'to have, to possess', 'ja': 'ある、持つ'}},
            {'vi': 'tại sao,', 'kr': {'ko': '왜', 'zh': '為什麼', 'en': 'why', 'ja': 'なぜ'}},
            {'vi': 'với, cùng với',
             'kr': {'ko': '~와 함께', 'zh': '與~一起', 'en': 'together with ~', 'ja': '~と一緒に'}},
            {'vi': 'về', 'kr': {'ko': '~에 대해', 'zh': '關於~', 'en': 'about ~', 'ja': '~について'}},
            {'vi': 'nhỏ', 'kr': {'ko': '작은', 'zh': '小的', 'en': 'small', 'ja': '小さい'}},
            {'vi': '(cái) kia', 'kr': {'ko': '저(저것)', 'zh': '那（那個）', 'en': 'that', 'ja': 'あれ'}},
            {'vi': 'thích', 'kr': {'ko': '좋아하다', 'zh': '喜歡', 'en': 'to like', 'ja': '好む'}},
            {'vi': 'tốt', 'kr': {'ko': '좋은', 'zh': '好的', 'en': 'good', 'ja': '良い'}},
            {'vi': 'càng A càng B',
             'kr': {'ko': 'A 하면할수록 더 B 하다.',
                    'zh': '越A就越B。',
                    'en': 'The more A, the more B.',
                    'ja': 'AすればするほどBだ。'}},
            {'vi': 'chỗ, nơi', 'kr': {'ko': '장소 (곳)', 'zh': '場所（地方）', 'en': 'place', 'ja': '場所（所）'}},
            {'vi': 'trước, trước khi', 'kr': {'ko': '전에', 'zh': '以前', 'en': 'before', 'ja': '前に'}},
            {'vi': 'mở (đóng)',
             'kr': {'ko': '열다 (닫다)', 'zh': '打開（關閉）', 'en': 'to open (close)', 'ja': '開ける（閉める）'}},
            {'vi': 'thường thường', 'kr': {'ko': '종종', 'zh': '常常', 'en': 'often', 'ja': 'しばしば'}},
            {'vi': 'bây giờ, lúc này', 'kr': {'ko': '지금', 'zh': '現在', 'en': 'now', 'ja': '今'}},
            {'vi': 'bấy giờ, lúc đó, lúc ấy',
             'kr': {'ko': '그때', 'zh': '那時', 'en': 'then, at that time', 'ja': 'その時'}},
            {'vi': 'tìm', 'kr': {'ko': '찾다', 'zh': '尋找', 'en': 'to find', 'ja': '探す'}},
            {'vi': 'đầu tiên', 'kr': {'ko': '처음', 'zh': '最初', 'en': 'the beginning', 'ja': '最初'}},
            {'vi': 'đủ', 'kr': {'ko': '충분한', 'zh': '充分的', 'en': 'sufficient', 'ja': '十分な'}},
            {'vi': 'bạn', 'kr': {'ko': '친구', 'zh': '朋友', 'en': 'friend', 'ja': '友達'}},
            {'vi': 'lớn, to', 'kr': {'ko': '큰', 'zh': '大的', 'en': 'big', 'ja': '大きい'}},
            {'vi': 'cần', 'kr': {'ko': '필요하다', 'zh': '需要', 'en': 'to need', 'ja': '必要だ'}},
            {'vi': 'để', 'kr': {'ko': '~하기 위해', 'zh': '為了~', 'en': 'in order to ~', 'ja': '~するために'}},
            {'vi': 'một', 'kr': {'ko': '하나', 'zh': '一個', 'en': 'one', 'ja': '一つ'}},
            {'vi': 'có thể, được', 'kr': {'ko': '할 수 있다', 'zh': '能夠', 'en': 'can', 'ja': 'できる'}},
            {'vi': 'luôn luôn', 'kr': {'ko': '항상', 'zh': '總是', 'en': 'always', 'ja': 'いつも'}},
            {'vi': 'phải, nên', 'kr': {'ko': '~해야 한다', 'zh': '必須~', 'en': 'must ~', 'ja': '~しなければならない'}},
            {'vi': 'hạnh phúc', 'kr': {'ko': '행복한', 'zh': '幸福的', 'en': 'happy', 'ja': '幸せな'}},
            {'vi': 'hoặc, hay', 'kr': {'ko': '혹은, 또는', 'zh': '或者,或', 'en': 'or, or', 'ja': 'あるいは、または'}},
            {'vi': 'sau', 'kr': {'ko': '후에', 'zh': '之後', 'en': 'after', 'ja': '後で'}},
            {'vi': 'hay quá',
             'kr': {'ko': '흥미있는 (감탄)', 'zh': '有趣的(感嘆)', 'en': 'interesting (exclamation)', 'ja': '興味深い(感嘆)'}},
            {'vi': 'đừng, chớ', 'kr': {'ko': '~하지마라', 'zh': '不要~', 'en': "don't ~", 'ja': '~するな'}},
            {'vi': 'đợi, chờ', 'kr': {'ko': '기다리다', 'zh': '等待', 'en': 'to wait', 'ja': '待つ'}},
            {'vi': 'ngủ', 'kr': {'ko': '자다', 'zh': '睡覺', 'en': 'to sleep', 'ja': '寝る'}},
            {'vi': 'vui', 'kr': {'ko': '기쁜', 'zh': '高興的', 'en': 'glad, happy', 'ja': 'うれしい'}},
            {'vi': 'buồn', 'kr': {'ko': '슬픈', 'zh': '悲傷的', 'en': 'sad', 'ja': '悲しい'}},
            {'vi': 'bằng', 'kr': {'ko': '~로 (수단)', 'zh': '以~(方式)', 'en': 'by (means)', 'ja': '~で(手段)'}},
            {'vi': 'nghe', 'kr': {'ko': '듣다', 'zh': '聽', 'en': 'listen', 'ja': '聞く'}},
            {'vi': 'cố gắng',
             'kr': {'ko': '노력하다, 시도하다', 'zh': '努力，嘗試', 'en': 'try, attempt', 'ja': '努力する、試みる'}},
            {'vi': 'cho phép', 'kr': {'ko': '허락하다', 'zh': '允許', 'en': 'to allow', 'ja': '許可する'}},
            {'vi': 'giữ',
             'kr': {'ko': '유지하다, 지키다', 'zh': '維持，保持', 'en': 'to maintain, to keep', 'ja': '維持する、守る'}},
            {'vi': 'dễ', 'kr': {'ko': '쉽다', 'zh': '容易', 'en': 'to be easy', 'ja': '易しい'}},
            {'vi': 'khó', 'kr': {'ko': '어렵다', 'zh': '困難', 'en': 'to be difficult', 'ja': '難しい'}}]}]
