# "교과 > 기본 단어·반의어" subtab -- "모든 대화를 구성하는 기본 단어" glossary,
# transcribed verbatim from page ~52-60 of the course booklet.

# The source table has no category subheadings -- just two columns, "단어"
# (word) and "예문" (example sentence), roughly ordered by the Korean word's
# alphabetical order. Only the "단어" column (headword + its Vietnamese
# equivalent(s)) is transcribed here as entries; the "예문" example-sentence
# column is not, since it illustrates usage rather than listing vocabulary.
# Two entries near "어디" (đấu, đầu) have no Korean headword of their own in
# the source -- they appear as a small aside pairing each Vietnamese word
# directly with its Korean gloss -- and are included verbatim as printed.
#
# Each word's "kr" is stored as a {"ko","zh","en","ja"} dict so js_json() (see build_app.py)
# serializes it straight into a JS object app_logic.js's T() helper can read directly.
#
# Words already covered by [신권]/[상용]/[반의] (VOCAB_THEO/FREQ_VOCAB/ANTONYM_PAIRS) have
# been removed here to avoid duplicate entries across 어휘 subtabs; sorted in Vietnamese
# dictionary order.

BASIC_WORD_GROUPS = [{'title': None,
  'words': [{'vi': 'bằng',
             'kr': {'ko': '~로 (수단)',
                    'zh': '以~(方式)',
                    'en': 'by (means)',
                    'ja': '~で(手段)',
                    'de': 'mit (Mittel)',
                    'fr': 'par, au moyen de',
                    'pl': 'przez, za pomocą'}},
            {'vi': 'bấy giờ, lúc đó, lúc ấy',
             'kr': {'ko': '그때',
                    'zh': '那時',
                    'en': 'then, at that time',
                    'ja': 'その時',
                    'de': 'damals, zu jener Zeit',
                    'fr': 'à ce moment-là, alors',
                    'pl': 'wtedy, w tamtym czasie'}},
            {'vi': 'bây giờ, lúc này',
             'kr': {'ko': '지금', 'zh': '現在', 'en': 'now', 'ja': '今', 'de': 'jetzt', 'fr': 'maintenant', 'pl': 'teraz'}},
            {'vi': 'biết',
             'kr': {'ko': '알다',
                    'zh': '知道',
                    'en': 'to know',
                    'ja': '知る',
                    'de': 'wissen',
                    'fr': 'savoir, connaître',
                    'pl': 'wiedzieć, znać'}},
            {'vi': 'cám ơn',
             'kr': {'ko': '감사하다',
                    'zh': '感謝',
                    'en': 'to be thankful',
                    'ja': '感謝する',
                    'de': 'danken',
                    'fr': 'remercier',
                    'pl': 'dziękować'}},
            {'vi': 'càng A càng B',
             'kr': {'ko': 'A 하면할수록 더 B 하다.',
                    'zh': '越A就越B。',
                    'en': 'The more A, the more B.',
                    'ja': 'AすればするほどBだ。',
                    'de': 'Je mehr A, desto mehr B.',
                    'fr': 'plus A, plus B',
                    'pl': 'im bardziej A, tym bardziej B'}},
            {'vi': 'chị ấy',
             'kr': {'ko': '그녀', 'zh': '她', 'en': 'she', 'ja': '彼女', 'de': 'sie', 'fr': 'elle', 'pl': 'ona'}},
            {'vi': 'cho dù, mặc dù',
             'kr': {'ko': '비록~해도',
                    'zh': '即使~也',
                    'en': 'even if ~',
                    'ja': 'たとえ～しても',
                    'de': 'obwohl, auch wenn',
                    'fr': 'même si, bien que',
                    'pl': 'chociaż, mimo że'}},
            {'vi': 'cho, do, vì',
             'kr': {'ko': '~을 위해 (~for)',
                    'zh': '為了~',
                    'en': 'for ~',
                    'ja': '~のために',
                    'de': 'für ~',
                    'fr': 'pour, à cause de',
                    'pl': 'dla, z powodu'}},
            {'vi': 'chỗ, nơi',
             'kr': {'ko': '장소 (곳)',
                    'zh': '場所（地方）',
                    'en': 'place',
                    'ja': '場所（所）',
                    'de': 'Ort, Stelle',
                    'fr': 'endroit, lieu',
                    'pl': 'miejsce'}},
            {'vi': 'chúng ta(tôi)',
             'kr': {'ko': '우리', 'zh': '我們', 'en': 'we', 'ja': '私たち', 'de': 'wir', 'fr': 'nous', 'pl': 'my'}},
            {'vi': 'có thể, được',
             'kr': {'ko': '할 수 있다',
                    'zh': '能夠',
                    'en': 'can',
                    'ja': 'できる',
                    'de': 'können',
                    'fr': 'pouvoir',
                    'pl': 'móc, można'}},
            {'vi': 'duy nhất',
             'kr': {'ko': '유일한',
                    'zh': '唯一的',
                    'en': 'only, sole',
                    'ja': '唯一の',
                    'de': 'einzig',
                    'fr': 'seul, unique',
                    'pl': 'jedyny'}},
            {'vi': 'đấu',
             'kr': {'ko': '싸우다',
                    'zh': '打架、爭鬥',
                    'en': 'to fight',
                    'ja': '戦う',
                    'de': 'kämpfen',
                    'fr': 'lutter, se battre',
                    'pl': 'walczyć'}},
            {'vi': 'đầu tiên',
             'kr': {'ko': '처음',
                    'zh': '最初',
                    'en': 'the beginning',
                    'ja': '最初',
                    'de': 'zuerst, Anfang',
                    'fr': 'd’abord, au début',
                    'pl': 'najpierw, pierwszy'}},
            {'vi': 'đến cùng',
             'kr': {'ko': '끝까지',
                    'zh': '到底',
                    'en': 'to the end',
                    'ja': '最後まで',
                    'de': 'bis zum Ende',
                    'fr': 'jusqu’à la fin',
                    'pl': 'do końca'}},
            {'vi': 'đợi, chờ',
             'kr': {'ko': '기다리다',
                    'zh': '等待',
                    'en': 'to wait',
                    'ja': '待つ',
                    'de': 'warten',
                    'fr': 'attendre',
                    'pl': 'czekać'}},
            {'vi': 'đó, cái đó(장소), ấy, cái ấy(사람)',
             'kr': {'ko': '그 (그것)',
                    'zh': '那(它)',
                    'en': 'that (it)',
                    'ja': 'それ',
                    'de': 'das (jenes)',
                    'fr': 'cela, ça, celui-là',
                    'pl': 'tamto, to, tamten'}},
            {'vi': 'đôi khi, có khi',
             'kr': {'ko': '때때로',
                    'zh': '有時',
                    'en': 'sometimes',
                    'ja': '時々',
                    'de': 'manchmal',
                    'fr': 'parfois',
                    'pl': 'czasami'}},
            {'vi': 'đừng, chớ',
             'kr': {'ko': '~하지마라',
                    'zh': '不要~',
                    'en': "don't ~",
                    'ja': '~するな',
                    'de': 'nicht ~ (tu nicht)',
                    'fr': 'ne pas (faire)',
                    'pl': 'nie (rób)'}},
            {'vi': 'đúng, (chính xác)',
             'kr': {'ko': '옳다 (정확하다)',
                    'zh': '正確(對的)',
                    'en': 'right (correct)',
                    'ja': '正しい(正確である)',
                    'de': 'richtig (genau)',
                    'fr': 'vrai, correct, exact',
                    'pl': 'prawidłowy, dokładny'}},
            {'vi': 'gì',
             'kr': {'ko': '무엇', 'zh': '什麼', 'en': 'what', 'ja': '何', 'de': 'was', 'fr': 'quoi, que', 'pl': 'co'}},
            {'vi': 'hầu như, gần như',
             'kr': {'ko': '거의',
                    'zh': '幾乎',
                    'en': 'almost',
                    'ja': 'ほとんど',
                    'de': 'fast, beinahe',
                    'fr': 'presque',
                    'pl': 'prawie'}},
            {'vi': 'hay quá',
             'kr': {'ko': '흥미있는 (감탄)',
                    'zh': '有趣的(感嘆)',
                    'en': 'interesting (exclamation)',
                    'ja': '興味深い(感嘆)',
                    'de': 'toll (Ausruf)',
                    'fr': 'super ! (exclamation)',
                    'pl': 'wspaniale! (wykrzyknik)'}},
            {'vi': 'họ',
             'kr': {'ko': '그들',
                    'zh': '他們',
                    'en': 'they',
                    'ja': '彼ら',
                    'de': 'sie (Plural)',
                    'fr': 'ils, eux',
                    'pl': 'oni'}},
            {'vi': 'hoặc, hay',
             'kr': {'ko': '혹은, 또는',
                    'zh': '或者,或',
                    'en': 'or, or',
                    'ja': 'あるいは、または',
                    'de': 'oder',
                    'fr': 'ou, ou bien',
                    'pl': 'albo, lub'}},
            {'vi': 'khi nào, lúc nào',
             'kr': {'ko': '언제', 'zh': '何時', 'en': 'when', 'ja': 'いつ', 'de': 'wann', 'fr': 'quand', 'pl': 'kiedy'}},
            {'vi': 'không thích, ghét',
             'kr': {'ko': '싫어하다',
                    'zh': '討厭、不喜歡',
                    'en': 'to dislike',
                    'ja': '嫌う',
                    'de': 'nicht mögen, hassen',
                    'fr': 'ne pas aimer, détester',
                    'pl': 'nie lubić, nienawidzić'}},
            {'vi': 'lớn, to',
             'kr': {'ko': '큰',
                    'zh': '大的',
                    'en': 'big',
                    'ja': '大きい',
                    'de': 'groß',
                    'fr': 'grand, gros',
                    'pl': 'duży, wielki'}},
            {'vi': 'lúc đó, lúc ấy',
             'kr': {'ko': '그때',
                    'zh': '那時',
                    'en': 'then, at that time',
                    'ja': 'その時',
                    'de': 'damals, zu jener Zeit',
                    'fr': 'à ce moment-là, alors',
                    'pl': 'wtedy, w tamtym czasie'}},
            {'vi': 'luôn luôn',
             'kr': {'ko': '항상',
                    'zh': '總是',
                    'en': 'always',
                    'ja': 'いつも',
                    'de': 'immer',
                    'fr': 'toujours',
                    'pl': 'zawsze'}},
            {'vi': 'mở (đóng)',
             'kr': {'ko': '열다 (닫다)',
                    'zh': '打開（關閉）',
                    'en': 'to open (close)',
                    'ja': '開ける（閉める）',
                    'de': 'öffnen (schließen)',
                    'fr': 'ouvrir (fermer)',
                    'pl': 'otwierać (zamykać)'}},
            {'vi': 'một',
             'kr': {'ko': '하나', 'zh': '一個', 'en': 'one', 'ja': '一つ', 'de': 'eins', 'fr': 'un', 'pl': 'jeden'}},
            {'vi': 'này(cái này) / đây',
             'kr': {'ko': '이(이것)',
                    'zh': '這（這個）',
                    'en': 'this',
                    'ja': 'これ',
                    'de': 'dies (dieses) / hier',
                    'fr': 'ceci / ici',
                    'pl': 'to / tutaj'}},
            {'vi': 'nếu (~thì)',
             'kr': {'ko': '만약',
                    'zh': '如果',
                    'en': 'if',
                    'ja': 'もし',
                    'de': 'wenn, falls',
                    'fr': 'si',
                    'pl': 'jeśli (~to)'}},
            {'vi': 'nghĩa',
             'kr': {'ko': '의미',
                    'zh': '意義',
                    'en': 'meaning',
                    'ja': '意味',
                    'de': 'Bedeutung',
                    'fr': 'sens, signification',
                    'pl': 'znaczenie'}},
            {'vi': 'người (ngươi)',
             'kr': {'ko': '사람 (너, 당신)',
                    'zh': '人（你）',
                    'en': 'person (you)',
                    'ja': '人（あなた）',
                    'de': 'Mensch, Person (du)',
                    'fr': 'personne (toi)',
                    'pl': 'osoba (ty)'}},
            {'vi': 'nhất',
             'kr': {'ko': '가장',
                    'zh': '最',
                    'en': 'most',
                    'ja': '最も',
                    'de': 'am meisten',
                    'fr': 'le plus',
                    'pl': 'najbardziej, naj-'}},
            {'vi': 'như thế, như vậy',
             'kr': {'ko': '그러한(~같은)',
                    'zh': '那樣的(~一樣的)',
                    'en': 'such (like ~)',
                    'ja': 'そのような(~のような)',
                    'de': 'so, solche(r)',
                    'fr': 'ainsi, comme cela',
                    'pl': 'tak, w ten sposób'}},
            {'vi': 'nhưng, mà',
             'kr': {'ko': '그러나',
                    'zh': '但是',
                    'en': 'but, however',
                    'ja': 'しかし',
                    'de': 'aber, jedoch',
                    'fr': 'mais, cependant',
                    'pl': 'ale, jednak'}},
            {'vi': 'nữa, hơn',
             'kr': {'ko': '더',
                    'zh': '更',
                    'en': 'more',
                    'ja': 'もっと',
                    'de': 'mehr',
                    'fr': 'plus, encore',
                    'pl': 'więcej, jeszcze'}},
            {'vi': 'phải, nên',
             'kr': {'ko': '~해야 한다',
                    'zh': '必須~',
                    'en': 'must ~',
                    'ja': '~しなければならない',
                    'de': 'müssen ~',
                    'fr': 'devoir, falloir',
                    'pl': 'musieć, powinien'}},
            {'vi': 'rất, lắm, quá',
             'kr': {'ko': '매우', 'zh': '非常', 'en': 'very', 'ja': 'とても', 'de': 'sehr', 'fr': 'très', 'pl': 'bardzo'}},
            {'vi': 'rõ ràng',
             'kr': {'ko': '분명한',
                    'zh': '清楚的，明確的',
                    'en': 'clear; obvious',
                    'ja': '明確な',
                    'de': 'klar, deutlich',
                    'fr': 'clair, évident',
                    'pl': 'jasny, wyraźny'}},
            {'vi': 'sau',
             'kr': {'ko': '후에',
                    'zh': '之後',
                    'en': 'after',
                    'ja': '後で',
                    'de': 'nach, danach',
                    'fr': 'après',
                    'pl': 'po, później'}},
            {'vi': 'tại sao,',
             'kr': {'ko': '왜',
                    'zh': '為什麼',
                    'en': 'why',
                    'ja': 'なぜ',
                    'de': 'warum',
                    'fr': 'pourquoi',
                    'pl': 'dlaczego'}},
            {'vi': 'thành, trở thành, trở nên',
             'kr': {'ko': '되다',
                    'zh': '成為',
                    'en': 'become',
                    'ja': 'なる',
                    'de': 'werden',
                    'fr': 'devenir',
                    'pl': 'stać się, stawać się'}},
            {'vi': 'thế nào, như thế nào',
             'kr': {'ko': '어떻게',
                    'zh': '怎麼、如何',
                    'en': 'how',
                    'ja': 'どう、どのように',
                    'de': 'wie',
                    'fr': 'comment',
                    'pl': 'jak'}},
            {'vi': 'thì giờ',
             'kr': {'ko': '시간', 'zh': '時間', 'en': 'time', 'ja': '時間', 'de': 'Zeit', 'fr': 'temps', 'pl': 'czas'}},
            {'vi': 'thường thường',
             'kr': {'ko': '종종',
                    'zh': '常常',
                    'en': 'often',
                    'ja': 'しばしば',
                    'de': 'oft, gewöhnlich',
                    'fr': 'souvent',
                    'pl': 'zazwyczaj, często'}},
            {'vi': 'tìm',
             'kr': {'ko': '찾다',
                    'zh': '尋找',
                    'en': 'to find',
                    'ja': '探す',
                    'de': 'suchen',
                    'fr': 'chercher, trouver',
                    'pl': 'szukać, znaleźć'}},
            {'vi': 'trước, trước khi',
             'kr': {'ko': '전에',
                    'zh': '以前',
                    'en': 'before',
                    'ja': '前に',
                    'de': 'vor, bevor',
                    'fr': 'avant',
                    'pl': 'przed, zanim'}},
            {'vi': 'tuy nhiên',
             'kr': {'ko': '그런데, 하지만',
                    'zh': '不過、但是',
                    'en': 'by the way, but',
                    'ja': 'ところで、しかし',
                    'de': 'jedoch, aber',
                    'fr': 'cependant, toutefois',
                    'pl': 'jednak, niemniej jednak'}},
            {'vi': 'từ~',
             'kr': {'ko': '~부터',
                    'zh': '從~',
                    'en': 'from ~',
                    'ja': '~から',
                    'de': 'von ~',
                    'fr': 'de, depuis',
                    'pl': 'od~'}},
            {'vi': 'vì thế, như thế, cho nên, vì vậy',
             'kr': {'ko': '그래서',
                    'zh': '所以',
                    'en': 'so, therefore',
                    'ja': 'だから',
                    'de': 'deshalb, daher',
                    'fr': 'donc, par conséquent',
                    'pl': 'dlatego, więc'}},
            {'vi': 'với, cùng với',
             'kr': {'ko': '~와 함께',
                    'zh': '與~一起',
                    'en': 'together with ~',
                    'ja': '~と一緒に',
                    'de': 'zusammen mit ~',
                    'fr': 'avec, ensemble avec',
                    'pl': 'z, razem z'}},
            {'vi': 'vui',
             'kr': {'ko': '기쁜',
                    'zh': '高興的',
                    'en': 'glad, happy',
                    'ja': 'うれしい',
                    'de': 'froh, glücklich',
                    'fr': 'joyeux, content',
                    'pl': 'wesoły, zadowolony'}},
            {'vi': 'xem, nhìn thấy',
             'kr': {'ko': '보다',
                    'zh': '看',
                    'en': 'to see',
                    'ja': '見る',
                    'de': 'sehen, schauen',
                    'fr': 'voir, regarder',
                    'pl': 'patrzeć, widzieć'}}]}]
