# "교과 > 성경 인명 사전" subtab -- Bible personal names, transcribed verbatim
# from page ~26-35 ("성경 인명 사전 (훈책)") of the course booklet.
#
# "kr" is a Bible proper name, stored as a {"ko","zh","en","ja","de"} dict so js_json() (see
# build_app.py) serializes it straight into a JS object app_logic.js's T() helper can read --
# each language shows the standard Bible-name form used in that language's own Bible/JW
# publications, not a literal translation of the Korean text.

BIBLE_NAMES = [{'no': 1, 'kr': {'ko': '여호와', 'zh': '耶和華', 'en': 'Jehovah', 'ja': 'エホバ', 'de': 'Jehova'}, 'vi': 'Giê-hô-va'},
 {'no': 2, 'kr': {'ko': '예수', 'zh': '耶穌', 'en': 'Jesus', 'ja': 'イエス', 'de': 'Jesus'}, 'vi': 'Giê-su'},
 {'no': 3, 'kr': {'ko': '아담', 'zh': '亞當', 'en': 'Adam', 'ja': 'アダム', 'de': 'Adam'}, 'vi': 'A-đam'},
 {'no': 4, 'kr': {'ko': '하와', 'zh': '夏娃', 'en': 'Eve', 'ja': 'エバ', 'de': 'Eva'}, 'vi': 'Ê-va'},
 {'no': 5,
  'kr': {'ko': '사탄 마귀', 'zh': '撒但魔鬼', 'en': 'Satan the Devil', 'ja': '悪魔サタン', 'de': 'Satan der Teufel'},
  'vi': 'Sa-tan Ác Qủy'},
 {'no': 6, 'kr': {'ko': '카인', 'zh': '該隱', 'en': 'Cain', 'ja': 'カイン', 'de': 'Kain'}, 'vi': 'Ca-in'},
 {'no': 7, 'kr': {'ko': '아벨', 'zh': '亞伯', 'en': 'Abel', 'ja': 'アベル', 'de': 'Abel'}, 'vi': 'A-bên'},
 {'no': 8, 'kr': {'ko': '노아', 'zh': '挪亞', 'en': 'Noah', 'ja': 'ノア', 'de': 'Noah'}, 'vi': 'Nô-ê'},
 {'no': 9, 'kr': {'ko': '셈', 'zh': '閃', 'en': 'Shem', 'ja': 'セム', 'de': 'Sem'}, 'vi': 'Sem'},
 {'no': 10, 'kr': {'ko': '함', 'zh': '含', 'en': 'Ham', 'ja': 'ハム', 'de': 'Ham'}, 'vi': 'Cham'},
 {'no': 11, 'kr': {'ko': '야벳', 'zh': '雅弗', 'en': 'Japheth', 'ja': 'ヤフェト', 'de': 'Japhet'}, 'vi': 'Gia-phết'},
 {'no': 12, 'kr': {'ko': '아브라함', 'zh': '亞伯拉罕', 'en': 'Abraham', 'ja': 'アブラハム', 'de': 'Abraham'}, 'vi': 'Áp-ra-ham'},
 {'no': 13, 'kr': {'ko': '사라', 'zh': '撒拉', 'en': 'Sarah', 'ja': 'サラ', 'de': 'Sara'}, 'vi': 'Sa-ra'},
 {'no': 14, 'kr': {'ko': '데라', 'zh': '他拉', 'en': 'Terah', 'ja': 'テラ', 'de': 'Terach'}, 'vi': 'Tha-rê'},
 {'no': 15, 'kr': {'ko': '롯', 'zh': '羅得', 'en': 'Lot', 'ja': 'ロト', 'de': 'Lot'}, 'vi': 'Lót'},
 {'no': 16, 'kr': {'ko': '하갈', 'zh': '夏甲', 'en': 'Hagar', 'ja': 'ハガル', 'de': 'Hagar'}, 'vi': 'Ha-ga'},
 {'no': 17, 'kr': {'ko': '이스마엘', 'zh': '以實瑪利', 'en': 'Ishmael', 'ja': 'イシュマエル', 'de': 'Ismael'}, 'vi': 'Ích-ma-ên'},
 {'no': 18, 'kr': {'ko': '이삭', 'zh': '以撒', 'en': 'Isaac', 'ja': 'イサク', 'de': 'Isaak'}, 'vi': 'Y-sác'},
 {'no': 19, 'kr': {'ko': '리브가', 'zh': '利百加', 'en': 'Rebekah', 'ja': 'リベカ', 'de': 'Rebekka'}, 'vi': 'Rê-bê-ca'},
 {'no': 20, 'kr': {'ko': '에서', 'zh': '以掃', 'en': 'Esau', 'ja': 'エサウ', 'de': 'Esau'}, 'vi': 'Ê-sau'},
 {'no': 21, 'kr': {'ko': '야곱', 'zh': '雅各', 'en': 'Jacob', 'ja': 'ヤコブ', 'de': 'Jakob'}, 'vi': 'Gia-cốp'},
 {'no': 22, 'kr': {'ko': '라반', 'zh': '拉班', 'en': 'Laban', 'ja': 'ラバン', 'de': 'Laban'}, 'vi': 'La-ban'},
 {'no': 23, 'kr': {'ko': '르우벤', 'zh': '呂便', 'en': 'Reuben', 'ja': 'ルベン', 'de': 'Ruben'}, 'vi': 'Ru-bên'},
 {'no': 24, 'kr': {'ko': '시므온', 'zh': '西緬', 'en': 'Simeon', 'ja': 'シメオン', 'de': 'Simeon'}, 'vi': 'Si-mê-ôn'},
 {'no': 25, 'kr': {'ko': '레위', 'zh': '利未', 'en': 'Levi', 'ja': 'レビ', 'de': 'Levi'}, 'vi': 'Lê-vi'},
 {'no': 26, 'kr': {'ko': '유다', 'zh': '猶大', 'en': 'Judah', 'ja': 'ユダ', 'de': 'Juda'}, 'vi': 'Giu-đa'},
 {'no': 27, 'kr': {'ko': '단', 'zh': '但', 'en': 'Dan', 'ja': 'ダン', 'de': 'Dan'}, 'vi': 'Đan'},
 {'no': 28, 'kr': {'ko': '납달리', 'zh': '拿弗他利', 'en': 'Naphtali', 'ja': 'ナフタリ', 'de': 'Naphtali'}, 'vi': 'Nép-ta-li'},
 {'no': 29, 'kr': {'ko': '갓', 'zh': '迦得', 'en': 'Gad', 'ja': 'ガド', 'de': 'Gad'}, 'vi': 'Gát'},
 {'no': 30, 'kr': {'ko': '아셀', 'zh': '亞設', 'en': 'Asher', 'ja': 'アシェル', 'de': 'Ascher'}, 'vi': 'A-se'},
 {'no': 31, 'kr': {'ko': '잇사갈', 'zh': '以薩迦', 'en': 'Issachar', 'ja': 'イッサカル', 'de': 'Issachar'}, 'vi': 'Y-sa-ca'},
 {'no': 32, 'kr': {'ko': '스불론', 'zh': '西布倫', 'en': 'Zebulun', 'ja': 'ゼブルン', 'de': 'Sebulon'}, 'vi': 'Xê-bu-lôn'},
 {'no': 33, 'kr': {'ko': '요셉', 'zh': '約瑟', 'en': 'Joseph', 'ja': 'ヨセフ', 'de': 'Joseph'}, 'vi': 'Giô-sép'},
 {'no': 34, 'kr': {'ko': '베냐민', 'zh': '便雅憫', 'en': 'Benjamin', 'ja': 'ベニヤミン', 'de': 'Benjamin'}, 'vi': 'Bên-gia-min'},
 {'no': 35, 'kr': {'ko': '보디발', 'zh': '波提乏', 'en': 'Potiphar', 'ja': 'ポティファル', 'de': 'Potiphar'}, 'vi': 'Phô-ti-pha'},
 {'no': 36, 'kr': {'ko': '파라오', 'zh': '法老', 'en': 'Pharaoh', 'ja': 'ファラオ', 'de': 'Pharao'}, 'vi': 'Pha-ra-ôn'},
 {'no': 37, 'kr': {'ko': '욥', 'zh': '約伯', 'en': 'Job', 'ja': 'ヨブ', 'de': 'Hiob'}, 'vi': 'Gióp'},
 {'no': 38, 'kr': {'ko': '엘리후', 'zh': '以利戶', 'en': 'Elihu', 'ja': 'エリフ', 'de': 'Elihu'}, 'vi': 'Ê-li-hu'},
 {'no': 39, 'kr': {'ko': '요게벳', 'zh': '約基別', 'en': 'Jochebed', 'ja': 'ヨケベデ', 'de': 'Jochebed'}, 'vi': 'Giô-kê-bết'},
 {'no': 40, 'kr': {'ko': '미리암', 'zh': '米利暗', 'en': 'Miriam', 'ja': 'ミリアム', 'de': 'Mirjam'}, 'vi': 'Mi-ri-am'},
 {'no': 41, 'kr': {'ko': '모세', 'zh': '摩西', 'en': 'Moses', 'ja': 'モーセ', 'de': 'Mose'}, 'vi': 'Môi-se'},
 {'no': 42, 'kr': {'ko': '아론', 'zh': '亞倫', 'en': 'Aaron', 'ja': 'アロン', 'de': 'Aaron'}, 'vi': 'A-rôn'},
 {'no': 43,
  'kr': {'ko': '이스라엘 백성', 'zh': '以色列人民', 'en': 'the people of Israel', 'ja': 'イスラエルの民', 'de': 'das Volk Israel'},
  'vi': 'Dân Y-sơ-ra-ên'},
 {'no': 44, 'kr': {'ko': '여호수아', 'zh': '約書亞', 'en': 'Joshua', 'ja': 'ヨシュア', 'de': 'Josua'}, 'vi': 'Giô-suê'},
 {'no': 45, 'kr': {'ko': '갈렙', 'zh': '迦勒', 'en': 'Caleb', 'ja': 'カレブ', 'de': 'Kaleb'}, 'vi': 'Ca-lép'},
 {'no': 46, 'kr': {'ko': '고라', 'zh': '可拉', 'en': 'Korah', 'ja': 'コラ', 'de': 'Korah'}, 'vi': 'Cô-rê'},
 {'no': 47, 'kr': {'ko': '다단', 'zh': '大坍', 'en': 'Dathan', 'ja': 'ダタン', 'de': 'Dathan'}, 'vi': 'Đa-than'},
 {'no': 48, 'kr': {'ko': '아비람', 'zh': '亞比蘭', 'en': 'Abiram', 'ja': 'アビラム', 'de': 'Abiram'}, 'vi': 'A-bi-ram'},
 {'no': 49, 'kr': {'ko': '발락', 'zh': '巴勒', 'en': 'Balak', 'ja': 'バラク', 'de': 'Balak'}, 'vi': 'Ba-lác'},
 {'no': 50, 'kr': {'ko': '발람', 'zh': '巴蘭', 'en': 'Balaam', 'ja': 'バラム', 'de': 'Bileam'}, 'vi': 'Ba-la-am'},
 {'no': 51, 'kr': {'ko': '라합', 'zh': '喇合', 'en': 'Rahab', 'ja': 'ラハブ', 'de': 'Rahab'}, 'vi': 'Ra-háp'},
 {'no': 52,
  'kr': {'ko': '기브온 사람들', 'zh': '基遍人', 'en': 'Gibeonites', 'ja': 'ギベオン人', 'de': 'Gibeoniter'},
  'vi': 'Dân Ga-ba-ôn'},
 {'no': 53, 'kr': {'ko': '야빈', 'zh': '耶賓', 'en': 'Jabin', 'ja': 'ヤビン', 'de': 'Jabin'}, 'vi': 'Gia-bin'},
 {'no': 54, 'kr': {'ko': '바락', 'zh': '巴拉', 'en': 'Barak', 'ja': 'バラク', 'de': 'Barak'}, 'vi': 'Ba-rác'},
 {'no': 55, 'kr': {'ko': '드보라', 'zh': '底波拉', 'en': 'Deborah', 'ja': 'デボラ', 'de': 'Debora'}, 'vi': 'Đê-bô-ra'},
 {'no': 56, 'kr': {'ko': '시스라', 'zh': '西西拉', 'en': 'Sisera', 'ja': 'シセラ', 'de': 'Sisera'}, 'vi': 'Si-sê-ra'},
 {'no': 57, 'kr': {'ko': '야엘', 'zh': '雅億', 'en': 'Jael', 'ja': 'ヤエル', 'de': 'Jael'}, 'vi': 'Gia-ên'},
 {'no': 58, 'kr': {'ko': '룻', 'zh': '路得', 'en': 'Ruth', 'ja': 'ルツ', 'de': 'Ruth'}, 'vi': 'Ru-tơ'},
 {'no': 59, 'kr': {'ko': '나오미', 'zh': '拿俄米', 'en': 'Naomi', 'ja': 'ナオミ', 'de': 'Noomi'}, 'vi': 'Na-ô-mi'},
 {'no': 60, 'kr': {'ko': '오르바', 'zh': '俄珥巴', 'en': 'Orpah', 'ja': 'オルパ', 'de': 'Orpa'}, 'vi': 'Ọt-ba'},
 {'no': 61, 'kr': {'ko': '보아스', 'zh': '波阿斯', 'en': 'Boaz', 'ja': 'ボアズ', 'de': 'Boas'}, 'vi': 'Bô-ô'},
 {'no': 62, 'kr': {'ko': '오벳', 'zh': '俄備得', 'en': 'Obed', 'ja': 'オベデ', 'de': 'Obed'}, 'vi': 'Ô-bết'},
 {'no': 63, 'kr': {'ko': '다윗', 'zh': '大衛', 'en': 'David', 'ja': 'ダビデ', 'de': 'David'}, 'vi': 'Đa-vít'},
 {'no': 64, 'kr': {'ko': '기드온', 'zh': '基甸', 'en': 'Gideon', 'ja': 'ギデオン', 'de': 'Gideon'}, 'vi': 'Ghi-đê-ôn'},
 {'no': 65,
  'kr': {'ko': '미디안 군대', 'zh': '米甸軍隊', 'en': 'the Midianite army', 'ja': 'ミディアン人の軍勢', 'de': 'die Armee der Midianiter'},
  'vi': 'quân Ma-đi-an'},
 {'no': 66, 'kr': {'ko': '엘가나', 'zh': '以利加拿', 'en': 'Elkanah', 'ja': 'エルカナ', 'de': 'Elkana'}, 'vi': 'Ên-ca-na'},
 {'no': 67, 'kr': {'ko': '한나', 'zh': '哈拿', 'en': 'Hannah', 'ja': 'ハンナ', 'de': 'Hanna'}, 'vi': 'Ha-na'},
 {'no': 68, 'kr': {'ko': '브닌나', 'zh': '毗尼拿', 'en': 'Peninnah', 'ja': 'ペニナ', 'de': 'Peninna'}, 'vi': 'Phê-ni-na'},
 {'no': 69, 'kr': {'ko': '엘리', 'zh': '以利', 'en': 'Eli', 'ja': 'エリ', 'de': 'Eli'}, 'vi': 'Hê-li'},
 {'no': 70, 'kr': {'ko': '사무엘', 'zh': '撒母耳', 'en': 'Samuel', 'ja': 'サムエル', 'de': 'Samuel'}, 'vi': 'Sa-mu-ên'},
 {'no': 71, 'kr': {'ko': '입다', 'zh': '耶弗他', 'en': 'Jephthah', 'ja': 'エフタ', 'de': 'Jephtha'}, 'vi': 'Giép-thê'},
 {'no': 72, 'kr': {'ko': '홉니', 'zh': '何弗尼', 'en': 'Hophni', 'ja': 'ホフニ', 'de': 'Hophni'}, 'vi': 'Hóp-ni'},
 {'no': 73, 'kr': {'ko': '비느하스', 'zh': '非尼哈', 'en': 'Phinehas', 'ja': 'フィネハス', 'de': 'Pinehas'}, 'vi': 'Phi-nê-a'},
 {'no': 74, 'kr': {'ko': '마노아', 'zh': '瑪挪亞', 'en': 'Manoah', 'ja': 'マノア', 'de': 'Manoach'}, 'vi': 'Ma-nô-a'},
 {'no': 75, 'kr': {'ko': '삼손', 'zh': '參孫', 'en': 'Samson', 'ja': 'サムソン', 'de': 'Simson'}, 'vi': 'Sam-sôn'},
 {'no': 76,
  'kr': {'ko': '블레셋 사람들', 'zh': '非利士人', 'en': 'Philistines', 'ja': 'フィリスティア人', 'de': 'Philister'},
  'vi': 'người Phi-li-tia'},
 {'no': 77, 'kr': {'ko': '들릴라', 'zh': '大利拉', 'en': 'Delilah', 'ja': 'デリラ', 'de': 'Delila'}, 'vi': 'Đa-li-la'},
 {'no': 78, 'kr': {'ko': '사울', 'zh': '掃羅', 'en': 'Saul', 'ja': 'サウル', 'de': 'Saul'}, 'vi': 'Sau-lơ'},
 {'no': 79, 'kr': {'ko': '아각', 'zh': '亞甲', 'en': 'Agag', 'ja': 'アガグ', 'de': 'Agag'}, 'vi': 'A-gác'},
 {'no': 80, 'kr': {'ko': '이새', 'zh': '耶西', 'en': 'Jesse', 'ja': 'エッサイ', 'de': 'Isai'}, 'vi': 'Giê-sê'},
 {'no': 81, 'kr': {'ko': '골리앗', 'zh': '歌利亞', 'en': 'Goliath', 'ja': 'ゴリアテ', 'de': 'Goliath'}, 'vi': 'Gô-li-át'},
 {'no': 82, 'kr': {'ko': '아비새', 'zh': '亞比篩', 'en': 'Abishai', 'ja': 'アビシャイ', 'de': 'Abischai'}, 'vi': 'A-bi-sai'},
 {'no': 83, 'kr': {'ko': '아브넬', 'zh': '押尼珥', 'en': 'Abner', 'ja': 'アブネル', 'de': 'Abner'}, 'vi': 'Áp-ne'},
 {'no': 84, 'kr': {'ko': '요나단', 'zh': '約拿單', 'en': 'Jonathan', 'ja': 'ヨナタン', 'de': 'Jonathan'}, 'vi': 'Giô-na-than'},
 {'no': 85,
  'kr': {'ko': '므비보셋', 'zh': '米非波設', 'en': 'Mephibosheth', 'ja': 'メフィボセテ', 'de': 'Mephiboscheth'},
  'vi': 'Mê-phi-bô-sết'},
 {'no': 86, 'kr': {'ko': '우리아', 'zh': '烏利亞', 'en': 'Uriah', 'ja': 'ウリヤ', 'de': 'Uria'}, 'vi': 'U-ri-a'},
 {'no': 87, 'kr': {'ko': '밧세바', 'zh': '拔示巴', 'en': 'Bathsheba', 'ja': 'バテシェバ', 'de': 'Bathseba'}, 'vi': 'Bát-sê-ba'},
 {'no': 88, 'kr': {'ko': '나단', 'zh': '拿單', 'en': 'Nathan', 'ja': 'ナタン', 'de': 'Nathan'}, 'vi': 'Na-than'},
 {'no': 89, 'kr': {'ko': '솔로몬', 'zh': '所羅門', 'en': 'Solomon', 'ja': 'ソロモン', 'de': 'Salomo'}, 'vi': 'Sa-lô-môn'},
 {'no': 90,
  'kr': {'ko': '여로보암', 'zh': '耶羅波安', 'en': 'Jeroboam', 'ja': 'ヤロブアム', 'de': 'Jerobeam'},
  'vi': 'Giê-rô-bô-am'},
 {'no': 91, 'kr': {'ko': '아히야', 'zh': '亞希雅', 'en': 'Ahijah', 'ja': 'アヒヤ', 'de': 'Ahija'}, 'vi': 'A-hi-gia'},
 {'no': 92, 'kr': {'ko': '르호보암', 'zh': '羅波安', 'en': 'Rehoboam', 'ja': 'レハブアム', 'de': 'Rehabeam'}, 'vi': 'Rê-hô-bô-am'},
 {'no': 93, 'kr': {'ko': '아합', 'zh': '亞哈', 'en': 'Ahab', 'ja': 'アハブ', 'de': 'Ahab'}, 'vi': 'A-háp'},
 {'no': 94, 'kr': {'ko': '이세벨', 'zh': '耶洗別', 'en': 'Jezebel', 'ja': 'イゼベル', 'de': 'Isebel'}, 'vi': 'Giê-xa-bên'},
 {'no': 95, 'kr': {'ko': '엘리야', 'zh': '以利亞', 'en': 'Elijah', 'ja': 'エリヤ', 'de': 'Elia'}, 'vi': 'Ê-li-gia'},
 {'no': 96, 'kr': {'ko': '엘리사', 'zh': '以利沙', 'en': 'Elisha', 'ja': 'エリシャ', 'de': 'Elisa'}, 'vi': 'Ê-li-sê'},
 {'no': 97,
  'kr': {'ko': '사르밧의 과부',
         'zh': '撒勒法的寡婦',
         'en': 'the widow of Zarephath',
         'ja': 'ザレファテのやもめ',
         'de': 'die Witwe von Zarpath'},
  'vi': 'bà góa ở Xa-rép-ta'},
 {'no': 98, 'kr': {'ko': '나봇', 'zh': '拿伯', 'en': 'Naboth', 'ja': 'ナボテ', 'de': 'Naboth'}, 'vi': 'Na-bốt'},
 {'no': 99, 'kr': {'ko': '여호람', 'zh': '約蘭', 'en': 'Jehoram', 'ja': 'ヨラム', 'de': 'Joram'}, 'vi': 'Giê-hô-ram'},
 {'no': 100, 'kr': {'ko': '예후', 'zh': '耶戶', 'en': 'Jehu', 'ja': 'エヒウ', 'de': 'Jehu'}, 'vi': 'Giê-hu'},
 {'no': 101,
  'kr': {'ko': '여호사밧', 'zh': '約沙法', 'en': 'Jehoshaphat', 'ja': 'ヨシャファト', 'de': 'Josaphat'},
  'vi': 'Giê-hô-sa-phát'},
 {'no': 102, 'kr': {'ko': '나아만', 'zh': '乃縵', 'en': 'Naaman', 'ja': 'ナアマン', 'de': 'Naaman'}, 'vi': 'Na-a-man'},
 {'no': 103,
  'kr': {'ko': '이스라엘 소녀',
         'zh': '以色列少女',
         'en': 'the Israelite girl',
         'ja': 'イスラエルの少女',
         'de': 'das israelitische Mädchen'},
  'vi': 'bé gái người Y-sơ-ra-ên'},
 {'no': 104,
  'kr': {'ko': '벤하닷', 'zh': '便哈達', 'en': 'Ben-hadad', 'ja': 'ベン・ハダド', 'de': 'Ben-Hadad'},
  'vi': 'Bên-ha-đát'},
 {'no': 105, 'kr': {'ko': '아달랴', 'zh': '亞她利雅', 'en': 'Athaliah', 'ja': 'アタルヤ', 'de': 'Athalja'}, 'vi': 'A-tha-li'},
 {'no': 106, 'kr': {'ko': '여호야다', 'zh': '耶何耶大', 'en': 'Jehoiada', 'ja': 'エホヤダ', 'de': 'Jojada'}, 'vi': 'Giê-hô-gia-đa'},
 {'no': 107,
  'kr': {'ko': '여호세바', 'zh': '約示巴', 'en': 'Jehosheba', 'ja': 'ヨシェバ', 'de': 'Joscheba'},
  'vi': 'Giê-hô-sê-ba'},
 {'no': 108, 'kr': {'ko': '여호아스', 'zh': '約阿施', 'en': 'Jehoash', 'ja': 'ヨアシュ', 'de': 'Joasch'}, 'vi': 'Giê-hô-ách'},
 {'no': 109, 'kr': {'ko': '요나', 'zh': '約拿', 'en': 'Jonah', 'ja': 'ヨナ', 'de': 'Jona'}, 'vi': 'Giô-na'},
 {'no': 110,
  'kr': {'ko': '산헤립', 'zh': '西拿基立', 'en': 'Sennacherib', 'ja': 'センナケリブ', 'de': 'Sanherib'},
  'vi': 'San-chê-ríp'},
 {'no': 111, 'kr': {'ko': '히스기야', 'zh': '希西家', 'en': 'Hezekiah', 'ja': 'ヒゼキヤ', 'de': 'Hiskia'}, 'vi': 'Ê-xê-chia'},
 {'no': 112, 'kr': {'ko': '요시야', 'zh': '約西亞', 'en': 'Josiah', 'ja': 'ヨシヤ', 'de': 'Josia'}, 'vi': 'Giô-si-a'},
 {'no': 113, 'kr': {'ko': '힐기야', 'zh': '希勒家', 'en': 'Hilkiah', 'ja': 'ヒルキヤ', 'de': 'Hilkija'}, 'vi': 'Hinh-kia'},
 {'no': 114, 'kr': {'ko': '사반', 'zh': '沙番', 'en': 'Shaphan', 'ja': 'シャファン', 'de': 'Schaphan'}, 'vi': 'Sa-phan'},
 {'no': 115, 'kr': {'ko': '훌다', 'zh': '戶勒大', 'en': 'Huldah', 'ja': 'フルダ', 'de': 'Hulda'}, 'vi': 'Hun-đa'},
 {'no': 116, 'kr': {'ko': '예레미야', 'zh': '耶利米', 'en': 'Jeremiah', 'ja': 'エレミヤ', 'de': 'Jeremia'}, 'vi': 'Giê-rê-mi'},
 {'no': 117, 'kr': {'ko': '바스훌', 'zh': '巴施戶珥', 'en': 'Pashhur', 'ja': 'パシュフル', 'de': 'Paschhur'}, 'vi': 'Pha-su-rơ'},
 {'no': 118,
  'kr': {'ko': '에벳멜렉', 'zh': '以伯米勒', 'en': 'Ebed-melech', 'ja': 'エベド・メレク', 'de': 'Ebed-Melech'},
  'vi': 'Ê-bết-mê-lết'},
 {'no': 119,
  'kr': {'ko': '느부갓네살', 'zh': '尼布甲尼撒', 'en': 'Nebuchadnezzar', 'ja': 'ネブカドネザル', 'de': 'Nebukadnezar'},
  'vi': 'Nê-bu-cát-nết-xa'},
 {'no': 120,
  'kr': {'ko': '여호야긴', 'zh': '約雅斤', 'en': 'Jehoiachin', 'ja': 'エホヤキン', 'de': 'Jojachin'},
  'vi': 'Giê-hô-gia-kin'},
 {'no': 121, 'kr': {'ko': '시드기야', 'zh': '西底家', 'en': 'Zedekiah', 'ja': 'ゼデキヤ', 'de': 'Zedekia'}, 'vi': 'Xê-đê-kia'},
 {'no': 122, 'kr': {'ko': '다니엘', 'zh': '但以理', 'en': 'Daniel', 'ja': 'ダニエル', 'de': 'Daniel'}, 'vi': 'Đa-ni-ên'},
 {'no': 123, 'kr': {'ko': '하나냐', 'zh': '哈拿尼雅', 'en': 'Hananiah', 'ja': 'ハナンヤ', 'de': 'Hananja'}, 'vi': 'Ha-na-nia'},
 {'no': 124, 'kr': {'ko': '미사엘', 'zh': '米沙勒', 'en': 'Mishael', 'ja': 'ミシャエル', 'de': 'Mischael'}, 'vi': 'Mi-sa-ên'},
 {'no': 125, 'kr': {'ko': '아사랴', 'zh': '亞撒利雅', 'en': 'Azariah', 'ja': 'アザルヤ', 'de': 'Asarja'}, 'vi': 'A-xa-ria'},
 {'no': 126,
  'kr': {'ko': '벨사살', 'zh': '伯沙撒', 'en': 'Belshazzar', 'ja': 'ベルシャツァル', 'de': 'Belsazar'},
  'vi': 'Ben-sát-xa'},
 {'no': 127, 'kr': {'ko': '키루스', 'zh': '居魯士', 'en': 'Cyrus', 'ja': 'キュロス', 'de': 'Cyrus'}, 'vi': 'Si-ru'},
 {'no': 128, 'kr': {'ko': '다리우스', 'zh': '大流士', 'en': 'Darius', 'ja': 'ダリウス', 'de': 'Darius'}, 'vi': 'Đa-ri-út'},
 {'no': 129, 'kr': {'ko': '에스더', 'zh': '以斯帖', 'en': 'Esther', 'ja': 'エステル', 'de': 'Esther'}, 'vi': 'Ê-xơ-tê'},
 {'no': 130, 'kr': {'ko': '모르드개', 'zh': '末底改', 'en': 'Mordecai', 'ja': 'モルデカイ', 'de': 'Mordechai'}, 'vi': 'Mạc-đô-chê'},
 {'no': 131,
  'kr': {'ko': '아하수에로', 'zh': '亞哈隨魯', 'en': 'Ahasuerus', 'ja': 'アハシュエロス', 'de': 'Ahasverus'},
  'vi': 'A-suê-ru'},
 {'no': 132, 'kr': {'ko': '하만', 'zh': '哈曼', 'en': 'Haman', 'ja': 'ハマン', 'de': 'Haman'}, 'vi': 'Ha-man'},
 {'no': 133, 'kr': {'ko': '에스라', 'zh': '以斯拉', 'en': 'Ezra', 'ja': 'エズラ', 'de': 'Esra'}, 'vi': 'Ê-xơ-ra'},
 {'no': 134,
  'kr': {'ko': '아닥사스다', 'zh': '亞達薛西', 'en': 'Artaxerxes', 'ja': 'アルタクセルクセス', 'de': 'Artaxerxes'},
  'vi': 'Ạt-ta-xét-xe'},
 {'no': 135, 'kr': {'ko': '느헤미야', 'zh': '尼希米', 'en': 'Nehemiah', 'ja': 'ネヘミヤ', 'de': 'Nehemia'}, 'vi': 'Nê-hê-mi'},
 {'no': 136, 'kr': {'ko': '스가랴', 'zh': '撒迦利亞', 'en': 'Zechariah', 'ja': 'ゼカリヤ', 'de': 'Sacharja'}, 'vi': 'Xa-cha-ri'},
 {'no': 137,
  'kr': {'ko': '엘리사벳', 'zh': '以利沙伯', 'en': 'Elizabeth', 'ja': 'エリサベツ', 'de': 'Elisabeth'},
  'vi': 'Ê-li-sa-bét'},
 {'no': 138, 'kr': {'ko': '가브리엘', 'zh': '加百列', 'en': 'Gabriel', 'ja': 'ガブリエル', 'de': 'Gabriel'}, 'vi': 'Gáp-ri-ên'},
 {'no': 139, 'kr': {'ko': '요한', 'zh': '約翰', 'en': 'John', 'ja': 'ヨハネ', 'de': 'Johannes'}, 'vi': 'Giăng'},
 {'no': 140, 'kr': {'ko': '마리아', 'zh': '馬利亞', 'en': 'Mary', 'ja': 'マリア', 'de': 'Maria'}, 'vi': 'Ma-ri'},
 {'no': 141, 'kr': {'ko': '요셉', 'zh': '約瑟', 'en': 'Joseph', 'ja': 'ヨセフ', 'de': 'Joseph'}, 'vi': 'Giô-sép'},
 {'no': 142,
  'kr': {'ko': '아우구스투스', 'zh': '奧古斯都', 'en': 'Augustus', 'ja': 'アウグストゥス', 'de': 'Augustus'},
  'vi': 'Au-gút-tơ'},
 {'no': 143, 'kr': {'ko': '헤롯', 'zh': '希律', 'en': 'Herod', 'ja': 'ヘロデ', 'de': 'Herodes'}, 'vi': 'Hê-rốt'},
 {'no': 144, 'kr': {'ko': '이사야', 'zh': '以賽亞', 'en': 'Isaiah', 'ja': 'イザヤ', 'de': 'Jesaja'}, 'vi': 'Ê-sai'},
 {'no': 145,
  'kr': {'ko': '사마리아 여자', 'zh': '撒馬利亞婦人', 'en': 'the Samaritan woman', 'ja': 'サマリアの女', 'de': 'die Samariterin'},
  'vi': 'phụ nữ Sa-ma-ri'},
 {'no': 146, 'kr': {'ko': '베드로', 'zh': '彼得', 'en': 'Peter', 'ja': 'ペテロ', 'de': 'Petrus'}, 'vi': 'Phi-e-rơ'},
 {'no': 147, 'kr': {'ko': '안드레', 'zh': '安得烈', 'en': 'Andrew', 'ja': 'アンデレ', 'de': 'Andreas'}, 'vi': 'Anh-rê'},
 {'no': 148, 'kr': {'ko': '야고보', 'zh': '雅各', 'en': 'James', 'ja': 'ヤコブ', 'de': 'Jakobus'}, 'vi': 'Gia-cơ'},
 {'no': 149, 'kr': {'ko': '요한', 'zh': '約翰', 'en': 'John', 'ja': 'ヨハネ', 'de': 'Johannes'}, 'vi': 'Giăng'},
 {'no': 150, 'kr': {'ko': '빌립', 'zh': '腓力', 'en': 'Philip', 'ja': 'フィリポ', 'de': 'Philippus'}, 'vi': 'Phi-líp'},
 {'no': 151,
  'kr': {'ko': '바돌로매', 'zh': '巴多羅買', 'en': 'Bartholomew', 'ja': 'バルトロマイ', 'de': 'Bartholomäus'},
  'vi': 'Ba-tô-lô-mê'},
 {'no': 152, 'kr': {'ko': '도마', 'zh': '多馬', 'en': 'Thomas', 'ja': 'トマス', 'de': 'Thomas'}, 'vi': 'Thô-ma'},
 {'no': 153, 'kr': {'ko': '마태', 'zh': '馬太', 'en': 'Matthew', 'ja': 'マタイ', 'de': 'Matthäus'}, 'vi': 'Ma-thi-ơ'},
 {'no': 154, 'kr': {'ko': '다대오', 'zh': '達太', 'en': 'Thaddaeus', 'ja': 'タダイ', 'de': 'Thaddäus'}, 'vi': 'Tha-đê'},
 {'no': 155, 'kr': {'ko': '시몬', 'zh': '西門', 'en': 'Simon', 'ja': 'シモン', 'de': 'Simon'}, 'vi': 'Si-môn'},
 {'no': 156,
  'kr': {'ko': '가룟 유다', 'zh': '加略人猶大', 'en': 'Judas Iscariot', 'ja': 'イスカリオテ・ユダ', 'de': 'Judas Iskariot'},
  'vi': 'Giu-đa Ích-ca-ri-ốt'},
 {'no': 157,
  'kr': {'ko': '막달라 마리아', 'zh': '抹大拉的馬利亞', 'en': 'Mary Magdalene', 'ja': 'マグダラのマリア', 'de': 'Maria Magdalena'},
  'vi': 'Ma-ri Ma-đơ-len'},
 {'no': 158, 'kr': {'ko': '요안나', 'zh': '約亞拿', 'en': 'Joanna', 'ja': 'ヨハンナ', 'de': 'Johanna'}, 'vi': 'Gian-nơ'},
 {'no': 159, 'kr': {'ko': '수산나', 'zh': '蘇撒拿', 'en': 'Susanna', 'ja': 'スザンナ', 'de': 'Susanna'}, 'vi': 'Su-xan-nơ'},
 {'no': 160, 'kr': {'ko': '야이로', 'zh': '睚魯', 'en': 'Jairus', 'ja': 'ヤイロ', 'de': 'Jairus'}, 'vi': 'Giai-ru'},
 {'no': 161,
  'kr': {'ko': '바리새인', 'zh': '法利賽人', 'en': 'Pharisee', 'ja': 'パリサイ人', 'de': 'Pharisäer'},
  'vi': 'Người Pha-ri-si'},
 {'no': 162, 'kr': {'ko': '나사로', 'zh': '拉撒路', 'en': 'Lazarus', 'ja': 'ラザロ', 'de': 'Lazarus'}, 'vi': 'La-xa-rơ'},
 {'no': 163, 'kr': {'ko': '마리아', 'zh': '馬利亞', 'en': 'Mary', 'ja': 'マリア', 'de': 'Maria'}, 'vi': 'Ma-ri'},
 {'no': 164, 'kr': {'ko': '마르다', 'zh': '馬大', 'en': 'Martha', 'ja': 'マルタ', 'de': 'Martha'}, 'vi': 'Ma-thê'},
 {'no': 165, 'kr': {'ko': '말고', 'zh': '馬勒古', 'en': 'Malchus', 'ja': 'マルコス', 'de': 'Malchus'}, 'vi': 'Man-chu'},
 {'no': 166, 'kr': {'ko': '안나스', 'zh': '亞那', 'en': 'Annas', 'ja': 'アンナス', 'de': 'Annas'}, 'vi': 'An-ne'},
 {'no': 167, 'kr': {'ko': '가야바', 'zh': '該亞法', 'en': 'Caiaphas', 'ja': 'カヤファ', 'de': 'Kaiphas'}, 'vi': 'Cai-pha'},
 {'no': 168,
  'kr': {'ko': '본디오 빌라도', 'zh': '本丟彼拉多', 'en': 'Pontius Pilate', 'ja': 'ポンテオ・ピラト', 'de': 'Pontius Pilatus'},
  'vi': 'Bôn-xơ Phi-lát'},
 {'no': 169, 'kr': {'ko': '가말리엘', 'zh': '迦瑪列', 'en': 'Gamaliel', 'ja': 'ガマリエル', 'de': 'Gamaliel'}, 'vi': 'Ga-ma-li-ên'},
 {'no': 170, 'kr': {'ko': '사울', 'zh': '掃羅', 'en': 'Saul', 'ja': 'サウル', 'de': 'Saulus'}, 'vi': 'Sau-lơ'},
 {'no': 171, 'kr': {'ko': '스데반', 'zh': '司提反', 'en': 'Stephen', 'ja': 'ステファノ', 'de': 'Stephanus'}, 'vi': 'Ê-tiên'},
 {'no': 172, 'kr': {'ko': '아나니아', 'zh': '亞拿尼亞', 'en': 'Ananias', 'ja': 'アナニア', 'de': 'Ananias'}, 'vi': 'A-na-nia'},
 {'no': 173, 'kr': {'ko': '유다', 'zh': '猶大', 'en': 'Judah', 'ja': 'ユダ', 'de': 'Judas'}, 'vi': 'Giu-đa'},
 {'no': 174, 'kr': {'ko': '바나바', 'zh': '巴拿巴', 'en': 'Barnabas', 'ja': 'バルナバ', 'de': 'Barnabas'}, 'vi': 'Ba-na-ba'},
 {'no': 175, 'kr': {'ko': '바울', 'zh': '保羅', 'en': 'Paul', 'ja': 'パウロ', 'de': 'Paulus'}, 'vi': 'Phao-lô'},
 {'no': 176, 'kr': {'ko': '고넬료', 'zh': '哥尼流', 'en': 'Cornelius', 'ja': 'コルネリオ', 'de': 'Kornelius'}, 'vi': 'Cọt-nây'},
 {'no': 177,
  'kr': {'ko': '세르기오 바울로', 'zh': '士求保羅', 'en': 'Sergius Paulus', 'ja': 'セルギオ・パウロ', 'de': 'Sergius Paulus'},
  'vi': 'Sê-giút Phau-lút'},
 {'no': 178, 'kr': {'ko': '실라', 'zh': '西拉', 'en': 'Silas', 'ja': 'シラス', 'de': 'Silas'}, 'vi': 'Si-la'},
 {'no': 179, 'kr': {'ko': '누가', 'zh': '路加', 'en': 'Luke', 'ja': 'ルカ', 'de': 'Lukas'}, 'vi': 'Lu-ca'},
 {'no': 180, 'kr': {'ko': '디모데', 'zh': '提摩太', 'en': 'Timothy', 'ja': 'テモテ', 'de': 'Timotheus'}, 'vi': 'Ti-mô-thê'},
 {'no': 181, 'kr': {'ko': '유니게', 'zh': '友尼基', 'en': 'Eunice', 'ja': 'エウニケ', 'de': 'Eunike'}, 'vi': 'Ơ-nít'},
 {'no': 182, 'kr': {'ko': '로이스', 'zh': '羅以', 'en': 'Lois', 'ja': 'ロイス', 'de': 'Lois'}, 'vi': 'Lô-ít'},
 {'no': 183, 'kr': {'ko': '페스투스', 'zh': '非斯都', 'en': 'Festus', 'ja': 'フェストゥス', 'de': 'Festus'}, 'vi': 'Phê-tô'},
 {'no': 184,
  'kr': {'ko': '아리스다르고', 'zh': '亞裡達古', 'en': 'Aristarchus', 'ja': 'アリスタルコ', 'de': 'Aristarchus'},
  'vi': 'A-ri-ta-cơ'}]
