# -*- coding: utf-8 -*-
"""AI-generated translations for the culture cards in culture_data.CULTURE_ARTICLES ([대화] > [문화]).

The cards' source text is Vietnamese + Korean only (titleVi / titleKo, summaryKo, learningPoint,
keywords[].vi/.ko). apply_culture_ai_translations() returns a copy that adds, without changing
any source field: `titleTr`, `summaryTr`, `learningPointTr` ({"ko": source, ...generated}),
keywords[].tr ({"ko": source, ...generated}) and `aiLangs`. Cards are matched by titleVi.

Order in each row: cs | zh_cn | zh | en | fr | de | hu | id | ja | pl
"""

import copy

CULTURE_AI_LANGS = ["cs", "zh_cn", "zh", "en", "fr", "de", "hu", "id", "ja", "pl"]

CULTURE_CARD_AI = {
    "Văn hóa cà phê Việt": {
        "title": "Vietnamská kávová kultura|越南的咖啡文化|越南的咖啡文化|Vietnamese Coffee Culture|La culture du café au Vietnam|Die vietnamesische Kaffeekultur|A vietnámi kávékultúra|Budaya kopi Vietnam|ベトナムのコーヒー文化|Wietnamska kultura kawy",
        "summary": "Vietnamci si vychutnávají silnou kávu připravenou v kapacím filtru phin a pijí ji v klidu s cukrem nebo kondenzovaným mlékem.|越南人喜欢用滴滤壶（phin）冲泡的浓咖啡，加入砂糖或炼乳慢慢品尝。|越南人喜歡用滴濾壺（phin）沖泡的濃咖啡，加入砂糖或煉乳慢慢品嚐。|Vietnamese people enjoy strong coffee brewed with a phin drip filter, sipping it slowly with sugar or condensed milk.|Les Vietnamiens apprécient un café corsé préparé avec un filtre phin et le boivent tranquillement avec du sucre ou du lait concentré.|Vietnamesen genießen starken Kaffee aus dem Phin-Tropffilter und trinken ihn gemächlich mit Zucker oder Kondensmilch.|A vietnámiak a phin csepegtetőszűrővel főzött erős kávét kedvelik, és cukorral vagy sűrített tejjel, komótosan isszák.|Orang Vietnam menikmati kopi kental yang diseduh dengan saringan tetes phin, lalu meminumnya perlahan dengan gula atau susu kental manis.|ベトナムの人々はフィン（phin）ドリッパーで淹れた濃いコーヒーを好み、砂糖や練乳を入れてゆっくり味わいます。|Wietnamczycy lubią mocną kawę parzoną w filtrze phin i piją ją niespiesznie z cukrem lub mlekiem skondensowanym.",
        "learningPoint": "Typickým rysem vietnamské kávové kultury je vychutnávat si klid při čekání, než káva pomalu prokape filtrem phin.|用滴滤壶（phin）等待咖啡一滴一滴慢慢落下、享受悠闲，是越南咖啡文化的特色。|用滴濾壺（phin）等待咖啡一滴一滴慢慢落下、享受悠閒，是越南咖啡文化的特色。|A hallmark of Vietnamese coffee culture is relaxing while you wait for the coffee to drip slowly through the phin.|Ce qui caractérise la culture du café vietnamienne, c'est de prendre son temps en attendant que le café s'écoule goutte à goutte du phin.|Typisch für die vietnamesische Kaffeekultur ist, die Ruhe zu genießen, während der Kaffee langsam durch den Phin tropft.|A vietnámi kávékultúra jellegzetessége, hogy nyugodtan kivárják, amíg a kávé lassan átcsöpög a phin szűrőn.|Ciri khas budaya kopi Vietnam adalah menikmati waktu santai sambil menunggu kopi menetes perlahan dari phin.|フィン（phin）でコーヒーがゆっくり落ちるのを待ちながら、ゆとりを楽しむのがベトナムのコーヒー文化の特徴です。|Cechą wietnamskiej kultury kawy jest spokojne czekanie, aż kawa powoli przecieknie przez filtr phin.",
        "keywords": [
            "káva z filtru phin|滴滤壶咖啡|滴濾壺咖啡|phin-filter coffee|café au filtre phin|Phin-Filterkaffee|phin szűrős kávé|kopi saring phin|フィンドリップコーヒー|kawa z filtra phin",
            "bílý cukr|白糖|白糖|white sugar|sucre blanc|weißer Zucker|fehér cukor|gula pasir|白砂糖|biały cukier",
            "hořká chuť|苦味|苦味|bitter taste|amertume|bitterer Geschmack|keserű íz|rasa pahit|苦味|gorzki smak",
            "vychutnávat|品尝|品嚐|to savor|savourer|genießen|élvezni, ízlelgetni|menikmati|味わう|delektować się",
        ],
    },
    "Quy tắc trên bàn ăn của người Việt": {
        "title": "Stolování s Vietnamci|与越南人用餐的礼仪|與越南人用餐的禮儀|Table Manners with Vietnamese People|Les bonnes manières à table avec des Vietnamiens|Tischsitten bei Vietnamesen|Étkezési illem vietnámiakkal|Etiket makan bersama orang Vietnam|ベトナム人との食事マナー|Savoir-vivre przy stole z Wietnamczykami",
        "summary": "Před jídlem se nejprve nabídne jídlo nejstaršímu, v jídle se nepřebírá a dává se pozor, aby se špičky hůlek nedotkly omáčky.|用餐前先请最年长的人用餐，不翻挑菜肴，并注意筷子尖不要碰到蘸酱。|用餐前先請最年長的人用餐，不翻挑菜餚，並注意筷子尖不要碰到沾醬。|Before eating, you first invite the eldest to eat, don't rummage through dishes to pick food, and take care that your chopstick tips don't touch the dipping sauce.|Avant le repas, on invite d'abord la personne la plus âgée à manger, on ne fouille pas dans les plats et on veille à ce que le bout des baguettes ne touche pas la sauce.|Vor dem Essen lädt man zuerst den Ältesten zum Essen ein, wühlt nicht im Essen und achtet darauf, dass die Stäbchenspitzen die Dip-Soße nicht berühren.|Evés előtt először a legidősebbet kínálják meg, nem turkálnak az ételben, és vigyáznak, hogy a pálcika hegye ne érjen a mártogatós szószhoz.|Sebelum makan, orang pertama-tama mempersilakan orang paling tua untuk makan, tidak mengaduk-aduk makanan, dan menjaga agar ujung sumpit tidak menyentuh saus cocolan.|食事の前にまず最年長の人に食事を勧め、料理をかき回して選ばず、箸先がたれにつかないよう気をつけます。|Przed jedzeniem najpierw zaprasza się do jedzenia najstarszą osobę, nie przebiera się w potrawach i uważa, by końcówki pałeczek nie dotknęły sosu.",
        "learningPoint": "Ve Vietnamu je důležitá úcta ke starším a hygiena a slušnost při jídle, kdy se jídlo nejprve přendá do vlastní misky.|在越南，尊敬长辈以及先把食物夹到自己碗里再吃的卫生与礼节都很重要。|在越南，尊敬長輩以及先把食物夾到自己碗裡再吃的衛生與禮節都很重要。|In Vietnam, respect for elders matters, as does the hygiene and etiquette of moving food to your own bowl before eating it.|Au Vietnam, le respect des aînés compte, tout comme l'hygiène et la politesse qui consistent à passer la nourriture dans son propre bol avant de la manger.|In Vietnam sind Respekt vor Älteren sowie Hygiene und Etikette wichtig: Man legt das Essen erst in die eigene Schale, bevor man isst.|Vietnámban fontos az idősebbek tisztelete, valamint az a higiénia és illem, hogy az ételt előbb a saját tálunkba tesszük.|Di Vietnam, rasa hormat kepada orang yang lebih tua serta kebersihan dan sopan santun mengambil makanan ke mangkuk sendiri sebelum dimakan sangat penting.|ベトナムでは年長者への敬意と、料理をいったん自分の器に取ってから食べる衛生・礼儀が大切です。|W Wietnamie ważny jest szacunek dla starszych oraz higiena i savoir-vivre: jedzenie najpierw nakłada się do własnej miseczki.",
        "keywords": [
            "pozvat k jídlu|请人吃饭|請人吃飯|to invite someone to eat|inviter à manger|zum Essen einladen|evésre kínálni|mempersilakan makan|食事を勧める|zaprosić do jedzenia",
            "starší člověk|长辈，年长者|長輩，年長者|elder, older person|personne âgée, aîné|ältere Person|idősebb ember|orang yang lebih tua|年長者|osoba starsza",
            "omáčka k namáčení|蘸酱|沾醬|dipping sauce|sauce à tremper|Dip-Soße|mártogatós szósz|saus cocolan|つけだれ|sos do maczania",
            "zdvořilý|有礼貌的|有禮貌的|polite|poli|höflich|udvarias|sopan|礼儀正しい|uprzejmy",
        ],
    },
    "Phở và Bún trong ẩm thực Việt": {
        "title": "Rozdíl mezi vietnamskými nudlemi Phở a Bún|越南河粉 Phở 与米线 Bún 的区别|越南河粉 Phở 與米線 Bún 的區別|The Difference Between Vietnamese Phở and Bún|La différence entre le phở et le bún vietnamiens|Der Unterschied zwischen vietnamesischem Phở und Bún|A vietnámi phở és bún különbsége|Perbedaan Phở dan Bún Vietnam|ベトナムの麺 Phở と Bún の違い|Różnica między wietnamskim phở a bún",
        "summary": "Phở, typické vietnamské nudlové jídlo, používá ploché nudle s hovězím nebo kuřecím vývarem, zatímco bún má kulaté nudle a jí se s různými vývary nebo jako míchaný salát.|越南代表性的面食河粉（Phở）用扁平的粉条配牛肉或鸡肉高汤，而米线（Bún）用圆形细粉，可配各种汤头或拌着吃。|越南代表性的麵食河粉（Phở）用扁平的粉條配牛肉或雞肉高湯，而米線（Bún）用圓形細粉，可配各種湯頭或拌著吃。|Phở, Vietnam's signature noodle dish, uses flat noodles in beef or chicken broth, while bún uses round noodles eaten with various broths or tossed as a salad.|Le phở, plat de nouilles emblématique du Vietnam, utilise des nouilles plates dans un bouillon de bœuf ou de poulet, tandis que le bún, aux nouilles rondes, se déguste avec divers bouillons ou en salade mélangée.|Phở, das typische vietnamesische Nudelgericht, hat flache Nudeln in Rinder- oder Hühnerbrühe, Bún dagegen runde Nudeln mit verschiedenen Brühen oder gemischt als Salat.|A phở, Vietnám jellegzetes tésztaétele, lapos tésztát használ marha- vagy csirkealaplével, a bún pedig kerek tésztát, amelyet különféle levesekkel vagy összekeverve esznek.|Phở, hidangan mi khas Vietnam, memakai mi pipih dengan kaldu sapi atau ayam, sedangkan bún memakai mi bulat yang dinikmati dengan aneka kuah atau diaduk.|ベトナムの代表的な麺料理フォー（Phở）は平たい麺に牛肉や鶏肉のスープを使い、ブン（Bún）は丸い麺でさまざまなスープや和え麺として楽しみます。|Phở, sztandarowe wietnamskie danie z makaronem, ma płaski makaron w bulionie wołowym lub drobiowym, a bún – okrągły makaron jedzony z różnymi bulionami lub jako sałatka.",
        "learningPoint": "Vietnamská nudlová jídla se rozvinula do mnoha podob podle tvaru nudlí (ploché bánh phở oproti kulatým sợi bún) a způsobu přípravy vývaru.|越南面食依面条形状（扁平的 bánh phở 与圆形的 sợi bún）及汤头做法发展出多种样貌。|越南麵食依麵條形狀（扁平的 bánh phở 與圓形的 sợi bún）及湯頭做法發展出多種樣貌。|Vietnamese noodle dishes have developed in many ways depending on the noodle shape (flat bánh phở vs. round sợi bún) and how the broth is made.|Les plats de nouilles vietnamiens se sont diversifiés selon la forme des nouilles (bánh phở plates contre sợi bún rondes) et la préparation du bouillon.|Vietnamesische Nudelgerichte haben sich je nach Nudelform (flache bánh phở gegenüber runden sợi bún) und Brühenzubereitung vielfältig entwickelt.|A vietnámi tésztaételek a tészta formája (lapos bánh phở vagy kerek sợi bún) és az alaplé elkészítése szerint sokféleképpen fejlődtek.|Hidangan mi Vietnam berkembang beragam menurut bentuk mi (bánh phở pipih vs. sợi bún bulat) dan cara membuat kuahnya.|麺の形（平たい bánh phở と丸い sợi bún）とスープの作り方によって、ベトナムの麺料理は多様に発展しました。|Wietnamskie dania z makaronem rozwinęły się na wiele sposobów w zależności od kształtu makaronu (płaski bánh phở kontra okrągły sợi bún) i sposobu gotowania bulionu.",
        "keywords": [
            "hovězí phở|牛肉河粉|牛肉河粉|beef phở|phở au bœuf|Rindfleisch-Phở|marhahúsos phở|phở sapi|牛肉のフォー|phở z wołowiną",
            "bún chả|烤肉米线|烤肉米線|bún chả (grilled pork with noodles)|bún chả (porc grillé et vermicelles)|Bún chả (gegrilltes Schweinefleisch mit Nudeln)|bún chả (grillezett sertéshús tésztával)|bún chả (babi panggang dengan bihun)|ブンチャー|bún chả (grillowana wieprzowina z makaronem)",
            "vývar|高汤|高湯|broth|bouillon|Brühe|alaplé|kaldu|スープ（だし）|bulion",
            "rýžové nudle phở|河粉面条|河粉麵條|phở rice noodles|nouilles de riz pour phở|Phở-Reisnudeln|phở rizstészta|mi beras phở|フォーの米麺|makaron ryżowy do phở",
        ],
    },
    "Phong tục truyền thống trong dịp Tết": {
        "title": "Typické vietnamské novoroční zvyky|越南代表性的春节习俗|越南代表性的春節習俗|Typical Vietnamese Lunar New Year Customs|Les coutumes typiques du Nouvel An vietnamien|Typische Bräuche zum vietnamesischen Neujahrsfest|Jellegzetes vietnámi holdújévi szokások|Tradisi khas Tahun Baru Imlek Vietnam|ベトナムの代表的なお正月の風習|Typowe wietnamskie zwyczaje noworoczne",
        "summary": "O lunárním Novém roce (Tết) se schází celá rodina, aby přivítala nový rok; patří k tomu zvyk xông đất – přijetí prvního hosta roku – a mâm ngũ quả, pět druhů ovoce na oltáři.|农历新年（Tết）全家团聚迎接新年，有迎接新年第一位访客的「踩年」（Xông đất）以及在祭台摆放五种水果的「五果盘」（Mâm ngũ quả）习俗。|農曆新年（Tết）全家團聚迎接新年，有迎接新年第一位訪客的「踩年」（Xông đất）以及在祭台擺放五種水果的「五果盤」（Mâm ngũ quả）習俗。|At the Lunar New Year (Tết) the whole family gathers to welcome the new year, with customs such as xông đất (receiving the first visitor of the year) and mâm ngũ quả (five kinds of fruit placed on the altar).|Au Nouvel An lunaire (Tết), toute la famille se réunit pour accueillir la nouvelle année, avec des coutumes comme le xông đất (accueillir le premier visiteur de l'année) et le mâm ngũ quả (plateau de cinq fruits sur l'autel).|Zum Mondneujahr (Tết) kommt die ganze Familie zusammen, um das neue Jahr zu begrüßen; dazu gehören Bräuche wie xông đất (der erste Besucher des Jahres) und mâm ngũ quả (fünf Früchte auf dem Altar).|A holdújévkor (Tết) az egész család összegyűlik az új év köszöntésére; szokás a xông đất (az év első látogatójának fogadása) és a mâm ngũ quả (ötféle gyümölcs az oltáron).|Saat Tahun Baru Imlek (Tết), seluruh keluarga berkumpul menyambut tahun baru, dengan tradisi xông đất (menerima tamu pertama tahun itu) dan mâm ngũ quả (lima jenis buah di altar).|旧正月（Tết）には家族全員が集まって新年を迎え、新年最初の客を迎えるソンダット（Xông đất）や、5種類の果物を祭壇に供えるマムグークア（Mâm ngũ quả）の風習があります。|W księżycowy Nowy Rok (Tết) cała rodzina gromadzi się, by powitać nowy rok; zwyczaje to m.in. xông đất (przyjęcie pierwszego gościa w roku) i mâm ngũ quả (pięć rodzajów owoców na ołtarzu).",
        "learningPoint": "Klade se důraz na štěstí a povahu prvního hosta roku a na oltář se pečlivě připravuje jídlo s prosbou o klid a prosperitu rodiny.|重视新年第一位访客的福气与品格，并在祭台上用心摆放食物，祈求家庭平安兴旺。|重視新年第一位訪客的福氣與品格，並在祭台上用心擺放食物，祈求家庭平安興旺。|People place great importance on the luck and character of the year's first visitor and carefully lay out food on the altar, wishing for the family's peace and prosperity.|On accorde une grande importance à la chance et au caractère du premier visiteur de l'année, et l'on dispose soigneusement des mets sur l'autel pour souhaiter paix et prospérité à la famille.|Man legt großen Wert auf das Glück und den Charakter des ersten Besuchers im Jahr und richtet sorgfältig Speisen auf dem Altar an, um Frieden und Wohlstand für die Familie zu erbitten.|Nagy jelentőséget tulajdonítanak az év első látogatója szerencséjének és jellemének, és gondosan ételt tesznek az oltárra a család békéjéért és boldogulásáért.|Keberuntungan dan watak tamu pertama tahun baru dianggap penting, dan makanan ditata dengan sepenuh hati di altar untuk memohon ketenteraman dan kemakmuran keluarga.|新年最初の客の福や人柄を重んじ、祭壇に心を込めて料理を供えて家族の平穏と繁栄を願います。|Dużą wagę przywiązuje się do szczęścia i charakteru pierwszego gościa w roku, a na ołtarzu starannie układa się jedzenie, prosząc o spokój i pomyślność rodziny.",
        "keywords": [
            "lunární Nový rok|农历新年|農曆新年|Lunar New Year|Nouvel An lunaire|Mondneujahr|holdújév|Tahun Baru Imlek|旧正月|księżycowy Nowy Rok",
            "první host v novém roce|新年第一位访客|新年第一位訪客|first visitor of the new year|premier visiteur de l'année|erster Besucher des neuen Jahres|az új év első látogatója|tamu pertama tahun baru|新年最初の訪問客|pierwszy gość w nowym roku",
            "mísa s pěti druhy ovoce (na oltář)|五果盘（祭台果盘）|五果盤（祭台果盤）|five-fruit tray (altar offering)|plateau des cinq fruits (autel)|Fünf-Früchte-Schale (Altar)|ötgyümölcsös tál (oltárra)|nampan lima buah (sesaji altar)|五果盆（祭壇の果物盛り）|taca pięciu owoców (na ołtarz)",
            "štěstí|幸运|幸運|good luck|chance|Glück|szerencse|keberuntungan|幸運|szczęście",
        ],
    },
    "Đám cưới và tiệc cưới ở Việt Nam": {
        "title": "Vietnamská svatba a svatební hostina|越南人的婚礼与喜宴|越南人的婚禮與喜宴|Vietnamese Weddings and Wedding Banquets|Mariages et banquets de noces au Vietnam|Vietnamesische Hochzeiten und Hochzeitsfeiern|Vietnámi esküvő és lakodalom|Pernikahan dan resepsi di Vietnam|ベトナム人の結婚式と披露宴|Wietnamski ślub i wesele",
        "summary": "Spolu se svatebním obřadem (Lễ Thành hôn) se hosté zvou na hostinu (Tiệc cưới), kde se jí a sledují gratulační vystoupení, a předávají se svatební dary v penězích (tiền mừng cưới).|在成婚礼（Lễ Thành hôn）之外，还会邀请宾客参加喜宴（Tiệc cưới），享用餐点与祝贺表演，并致送礼金（tiền mừng cưới）。|在成婚禮（Lễ Thành hôn）之外，還會邀請賓客參加喜宴（Tiệc cưới），享用餐點與祝賀表演，並致送禮金（tiền mừng cưới）。|Along with the wedding ceremony (Lễ Thành hôn), guests are invited to a banquet (Tiệc cưới) with a meal and celebratory performances, and they give wedding money (tiền mừng cưới).|Outre la cérémonie de mariage (Lễ Thành hôn), les invités sont conviés à un banquet (Tiệc cưới) avec repas et spectacles, et offrent de l'argent aux mariés (tiền mừng cưới).|Neben der Trauungszeremonie (Lễ Thành hôn) werden Gäste zu einem Festessen (Tiệc cưới) mit Essen und Darbietungen eingeladen und überreichen Geldgeschenke (tiền mừng cưới).|Az esküvői szertartás (Lễ Thành hôn) mellett a vendégeket lakodalomra (Tiệc cưới) hívják étkezéssel és ünnepi műsorral, ők pedig nászajándék-pénzt (tiền mừng cưới) adnak.|Selain upacara pernikahan (Lễ Thành hôn), tamu diundang ke resepsi (Tiệc cưới) untuk makan dan menikmati hiburan, serta memberikan uang hadiah (tiền mừng cưới).|結婚の儀式（Lễ Thành hôn）とともに披露宴（Tiệc cưới）に招待客を招いて食事や余興を楽しみ、ご祝儀（tiền mừng cưới）を渡します。|Oprócz ceremonii ślubnej (Lễ Thành hôn) gości zaprasza się na przyjęcie (Tiệc cưới) z posiłkiem i występami, a goście wręczają prezent w gotówce (tiền mừng cưới).",
        "learningPoint": "Pro pohodlí hostů se hostiny někdy pořádají odděleně v několika městech a novomanželé obcházejí všechny stoly a děkují.|为了方便宾客，有时会在多个城市分别举办喜宴，新郎新娘也会逐桌致谢。|為了方便賓客，有時會在多個城市分別舉辦喜宴，新郎新娘也會逐桌致謝。|For guests' convenience, banquets are sometimes held separately in several cities, and the bride and groom go around every table to thank everyone.|Pour faciliter la venue des invités, les banquets se tiennent parfois dans plusieurs villes, et les mariés passent à chaque table pour remercier.|Zur Bequemlichkeit der Gäste finden Feiern manchmal getrennt in mehreren Städten statt, und das Brautpaar geht an jeden Tisch, um sich zu bedanken.|A vendégek kényelméért néha több városban külön tartanak lakodalmat, és a jegyespár minden asztalhoz odamegy megköszönni a részvételt.|Demi kenyamanan tamu, resepsi kadang diadakan terpisah di beberapa kota, dan pengantin berkeliling ke setiap meja untuk berterima kasih.|招待客の便宜のために複数の都市で披露宴を分けて開くこともあり、新郎新婦はすべてのテーブルを回って感謝を伝えます。|Dla wygody gości wesela bywają organizowane osobno w kilku miastach, a para młoda obchodzi wszystkie stoły, dziękując gościom.",
        "keywords": [
            "svatba|婚礼|婚禮|wedding|mariage|Hochzeit|esküvő|pernikahan|結婚式|ślub",
            "svatební hostina|喜宴|喜宴|wedding banquet|banquet de noces|Hochzeitsfeier|lakodalom|resepsi pernikahan|結婚披露宴|przyjęcie weselne",
            "svatební dar v penězích|礼金|禮金|wedding gift money|argent offert aux mariés|Geldgeschenk zur Hochzeit|nászajándék-pénz|uang hadiah pernikahan|ご祝儀|prezent ślubny w gotówce",
            "snubní prsten|结婚戒指|結婚戒指|wedding ring|alliance|Ehering|jegygyűrű|cincin kawin|結婚指輪|obrączka",
        ],
    },
    "Ứng dụng di động thay đổi tiêu dùng": {
        "title": "Jak mobilní aplikace změnily nákupní zvyky Vietnamců|智能手机应用改变的越南消费模式|智慧型手機應用程式改變的越南消費模式|How Smartphone Apps Changed Vietnamese Consumer Habits|Comment les applications mobiles ont changé la consommation au Vietnam|Wie Smartphone-Apps das Konsumverhalten in Vietnam verändert haben|Hogyan változtatták meg az okostelefonos alkalmazások a vietnámi fogyasztást|Aplikasi ponsel yang mengubah pola konsumsi Vietnam|スマートフォンアプリが変えたベトナムの消費パターン|Jak aplikacje mobilne zmieniły wietnamskie nawyki konsumenckie",
        "summary": "S rozšířením aplikací na objednávání motorkových taxi a rozvoz jídla se způsob, jakým se Vietnamci přepravují a každodenně nakupují, rychle digitalizoval.|随着摩托车叫车与外卖应用的普及，越南人的出行与日常消费方式迅速数字化。|隨著機車叫車與外送應用程式的普及，越南人的出行與日常消費方式迅速數位化。|As motorbike-taxi and food-delivery apps became widespread, the way Vietnamese people get around and shop day to day has rapidly gone digital.|Avec la généralisation des applications de moto-taxi et de livraison de repas, les déplacements et la consommation quotidienne des Vietnamiens se sont rapidement numérisés.|Mit der Verbreitung von Motorradtaxi- und Essenslieferdiensten per App haben sich Mobilität und Alltagskonsum der Vietnamesen rasch digitalisiert.|A motoros taxi- és ételkiszállító alkalmazások elterjedésével a vietnámiak közlekedése és mindennapi vásárlása gyorsan digitálissá vált.|Seiring populernya aplikasi ojek dan pesan-antar makanan, cara orang Vietnam bepergian dan berbelanja sehari-hari cepat beralih ke digital.|バイクタクシーの配車や料理の配達アプリが普及し、ベトナムの人々の移動や日常の消費の仕方が急速にデジタル化しました。|Wraz z upowszechnieniem się aplikacji do zamawiania mototaksówek i dostaw jedzenia sposób poruszania się i codzienne zakupy Wietnamczyków szybko się zdigitalizowały.",
        "learningPoint": "Ve městech s častými dopravními zácpami se služby přepravy a rozvozu na motorkách staly nezbytnou součástí života.|在交通拥堵严重的城市，以摩托车为主的叫车与外卖服务已成为生活必需。|在交通壅塞嚴重的城市，以機車為主的叫車與外送服務已成為生活必需。|In cities with heavy traffic, motorbike-based ride-hailing and delivery services have become an essential part of life.|Dans les villes très embouteillées, les services de transport et de livraison à moto sont devenus indispensables au quotidien.|In Städten mit viel Stau sind Fahr- und Lieferdienste per Motorrad zu einem unverzichtbaren Teil des Alltags geworden.|A zsúfolt forgalmú városokban a motoros fuvar- és kiszállítási szolgáltatások az élet nélkülözhetetlen részévé váltak.|Di kota yang sering macet, layanan ojek dan antar berbasis sepeda motor telah menjadi kebutuhan pokok sehari-hari.|渋滞の多い都市では、バイクを使った配車や配達サービスが生活に欠かせない手段として定着しました。|W zakorkowanych miastach usługi przewozu i dostaw na motocyklach stały się niezbędnym elementem życia.",
        "keywords": [
            "motorkové taxi přes aplikaci|网约摩托车|網約機車|app-based motorbike taxi|moto-taxi par application|Motorradtaxi per App|alkalmazással hívható motoros taxi|ojek online|配車アプリのバイクタクシー|mototaksówka z aplikacji",
            "doručení, rozvoz|送货，外卖|送貨，外送|delivery|livraison|Lieferung|kiszállítás|pengantaran|配達|dostawa",
            "objednat jízdu|叫车，订车|叫車，訂車|to book a ride|réserver un véhicule|eine Fahrt buchen|fuvart rendelni|memesan kendaraan|配車を予約する|zamówić przejazd",
            "pohodlný, praktický|方便|方便|convenient|pratique|bequem, praktisch|kényelmes, praktikus|praktis, nyaman|便利だ|wygodny",
        ],
    },
    "Thời tiết và khí hậu Việt Nam": {
        "title": "Počasí a podnebí na severu a jihu Vietnamu|越南南北的天气与气候特点|越南南北的天氣與氣候特點|Weather and Climate in Northern and Southern Vietnam|Météo et climat du nord et du sud du Vietnam|Wetter und Klima im Norden und Süden Vietnams|Időjárás és éghajlat Észak- és Dél-Vietnámban|Cuaca dan iklim di utara dan selatan Vietnam|ベトナム南北の天気と気候の特徴|Pogoda i klimat na północy i południu Wietnamu",
        "summary": "Díky dlouhému území táhnoucímu se 1 650 km od severu k jihu má sever čtyři roční období (jaro, léto, podzim, zima), zatímco jih má dvě výrazná období: období dešťů a období sucha.|越南南北绵延1,650公里，北部有春夏秋冬四季，南部则雨季与旱季两季分明。|越南南北綿延1,650公里，北部有春夏秋冬四季，南部則雨季與旱季兩季分明。|With a long territory stretching 1,650 km north to south, the north has four seasons (spring, summer, autumn, winter), while the south has two distinct seasons: rainy and dry.|Avec un territoire qui s'étire sur 1 650 km du nord au sud, le nord connaît quatre saisons (printemps, été, automne, hiver), tandis que le sud a deux saisons marquées : la saison des pluies et la saison sèche.|Durch die 1.650 km lange Nord-Süd-Ausdehnung hat der Norden vier Jahreszeiten (Frühling, Sommer, Herbst, Winter), der Süden dagegen zwei ausgeprägte: Regenzeit und Trockenzeit.|Az északról délre 1650 km hosszan elnyúló ország északi részén négy évszak van (tavasz, nyár, ősz, tél), délen viszont két jól elkülönülő: az esős és a száraz évszak.|Dengan wilayah memanjang 1.650 km dari utara ke selatan, utara memiliki empat musim (semi, panas, gugur, dingin), sedangkan selatan memiliki dua musim yang jelas: musim hujan dan musim kemarau.|南北1,650kmにわたる細長い地形で、北部には四季（春・夏・秋・冬）があり、南部は雨季と乾季の二つの季節がはっきりしています。|Dzięki długiemu terytorium ciągnącemu się 1650 km z północy na południe północ ma cztery pory roku (wiosnę, lato, jesień, zimę), a południe dwie wyraźne: porę deszczową i porę suchą.",
        "learningPoint": "Sever včetně Hanoje se v zimě ochladí pod 10 °C, zatímco jih včetně Ho Či Minova Města má po celý rok tropické podnebí.|包括河内在内的北部冬季会冷到10度以下，而包括胡志明市在内的南部全年维持热带气候。|包括河內在內的北部冬季會冷到10度以下，而包括胡志明市在內的南部全年維持熱帶氣候。|The north, including Hanoi, gets chilly in winter, below 10°C, while the south, including Ho Chi Minh City, keeps a tropical climate all year round.|Le nord, dont Hanoï, se rafraîchit en hiver sous les 10 °C, tandis que le sud, dont Hô Chi Minh-Ville, garde un climat tropical toute l'année.|Der Norden mit Hanoi wird im Winter kühl, unter 10 °C, während der Süden mit Ho-Chi-Minh-Stadt das ganze Jahr über tropisches Klima hat.|Az észak, köztük Hanoi, télen 10 °C alá hűl, míg a dél, köztük Ho Si Minh-város, egész évben trópusi éghajlatú.|Wilayah utara, termasuk Hanoi, menjadi dingin di bawah 10°C pada musim dingin, sedangkan selatan, termasuk Kota Ho Chi Minh, beriklim tropis sepanjang tahun.|ハノイをはじめとする北部は冬に10度以下まで冷え込みますが、ホーチミンをはじめとする南部は一年中熱帯気候です。|Północ, w tym Hanoi, zimą ochładza się poniżej 10°C, a południe, w tym Ho Chi Minh, przez cały rok ma klimat tropikalny.",
        "keywords": [
            "podnebí|气候|氣候|climate|climat|Klima|éghajlat|iklim|気候|klimat",
            "období dešťů|雨季|雨季|rainy season|saison des pluies|Regenzeit|esős évszak|musim hujan|雨季|pora deszczowa",
            "období sucha|旱季|旱季|dry season|saison sèche|Trockenzeit|száraz évszak|musim kemarau|乾季|pora sucha",
            "počasí|天气|天氣|weather|temps, météo|Wetter|időjárás|cuaca|天気|pogoda",
        ],
    },
    "Hệ thống bệnh viện công và tư": {
        "title": "Veřejné a soukromé nemocnice ve Vietnamu|越南的公立医院与私立医院|越南的公立醫院與私立醫院|Public and Private Hospitals in Vietnam|Hôpitaux publics et privés au Vietnam|Öffentliche und private Krankenhäuser in Vietnam|Állami és magánkórházak Vietnámban|Rumah sakit negeri dan swasta di Vietnam|ベトナムの公立病院と私立病院|Szpitale publiczne i prywatne w Wietnamie",
        "summary": "Veřejné nemocnice mají nízké poplatky a mnoho zkušených lékařů, ale dlouhé čekací doby; soukromé nemocnice jsou rychlé a příjemné, ale dražší.|公立医院诊疗费低廉、医术好的医生多，但等候时间长；私立医院快速舒适，但费用较高。|公立醫院診療費低廉、醫術好的醫師多，但等候時間長；私立醫院快速舒適，但費用較高。|Public hospitals are cheap and have many skilled doctors but long waits, while private hospitals are fast and comfortable but more expensive.|Les hôpitaux publics sont bon marché et comptent de nombreux médecins compétents, mais l'attente y est longue ; les hôpitaux privés sont rapides et agréables, mais plus chers.|Öffentliche Krankenhäuser sind günstig und haben viele fähige Ärzte, aber lange Wartezeiten; private Krankenhäuser sind schnell und angenehm, aber teurer.|Az állami kórházakban olcsó a kezelés és sok a jó orvos, de hosszú a várakozás; a magánkórházak gyorsak és kényelmesek, de drágábbak.|Rumah sakit negeri murah dan memiliki banyak tenaga medis andal tetapi antreannya lama, sedangkan rumah sakit swasta cepat dan nyaman tetapi biayanya tinggi.|公立病院は診療費が安く腕の良い医師も多いものの待ち時間が長く、私立病院は早くて快適ですが診療費が高めです。|Szpitale publiczne są tanie i mają wielu doświadczonych lekarzy, ale długo się czeka; prywatne są szybkie i komfortowe, lecz droższe.",
        "learningPoint": "Podle situace se na odbornou léčbu volí velké veřejné nemocnice a na rychlou a pohodlnou službu soukromé.|依情况不同，专业治疗会选择大型公立医院，快速便利的服务则选择私立医院。|依情況不同，專業治療會選擇大型公立醫院，快速便利的服務則選擇私立醫院。|Depending on the situation, people choose large public hospitals for specialized treatment and private hospitals for fast, convenient service.|Selon la situation, on choisit un grand hôpital public pour un traitement spécialisé et un hôpital privé pour un service rapide et pratique.|Je nach Situation wählt man für Fachbehandlungen große öffentliche Krankenhäuser und für schnellen, bequemen Service private.|A helyzettől függően szakellátásra a nagy állami kórházakat, gyors és kényelmes szolgáltatásra a magánkórházakat választják.|Tergantung situasinya, orang memilih rumah sakit negeri besar untuk perawatan khusus dan rumah sakit swasta untuk layanan yang cepat dan praktis.|状況に応じて、専門的な治療には大型の公立病院を、迅速で便利なサービスには私立病院を選びます。|W zależności od sytuacji na specjalistyczne leczenie wybiera się duże szpitale publiczne, a na szybką i wygodną obsługę – prywatne.",
        "keywords": [
            "veřejná nemocnice|公立医院|公立醫院|public hospital|hôpital public|öffentliches Krankenhaus|állami kórház|rumah sakit negeri|公立病院|szpital publiczny",
            "soukromá nemocnice|私立医院|私立醫院|private hospital|hôpital privé|Privatkrankenhaus|magánkórház|rumah sakit swasta|私立病院|szpital prywatny",
            "nechat se vyšetřit|看病，就诊|看病，就診|to see a doctor|consulter un médecin|sich untersuchen lassen|orvosi vizsgálatra menni|berobat|診察を受ける|iść do lekarza",
            "náklady|费用|費用|cost|coût, frais|Kosten|költség|biaya|費用|koszt",
        ],
    },
    "Các lễ hội đặc sắc ở Việt Nam": {
        "title": "Zajímavé regionální slavnosti ve Vietnamu|越南有趣的地方节庆|越南有趣的地方節慶|Interesting Regional Festivals in Vietnam|Des fêtes régionales remarquables au Vietnam|Interessante regionale Feste in Vietnam|Érdekes vietnámi helyi fesztiválok|Festival daerah yang menarik di Vietnam|ベトナムの興味深い地域のお祭り|Ciekawe regionalne święta w Wietnamie",
        "summary": "Slavnostně se konají tradiční slavnosti, například slavnost Đền Hùng (Lễ hội Đền Hùng) 10. dne 3. lunárního měsíce na počest zakladatelů země nebo slavnost Lim (Hội Lim) v severní provincii Bắc Ninh, zaměřená na lidové písně quan họ.|每逢农历三月初十，有纪念建国始祖的雄王庙会（Lễ hội Đền Hùng），北部北宁省也有以官贺民歌为中心的林庙会（Hội Lim）等传统节庆隆重举行。|每逢農曆三月初十，有紀念建國始祖的雄王廟會（Lễ hội Đền Hùng），北部北寧省也有以官賀民歌為中心的林廟會（Hội Lim）等傳統節慶隆重舉行。|Traditional festivals are held on a grand scale, such as the Hùng Temple Festival (Lễ hội Đền Hùng) on the 10th day of the 3rd lunar month honoring the nation's founders, and the Lim Festival (Hội Lim) in northern Bắc Ninh province, centered on quan họ folk songs.|De grandes fêtes traditionnelles ont lieu, comme la fête du temple Hùng (Lễ hội Đền Hùng) le 10e jour du 3e mois lunaire en l'honneur des fondateurs du pays, ou la fête de Lim (Hội Lim) dans la province de Bắc Ninh, centrée sur les chants populaires quan họ.|Traditionelle Feste werden groß gefeiert, etwa das Hùng-Tempel-Fest (Lễ hội Đền Hùng) am 10. Tag des 3. Mondmonats zu Ehren der Staatsgründer oder das Lim-Fest (Hội Lim) in der nördlichen Provinz Bắc Ninh mit Quan-họ-Volksliedern.|Nagyszabású hagyományos ünnepeket tartanak, például a Hùng-templom ünnepét (Lễ hội Đền Hùng) a 3. holdhónap 10. napján az ország alapítóinak tiszteletére, vagy az északi Bắc Ninh tartományban a quan họ népdalokra épülő Lim-ünnepet (Hội Lim).|Festival tradisional digelar meriah, seperti Festival Kuil Hùng (Lễ hội Đền Hùng) pada tanggal 10 bulan 3 Imlek untuk menghormati para pendiri bangsa, dan Festival Lim (Hội Lim) di Provinsi Bắc Ninh di utara yang berpusat pada lagu rakyat quan họ.|旧暦3月10日に建国の祖をたたえるフン王廟祭り（Lễ hội Đền Hùng）や、北部バクニン省で民謡クアンホーを中心に行われるリム祭り（Hội Lim）などの伝統的な祭りが盛大に開かれます。|Hucznie obchodzi się tradycyjne święta, np. święto świątyni Hùng (Lễ hội Đền Hùng) 10. dnia 3. miesiąca księżycowego ku czci założycieli kraju czy święto Lim (Hội Lim) w północnej prowincji Bắc Ninh, poświęcone pieśniom ludowym quan họ.",
        "learningPoint": "Jádrem slavností jsou lidové obřady a hry, které posilují úctu k předkům a soudržnost společenství.|加强祖先崇拜与社区团结的民俗仪式和民俗游戏是节庆的核心。|加強祖先崇拜與社區團結的民俗儀式和民俗遊戲是節慶的核心。|At the heart of the festivals are folk rites and traditional games that strengthen ancestor veneration and community bonds.|Au cœur de ces fêtes se trouvent des rites et jeux populaires qui renforcent le culte des ancêtres et la cohésion de la communauté.|Im Mittelpunkt der Feste stehen volkstümliche Rituale und Spiele, die die Ahnenverehrung und den Zusammenhalt der Gemeinschaft stärken.|Az ünnepek lényegét az ősök tiszteletét és a közösség összetartását erősítő népi szertartások és játékok adják.|Inti festival adalah upacara dan permainan rakyat yang memperkuat penghormatan kepada leluhur dan kebersamaan masyarakat.|祖先崇拝と共同体の結束を固める民俗儀式や民俗遊びが祭りの中心です。|Sercem świąt są ludowe obrzędy i zabawy, które umacniają cześć dla przodków i więzi wspólnoty.",
        "keywords": [
            "slavnost, festival|节庆，庙会|節慶，廟會|festival|fête, festival|Fest|ünnep, fesztivál|festival|祭り|święto, festiwal",
            "chrám krále Hùnga|雄王庙|雄王廟|Hùng Temple|temple Hùng|Hùng-Tempel|Hùng-templom|Kuil Hùng|フン王廟|świątynia Hùng",
            "lidový|民俗|民俗|folk|populaire, folklorique|volkstümlich|népi|rakyat|民俗|ludowy",
            "tradice|传统|傳統|tradition|tradition|Tradition|hagyomány|tradisi|伝統|tradycja",
        ],
    },
    "Văn hóa mạng xã hội tại Việt Nam": {
        "title": "Čilá komunikace Vietnamců na sociálních sítích|越南人活跃的社群网络交流|越南人活躍的社群網路交流|Vietnamese People's Lively Social Media Communication|L'intense communication des Vietnamiens sur les réseaux sociaux|Die rege Kommunikation der Vietnamesen in sozialen Netzwerken|A vietnámiak élénk kommunikációja a közösségi médiában|Komunikasi aktif orang Vietnam di media sosial|ベトナムの人々の活発なSNSコミュニケーション|Żywa komunikacja Wietnamczyków w mediach społecznościowych",
        "summary": "Vietnamci tradičně kladou důraz na vztahy, a proto čile komunikují a sdílejí každodenní život i výročí přes sociální sítě jako Facebook a Zalo.|越南人传统上重视人际关系，透过脸书、Zalo 等社群网络积极分享日常与纪念日并交流。|越南人傳統上重視人際關係，透過臉書、Zalo 等社群網路積極分享日常與紀念日並交流。|Vietnamese people traditionally value relationships, so they actively communicate by sharing daily life and special occasions on social networks such as Facebook and Zalo.|Attachés aux relations humaines, les Vietnamiens communiquent beaucoup en partageant leur quotidien et leurs fêtes sur les réseaux sociaux comme Facebook et Zalo.|Vietnamesen legen traditionell großen Wert auf Beziehungen und teilen ihren Alltag und besondere Anlässe rege über soziale Netzwerke wie Facebook und Zalo.|A vietnámiak hagyományosan fontosnak tartják a kapcsolatokat, ezért a Facebookon, a Zalón és más közösségi oldalakon élénken megosztják mindennapjaikat és ünnepeiket.|Orang Vietnam secara tradisional menjunjung hubungan, sehingga aktif berkomunikasi dengan membagikan keseharian dan hari peringatan lewat media sosial seperti Facebook dan Zalo.|ベトナムでは伝統的に人間関係を重んじ、フェイスブックやザロ（Zalo）などのSNSで日常や記念日を共有して活発に交流します。|Wietnamczycy tradycyjnie cenią relacje, dlatego żywo komunikują się, dzieląc się codziennością i ważnymi okazjami w serwisach takich jak Facebook i Zalo.",
        "learningPoint": "Zejména Zalo slouží jako národní komunikátor pro pracovní i běžné zprávy a má velmi vysokou míru používání.|尤其 Zalo 在工作与日常讯息中扮演国民通讯软件的角色，使用率很高。|尤其 Zalo 在工作與日常訊息中扮演國民通訊軟體的角色，使用率很高。|Zalo in particular serves as the national messenger for work and everyday messages, with a very high usage rate.|Zalo, en particulier, fait office de messagerie nationale pour le travail comme pour la vie quotidienne, avec un taux d'utilisation très élevé.|Besonders Zalo dient als nationaler Messenger für berufliche und alltägliche Nachrichten und wird sehr häufig genutzt.|Különösen a Zalo tölti be a nemzeti üzenetküldő szerepét munkában és a hétköznapokban, igen magas használati aránnyal.|Terutama Zalo berperan sebagai aplikasi pesan nasional untuk urusan kerja maupun sehari-hari, dengan tingkat penggunaan yang tinggi.|特にZaloは仕事や日常のメッセージで国民的メッセンジャーの役割を果たし、利用率が高いです。|Szczególnie Zalo pełni rolę narodowego komunikatora w pracy i na co dzień i jest bardzo powszechnie używany.",
        "keywords": [
            "sociální sítě|社群网络，社交媒体|社群網路，社群媒體|social networks / social media|réseaux sociaux|soziale Netzwerke|közösségi média|media sosial|SNS、ソーシャルメディア|media społecznościowe",
            "propojit, spojit|连接|連接|to connect|relier, se connecter|verbinden|összekapcsolni|terhubung|つながる|łączyć",
            "sdílet|分享|分享|to share|partager|teilen|megosztani|berbagi|共有する|udostępniać, dzielić się",
            "přátelé|朋友|朋友|friends|amis|Freunde|barátok|teman-teman|友達|przyjaciele",
        ],
    },
    "Các kỳ thi chứng chỉ tiếng Việt": {
        "title": "Zkoušky a certifikáty z vietnamštiny|越南语认证考试与证书|越南語認證考試與證書|Vietnamese Proficiency Tests and Certificates|Examens et certificats de vietnamien|Vietnamesisch-Prüfungen und Zertifikate|Vietnámi nyelvvizsgák és bizonyítványok|Ujian dan sertifikat kemahiran bahasa Vietnam|ベトナム語の認定試験と資格|Egzaminy i certyfikaty z języka wietnamskiego",
        "summary": "K oficiálnímu ověření znalosti vietnamštiny slouží mluvní zkoušky OPI/OPIc, komplexní zkouška ABC (pořádaná filozofickými fakultami v Hanoji a Ho Či Minově Městě), FLEX a další.|为获得越南语能力的正式认证，有以口说为主的 OPI/OPIc、综合评价的 ABC 考试（由河内/胡志明市人文大学主办）、FLEX 等。|為獲得越南語能力的正式認證，有以口說為主的 OPI/OPIc、綜合評價的 ABC 考試（由河內/胡志明市人文大學主辦）、FLEX 等。|To have Vietnamese proficiency officially certified, there are speaking-focused OPI/OPIc tests, the comprehensive ABC exam (run by the universities of social sciences and humanities in Hanoi and Ho Chi Minh City), FLEX and others.|Pour faire certifier officiellement son niveau de vietnamien, il existe les tests oraux OPI/OPIc, l'examen complet ABC (organisé par les universités de sciences humaines de Hanoï et de Hô Chi Minh-Ville), le FLEX, etc.|Zur offiziellen Bescheinigung von Vietnamesischkenntnissen gibt es die sprechorientierten Tests OPI/OPIc, die umfassende ABC-Prüfung (ausgerichtet von den geisteswissenschaftlichen Universitäten in Hanoi und Ho-Chi-Minh-Stadt), FLEX und weitere.|A vietnámi nyelvtudás hivatalos igazolására ott vannak a beszédközpontú OPI/OPIc vizsgák, az átfogó ABC vizsga (a hanoi és Ho Si Minh-városi bölcsészettudományi egyetemek szervezésében), a FLEX és mások.|Untuk mendapat pengakuan resmi atas kemampuan bahasa Vietnam, tersedia tes berbasis berbicara OPI/OPIc, ujian komprehensif ABC (diselenggarakan universitas ilmu sosial dan humaniora di Hanoi/Kota Ho Chi Minh), FLEX, dan lainnya.|ベトナム語の実力を公式に認定してもらうため、会話中心のOPI/OPIc、総合評価のABC試験（ハノイ／ホーチミン人文社会科学大学主催）、FLEXなどが実施されています。|Aby oficjalnie potwierdzić znajomość wietnamskiego, można zdawać ustne testy OPI/OPIc, kompleksowy egzamin ABC (organizowany przez uniwersytety nauk społecznych i humanistycznych w Hanoi i Ho Chi Minh), FLEX i inne.",
        "learningPoint": "Podle cíle, například zaměstnání nebo studia v zahraničí, se volí buď mluvní zkouška, nebo komplexní zkouška ze všech čtyř dovedností.|依就业、留学等目的，选择以口说为主的考试或四项能力综合评价的考试报考。|依就業、留學等目的，選擇以口說為主的考試或四項能力綜合評價的考試報考。|Depending on the goal, such as employment or study abroad, people choose either a speaking-focused test or a comprehensive test of all four skills.|Selon l'objectif (emploi, études à l'étranger…), on choisit un examen centré sur l'oral ou un examen complet des quatre compétences.|Je nach Ziel, etwa Beruf oder Auslandsstudium, wählt man eine Sprechprüfung oder eine umfassende Prüfung aller vier Fertigkeiten.|A céltól – például munkavállalás vagy külföldi tanulmányok – függően beszédközpontú vagy mind a négy készséget mérő átfogó vizsgát választanak.|Sesuai tujuan seperti bekerja atau studi di luar negeri, orang memilih ujian yang berfokus pada berbicara atau ujian komprehensif empat keterampilan.|就職や留学など目的に応じて、会話中心の試験か4技能を総合評価する試験を選んで受験します。|W zależności od celu, np. pracy lub studiów za granicą, wybiera się egzamin ustny albo kompleksowy egzamin ze wszystkich czterech umiejętności.",
        "keywords": [
            "certifikát, osvědčení|证书，结业证书|證書，結業證書|certificate|certificat, attestation|Zertifikat, Nachweis|bizonyítvány, tanúsítvány|sertifikat|資格証、修了証|certyfikat, zaświadczenie",
            "zkouška|考试|考試|exam|examen|Prüfung|vizsga|ujian|試験|egzamin",
            "dovednost|技能|技能|skill|compétence|Fertigkeit|készség|keterampilan|技能、スキル|umiejętność",
            "pohovor, rozhovor|面试，访谈|面試，訪談|interview|entretien|Vorstellungsgespräch, Interview|interjú, állásinterjú|wawancara|面接、インタビュー|rozmowa kwalifikacyjna, wywiad",
        ],
    },
    "Thuê và mua bất động sản ở Việt Nam": {
        "title": "Nájem bydlení ve Vietnamu|越南人的房屋租赁文化|越南人的房屋租賃文化|Renting Homes in Vietnam|La location immobilière au Vietnam|Wohnungsmiete in Vietnam|Lakásbérlés Vietnámban|Budaya sewa properti di Vietnam|ベトナムの不動産賃貸文化|Wynajem mieszkań w Wietnamie",
        "summary": "Ve městech je běžný pronájem malých bytů (chung cư mini) a bytů v domech (căn hộ); smlouvy se skládají z kauce (tiền đặt cọc) a měsíčního nájmu (tiền thuê nhà).|城市地区的小型公寓（chung cư mini）或公寓（căn hộ）租赁很普遍，契约由押金（tiền đặt cọc）与月租（tiền thuê nhà）构成。|城市地區的小型公寓（chung cư mini）或公寓（căn hộ）租賃很普遍，契約由押金（tiền đặt cọc）與月租（tiền thuê nhà）構成。|In cities, renting mini apartments (chung cư mini) and apartments (căn hộ) is common, with contracts built around a deposit (tiền đặt cọc) and monthly rent (tiền thuê nhà).|En ville, la location de mini-appartements (chung cư mini) et d'appartements (căn hộ) est courante, avec des contrats fondés sur une caution (tiền đặt cọc) et un loyer mensuel (tiền thuê nhà).|In Städten ist die Miete kleiner Wohnungen (chung cư mini) und Apartments (căn hộ) verbreitet; Verträge bestehen aus Kaution (tiền đặt cọc) und Monatsmiete (tiền thuê nhà).|A városokban gyakori a minilakások (chung cư mini) és lakások (căn hộ) bérlése; a szerződés kaucióból (tiền đặt cọc) és havi bérleti díjból (tiền thuê nhà) áll.|Di perkotaan, menyewa apartemen mini (chung cư mini) atau apartemen (căn hộ) sangat umum, dengan kontrak berupa uang jaminan (tiền đặt cọc) dan sewa bulanan (tiền thuê nhà).|都市部ではワンルーム（chung cư mini）やアパート（căn hộ）の賃貸が盛んで、保証金（tiền đặt cọc）と月額家賃（tiền thuê nhà）の契約形態をとります。|W miastach powszechny jest wynajem mini-mieszkań (chung cư mini) i mieszkań (căn hộ), a umowa obejmuje kaucję (tiền đặt cọc) i czynsz miesięczny (tiền thuê nhà).",
        "learningPoint": "Protože mnoho bytů je plně zařízených (đầy đủ nội thất), je stěhování pro cizince i mladé lidi poměrně snadné.|许多房屋家具齐全（đầy đủ nội thất），外国人和年轻人搬家居住相对方便。|許多房屋家具齊全（đầy đủ nội thất），外國人和年輕人搬家居住相對方便。|Because many homes come fully furnished (đầy đủ nội thất), moving is relatively easy for foreigners and young people.|Comme beaucoup de logements sont entièrement meublés (đầy đủ nội thất), déménager est relativement facile pour les étrangers et les jeunes.|Da viele Wohnungen voll möbliert sind (đầy đủ nội thất), ist ein Umzug für Ausländer und junge Leute relativ einfach.|Mivel sok lakás teljesen bútorozott (đầy đủ nội thất), a külföldiek és a fiatalok viszonylag könnyen költözhetnek.|Karena banyak hunian sudah lengkap berperabot (đầy đủ nội thất), orang asing dan anak muda relatif mudah berpindah tempat tinggal.|家具付き（đầy đủ nội thất）の住宅が多いため、外国人や若者の住み替えが比較的便利です。|Ponieważ wiele mieszkań jest w pełni umeblowanych (đầy đủ nội thất), przeprowadzka jest stosunkowo łatwa dla obcokrajowców i młodych ludzi.",
        "keywords": [
            "pronajmout si dům/byt|租房|租房|to rent a home|louer un logement|eine Wohnung mieten|lakást bérelni|menyewa rumah|家を借りる|wynająć mieszkanie",
            "složit zálohu, kauci|付押金|付押金|to pay a deposit|verser une caution|eine Kaution hinterlegen|kauciót fizetni|membayar uang jaminan|保証金を払う|wpłacić kaucję",
            "byt|公寓|公寓|apartment|appartement|Wohnung|lakás|apartemen|アパート、マンション|mieszkanie",
            "smlouva|合同|合約|contract|contrat|Vertrag|szerződés|kontrak|契約書|umowa",
        ],
    },
}


# The five long articles (title / subtitle / paragraphs) already have ko/zh/en/ja/de/fr/pl; these fill
# only the languages they lack. Keyed by the English title. Row order: cs | zh_cn | hu | id
CULTURE_ARTICLE_AI_LANGS = ["cs", "zh_cn", "hu", "id"]
CULTURE_ARTICLE_AI = {
    "Various Noodle Dishes of Vietnam": {
        "title": "Rozmanitá vietnamská nudlová jídla|越南多样的面食料理|Vietnám sokféle tésztaétele|Ragam hidangan mi Vietnam",
        "subtitle": "Je phở, které jím, ze severu, nebo z jihu?|我吃的河粉是北部的还是南部的呢？|A phở, amit eszem, északi vagy déli?|Apakah phở yang saya makan berasal dari utara atau selatan?",
        "paragraphs": [
            "Klíčky, hovězí maso, osvěžující vývar a nudle se spojují v čistou a svěží chuť phở. Phở je jídlo, které Vietnamci milují; nudle jsou poněkud silnější a vývar bývá sytý. K phở se kromě koriandru přidává různá zelenina a na severu je také zvykem namáčet do phở dlouhé smažené tyčinky z těsta.|豆芽菜与牛肉，配上清爽汤头与面条融为一体，呈现清爽利落的滋味，这就是河粉。河粉是越南人喜爱的美食，面条稍粗，汤头也偏浓郁。吃河粉时，除了香菜之外还会加入各种蔬菜，在北部地区，人们也会把河粉搭配长条油条一起蘸着吃。|A babcsíra és a marhahús a frissítő alaplében a tésztával együtt adja a phở tiszta, üde ízét. A phở a vietnámiak kedvenc étele; a tészta kissé vastagabb, az alaplé pedig inkább sűrű. Phở evésekor a koriander mellé sokféle zöldséget tesznek, északon pedig az is szokás, hogy hosszú olajban sült tésztarudakat mártogatnak bele.|Tauge dan daging sapi berpadu dengan mi dalam kuah yang segar, menghasilkan rasa phở yang bersih dan menyegarkan. Phở adalah hidangan kesukaan orang Vietnam; minya agak tebal dan kuahnya cenderung pekat. Saat makan phở, orang menambahkan berbagai sayuran selain ketumbar, dan di wilayah utara juga lazim mencelupkan cakwe panjang ke dalam phở.",
            "Phở bylo původně jídlem Hanoje a dalších oblastí severního Vietnamu. Sever kladl velký důraz na zemědělství jako základ státu, a proto zakazoval porážku skotu a prodej hovězího masa. Vývar se tedy vařil z kuřecích kostí a měl lehkou, jemnou chuť.|河粉原本是河内等越南北部地区的食物。北部地区因重视作为国家根基的农业，因此禁止屠宰牛只与贩售牛肉，所以汤头多以鸡骨熬煮而成，味道较为清淡。|A phở eredetileg Hanoi és Észak-Vietnám más területeinek étele volt. Észak nagy jelentőséget tulajdonított a mezőgazdaságnak mint az ország alapjának, ezért tiltotta a szarvasmarhák levágását és a marhahús árusítását. Az alaplevet így csirkecsontból főzték, könnyű, enyhe ízűre.|Phở awalnya adalah makanan dari Hanoi dan wilayah Vietnam utara lainnya. Karena wilayah utara sangat menjunjung pertanian sebagai fondasi negara, penyembelihan sapi dan penjualan daging sapi dilarang. Akibatnya, kuahnya dibuat dari rebusan tulang ayam sehingga rasanya ringan dan lembut.",
            "Jídla na jihu bývají nasládlá, a proto je tam i vývar phở mírně sladký. Na rozdíl od severu se vývar připravuje dlouhým vařením hovězích kostí. Lidé do něj přimíchávají limetku, klíčky a různé bylinky a jedí ho i s rozmanitými omáčkami.|南部地区的食物大多带有甜味，因此河粉的汤头也偏甜。此外，和北部不同的是，南部的汤头是用牛骨长时间熬煮而成。吃的时候不仅会加入青柠、豆芽菜及各种香草，还会搭配各式酱料一起享用。|A déli ételek inkább édeskések, így ott a phở alaplé is kissé édes. Északkal ellentétben az alaplevet marhacsontból, hosszan főzve készítik. Lime-ot, babcsírát és különféle fűszernövényeket kevernek bele, és sokféle mártással is fogyasztják.|Makanan di wilayah selatan cenderung manis, sehingga kuah phở di sana juga agak manis. Selain itu, berbeda dengan utara, kuahnya dibuat dengan merebus tulang sapi dalam waktu lama. Orang tidak hanya mencampurkan jeruk nipis, tauge, dan aneka daun herba, tetapi juga menikmatinya dengan berbagai saus cocolan.",
            "Dnes lze i v Koreji ochutnat nejrůznější druhy phở. Způsob, jakým se k vývaru přimíchávají různé omáčky nebo se do nich namáčí maso, se zdá dost podobný phở z jižního Vietnamu.|现在在韩国国内也能品尝到各式各样的河粉了。将多种酱料适度调配后配着汤一起吃，或是用来蘸肉吃的方式，似乎与越南南部地区的河粉颇为相似。|Ma már Koreában is sokféle phởt lehet kóstolni. Ahogyan különféle mártásokat kevernek az alaplé mellé vagy a húst mártogatják beléjük, az eléggé hasonlít a dél-vietnámi phởhöz.|Kini berbagai jenis phở juga dapat dinikmati di Korea. Cara orang mencampur berbagai saus untuk menemani kuah atau mencelupkan daging ke dalamnya tampak cukup mirip dengan phở dari Vietnam selatan.",
            "Phở ze kterého regionu máte raději? Nebylo by nejlepší vydat se tam a ochutnat ho osobně?|大家比较喜欢越南哪个地区的河粉呢？亲自前往品尝应该是最好的方式吧？|Melyik vidék phởját szereti jobban? Nem az lenne a legjobb, ha elmenne és személyesen megkóstolná?|Phở dari daerah mana yang lebih Anda sukai? Bukankah paling baik jika pergi dan mencicipinya sendiri?",
        ],
    },
    "Vietnam's Traditional Costume": {
        "title": "Tradiční vietnamský oděv|越南的传统服饰|Vietnám hagyományos viselete|Pakaian tradisional Vietnam",
        "subtitle": "Barevné a nádherné vietnamské áo dài|五彩缤纷、华丽的越南奥黛|A színes és pompás vietnámi áo dài|Áo dài Vietnam yang berwarna-warni dan indah",
        "paragraphs": [
            "Když si vybavíte film odehrávající se ve Vietnamu, asi vás jako první napadne štíhlá žena v tradičním vietnamském oděvu áo dài. Ve vietnamštině „áo“ znamená „oděv“ a „dài“ znamená „dlouhý“ — tvar oděvu je tedy patrný už z jeho názvu.|若想到以越南为背景的电影，最先浮现脑海的大概就是身穿越南传统服饰奥黛的苗条女性吧。在越南语中，“áo”意为“衣服”，“dài”意为“长”，也就是说，光从名称就能看出这件衣服的形状。|Ha egy Vietnámban játszódó filmre gondolunk, valószínűleg elsőként egy vietnámi hagyományos viseletet, áo dàit viselő karcsú nő jut eszünkbe. Vietnámiul az „áo” jelentése „ruha”, a „dài” jelentése „hosszú” — vagyis a ruha formája már a nevéből kiderül.|Jika membayangkan film berlatar Vietnam, yang pertama terlintas mungkin seorang wanita langsing mengenakan áo dài, pakaian tradisional Vietnam. Dalam bahasa Vietnam, \"áo\" berarti \"pakaian\" dan \"dài\" berarti \"panjang\" — jadi bentuk pakaian ini sudah tergambar dari namanya.",
            "Horní díl áo dài obvykle sahá až k nohám a nosí se k němu široké rovné kalhoty. Na první pohled se může podobat čínskému čchi-pao, liší se však tím, že se pod něj nosí kalhoty se širokými nohavicemi. Áo dài je tak jemný oděv, že se při jeho šití bere až 18 tělesných měr. Přiléhá k postavě a zvýrazňuje krásné linie těla, a proto tolik sluší štíhlým Vietnamkám.|奥黛的上衣通常长至腿部，下身则搭配宽管长裤。乍看之下与中国的旗袍相似，但不同之处在于里面搭配的是裤管宽松的长裤。奥黛是一件相当讲究的服装，制作时甚至需要量测多达18处的身体尺寸。它能完美贴合穿着者的身形，展现出优美的身体曲线，因此也非常适合身材纤瘦的越南女性穿着。|Az áo dài felső része általában a lábakig ér, alul pedig bő, egyenes szárú nadrágot viselnek hozzá. Első ránézésre a kínai csipaóra emlékeztethet, de abban különbözik, hogy bő szárú nadrágot hordanak alatta. Az áo dài olyan finom ruhadarab, hogy elkészítéséhez akár 18 testméretet is levesznek. Szorosan követi viselője alakját, kiemelve a szép testvonalakat, ezért illik annyira a karcsú vietnámi nőkhöz.|Bagian atas áo dài biasanya panjang hingga ke kaki, sedangkan bawahannya berupa celana panjang lurus yang lebar. Sekilas mirip qipao dari Tiongkok, tetapi berbeda karena dipadukan dengan celana berkaki lebar. Áo dài adalah busana yang sangat teliti — pembuatannya bisa memerlukan hingga 18 ukuran tubuh. Busana ini melekat pas di tubuh pemakainya dan menonjolkan lekuk tubuh yang indah, sehingga sangat cocok untuk wanita Vietnam yang ramping.",
            "Áo dài lze ve Vietnamu často vidět jako uniformu na úřadech, v bankách, hotelech a u leteckých společností i při zvláštních příležitostech, jako jsou svatby, zahájení školního roku a promoce.|在越南的政府机关、银行、饭店、航空公司的制服，以及婚礼、入学典礼、毕业典礼等特别场合，都能经常看到奥黛的身影。|Vietnámban gyakran látni áo dàit egyenruhaként hivatalokban, bankokban, szállodákban és légitársaságoknál, valamint különleges alkalmakkor, például esküvőn, tanévnyitón és ballagáson.|Di Vietnam, áo dài sering terlihat sebagai seragam di kantor pemerintahan, bank, hotel, dan maskapai penerbangan, juga pada acara khusus seperti pernikahan, upacara penerimaan siswa baru, dan wisuda.",
            "Musíte si tedy nechat vzít všechny míry, pokud si chcete ve Vietnamu áo dài vyzkoušet? Ne nutně. Dnes je k dostání mnoho konfekčních áo dài v různých velikostech, takže si každý může snadno koupit takové, které mu padne.|那么，如果想在越南试穿奥黛，一定要把身体尺寸全部量一遍吗？其实不然。现在有许多不同尺寸的成品服装，任何人都能轻松买到适合自己尺寸的奥黛。|Ha tehát ki szeretne próbálni egy áo dàit Vietnámban, minden testméretét le kell venni? Nem feltétlenül. Ma már sokféle méretben kaphatók készruhák, így bárki könnyen vehet magának illő áo dàit.|Lalu, jika ingin mencoba áo dài di Vietnam, apakah semua ukuran tubuh harus diukur? Tidak juga. Kini tersedia banyak produk jadi dalam berbagai ukuran, sehingga siapa pun dapat dengan mudah membeli áo dài yang pas.",
            "Co takhle obléct si splývavé áo dài a pořídit pár krásných fotografií na nádherných turistických místech Vietnamu? Určitě to bude jedna z radostí cestování po Vietnamu.|穿上轻柔飘逸的奥黛，在越南美丽的观光景点拍几张美美的照片，如何呢？这将会成为越南旅行乐趣之一。|Mit szólna hozzá, ha egy lágyan omló áo dàiban néhány szép fotót készítene Vietnám gyönyörű turisztikai helyszínein? Biztosan a vietnámi utazás egyik öröme lesz.|Bagaimana kalau mengenakan áo dài yang melambai dan berfoto di tempat-tempat wisata Vietnam yang indah? Tentu akan menjadi salah satu kesenangan berwisata di Vietnam.",
        ],
    },
    "Vietnam, the Country of Motorbikes": {
        "title": "Vietnam, země motorek|摩托车王国越南|Vietnám, a motorok országa|Vietnam, negeri sepeda motor",
        "subtitle": "Takhle se přechází ulice!|这样过马路吧！|Így kell átkelni az úttesten!|Begini cara menyeberang jalan!",
        "paragraphs": [
            "Mnozí z vás asi vědí, že se Vietnamu říká „země motorek“ — slovo „Vietnam“ člověku hned připomene motorky. Počet motorek ve Vietnamu je tak obrovský, že patří mezi pět největších na světě. Proč se tedy Vietnamci na motorky tolik spoléhají?|一提到“越南”就会马上联想到摩托车，相信很多人都知道越南被称为“摩托车王国”。越南的摩托车保有量在全世界能排进前五名，数量相当惊人。那么，越南为什么会这么广泛地使用摩托车呢？|Sokan tudják, hogy Vietnámot „a motorok országának” hívják — a „Vietnám” szóról rögtön a motorok jutnak eszünkbe. A vietnámi motorok száma olyan hatalmas, hogy a világ első öt helye között van. De miért támaszkodnak a vietnámiak ennyire a motorokra?|Banyak dari Anda mungkin sudah tahu bahwa Vietnam dijuluki \"negeri sepeda motor\" — kata \"Vietnam\" langsung mengingatkan pada sepeda motor. Jumlah sepeda motor di Vietnam begitu besar hingga termasuk lima besar dunia. Lalu, mengapa orang Vietnam begitu mengandalkan sepeda motor?",
            "Prvním důvodem je stav vietnamských silnic. Silnice bývají úzké a je mnoho jednosměrek, takže motorka ve Vietnamu šetří čas a je praktická. Druhým důvodem je, že auta jsou velmi drahá, a proto se mnoho lidí spoléhá na motorky.|第一个原因是越南的道路状况。由于道路较为狭窄，加上单行道又多，因此在越南骑乘摩托车既能节省时间又相当便利。第二个原因则是汽车价格非常昂贵，所以人们大多选择使用摩托车。|Az első ok Vietnám útviszonyai. Az utak inkább keskenyek, és sok az egyirányú utca, így Vietnámban a motor időt takarít meg és kényelmes. A második ok, hogy az autók nagyon drágák, ezért sokan inkább motorra hagyatkoznak.|Alasan pertama adalah kondisi jalan di Vietnam. Karena jalannya cenderung sempit dan banyak jalan satu arah, sepeda motor di Vietnam menghemat waktu dan praktis. Alasan kedua, mobil sangat mahal sehingga banyak orang mengandalkan sepeda motor.",
            "Z těchto důvodů je ve Vietnamu opravdu obrovské množství motorek! Pro cestovatele to však může být velmi neobvyklý pohled. Zvlášť při přecházení ulice tam, kde není semafor ani přechod, může být dost znepokojující přijít na to, kde a jak přejít. Nikdy byste neměli běžet jen proto, že jede motorka, a snažit se přejít rychle. Když půjdete pomalu a rovnoměrně, motorky vás šikovně objedou.|因为这些原因，越南的摩托车真的非常多！但对旅客来说，这无疑是相当陌生的景象。尤其是过马路时，如果没有红绿灯或斑马线，该从哪里、如何过马路实在让人十分苦恼。看到摩托车来了，也绝对不能为了快速通过而奔跑。只要慢慢地走，摩托车们自然会巧妙地绕过去。|Ezek miatt Vietnámban valóban rengeteg a motor! Az utazóknak viszont ez igen szokatlan látvány lehet. Különösen ott, ahol nincs közlekedési lámpa vagy zebra, komoly fejtörést okozhat, hol és hogyan keljünk át. Soha ne fusson csak azért, mert jön egy motor, hogy gyorsan átérjen. Ha lassan és egyenletesen halad, a motorok ügyesen kikerülik.|Karena alasan-alasan itu, jumlah sepeda motor di Vietnam benar-benar sangat banyak! Namun bagi wisatawan, ini bisa menjadi pemandangan yang sangat asing. Terutama saat menyeberang di tempat tanpa lampu lalu lintas atau zebra cross, cukup membingungkan harus menyeberang di mana dan bagaimana. Jangan sekali-kali berlari hanya karena ada sepeda motor datang supaya cepat menyeberang. Jika berjalan pelan dan tenang, sepeda motor akan dengan cekatan menghindar dan lewat.",
            "Bude to opravdu zábavný zážitek, který můžete zažít jen ve Vietnamu.|这将会是只有在越南才能体验到的非常有趣的经历。|Igazán szórakoztató élmény lesz, amelyet csak Vietnámban tapasztalhat meg.|Ini akan menjadi pengalaman seru yang hanya bisa Anda alami di Vietnam.",
        ],
    },
    "Vietnam's Climate": {
        "title": "Podnebí Vietnamu|越南的气候|Vietnám éghajlata|Iklim Vietnam",
        "subtitle": "I ve Vietnamu se nosí teplé bundy?|在越南竟然也要穿厚外套？|Vietnámban is vastag kabátot hordanak?|Di Vietnam juga memakai jaket tebal?",
        "paragraphs": [
            "Území Vietnamu má tvar dlouhého písmene S a vzdálenost od nejjižnějšího po nejsevernější bod dosahuje až 1 750 km. Proto jsou rozdíly v podnebí mezi regiony velmi výrazné.|越南的地形呈长长的S字型，从最南端到最北端的距离长达1,750公里，相隔相当遥远。因此各地区之间的气候差异也十分明显。|Vietnám területe hosszú S alakú, a legdélebbi és a legészakibb pont közötti távolság eléri az 1750 km-t. Ezért a régiók éghajlata között nagyon markánsak a különbségek.|Wilayah Vietnam berbentuk huruf S yang panjang, dengan jarak dari titik paling selatan ke paling utara mencapai 1.750 km. Karena itu, perbedaan iklim antarwilayah sangat mencolok.",
            "Severní Vietnam má čtyři výrazná roční období, podobně jako Korea. Jaro a podzim jsou poměrně krátké, ale v zimě teplota dost klesá — v některých oblastech dokonce sněží. Není neobvyklé vidět místní v teplých bundách.|越南北部地区和韩国一样有四季之分。春季和秋季相对较短，但冬季气温下降得相当多，甚至有些地区会下雪。因此经常可以看到当地人穿着厚外套出门的样子。|Észak-Vietnámban Koreához hasonlóan négy jól elkülönülő évszak van. A tavasz és az ősz viszonylag rövid, de télen a hőmérséklet jelentősen lecsökken — egyes területeken még havazik is. Gyakran látni vastag kabátban járó helyieket.|Vietnam utara memiliki empat musim yang jelas, seperti Korea. Musim semi dan gugur relatif singkat, tetapi pada musim dingin suhunya turun cukup banyak — bahkan di beberapa daerah turun salju. Penduduk setempat sering terlihat mengenakan jaket tebal.",
            "Ve středním Vietnamu je mnoho náhorních plošin, které, jak už název napovídá, leží ve vyšší nadmořské výšce, a mají proto poměrně chladné podnebí. Díky tomu se zde hojně pěstuje mnoho plodin, například vietnamská káva. S počasím podobným korejskému podzimu až počátku zimy je zde chladno a příjemně, takže je to skvělý region pro cestování.|中部地区有许多高原地带，这些高原地带正如其名，因地势较高，气候相对凉爽。也因为这种凉爽的气候，这里也是种植越南咖啡等多种作物的重要地区。气温大约如韩国的秋末到初冬般凉爽宜人，是非常适合享受旅行的地区。|Közép-Vietnámban sok a fennsík, amelyek – ahogy a nevük is mutatja – magasabban fekszenek, így viszonylag hűvös az éghajlatuk. E hűvös éghajlat miatt itt sokféle növényt, például vietnámi kávét termesztenek. A koreai ősz végéhez és tél elejéhez hasonló időjárással hűvös és kellemes, kiváló vidék az utazáshoz.|Wilayah Vietnam tengah memiliki banyak dataran tinggi yang, sesuai namanya, terletak di ketinggian sehingga iklimnya relatif sejuk. Karena iklim yang sejuk ini, wilayah ini juga menjadi tempat budidaya berbagai tanaman seperti kopi Vietnam. Dengan cuaca mirip akhir musim gugur hingga awal musim dingin di Korea, udaranya sejuk dan nyaman — wilayah yang sangat cocok untuk berwisata.",
            "Jižní region s centrem v Ho Či Minově Městě má typické podnebí jihovýchodní Asie. Průměrná teplota je 27–30 °C a rok se dělí na období sucha a období dešťů. V období sucha slunce pálí mnohem víc než v korejském létě. V období dešťů může několikrát denně přijít náhlý prudký liják, a proto Vietnamci v tomto období vždy nosí pláštěnku.|以胡志明市为中心的南部地区属于典型的东南亚气候。平均气温为27～30度，可分为旱季和雨季。旱季时的阳光炎热程度是韩国夏天无法比拟的。到了雨季，一天之内可能会下好几次游击式暴雨，因此越南人在雨季时总是随身携带雨衣。|A Ho Si Minh-város körüli déli régióban tipikus délkelet-ázsiai éghajlat uralkodik. Az átlaghőmérséklet 27–30 °C, és az év száraz és esős évszakra oszlik. A száraz évszakban a nap sokkal jobban tűz, mint a koreai nyárban. Esős évszakban naponta többször is lecsaphat hirtelen felhőszakadás, ezért a vietnámiak ilyenkor mindig esőkabátot hordanak maguknál.|Wilayah selatan yang berpusat di Kota Ho Chi Minh beriklim khas Asia Tenggara. Suhu rata-ratanya 27–30°C, dan musimnya terbagi menjadi musim kemarau dan musim hujan. Pada musim kemarau, terik mataharinya jauh melebihi musim panas di Korea. Saat musim hujan tiba, hujan deras mendadak bisa turun beberapa kali sehari, sehingga orang Vietnam selalu membawa jas hujan pada musim itu.",
        ],
    },
    "Vietnamese and Chinese Characters": {
        "title": "Vietnamština a čínské znaky|越南语与汉字|A vietnámi nyelv és a kínai írásjegyek|Bahasa Vietnam dan aksara Tionghoa",
        "subtitle": "Vietnamština: více než 60 % tvoří sinovietnamská slova|60%以上由汉字词构成的越南语|Vietnámi: több mint 60%-a kínai eredetű szó|Bahasa Vietnam: lebih dari 60% terdiri atas kata Sino-Vietnam",
        "paragraphs": [
            "Pokud se učíte vietnamsky, asi jste učinili zajímavý objev — přibližně 60 % vietnamské slovní zásoby tvoří sinovietnamská slova.|如果是正在学习越南语的朋友，应该会有一个令人惊奇的发现，那就是越南语中约有60%是由汉越词（汉字词）所构成的。|Ha vietnámiul tanul, valószínűleg érdekes felfedezést tett: a vietnámi szókincs körülbelül 60%-a kínai eredetű (sino-vietnámi) szó.|Jika Anda sedang belajar bahasa Vietnam, Anda mungkin menemukan hal menarik — sekitar 60% kosakata bahasa Vietnam terdiri atas kata Sino-Vietnam.",
            "Vlivem čínštiny se ve vietnamštině vyvinula sinovietnamská výslovnost. Přestože se vietnamština píše latinkou, mnoho jejích částí zní dost podobně jako výslovnost čínských znaků.|越南语受中国影响，发展出许多汉字音，因此虽然越南语的文字是以罗马字标记，但其中有不少部分与汉字读音相当相似。|A kínai hatás nyomán a vietnámiban kialakult a kínai írásjegyek vietnámi kiejtése. Így bár a vietnámit latin betűkkel írják, sok része meglehetősen hasonlóan hangzik a kínai írásjegyek kiejtéséhez.|Karena pengaruh Tiongkok, bahasa Vietnam mengembangkan lafal Sino-Vietnam. Jadi, meskipun ditulis dengan huruf Latin, banyak bagiannya yang terdengar cukup mirip dengan lafal aksara Tionghoa.",
            "Uvedu příklad!|举个例子给大家看吧！|Hadd mondjak egy példát!|Mari saya berikan contoh!",
            "đồng ý [동 이] souhlasit / xã hội [싸 호이] společnost / quan quang [꽌꽝] cestovní ruch|đồng ý [동 이] 同意 / xã hội [싸 호이] 社会 / quan quang [꽌꽝] 观光|đồng ý [동 이] egyetérteni / xã hội [싸 호이] társadalom / quan quang [꽌꽝] turizmus|đồng ý [동 이] setuju / xã hội [싸 호이] masyarakat / quan quang [꽌꽝] pariwisata",
            "Při pohledu na slova výše jste si asi všimli, jak podobná je výslovnost. Vietnamština má samozřejmě tóny a význam se podle tónu mění, ale protože je základní zvuk stejný, můžete i u slov, která vidíte poprvé, odhadnout význam podle zvuku.|看了上面的单字，大家应该会发现发音相当相似吧。当然，越南语有声调之分，发音会因声调不同而意思有所改变，但由于音节本身相同，就算是第一次见到的单字，也能透过发音来推测其意思。|A fenti szavakat látva valószínűleg észrevette, mennyire hasonló a kiejtés. A vietnámiban persze vannak tónusok, és a jelentés a tónustól függően változik, de mivel az alaphang ugyanaz, még az először látott szavak jelentését is kitalálhatja a hangzás alapján.|Melihat kata-kata di atas, Anda mungkin menyadari betapa miripnya lafalnya. Tentu bahasa Vietnam memiliki nada dan artinya berubah sesuai nada, tetapi karena bunyi dasarnya sama, Anda bisa menebak arti kata yang baru pertama kali dilihat dari bunyinya.",
            "Možná jste si mysleli, že studium vietnamštiny je jen těžké, ale když se na to podíváte takto, nepřipadá vám teď trochu snazší?|原本以为越南语很难学，但这样看下来，是不是觉得学越南语稍微变得简单一些了呢？|Talán úgy gondolta, hogy a vietnámi tanulása csak nehéz, de így nézve nem tűnik most egy kicsit könnyebbnek?|Mungkin Anda mengira belajar bahasa Vietnam itu sulit saja, tetapi jika dilihat seperti ini, bukankah sekarang terasa sedikit lebih mudah?",
        ],
    },
}


def _row(text):
    vals = text.split("|")
    assert len(vals) == len(CULTURE_AI_LANGS), text
    return dict(zip(CULTURE_AI_LANGS, vals))


def _fill_article(a):
    ai = CULTURE_ARTICLE_AI.get((a.get("title") or {}).get("en"))
    if not ai:
        return
    def fill(obj, row):
        for lang, text in zip(CULTURE_ARTICLE_AI_LANGS, row.split("|")):
            if not obj.get(lang):
                obj[lang] = text
    assert all(len(r.split("|")) == len(CULTURE_ARTICLE_AI_LANGS) for r in [ai["title"], ai["subtitle"]] + ai["paragraphs"])
    fill(a["title"], ai["title"])
    fill(a["subtitle"], ai["subtitle"])
    for p, row in zip(a.get("paragraphs", []), ai["paragraphs"]):
        fill(p, row)
    a["aiLangs"] = list(CULTURE_ARTICLE_AI_LANGS)


def apply_culture_ai_translations(articles):
    out = copy.deepcopy(articles)
    for a in out:
        if isinstance(a.get("title"), dict):
            _fill_article(a)
            continue
        ai = CULTURE_CARD_AI.get(a.get("titleVi"))
        if not ai:
            continue
        a["titleTr"] = dict({"ko": a.get("titleKo", "")}, **_row(ai["title"]))
        a["summaryTr"] = dict({"ko": a.get("summaryKo", "")}, **_row(ai["summary"]))
        a["learningPointTr"] = dict({"ko": a.get("learningPoint", "")}, **_row(ai["learningPoint"]))
        for kw, row in zip(a.get("keywords", []), ai["keywords"]):
            kw["tr"] = dict({"ko": kw.get("ko", "")}, **_row(row))
        a["aiLangs"] = list(CULTURE_AI_LANGS)
    return out
