# "교과" tab -- content drawn from the PDF course booklet
# "베트남어 학습반 16주 과정" (Vietnamese-language study class, 16-week course).
# WELCOME_TEXT / COURSE_PHASES / WEEK16_TOC below are transcribed verbatim from
# pages 3-6 of that booklet.
#
# Translatable Korean text fields (title/body/range/text/note) are stored as
# {"ko","zh","en","ja","de","fr"} dicts so js_json() (see build_app.py) serializes them straight into JS
# objects that app_logic.js's T() helper can read directly. Structural fields (page, link) are
# left as plain values.

WELCOME_TEXT = {'title': {'ko': '베트남어 학습반에 오신 여러분을 환영합니다!!',
           'zh': '歡迎各位來到越南語學習班！！',
           'en': 'Welcome to the Vietnamese class!!',
           'ja': 'ベトナム語訓練コースへようこそ！！',
           'de': 'Willkommen zum Vietnamesisch-Sprachkurs!!',
           'fr': 'Bienvenue au cours de vietnamien !!'},
 'body': [{'ko': '이 학습반은 베트남어로 좋은 소식을 전파하기 위해 마련된 것입니다.',
           'zh': '這個學習班是為了用越南語傳講好消息而設立的。',
           'en': 'This class was set up to help preach the good news in Vietnamese.',
           'ja': 'このクラスは、ベトナム語で良い知らせを伝えるために設けられたものです。',
           'de': 'Dieser Kurs wurde eingerichtet, um beim Predigen der guten Botschaft auf '
                 'Vietnamesisch zu helfen.',
           'fr': 'Ce cours a été mis en place pour aider à prêcher la bonne nouvelle en '
                 'vietnamien.'},
          {'ko': '이 과정은 베트남어에 대해 철저히 연구하기 위한 것이 아니라 형제 자매들이 베트남어의 기초를 배우도록 도움을 주기 위한 것입니다.',
           'zh': '這個課程並非要對越南語進行深入的研究，而是要幫助弟兄姐妹學習越南語的基礎。',
           'en': 'Its purpose is not to thoroughly study the Vietnamese language, but to help '
                 'brothers and sisters learn the basics of Vietnamese.',
           'ja': 'このコースはベトナム語を徹底的に研究するためのものではなく、兄弟姉妹がベトナム語の基礎を学ぶ手助けをするためのものです。',
           'de': 'Dieser Kurs soll nicht dem gründlichen wissenschaftlichen Sprachstudium dienen, '
                 'sondern Brüdern und Schwestern helfen, die Grundlagen der vietnamesischen '
                 'Sprache zu erlernen.',
           'fr': 'Son but n’est pas d’étudier la langue vietnamienne en profondeur, mais d’aider '
                 'les frères et sœurs à en acquérir les bases.'},
          {'ko': '형제 자매들은 이 학습반이 끝난 후 야외 봉사에서 정기적으로 베트남어를 사용하고 베트남어 회중이나 집단의 활동에 참여함으로 계속 발전하게 될 '
                 '것입니다.',
           'zh': '學習班結束後，弟兄姐妹將能夠在外勤傳道中經常使用越南語，並藉著參與越南語會眾或小組的活動繼續進步。',
           'en': 'After completing this class, brothers and sisters will continue to improve by '
                 'regularly using Vietnamese in the field ministry and by participating in the '
                 'activities of a Vietnamese congregation or group.',
           'ja': '兄弟姉妹はこのクラスが終わった後、野外奉仕で定期的にベトナム語を使い、ベトナム語の会衆やグループの活動に参加することによって、引き続き上達していくことになります。',
           'de': 'Nach Abschluss des Kurses können die Brüder und Schwestern weitere Fortschritte '
                 'machen, indem sie Vietnamesisch regelmäßig im Predigtdienst gebrauchen und sich '
                 'an den Aktivitäten einer vietnamesischen Versammlung oder Gruppe beteiligen.',
           'fr': 'Après avoir suivi ce cours, les frères et sœurs continueront de progresser en '
                 'utilisant régulièrement le vietnamien en prédication et en participant aux '
                 'activités d’une assemblée ou d’un groupe vietnamien.'},
          {'ko': '이 학습반은 16주간 운영되며 교과 과정은 아래와 같습니다.',
           'zh': '這個學習班為期16週，課程內容如下。',
           'en': 'This class runs for 16 weeks, and the curriculum is as follows.',
           'ja': 'このクラスは16週間行われ、カリキュラムは以下の通りです。',
           'de': 'Dieser Kurs dauert 16 Wochen und der Lehrplan sieht wie folgt aus:',
           'fr': 'Ce cours s’étend sur 16 semaines et le programme se présente comme suit :'}]}

COURSE_PHASES = [{'range': {'ko': '1-4주',
            'zh': '第1-4週',
            'en': 'Weeks 1-4',
            'ja': '第1～4週',
            'de': 'Woche 1–4',
            'fr': 'Semaines 1–4'},
  'title': {'ko': '베트남어의 기초',
            'zh': '越南語基礎',
            'en': 'Basics of Vietnamese',
            'ja': 'ベトナム語の基礎',
            'de': 'Grundlagen des Vietnamesischen',
            'fr': 'Les bases du vietnamien'},
  'body': [{'ko': '베트남어의 자음과 모음 발음법, 성서 책명, 인명 등을 함께 공부합니다. 베트남어의 가장 큰 특징인 성조를 익히고 계속 연습합니다. 성조는 '
                  '학습반 기간 동안 계속 반복적으로 학습해서 익혀 나가도록 합니다.',
            'zh': '一起學習越南語子音和母音的發音方法、聖經書名、人名等。學習並持續練習越南語最大的特色——聲調。聲調將在整個課程期間反覆練習，逐步熟練掌握。',
            'en': 'You will study Vietnamese consonant and vowel pronunciation together with Bible '
                  'book names, personal names, and more. You will learn and keep practicing tone, '
                  'the most distinctive feature of Vietnamese. Tones will be practiced repeatedly '
                  'throughout the course so that you gradually master them.',
            'ja': 'ベトナム語の子音と母音の発音方法、聖書の書名、人名などを一緒に学びます。ベトナム語最大の特徴である声調を身につけ、継続して練習します。声調はクラス期間を通じて繰り返し学習し、身につけていきます。',
            'de': 'Wir lernen die Aussprache der vietnamesischen Konsonanten und Vokale sowie '
                  'Bibelbuchnamen, Eigennamen und mehr. Außerdem lernen und üben wir die Töne – '
                  'das markanteste Merkmal des Vietnamesischen. Die Töne werden während des '
                  'gesamten Kurses wiederholt geübt, um sie sicher zu beherrschen.',
            'fr': 'Nous étudierons la prononciation des consonnes et des voyelles vietnamiennes, '
                  'ainsi que le nom des livres de la Bible, des noms de personnages, etc. Nous '
                  'apprendrons et exercerons les tons, principale caractéristique du vietnamien, '
                  'tout au long du cours afin de les maîtriser progressivement.'},
           {'ko': '봉사의 직무에서 바로 활용할 수 있는 기본적인 제공 연설을 공부하고 훈련합니다.',
            'zh': '學習並訓練可以在服事職務中立即運用的基本提供演講。',
            'en': 'You will study and practice basic offer talks that can be put to immediate use '
                  'in the ministry.',
            'ja': '奉仕の務めですぐに活用できる基本的な提供のスピーチを学び、訓練します。',
            'de': 'Wir lernen und üben grundlegende Gesprächsvorschläge, die direkt im '
                  'Predigtdienst eingesetzt werden können.',
            'fr': 'Nous étudierons et mettrons en pratique des présentations de base directement '
                  'utilisables dans le ministère.'},
           {'ko': '첫 한 달 수업 과정이 끝난 후 베트남어 집회에 참석하신다면 유익할 것입니다.',
            'zh': '完成第一個月的課程後，如果能夠參加越南語聚會，將會很有幫助。',
            'en': 'After finishing the first month of classes, it would be beneficial to attend a '
                  'Vietnamese-language meeting.',
            'ja': '最初の1か月の授業課程が終わった後、ベトナム語の集会に出席すると有益でしょう。',
            'de': 'Nach dem ersten Unterrichtsmonat ist es sehr nützlich, die Zusammenkünfte auf '
                  'Vietnamesisch zu besuchen.',
            'fr': 'Après le premier mois de cours, il sera très profitable d’assister aux réunions '
                  'en vietnamien.'}]},
 {'range': {'ko': '5-14주',
            'zh': '第5–14週',
            'en': 'Weeks 5–14',
            'ja': '5～14週目',
            'de': 'Woche 5–14',
            'fr': 'Semaines 5–14'},
  'title': {'ko': '베트남어 단어와 작문 수업, 베트남어 출판물 읽기 연습',
            'zh': '越南語詞彙與寫作課程、越南語出版物閱讀練習',
            'en': 'Vietnamese vocabulary and writing lessons, Vietnamese publication reading '
                  'practice',
            'ja': 'ベトナム語の単語と作文の授業、ベトナム語出版物の読解練習',
            'de': 'Wortschatz- und Schreibübungen auf Vietnamesisch, Leseübungen mit '
                  'vietnamesischen Publikationen',
            'fr': 'Vocabulaire et rédaction en vietnamien, entraînement à la lecture de '
                  'publications en vietnamien'},
  'body': [{'ko': '기본 단어 800개를 익히고 범용언어 생성법을 통한 베트남어 문장 만들기를 연습합니다.',
            'zh': '學習800個基本詞彙，並透過通用造句法練習組成越南語句子。',
            'en': 'You will learn 800 basic words and practice forming Vietnamese sentences using '
                  'a general sentence-building method.',
            'ja': '基本単語800個を身につけ、汎用言語生成法を通してベトナム語の文章作りを練習します。',
            'de': 'Wir lernen 800 Grundwörter und üben das Bilden vietnamesischer Sätze anhand der '
                  'Satzbaumethode.',
            'fr': 'Nous apprendrons 800 mots de base et nous entraînerons à construire des phrases '
                  'en vietnamien à l’aide de la méthode de construction de phrases.'},
           {'ko': '“행누” 베트남어를 주 교재로 해서 베트남어 읽기 연습을 합니다.',
            'zh': '以《행누》越南語教材為主，進行越南語閱讀練習。',
            'en': 'You will practice Vietnamese reading using "행누" Vietnamese as the main '
                  'textbook.',
            'ja': '「행누」ベトナム語を主な教材としてベトナム語の読解練習を行います。',
            'de': 'Anhand des Hauptlehrbuchs „행누“ (Glücklich – für immer) üben wir das Lesen auf '
                  'Vietnamesisch.',
            'fr': 'Nous nous exercerons à la lecture en vietnamien avec pour manuel principal le '
                  'livre « 행누 » (Vivez pour toujours).'},
           {'ko': '이 기간에도 변함없이 베트남어 성조를 연습하고 베트남어 기본 표현들을 계속 익혀 나갑니다.',
            'zh': '這段期間也一如既往地練習越南語聲調，並持續學習越南語基本表達方式。',
            'en': 'During this period as well, you will keep practicing Vietnamese tones as before '
                  'and continue learning basic Vietnamese expressions.',
            'ja': 'この期間も変わらずベトナム語の声調を練習し、ベトナム語の基本表現を引き続き身につけていきます。',
            'de': 'Auch in dieser Zeit üben wir weiterhin fleißig die Töne und eignen uns '
                  'grundlegende vietnamesische Ausdrücke an.',
            'fr': 'Pendant cette période, nous continuerons de pratiquer assidûment les tons et '
                  'd’acquérir des expressions courantes en vietnamien.'}]},
 {'range': {'ko': '15-16주',
            'zh': '第15–16週',
            'en': 'Weeks 15–16',
            'ja': '15～16週目',
            'de': 'Woche 15–16',
            'fr': 'Semaines 15–16'},
  'title': {'ko': '베트남어로 연설을 준비하거나 베트남어로 성서 연구 사회 준비',
            'zh': '準備越南語演講，或準備以越南語主持聖經研究',
            'en': 'Preparing a talk in Vietnamese, or preparing to conduct a Bible study in '
                  'Vietnamese',
            'ja': 'ベトナム語でスピーチを準備するか、ベトナム語で聖書研究の司会を準備する',
            'de': 'Vorbereitung eines Vortrags oder der Leitung eines Bibelstudiums auf '
                  'Vietnamesisch',
            'fr': 'Préparation d’un exposé ou de la direction d’une étude biblique en vietnamien'},
  'body': [{'ko': '한 가지 주제로 베트남어 연설을 준비하거나 해당 주 생활과 봉사 집회 과제를 준비해 봅니다.',
            'zh': '嘗試以一個主題準備越南語演講，或準備當週的生活與服事聚會作業。',
            'en': "Try preparing a Vietnamese talk on one topic, or preparing that week's "
                  'Christian Life and Ministry Meeting assignment.',
            'ja': '一つのテーマでベトナム語のスピーチを準備するか、その週の「クリスチャン生活と奉仕」の集会の課題を準備してみます。',
            'de': 'Bereiten Sie einen Vortrag zu einem Thema oder eine Aufgabe für die '
                  'Leben-und-Dienst-Zusammenkunft der jeweiligen Woche auf Vietnamesisch vor.',
            'fr': 'Préparez un exposé sur un thème ou un devoir pour la réunion Vie chrétienne et '
                  'ministère de la semaine en vietnamien.'},
           {'ko': '회중 성서 연구 혹은 파수대 집회에서 베트남어로 발표해 봅니다.',
            'zh': '嘗試在會眾聖經研究班或《守望台》研究班上用越南語發表。',
            'en': 'Try giving a comment in Vietnamese at the congregation Bible study or the '
                  'Watchtower Study.',
            'ja': '会衆聖書研究または「ものみの塔」研究の集会でベトナム語で発表してみます。',
            'de': 'Geben Sie einen Kommentar auf Vietnamesisch beim Versammlungsbibelstudium oder '
                  'beim Wachtturm-Studium.',
            'fr': 'Donnez un commentaire en vietnamien lors de l’étude biblique de l’assemblée ou '
                  'de l’étude de La Tour de Garde.'},
           {'ko': '베트남어로 성서 연구 사회를 해 봅니다.',
            'zh': '嘗試以越南語主持聖經研究。',
            'en': 'Try conducting a Bible study in Vietnamese.',
            'ja': 'ベトナム語で聖書研究の司会をしてみます。',
            'de': 'Leiten Sie ein Bibelstudium auf Vietnamesisch.',
            'fr': 'Entraînez-vous à diriger une étude biblique en vietnamien.'}]}]

WEEK16_TOC = [{'items': [{'link': {'subAttr': 'pron', 'subVal': 'settings', 'tab': 'pron'},
             'page': None,
             'text': {'en': 'Vietnamese Pronunciation – Setup',
                      'ja': 'ベトナム語発音設定',
                      'ko': '베트남어 발음 설정',
                      'zh': '越南語發音設定',
                      'de': 'Vietnamesische Aussprache – Einstellungen',
                      'fr': 'Prononciation vietnamienne – Réglages'}},
            {'link': {'subAttr': 'pron', 'subVal': 'alphabet', 'tab': 'pron'},
             'page': None,
             'text': {'en': 'Vietnamese Alphabet',
                      'ja': 'ベトナム語の文字',
                      'ko': '베트남어 문자',
                      'zh': '越南語文字',
                      'de': 'Vietnamesisches Alphabet',
                      'fr': 'Alphabet vietnamien'}},
            {'link': {'subAttr': 'pron', 'subVal': 'vowels', 'tab': 'pron'},
             'page': 11,
             'text': {'en': 'Vietnamese Pronunciation – Vowels',
                      'ja': 'ベトナム語の発音－母音',
                      'ko': '베트남어 발음 – 모음',
                      'zh': '越南語發音－母音',
                      'de': 'Vietnamesische Aussprache – Vokale',
                      'fr': 'Prononciation vietnamienne – Voyelles'}},
            {'link': {'subAttr': 'pron', 'subVal': 'consonants', 'tab': 'pron'},
             'page': 9,
             'text': {'en': 'Vietnamese Pronunciation – Consonants',
                      'ja': 'ベトナム語の発音－子音',
                      'ko': '베트남어 발음 – 자음',
                      'zh': '越南語發音－子音',
                      'de': 'Vietnamesische Aussprache – Konsonanten',
                      'fr': 'Prononciation vietnamienne – Consonnes'}},
            {'link': {'subAttr': 'pron', 'subVal': 'tones', 'tab': 'pron'},
             'page': 7,
             'text': {'en': 'Tone Practice',
                      'ja': '声調練習',
                      'ko': '성조연습',
                      'zh': '聲調練習',
                      'de': 'Tonübungen',
                      'fr': 'Exercice sur les tons'}},
            {'link': {'subAttr': 'vocab',
                      'subVal': 'rhyme',
                      'tab': 'vocab',
                      'vocabRange': {'end': 212, 'start': 0}},
             'page': None,
             'text': {'en': 'Vietnamese Vocabulary Study – (Sino-Vietnamese 1-212)',
                      'ja': 'ベトナム語語彙学習 （漢越音 1~212）',
                      'ko': '베트남어 어휘 학습 (한자음 1~212번)',
                      'zh': '越南語詞彙學習 （漢字音 1~212）',
                      'de': 'Vietnamesischer Wortschatz – (Sino-Vietnamesisch 1–212)',
                      'fr': 'Vocabulaire vietnamien – (Sino-vietnamien 1–212)'}},
            {'link': {'subAttr': 'sentence',
                      'subVal': 'wt',
                      'tab': 'sentence',
                      'vocabRange': {'end': 50, 'start': 0}},
             'page': None,
             'text': {'en': 'Vietnamese Watchtower Vocabulary Study – (50 Words)',
                      'ja': 'ベトナム語ものみの塔語彙50個学習',
                      'ko': '베트남어 파수대 어휘 50개 학습',
                      'zh': '越南語守望台詞彙50個學習',
                      'de': 'Vietnamesischer Wachtturm-Wortschatz – (50 Wörter)',
                      'fr': 'Vocabulaire vietnamien de La Tour de Garde – (50 mots)'}},
            {'link': {'subAttr': 'wizard', 'subVal': 'talks', 'tab': 'wizard', 'talkNums': [1]},
             'page': 13,
             'text': {'en': 'Vietnamese Offer Talk 1',
                      'ja': 'ベトナム語の提供のスピーチ1',
                      'ko': '베트남어 제공 연설 1',
                      'zh': '越南語提供演講1',
                      'de': 'Vietnamesischer Gesprächsvorschlag 1',
                      'fr': 'Présentation en vietnamien 1'}}],
  'note': {'en': 'Learning Vietnamese Letters and Basic Pronunciation',
           'ja': 'ベトナム語の文字と発音の基礎を学ぶ',
           'ko': '베트남어 문자와 발음 기초 배우기',
           'zh': '學習越南語字母與發音基礎',
           'de': 'Vietnamesische Buchstaben und Grundlagen der Aussprache lernen',
           'fr': 'Apprentissage des lettres et des bases de la prononciation du vietnamien'},
  'title': {'en': 'Oct 3, 2026 — Welcome to the Vietnamese Class',
            'ja': '2026/10/3 ベトナム語訓練コースへようこそ',
            'ko': '2026/10/3 베트남어 학습반에 오신 여러분을 환영합니다',
            'zh': '2026/10/3 歡迎各位來到越南語學習班',
            'de': '3. Okt. 2026 – Willkommen zum Vietnamesisch-Sprachkurs',
            'fr': '3 oct. 2026 – Bienvenue au cours de vietnamien'},
  'week': 0},
 {'items': [{'link': {'subAttr': 'pron', 'subVal': 'tones', 'tab': 'pron'},
             'page': None,
             'text': {'en': 'Tone Practice',
                      'ja': '声調練習',
                      'ko': '성조연습',
                      'zh': '聲調練習',
                      'de': 'Tonübungen',
                      'fr': 'Exercice sur les tons'}},
            {'link': {'subAttr': 'vocab',
                      'subVal': 'rhyme',
                      'tab': 'vocab',
                      'vocabRange': {'end': 316, 'start': 212}},
             'page': None,
             'text': {'en': 'Vietnamese Vocabulary Study – Week 1 (Sino-Vietnamese 213-316)',
                      'ja': 'ベトナム語語彙学習 1週目（漢越音 213~316）',
                      'ko': '베트남어 어휘 학습 1주차 (한자음 213~316번)',
                      'zh': '越南語詞彙學習 第1週（漢字音 213~316）',
                      'de': 'Vietnamesischer Wortschatz – Woche 1 (Sino-Vietnamesisch 213–316)',
                      'fr': 'Vocabulaire vietnamien – Semaine 1 (Sino-vietnamien 213–316)'}},
            {'link': {'subAttr': 'vocab',
                      'subVal': 'orderrev',
                      'tab': 'vocab',
                      'vocabRange': {'end': 15, 'start': 0}},
             'page': None,
             'text': {'en': 'Vietnamese Vocabulary Study – Week 1 (Reversed Order 1-15)',
                      'ja': 'ベトナム語語彙学習 1週目（語順が逆 1~15）',
                      'ko': '베트남어 어휘 학습 1주차 (어순반대 1~15번)',
                      'zh': '越南語詞彙學習 第1週（語序相反 1~15）',
                      'de': 'Vietnamesischer Wortschatz – Woche 1 (Umgekehrte Wortstellung 1–15)',
                      'fr': 'Vocabulaire vietnamien – Semaine 1 (Ordre inverse 1–15)'}},
            {'link': {'subAttr': 'vocab',
                      'subVal': 'groups',
                      'tab': 'vocab',
                      'vocabRange': {'end': 105, 'start': 0}},
             'page': None,
             'text': {'en': 'Vietnamese Vocabulary Study – Week 1 (Same Sound 1-105)',
                      'ja': 'ベトナム語語彙学習 1週目（同音 1~105）',
                      'ko': '베트남어 어휘 학습 1주차 (동일음 1~105번)',
                      'zh': '越南語詞彙學習 第1週（同音字 1~105）',
                      'de': 'Vietnamesischer Wortschatz – Woche 1 (Gleichlautend 1–105)',
                      'fr': 'Vocabulaire vietnamien – Semaine 1 (Même son 1–105)'}},
            {'link': {'subAttr': 'sentence',
                      'subVal': 'wt',
                      'tab': 'sentence',
                      'vocabRange': {'end': 100, 'start': 50}},
             'page': None,
             'text': {'en': 'Vietnamese Watchtower Vocabulary Study – Week 1 (50 Words)',
                      'ja': 'ベトナム語ものみの塔語彙50個学習 1週目',
                      'ko': '베트남어 파수대 어휘 50개 학습 1주차',
                      'zh': '越南語守望台詞彙50個學習 第1週',
                      'de': 'Vietnamesischer Wachtturm-Wortschatz – Woche 1 (50 Wörter)',
                      'fr': 'Vocabulaire vietnamien de La Tour de Garde – Semaine 1 (50 mots)'}},
            {'link': {'subAttr': 'pron', 'subVal': 'consonants', 'tab': 'pron'},
             'page': None,
             'text': {'en': 'Vietnamese Pronunciation – Consonant and Vowel Review',
                      'ja': 'ベトナム語の発音－子音、母音の復習',
                      'ko': '베트남어 발음 – 자음, 모음 복습',
                      'zh': '越南語發音－子音、母音複習',
                      'de': 'Vietnamesische Aussprache – Wiederholung von Konsonanten und Vokalen',
                      'fr': 'Prononciation vietnamienne – Révision des consonnes et des voyelles'}},
            {'link': {'subAttr': 'bible', 'subVal': 'books', 'tab': 'bible'},
             'page': 15,
             'text': {'en': 'Vietnamese Bible Book Name Reading Practice 1',
                      'ja': 'ベトナム語の聖書の書名読み練習1',
                      'ko': '베트남어 성경 책명 읽기 연습 1',
                      'zh': '越南語聖經書名朗讀練習1',
                      'de': 'Leseübung der vietnamesischen Bibelbuchnamen 1',
                      'fr': 'Lecture des noms de livres bibliques en vietnamien 1'}},
            {'link': {'subAttr': 'bible', 'subVal': 'numbers', 'tab': 'bible'},
             'page': 17,
             'text': {'en': 'Vietnamese Numbers 1–9',
                      'ja': 'ベトナム語の数字1～9',
                      'ko': '베트남어 숫자 1–9',
                      'zh': '越南語數字1–9',
                      'de': 'Vietnamesische Zahlen 1–9',
                      'fr': 'Nombres vietnamiens 1–9'}},
            {'link': {'subAttr': 'wizard', 'subVal': 'talks', 'tab': 'wizard', 'talkNums': [2]},
             'page': 18,
             'text': {'en': 'Vietnamese Offer Talk 2',
                      'ja': 'ベトナム語の提供のスピーチ2',
                      'ko': '베트남어 제공 연설 2',
                      'zh': '越南語提供演講2',
                      'de': 'Vietnamesischer Gesprächsvorschlag 2',
                      'fr': 'Présentation en vietnamien 2'}},
            {'link': {'anchor': 'song-46',
                      'subAttr': 'curriculum',
                      'subVal': 'song',
                      'tab': 'curriculum'},
             'page': 19,
             'text': {'en': 'Vietnamese Song (No. 46)',
                      'ja': 'ベトナム語の歌(46番)',
                      'ko': '베트남어 노래 (46번)',
                      'zh': '越南語詩歌(第46首)',
                      'de': 'Vietnamesisches Lied (Nr. 46)',
                      'fr': 'Cantique en vietnamien (n° 46)'}}],
  'note': {'en': 'Learning Vietnamese Bible Book Names and Numbers (Balloon Preparation)',
           'ja': 'ベトナム語の聖書の書名と数字を学ぶ（風船の準備）',
           'ko': '베트남어 성경 책명과 숫자 배우기 (풍선 준비)',
           'zh': '學習越南語聖經書名與數字（準備氣球）',
           'de': 'Vietnamesische Bibelbuchnamen und Zahlen lernen (Luftballons vorbereiten)',
           'fr': 'Apprentissage du nom des livres de la Bible et des nombres en vietnamien '
                 '(préparation de ballons)'},
  'week': 1},
 {'items': [{'link': {'subAttr': 'pron', 'subVal': 'tonepairs', 'tab': 'pron'},
             'page': 21,
             'text': {'en': 'Tone Practice, Tone Sequences',
                      'ja': '声調練習、連続声調',
                      'ko': '성조연습, 연속성조',
                      'zh': '聲調練習、連續聲調',
                      'de': 'Tonübungen, Tonkombinationen',
                      'fr': 'Exercice sur les tons, combinaisons de tons'}},
            {'link': {'subAttr': 'vocab',
                      'subVal': 'groups',
                      'tab': 'vocab',
                      'vocabRange': {'end': 317, 'start': 105}},
             'page': None,
             'text': {'en': 'Vietnamese Vocabulary Study – Week 2 (Same Sound 106-317)',
                      'ja': 'ベトナム語語彙学習 2週目（同音 106~317）',
                      'ko': '베트남어 어휘 학습 2주차 (동일음 106~317번)',
                      'zh': '越南語詞彙學習 第2週（同音字 106~317）',
                      'de': 'Vietnamesischer Wortschatz – Woche 2 (Gleichlautend 106–317)',
                      'fr': 'Vocabulaire vietnamien – Semaine 2 (Même son 106–317)'}},
            {'link': {'subAttr': 'sentence',
                      'subVal': 'wt',
                      'tab': 'sentence',
                      'vocabRange': {'end': 150, 'start': 100}},
             'page': None,
             'text': {'en': 'Vietnamese Watchtower Vocabulary Study – Week 2 (50 Words)',
                      'ja': 'ベトナム語ものみの塔語彙50個学習 2週目',
                      'ko': '베트남어 파수대 어휘 50개 학습 2주차',
                      'zh': '越南語守望台詞彙50個學習 第2週',
                      'de': 'Vietnamesischer Wachtturm-Wortschatz – Woche 2 (50 Wörter)',
                      'fr': 'Vocabulaire vietnamien de La Tour de Garde – Semaine 2 (50 mots)'}},
            {'link': {'subAttr': 'bible', 'subVal': 'books', 'tab': 'bible'},
             'page': 22,
             'text': {'en': 'Vietnamese Bible Book Name Reading Practice 2',
                      'ja': 'ベトナム語の聖書の書名読み練習2',
                      'ko': '베트남어 성경 책명 읽기 연습 2',
                      'zh': '越南語聖經書名朗讀練習2',
                      'de': 'Leseübung der vietnamesischen Bibelbuchnamen 2',
                      'fr': 'Lecture des noms de livres bibliques en vietnamien 2'}},
            {'link': {'subAttr': 'wizard', 'subVal': 'talks', 'tab': 'wizard', 'talkNums': [3]},
             'page': 24,
             'text': {'en': 'Vietnamese Offer Talk 3',
                      'ja': 'ベトナム語の提供のスピーチ3',
                      'ko': '베트남어 제공 연설 3',
                      'zh': '越南語提供演講3',
                      'de': 'Vietnamesischer Gesprächsvorschlag 3',
                      'fr': 'Présentation en vietnamien 3'}},
            {'link': {'subAttr': 'vocab', 'subVal': 'names', 'tab': 'vocab'},
             'page': 25,
             'text': {'en': 'Theocratic terms, pronunciation practice for key Bible characters '
                            '(훈책)',
                      'ja': '神権用語、主要人物の発音練習(훈책)',
                      'ko': '신권 용어, 주요 인물 발음 연습(훈책)',
                      'zh': '神權用語、重要人物發音練習(훈책)',
                      'de': 'Theokratische Begriffe, Ausspracheübung wichtiger biblischer Personen '
                            '(Lehrbuch)',
                      'fr': 'Termes théocratiques, prononciation des principaux personnages '
                            'bibliques (manuel)'}}],
  'note': {'en': 'Looking Up Bible Verses in Vietnamese',
           'ja': 'ベトナム語で聖句を調べる',
           'ko': '베트남어로 성경구절 찾아보기',
           'zh': '用越南語查找聖經經文',
           'de': 'Bibelstellen auf Vietnamesisch nachschlagen',
           'fr': 'Recherche de versets bibliques en vietnamien'},
  'week': 2},
 {'items': [{'link': {'subAttr': 'pron', 'subVal': 'tonepairs', 'tab': 'pron'},
             'page': 36,
             'text': {'en': 'Tone Practice, Tone Sequences',
                      'ja': '声調練習、連続声調',
                      'ko': '성조연습, 연속성조',
                      'zh': '聲調練習、連續聲調',
                      'de': 'Tonübungen, Tonkombinationen',
                      'fr': 'Exercice sur les tons, combinaisons de tons'}},
            {'link': {'subAttr': 'vocab',
                      'subVal': 'groups',
                      'tab': 'vocab',
                      'vocabRange': {'end': 530, 'start': 317}},
             'page': None,
             'text': {'en': 'Vietnamese Vocabulary Study – Week 3 (Same Sound 318-530)',
                      'ja': 'ベトナム語語彙学習 3週目（同音 318~530）',
                      'ko': '베트남어 어휘 학습 3주차 (동일음 318~530번)',
                      'zh': '越南語詞彙學習 第3週（同音字 318~530）',
                      'de': 'Vietnamesischer Wortschatz – Woche 3 (Gleichlautend 318–530)',
                      'fr': 'Vocabulaire vietnamien – Semaine 3 (Même son 318–530)'}},
            {'link': {'subAttr': 'sentence',
                      'subVal': 'wt',
                      'tab': 'sentence',
                      'vocabRange': {'end': 200, 'start': 150}},
             'page': None,
             'text': {'en': 'Vietnamese Watchtower Vocabulary Study – Week 3 (50 Words)',
                      'ja': 'ベトナム語ものみの塔語彙50個学習 3週目',
                      'ko': '베트남어 파수대 어휘 50개 학습 3주차',
                      'zh': '越南語守望台詞彙50個學習 第3週',
                      'de': 'Vietnamesischer Wachtturm-Wortschatz – Woche 3 (50 Wörter)',
                      'fr': 'Vocabulaire vietnamien de La Tour de Garde – Semaine 3 (50 mots)'}},
            {'link': {'subAttr': 'bible', 'subVal': 'numbers', 'tab': 'bible'},
             'page': 37,
             'text': {'en': 'Vietnamese Numbers',
                      'ja': 'ベトナム語の数字',
                      'ko': '베트남어 숫자',
                      'zh': '越南語數字',
                      'de': 'Vietnamesische Zahlen',
                      'fr': 'Nombres vietnamiens'}},
            {'link': {'subAttr': 'bible', 'subVal': 'days', 'tab': 'bible'},
             'page': 37,
             'text': {'en': 'Vietnamese Days of the Week, Dates',
                      'ja': 'ベトナム語の曜日、日付',
                      'ko': '베트남어 요일, 날짜',
                      'zh': '越南語星期、日期',
                      'de': 'Vietnamesische Wochentage, Datum',
                      'fr': 'Jours de la semaine et dates en vietnamien'}},
            {'link': {'subAttr': 'wizard', 'subVal': 'talks', 'tab': 'wizard', 'talkNums': [4]},
             'page': 42,
             'text': {'en': 'Vietnamese Offer Talk 4',
                      'ja': 'ベトナム語の提供のスピーチ4',
                      'ko': '베트남어 제공 연설 4',
                      'zh': '越南語提供演講4',
                      'de': 'Vietnamesischer Gesprächsvorschlag 4',
                      'fr': 'Présentation en vietnamien 4'}},
            {'link': {'subAttr': 'wizard', 'subVal': 'main', 'tab': 'wizard'},
             'page': None,
             'text': {'en': 'Vietnamese Dialogue Practice (Self-Introduction, Exchanging Contact '
                            'Info)',
                      'ja': 'ベトナム語会話練習（自己紹介、連絡先交換）',
                      'ko': '베트남어 대화 연습 (자기소개, 연락처 교환)',
                      'zh': '越南語對話練習（自我介紹、交換聯絡方式）',
                      'de': 'Vietnamesische Dialogübungen (Sich vorstellen, Kontaktdaten '
                            'austauschen)',
                      'fr': 'Pratique du dialogue en vietnamien (Se présenter, échanger ses '
                            'coordonnées)'}},
            {'link': {'subAttr': 'bible', 'subVal': 'books', 'tab': 'bible'},
             'page': None,
             'text': {'en': 'Bible Review',
                      'ja': '聖書の復習',
                      'ko': '성경 복습',
                      'zh': '聖經複習',
                      'de': 'Bibel-Wiederholung',
                      'fr': 'Révision biblique'}}],
  'note': {'en': 'Asking a Vietnamese Person for Personal Information',
           'ja': 'ベトナム人に身上情報を尋ねる',
           'ko': '베트남 사람에게 신상정보 물어보기',
           'zh': '向越南人詢問個人資料',
           'de': 'Persönliche Angaben auf Vietnamesisch erfragen',
           'fr': 'Demander des renseignements personnels en vietnamien'},
  'week': 3},
 {'items': [{'link': {'subAttr': 'pron', 'subVal': 'tonepairs', 'tab': 'pron'},
             'page': 44,
             'text': {'en': 'Tone Practice, Tone Sequences',
                      'ja': '声調練習、連続声調',
                      'ko': '성조연습, 연속성조',
                      'zh': '聲調練習、連續聲調',
                      'de': 'Tonübungen, Tonkombinationen',
                      'fr': 'Exercice sur les tons, combinaisons de tons'}},
            {'link': {'subAttr': 'vocab',
                      'subVal': 'groups',
                      'tab': 'vocab',
                      'vocabRange': {'end': 620, 'start': 530}},
             'page': None,
             'text': {'en': 'Vietnamese Vocabulary Study – Week 4 (Same Sound 531-620)',
                      'ja': 'ベトナム語語彙学習 4週目（同音 531~620）',
                      'ko': '베트남어 어휘 학습 4주차 (동일음 531~620번)',
                      'zh': '越南語詞彙學習 第4週（同音字 531~620）',
                      'de': 'Vietnamesischer Wortschatz – Woche 4 (Gleichlautend 531–620)',
                      'fr': 'Vocabulaire vietnamien – Semaine 4 (Même son 531–620)'}},
            {'link': {'subAttr': 'vocab',
                      'subVal': 'basic',
                      'tab': 'vocab',
                      'vocabRange': {'end': 58, 'start': 0}},
             'page': None,
             'text': {'en': 'Vietnamese Vocabulary Study – Week 4 (Base 1-113)',
                      'ja': 'ベトナム語語彙学習 4週目（基本 1~113）',
                      'ko': '베트남어 어휘 학습 4주차 (기본 1~113번)',
                      'zh': '越南語詞彙學習 第4週（基本 1~113）',
                      'de': 'Vietnamesischer Wortschatz – Woche 4 (Grundlagen 1–113)',
                      'fr': 'Vocabulaire vietnamien – Semaine 4 (Bases 1–113)'}},
            {'link': {'subAttr': 'vocab',
                      'subVal': 'antonym',
                      'tab': 'vocab',
                      'vocabRange': {'end': 10, 'start': 0}},
             'page': None,
             'text': {'en': 'Vietnamese Vocabulary Study – Week 4 (Antonyms 1-10)',
                      'ja': 'ベトナム語語彙学習 4週目（反意語 1~10）',
                      'ko': '베트남어 어휘 학습 4주차 (반의 1~10번)',
                      'zh': '越南語詞彙學習 第4週（反義 1~10）',
                      'de': 'Vietnamesischer Wortschatz – Woche 4 (Gegenteile 1–10)',
                      'fr': 'Vocabulaire vietnamien – Semaine 4 (Antonymes 1–10)'}},
            {'link': {'subAttr': 'sentence',
                      'subVal': 'wt',
                      'tab': 'sentence',
                      'vocabRange': {'end': 250, 'start': 200}},
             'page': None,
             'text': {'en': 'Vietnamese Watchtower Vocabulary Study – Week 4 (50 Words)',
                      'ja': 'ベトナム語ものみの塔語彙50個学習 4週目',
                      'ko': '베트남어 파수대 어휘 50개 학습 4주차',
                      'zh': '越南語守望台詞彙50個學習 第4週',
                      'de': 'Vietnamesischer Wachtturm-Wortschatz – Woche 4 (50 Wörter)',
                      'fr': 'Vocabulaire vietnamien de La Tour de Garde – Semaine 4 (50 mots)'}},
            {'link': {'subAttr': 'wizard', 'subVal': 'talks', 'tab': 'wizard', 'talkNums': [5]},
             'page': 45,
             'text': {'en': 'Vietnamese Offer Talk 5',
                      'ja': 'ベトナム語の提供のスピーチ5',
                      'ko': '베트남어 제공 연설 5',
                      'zh': '越南語提供演講5',
                      'de': 'Vietnamesischer Gesprächsvorschlag 5',
                      'fr': 'Présentation en vietnamien 5'}},
            {'link': {'subAttr': 'wizard', 'subVal': 'reftable', 'tab': 'wizard'},
             'page': 46,
             'text': {'en': 'Vietnamese Terms of Address',
                      'ja': 'ベトナム語の呼び方',
                      'ko': '베트남어 호칭',
                      'zh': '越南語稱謂',
                      'de': 'Vietnamesische Anredeformen',
                      'fr': 'Formules d’adresse en vietnamien'}},
            {'link': {'subAttr': 'bible', 'subVal': 'time', 'tab': 'bible'},
             'page': 46,
             'text': {'en': 'Vietnamese Time',
                      'ja': 'ベトナム語の時間',
                      'ko': '베트남어 시간',
                      'zh': '越南語時間',
                      'de': 'Vietnamesische Uhrzeit',
                      'fr': 'L’heure en vietnamien'}},
            {'link': None,
             'page': None,
             'text': {'en': 'Vietnamese Publication Reading Practice (행누, 랑제)',
                      'ja': 'ベトナム語出版物の読解練習(행누, 랑제)',
                      'ko': '베트남어 출판물 읽기 연습 (행누, 랑제)',
                      'zh': '越南語出版物閱讀練習(행누, 랑제)',
                      'de': 'Leseübung mit vietnamesischen Publikationen (행누, 랑제)',
                      'fr': 'Entraînement à la lecture de publications en vietnamien (행누, 랑제)'}},
            {'link': {'subAttr': 'bible', 'subVal': 'numbers', 'tab': 'bible'},
             'page': None,
             'text': {'en': 'Number Review (3-6-9 Game)',
                      'ja': '数字の復習(3・6・9ゲーム)',
                      'ko': '숫자 복습 (3,6,9 게임)',
                      'zh': '數字複習(3、6、9遊戲)',
                      'de': 'Zahlenwiederholung (3-6-9-Spiel)',
                      'fr': 'Révision des nombres (Jeu du 3-6-9)'}},
            {'link': {'subAttr': 'pron', 'subVal': 'nsdiff', 'tab': 'pron'},
             'page': None,
             'text': {'en': 'Vietnamese North/South Pronunciation Differences',
                      'ja': 'ベトナム語の南北発音の違い',
                      'ko': '베트남어 남북 발음 차이',
                      'zh': '越南語南北發音差異',
                      'de': 'Ausspracheunterschiede Nord/Süd im Vietnamesischen',
                      'fr': 'Différences de prononciation Nord/Sud en vietnamien'}}],
  'note': {'en': 'Learning Vietnamese Terms of Address',
           'ja': 'ベトナム語の呼び方を学ぶ',
           'ko': '베트남어 호칭 배우기',
           'zh': '學習越南語稱謂',
           'de': 'Vietnamesische Anredeformen lernen',
           'fr': 'Apprentissage des formules d’adresse en vietnamien'},
  'week': 4},
 {'items': [],
  'note': {'en': 'No new vocabulary pool progress this week, but the daily 10-word Watchtower '
                 'vocabulary study continues as usual.',
           'ja': '新しい語彙の進度は休みますが、毎日のものみの塔語彙10個の学習は続けます。',
           'ko': '새 어휘 진도는 쉬고, 파수대 어휘 10개 학습은 계속합니다.',
           'zh': '暫停新詞彙進度，但每天10個守望台詞彙學習照常進行。',
           'de': 'Diese Woche kein neuer allgemeiner Wortschatz, aber das tägliche Lernen von 10 '
                 'Wachtturm-Wörtern läuft normal weiter.',
           'fr': 'Pas de nouveau vocabulaire général cette semaine, mais l’étude quotidienne des '
                 '10 mots de La Tour de Garde se poursuit normalement.'},
  'title': {'en': "Break (Vietnamese Sister's Wedding, Nov 7, 2026)",
            'ja': '休み（ベトナム語姉妹の結婚式 2026/11/7）',
            'ko': '방학(2026/11/7)',
            'zh': '假期（越南姐妹婚禮 2026/11/7）',
            'de': 'Unterrichtsfrei (Hochzeit einer vietnamesischen Schwester, 7. Nov. 2026)',
            'fr': 'Pause (Mariage d’une sœur vietnamienne, 7 nov. 2026)'},
  'week': -1.5},
 {'items': [{'link': {'subAttr': 'pron', 'subVal': 'tonepairs', 'tab': 'pron'},
             'page': 60,
             'text': {'en': 'Tone Practice, Tone Sequences',
                      'ja': '声調練習、連続声調',
                      'ko': '성조연습, 연속성조',
                      'zh': '聲調練習、連續聲調',
                      'de': 'Tonübungen, Tonkombinationen',
                      'fr': 'Exercice sur les tons, combinaisons de tons'}},
            {'link': {'subAttr': 'vocab',
                      'subVal': 'antonym',
                      'tab': 'vocab',
                      'vocabRange': {'end': 99, 'start': 10}},
             'page': None,
             'text': {'en': 'Vietnamese Vocabulary Study – Week 5 (Antonyms 11-99)',
                      'ja': 'ベトナム語語彙学習 5週目（反意語 11~99）',
                      'ko': '베트남어 어휘 학습 5주차 (반의 11~99번)',
                      'zh': '越南語詞彙學習 第5週（反義 11~99）',
                      'de': 'Vietnamesischer Wortschatz – Woche 5 (Gegenteile 11–99)',
                      'fr': 'Vocabulaire vietnamien – Semaine 5 (Antonymes 11–99)'}},
            {'link': {'subAttr': 'vocab',
                      'subVal': 'freq',
                      'tab': 'vocab',
                      'vocabRange': {'end': 121, 'start': 0}},
             'page': None,
             'text': {'en': 'Vietnamese Vocabulary Study – Week 5 (Frequent 1-123)',
                      'ja': 'ベトナム語語彙学習 5週目（常用 1~123）',
                      'ko': '베트남어 어휘 학습 5주차 (상용 1~123번)',
                      'zh': '越南語詞彙學習 第5週（常用 1~123）',
                      'de': 'Vietnamesischer Wortschatz – Woche 5 (Häufig 1–123)',
                      'fr': 'Vocabulaire vietnamien – Semaine 5 (Fréquent 1–123)'}},
            {'link': {'subAttr': 'sentence',
                      'subVal': 'wt',
                      'tab': 'sentence',
                      'vocabRange': {'end': 350, 'start': 300}},
             'page': None,
             'text': {'en': 'Vietnamese Watchtower Vocabulary Study – Week 5 (50 Words)',
                      'ja': 'ベトナム語ものみの塔語彙50個学習 5週目',
                      'ko': '베트남어 파수대 어휘 50개 학습 5주차',
                      'zh': '越南語守望台詞彙50個學習 第5週',
                      'de': 'Vietnamesischer Wachtturm-Wortschatz – Woche 5 (50 Wörter)',
                      'fr': 'Vocabulaire vietnamien de La Tour de Garde – Semaine 5 (50 mots)'}},
            {'link': {'subAttr': 'wizard', 'subVal': 'talks', 'tab': 'wizard', 'talkNums': [6]},
             'page': 61,
             'text': {'en': 'Vietnamese Offer Talk 6',
                      'ja': 'ベトナム語提供の話 6',
                      'ko': '베트남어 제공 연설 6',
                      'zh': '越南語提供演講 6',
                      'de': 'Vietnamesischer Gesprächsvorschlag 6',
                      'fr': 'Présentation en vietnamien 6'}},
            {'link': {'anchor': 'song-12',
                      'subAttr': 'curriculum',
                      'subVal': 'song',
                      'tab': 'curriculum'},
             'page': 62,
             'text': {'en': 'Vietnamese Song (No. 12)',
                      'ja': 'ベトナム語の歌（12番）',
                      'ko': '베트남어 노래 (12번)',
                      'zh': '越南語詩歌（第12首）',
                      'de': 'Vietnamesisches Lied (Nr. 12)',
                      'fr': 'Cantique en vietnamien (n° 12)'}},
            {'link': {'subAttr': 'bible', 'subVal': 'books', 'tab': 'bible'},
             'page': None,
             'text': {'en': 'Vietnamese Bible Search Test',
                      'ja': 'ベトナム語聖書探しテスト',
                      'ko': '베트남어 성경 찾기 시험',
                      'zh': '越南語聖經查找測驗',
                      'de': 'Bibelstellen-Suchtest auf Vietnamesisch',
                      'fr': 'Test de recherche de versets bibliques en vietnamien'}},
            {'link': None,
             'page': None,
             'text': {'en': 'Reading "행누책"',
                      'ja': '「행누책」を読む',
                      'ko': '행누책 읽기',
                      'zh': '閱讀《행누책》',
                      'de': 'Lesen im „행누“-Buch (Glücklich – für immer)',
                      'fr': 'Lecture du livre « 행누 » (Vivez pour toujours)'}}],
  'note': {'en': 'Vietnamese Song (No. 12) and Bible Look-Up Practice',
           'ja': 'ベトナム語の歌(12番)と聖句探しの練習',
           'ko': '베트남어 노래(12번)와 성경 찾기 연습',
           'zh': '越南語詩歌(第12首)與查經練習',
           'de': 'Vietnamesisches Lied (Nr. 12) und Bibelstellen-Nachschlageübung',
           'fr': 'Cantique en vietnamien (n° 12) et entraînement à la recherche de versets '
                 'bibliques'},
  'week': 5},
 {'items': [{'link': {'subAttr': 'pron', 'subVal': 'tonepairs', 'tab': 'pron'},
             'page': 64,
             'text': {'en': 'Tone Practice, Tone Sequences',
                      'ja': '声調練習、連続声調',
                      'ko': '성조연습, 연속성조',
                      'zh': '聲調練習、連續聲調',
                      'de': 'Tonübungen, Tonkombinationen',
                      'fr': 'Exercice sur les tons, combinaisons de tons'}},
            {'link': {'subAttr': 'vocab',
                      'subVal': 'freq',
                      'tab': 'vocab',
                      'vocabRange': {'end': 331, 'start': 121}},
             'page': None,
             'text': {'en': 'Vietnamese Vocabulary Study – Week 6 (Frequent 124-336)',
                      'ja': 'ベトナム語語彙学習 6週目（常用 124~336）',
                      'ko': '베트남어 어휘 학습 6주차 (상용 124~336번)',
                      'zh': '越南語詞彙學習 第6週（常用 124~336）',
                      'de': 'Vietnamesischer Wortschatz – Woche 6 (Häufig 124–336)',
                      'fr': 'Vocabulaire vietnamien – Semaine 6 (Fréquent 124–336)'}},
            {'link': {'subAttr': 'sentence',
                      'subVal': 'wt',
                      'tab': 'sentence',
                      'vocabRange': {'end': 400, 'start': 350}},
             'page': None,
             'text': {'en': 'Vietnamese Watchtower Vocabulary Study – Week 6 (50 Words)',
                      'ja': 'ベトナム語ものみの塔語彙50個学習 6週目',
                      'ko': '베트남어 파수대 어휘 50개 학습 6주차',
                      'zh': '越南語守望台詞彙50個學習 第6週',
                      'de': 'Vietnamesischer Wachtturm-Wortschatz – Woche 6 (50 Wörter)',
                      'fr': 'Vocabulaire vietnamien de La Tour de Garde – Semaine 6 (50 mots)'}},
            {'link': {'subAttr': 'wizard', 'subVal': 'talks', 'tab': 'wizard', 'talkNums': [7]},
             'page': 65,
             'text': {'en': 'Vietnamese Offer Talk 7',
                      'ja': 'ベトナム語提供の話 7',
                      'ko': '베트남어 제공 연설 7',
                      'zh': '越南語提供演講 7',
                      'de': 'Vietnamesischer Gesprächsvorschlag 7',
                      'fr': 'Présentation en vietnamien 7'}},
            {'link': None,
             'page': None,
             'text': {'en': 'Vietnamese Reading Practice',
                      'ja': 'ベトナム語読解練習',
                      'ko': '베트남어 읽기 연습',
                      'zh': '越南語閱讀練習',
                      'de': 'Vietnamesische Leseübungen',
                      'fr': 'Entraînement à la lecture en vietnamien'}},
            {'link': {'subAttr': 'grammar', 'subVal': 'sentences', 'tab': 'grammar'},
             'page': 66,
             'text': {'en': 'Introduction to the Universal Language Generation Method',
                      'ja': '汎用言語生成法の紹介',
                      'ko': '범용언어 생성법 소개',
                      'zh': '通用語言生成法介紹',
                      'de': 'Einführung in die Satzbaumethode',
                      'fr': 'Introduction à la méthode de construction de phrases'}},
            {'link': {'subAttr': 'grammar', 'subVal': 'lessons', 'tab': 'grammar'},
             'page': None,
             'text': {'en': 'Vietnamese Grammar Examples',
                      'ja': 'ベトナム語文法例文',
                      'ko': '베트남어 문법 예문',
                      'zh': '越南語文法例句',
                      'de': 'Vietnamesische Beispielsätze zur Grammatik',
                      'fr': 'Exemples de grammaire vietnamienne'}}],
  'note': {'en': 'Starting to Build Sentences with the Universal Sentence Method',
           'ja': '汎用言語生成法で文を作り始める',
           'ko': '범용언어 생성법으로 문장 만들기 시작',
           'zh': '開始用通用造句法練習造句',
           'de': 'Erste Sätze bilden mit der Satzbaumethode',
           'fr': 'Début de la construction de phrases avec la méthode générale'},
  'week': 6},
 {'items': [{'link': {'subAttr': 'pron', 'subVal': 'tonepairs', 'tab': 'pron'},
             'page': 75,
             'text': {'en': 'Tone Practice, Tone Sequences',
                      'ja': '声調練習、連続声調',
                      'ko': '성조연습, 연속성조',
                      'zh': '聲調練習、連續聲調',
                      'de': 'Tonübungen, Tonkombinationen',
                      'fr': 'Exercice sur les tons, combinaisons de tons'}},
            {'link': {'subAttr': 'vocab',
                      'subVal': 'freq',
                      'tab': 'vocab',
                      'vocabRange': {'end': 540, 'start': 331}},
             'page': None,
             'text': {'en': 'Vietnamese Vocabulary Study – Week 7 (Frequent 337-549)',
                      'ja': 'ベトナム語語彙学習 7週目（常用 337~549）',
                      'ko': '베트남어 어휘 학습 7주차 (상용 337~549번)',
                      'zh': '越南語詞彙學習 第7週（常用 337~549）',
                      'de': 'Vietnamesischer Wortschatz – Woche 7 (Häufig 337–549)',
                      'fr': 'Vocabulaire vietnamien – Semaine 7 (Fréquent 337–549)'}},
            {'link': {'subAttr': 'sentence',
                      'subVal': 'wt',
                      'tab': 'sentence',
                      'vocabRange': {'end': 450, 'start': 400}},
             'page': None,
             'text': {'en': 'Vietnamese Watchtower Vocabulary Study – Week 7 (50 Words)',
                      'ja': 'ベトナム語ものみの塔語彙50個学習 7週目',
                      'ko': '베트남어 파수대 어휘 50개 학습 7주차',
                      'zh': '越南語守望台詞彙50個學習 第7週',
                      'de': 'Vietnamesischer Wachtturm-Wortschatz – Woche 7 (50 Wörter)',
                      'fr': 'Vocabulaire vietnamien de La Tour de Garde – Semaine 7 (50 mots)'}},
            {'link': {'subAttr': 'wizard', 'subVal': 'talks', 'tab': 'wizard', 'talkNums': [8]},
             'page': 76,
             'text': {'en': 'Vietnamese Offer Talk 8',
                      'ja': 'ベトナム語提供の話 8',
                      'ko': '베트남어 제공 연설 8',
                      'zh': '越南語提供演講 8',
                      'de': 'Vietnamesischer Gesprächsvorschlag 8',
                      'fr': 'Présentation en vietnamien 8'}},
            {'link': {'subAttr': 'grammar', 'subVal': 'sentences', 'tab': 'grammar'},
             'page': None,
             'text': {'en': 'Building Vietnamese Sentences Using the Universal Language Generation '
                            'Method',
                      'ja': '汎用言語生成法を使ってベトナム語の文を作る',
                      'ko': '범용언어 생성법을 통한 베트남어 문장 만들기',
                      'zh': '運用通用語言生成法造越南語句子',
                      'de': 'Vietnamesische Sätze bilden mit der Satzbaumethode',
                      'fr': 'Construction de phrases vietnamiennes avec la méthode générale'}},
            {'link': None,
             'page': None,
             'text': {'en': 'Vietnamese Reading Practice',
                      'ja': 'ベトナム語読解練習',
                      'ko': '베트남어 읽기 연습',
                      'zh': '越南語閱讀練習',
                      'de': 'Vietnamesische Leseübungen',
                      'fr': 'Entraînement à la lecture en vietnamien'}},
            {'link': None,
             'page': None,
             'text': {'en': 'Write a Diary in Vietnamese and Present It',
                      'ja': 'ベトナム語で日記を書いて発表する',
                      'ko': '베트남어로 일기쓰고 발표',
                      'zh': '用越南語寫日記並發表',
                      'de': 'Tagebuch auf Vietnamesisch schreiben und vortragen',
                      'fr': 'Écrire un journal en vietnamien et le présenter'}},
            {'link': {'subAttr': 'grammar', 'subVal': 'builder', 'tab': 'grammar'},
             'page': None,
             'text': {'en': 'Practicing Sentence-Making with the Sentence Builder',
                      'ja': '文章生成器で文を作る練習',
                      'ko': '문장 생성기로 문장 만들기 연습',
                      'zh': '用造句產生器練習造句',
                      'de': 'Sätze bilden mit dem Satzgenerator üben',
                      'fr': 'Exercice de construction de phrases avec le générateur de phrases'}}],
  'note': {'en': 'Writing and Presenting a Diary in Vietnamese',
           'ja': 'ベトナム語で日記を書いて発表する',
           'ko': '베트남어로 일기 쓰고 발표하기',
           'zh': '用越南語寫日記並發表',
           'de': 'Ein Tagebuch auf Vietnamesisch schreiben und vortragen',
           'fr': 'Rédiger et présenter un journal en vietnamien'},
  'week': 7},
 {'items': [],
  'note': {'en': 'No new vocabulary pool progress this week, but the daily 10-word Watchtower '
                 'vocabulary study continues as usual.',
           'ja': '新しい語彙の進度は休みますが、毎日のものみの塔語彙10個の学習は続けます。',
           'ko': '새 어휘 진도는 쉬고, 파수대 어휘 10개 학습은 계속합니다.',
           'zh': '暫停新詞彙進度，但每天10個守望台詞彙學習照常進行。',
           'de': 'Diese Woche kein neuer allgemeiner Wortschatz, aber das tägliche Lernen von 10 '
                 'Wachtturm-Wörtern läuft normal weiter.',
           'fr': 'Pas de nouveau vocabulaire général cette semaine, mais l’étude quotidienne des '
                 '10 mots de La Tour de Garde se poursuit normalement.'},
  'title': {'en': 'Break (Vietnamese Circuit Assembly, Dec 5, 2026)',
            'ja': '休み（ベトナム語巡回大会 2026/12/5）',
            'ko': '방학(베트남어 순회대회 2026/12/5)',
            'zh': '假期（越南語巡迴大會 2026/12/5）',
            'de': 'Unterrichtsfrei (Kreiskongress auf Vietnamesisch, 5. Dez. 2026)',
            'fr': 'Pause (Assemblée de circonscription en vietnamien, 5 déc. 2026)'},
  'week': -2.5},
 {'items': [{'link': {'subAttr': 'pron', 'subVal': 'tonepairs', 'tab': 'pron'},
             'page': None,
             'text': {'en': 'Tone Practice, Tone Sequences',
                      'ja': '声調練習、連続声調',
                      'ko': '성조연습, 연속성조',
                      'zh': '聲調練習、連續聲調',
                      'de': 'Tonübungen, Tonkombinationen',
                      'fr': 'Exercice sur les tons, combinaisons de tons'}},
            {'link': {'subAttr': 'vocab',
                      'subVal': 'freq',
                      'tab': 'vocab',
                      'vocabRange': {'end': 749, 'start': 540}},
             'page': None,
             'text': {'en': 'Vietnamese Vocabulary Study – Week 8 (Frequent 550-761)',
                      'ja': 'ベトナム語語彙学習 8週目（常用 550~761）',
                      'ko': '베트남어 어휘 학습 8주차 (상용 550~761번)',
                      'zh': '越南語詞彙學習 第8週（常用 550~761）',
                      'de': 'Vietnamesischer Wortschatz – Woche 8 (Häufig 550–761)',
                      'fr': 'Vocabulaire vietnamien – Semaine 8 (Fréquent 550–761)'}},
            {'link': {'subAttr': 'sentence',
                      'subVal': 'wt',
                      'tab': 'sentence',
                      'vocabRange': {'end': 550, 'start': 500}},
             'page': None,
             'text': {'en': 'Vietnamese Watchtower Vocabulary Study – Week 8 (50 Words)',
                      'ja': 'ベトナム語ものみの塔語彙50個学習 8週目',
                      'ko': '베트남어 파수대 어휘 50개 학습 8주차',
                      'zh': '越南語守望台詞彙50個學習 第8週',
                      'de': 'Vietnamesischer Wachtturm-Wortschatz – Woche 8 (50 Wörter)',
                      'fr': 'Vocabulaire vietnamien de La Tour de Garde – Semaine 8 (50 mots)'}},
            {'link': {'subAttr': 'wizard', 'subVal': 'talks', 'tab': 'wizard', 'talkNums': [9]},
             'page': 78,
             'text': {'en': 'Vietnamese Offer Talk 9',
                      'ja': 'ベトナム語提供の話 9',
                      'ko': '베트남어 제공 연설 9',
                      'zh': '越南語提供演講 9',
                      'de': 'Vietnamesischer Gesprächsvorschlag 9',
                      'fr': 'Présentation en vietnamien 9'}},
            {'link': {'subAttr': 'grammar', 'subVal': 'sentences', 'tab': 'grammar'},
             'page': None,
             'text': {'en': 'Building Vietnamese Sentences Using the Universal Language Generation '
                            'Method',
                      'ja': '汎用言語生成法を使ってベトナム語の文を作る',
                      'ko': '범용언어 생성법을 통한 베트남어 문장 만들기',
                      'zh': '運用通用語言生成法造越南語句子',
                      'de': 'Vietnamesische Sätze bilden mit der Satzbaumethode',
                      'fr': 'Construction de phrases vietnamiennes avec la méthode générale'}},
            {'link': None,
             'page': None,
             'text': {'en': 'Vietnamese Reading Practice',
                      'ja': 'ベトナム語読解練習',
                      'ko': '베트남어 읽기 연습',
                      'zh': '越南語閱讀練習',
                      'de': 'Vietnamesische Leseübungen',
                      'fr': 'Entraînement à la lecture en vietnamien'}}],
  'note': {'en': 'Deepening Practice with Talks and Sentence-Building',
           'ja': '提供の話と文作りの練習を深める',
           'ko': '제공 연설과 문장 만들기 연습 심화',
           'zh': '深化提供演講與造句練習',
           'de': 'Vertiefung: Gesprächsvorschläge und Sätze bilden',
           'fr': 'Approfondissement : présentations et construction de phrases'},
  'week': 8},
 {'items': [{'link': {'subAttr': 'wizard', 'subVal': 'talks', 'tab': 'wizard', 'talkNums': [10]},
             'page': 81,
             'text': {'en': 'Vietnamese Offer Talk 10',
                      'ja': 'ベトナム語提供の話 10',
                      'ko': '베트남어 제공 연설 10',
                      'zh': '越南語提供演講 10',
                      'de': 'Vietnamesischer Gesprächsvorschlag 10',
                      'fr': 'Présentation en vietnamien 10'}},
            {'link': {'subAttr': 'vocab',
                      'subVal': 'freq',
                      'tab': 'vocab',
                      'vocabRange': {'end': 958, 'start': 749}},
             'page': None,
             'text': {'en': 'Vietnamese Vocabulary Study – Week 9 (Frequent 762-974)',
                      'ja': 'ベトナム語語彙学習 9週目（常用 762~974）',
                      'ko': '베트남어 어휘 학습 9주차 (상용 762~974번)',
                      'zh': '越南語詞彙學習 第9週（常用 762~974）',
                      'de': 'Vietnamesischer Wortschatz – Woche 9 (Häufig 762–974)',
                      'fr': 'Vocabulaire vietnamien – Semaine 9 (Fréquent 762–974)'}},
            {'link': {'subAttr': 'sentence',
                      'subVal': 'wt',
                      'tab': 'sentence',
                      'vocabRange': {'end': 600, 'start': 550}},
             'page': None,
             'text': {'en': 'Vietnamese Watchtower Vocabulary Study – Week 9 (50 Words)',
                      'ja': 'ベトナム語ものみの塔語彙50個学習 9週目',
                      'ko': '베트남어 파수대 어휘 50개 학습 9주차',
                      'zh': '越南語守望台詞彙50個學習 第9週',
                      'de': 'Vietnamesischer Wachtturm-Wortschatz – Woche 9 (50 Wörter)',
                      'fr': 'Vocabulaire vietnamien de La Tour de Garde – Semaine 9 (50 mots)'}},
            {'link': {'subAttr': 'grammar', 'subVal': 'sentences', 'tab': 'grammar'},
             'page': None,
             'text': {'en': 'Building Vietnamese Sentences Using the Universal Language Generation '
                            'Method',
                      'ja': '汎用言語生成法を使ってベトナム語の文を作る',
                      'ko': '범용언어 생성법을 통한 베트남어 문장 만들기',
                      'zh': '運用通用語言生成法造越南語句子',
                      'de': 'Vietnamesische Sätze bilden mit der Satzbaumethode',
                      'fr': 'Construction de phrases vietnamiennes avec la méthode générale'}},
            {'link': None,
             'page': None,
             'text': {'en': 'Vietnamese Reading Practice',
                      'ja': 'ベトナム語読解練習',
                      'ko': '베트남어 읽기 연습',
                      'zh': '越南語閱讀練習',
                      'de': 'Vietnamesische Leseübungen',
                      'fr': 'Entraînement à la lecture en vietnamien'}},
            {'link': {'anchor': 'song-18',
                      'subAttr': 'curriculum',
                      'subVal': 'song',
                      'tab': 'curriculum'},
             'page': 82,
             'text': {'en': 'Vietnamese Song (No. 18)',
                      'ja': 'ベトナム語の歌（18番）',
                      'ko': '베트남어 노래 (18번)',
                      'zh': '越南語詩歌（第18首）',
                      'de': 'Vietnamesisches Lied (Nr. 18)',
                      'fr': 'Cantique en vietnamien (n° 18)'}}],
  'note': {'en': 'Learning Vietnamese Song No. 18',
           'ja': 'ベトナム語の歌(18番)を学ぶ',
           'ko': '베트남어 노래(18번) 배우기',
           'zh': '學習越南語詩歌(第18首)',
           'de': 'Vietnamesisches Lied Nr. 18 lernen',
           'fr': 'Apprentissage du cantique en vietnamien n° 18'},
  'week': 9},
 {'items': [],
  'note': {'en': 'No new vocabulary pool progress this week, but the daily 10-word Watchtower '
                 'vocabulary study continues as usual.',
           'ja': '新しい語彙の進度は休みますが、毎日のものみの塔語彙10個の学習は続けます。',
           'ko': '새 어휘 진도는 쉬고, 파수대 어휘 10개 학습은 계속합니다.',
           'zh': '暫停新詞彙進度，但每天10個守望台詞彙學習照常進行。',
           'de': 'Diese Woche kein neuer allgemeiner Wortschatz, aber das tägliche Lernen von 10 '
                 'Wachtturm-Wörtern läuft normal weiter.',
           'fr': 'Pas de nouveau vocabulaire général cette semaine, mais l’étude quotidienne des '
                 '10 mots de La Tour de Garde se poursuit normalement.'},
  'title': {'en': 'Break (Korean Circuit Assembly, Dec 26, 2026)',
            'ja': '休み（韓国語巡回大会 2026/12/26）',
            'ko': '방학(한국어 순회대회 2026/12/26)',
            'zh': '假期（韓語巡迴大會 2026/12/26）',
            'de': 'Unterrichtsfrei (Kreiskongress auf Koreanisch, 26. Dez. 2026)',
            'fr': 'Pause (Assemblée de circonscription en coréen, 26 déc. 2026)'},
  'week': -3.5},
 {'items': [{'link': None,
             'page': None,
             'text': {'en': 'Vietnamese Reading Practice',
                      'ja': 'ベトナム語読解練習',
                      'ko': '베트남어 읽기 연습',
                      'zh': '越南語閱讀練習',
                      'de': 'Vietnamesische Leseübungen',
                      'fr': 'Entraînement à la lecture en vietnamien'}},
            {'link': {'subAttr': 'wizard', 'subVal': 'talks', 'tab': 'wizard', 'talkNums': [11]},
             'page': 85,
             'text': {'en': 'Vietnamese Offer Talk 11 (Meeting Invitation)',
                      'ja': 'ベトナム語提供の話 11（集会への招待）',
                      'ko': '베트남어 제공 연설 11 (집회 초대)',
                      'zh': '越南語提供演講 11（邀請聚會）',
                      'de': 'Vietnamesischer Gesprächsvorschlag 11 (Einladung zur Zusammenkunft)',
                      'fr': 'Présentation en vietnamien 11 (Invitation aux réunions)'}},
            {'link': {'subAttr': 'vocab',
                      'subVal': 'freq',
                      'tab': 'vocab',
                      'vocabRange': {'end': 1167, 'start': 958}},
             'page': None,
             'text': {'en': 'Vietnamese Vocabulary Study – Week 10 (Frequent 975-1186)',
                      'ja': 'ベトナム語語彙学習 10週目（常用 975~1186）',
                      'ko': '베트남어 어휘 학습 10주차 (상용 975~1186번)',
                      'zh': '越南語詞彙學習 第10週（常用 975~1186）',
                      'de': 'Vietnamesischer Wortschatz – Woche 10 (Häufig 975–1186)',
                      'fr': 'Vocabulaire vietnamien – Semaine 10 (Fréquent 975–1186)'}},
            {'link': {'subAttr': 'sentence',
                      'subVal': 'wt',
                      'tab': 'sentence',
                      'vocabRange': {'end': 700, 'start': 650}},
             'page': None,
             'text': {'en': 'Vietnamese Watchtower Vocabulary Study – Week 10 (50 Words)',
                      'ja': 'ベトナム語ものみの塔語彙50個学習 10週目',
                      'ko': '베트남어 파수대 어휘 50개 학습 10주차',
                      'zh': '越南語守望台詞彙50個學習 第10週',
                      'de': 'Vietnamesischer Wachtturm-Wortschatz – Woche 10 (50 Wörter)',
                      'fr': 'Vocabulaire vietnamien de La Tour de Garde – Semaine 10 (50 mots)'}},
            {'link': {'subAttr': 'grammar', 'subVal': 'sentences', 'tab': 'grammar'},
             'page': None,
             'text': {'en': 'Building Vietnamese Sentences Using the Universal Language Generation '
                            'Method',
                      'ja': '汎用言語生成法を使ってベトナム語の文を作る',
                      'ko': '범용언어 생성법을 통한 베트남어 문장 만들기',
                      'zh': '運用通用語言生成法造越南語句子',
                      'de': 'Vietnamesische Sätze bilden mit der Satzbaumethode',
                      'fr': 'Construction de phrases vietnamiennes avec la méthode générale'}},
            {'link': None,
             'page': None,
             'text': {'en': 'Vietnamese Study Edition Watchtower Reading Practice',
                      'ja': 'ベトナム語研究用「ものみの塔」読解練習',
                      'ko': '베트남어 연구용 파수대 읽기 연습',
                      'zh': '越南語研究版《守望台》閱讀練習',
                      'de': 'Leseübung mit der vietnamesischen Studienausgabe des Wachtturms',
                      'fr': 'Lecture de l’édition d’étude de La Tour de Garde en vietnamien'}},
            {'link': {'anchor': 'prayer-prep',
                      'subAttr': 'curriculum',
                      'subVal': 'prayer',
                      'tab': 'curriculum'},
             'page': 86,
             'text': {'en': 'Preparing to Pray in Vietnamese',
                      'ja': 'ベトナム語で祈る準備をする',
                      'ko': '베트남어로 기도 준비하기',
                      'zh': '準備用越南語禱告',
                      'de': 'Gebet auf Vietnamesisch vorbereiten',
                      'fr': 'Préparation d’une prière en vietnamien'}}],
  'note': {'en': 'Preparing to Pray in Vietnamese',
           'ja': 'ベトナム語で祈りを準備する',
           'ko': '베트남어로 기도 준비하기',
           'zh': '準備用越南語禱告',
           'de': 'Ein Gebet auf Vietnamesisch vorbereiten',
           'fr': 'Préparation d’une prière en vietnamien'},
  'week': 10},
 {'items': [{'link': {'subAttr': 'wizard',
                      'subVal': 'talks',
                      'tab': 'wizard',
                      'talkNums': [1, 2, 3, 4]},
             'page': None,
             'text': {'en': 'Review of Offer Talks 1, 2, 3, 4',
                      'ja': '提供の話1、2、3、4の復習',
                      'ko': '제공 연설 1,2,3,4 복습',
                      'zh': '提供演講 1、2、3、4 複習',
                      'de': 'Wiederholung der Gesprächsvorschläge 1, 2, 3, 4',
                      'fr': 'Révision des présentations 1, 2, 3, 4'}},
            {'link': {'subAttr': 'vocab',
                      'subVal': 'freq',
                      'tab': 'vocab',
                      'vocabRange': {'end': 1377, 'start': 1167}},
             'page': None,
             'text': {'en': 'Vietnamese Vocabulary Study – Week 11 (Frequent 1187-1399)',
                      'ja': 'ベトナム語語彙学習 11週目（常用 1187~1399）',
                      'ko': '베트남어 어휘 학습 11주차 (상용 1187~1399번)',
                      'zh': '越南語詞彙學習 第11週（常用 1187~1399）',
                      'de': 'Vietnamesischer Wortschatz – Woche 11 (Häufig 1187–1399)',
                      'fr': 'Vocabulaire vietnamien – Semaine 11 (Fréquent 1187–1399)'}},
            {'link': {'subAttr': 'sentence',
                      'subVal': 'wt',
                      'tab': 'sentence',
                      'vocabRange': {'end': 750, 'start': 700}},
             'page': None,
             'text': {'en': 'Vietnamese Watchtower Vocabulary Study – Week 11 (50 Words)',
                      'ja': 'ベトナム語ものみの塔語彙50個学習 11週目',
                      'ko': '베트남어 파수대 어휘 50개 학습 11주차',
                      'zh': '越南語守望台詞彙50個學習 第11週',
                      'de': 'Vietnamesischer Wachtturm-Wortschatz – Woche 11 (50 Wörter)',
                      'fr': 'Vocabulaire vietnamien de La Tour de Garde – Semaine 11 (50 mots)'}},
            {'link': None,
             'page': None,
             'text': {'en': 'Vietnamese Reading Practice',
                      'ja': 'ベトナム語読解練習',
                      'ko': '베트남어 읽기 연습',
                      'zh': '越南語閱讀練習',
                      'de': 'Vietnamesische Leseübungen',
                      'fr': 'Entraînement à la lecture en vietnamien'}},
            {'link': {'subAttr': 'grammar', 'subVal': 'sentences', 'tab': 'grammar'},
             'page': None,
             'text': {'en': 'Building Vietnamese Sentences Using the Universal Language Generation '
                            'Method',
                      'ja': '汎用言語生成法を使ってベトナム語の文を作る',
                      'ko': '범용언어 생성법을 통한 베트남어 문장 만들기',
                      'zh': '運用通用語言生成法造越南語句子',
                      'de': 'Vietnamesische Sätze bilden mit der Satzbaumethode',
                      'fr': 'Construction de phrases vietnamiennes avec la méthode générale'}},
            {'link': None,
             'page': 90,
             'text': {'en': "Meeting Chairman's Expressions Practice (Brothers)",
                      'ja': '集会司会の表現練習（兄弟）',
                      'ko': '집회 사회 표현 연습 (형제)',
                      'zh': '聚會主持用語練習（弟兄）',
                      'de': 'Ausdrücke für den Zusammenkunftsvorsitz üben (Brüder)',
                      'fr': 'Expressions pour présider la réunion (Frères)'}},
            {'link': None,
             'page': None,
             'text': {'en': 'Watchtower Study Comments Preparation (Brothers, Sisters)',
                      'ja': '「ものみの塔」発表の準備（兄弟、姉妹）',
                      'ko': '파수대 발표 준비 (형제, 자매)',
                      'zh': '《守望台》發表準備（弟兄、姐妹）',
                      'de': 'Vorbereitung von Kommentaren für das Wachtturm-Studium (Brüder, '
                            'Schwestern)',
                      'fr': 'Préparation des commentaires pour l’étude de La Tour de Garde '
                            '(Frères, Sœurs)'}}],
  'note': {'en': 'Preparing to Chair the Meeting and Give a Watchtower Comment',
           'ja': '集会の司会と「ものみの塔」発表の準備',
           'ko': '집회 사회·파수대 발표 준비',
           'zh': '準備聚會主席與守望台發表',
           'de': 'Vorbereitung auf den Zusammenkunftsvorsitz und Wachtturm-Kommentare',
           'fr': 'Préparation pour présider la réunion et donner un commentaire à La Tour de '
                 'Garde'},
  'week': 11},
 {'items': [{'link': {'subAttr': 'wizard', 'subVal': 'talks', 'tab': 'wizard', 'talkNums': [5, 6]},
             'page': None,
             'text': {'en': 'Review of Offer Talks 5, 6',
                      'ja': '提供の話5、6の復習',
                      'ko': '제공 연설 5,6 복습',
                      'zh': '提供演講 5、6 複習',
                      'de': 'Wiederholung der Gesprächsvorschläge 5, 6',
                      'fr': 'Révision des présentations 5, 6'}},
            {'link': {'subAttr': 'vocab',
                      'subVal': 'freq',
                      'tab': 'vocab',
                      'vocabRange': {'end': 1476, 'start': 1377}},
             'page': None,
             'text': {'en': 'Vietnamese Vocabulary Study – Week 12 (Frequent 1400-1503)',
                      'ja': 'ベトナム語語彙学習 12週目（常用 1400~1503）',
                      'ko': '베트남어 어휘 학습 12주차 (상용 1400~1503번)',
                      'zh': '越南語詞彙學習 第12週（常用 1400~1503）',
                      'de': 'Vietnamesischer Wortschatz – Woche 12 (Häufig 1400–1503)',
                      'fr': 'Vocabulaire vietnamien – Semaine 12 (Fréquent 1400–1503)'}},
            {'link': {'subAttr': 'vocab',
                      'subVal': 'theo',
                      'tab': 'vocab',
                      'vocabRange': {'end': 109, 'start': 0}},
             'page': None,
             'text': {'en': 'Vietnamese Vocabulary Study – Week 12 (Theocratic 1-109)',
                      'ja': 'ベトナム語語彙学習 12週目（神権 1~109）',
                      'ko': '베트남어 어휘 학습 12주차 (신권 1~109번)',
                      'zh': '越南語詞彙學習 第12週（屬靈詞彙 1~109）',
                      'de': 'Vietnamesischer Wortschatz – Woche 12 (Theokratisch 1–109)',
                      'fr': 'Vocabulaire vietnamien – Semaine 12 (Théocratique 1–109)'}},
            {'link': {'subAttr': 'sentence',
                      'subVal': 'wt',
                      'tab': 'sentence',
                      'vocabRange': {'end': 800, 'start': 750}},
             'page': None,
             'text': {'en': 'Vietnamese Watchtower Vocabulary Study – Week 12 (50 Words)',
                      'ja': 'ベトナム語ものみの塔語彙50個学習 12週目',
                      'ko': '베트남어 파수대 어휘 50개 학습 12주차',
                      'zh': '越南語守望台詞彙50個學習 第12週',
                      'de': 'Vietnamesischer Wachtturm-Wortschatz – Woche 12 (50 Wörter)',
                      'fr': 'Vocabulaire vietnamien de La Tour de Garde – Semaine 12 (50 mots)'}},
            {'link': {'subAttr': 'grammar', 'subVal': 'special', 'tab': 'grammar'},
             'page': 93,
             'text': {'en': 'Special Lecture on Vietnamese Grammar',
                      'ja': 'ベトナム語文法特別講座',
                      'ko': '베트남어 문법 특강',
                      'zh': '越南語文法特別課程',
                      'de': 'Sonderlektion: Vietnamesische Grammatik',
                      'fr': 'Leçon spéciale de grammaire vietnamienne'}},
            {'link': None,
             'page': None,
             'text': {'en': 'Preparing Situational Demonstrations',
                      'ja': '状況別実演の準備',
                      'ko': '상황별 실연 준비',
                      'zh': '情境示範準備',
                      'de': 'Vorbereitung von Demonstrationen für verschiedene Situationen',
                      'fr': 'Préparation de démonstrations par situation'}},
            {'link': {'subAttr': 'vocab', 'subVal': 'dialect', 'tab': 'vocab'},
             'page': None,
             'text': {'en': 'Vietnamese North/South Vocabulary Differences',
                      'ja': 'ベトナム語の南北単語の違い',
                      'ko': '베트남어 남북 단어 차이',
                      'zh': '越南語南北詞彙差異',
                      'de': 'Wortschatzunterschiede Nord/Süd im Vietnamesischen',
                      'fr': 'Différences de vocabulaire Nord/Sud en vietnamien'}}],
  'note': {'en': 'Learning North–South Vietnamese Word Differences',
           'ja': 'ベトナム語の南北の単語の違いを学ぶ',
           'ko': '베트남어 남북 단어 차이 배우기',
           'zh': '學習越南語南北用語差異',
           'de': 'Wortschatzunterschiede zwischen Nord und Süd im Vietnamesischen lernen',
           'fr': 'Apprentissage des différences de vocabulaire entre le Nord et le Sud'},
  'week': 12},
 {'items': [{'link': {'subAttr': 'wizard', 'subVal': 'talks', 'tab': 'wizard', 'talkNums': [7, 8]},
             'page': None,
             'text': {'en': 'Review of Offer Talks 7, 8',
                      'ja': '提供の話7、8の復習',
                      'ko': '제공 연설 7,8 복습',
                      'zh': '提供演講 7、8 複習',
                      'de': 'Wiederholung der Gesprächsvorschläge 7, 8',
                      'fr': 'Révision des présentations 7, 8'}},
            {'link': {'subAttr': 'vocab',
                      'subVal': 'theo',
                      'tab': 'vocab',
                      'vocabRange': {'end': 283, 'start': 109}},
             'page': None,
             'text': {'en': 'Vietnamese Vocabulary Study – Week 13 (Theocratic 110-283)',
                      'ja': 'ベトナム語語彙学習 13週目（神権 110~283）',
                      'ko': '베트남어 어휘 학습 13주차 (신권 110~283번)',
                      'zh': '越南語詞彙學習 第13週（屬靈詞彙 110~283）',
                      'de': 'Vietnamesischer Wortschatz – Woche 13 (Theokratisch 110–283)',
                      'fr': 'Vocabulaire vietnamien – Semaine 13 (Théocratique 110–283)'}},
            {'link': {'subAttr': 'vocab',
                      'subVal': 'names',
                      'tab': 'vocab',
                      'vocabRange': {'end': 38, 'start': 0}},
             'page': None,
             'text': {'en': 'Vietnamese Vocabulary Study – Week 13 (Names 1-38)',
                      'ja': 'ベトナム語語彙学習 13週目（人名 1~38）',
                      'ko': '베트남어 어휘 학습 13주차 (인명 1~38번)',
                      'zh': '越南語詞彙學習 第13週（人名 1~38）',
                      'de': 'Vietnamesischer Wortschatz – Woche 13 (Namen 1–38)',
                      'fr': 'Vocabulaire vietnamien – Semaine 13 (Noms 1–38)'}},
            {'link': {'subAttr': 'sentence',
                      'subVal': 'wt',
                      'tab': 'sentence',
                      'vocabRange': {'end': 850, 'start': 800}},
             'page': None,
             'text': {'en': 'Vietnamese Watchtower Vocabulary Study – Week 13 (50 Words)',
                      'ja': 'ベトナム語ものみの塔語彙50個学習 13週目',
                      'ko': '베트남어 파수대 어휘 50개 학습 13주차',
                      'zh': '越南語守望台詞彙50個學習 第13週',
                      'de': 'Vietnamesischer Wachtturm-Wortschatz – Woche 13 (50 Wörter)',
                      'fr': 'Vocabulaire vietnamien de La Tour de Garde – Semaine 13 (50 mots)'}},
            {'link': {'anchor': 'song-46',
                      'subAttr': 'curriculum',
                      'subVal': 'song',
                      'tab': 'curriculum'},
             'page': None,
             'text': {'en': 'Vietnamese Song (No. 46, Graduation Song) Preparation',
                      'ja': 'ベトナム語の歌（46番、卒業式の歌）準備',
                      'ko': '베트남어 노래 (46번, 졸업식 노래) 준비',
                      'zh': '越南語詩歌（第46首，畢業典禮詩歌）準備',
                      'de': 'Vietnamesisches Lied (Nr. 46, Abschlusslied) – Vorbereitung',
                      'fr': 'Cantique en vietnamien (n° 46, chant de clôture) – Préparation'}},
            {'link': None,
             'page': None,
             'text': {'en': 'Vietnamese Meeting Rehearsal',
                      'ja': 'ベトナム語集会リハーサル',
                      'ko': '베트남어 집회 리허설',
                      'zh': '越南語聚會演練',
                      'de': 'Probe für die vietnamesische Zusammenkunft',
                      'fr': 'Répétition de la réunion en vietnamien'}},
            {'link': {'subAttr': 'vocab', 'subVal': 'orderrev', 'tab': 'vocab'},
             'page': None,
             'text': {'en': 'Sino-Vietnamese Words with Reversed Word Order',
                      'ja': 'ベトナム語の語順が逆の漢字語',
                      'ko': '베트남어 어순반대 한자어',
                      'zh': '越南語語序相反的漢字詞',
                      'de': 'Sino-vietnamesische Wörter mit umgekehrter Wortstellung',
                      'fr': 'Mots sino-vietnamiens à ordre inverse'}}],
  'note': {'en': 'Preparing the Graduation Song (No. 46) and Meeting Rehearsal',
           'ja': '卒業式の歌(46番)と集会リハーサルの準備',
           'ko': '졸업식 노래(46번)와 집회 리허설 준비',
           'zh': '準備畢業典禮詩歌(第46首)與聚會彩排',
           'de': 'Vorbereitung des Abschlusslieds (Nr. 46) und Zusammenkunftsprobe',
           'fr': 'Préparation du cantique de fin de cours (n° 46) et répétition de la réunion'},
  'week': 13},
 {'items': [{'link': {'subAttr': 'wizard',
                      'subVal': 'talks',
                      'tab': 'wizard',
                      'talkNums': [9, 10, 11]},
             'page': None,
             'text': {'en': 'Review of Offer Talks 9, 10, 11',
                      'ja': '提供の話9、10、11の復習',
                      'ko': '제공 연설 9,10,11 복습',
                      'zh': '提供演講 9、10、11 複習',
                      'de': 'Wiederholung der Gesprächsvorschläge 9, 10, 11',
                      'fr': 'Révision des présentations 9, 10, 11'}},
            {'link': {'subAttr': 'vocab',
                      'subVal': 'names',
                      'tab': 'vocab',
                      'vocabRange': {'end': 184, 'start': 38}},
             'page': None,
             'text': {'en': 'Vietnamese Vocabulary Study – Week 14 (Names 39-184)',
                      'ja': 'ベトナム語語彙学習 14週目（人名 39~184）',
                      'ko': '베트남어 어휘 학습 14주차 (인명 39~184번)',
                      'zh': '越南語詞彙學習 第14週（人名 39~184）',
                      'de': 'Vietnamesischer Wortschatz – Woche 14 (Namen 39–184)',
                      'fr': 'Vocabulaire vietnamien – Semaine 14 (Noms 39–184)'}},
            {'link': {'subAttr': 'vocab',
                      'subVal': 'chain',
                      'tab': 'vocab',
                      'vocabRange': {'end': 67, 'start': 0}},
             'page': None,
             'text': {'en': 'Vietnamese Vocabulary Study – Week 14 (Word Chain 1-67)',
                      'ja': 'ベトナム語語彙学習 14週目（しりとり 1~67）',
                      'ko': '베트남어 어휘 학습 14주차 (끝말 1~67번)',
                      'zh': '越南語詞彙學習 第14週（字尾 1~67）',
                      'de': 'Vietnamesischer Wortschatz – Woche 14 (Wortketten 1–67)',
                      'fr': 'Vocabulaire vietnamien – Semaine 14 (Mots enchaînés 1–67)'}},
            {'link': {'subAttr': 'sentence',
                      'subVal': 'wt',
                      'tab': 'sentence',
                      'vocabRange': {'end': 900, 'start': 850}},
             'page': None,
             'text': {'en': 'Vietnamese Watchtower Vocabulary Study – Week 14 (50 Words)',
                      'ja': 'ベトナム語ものみの塔語彙50個学習 14週目',
                      'ko': '베트남어 파수대 어휘 50개 학습 14주차',
                      'zh': '越南語守望台詞彙50個學習 第14週',
                      'de': 'Vietnamesischer Wachtturm-Wortschatz – Woche 14 (50 Wörter)',
                      'fr': 'Vocabulaire vietnamien de La Tour de Garde – Semaine 14 (50 mots)'}},
            {'link': None,
             'page': None,
             'text': {'en': 'Graduation Ceremony Preparation (Assignments)',
                      'ja': '卒業式の準備（任命）',
                      'ko': '졸업식 준비 (임명)',
                      'zh': '畢業典禮準備（指派）',
                      'de': 'Vorbereitung auf die Abschlussfeier (Zuteilungen)',
                      'fr': 'Préparation de la cérémonie de clôture (Attributions)'}},
            {'link': {'subAttr': 'vocab', 'subVal': 'chain', 'tab': 'vocab'},
             'page': None,
             'text': {'en': 'Vietnamese Word Chain Game',
                      'ja': 'ベトナム語しりとり',
                      'ko': '베트남어 끝말잇기',
                      'zh': '越南語文字接龍',
                      'de': 'Vietnamesisches Wortkettenspiel',
                      'fr': 'Jeu des mots enchaînés en vietnamien'}}],
  'note': {'en': 'Preparing for Graduation and Assignments',
           'ja': '卒業式の準備と割り当て',
           'ko': '졸업식 준비 및 임명',
           'zh': '畢業典禮準備與委派',
           'de': 'Vorbereitung auf den Abschluss und Zuteilungen',
           'fr': 'Préparation de la cérémonie de fin de cours et attributions'},
  'week': 14},
 {'items': [{'link': None,
             'page': None,
             'text': {'en': 'Watchtower Meeting Demonstration (Chairman, Reading, Comments)',
                      'ja': '「ものみの塔」集会の実演（司会、朗読、発表）',
                      'ko': '파수대 집회 실연 (사회, 낭독, 발표)',
                      'zh': '《守望台》聚會實演（主持、朗讀、發表）',
                      'de': 'Demonstration des Wachtturm-Studiums (Vorsitz, Vorlesen, Kommentare)',
                      'fr': 'Démonstration de la réunion de La Tour de Garde (Président, lecture, '
                            'commentaires)'}},
            {'link': {'subAttr': 'vocab',
                      'subVal': 'chain',
                      'tab': 'vocab',
                      'vocabRange': {'end': 232, 'start': 67}},
             'page': None,
             'text': {'en': 'Vietnamese Vocabulary Study – Week 15 (Word Chain 68-232)',
                      'ja': 'ベトナム語語彙学習 15週目（しりとり 68~232）',
                      'ko': '베트남어 어휘 학습 15주차 (끝말 68~232번)',
                      'zh': '越南語詞彙學習 第15週（字尾 68~232）',
                      'de': 'Vietnamesischer Wortschatz – Woche 15 (Wortketten 68–232)',
                      'fr': 'Vocabulaire vietnamien – Semaine 15 (Mots enchaînés 68–232)'}},
            {'link': {'subAttr': 'vocab',
                      'subVal': 'dialect',
                      'tab': 'vocab',
                      'vocabRange': {'end': 48, 'start': 0}},
             'page': None,
             'text': {'en': 'Vietnamese Vocabulary Study – Week 15 (North/South Words 1-48)',
                      'ja': 'ベトナム語語彙学習 15週目（南北の単語 1~48）',
                      'ko': '베트남어 어휘 학습 15주차 (남북 단어 1~48번)',
                      'zh': '越南語詞彙學習 第15週（南北用詞 1~48）',
                      'de': 'Vietnamesischer Wortschatz – Woche 15 (Nord/Süd-Wörter 1–48)',
                      'fr': 'Vocabulaire vietnamien – Semaine 15 (Mots Nord/Sud 1–48)'}},
            {'link': {'subAttr': 'sentence',
                      'subVal': 'wt',
                      'tab': 'sentence',
                      'vocabRange': {'end': 950, 'start': 900}},
             'page': None,
             'text': {'en': 'Vietnamese Watchtower Vocabulary Study – Week 15 (50 Words)',
                      'ja': 'ベトナム語ものみの塔語彙50個学習 15週目',
                      'ko': '베트남어 파수대 어휘 50개 학습 15주차',
                      'zh': '越南語守望台詞彙50個學習 第15週',
                      'de': 'Vietnamesischer Wachtturm-Wortschatz – Woche 15 (50 Wörter)',
                      'fr': 'Vocabulaire vietnamien de La Tour de Garde – Semaine 15 (50 mots)'}},
            {'link': None,
             'page': None,
             'text': {'en': 'Graduation',
                      'ja': '卒業',
                      'ko': '졸업',
                      'zh': '畢業',
                      'de': 'Kursabschluss',
                      'fr': 'Fin de cours'}}],
  'note': {'en': 'Watchtower Meeting Demonstration and Graduation',
           'ja': '「ものみの塔」集会の実演と卒業',
           'ko': '파수대 집회 실연과 졸업',
           'zh': '守望台聚會實演與畢業',
           'de': 'Demonstration des Wachtturm-Studiums und Kursabschluss',
           'fr': 'Démonstration de l’étude de La Tour de Garde et remise des attestations'},
  'week': 15},
 {'items': [{'link': {'subAttr': 'pron', 'subVal': 'tones', 'tab': 'pron'},
             'page': None,
             'text': {'en': 'Cumulative review of pronunciation and tones from all 16 weeks',
                      'ja': '16週間で学んだ発音・声調の総復習',
                      'ko': '16주간 배운 발음·성조 총복습',
                      'zh': '總複習16週學過的發音與聲調',
                      'de': 'Gesamtwiederholung von Aussprache und Tönen aus allen 16 Wochen',
                      'fr': 'Révision générale de la prononciation et des tons des 16 semaines'}},
            {'link': {'subAttr': 'review', 'subVal': 'vocab', 'tab': 'review'},
             'page': None,
             'text': {'en': 'Review game covering all vocabulary studied',
                      'ja': '学んだ語彙全体の復習ゲーム',
                      'ko': '배운 어휘 전체 복습 게임',
                      'zh': '複習學過的所有詞彙',
                      'de': 'Wiederholungsspiel zum gesamten gelernten Wortschatz',
                      'fr': 'Jeu de révision portant sur tout le vocabulaire étudié'}},
            {'link': {'subAttr': 'wizard', 'subVal': 'talks', 'tab': 'wizard'},
             'page': None,
             'text': {'en': 'Review all offer talks',
                      'ja': '提供のスピーチ全体の復習',
                      'ko': '제공 연설 전체 복습',
                      'zh': '複習所有提供演講',
                      'de': 'Wiederholung aller Gesprächsvorschläge',
                      'fr': 'Révision de toutes les présentations'}},
            {'link': {'subAttr': 'sentence',
                      'subVal': 'wt',
                      'tab': 'sentence',
                      'vocabRange': {'end': 1000, 'start': 950}},
             'page': None,
             'text': {'en': 'Vietnamese Watchtower Vocabulary Study – Week 16 (50 Words)',
                      'ja': 'ベトナム語ものみの塔語彙50個学習 16週目',
                      'ko': '베트남어 파수대 어휘 50개 학습 16주차',
                      'zh': '越南語守望台詞彙50個學習 第16週',
                      'de': 'Vietnamesischer Wachtturm-Wortschatz – Woche 16 (50 Wörter)',
                      'fr': 'Vocabulaire vietnamien de La Tour de Garde – Semaine 16 (50 mots)'}}],
  'note': {'en': 'A wrap-up review of all the pronunciation, vocabulary, offer talks, and Bible '
                 'knowledge covered so far.',
           'ja': 'これまで学んだ発音、語彙、提供のスピーチ、聖書の知識を総復習します。',
           'ko': '지금까지 배운 발음, 어휘, 제공 연설, 성서 지식을 총정리하며 복습합니다.',
           'zh': '總結並複習至今學過的發音、詞彙、提供演講和聖經知識。',
           'de': 'Abschließende Gesamtwiederholung aller bisher behandelten Themen: Aussprache, '
                 'Wortschatz, Gesprächsvorschläge und biblisches Wissen.',
           'fr': 'Révision générale récapitulative de la prononciation, du vocabulaire, des '
                 'présentations et des connaissances bibliques acquises.'},
  'title': {'en': 'Week 16 (Cumulative Review)',
            'ja': '16週目（総復習）',
            'ko': '16주 (총복습)',
            'zh': '第16週（總複習）',
            'de': 'Woche 16 (Gesamtwiederholung)',
            'fr': 'Semaine 16 (Révision générale)'},
  'week': 16}]
