# "교과" tab -- content drawn from the PDF course booklet
# "베트남어 학습반 16주 과정" (Vietnamese-language study class, 16-week course).
# WELCOME_TEXT / COURSE_PHASES / WEEK16_TOC below are transcribed verbatim from
# pages 3-6 of that booklet.
#
# Translatable Korean text fields (title/body/range/text/note) are stored as
# {"ko","zh","en","ja"} dicts so js_json() (see build_app.py) serializes them straight into JS
# objects that app_logic.js's T() helper can read directly. Structural fields (page, link) are
# left as plain values.

WELCOME_TEXT = {'title': {'ko': '베트남어 학습반에 오신 여러분을 환영합니다!!',
           'zh': '歡迎各位來到越南語學習班！！',
           'en': 'Welcome to the Vietnamese class!!',
           'ja': 'ベトナム語訓練コースへようこそ！！'},
 'body': [{'ko': '이 학습반은 베트남어로 좋은 소식을 전파하기 위해 마련된 것입니다.',
           'zh': '這個學習班是為了用越南語傳講好消息而設立的。',
           'en': 'This class was set up to help preach the good news in Vietnamese.',
           'ja': 'このクラスは、ベトナム語で良い知らせを伝えるために設けられたものです。'},
          {'ko': '이 과정은 베트남어에 대해 철저히 연구하기 위한 것이 아니라 형제 자매들이 베트남어의 기초를 배우도록 도움을 주기 위한 것입니다.',
           'zh': '這個課程並非要對越南語進行深入的研究，而是要幫助弟兄姐妹學習越南語的基礎。',
           'en': 'Its purpose is not to thoroughly study the Vietnamese language, but to help brothers and '
                 'sisters learn the basics of Vietnamese.',
           'ja': 'このコースはベトナム語を徹底的に研究するためのものではなく、兄弟姉妹がベトナム語の基礎を学ぶ手助けをするためのものです。'},
          {'ko': '형제 자매들은 이 학습반이 끝난 후 야외 봉사에서 정기적으로 베트남어를 사용하고 베트남어 회중이나 집단의 활동에 참여함으로 계속 발전하게 될 것입니다.',
           'zh': '學習班結束後，弟兄姐妹將能夠在外勤傳道中經常使用越南語，並藉著參與越南語會眾或小組的活動繼續進步。',
           'en': 'After completing this class, brothers and sisters will continue to improve by regularly '
                 'using Vietnamese in the field ministry and by participating in the activities of a '
                 'Vietnamese congregation or group.',
           'ja': '兄弟姉妹はこのクラスが終わった後、野外奉仕で定期的にベトナム語を使い、ベトナム語の会衆やグループの活動に参加することによって、引き続き上達していくことになります。'},
          {'ko': '이 학습반은 16주간 운영되며 교과 과정은 아래와 같습니다.',
           'zh': '這個學習班為期16週，課程內容如下。',
           'en': 'This class runs for 16 weeks, and the curriculum is as follows.',
           'ja': 'このクラスは16週間行われ、カリキュラムは以下の通りです。'}]}

COURSE_PHASES = [{'range': {'ko': '1-4주', 'zh': '第1-4週', 'en': 'Weeks 1-4', 'ja': '第1～4週'},
  'title': {'ko': '베트남어의 기초', 'zh': '越南語基礎', 'en': 'Basics of Vietnamese', 'ja': 'ベトナム語の基礎'},
  'body': [{'ko': '베트남어의 자음과 모음 발음법, 성서 책명, 인명 등을 함께 공부합니다. 베트남어의 가장 큰 특징인 성조를 익히고 계속 연습합니다. 성조는 학습반 기간 동안 '
                  '계속 반복적으로 학습해서 익혀 나가도록 합니다.',
            'zh': '一起學習越南語子音和母音的發音方法、聖經書名、人名等。學習並持續練習越南語最大的特色——聲調。聲調將在整個課程期間反覆練習，逐步熟練掌握。',
            'en': 'You will study Vietnamese consonant and vowel pronunciation together with Bible book '
                  'names, personal names, and more. You will learn and keep practicing tone, the most '
                  'distinctive feature of Vietnamese. Tones will be practiced repeatedly throughout the '
                  'course so that you gradually master them.',
            'ja': 'ベトナム語の子音と母音の発音方法、聖書の書名、人名などを一緒に学びます。ベトナム語最大の特徴である声調を身につけ、継続して練習します。声調はクラス期間を通じて繰り返し学習し、身につけていきます。'},
           {'ko': '봉사의 직무에서 바로 활용할 수 있는 기본적인 제공 연설을 공부하고 훈련합니다.',
            'zh': '學習並訓練可以在服事職務中立即運用的基本提供演講。',
            'en': 'You will study and practice basic offer talks that can be put to immediate use in the '
                  'ministry.',
            'ja': '奉仕の務めですぐに活用できる基本的な提供のスピーチを学び、訓練します。'},
           {'ko': '첫 한 달 수업 과정이 끝난 후 베트남어 집회에 참석하신다면 유익할 것입니다.',
            'zh': '完成第一個月的課程後，如果能夠參加越南語聚會，將會很有幫助。',
            'en': 'After finishing the first month of classes, it would be beneficial to attend a '
                  'Vietnamese-language meeting.',
            'ja': '最初の1か月の授業課程が終わった後、ベトナム語の集会に出席すると有益でしょう。'}]},
 {'range': {'ko': '5-14주', 'zh': '第5–14週', 'en': 'Weeks 5–14', 'ja': '5～14週目'},
  'title': {'ko': '베트남어 단어와 작문 수업, 베트남어 출판물 읽기 연습',
            'zh': '越南語詞彙與寫作課程、越南語出版物閱讀練習',
            'en': 'Vietnamese vocabulary and writing lessons, Vietnamese publication reading practice',
            'ja': 'ベトナム語の単語と作文の授業、ベトナム語出版物の読解練習'},
  'body': [{'ko': '기본 단어 800개를 익히고 범용언어 생성법을 통한 베트남어 문장 만들기를 연습합니다.',
            'zh': '學習800個基本詞彙，並透過通用造句法練習組成越南語句子。',
            'en': 'You will learn 800 basic words and practice forming Vietnamese sentences using a general '
                  'sentence-building method.',
            'ja': '基本単語800個を身につけ、汎用言語生成法を通してベトナム語の文章作りを練習します。'},
           {'ko': '“행누” 베트남어를 주 교재로 해서 베트남어 읽기 연습을 합니다.',
            'zh': '以《행누》越南語教材為主，進行越南語閱讀練習。',
            'en': 'You will practice Vietnamese reading using "행누" Vietnamese as the main textbook.',
            'ja': '「행누」ベトナム語を主な教材としてベトナム語の読解練習を行います。'},
           {'ko': '이 기간에도 변함없이 베트남어 성조를 연습하고 베트남어 기본 표현들을 계속 익혀 나갑니다.',
            'zh': '這段期間也一如既往地練習越南語聲調，並持續學習越南語基本表達方式。',
            'en': 'During this period as well, you will keep practicing Vietnamese tones as before and '
                  'continue learning basic Vietnamese expressions.',
            'ja': 'この期間も変わらずベトナム語の声調を練習し、ベトナム語の基本表現を引き続き身につけていきます。'}]},
 {'range': {'ko': '15-16주', 'zh': '第15–16週', 'en': 'Weeks 15–16', 'ja': '15～16週目'},
  'title': {'ko': '베트남어로 연설을 준비하거나 베트남어로 성서 연구 사회 준비',
            'zh': '準備越南語演講，或準備以越南語主持聖經研究',
            'en': 'Preparing a talk in Vietnamese, or preparing to conduct a Bible study in Vietnamese',
            'ja': 'ベトナム語でスピーチを準備するか、ベトナム語で聖書研究の司会を準備する'},
  'body': [{'ko': '한 가지 주제로 베트남어 연설을 준비하거나 해당 주 생활과 봉사 집회 과제를 준비해 봅니다.',
            'zh': '嘗試以一個主題準備越南語演講，或準備當週的生活與服事聚會作業。',
            'en': "Try preparing a Vietnamese talk on one topic, or preparing that week's Christian Life and "
                  'Ministry Meeting assignment.',
            'ja': '一つのテーマでベトナム語のスピーチを準備するか、その週の「クリスチャン生活と奉仕」の集会の課題を準備してみます。'},
           {'ko': '회중 성서 연구 혹은 파수대 집회에서 베트남어로 발표해 봅니다.',
            'zh': '嘗試在會眾聖經研究班或《守望台》研究班上用越南語發表。',
            'en': 'Try giving a comment in Vietnamese at the congregation Bible study or the Watchtower '
                  'Study.',
            'ja': '会衆聖書研究または「ものみの塔」研究の集会でベトナム語で発表してみます。'},
           {'ko': '베트남어로 성서 연구 사회를 해 봅니다.',
            'zh': '嘗試以越南語主持聖經研究。',
            'en': 'Try conducting a Bible study in Vietnamese.',
            'ja': 'ベトナム語で聖書研究の司会をしてみます。'}]}]

WEEK16_TOC = [{'week': 1,
  'items': [{'text': {'ko': '베트남어 발음 설정',
                      'zh': '越南語發音設定',
                      'en': 'Vietnamese Pronunciation – Setup',
                      'ja': 'ベトナム語発音設定'},
             'page': None,
             'link': {'tab': 'pron', 'subAttr': 'pron', 'subVal': 'settings'}},
            {'text': {'ko': '베트남어 문자', 'zh': '越南語文字', 'en': 'Vietnamese Alphabet', 'ja': 'ベトナム語の文字'},
             'page': None,
             'link': {'tab': 'pron', 'subAttr': 'pron', 'subVal': 'alphabet'}},
            {'text': {'ko': '베트남어 발음 – 모음',
                      'zh': '越南語發音－母音',
                      'en': 'Vietnamese Pronunciation – Vowels',
                      'ja': 'ベトナム語の発音－母音'},
             'page': 11,
             'link': {'tab': 'pron', 'subAttr': 'pron', 'subVal': 'vowels'}},
            {'text': {'ko': '베트남어 발음 – 자음',
                      'zh': '越南語發音－子音',
                      'en': 'Vietnamese Pronunciation – Consonants',
                      'ja': 'ベトナム語の発音－子音'},
             'page': 9,
             'link': {'tab': 'pron', 'subAttr': 'pron', 'subVal': 'consonants'}},
            {'text': {'ko': '성조연습', 'zh': '聲調練習', 'en': 'Tone Practice', 'ja': '声調練習'},
             'page': 7,
             'link': {'tab': 'pron', 'subAttr': 'pron', 'subVal': 'tones'}},
            {'text': {'ko': '베트남어 어휘 학습 1주차 (한자음 1~212번)',
                      'zh': '越南語詞彙學習 第1週（漢字音 1~212）',
                      'en': 'Vietnamese Vocabulary Study – Week 1 (Sino-Vietnamese 1-212)',
                      'ja': 'ベトナム語語彙学習 1週目（漢越音 1~212）'},
             'page': None,
             'link': {'tab': 'vocab', 'subAttr': 'vocab', 'subVal': 'rhyme', 'vocabRange': {'start': 0, 'end': 212}}},
            {'text': {'ko': '베트남어 파수대 어휘 50개 학습 1주차',
                      'zh': '越南語守望台詞彙50個學習 第1週',
                      'en': 'Vietnamese Watchtower Vocabulary Study – Week 1 (50 Words)',
                      'ja': 'ベトナム語ものみの塔語彙50個学習 1週目'},
             'page': None,
             'link': {'tab': 'vocab', 'subAttr': 'vocab', 'subVal': 'wt', 'vocabRange': {'start': 0, 'end': 50}}},
            {'text': {'ko': '베트남어 제공 연설 1',
                      'zh': '越南語提供演講1',
                      'en': 'Vietnamese Offer Talk 1',
                      'ja': 'ベトナム語の提供のスピーチ1'},
             'page': 13,
             'link': {'tab': 'wizard', 'subAttr': 'wizard', 'subVal': 'talks', 'talkNums': [1]}}],
  'note': {'ko': '베트남어 문자와 발음 기초 배우기',
           'zh': '學習越南語字母與發音基礎',
           'en': 'Learning Vietnamese Letters and Basic Pronunciation',
           'ja': 'ベトナム語の文字と発音の基礎を学ぶ'}},
 {'week': 2,
  'items': [{'text': {'ko': '성조연습', 'zh': '聲調練習', 'en': 'Tone Practice', 'ja': '声調練習'},
             'page': None,
             'link': {'tab': 'pron', 'subAttr': 'pron', 'subVal': 'tones'}},
            {'text': {'ko': '베트남어 어휘 학습 2주차 (한자음 213~316번)',
                      'zh': '越南語詞彙學習 第2週（漢字音 213~316）',
                      'en': 'Vietnamese Vocabulary Study – Week 2 (Sino-Vietnamese 213-316)',
                      'ja': 'ベトナム語語彙学習 2週目（漢越音 213~316）'},
             'page': None,
             'link': {'tab': 'vocab',
                      'subAttr': 'vocab',
                      'subVal': 'rhyme',
                      'vocabRange': {'start': 212, 'end': 316}}},
            {'text': {'ko': '베트남어 어휘 학습 2주차 (어순반대 1~15번)',
                      'zh': '越南語詞彙學習 第2週（語序相反 1~15）',
                      'en': 'Vietnamese Vocabulary Study – Week 2 (Reversed Order 1-15)',
                      'ja': 'ベトナム語語彙学習 2週目（語順が逆 1~15）'},
             'page': None,
             'link': {'tab': 'vocab',
                      'subAttr': 'vocab',
                      'subVal': 'orderrev',
                      'vocabRange': {'start': 0, 'end': 15}}},
            {'text': {'ko': '베트남어 어휘 학습 2주차 (동일음 1~105번)',
                      'zh': '越南語詞彙學習 第2週（同音字 1~105）',
                      'en': 'Vietnamese Vocabulary Study – Week 2 (Same Sound 1-105)',
                      'ja': 'ベトナム語語彙学習 2週目（同音 1~105）'},
             'page': None,
             'link': {'tab': 'vocab',
                      'subAttr': 'vocab',
                      'subVal': 'groups',
                      'vocabRange': {'start': 0, 'end': 105}}},
            {'text': {'ko': '베트남어 파수대 어휘 50개 학습 2주차',
                      'zh': '越南語守望台詞彙50個學習 第2週',
                      'en': 'Vietnamese Watchtower Vocabulary Study – Week 2 (50 Words)',
                      'ja': 'ベトナム語ものみの塔語彙50個学習 2週目'},
             'page': None,
             'link': {'tab': 'vocab', 'subAttr': 'vocab', 'subVal': 'wt', 'vocabRange': {'start': 50, 'end': 100}}},
            {'text': {'ko': '베트남어 발음 – 자음, 모음 복습',
                      'zh': '越南語發音－子音、母音複習',
                      'en': 'Vietnamese Pronunciation – Consonant and Vowel Review',
                      'ja': 'ベトナム語の発音－子音、母音の復習'},
             'page': None,
             'link': {'tab': 'pron', 'subAttr': 'pron', 'subVal': 'consonants'}},
            {'text': {'ko': '베트남어 성경 책명 읽기 연습 1',
                      'zh': '越南語聖經書名朗讀練習1',
                      'en': 'Vietnamese Bible Book Name Reading Practice 1',
                      'ja': 'ベトナム語の聖書の書名読み練習1'},
             'page': 15,
             'link': {'tab': 'bible', 'subAttr': 'bible', 'subVal': 'books'}},
            {'text': {'ko': '베트남어 숫자 1–9', 'zh': '越南語數字1–9', 'en': 'Vietnamese Numbers 1–9', 'ja': 'ベトナム語の数字1～9'},
             'page': 17,
             'link': {'tab': 'bible', 'subAttr': 'bible', 'subVal': 'numbers'}},
            {'text': {'ko': '베트남어 제공 연설 2',
                      'zh': '越南語提供演講2',
                      'en': 'Vietnamese Offer Talk 2',
                      'ja': 'ベトナム語の提供のスピーチ2'},
             'page': 18,
             'link': {'tab': 'wizard', 'subAttr': 'wizard', 'subVal': 'talks', 'talkNums': [2]}},
            {'text': {'ko': '베트남어 노래 (46번)',
                      'zh': '越南語詩歌(第46首)',
                      'en': 'Vietnamese Song (No. 46)',
                      'ja': 'ベトナム語の歌(46番)'},
             'page': 19,
             'link': {'tab': 'curriculum', 'subAttr': 'curriculum', 'subVal': 'prayer', 'anchor': 'song-46'}}],
  'note': {'ko': '베트남어 성경 책명과 숫자 배우기 (풍선 준비)',
           'zh': '學習越南語聖經書名與數字（準備氣球）',
           'en': 'Learning Vietnamese Bible Book Names and Numbers (Balloon Preparation)',
           'ja': 'ベトナム語の聖書の書名と数字を学ぶ（風船の準備）'}},
 {'week': 3,
  'items': [{'text': {'ko': '성조연습, 연속성조',
                      'zh': '聲調練習、連續聲調',
                      'en': 'Tone Practice, Tone Sequences',
                      'ja': '声調練習、連続声調'},
             'page': 21,
             'link': {'tab': 'pron', 'subAttr': 'pron', 'subVal': 'tonepairs'}},
            {'text': {'ko': '베트남어 어휘 학습 3주차 (동일음 106~317번)',
                      'zh': '越南語詞彙學習 第3週（同音字 106~317）',
                      'en': 'Vietnamese Vocabulary Study – Week 3 (Same Sound 106-317)',
                      'ja': 'ベトナム語語彙学習 3週目（同音 106~317）'},
             'page': None,
             'link': {'tab': 'vocab',
                      'subAttr': 'vocab',
                      'subVal': 'groups',
                      'vocabRange': {'start': 105, 'end': 317}}},
            {'text': {'ko': '베트남어 파수대 어휘 50개 학습 3주차',
                      'zh': '越南語守望台詞彙50個學習 第3週',
                      'en': 'Vietnamese Watchtower Vocabulary Study – Week 3 (50 Words)',
                      'ja': 'ベトナム語ものみの塔語彙50個学習 3週目'},
             'page': None,
             'link': {'tab': 'vocab', 'subAttr': 'vocab', 'subVal': 'wt', 'vocabRange': {'start': 100, 'end': 150}}},
            {'text': {'ko': '베트남어 성경 책명 읽기 연습 2',
                      'zh': '越南語聖經書名朗讀練習2',
                      'en': 'Vietnamese Bible Book Name Reading Practice 2',
                      'ja': 'ベトナム語の聖書の書名読み練習2'},
             'page': 22,
             'link': {'tab': 'bible', 'subAttr': 'bible', 'subVal': 'books'}},
            {'text': {'ko': '베트남어 제공 연설 3',
                      'zh': '越南語提供演講3',
                      'en': 'Vietnamese Offer Talk 3',
                      'ja': 'ベトナム語の提供のスピーチ3'},
             'page': 24,
             'link': {'tab': 'wizard', 'subAttr': 'wizard', 'subVal': 'talks', 'talkNums': [3]}},
            {'text': {'ko': '신권 용어, 주요 인물 발음 연습(훈책)',
                      'zh': '神權用語、重要人物發音練習(훈책)',
                      'en': 'Theocratic terms, pronunciation practice for key Bible characters (훈책)',
                      'ja': '神権用語、主要人物の発音練習(훈책)'},
             'page': 25,
             'link': {'tab': 'vocab', 'subAttr': 'vocab', 'subVal': 'names'}}],
  'note': {'ko': '베트남어로 성경구절 찾아보기',
           'zh': '用越南語查找聖經經文',
           'en': 'Looking Up Bible Verses in Vietnamese',
           'ja': 'ベトナム語で聖句を調べる'}},
 {'week': 4,
  'items': [{'text': {'ko': '성조연습, 연속성조',
                      'zh': '聲調練習、連續聲調',
                      'en': 'Tone Practice, Tone Sequences',
                      'ja': '声調練習、連続声調'},
             'page': 36,
             'link': {'tab': 'pron', 'subAttr': 'pron', 'subVal': 'tonepairs'}},
            {'text': {'ko': '베트남어 어휘 학습 4주차 (동일음 318~530번)',
                      'zh': '越南語詞彙學習 第4週（同音字 318~530）',
                      'en': 'Vietnamese Vocabulary Study – Week 4 (Same Sound 318-530)',
                      'ja': 'ベトナム語語彙学習 4週目（同音 318~530）'},
             'page': None,
             'link': {'tab': 'vocab',
                      'subAttr': 'vocab',
                      'subVal': 'groups',
                      'vocabRange': {'start': 317, 'end': 530}}},
            {'text': {'ko': '베트남어 파수대 어휘 50개 학습 4주차',
                      'zh': '越南語守望台詞彙50個學習 第4週',
                      'en': 'Vietnamese Watchtower Vocabulary Study – Week 4 (50 Words)',
                      'ja': 'ベトナム語ものみの塔語彙50個学習 4週目'},
             'page': None,
             'link': {'tab': 'vocab', 'subAttr': 'vocab', 'subVal': 'wt', 'vocabRange': {'start': 150, 'end': 200}}},
            {'text': {'ko': '베트남어 숫자', 'zh': '越南語數字', 'en': 'Vietnamese Numbers', 'ja': 'ベトナム語の数字'},
             'page': 37,
             'link': {'tab': 'bible', 'subAttr': 'bible', 'subVal': 'numbers'}},
            {'text': {'ko': '베트남어 요일, 날짜',
                      'zh': '越南語星期、日期',
                      'en': 'Vietnamese Days of the Week, Dates',
                      'ja': 'ベトナム語の曜日、日付'},
             'page': 37,
             'link': {'tab': 'bible', 'subAttr': 'bible', 'subVal': 'days'}},
            {'text': {'ko': '베트남어 제공 연설 4',
                      'zh': '越南語提供演講4',
                      'en': 'Vietnamese Offer Talk 4',
                      'ja': 'ベトナム語の提供のスピーチ4'},
             'page': 42,
             'link': {'tab': 'wizard', 'subAttr': 'wizard', 'subVal': 'talks', 'talkNums': [4]}},
            {'text': {'ko': '베트남어 대화 연습 (자기소개, 연락처 교환)',
                      'zh': '越南語對話練習（自我介紹、交換聯絡方式）',
                      'en': 'Vietnamese Dialogue Practice (Self-Introduction, Exchanging Contact Info)',
                      'ja': 'ベトナム語会話練習（自己紹介、連絡先交換）'},
             'page': None,
             'link': {'tab': 'wizard', 'subAttr': 'wizard', 'subVal': 'main'}},
            {'text': {'ko': '성경 복습', 'zh': '聖經複習', 'en': 'Bible Review', 'ja': '聖書の復習'},
             'page': None,
             'link': {'tab': 'bible', 'subAttr': 'bible', 'subVal': 'books'}}],
  'note': {'ko': '베트남 사람에게 신상정보 물어보기',
           'zh': '向越南人詢問個人資料',
           'en': 'Asking a Vietnamese Person for Personal Information',
           'ja': 'ベトナム人に身上情報を尋ねる'}},
 {'week': 5,
  'items': [{'text': {'ko': '성조연습, 연속성조',
                      'zh': '聲調練習、連續聲調',
                      'en': 'Tone Practice, Tone Sequences',
                      'ja': '声調練習、連続声調'},
             'page': 44,
             'link': {'tab': 'pron', 'subAttr': 'pron', 'subVal': 'tonepairs'}},
            {'text': {'ko': '베트남어 어휘 학습 5주차 (동일음 531~620번)',
                      'zh': '越南語詞彙學習 第5週（同音字 531~620）',
                      'en': 'Vietnamese Vocabulary Study – Week 5 (Same Sound 531-620)',
                      'ja': 'ベトナム語語彙学習 5週目（同音 531~620）'},
             'page': None,
             'link': {'tab': 'vocab',
                      'subAttr': 'vocab',
                      'subVal': 'groups',
                      'vocabRange': {'start': 530, 'end': 620}}},
            {'text': {'ko': '베트남어 어휘 학습 5주차 (기본 1~113번)',
                      'zh': '越南語詞彙學習 第5週（基本 1~113）',
                      'en': 'Vietnamese Vocabulary Study – Week 5 (Base 1-113)',
                      'ja': 'ベトナム語語彙学習 5週目（基本 1~113）'},
             'page': None,
             'link': {'tab': 'vocab', 'subAttr': 'vocab', 'subVal': 'basic', 'vocabRange': {'start': 0, 'end': 113}}},
            {'text': {'ko': '베트남어 어휘 학습 5주차 (반의 1~10번)',
                      'zh': '越南語詞彙學習 第5週（反義 1~10）',
                      'en': 'Vietnamese Vocabulary Study – Week 5 (Antonyms 1-10)',
                      'ja': 'ベトナム語語彙学習 5週目（反意語 1~10）'},
             'page': None,
             'link': {'tab': 'vocab',
                      'subAttr': 'vocab',
                      'subVal': 'antonym',
                      'vocabRange': {'start': 0, 'end': 10}}},
            {'text': {'ko': '베트남어 파수대 어휘 50개 학습 5주차',
                      'zh': '越南語守望台詞彙50個學習 第5週',
                      'en': 'Vietnamese Watchtower Vocabulary Study – Week 5 (50 Words)',
                      'ja': 'ベトナム語ものみの塔語彙50個学習 5週目'},
             'page': None,
             'link': {'tab': 'vocab', 'subAttr': 'vocab', 'subVal': 'wt', 'vocabRange': {'start': 200, 'end': 250}}},
            {'text': {'ko': '베트남어 제공 연설 5',
                      'zh': '越南語提供演講5',
                      'en': 'Vietnamese Offer Talk 5',
                      'ja': 'ベトナム語の提供のスピーチ5'},
             'page': 45,
             'link': {'tab': 'wizard', 'subAttr': 'wizard', 'subVal': 'talks', 'talkNums': [5]}},
            {'text': {'ko': '베트남어 호칭', 'zh': '越南語稱謂', 'en': 'Vietnamese Terms of Address', 'ja': 'ベトナム語の呼び方'},
             'page': 46,
             'link': {'tab': 'wizard', 'subAttr': 'wizard', 'subVal': 'reftable'}},
            {'text': {'ko': '베트남어 시간', 'zh': '越南語時間', 'en': 'Vietnamese Time', 'ja': 'ベトナム語の時間'},
             'page': 46,
             'link': {'tab': 'bible', 'subAttr': 'bible', 'subVal': 'time'}},
            {'text': {'ko': '베트남어 출판물 읽기 연습 (행누, 랑제)',
                      'zh': '越南語出版物閱讀練習(행누, 랑제)',
                      'en': 'Vietnamese Publication Reading Practice (행누, 랑제)',
                      'ja': 'ベトナム語出版物の読解練習(행누, 랑제)'},
             'page': None,
             'link': None},
            {'text': {'ko': '숫자 복습 (3,6,9 게임)',
                      'zh': '數字複習(3、6、9遊戲)',
                      'en': 'Number Review (3-6-9 Game)',
                      'ja': '数字の復習(3・6・9ゲーム)'},
             'page': None,
             'link': {'tab': 'bible', 'subAttr': 'bible', 'subVal': 'numbers'}},
            {'text': {'ko': '베트남어 남북 발음 차이',
                      'zh': '越南語南北發音差異',
                      'en': 'Vietnamese North/South Pronunciation Differences',
                      'ja': 'ベトナム語の南北発音の違い'},
             'page': None,
             'link': {'tab': 'pron', 'subAttr': 'pron', 'subVal': 'nsdiff'}}],
  'note': {'ko': '베트남어 호칭 배우기', 'zh': '學習越南語稱謂', 'en': 'Learning Vietnamese Terms of Address', 'ja': 'ベトナム語の呼び方を学ぶ'}},
 {'week': 6,
  'items': [{'text': {'ko': '성조연습, 연속성조',
                      'zh': '聲調練習、連續聲調',
                      'en': 'Tone Practice, Tone Sequences',
                      'ja': '声調練習、連続声調'},
             'page': 60,
             'link': {'tab': 'pron', 'subAttr': 'pron', 'subVal': 'tonepairs'}},
            {'text': {'ko': '베트남어 어휘 학습 6주차 (반의 11~99번)',
                      'zh': '越南語詞彙學習 第6週（反義 11~99）',
                      'en': 'Vietnamese Vocabulary Study – Week 6 (Antonyms 11-99)',
                      'ja': 'ベトナム語語彙学習 6週目（反意語 11~99）'},
             'page': None,
             'link': {'tab': 'vocab',
                      'subAttr': 'vocab',
                      'subVal': 'antonym',
                      'vocabRange': {'start': 10, 'end': 99}}},
            {'text': {'ko': '베트남어 어휘 학습 6주차 (상용 1~123번)',
                      'zh': '越南語詞彙學習 第6週（常用 1~123）',
                      'en': 'Vietnamese Vocabulary Study – Week 6 (Frequent 1-123)',
                      'ja': 'ベトナム語語彙学習 6週目（常用 1~123）'},
             'page': None,
             'link': {'tab': 'vocab', 'subAttr': 'vocab', 'subVal': 'freq', 'vocabRange': {'start': 0, 'end': 123}}},
            {'text': {'ko': '베트남어 파수대 어휘 50개 학습 6주차',
                      'zh': '越南語守望台詞彙50個學習 第6週',
                      'en': 'Vietnamese Watchtower Vocabulary Study – Week 6 (50 Words)',
                      'ja': 'ベトナム語ものみの塔語彙50個学習 6週目'},
             'page': None,
             'link': {'tab': 'vocab', 'subAttr': 'vocab', 'subVal': 'wt', 'vocabRange': {'start': 250, 'end': 300}}},
            {'text': {'ko': '베트남어 제공 연설 6', 'zh': '越南語提供演講 6', 'en': 'Vietnamese Offer Talk 6', 'ja': 'ベトナム語提供の話 6'},
             'page': 61,
             'link': {'tab': 'wizard', 'subAttr': 'wizard', 'subVal': 'talks', 'talkNums': [6]}},
            {'text': {'ko': '베트남어 노래 (12번)',
                      'zh': '越南語詩歌（第12首）',
                      'en': 'Vietnamese Song (No. 12)',
                      'ja': 'ベトナム語の歌（12番）'},
             'page': 62,
             'link': {'tab': 'curriculum', 'subAttr': 'curriculum', 'subVal': 'prayer', 'anchor': 'song-12'}},
            {'text': {'ko': '베트남어 성경 찾기 시험',
                      'zh': '越南語聖經查找測驗',
                      'en': 'Vietnamese Bible Search Test',
                      'ja': 'ベトナム語聖書探しテスト'},
             'page': None,
             'link': {'tab': 'bible', 'subAttr': 'bible', 'subVal': 'books'}},
            {'text': {'ko': '행누책 읽기', 'zh': '閱讀《행누책》', 'en': 'Reading "행누책"', 'ja': '「행누책」を読む'},
             'page': None,
             'link': None}],
  'note': {'ko': '베트남어 노래(12번)와 성경 찾기 연습',
           'zh': '越南語詩歌(第12首)與查經練習',
           'en': 'Vietnamese Song (No. 12) and Bible Look-Up Practice',
           'ja': 'ベトナム語の歌(12番)と聖句探しの練習'}},
 {'week': 7,
  'items': [{'text': {'ko': '성조연습, 연속성조',
                      'zh': '聲調練習、連續聲調',
                      'en': 'Tone Practice, Tone Sequences',
                      'ja': '声調練習、連続声調'},
             'page': 64,
             'link': {'tab': 'pron', 'subAttr': 'pron', 'subVal': 'tonepairs'}},
            {'text': {'ko': '베트남어 어휘 학습 7주차 (상용 124~336번)',
                      'zh': '越南語詞彙學習 第7週（常用 124~336）',
                      'en': 'Vietnamese Vocabulary Study – Week 7 (Frequent 124-336)',
                      'ja': 'ベトナム語語彙学習 7週目（常用 124~336）'},
             'page': None,
             'link': {'tab': 'vocab',
                      'subAttr': 'vocab',
                      'subVal': 'freq',
                      'vocabRange': {'start': 123, 'end': 336}}},
            {'text': {'ko': '베트남어 파수대 어휘 50개 학습 7주차',
                      'zh': '越南語守望台詞彙50個學習 第7週',
                      'en': 'Vietnamese Watchtower Vocabulary Study – Week 7 (50 Words)',
                      'ja': 'ベトナム語ものみの塔語彙50個学習 7週目'},
             'page': None,
             'link': {'tab': 'vocab', 'subAttr': 'vocab', 'subVal': 'wt', 'vocabRange': {'start': 300, 'end': 350}}},
            {'text': {'ko': '베트남어 제공 연설 7', 'zh': '越南語提供演講 7', 'en': 'Vietnamese Offer Talk 7', 'ja': 'ベトナム語提供の話 7'},
             'page': 65,
             'link': {'tab': 'wizard', 'subAttr': 'wizard', 'subVal': 'talks', 'talkNums': [7]}},
            {'text': {'ko': '베트남어 읽기 연습', 'zh': '越南語閱讀練習', 'en': 'Vietnamese Reading Practice', 'ja': 'ベトナム語読解練習'},
             'page': None,
             'link': None},
            {'text': {'ko': '범용언어 생성법 소개',
                      'zh': '通用語言生成法介紹',
                      'en': 'Introduction to the Universal Language Generation Method',
                      'ja': '汎用言語生成法の紹介'},
             'page': 66,
             'link': {'tab': 'grammar', 'subAttr': 'grammar', 'subVal': 'sentences'}},
            {'text': {'ko': '베트남어 문법 예문', 'zh': '越南語文法例句', 'en': 'Vietnamese Grammar Examples', 'ja': 'ベトナム語文法例文'},
             'page': None,
             'link': {'tab': 'grammar', 'subAttr': 'grammar', 'subVal': 'lessons'}}],
  'note': {'ko': '범용언어 생성법으로 문장 만들기 시작',
           'zh': '開始用通用造句法練習造句',
           'en': 'Starting to Build Sentences with the Universal Sentence Method',
           'ja': '汎用言語生成法で文を作り始める'}},
 {'week': 8,
  'items': [{'text': {'ko': '성조연습, 연속성조',
                      'zh': '聲調練習、連續聲調',
                      'en': 'Tone Practice, Tone Sequences',
                      'ja': '声調練習、連続声調'},
             'page': 75,
             'link': {'tab': 'pron', 'subAttr': 'pron', 'subVal': 'tonepairs'}},
            {'text': {'ko': '베트남어 어휘 학습 8주차 (상용 337~549번)',
                      'zh': '越南語詞彙學習 第8週（常用 337~549）',
                      'en': 'Vietnamese Vocabulary Study – Week 8 (Frequent 337-549)',
                      'ja': 'ベトナム語語彙学習 8週目（常用 337~549）'},
             'page': None,
             'link': {'tab': 'vocab',
                      'subAttr': 'vocab',
                      'subVal': 'freq',
                      'vocabRange': {'start': 336, 'end': 549}}},
            {'text': {'ko': '베트남어 파수대 어휘 50개 학습 8주차',
                      'zh': '越南語守望台詞彙50個學習 第8週',
                      'en': 'Vietnamese Watchtower Vocabulary Study – Week 8 (50 Words)',
                      'ja': 'ベトナム語ものみの塔語彙50個学習 8週目'},
             'page': None,
             'link': {'tab': 'vocab', 'subAttr': 'vocab', 'subVal': 'wt', 'vocabRange': {'start': 350, 'end': 400}}},
            {'text': {'ko': '베트남어 제공 연설 8', 'zh': '越南語提供演講 8', 'en': 'Vietnamese Offer Talk 8', 'ja': 'ベトナム語提供の話 8'},
             'page': 76,
             'link': {'tab': 'wizard', 'subAttr': 'wizard', 'subVal': 'talks', 'talkNums': [8]}},
            {'text': {'ko': '범용언어 생성법을 통한 베트남어 문장 만들기',
                      'zh': '運用通用語言生成法造越南語句子',
                      'en': 'Building Vietnamese Sentences Using the Universal Language Generation Method',
                      'ja': '汎用言語生成法を使ってベトナム語の文を作る'},
             'page': None,
             'link': {'tab': 'grammar', 'subAttr': 'grammar', 'subVal': 'sentences'}},
            {'text': {'ko': '베트남어 읽기 연습', 'zh': '越南語閱讀練習', 'en': 'Vietnamese Reading Practice', 'ja': 'ベトナム語読解練習'},
             'page': None,
             'link': None},
            {'text': {'ko': '베트남어로 일기쓰고 발표',
                      'zh': '用越南語寫日記並發表',
                      'en': 'Write a Diary in Vietnamese and Present It',
                      'ja': 'ベトナム語で日記を書いて発表する'},
             'page': None,
             'link': None},
            {'text': {'ko': '문장 생성기로 문장 만들기 연습',
                      'zh': '用造句產生器練習造句',
                      'en': 'Practicing Sentence-Making with the Sentence Builder',
                      'ja': '文章生成器で文を作る練習'},
             'page': None,
             'link': {'tab': 'grammar', 'subAttr': 'grammar', 'subVal': 'builder'}}],
  'note': {'ko': '베트남어로 일기 쓰고 발표하기',
           'zh': '用越南語寫日記並發表',
           'en': 'Writing and Presenting a Diary in Vietnamese',
           'ja': 'ベトナム語で日記を書いて発表する'}},
 {'week': 9,
  'items': [{'text': {'ko': '성조연습, 연속성조',
                      'zh': '聲調練習、連續聲調',
                      'en': 'Tone Practice, Tone Sequences',
                      'ja': '声調練習、連続声調'},
             'page': None,
             'link': {'tab': 'pron', 'subAttr': 'pron', 'subVal': 'tonepairs'}},
            {'text': {'ko': '베트남어 어휘 학습 9주차 (상용 550~761번)',
                      'zh': '越南語詞彙學習 第9週（常用 550~761）',
                      'en': 'Vietnamese Vocabulary Study – Week 9 (Frequent 550-761)',
                      'ja': 'ベトナム語語彙学習 9週目（常用 550~761）'},
             'page': None,
             'link': {'tab': 'vocab',
                      'subAttr': 'vocab',
                      'subVal': 'freq',
                      'vocabRange': {'start': 549, 'end': 761}}},
            {'text': {'ko': '베트남어 파수대 어휘 50개 학습 9주차',
                      'zh': '越南語守望台詞彙50個學習 第9週',
                      'en': 'Vietnamese Watchtower Vocabulary Study – Week 9 (50 Words)',
                      'ja': 'ベトナム語ものみの塔語彙50個学習 9週目'},
             'page': None,
             'link': {'tab': 'vocab', 'subAttr': 'vocab', 'subVal': 'wt', 'vocabRange': {'start': 400, 'end': 450}}},
            {'text': {'ko': '베트남어 제공 연설 9', 'zh': '越南語提供演講 9', 'en': 'Vietnamese Offer Talk 9', 'ja': 'ベトナム語提供の話 9'},
             'page': 78,
             'link': {'tab': 'wizard', 'subAttr': 'wizard', 'subVal': 'talks', 'talkNums': [9]}},
            {'text': {'ko': '범용언어 생성법을 통한 베트남어 문장 만들기',
                      'zh': '運用通用語言生成法造越南語句子',
                      'en': 'Building Vietnamese Sentences Using the Universal Language Generation Method',
                      'ja': '汎用言語生成法を使ってベトナム語の文を作る'},
             'page': None,
             'link': {'tab': 'grammar', 'subAttr': 'grammar', 'subVal': 'sentences'}},
            {'text': {'ko': '베트남어 읽기 연습', 'zh': '越南語閱讀練習', 'en': 'Vietnamese Reading Practice', 'ja': 'ベトナム語読解練習'},
             'page': None,
             'link': None}],
  'note': {'ko': '제공 연설과 문장 만들기 연습 심화',
           'zh': '深化提供演講與造句練習',
           'en': 'Deepening Practice with Talks and Sentence-Building',
           'ja': '提供の話と文作りの練習を深める'}},
 {'week': 10,
  'items': [{'text': {'ko': '베트남어 제공 연설 10',
                      'zh': '越南語提供演講 10',
                      'en': 'Vietnamese Offer Talk 10',
                      'ja': 'ベトナム語提供の話 10'},
             'page': 81,
             'link': {'tab': 'wizard', 'subAttr': 'wizard', 'subVal': 'talks', 'talkNums': [10]}},
            {'text': {'ko': '베트남어 어휘 학습 10주차 (상용 762~974번)',
                      'zh': '越南語詞彙學習 第10週（常用 762~974）',
                      'en': 'Vietnamese Vocabulary Study – Week 10 (Frequent 762-974)',
                      'ja': 'ベトナム語語彙学習 10週目（常用 762~974）'},
             'page': None,
             'link': {'tab': 'vocab',
                      'subAttr': 'vocab',
                      'subVal': 'freq',
                      'vocabRange': {'start': 761, 'end': 974}}},
            {'text': {'ko': '베트남어 파수대 어휘 50개 학습 10주차',
                      'zh': '越南語守望台詞彙50個學習 第10週',
                      'en': 'Vietnamese Watchtower Vocabulary Study – Week 10 (50 Words)',
                      'ja': 'ベトナム語ものみの塔語彙50個学習 10週目'},
             'page': None,
             'link': {'tab': 'vocab', 'subAttr': 'vocab', 'subVal': 'wt', 'vocabRange': {'start': 450, 'end': 500}}},
            {'text': {'ko': '범용언어 생성법을 통한 베트남어 문장 만들기',
                      'zh': '運用通用語言生成法造越南語句子',
                      'en': 'Building Vietnamese Sentences Using the Universal Language Generation Method',
                      'ja': '汎用言語生成法を使ってベトナム語の文を作る'},
             'page': None,
             'link': {'tab': 'grammar', 'subAttr': 'grammar', 'subVal': 'sentences'}},
            {'text': {'ko': '베트남어 읽기 연습', 'zh': '越南語閱讀練習', 'en': 'Vietnamese Reading Practice', 'ja': 'ベトナム語読解練習'},
             'page': None,
             'link': None},
            {'text': {'ko': '베트남어 노래 (18번)',
                      'zh': '越南語詩歌（第18首）',
                      'en': 'Vietnamese Song (No. 18)',
                      'ja': 'ベトナム語の歌（18番）'},
             'page': 82,
             'link': {'tab': 'curriculum', 'subAttr': 'curriculum', 'subVal': 'prayer', 'anchor': 'song-18'}}],
  'note': {'ko': '베트남어 노래(18번) 배우기',
           'zh': '學習越南語詩歌(第18首)',
           'en': 'Learning Vietnamese Song No. 18',
           'ja': 'ベトナム語の歌(18番)を学ぶ'}},
 {'week': 11,
  'items': [{'text': {'ko': '베트남어 읽기 연습', 'zh': '越南語閱讀練習', 'en': 'Vietnamese Reading Practice', 'ja': 'ベトナム語読解練習'},
             'page': None,
             'link': None},
            {'text': {'ko': '베트남어 제공 연설 11 (집회 초대)',
                      'zh': '越南語提供演講 11（邀請聚會）',
                      'en': 'Vietnamese Offer Talk 11 (Meeting Invitation)',
                      'ja': 'ベトナム語提供の話 11（集会への招待）'},
             'page': 85,
             'link': {'tab': 'wizard', 'subAttr': 'wizard', 'subVal': 'talks', 'talkNums': [11]}},
            {'text': {'ko': '베트남어 어휘 학습 11주차 (상용 975~1186번)',
                      'zh': '越南語詞彙學習 第11週（常用 975~1186）',
                      'en': 'Vietnamese Vocabulary Study – Week 11 (Frequent 975-1186)',
                      'ja': 'ベトナム語語彙学習 11週目（常用 975~1186）'},
             'page': None,
             'link': {'tab': 'vocab',
                      'subAttr': 'vocab',
                      'subVal': 'freq',
                      'vocabRange': {'start': 974, 'end': 1186}}},
            {'text': {'ko': '베트남어 파수대 어휘 50개 학습 11주차',
                      'zh': '越南語守望台詞彙50個學習 第11週',
                      'en': 'Vietnamese Watchtower Vocabulary Study – Week 11 (50 Words)',
                      'ja': 'ベトナム語ものみの塔語彙50個学習 11週目'},
             'page': None,
             'link': {'tab': 'vocab', 'subAttr': 'vocab', 'subVal': 'wt', 'vocabRange': {'start': 500, 'end': 550}}},
            {'text': {'ko': '범용언어 생성법을 통한 베트남어 문장 만들기',
                      'zh': '運用通用語言生成法造越南語句子',
                      'en': 'Building Vietnamese Sentences Using the Universal Language Generation Method',
                      'ja': '汎用言語生成法を使ってベトナム語の文を作る'},
             'page': None,
             'link': {'tab': 'grammar', 'subAttr': 'grammar', 'subVal': 'sentences'}},
            {'text': {'ko': '베트남어 연구용 파수대 읽기 연습',
                      'zh': '越南語研究版《守望台》閱讀練習',
                      'en': 'Vietnamese Study Edition Watchtower Reading Practice',
                      'ja': 'ベトナム語研究用「ものみの塔」読解練習'},
             'page': None,
             'link': None},
            {'text': {'ko': '베트남어로 기도 준비하기',
                      'zh': '準備用越南語禱告',
                      'en': 'Preparing to Pray in Vietnamese',
                      'ja': 'ベトナム語で祈る準備をする'},
             'page': 86,
             'link': {'tab': 'curriculum', 'subAttr': 'curriculum', 'subVal': 'prayer', 'anchor': 'prayer-prep'}}],
  'note': {'ko': '베트남어로 기도 준비하기', 'zh': '準備用越南語禱告', 'en': 'Preparing to Pray in Vietnamese', 'ja': 'ベトナム語で祈りを準備する'}},
 {'week': 12,
  'items': [{'text': {'ko': '제공 연설 1,2,3,4 복습',
                      'zh': '提供演講 1、2、3、4 複習',
                      'en': 'Review of Offer Talks 1, 2, 3, 4',
                      'ja': '提供の話1、2、3、4の復習'},
             'page': None,
             'link': {'tab': 'wizard', 'subAttr': 'wizard', 'subVal': 'talks', 'talkNums': [1, 2, 3, 4]}},
            {'text': {'ko': '베트남어 어휘 학습 12주차 (상용 1187~1399번)',
                      'zh': '越南語詞彙學習 第12週（常用 1187~1399）',
                      'en': 'Vietnamese Vocabulary Study – Week 12 (Frequent 1187-1399)',
                      'ja': 'ベトナム語語彙学習 12週目（常用 1187~1399）'},
             'page': None,
             'link': {'tab': 'vocab',
                      'subAttr': 'vocab',
                      'subVal': 'freq',
                      'vocabRange': {'start': 1186, 'end': 1399}}},
            {'text': {'ko': '베트남어 파수대 어휘 50개 학습 12주차',
                      'zh': '越南語守望台詞彙50個學習 第12週',
                      'en': 'Vietnamese Watchtower Vocabulary Study – Week 12 (50 Words)',
                      'ja': 'ベトナム語ものみの塔語彙50個学習 12週目'},
             'page': None,
             'link': {'tab': 'vocab', 'subAttr': 'vocab', 'subVal': 'wt', 'vocabRange': {'start': 550, 'end': 600}}},
            {'text': {'ko': '베트남어 읽기 연습', 'zh': '越南語閱讀練習', 'en': 'Vietnamese Reading Practice', 'ja': 'ベトナム語読解練習'},
             'page': None,
             'link': None},
            {'text': {'ko': '범용언어 생성법을 통한 베트남어 문장 만들기',
                      'zh': '運用通用語言生成法造越南語句子',
                      'en': 'Building Vietnamese Sentences Using the Universal Language Generation Method',
                      'ja': '汎用言語生成法を使ってベトナム語の文を作る'},
             'page': None,
             'link': {'tab': 'grammar', 'subAttr': 'grammar', 'subVal': 'sentences'}},
            {'text': {'ko': '집회 사회 표현 연습 (형제)',
                      'zh': '聚會主持用語練習（弟兄）',
                      'en': "Meeting Chairman's Expressions Practice (Brothers)",
                      'ja': '集会司会の表現練習（兄弟）'},
             'page': 90,
             'link': None},
            {'text': {'ko': '파수대 발표 준비 (형제, 자매)',
                      'zh': '《守望台》發表準備（弟兄、姐妹）',
                      'en': 'Watchtower Study Comments Preparation (Brothers, Sisters)',
                      'ja': '「ものみの塔」発表の準備（兄弟、姉妹）'},
             'page': None,
             'link': None}],
  'note': {'ko': '집회 사회·파수대 발표 준비',
           'zh': '準備聚會主席與守望台發表',
           'en': 'Preparing to Chair the Meeting and Give a Watchtower Comment',
           'ja': '集会の司会と「ものみの塔」発表の準備'}},
 {'week': 13,
  'items': [{'text': {'ko': '제공 연설 5,6 복습',
                      'zh': '提供演講 5、6 複習',
                      'en': 'Review of Offer Talks 5, 6',
                      'ja': '提供の話5、6の復習'},
             'page': None,
             'link': {'tab': 'wizard', 'subAttr': 'wizard', 'subVal': 'talks', 'talkNums': [5, 6]}},
            {'text': {'ko': '베트남어 어휘 학습 13주차 (상용 1400~1503번)',
                      'zh': '越南語詞彙學習 第13週（常用 1400~1503）',
                      'en': 'Vietnamese Vocabulary Study – Week 13 (Frequent 1400-1503)',
                      'ja': 'ベトナム語語彙学習 13週目（常用 1400~1503）'},
             'page': None,
             'link': {'tab': 'vocab',
                      'subAttr': 'vocab',
                      'subVal': 'freq',
                      'vocabRange': {'start': 1399, 'end': 1503}}},
            {'text': {'ko': '베트남어 어휘 학습 13주차 (신권 1~109번)',
                      'zh': '越南語詞彙學習 第13週（屬靈詞彙 1~109）',
                      'en': 'Vietnamese Vocabulary Study – Week 13 (Theocratic 1-109)',
                      'ja': 'ベトナム語語彙学習 13週目（神権 1~109）'},
             'page': None,
             'link': {'tab': 'vocab', 'subAttr': 'vocab', 'subVal': 'theo', 'vocabRange': {'start': 0, 'end': 109}}},
            {'text': {'ko': '베트남어 파수대 어휘 50개 학습 13주차',
                      'zh': '越南語守望台詞彙50個學習 第13週',
                      'en': 'Vietnamese Watchtower Vocabulary Study – Week 13 (50 Words)',
                      'ja': 'ベトナム語ものみの塔語彙50個学習 13週目'},
             'page': None,
             'link': {'tab': 'vocab', 'subAttr': 'vocab', 'subVal': 'wt', 'vocabRange': {'start': 600, 'end': 650}}},
            {'text': {'ko': '베트남어 문법 특강',
                      'zh': '越南語文法特別課程',
                      'en': 'Special Lecture on Vietnamese Grammar',
                      'ja': 'ベトナム語文法特別講座'},
             'page': 93,
             'link': {'tab': 'grammar', 'subAttr': 'grammar', 'subVal': 'special'}},
            {'text': {'ko': '상황별 실연 준비',
                      'zh': '情境示範準備',
                      'en': 'Preparing Situational Demonstrations',
                      'ja': '状況別実演の準備'},
             'page': None,
             'link': None},
            {'text': {'ko': '베트남어 남북 단어 차이',
                      'zh': '越南語南北詞彙差異',
                      'en': 'Vietnamese North/South Vocabulary Differences',
                      'ja': 'ベトナム語の南北単語の違い'},
             'page': None,
             'link': {'tab': 'vocab', 'subAttr': 'vocab', 'subVal': 'dialect'}}],
  'note': {'ko': '베트남어 남북 단어 차이 배우기',
           'zh': '學習越南語南北用語差異',
           'en': 'Learning North–South Vietnamese Word Differences',
           'ja': 'ベトナム語の南北の単語の違いを学ぶ'}},
 {'week': 14,
  'items': [{'text': {'ko': '제공 연설 7,8 복습',
                      'zh': '提供演講 7、8 複習',
                      'en': 'Review of Offer Talks 7, 8',
                      'ja': '提供の話7、8の復習'},
             'page': None,
             'link': {'tab': 'wizard', 'subAttr': 'wizard', 'subVal': 'talks', 'talkNums': [7, 8]}},
            {'text': {'ko': '베트남어 어휘 학습 14주차 (신권 110~283번)',
                      'zh': '越南語詞彙學習 第14週（屬靈詞彙 110~283）',
                      'en': 'Vietnamese Vocabulary Study – Week 14 (Theocratic 110-283)',
                      'ja': 'ベトナム語語彙学習 14週目（神権 110~283）'},
             'page': None,
             'link': {'tab': 'vocab',
                      'subAttr': 'vocab',
                      'subVal': 'theo',
                      'vocabRange': {'start': 109, 'end': 283}}},
            {'text': {'ko': '베트남어 어휘 학습 14주차 (인명 1~38번)',
                      'zh': '越南語詞彙學習 第14週（人名 1~38）',
                      'en': 'Vietnamese Vocabulary Study – Week 14 (Names 1-38)',
                      'ja': 'ベトナム語語彙学習 14週目（人名 1~38）'},
             'page': None,
             'link': {'tab': 'vocab', 'subAttr': 'vocab', 'subVal': 'names', 'vocabRange': {'start': 0, 'end': 38}}},
            {'text': {'ko': '베트남어 파수대 어휘 50개 학습 14주차',
                      'zh': '越南語守望台詞彙50個學習 第14週',
                      'en': 'Vietnamese Watchtower Vocabulary Study – Week 14 (50 Words)',
                      'ja': 'ベトナム語ものみの塔語彙50個学習 14週目'},
             'page': None,
             'link': {'tab': 'vocab', 'subAttr': 'vocab', 'subVal': 'wt', 'vocabRange': {'start': 650, 'end': 700}}},
            {'text': {'ko': '베트남어 노래 (46번, 졸업식 노래) 준비',
                      'zh': '越南語詩歌（第46首，畢業典禮詩歌）準備',
                      'en': 'Vietnamese Song (No. 46, Graduation Song) Preparation',
                      'ja': 'ベトナム語の歌（46番、卒業式の歌）準備'},
             'page': None,
             'link': {'tab': 'curriculum', 'subAttr': 'curriculum', 'subVal': 'prayer', 'anchor': 'song-46'}},
            {'text': {'ko': '베트남어 집회 리허설',
                      'zh': '越南語聚會演練',
                      'en': 'Vietnamese Meeting Rehearsal',
                      'ja': 'ベトナム語集会リハーサル'},
             'page': None,
             'link': None},
            {'text': {'ko': '베트남어 어순반대 한자어',
                      'zh': '越南語語序相反的漢字詞',
                      'en': 'Sino-Vietnamese Words with Reversed Word Order',
                      'ja': 'ベトナム語の語順が逆の漢字語'},
             'page': None,
             'link': {'tab': 'vocab', 'subAttr': 'vocab', 'subVal': 'orderrev'}}],
  'note': {'ko': '졸업식 노래(46번)와 집회 리허설 준비',
           'zh': '準備畢業典禮詩歌(第46首)與聚會彩排',
           'en': 'Preparing the Graduation Song (No. 46) and Meeting Rehearsal',
           'ja': '卒業式の歌(46番)と集会リハーサルの準備'}},
 {'week': 15,
  'items': [{'text': {'ko': '제공 연설 9,10,11 복습',
                      'zh': '提供演講 9、10、11 複習',
                      'en': 'Review of Offer Talks 9, 10, 11',
                      'ja': '提供の話9、10、11の復習'},
             'page': None,
             'link': {'tab': 'wizard', 'subAttr': 'wizard', 'subVal': 'talks', 'talkNums': [9, 10, 11]}},
            {'text': {'ko': '베트남어 어휘 학습 15주차 (인명 39~184번)',
                      'zh': '越南語詞彙學習 第15週（人名 39~184）',
                      'en': 'Vietnamese Vocabulary Study – Week 15 (Names 39-184)',
                      'ja': 'ベトナム語語彙学習 15週目（人名 39~184）'},
             'page': None,
             'link': {'tab': 'vocab',
                      'subAttr': 'vocab',
                      'subVal': 'names',
                      'vocabRange': {'start': 38, 'end': 184}}},
            {'text': {'ko': '베트남어 어휘 학습 15주차 (끝말 1~67번)',
                      'zh': '越南語詞彙學習 第15週（字尾 1~67）',
                      'en': 'Vietnamese Vocabulary Study – Week 15 (Word Chain 1-67)',
                      'ja': 'ベトナム語語彙学習 15週目（しりとり 1~67）'},
             'page': None,
             'link': {'tab': 'vocab', 'subAttr': 'vocab', 'subVal': 'chain', 'vocabRange': {'start': 0, 'end': 67}}},
            {'text': {'ko': '베트남어 파수대 어휘 50개 학습 15주차',
                      'zh': '越南語守望台詞彙50個學習 第15週',
                      'en': 'Vietnamese Watchtower Vocabulary Study – Week 15 (50 Words)',
                      'ja': 'ベトナム語ものみの塔語彙50個学習 15週目'},
             'page': None,
             'link': {'tab': 'vocab', 'subAttr': 'vocab', 'subVal': 'wt', 'vocabRange': {'start': 700, 'end': 750}}},
            {'text': {'ko': '졸업식 준비 (임명)',
                      'zh': '畢業典禮準備（指派）',
                      'en': 'Graduation Ceremony Preparation (Assignments)',
                      'ja': '卒業式の準備（任命）'},
             'page': None,
             'link': None},
            {'text': {'ko': '베트남어 끝말잇기', 'zh': '越南語文字接龍', 'en': 'Vietnamese Word Chain Game', 'ja': 'ベトナム語しりとり'},
             'page': None,
             'link': {'tab': 'vocab', 'subAttr': 'vocab', 'subVal': 'chain'}}],
  'note': {'ko': '졸업식 준비 및 임명',
           'zh': '畢業典禮準備與委派',
           'en': 'Preparing for Graduation and Assignments',
           'ja': '卒業式の準備と割り当て'}},
 {'week': 16,
  'items': [{'text': {'ko': '파수대 집회 실연 (사회, 낭독, 발표)',
                      'zh': '《守望台》聚會實演（主持、朗讀、發表）',
                      'en': 'Watchtower Meeting Demonstration (Chairman, Reading, Comments)',
                      'ja': '「ものみの塔」集会の実演（司会、朗読、発表）'},
             'page': None,
             'link': None},
            {'text': {'ko': '베트남어 어휘 학습 16주차 (끝말 68~232번)',
                      'zh': '越南語詞彙學習 第16週（字尾 68~232）',
                      'en': 'Vietnamese Vocabulary Study – Week 16 (Word Chain 68-232)',
                      'ja': 'ベトナム語語彙学習 16週目（しりとり 68~232）'},
             'page': None,
             'link': {'tab': 'vocab',
                      'subAttr': 'vocab',
                      'subVal': 'chain',
                      'vocabRange': {'start': 67, 'end': 232}}},
            {'text': {'ko': '베트남어 어휘 학습 16주차 (남북 단어 1~48번)',
                      'zh': '越南語詞彙學習 第16週（南北用詞 1~48）',
                      'en': 'Vietnamese Vocabulary Study – Week 16 (North/South Words 1-48)',
                      'ja': 'ベトナム語語彙学習 16週目（南北の単語 1~48）'},
             'page': None,
             'link': {'tab': 'vocab',
                      'subAttr': 'vocab',
                      'subVal': 'dialect',
                      'vocabRange': {'start': 0, 'end': 48}}},
            {'text': {'ko': '베트남어 파수대 어휘 50개 학습 16주차',
                      'zh': '越南語守望台詞彙50個學習 第16週',
                      'en': 'Vietnamese Watchtower Vocabulary Study – Week 16 (50 Words)',
                      'ja': 'ベトナム語ものみの塔語彙50個学習 16週目'},
             'page': None,
             'link': {'tab': 'vocab', 'subAttr': 'vocab', 'subVal': 'wt', 'vocabRange': {'start': 750, 'end': 800}}},
            {'text': {'ko': '졸업', 'zh': '畢業', 'en': 'Graduation', 'ja': '卒業'}, 'page': None, 'link': None}],
  'note': {'ko': '파수대 집회 실연과 졸업',
           'zh': '守望台聚會實演與畢業',
           'en': 'Watchtower Meeting Demonstration and Graduation',
           'ja': '「ものみの塔」集会の実演と卒業'}}]
