# North/South everyday-vocabulary pairs -- same meaning, different word choice
# (distinct from NORTH_SOUTH_DIFFS in pronunciation_data.py, which is about the SAME
# word being pronounced differently). Source: user-provided list based on
# https://terms.naver.com/언어/베트남어의-방언-2AqIsqIGy48VQswyhz8ywP
# NOTE: the user's original list included "rẽ / quẹo / 돌아가다" twice; the duplicate
# was dropped here. "숫가락" was corrected to the standard spelling "숟가락".
#
# "mean" is stored as a {"ko","zh","en","ja","de"} dict so js_json() (see build_app.py) serializes
# it straight into a JS object app_logic.js's T() helper can read directly.

DIALECT_WORDS = [{'north': 'bố', 'south': 'ba/cha', 'mean': {'ko': '아버지', 'zh': '父親', 'en': 'father', 'ja': '父', 'de': 'Vater'}},
 {'north': 'mẹ', 'south': 'má', 'mean': {'ko': '어머니', 'zh': '母親', 'en': 'mother', 'ja': '母', 'de': 'Mutter'}},
 {'north': 'vâng', 'south': 'dạ', 'mean': {'ko': '예', 'zh': '是', 'en': 'yes', 'ja': 'はい', 'de': 'ja'}},
 {'north': 'xấu hổ, ngượng',
  'south': 'mắc cỡ',
  'mean': {'ko': '부끄럽다, 창피하다', 'zh': '害羞，丟臉', 'en': 'ashamed; embarrassed', 'ja': '恥ずかしい、きまり悪い', 'de': 'beschämt, verlegen'}},
 {'north': 'dối', 'south': 'xạo', 'mean': {'ko': '거짓말 하다', 'zh': '說謊', 'en': 'to lie', 'ja': '嘘をつく', 'de': 'lügen'}},
 {'north': 'đùa',
  'south': 'giỡn, nói chơi',
  'mean': {'ko': '농담, 장난하다', 'zh': '玩笑，惡作劇', 'en': 'joke, prank', 'ja': '冗談、いたずらする', 'de': 'Scherz, scherzen'}},
 {'north': 'rỗi', 'south': 'rảnh', 'mean': {'ko': '한가하다', 'zh': '空閒的', 'en': 'to be free/idle', 'ja': '暇だ', 'de': 'Zeit haben, frei haben'}},
 {'north': 'bận', 'south': 'kẹt', 'mean': {'ko': '바쁘다', 'zh': '忙碌', 'en': 'busy', 'ja': '忙しい', 'de': 'beschäftigt'}},
 {'north': 'muộn', 'south': 'trễ', 'mean': {'ko': '늦다', 'zh': '遲到', 'en': 'be late', 'ja': '遅れる', 'de': 'zu spät, verspätet'}},
 {'north': 'tay phải', 'south': 'tay mặt', 'mean': {'ko': '오른손', 'zh': '右手', 'en': 'right hand', 'ja': '右手', 'de': 'rechte Hand'}},
 {'north': 'rẽ', 'south': 'quẹo', 'mean': {'ko': '돌아가다', 'zh': '回去', 'en': 'go back', 'ja': '帰る', 'de': 'abbiegen / umkehren'}},
 {'north': 'vào', 'south': 'vô', 'mean': {'ko': '들어가다', 'zh': '進去', 'en': 'enter', 'ja': '入る', 'de': 'hineingehen, eintreten'}},
 {'north': 'mắng', 'south': 'chửi', 'mean': {'ko': '야단치다', 'zh': '責罵', 'en': 'to scold', 'ja': '叱る', 'de': 'schimpfen, tadeln'}},
 {'north': 'thích', 'south': 'khoái', 'mean': {'ko': '좋아하다', 'zh': '喜歡', 'en': 'to like', 'ja': '好む', 'de': 'mögen, gernhaben'}},
 {'north': 'hỏng',
  'south': 'hư',
  'mean': {'ko': '고장나다', 'zh': '故障、壞掉', 'en': 'to break down, malfunction', 'ja': '故障する', 'de': 'kaputtgehen, beschädigt sein'}},
 {'north': 'mặc cả',
  'south': 'trả giá',
  'mean': {'ko': '값을 깎다, 흥정하다', 'zh': '殺價，討價還價', 'en': 'to bargain, to haggle', 'ja': '値切る、交渉する', 'de': 'feilschen, verhandeln'}},
 {'north': 'đắt', 'south': 'mắc', 'mean': {'ko': '비싸다', 'zh': '貴，昂貴', 'en': 'to be expensive', 'ja': '値段が高い', 'de': 'teuer'}},
 {'north': 'mặc', 'south': 'bận', 'mean': {'ko': '옷을 입다', 'zh': '穿衣服', 'en': 'to put on clothes', 'ja': '服を着る', 'de': 'Kleidung anziehen'}},
 {'north': 'gọi',
  'south': 'kêu',
  'mean': {'ko': '음식을 주문하다, 시키다', 'zh': '訂購,吩咐', 'en': 'to order, to have someone do', 'ja': '注文する、命じる', 'de': 'bestellen, rufen'}},
 {'north': 'tắc đường',
  'south': 'kẹt xe',
  'mean': {'ko': '차가 막히다', 'zh': '塞車', 'en': 'to be stuck in traffic', 'ja': '渋滞する', 'de': 'im Stau stehen, Verkehrsstau'}},
 {'north': 'thuê',
  'south': 'mướn',
  'mean': {'ko': '빌리다, 고용하다', 'zh': '借用，僱用', 'en': 'to borrow; to hire', 'ja': '借りる、雇う', 'de': 'mieten, leihen, anstellen'}},
 {'north': 'biển',
  'south': 'bảng',
  'mean': {'ko': '차번호판', 'zh': '車牌（車號）', 'en': 'license plate (car number)', 'ja': 'ナンバープレート（車番号）', 'de': 'Nummernschild (Kennzeichen)'}},
 {'north': 'ví', 'south': 'bóp', 'mean': {'ko': '지갑', 'zh': '錢包', 'en': 'wallet', 'ja': '財布', 'de': 'Geldbörse, Portemonnaie'}},
 {'north': 'bát', 'south': 'chén', 'mean': {'ko': '그릇', 'zh': '碗、容器', 'en': 'bowl, vessel', 'ja': '器', 'de': 'Schale, Schüssel'}},
 {'north': 'đĩa', 'south': 'dĩa', 'mean': {'ko': '접시', 'zh': '盤子', 'en': 'plate', 'ja': '皿', 'de': 'Teller'}},
 {'north': 'cốc', 'south': 'ly', 'mean': {'ko': '컵', 'zh': '杯子', 'en': 'cup', 'ja': 'コップ', 'de': 'Becher, Glas'}},
 {'north': 'thìa',
  'south': 'muỗng',
  'mean': {'ko': '숟가락 (사실은 한국 숟가락보다는 작은 국자에 더 가까움)', 'zh': '湯匙', 'en': 'spoon', 'ja': 'スプーン', 'de': 'Löffel'}},
 {'north': 'phong bì', 'south': 'bao thơ', 'mean': {'ko': '편지봉투', 'zh': '信封', 'en': 'envelope', 'ja': '封筒', 'de': 'Briefumschlag'}},
 {'north': 'ô tô', 'south': 'xe hơi', 'mean': {'ko': '자동차', 'zh': '汽車', 'en': 'car', 'ja': '自動車', 'de': 'Auto, Pkw'}},
 {'north': 'lọ', 'south': 'chai', 'mean': {'ko': '병', 'zh': '瓶子', 'en': 'bottle', 'ja': '瓶', 'de': 'Flasche'}},
 {'north': 'lợn', 'south': 'heo', 'mean': {'ko': '돼지', 'zh': '豬', 'en': 'pig', 'ja': '豚', 'de': 'Schwein'}},
 {'north': 'hoa quả', 'south': 'trái cây', 'mean': {'ko': '열매, 과일', 'zh': '果實，水果', 'en': 'fruit', 'ja': '果実', 'de': 'Obst, Früchte'}},
 {'north': 'chụp ảnh',
  'south': 'chụp hình',
  'mean': {'ko': '사진을 찍다', 'zh': '拍照', 'en': 'to take a photo', 'ja': '写真を撮る', 'de': 'fotografieren, ein Foto machen'}},
 {'north': 'cắt tóc', 'south': 'hớt tóc', 'mean': {'ko': '머리카락을 자르다', 'zh': '剪頭髮', 'en': 'cut hair', 'ja': '髪を切る', 'de': 'Haare schneiden'}},
 {'north': 'đá bóng',
  'south': 'đá banh',
  'mean': {'ko': '축구하다', 'zh': '踢足球', 'en': 'to play soccer', 'ja': 'サッカーをする', 'de': 'Fußball spielen'}},
 {'north': 'uống rượu',
  'south': 'nhậu rượu',
  'mean': {'ko': '술을 마시다', 'zh': '喝酒', 'en': 'to drink alcohol', 'ja': '酒を飲む', 'de': 'Alkohol trinken'}},
 {'north': 'cân',
  'south': 'kí',
  'mean': {'ko': '근(1cân=1kg)', 'zh': '斤(1cân=1公斤)', 'en': 'geun/catty (1 cân = 1 kg)', 'ja': '斤(1cân=1kg)', 'de': 'Kilo (1 cân = 1 kg)'}},
 {'north': 'tầng', 'south': 'lầu', 'mean': {'ko': '층(floor)', 'zh': '樓層', 'en': 'floor', 'ja': '階', 'de': 'Stockwerk, Etage'}},
 {'north': 'hiệu', 'south': 'tiệm', 'mean': {'ko': '가게', 'zh': '商店', 'en': 'shop', 'ja': '店', 'de': 'Laden, Geschäft'}},
 {'north': 'nhanh', 'south': 'lẹ', 'mean': {'ko': '빠르다', 'zh': '快，迅速', 'en': 'to be fast', 'ja': '速い', 'de': 'schnell'}},
 {'north': 'đắt quá',
  'south': 'mắc quá',
  'mean': {'ko': '너무 비싸다', 'zh': '太貴了', 'en': 'to be too expensive', 'ja': '値段が高すぎる', 'de': 'zu teuer'}},
 {'north': 'anh cả', 'south': 'anh hai', 'mean': {'ko': '장남, 맏아들', 'zh': '長子', 'en': 'eldest son', 'ja': '長男', 'de': 'ältester Sohn / ältester Bruder'}},
 {'north': 'cái ô', 'south': 'cây dù', 'mean': {'ko': '우산', 'zh': '雨傘', 'en': 'umbrella', 'ja': '傘', 'de': 'Regenschirm'}},
 {'north': 'bị ốm',
  'south': 'bị bệnh',
  'mean': {'ko': '병들다, 아프다', 'zh': '生病，患病', 'en': 'to become ill; to be sick', 'ja': '病気になる、具合が悪い', 'de': 'krank werden, krank sein'}},
 {'north': 'gì', 'south': 'chi', 'mean': {'ko': '무엇', 'zh': '什麼', 'en': 'what', 'ja': '何', 'de': 'was'}},
 {'north': 'một ít', 'south': 'chút xíu', 'mean': {'ko': '조금', 'zh': '一點', 'en': 'a little', 'ja': '少し', 'de': 'ein wenig, ein bisschen'}},
 {'north': 'trứng gà', 'south': 'hột gà', 'mean': {'ko': '계란', 'zh': '雞蛋', 'en': 'egg', 'ja': '卵', 'de': 'Hühnerei, Ei'}}]
