# "교과 > 문법 특강" subtab -- the A-Z 문법 사전 (alphabetical grammar-particle
# dictionary), transcribed verbatim from pages 104-125 of the course booklet.
#
# "pos" (part-of-speech tag), "meaning" (usage explanation), and each example's "kr"
# (Korean translation) are stored as {"ko","zh","en","ja"} dicts so js_json() (see
# build_app.py) serializes them straight into JS objects app_logic.js's T() helper can
# read directly. A handful of examples have no Korean translation printed in the
# original booklet -- those keep "kr" as a plain empty string (T() passes a plain
# string straight through either way).

GRAMMAR_DICT = [{'headword': 'à',
  'pos': {'ko': '조사', 'zh': '助詞', 'en': 'particle', 'ja': '助詞'},
  'meaning': {'ko': '문장 끝에 위치 - 무슨 일에 관하여 덧붙여 질문하기 위하여 사용함.',
              'zh': '位於句末——用於就某事進一步追加提問。',
              'en': 'Placed at the end of a sentence — used to ask an additional question about something.',
              'ja': '文末に位置－何かについて追加で質問するために使用する。'},
  'examples': [{'vi': 'Anh là sinh viên à?',
                'kr': {'ko': '당신은 학생입니까?', 'zh': '您是學生嗎？', 'en': 'Are you a student?', 'ja': 'あなたは学生ですか？'}},
               {'vi': 'Chị không đi làm à?',
                'kr': {'ko': '당신은 일하러 가지 않습니까?',
                       'zh': '您不去上班嗎？',
                       'en': "Aren't you going to work?",
                       'ja': 'あなたは仕事に行かないのですか？'}}]},
 {'headword': 'ạ',
  'pos': {'ko': '조사', 'zh': '助詞', 'en': 'particle', 'ja': '助詞'},
  'meaning': {'ko': '경의를 표현하기 위해 문말 뒤에 사용함.',
              'zh': '為了表示敬意而用在句末。',
              'en': 'Used at the end of a sentence to express respect.',
              'ja': '敬意を表すために文末に使用します。'},
  'examples': [{'vi': 'Chào anh ạ.', 'kr': {'ko': '안녕하세요.', 'zh': '你好。', 'en': 'Hello.', 'ja': 'こんにちは。'}},
               {'vi': 'Xin lỗi, mấy giờ rồi ạ?',
                'kr': {'ko': '실례하지만, 몇 시죠?',
                       'zh': '不好意思，請問現在幾點？',
                       'en': 'Excuse me, what time is it?',
                       'ja': 'すみません、今何時ですか。'}}]},
 {'headword': 'bị',
  'pos': None,
  'meaning': {'ko': '베트남어에서 bị 는 부정적이며 운이 없는 상태를 나타내기 위해 사용됨.',
              'zh': '在越南語中，bị用於表示消極、倒霉的狀態。',
              'en': 'In Vietnamese, bị is used to express a negative, unlucky state.',
              'ja': 'ベトナム語でbịは否定的で運が悪い状態を表すために使われる。'},
  'examples': [{'vi': 'Cô ấy bị cảm.',
                'kr': {'ko': '그녀는 감기에 걸렸다.',
                       'zh': '她感冒了。',
                       'en': 'She caught a cold.',
                       'ja': '彼女は風邪をひいた。'}}]},
 {'headword': 'bức',
  'pos': None,
  'meaning': {'ko': '주로 벽에 걸려있는 사물 앞에 사용함.',
              'zh': '主要用於掛在牆上的物品前。',
              'en': 'Mainly used before objects that are hung on a wall.',
              'ja': '主に壁に掛かっている物の前で使う。'},
  'examples': [{'vi': 'bức tranh', 'kr': {'ko': '그림', 'zh': '圖畫', 'en': 'picture, drawing', 'ja': '絵'}},
               {'vi': 'bức màn', 'kr': {'ko': '커튼', 'zh': '窗簾', 'en': 'curtain', 'ja': 'カーテン'}}]},
 {'headword': 'các',
  'pos': None,
  'meaning': {'ko': '… 들 (명사 앞에 위치하여 복수를 만듦. 불특정한 대상을 가리킴.)',
              'zh': '… 들（們）（位於名詞前面構成複數。指不特定的對象。）',
              'en': '… 들 (plural marker; placed before a noun to make it plural. Refers to an unspecified '
                    'group.)',
              'ja': '… 들（〜たち）（名詞の前に位置して複数を作る。不特定の対象を指す。）'},
  'examples': [{'vi': 'Các bạn đều rất tốt.',
                'kr': {'ko': '친구들은 모두 매우 좋아한다.',
                       'zh': '朋友們都很喜歡。',
                       'en': 'All the friends like it very much.',
                       'ja': '友達はみんなとても好きだ。'}},
               {'vi': 'Các dân tộc đều có quyền bình đẳng.',
                'kr': {'ko': '모든 민족은 모두 평등의 권리를 갖고 있다.',
                       'zh': '所有民族都擁有平等的權利。',
                       'en': 'All peoples have equal rights.',
                       'ja': 'すべての民族はみな平等の権利を持っている。'}}]},
 {'headword': 'cái',
  'pos': None,
  'meaning': {'ko': '스스로 움직일 수 없는 물체의 종류와 성질.',
              'zh': '無法自行移動的物體的種類與性質。',
              'en': 'The type and nature of objects that cannot move on their own.',
              'ja': '自分で動くことができない物の種類と性質。'},
  'examples': [{'vi': 'Mẹ tôi mua cho tôi hai cái áo mới.', 'kr': ''}]},
 {'headword': 'chiếc',
  'pos': None,
  'meaning': {'ko': '주로 차량, 선박, 비행기, 교량 등의 명사 앞에 쓰임.',
              'zh': '主要用於車輛、船隻、飛機、橋樑等名詞前。',
              'en': 'Mainly used before nouns such as vehicle, ship, airplane, bridge, etc.',
              'ja': '主に車両、船舶、飛行機、橋などの名詞の前で使われる。'},
  'examples': [{'vi': 'Chiếc xe hơi này giá bao nhiêu?',
                'kr': {'ko': '이 자동차는 가격이 얼마입니까?',
                       'zh': '這輛車的價格是多少?',
                       'en': 'How much does this car cost?',
                       'ja': 'この自動車は値段がいくらですか?'}}]},
 {'headword': 'chiếm…%',
  'pos': None,
  'meaning': {'ko': '~%를 점유하다. (비율에 대해 말할 때 사용하는 표현.)',
              'zh': '佔~%。（談論比例時使用的表達方式。）',
              'en': 'to occupy/take up ~%. (An expression used when talking about a proportion.)',
              'ja': '~%を占める。（比率について話すときに使う表現。）'},
  'examples': [{'vi': 'Trong cơ cấu dân số Việt Nam, số lượng nữ chiếm gần 51%.',
                'kr': {'ko': '베트남 인구 구성 중에, 여성의 숫자는 약 51%를 차지한다.',
                       'zh': '在越南的人口構成中，女性人數約佔51%。',
                       'en': "In Vietnam's population composition, women make up about 51%.",
                       'ja': 'ベトナムの人口構成のうち、女性の数は約51%を占める。'}}]},
 {'headword': 'có thể',
  'pos': None,
  'meaning': {'ko': 'có thể는 조동사로 "~할 수 있다"',
              'zh': 'có thể 是助動詞，意為"能~"',
              'en': 'có thể is an auxiliary verb meaning "can ~"',
              'ja': 'có thể は助動詞で「~できる」という意味です'},
  'examples': [{'vi': 'Tôi có thể nấu món ăn Việt Nam.',
                'kr': {'ko': '나는 베트남 요리를 할 수 있다.',
                       'zh': '我會做越南菜。',
                       'en': 'I can cook Vietnamese food.',
                       'ja': '私はベトナム料理を作れる。'}},
               {'vi': 'Anh có thể học Kinh Thánh được không?.',
                'kr': {'ko': '당신은 성서연구를 할 수 있습니까?',
                       'zh': '您能進行聖經研究嗎？',
                       'en': 'Can you have a Bible study?',
                       'ja': 'あなたは聖書研究をすることができますか？'}}]},
 {'headword': 'con',
  'pos': None,
  'meaning': {'ko': '동물 이름 앞에 붙이는 종별사 * 동물 이외에 con đao칼, con đường길',
              'zh': '加在動物名稱前面的類別詞 *除動物外還有con đao(刀)、con đường(路)',
              'en': 'A classifier placed before animal names *besides animals, also used for con đao '
                    '(knife), con đường (road)',
              'ja': '動物の名前の前に付ける類別詞 *動物以外にもcon đao（ナイフ）、con đường（道）'},
  'examples': [{'vi': 'Con chó này dễ thương quá.',
                'kr': {'ko': '이 개는 매우 귀엽다.',
                       'zh': '這隻狗很可愛。',
                       'en': 'This dog is very cute.',
                       'ja': 'この犬はとてもかわいい。'}}]},
 {'headword': 'còn',
  'pos': {'ko': '접', 'zh': '連詞', 'en': 'conj.', 'ja': '接続詞'},
  'meaning': {'ko': '그런데 / 부) 여전히, 아직',
              'zh': '不過 / (副)仍然,還',
              'en': 'however, by the way / (adv.) still, yet',
              'ja': 'ところで / (副)依然として、まだ'},
  'examples': [{'vi': 'Tôi là người Việt, còn anh?',
                'kr': {'ko': '나는 베트남 사람입니다, 그런데 당신은?',
                       'zh': '我是越南人,那您呢?',
                       'en': 'I am Vietnamese, and you?',
                       'ja': '私はベトナム人です、それであなたは?'}},
               {'vi': 'Anh Minh là người Hàn Quốc, còn anh Phát là người Việt.',
                'kr': {'ko': 'Minh씨는 한국 사람입니다, 그런데 Phát은 베트남 사람입니다.',
                       'zh': 'Minh先生是韓國人，而Phát是越南人。',
                       'en': 'Mr. Minh is Korean, but Phát is Vietnamese.',
                       'ja': 'ミンさんは韓国人です、しかしファットはベトナム人です。'}},
               {'vi': 'Anh ấy còn độc thân.',
                'kr': {'ko': '그는 여전히 독신이다.',
                       'zh': '他依然單身。',
                       'en': 'He is still single.',
                       'ja': '彼は依然として独身だ。'}},
               {'vi': 'Nó còn ngủ, chưa thức dậy.',
                'kr': {'ko': '그는 여전히 자고 있다, 아직 일어나지 않았다.',
                       'zh': '他還在睡覺,還沒有起床。',
                       'en': "He is still sleeping, he hasn't gotten up yet.",
                       'ja': '彼はまだ寝ている、まだ起きていない。'}}]},
 {'headword': 'cũng',
  'pos': None,
  'meaning': {'ko': '역시(동사나 형용사 앞에 위치하여 동일함을 나타내는 표현.)',
              'zh': '也（放在動詞或形容詞前面，表示相同的用法。）',
              'en': 'also (an expression placed before a verb or adjective indicating sameness.)',
              'ja': 'も（動詞や形容詞の前に置かれ、同じであることを表す表現。）'},
  'examples': [{'vi': 'Anh là sinh viên. Tôi cũng là sinh viên.',
                'kr': {'ko': '당신은 학생입니다. 나도 역시 학생입니다.',
                       'zh': '您是學生。我也是學生。',
                       'en': 'You are a student. I am also a student.',
                       'ja': 'あなたは学生です。私も同じく学生です。'}},
               {'vi': 'Chị là giáo viên. Anh cũng là giáo viên.',
                'kr': {'ko': '당신은 선생님입니다. 당신도 역시 선생님입니다.',
                       'zh': '您是老師。您也是老師。',
                       'en': 'You are a teacher. You are also a teacher.',
                       'ja': 'あなたは先生です。あなたも同じく先生です。'}}]},
 {'headword': 'dạ',
  'pos': None,
  'meaning': {'ko': '문장 앞에 위치하여 공손, 예의를 표시하기 위해 사용됨.',
              'zh': '位於句子前面，用於表示恭敬、禮貌。',
              'en': 'Placed at the beginning of a sentence, used to express politeness and courtesy.',
              'ja': '文の前に位置して、丁寧さ、礼儀を表すために使用される。'},
  'examples': [{'vi': 'Dạ, cám ơn.',
                'kr': {'ko': '예, 고맙습니다.', 'zh': '是的，謝謝。', 'en': 'Yes, thank you.', 'ja': 'はい、ありがとうございます。'}}]},
 {'headword': 'dễ',
  'pos': None,
  'meaning': {'ko': '~하기 쉽다.(행동의 편안함 정도를 나타내는 표현.)',
              'zh': '容易~。（表示動作輕鬆程度的表達方式。）',
              'en': 'easy to ~. (An expression indicating how easy/comfortable the action is.)',
              'ja': '~しやすい。（行動の楽さの程度を表す表現。）'},
  'examples': [{'vi': 'Đường này dễ đi lắm.',
                'kr': {'ko': '이 길은 매우 쉽게 간다.',
                       'zh': '這條路走起來很輕鬆。',
                       'en': 'This road is very easy to travel.',
                       'ja': 'この道はとても簡単に行ける。'}}]},
 {'headword': 'đấy',
  'pos': {'ko': '부', 'zh': '副詞', 'en': 'adv.', 'ja': '副詞'},
  'meaning': {'ko': '저기 / 의문사 뒤에 붙여 강조를 나타내는 말.',
              'zh': '“那裡”/加在疑問詞後面表示強調的詞。',
              'en': '"over there" / a word attached after an interrogative word to show emphasis.',
              'ja': '「あそこ」/疑問詞の後に付けて強調を表す言葉。'},
  'examples': [{'vi': 'Lan đi đâu đấy?',
                'kr': {'ko': 'Lan씨는 어디 가세요?',
                       'zh': 'Lan女士要去哪裡？',
                       'en': 'Where is Ms. Lan going?',
                       'ja': 'ランさんはどこへ行かれますか？'}},
               {'vi': 'Anh làm gì đấy?',
                'kr': {'ko': '당신은 무슨 일 하세요?',
                       'zh': '您是做什麼工作的？',
                       'en': 'What do you do (for work)?',
                       'ja': 'あなたは何のお仕事をされていますか？'}},
               {'vi': 'Ai đấy?',
                'kr': {'ko': '누구세요?', 'zh': '您是誰？', 'en': 'Who are you?', 'ja': 'どなたですか？'}}]},
 {'headword': 'định',
  'pos': None,
  'meaning': {'ko': '이 단어는 보통 동사와 함께 사용되어 장래의 행동을 나타냄.',
              'zh': '此詞通常與動詞一起使用,表示將來的動作。',
              'en': 'This word is usually used with a verb to indicate a future action.',
              'ja': 'この単語は普通動詞と共に使われ、将来の行動を表す。'},
  'examples': [{'vi': 'Tôi đang định đi Seoul.',
                'kr': {'ko': '나는 서울에 갈 작정이다.',
                       'zh': '我打算去首爾。',
                       'en': 'I intend to go to Seoul.',
                       'ja': '私はソウルに行くつもりだ。'}},
               {'vi': 'Anh ấy định mua xe ô tô.',
                'kr': {'ko': '그는 자동차를 살 예정이다.',
                       'zh': '他打算買車。',
                       'en': 'He plans to buy a car.',
                       'ja': '彼は車を買う予定だ。'}}]},
 {'headword': 'để',
  'pos': None,
  'meaning': {'ko': '~하기위해/ 누구로 부터 저지 받지 않기 위해 :~하기 위해서 내버려 둬라. ~하기 원한다.',
              'zh': '為了~／為了不被某人阻止：為了~而隨其自然。想要~。',
              'en': 'in order to ~ / so as not to be stopped by someone: let it be, in order to ~. Wants to '
                    '~.',
              'ja': '~するために／誰かに邪魔されないように：~するために放っておいてくれ。~することを望む。'},
  'examples': [{'vi': 'Nó mệt, để nó ngủ.',
                'kr': {'ko': '그는 피곤하다. 그가 자도록 내버려 둬라.',
                       'zh': '他很累。讓他睡吧。',
                       'en': 'He is tired. Let him sleep.',
                       'ja': '彼は疲れている。彼を寝かせておきなさい。'}},
               {'vi': 'Anh ấy đến bệnh viện để kiểm tra mắt.',
                'kr': {'ko': '그는 눈 검사를 하기 위해 병원에 왔다.',
                       'zh': '他為了做眼睛檢查來到了醫院。',
                       'en': 'He came to the hospital to have an eye exam.',
                       'ja': '彼は目の検査をするために病院に来た。'}},
               {'vi': 'Nó hát để mẹ vui.',
                'kr': {'ko': '그는 어머니를 기쁘게 하기 위해 노래를 불렀다.',
                       'zh': '他為了讓母親高興而唱了歌。',
                       'en': 'He sang a song to make his mother happy.',
                       'ja': '彼は母を喜ばせるために歌を歌った。'}}]},
 {'headword': 'đó',
  'pos': {'ko': '형', 'zh': '形容詞', 'en': 'adj.', 'ja': '形容詞'},
  'meaning': {'ko': '그 / 대)그것, 그 사람 / 부) 문장 뒤에 붙여 강조를 나타내는 말.',
              'zh': '그／代)那個、那個人／副）用在句末表示強調的詞。',
              'en': '그 / (pronoun) that thing, that person / (adverb) a word attached at the end of a '
                    'sentence to show emphasis.',
              'ja': '그／代）それ、その人／副）文末に付けて強調を表す言葉。'},
  'examples': [{'vi': 'Sau đó', 'kr': {'ko': '그 후에', 'zh': '之後', 'en': 'after that', 'ja': 'その後に'}},
               {'vi': 'Trước đó', 'kr': {'ko': '그전에', 'zh': '在那之前', 'en': 'before that', 'ja': 'それ以前に'}},
               {'vi': 'Đó là',
                'kr': {'ko': '그것은 … 이다.', 'zh': '那是……。', 'en': 'That is ….', 'ja': 'それは…である。'}},
               {'vi': 'Anh đi đâu đó?',
                'kr': {'ko': '당신은 어디 가세요?',
                       'zh': '您去哪裡？',
                       'en': 'Where are you going?',
                       'ja': 'あなたはどこへ行かれますか？'}}]},
 {'headword': 'được',
  'pos': None,
  'meaning': {'ko': 'được이 동사 뒤에서 "~할 수 있다." được이 주어 뒤에서 "얻다" (긍정적이고 좋은 상태를 나타내기 위해 사용됨.)',
              'zh': 'được 放在動詞後表示"能~"。được 放在主語後表示"獲得"（用於表達積極、良好的狀態。）',
              'en': 'được after a verb means "can ~." được after the subject means "to get/obtain" (used to '
                    'indicate a positive, good state.)',
              'ja': 'được が動詞の後ろにあると「~できる」。được が主語の後ろにあると「得る」（肯定的で良い状態を表すために使われる。）'},
  'examples': [{'vi': 'Anh nói tiếng Anh được không?',
                'kr': {'ko': '당신은 영어를 할 수 있습니까?',
                       'zh': '您會說英語嗎？',
                       'en': 'Can you speak English?',
                       'ja': 'あなたは英語ができますか？'}},
               {'vi': 'Dạ, được. / Dạ, không được.',
                'kr': {'ko': '예, 할 수 있습니다. / 예, 할 수 없습니다.',
                       'zh': '是的，可以。／是的，不可以。',
                       'en': 'Yes, I can. / Yes, I cannot.',
                       'ja': 'はい、できます。／はい、できません。'}},
               {'vi': 'Tôi được phép đi chơi.',
                'kr': {'ko': '나는 놀러 가는 것을 허락받았다.',
                       'zh': '我被允許出去玩。',
                       'en': 'I was given permission to go out and play.',
                       'ja': '私は遊びに行くことを許可された。'}}]},
 {'headword': 'gửi lời',
  'pos': None,
  'meaning': {'ko': '안부를 전해달라고 부탁하는 말 앞에 사용함.',
              'zh': '用於請對方代為問候的話語前面。',
              'en': "Used before a phrase asking someone to pass along one's regards.",
              'ja': 'よろしくと伝えてほしいと頼む言葉の前に使用します。'},
  'examples': [{'vi': 'Xin gửi lời thăm anh Phát.',
                'kr': {'ko': '제 대신 Phát에게 안부를 전해 주세요.',
                       'zh': '請代我向Phát問好。',
                       'en': 'Please give my regards to Phát for me.',
                       'ja': '私の代わりにPhátによろしくお伝えください。'}},
               {'vi': 'Xin gửi lời chào gia đình Minh.',
                'kr': {'ko': '제 대신 Minh 가족에게 안부를 전해 주세요.',
                       'zh': '請代我向Minh一家問好。',
                       'en': "Please give my regards to Minh's family for me.",
                       'ja': '私の代わりにMinhのご家族によろしくお伝えください。'}}]},
 {'headword': 'hả',
  'pos': {'ko': '조사', 'zh': '助詞', 'en': 'particle', 'ja': '助詞'},
  'meaning': {'ko': '문장 앞과 끝에 사용하여 질문을 더욱 더 파악함./ 명) 친밀함을 나타내는 의문사',
              'zh': '用在句子的前面和末尾，使提問更加明確。／（名）表示親密感的疑問詞',
              'en': 'Used at the beginning and end of a sentence to make the question clearer. / (noun) an '
                    'interrogative word expressing familiarity',
              'ja': '文の前と後ろに使って質問をより明確にする。／（名）親しみを表す疑問詞'},
  'examples': [{'vi': 'Xe đến rồi hả?',
                'kr': {'ko': '차 도착했어요?', 'zh': '車到了嗎?', 'en': 'Has the car arrived?', 'ja': '車は着きましたか?'}},
               {'vi': 'Hả, bao nhiêu tiền?',
                'kr': {'ko': '얼마에요?', 'zh': '多少錢？', 'en': 'How much is it?', 'ja': 'いくらですか。'}}]},
 {'headword': 'hàng …',
  'pos': None,
  'meaning': {'ko': '수 ~ 시간을 뜻하는 명사 앞에 위치해 장기간을 나타냄. 또는 많은 수를 나타냄.)',
              'zh': '位於表示「~小時」等時間的名詞前，表示長時間。或表示數量很多。)',
              'en': 'Placed before a noun meaning "several ~ hours/time" to indicate a long duration. Or '
                    'indicates a large quantity.)',
              'ja': '「〜時間」などの時間を表す名詞の前に置かれ、長期間を表す。または多い数を表す。)'},
  'examples': [{'vi': 'Hàng triệu người',
                'kr': {'ko': '수백만 사람', 'zh': '數百萬人', 'en': 'millions of people', 'ja': '数百万の人々'}},
               {'vi': 'Hàng ngày', 'kr': {'ko': '매일', 'zh': '每天', 'en': 'every day', 'ja': '毎日'}}]},
 {'headword': 'hơn',
  'pos': None,
  'meaning': {'ko': '비교급 문장을 만들 때 쓰는 용법 : ~보다 나은, 더 좋은',
              'zh': '表示「比…好、更好」的比較級用法',
              'en': 'Usage for forming comparative sentences: better than ~, more',
              'ja': '比較級の文を作るときに使う用法：〜より良い、もっと良い'},
  'examples': [{'vi': 'Lan cao hơn Mai.',
                'kr': {'ko': 'Lan은 Mai보다 더 큽니다.',
                       'zh': 'Lan比Mai更高。',
                       'en': 'Lan is taller than Mai.',
                       'ja': 'ランはマイより背が高いです。'}},
               {'vi': 'Anh ấy thích cà phê hơn trà.',
                'kr': {'ko': '그는 차보다 커피를 더 좋아합니다.',
                       'zh': '比起茶,他更喜歡咖啡。',
                       'en': 'He likes coffee more than tea.',
                       'ja': '彼はお茶よりコーヒーの方が好きです。'}},
               {'vi': 'Cái ti vi này rẻ hơn cái ti vi kia.',
                'kr': {'ko': '이 TV는 저 TV보다 더 쌉니다.',
                       'zh': '這台電視比那台電視更便宜。',
                       'en': 'This TV is cheaper than that TV.',
                       'ja': 'このテレビはあのテレビより安いです。'}}]},
 {'headword': 'khó',
  'pos': None,
  'meaning': {'ko': '~하기 어렵다. (행동의 어려움의 정도를 나타내는 표현.)',
              'zh': '難以~。（表示動作困難程度的表達方式。）',
              'en': 'hard to ~. (An expression indicating how difficult the action is.)',
              'ja': '~しにくい。（行動の難しさの程度を表す表現。）'},
  'examples': [{'vi': 'Vấn đề này khó nói lắm.',
                'kr': {'ko': '이 문제는 말하기 매우 어렵다.',
                       'zh': '這個問題很難說。',
                       'en': 'This problem is very difficult to talk about.',
                       'ja': 'この問題は話すのがとても難しい。'}}]},
 {'headword': 'không thể',
  'pos': None,
  'meaning': {'ko': 'Không thể는 조동사로 "~할 수 없다."',
              'zh': "Không thể 是助動詞，意為'不能~'。",
              'en': 'Không thể is an auxiliary verb meaning "cannot ~."',
              'ja': 'Không thể は助動詞で「~できない」という意味です。'},
  'examples': [{'vi': 'Tôi không thể nấu món ăn Việt Nam.',
                'kr': {'ko': '나는 베트남 요리를 할 수 없습니다.',
                       'zh': '我不會做越南菜。',
                       'en': 'I cannot cook Vietnamese food.',
                       'ja': '私はベトナム料理を作れません。'}},
               {'vi': 'Tôi không nấu được món ăn Việt Nam.',
                'kr': {'ko': '나는 베트남 요리를 할 수 없습니다.',
                       'zh': '我不會做越南菜。',
                       'en': 'I cannot cook Vietnamese food.',
                       'ja': '私はベトナム料理を作れません。'}},
               {'vi': 'Tôi không thể nấu được món ăn Việt Nam.',
                'kr': {'ko': '나는 베트남 요리를 할 수 없습니다.',
                       'zh': '我不會做越南菜。',
                       'en': 'I cannot cook Vietnamese food.',
                       'ja': '私はベトナム料理を作れません。'}}]},
 {'headword': 'là',
  'pos': None,
  'meaning': {'ko': '~이다 (주어와 보어를 연결시킴.)',
              'zh': '是~（連接主語和補語。）',
              'en': 'to be ~ (connects the subject and the complement.)',
              'ja': '~である（主語と補語を結びつける。）'},
  'examples': [{'vi': 'Anh là sinh viên phải không?',
                'kr': {'ko': '당신은 학생입니까?', 'zh': '您是學生嗎？', 'en': 'Are you a student?', 'ja': 'あなたは学生ですか？'}},
               {'vi': 'Tôi là giáo viên.',
                'kr': {'ko': '나는 선생님이다.', 'zh': '我是老師。', 'en': 'I am a teacher.', 'ja': '私は先生だ。'}}]},
 {'headword': 'lại',
  'pos': {'ko': '부', 'zh': '副詞', 'en': 'adv.', 'ja': '副詞'},
  'meaning': {'ko': '동사 뒤에 사용, 행동을 다시 반복하기를 원할 때 말하는 사람의 기대와 동기와 반대될 때, 앞 문장과 뒤 문장 사이에 반대의 일에 사용함.',
              'zh': '用在動詞後面，當想要再次重複該動作、與說話者的期待和動機相反時，用於前後句之間表示相反的事情。',
              'en': 'Used after a verb; used when one wants to repeat an action again, contrary to the '
                    "speaker's expectation and motive, and used between the preceding and following clauses "
                    'to express something contrary.',
              'ja': '動詞の後ろに使用し、その行動をもう一度繰り返したいとき、話し手の期待や動機と反対のとき、前の文と後ろの文の間で反対のことに使用する。'},
  'examples': [{'vi': 'Em có thể nói lại một lần nữa được không?',
                'kr': {'ko': '당신은 한 번 더 말해 줄 수 있습니까?',
                       'zh': '您能再說一遍嗎？',
                       'en': 'Could you say that one more time?',
                       'ja': 'あなたはもう一度言っていただけますか？'}},
               {'vi': 'Ngủ xong, nó lại học.',
                'kr': {'ko': '잠자고 나서, 그는 다시 공부한다.',
                       'zh': '睡覺之後,他又開始學習。',
                       'en': 'After sleeping, he studies again.',
                       'ja': '眠った後、彼はまた勉強する。'}}]},
 {'headword': 'mới',
  'pos': {'ko': '부', 'zh': '副詞', 'en': 'adv.', 'ja': '副詞'},
  'meaning': {'ko': '단지, 비로소 *뒤에 동사가 옴. / 형)새로운, 처음으로…한 *주어 뒤에 사용.',
              'zh': '只，才 *後面接動詞。/（形容詞）新的，第一次…的 *用在主語後面。',
              'en': 'only, only then *followed by a verb. / (adj.) new, for the first time … *used after the '
                    'subject.',
              'ja': 'ただ、やっと *後ろに動詞が来る。/（形）新しい、初めて…した *主語の後ろに使う。'},
  'examples': [{'vi': 'Anh Minh mới đi Hà Nội hôm qua.',
                'kr': {'ko': 'Minh씨는 비로소 어제 하노이에 갔다.',
                       'zh': 'Minh先生昨天才去了河內。',
                       'en': 'Mr. Minh only went to Hanoi yesterday.',
                       'ja': 'ミンさんは昨日になってようやくハノイに行った。'}},
               {'vi': 'Tôi mới nói chuyện với anh ấy.',
                'kr': {'ko': '나는 처음으로 그와 이야기 했다.',
                       'zh': '我第一次和他談了話。',
                       'en': 'I talked with him for the first time.',
                       'ja': '私は初めて彼と話をした。'}},
               {'vi': 'Cái áo này mới.',
                'kr': {'ko': '이 옷은 새것이다.',
                       'zh': '這件衣服是新的。',
                       'en': 'These clothes are new.',
                       'ja': 'この服は新品だ。'}}]},
 {'headword': 'nên',
  'pos': None,
  'meaning': {'ko': '이 단어는 동사 앞에 위치하여 반드시 실현되어야 할 행동을 나타냄.',
              'zh': '此詞位於動詞前,表示必須實現的動作。',
              'en': 'This word is placed before a verb to indicate an action that must be carried out.',
              'ja': 'この単語は動詞の前に置かれ、必ず実現されるべき行動を表す。'},
  'examples': [{'vi': 'Anh nên đi Việt Nam.',
                'kr': {'ko': '당신은 베트남에 가야 해요.',
                       'zh': '您必須去越南。',
                       'en': 'You have to go to Vietnam.',
                       'ja': 'あなたはベトナムに行かなければなりません。'}},
               {'vi': 'Anh nên làm giáo viên.',
                'kr': {'ko': '당신은 선생님을 해야 해요.',
                       'zh': '您應該當老師。',
                       'en': 'You should become a teacher.',
                       'ja': 'あなたは先生をしなければなりません。'}}]},
 {'headword': 'nhé',
  'pos': None,
  'meaning': {'ko': '말끝에 붙여 권유 또는 제의 할 때 사용.',
              'zh': '加在話尾，用於勸誘或提議時使用。',
              'en': 'Attached to the end of a sentence, used when suggesting or proposing something.',
              'ja': '話の終わりに付けて、勧誘または提案をするときに使用する。'},
  'examples': [{'vi': 'Anh kêu món ăn nhé!',
                'kr': {'ko': '당신이 요리를 시켜라!',
                       'zh': '您來點菜吧！',
                       'en': 'You order the food!',
                       'ja': 'あなたが料理を注文しなさい！'}},
               {'vi': 'Ngày mai chị đến sớm nhé!',
                'kr': {'ko': '당신은 내일 일찍 도착해야 합니다!',
                       'zh': '您明天必須早點到！',
                       'en': 'You must arrive early tomorrow!',
                       'ja': 'あなたは明日早く到着しなければなりません！'}}]},
 {'headword': 'nhỉ',
  'pos': {'ko': '부', 'zh': '副詞', 'en': 'adv.', 'ja': '副詞'},
  'meaning': {'ko': '문장 끝에 붙여 강조하는 말/ 질문에 사용할 경우 - 상대의 동의를 구하는 말.',
              'zh': '加在句末表示強調的詞／用於提問時——徵求對方同意的話。',
              'en': 'A word attached to the end of a sentence for emphasis / when used in a question — a '
                    "word seeking the other person's agreement.",
              'ja': '文末に付けて強調する言葉／質問に使う場合－相手の同意を求める言葉。'},
  'examples': [{'vi': 'Anh ấy nói tiếng Việt giỏi quá nhỉ.',
                'kr': {'ko': '그는 베트남어를 매우 잘한다.',
                       'zh': '他越南語說得很好。',
                       'en': 'He is very good at Vietnamese.',
                       'ja': '彼はベトナム語がとても上手だ。'}},
               {'vi': 'Hôm nay trời lạnh quá, chỉ nhỉ?',
                'kr': {'ko': '오늘 날씨 매우 춥네요, 그렇죠?',
                       'zh': '今天天氣很冷，對吧？',
                       'en': "The weather is very cold today, isn't it?",
                       'ja': '今日はとても寒いですね、そうでしょう？'}}]},
 {'headword': 'nhờ',
  'pos': None,
  'meaning': {'ko': '~ 덕분에, ~에 의지하여 / Nhờ 뒤에는 항상 인칭, 문장중간에 giúp, giùm, hộ 사용함.',
              'zh': '~多虧，依靠~／Nhờ 後面總是接人稱，句子中間使用 giúp、giùm、hộ。',
              'en': 'thanks to ~, relying on ~ / Nhờ is always followed by a person; giúp, giùm, or hộ are '
                    'used in the middle of the sentence.',
              'ja': '~のおかげで、~に頼って／Nhờ の後には常に人称が来て、文の途中で giúp、giùm、hộ を使います。'},
  'examples': [{'vi': 'Nhờ anh mang giúp hành lý của tôi ra xe.',
                'kr': {'ko': '당신이 도와준 덕분에 나의 트렁크를 차까지 옮길 수 있었다.',
                       'zh': '多虧您的幫助，我才能把行李箱搬到車上。',
                       'en': 'Thanks to your help, I was able to carry my trunk to the car.',
                       'ja': 'あなたが手伝ってくれたおかげで、私のトランクを車まで運ぶことができました。'}},
               {'vi': 'Nhờ anh hỏi họ tôi giá vé máy bay đi Hà Nội là bao nhiêu.',
                'kr': {'ko': '당신 덕분에 하노이 가는 비행기 표 값이 얼마인지 질문할 수 있었다.',
                       'zh': '多虧了您，我才能夠問到去河內的機票多少錢。',
                       'en': 'Thanks to you, I was able to ask how much the plane ticket to Hanoi costs.',
                       'ja': 'あなたのおかげで、ハノイ行きの飛行機のチケットがいくらか尋ねることができました。'}}]},
 {'headword': 'những',
  'pos': None,
  'meaning': {'ko': '…들 (명사 앞에 위치하여 복수형을 만듦. 구체적이거나 특정한 대상을 가리킴.)',
              'zh': '…들（們）（位於名詞前面構成複數形式。指具體或特定的對象。）',
              'en': '…들 (plural marker; placed before a noun to make a plural form. Refers to a specific, '
                    'concrete group.)',
              'ja': '…들（〜たち）（名詞の前に位置して複数形を作る。具体的または特定の対象を指す。）'},
  'examples': [{'vi': 'Trong số các bạn, những bạn nào đã đi Việt Nam?',
                'kr': {'ko': '친구들 중에, 어떤 친구들이 베트남에 가보았니?',
                       'zh': '朋友們中,有哪些朋友去過越南?',
                       'en': 'Among your friends, which ones have been to Vietnam?',
                       'ja': '友達の中で、どの友達がベトナムに行ったことがありますか?'}},
               {'vi': 'Những quyển sách này rất hay.',
                'kr': {'ko': '이 책들은 매우 재미있다.',
                       'zh': '這些書很有趣。',
                       'en': 'These books are very interesting.',
                       'ja': 'この本はとても面白い。'}}]},
 {'headword': 'ở',
  'pos': None,
  'meaning': {'ko': '~에 (동사 뒤나 장소를 나타내는 명사 앞에 위치하여 행동이 발생된 장소를 가리킴.)',
              'zh': '~在（位於動詞後面或表示地點的名詞前面，指出動作發生的地點。）',
              'en': '~ at (placed after a verb or before a noun indicating a place, pointing to where the '
                    'action occurs.)',
              'ja': '~に（動詞の後ろや場所を表す名詞の前に位置し、行動が起こった場所を指す。）'},
  'examples': [{'vi': 'Tôi học ở Hà Nội.',
                'kr': {'ko': '나는 하노이에서 공부합니다.',
                       'zh': '我在河內學習。',
                       'en': 'I study in Hanoi.',
                       'ja': '私はハノイで勉強します。'}},
               {'vi': 'Chị dạy ở Seoul.',
                'kr': {'ko': '당신은 서울에서 가르친다.',
                       'zh': '您在首爾教書。',
                       'en': 'You teach in Seoul.',
                       'ja': 'あなたはソウルで教えます。'}}]},
 {'headword': 'quyển',
  'pos': None,
  'meaning': {'ko': '책을 의미하는 명사 대신 씀.',
              'zh': '用於代替表示“書”的名詞。',
              'en': 'Used in place of a noun meaning "book".',
              'ja': '「本」を意味する名詞の代わりに使う。'},
  'examples': [{'vi': 'Anh ấy đã đọc quyển sách ấy chưa? / quyển vở노트, quyển sổ tay다이어리.',
                'kr': {'ko': '*동물이외에 con đao 칼, con đường 길',
                       'zh': '*除動物之外，還有 con đao（刀）、con đường（路）',
                       'en': '*Besides animals, also con đao (knife), con đường (road)',
                       'ja': '*動物以外にも con đao（刀）、con đường（道）'}}]},
 {'headword': 'rất',
  'pos': None,
  'meaning': {'ko': '매우 (형용사 앞에 위치해야 함.)',
              'zh': '非常（必須位於形容詞前面。）',
              'en': 'very (must be placed before the adjective.)',
              'ja': 'とても（形容詞の前に位置しなければならない。）'},
  'examples': [{'vi': 'Anh ấy rất đẹp.',
                'kr': {'ko': '그는 매우 잘생겼다.', 'zh': '他很帥。', 'en': 'He is very handsome.', 'ja': '彼はとてもハンサムだ。'}},
               {'vi': 'Rất tốt', 'kr': {'ko': '매우 좋은', 'zh': '非常好的', 'en': 'very good', 'ja': 'とても良い'}}]},
 {'headword': 'theo',
  'pos': None,
  'meaning': {'ko': '~에 따르면 (인칭대명사 앞에 위치하면 누군가의 개별적인 의견을 말하는 표현)',
              'zh': '根據~（放在人稱代詞前面時，表示某人的個人意見）',
              'en': "according to ~ (when placed before a personal pronoun, an expression stating someone's "
                    'personal opinion)',
              'ja': '~によれば（人称代名詞の前に位置すると、誰かの個人的な意見を述べる表現）'},
  'examples': [{'vi': 'Theo tôi, anh ấy nói đúng.',
                'kr': {'ko': '내 생각에는, 그가 정확히 말한다.',
                       'zh': '我認為,他說得很準確。',
                       'en': 'In my opinion, he speaks accurately.',
                       'ja': '私の考えでは、彼は正確に話す。'}},
               {'vi': 'Theo bà, đôi giày này có đắt không?',
                'kr': {'ko': '아주머니 생각에는, 이 신발이 비쌉니까?',
                       'zh': '阿姨，您覺得這雙鞋貴嗎？',
                       'en': "Ma'am, do you think these shoes are expensive?",
                       'ja': 'おばさん、あなたの考えでは、この靴は高いですか。'}}]},
 {'headword': 'vậy',
  'pos': {'ko': '부', 'zh': '副詞', 'en': 'adv.', 'ja': '副詞'},
  'meaning': {'ko': '그와 같이, 그래서 / 질문하는 문장 끝에 사용되어 그 내용을 더 파악하기 위해 사용함.',
              'zh': '像那樣,所以 / 用在疑問句句尾,用來進一步確認其內容。',
              'en': 'like that, so / Used at the end of a question sentence to further clarify the content.',
              'ja': 'そのように、それで / 疑問文の文末に使われ、その内容をさらに把握するために使用する。'},
  'examples': [{'vi': 'Tất cả bao nhiêu tiền vậy, cô?',
                'kr': {'ko': '전부 얼마 입니까, 아가씨?',
                       'zh': '一共多少錢,小姐?',
                       'en': 'How much is it altogether, miss?',
                       'ja': '全部でいくらですか、お嬢さん?'}},
               {'vi': 'Ga Sài Gòn ở đâu vậy?',
                'kr': {'ko': 'Sài Gòn역이 어디에 있죠?',
                       'zh': '西貢站在哪裡？',
                       'en': 'Where is Sài Gòn Station?',
                       'ja': 'サイゴン駅はどこにありますか？'}}]},
 {'headword': 'xin',
  'pos': None,
  'meaning': {'ko': '정중한 표현, 요청할 때 사용함.',
              'zh': '禮貌的表達方式,用於請求時。',
              'en': 'A polite expression, used when making a request.',
              'ja': '丁寧な表現で、依頼するときに使う。'},
  'examples': [{'vi': 'Xin chào anh.', 'kr': {'ko': '안녕하세요.', 'zh': '你好。', 'en': 'Hello.', 'ja': 'こんにちは。'}},
               {'vi': 'Xin cảm ơn chị.',
                'kr': {'ko': '고맙습니다.', 'zh': '謝謝。', 'en': 'Thank you.', 'ja': 'ありがとうございます。'}}]},
 {'headword': 'xong',
  'pos': None,
  'meaning': {'ko': '마치다.(동사 뒤에 위치하여 그 행동을 끝냈다는 표현. 단독으로 사용할 때도 있음.)',
              'zh': '結束。（位於動詞後面，表示已經完成該動作的表達。也有單獨使用的情況。）',
              'en': 'To finish. (Placed after a verb, expressing that the action has been completed. It can '
                    'also be used alone.)',
              'ja': '終える。（動詞の後ろに位置して、その行動を終えたという表現。単独で使う場合もある。）'},
  'examples': [{'vi': 'Anh ấy làm nhà xong rồi.',
                'kr': {'ko': '그는 이미 집을 다 만들었다.',
                       'zh': '他已經把房子全部蓋好了。',
                       'en': 'He has already finished building the house.',
                       'ja': '彼はすでに家を全部建て終えた。'}},
               {'vi': 'Khi nào xong việc, anh và tôi đi chơi.',
                'kr': {'ko': '일이 끝날 때면, 너와 내가 놀러 가자.',
                       'zh': '工作結束的時候,我們一起去玩吧。',
                       'en': "When the work is done, let's you and I go out and have fun.",
                       'ja': '仕事が終わったら、あなたと私で遊びに行こう。'}}]},
 {'headword': '(như) thế nào?',
  'pos': None,
  'meaning': {'ko': '이 구문은 명사 또는 동사 뒤에 위치하여 상태, 성질 등에 대해 묻기 위해 사용함.',
              'zh': '此句型位於名詞或動詞之後,用於詢問狀態、性質等。',
              'en': 'This construction is placed after a noun or verb to ask about a state, quality, etc.',
              'ja': 'この構文は名詞または動詞の後に置かれ、状態や性質などについて尋ねるために使う。'},
  'examples': [{'vi': 'Sinh viên học thế nào?',
                'kr': {'ko': '학생은 공부를 어떻게 합니까?',
                       'zh': '學生是怎麼學習的?',
                       'en': 'How does the student study?',
                       'ja': '学生はどのように勉強しますか?'}},
               {'vi': 'Sinh viên học tốt.',
                'kr': {'ko': '학생은 공부를 잘 합니다.',
                       'zh': '學生學習得很好。',
                       'en': 'The student studies well.',
                       'ja': '学生は勉強がよくできます。'}}]},
 {'headword': '…(1.2)…gìcũng…(3)',
  'pos': None,
  'meaning': {'ko': '(1)또는 (2)라도 (3)한다. (1,2의 대립되는 단어를 사용하여 어떤 경우에는 3의 행동을 하겠다는 표현.)',
              'zh': '無論(1)還是(2)都(3)。（使用(1)、(2)這對相反的詞，表示無論哪種情況都會做(3)這個動作的表達方式。）',
              'en': 'Whether (1) or (2), (3) happens. (An expression using a pair of opposite words (1) and '
                    '(2) to say that action (3) will be done in either case.)',
              'ja': '(1)でも(2)でも(3)する。（(1)、(2)という対立する単語を使い、どちらの場合でも(3)の行動をするという表現。）'},
  'examples': [{'vi': 'Đắt rẻ gì cũng ăn.',
                'kr': {'ko': '비싸건 싸건 역시 먹는다.',
                       'zh': '不管貴還是便宜，還是要吃。',
                       'en': "Whether it's expensive or cheap, I'll eat it anyway.",
                       'ja': '高くても安くても、やはり食べます。'}},
               {'vi': 'Xấu đẹp gì cũng mua.',
                'kr': {'ko': '추하던 이쁘던 역시 산다.',
                       'zh': '無論醜還是美,人還是要生活。',
                       'en': 'Whether ugly or pretty, one still lives all the same.',
                       'ja': '醜くても美しくても、やはり生きていく。'}}]},
 {'headword': '…(đã) lâu chưa?',
  'pos': None,
  'meaning': {'ko': '…오래 되었습니까? (어떤 일을 한지 시간적으로 물어보는 표현.)',
              'zh': '…有多久了？（詢問某事已經過去多長時間的表達方式。）',
              'en': '… has it been long? (An expression asking how much time has passed since doing '
                    'something.)',
              'ja': '…長くなりましたか？（あることをしてからどれくらい時間が経ったかを尋ねる表現。）'},
  'examples': [{'vi': 'Anh làm nghề giáo viên đã lâu chưa?',
                'kr': {'ko': '당신은 선생님을 한 지 오래되었습니까?',
                       'zh': '您當老師很久了嗎？',
                       'en': 'Have you been a teacher for a long time?',
                       'ja': 'あなたは先生になってから長いですか？'}},
               {'vi': 'Anh sang Hàn Quốc đã lâu chưa?',
                'kr': {'ko': '당신은 한국에 건너온 지 오래되었습니까?',
                       'zh': '您來韓國很久了嗎？',
                       'en': 'Has it been a long time since you came to Korea?',
                       'ja': 'あなたは韓国に来てから長いですか？'}}]},
 {'headword': '…bao xa?/…mất bao lâu?',
  'pos': None,
  'meaning': {'ko': 'bao xa 거리/ mất bao lâu (시간이)얼마나 걸리는가?',
              'zh': 'bao xa 距離／mất bao lâu （時間）要多久？',
              'en': 'bao xa (distance) / mất bao lâu — how long does it take (time)?',
              'ja': 'bao xa 距離／mất bao lâu （時間が）どのくらいかかるか？'},
  'examples': [{'vi': 'Vũng Tàu cách Sài Gòn bao xa? - Khoảng 100 km.',
                'kr': {'ko': 'Vũng Tàu는 Sài Gòn에서 얼마나 먼가요? - 약 100 km입니다.',
                       'zh': '頭頓離西貢有多遠？——大約100公里。',
                       'en': 'How far is Vũng Tàu from Sài Gòn? — About 100 km.',
                       'ja': 'ブンタウはサイゴンからどのくらい遠いですか？ — 約100kmです。'}},
               {'vi': 'Từ Sài Gòn đến Vũng Tàu mất bao lâu? - Mất khoảng 2 tiếng.',
                'kr': {'ko': 'Sài Gòn에서 Vũng Tàu까지 얼마나 걸리나요? - 약 2시간 걸립니다.',
                       'zh': '從西貢到頭頓要多久？——大約需要2小時。',
                       'en': 'How long does it take from Sài Gòn to Vũng Tàu? — It takes about 2 hours.',
                       'ja': 'サイゴンからブンタウまでどのくらいかかりますか？ — 約2時間かかります。'}}]},
 {'headword': '… chỉ … thôi',
  'pos': None,
  'meaning': {'ko': '단지, 다만 / 만 ( = chỉ +동사 또는 명사 … + mà thôi 의 형식임.)',
              'zh': '只是，只不過 / 只 (= chỉ + 動詞或名詞 … + mà thôi 的形式。)',
              'en': 'just, only / only (= in the form chỉ + verb or noun … + mà thôi.)',
              'ja': 'ただ、〜だけ / だけ（= chỉ + 動詞または名詞 … + mà thôi の形。）'},
  'examples': [{'vi': 'Tôi chỉ thích xem phim. / Tôi chỉ thích xem phim thôi.',
                'kr': {'ko': '나는 영화 보는 것만 좋아한다.',
                       'zh': '我只喜歡看電影。',
                       'en': 'I only like watching movies.',
                       'ja': '私は映画を見ることだけが好きだ。'}},
               {'vi': 'Chỉ thanh niên thích nhạc rock. / Chỉ thanh niên thích nhạc rock thôi.',
                'kr': {'ko': '단지 젊은이들만 록 음악을 좋아한다.',
                       'zh': '只有年輕人喜歡搖滾音樂。',
                       'en': 'Only young people like rock music.',
                       'ja': 'ただ若者たちだけがロック音楽を好む。'}}]},
 {'headword': '… đi!',
  'pos': None,
  'meaning': {'ko': '…해라! (문장의 끝에 위치하여 즉시 시행할 것을 명령, 권유하는 표현)',
              'zh': '…做吧！（位於句末，表示立即命令或勸誘執行某事的表達方式）',
              'en': 'Do …! (Placed at the end of a sentence, an expression that commands or urges immediate '
                    'action.)',
              'ja': '…しろ！（文末に位置し、即座に実行するよう命令・勧める表現）'},
  'examples': [{'vi': 'Vào đi!', 'kr': {'ko': '들어와!', 'zh': '進來！', 'en': 'Come in!', 'ja': '入って来て！'}},
               {'vi': 'Anh học đi!', 'kr': {'ko': '공부해라!', 'zh': '去學習吧！', 'en': 'Study!', 'ja': '勉強しろ！'}}]},
 {'headword': '… đi(lại)',
  'pos': None,
  'meaning': {'ko': '형용사 다음에 놓여 과거에 비해 감소 또는 퇴화를 나타낼 때 사용함.',
              'zh': '放在形容詞之後,用於表示與過去相比的減少或退化。',
              'en': 'Placed after an adjective, used to indicate a decrease or decline compared to the past.',
              'ja': '形容詞の後に置かれ、過去に比べて減少または退化を表すときに使う。'},
  'examples': [{'vi': 'Anh ấy dạo này yếu đi.',
                'kr': {'ko': '요즘 그는 점점 쇠약해진다.',
                       'zh': '最近他越來越虛弱了。',
                       'en': 'These days, he is getting weaker.',
                       'ja': '最近、彼はだんだん弱っている。'}},
               {'vi': 'Chị ấy bắt đầu nhăn lại.',
                'kr': {'ko': '그녀의 피부는 주름살이 생기기 시작했다.',
                       'zh': '她的皮膚開始出現皺紋了。',
                       'en': 'Her skin has started to develop wrinkles.',
                       'ja': '彼女の肌にしわができ始めた。'}}]},
 {'headword': '… đúng không?',
  'pos': None,
  'meaning': {'ko': '…맞습니까? (문장의 끝에 위치해서 긍정문을 의문문으로 만듦.)',
              'zh': '…對嗎？（位於句末，把陳述句變成疑問句。）',
              'en': '… right? (Placed at the end of a sentence to turn a statement into a question.)',
              'ja': '…合っていますか？（文末に位置して肯定文を疑問文にする。）'},
  'examples': [{'vi': 'Bây giờ là 5 giờ rồi, đúng không?',
                'kr': {'ko': '지금은 5시입니다, 맞지요?',
                       'zh': '現在是5點,對吧?',
                       'en': "It's 5 o'clock now, right?",
                       'ja': '今は5時です、そうですよね?'}},
               {'vi': 'Anh là sinh viên, đúng không?',
                'kr': {'ko': '당신은 학생입니다, 맞지요?',
                       'zh': '您是學生，對吧？',
                       'en': 'You are a student, right?',
                       'ja': 'あなたは学生ですよね？'}}]},
 {'headword': '…lắm',
  'pos': None,
  'meaning': {'ko': '매우(형용사 뒤에 위치함.)',
              'zh': '非常（位於形容詞後面。）',
              'en': 'very (placed after the adjective.)',
              'ja': 'とても（形容詞の後ろに位置する。）'},
  'examples': [{'vi': 'Đẹp lắm.',
                'kr': {'ko': '매우 아름답다.', 'zh': '非常漂亮。', 'en': 'Very beautiful.', 'ja': 'とても美しい。'}},
               {'vi': 'Anh ấy đẹp lắm.',
                'kr': {'ko': '그는 매우 잘생겼다.',
                       'zh': '他很帥。',
                       'en': 'He is very handsome.',
                       'ja': '彼はとてもハンサムだ。'}}]},
 {'headword': '… làm sao … được',
  'pos': None,
  'meaning': {'ko': '… 은 가능하지 않다.(…이 불가능하다는 표현.)',
              'zh': '…是不可能的。（表示…不可能的表達方式。）',
              'en': '… is not possible. (An expression saying that … is impossible.)',
              'ja': '…は可能ではない。（…が不可能であるという表現。）'},
  'examples': [{'vi': 'Chúng ta ăn làm sao hết được.',
                'kr': {'ko': '우리가 어떻게 다 먹을 수 있겠니?',
                       'zh': '我們怎麼可能全部吃完呢？',
                       'en': 'How could we possibly eat it all?',
                       'ja': '私たちがどうやって全部食べられるでしょうか。'}}]},
 {'headword': '… ngay',
  'pos': None,
  'meaning': {'ko': '즉시 … (동사 뒤에 위치하여 즉시 동사 할 것 을 요구 또는 명령하는 표현.)',
              'zh': '立即……(位於動詞後,表示要求或命令立即做該動作的表達。)',
              'en': 'Immediately... (an expression placed after a verb requesting or commanding that the '
                    'action be done at once.)',
              'ja': 'すぐに…(動詞の後に置かれ、すぐにその動作をするよう要求または命令する表現。)'},
  'examples': [{'vi': 'Xe cứu hỏa đến ngay, chợ Đồng Xuân cháy!',
                'kr': {'ko': '소방차 즉시 오세요, Đồng Xuân시장이 불타고 있어요!',
                       'zh': '消防車請立刻過來，Đồng Xuân市場著火了！',
                       'en': 'Fire truck, come immediately, Đồng Xuân market is on fire!',
                       'ja': '消防車、すぐ来てください、Đồng Xuân市場が燃えています！'}},
               {'vi': 'Mẹ ốm nặng, con về ngay.',
                'kr': {'ko': '어머니가 중병이시다, 너는 즉시 돌아와라.',
                       'zh': '母親病重了，你馬上回來。',
                       'en': 'Mother is gravely ill, come back immediately.',
                       'ja': '母が重病です、すぐに帰ってきなさい。'}}]},
 {'headword': '…nhất',
  'pos': None,
  'meaning': {'ko': '가장…하다.(최상급)', 'zh': '最…（最高級）', 'en': 'the most ... (superlative)', 'ja': '最も…だ。（最上級）'},
  'examples': [{'vi': 'Trong mười hai tháng thì tháng hai là tháng rét nhất.',
                'kr': {'ko': '12개월 중 2월이 제일 추운 달이다.',
                       'zh': '12個月中2月是最冷的月份。',
                       'en': 'Of the 12 months, February is the coldest.',
                       'ja': '12か月の中で2月が一番寒い月だ。'}},
               {'vi': 'Giỏi nhất',
                'kr': {'ko': '가장 능숙한', 'zh': '最熟練的', 'en': 'the most skillful', 'ja': '最も上手な'}}]},
 {'headword': '…nữa',
  'pos': None,
  'meaning': {'ko': '동사 뒤에 또는 문장 맨 끝에 위치하여 행동의 반복 또는 추가를 표시함.',
              'zh': '位於動詞後面或句子末尾，表示動作的重複或追加。',
              'en': 'Placed after a verb or at the very end of a sentence, indicating repetition or addition '
                    'of an action.',
              'ja': '動詞の後ろまたは文の最後に位置して、動作の反復または追加を表す。'},
  'examples': [{'vi': 'Tôi sẽ đi Việt Nam nữa.',
                'kr': {'ko': '나는 베트남에 또 갈 거야.',
                       'zh': '我還會再去越南的。',
                       'en': 'I will go to Vietnam again.',
                       'ja': '私はまたベトナムに行くつもりだ。'}},
               {'vi': 'Anh nên học tiếng Việt nữa.',
                'kr': {'ko': '당신은 베트남어를 더 배워야 해요.',
                       'zh': '您需要多學一點越南語。',
                       'en': 'You need to learn more Vietnamese.',
                       'ja': 'あなたはもっとベトナム語を学ばなければなりません。'}}]},
 {'headword': '…quá',
  'pos': None,
  'meaning': {'ko': '매우 (형용사의 앞, 뒤 모두에 위치할 수 있음.)',
              'zh': '非常（可以位於形容詞的前面或後面。）',
              'en': 'very (can be placed either before or after the adjective.)',
              'ja': 'とても（形容詞の前後どちらにも位置できる。）'},
  'examples': [{'vi': 'Anh ấy đẹp quá.',
                'kr': {'ko': '그는 매우 잘생겼다.', 'zh': '他很帥。', 'en': 'He is very handsome.', 'ja': '彼はとてもハンサムだ。'}},
               {'vi': 'To quá.', 'kr': {'ko': '매우 크다.', 'zh': '非常大。', 'en': 'Very big.', 'ja': 'とても大きい。'}}]},
 {'headword': '…ra(lên)',
  'pos': None,
  'meaning': {'ko': '형용사 다음에 위치하여 과거에 비해 발전 또는 진보를 나타낼 때 사용함.',
              'zh': '位於形容詞之後,用於表示與過去相比的發展或進步。',
              'en': 'Placed after an adjective, used to indicate development or progress compared to the '
                    'past.',
              'ja': '形容詞の後に位置し、過去に比べて発展または進歩を表すときに使う。'},
  'examples': [{'vi': 'Anh ấy dạo này khoẻ ra.',
                'kr': {'ko': '요즘 그는 점점 건강해진다.',
                       'zh': '最近他越來越健康了。',
                       'en': 'These days, he is getting healthier.',
                       'ja': '最近、彼はだんだん健康になっている。'}},
               {'vi': 'Chị ấy trắng hồng lên.',
                'kr': {'ko': '그녀의 피부는 점점 하얗고 발그스레 해진다.',
                       'zh': '她的皮膚漸漸變得白皙紅潤。',
                       'en': 'Her skin is gradually becoming white and rosy.',
                       'ja': '彼女の肌はだんだん白くほんのり赤くなっていく。'}}]},
 {'headword': '…sau',
  'pos': None,
  'meaning': {'ko': '뒤에 … 하다. ( 동사 뒤에 sau를 넣어 뒤에 동사를 하겠다는 표현.)',
              'zh': '之後…做。（在動詞後面加sau，表示之後要做該動詞動作的表達。）',
              'en': 'To do … afterward. (An expression formed by adding sau after the verb, meaning one will '
                    'do the verb afterward.)',
              'ja': '後で…する。（動詞の後ろにsauを入れて、後でその動詞をするという表現。）'},
  'examples': [{'vi': 'Anh làm trước, tôi làm sau.',
                'kr': {'ko': '너 먼저 해라, 나는 뒤에 할게.',
                       'zh': '你先做吧,我等一下再做。',
                       'en': "You go first, I'll do it later.",
                       'ja': 'お前が先にやれ、私は後でやるよ。'}},
               {'vi': 'Tuy ông ấy đến sau nhưng chưa muộn.',
                'kr': {'ko': '비록 그가 뒤에 왔지만, 아직 늦지 않았다.',
                       'zh': '雖然他來晚了，但還不算太晚。',
                       'en': 'Although he came late, it is still not too late.',
                       'ja': '彼は遅れて来たけれど、まだ遅くはありません。'}}]},
 {'headword': '…tiếp',
  'pos': None,
  'meaning': {'ko': '이 단어는 동사 뒤에 사용되어 행동의 계속을 나타냄.',
              'zh': '此詞用於動詞之後,表示動作的持續。',
              'en': 'This word is used after a verb to indicate the continuation of an action.',
              'ja': 'この単語は動詞の後に使われ、動作の継続を表す。'},
  'examples': [{'vi': 'Hôm nay có học tiếp không?',
                'kr': {'ko': '오늘 공부를 계속 합니까?',
                       'zh': '今天要繼續學習嗎？',
                       'en': 'Are you continuing to study today?',
                       'ja': '今日も勉強を続けますか。'}},
               {'vi': 'Không nghỉ, làm tiếp đi.',
                'kr': {'ko': '쉬지 말고, 일을 계속하세요.',
                       'zh': '不要休息，繼續工作。',
                       'en': "Don't rest, keep working.",
                       'ja': '休まないで、仕事を続けてください。'}}]},
 {'headword': '… trong bao lâu?',
  'pos': None,
  'meaning': {'ko': '… 얼마 동안? (어떤 일을 얼마 동안 하는 것인지를 물어보는 표현.)',
              'zh': '…多長時間？（詢問某事持續多長時間的表達方式。）',
              'en': '… for how long? (An expression asking how long something is/was done for.)',
              'ja': '…どのくらいの間？（あることをどのくらいの間するのかを尋ねる表現。）'},
  'examples': [{'vi': 'Anh đã ở Hàn Quốc trong bao lâu?',
                'kr': {'ko': '당신은 한국에 얼마 동안 살았습니까?',
                       'zh': '您在韓國住了多久？',
                       'en': 'How long have you lived in Korea?',
                       'ja': 'あなたは韓国にどのくらい住みましたか？'}},
               {'vi': 'Chị sẽ ở trong bao lâu nữa?',
                'kr': {'ko': '당신은 얼마나 더 계실 겁니까?',
                       'zh': '您還要待多久？',
                       'en': 'How much longer will you be staying?',
                       'ja': 'あなたはあとどのくらいいらっしゃいますか？'}}]},
 {'headword': '…xuống',
  'pos': None,
  'meaning': {'ko': '아래로 ~ 하다. (동사 뒤에 위치하여 행동의 방향(아래로)을 나타냄.)',
              'zh': '向下～。（放在動詞後面，表示動作的方向（向下）。）',
              'en': 'to ~ down. (Placed after the verb to indicate the direction of the action (downward).)',
              'ja': '下へ〜する。（動詞の後ろに置かれ、動作の方向（下へ）を表す。）'},
  'examples': [{'vi': 'Đặt bút xuống.',
                'kr': {'ko': '펜을 내려놓다.', 'zh': '放下筆。', 'en': 'Put down the pen.', 'ja': 'ペンを置く。'}},
               {'vi': 'Từ núi xuống.',
                'kr': {'ko': '산에서 내려오다.',
                       'zh': '從山上下來。',
                       'en': 'To come down from the mountain.',
                       'ja': '山から降りてくる。'}}]},
 {'headword': 'bởi vì…cho nên',
  'pos': None,
  'meaning': {'ko': '… 때문에 그래서…(원인과 결과를 나타내는 표현.)',
              'zh': '…因為所以…（表示原因和結果的表達方式。）',
              'en': '… because, so … (An expression showing cause and effect.)',
              'ja': '…なので、それで…（原因と結果を表す表現。）'},
  'examples': [{'vi': 'Bởi vì tôi là người Hàn Quốc cho nên tôi sống ở Hàn Quốc.',
                'kr': {'ko': '나는 한국 사람이기 때문에 나는 한국에서 삽니다.',
                       'zh': '因為我是韓國人,所以我住在韓國。',
                       'en': 'Because I am Korean, I live in Korea.',
                       'ja': '私は韓国人なので、韓国に住んでいます。'}},
               {'vi': 'Vì tôi đang nghiên cứu Việt Nam nên tôi cần đi Việt Nam.',
                'kr': {'ko': '나는 베트남에 대해 연구하기 때문에 나는 베트남에 갈 필요가 있다.',
                       'zh': '因為我在研究越南,所以我需要去越南。',
                       'en': 'Because I research about Vietnam, I need to go to Vietnam.',
                       'ja': '私はベトナムについて研究しているので、ベトナムに行く必要がある。'}}]},
 {'headword': 'cả…cả…',
  'pos': None,
  'meaning': {'ko': '이 구문은 거의 전체에 가까운 많은 수량을 강조하기 위해 사용함.',
              'zh': '此句型用於強調接近全部的大量數量。',
              'en': 'This construction is used to emphasize a large quantity close to the whole.',
              'ja': 'この構文はほぼ全体に近い多い数量を強調するために使う。'},
  'examples': [{'vi': 'Tôi làm việc cả ở cơ quan cả ở nhà.',
                'kr': {'ko': '나는 직장과 집 모두에서 일을 한다.',
                       'zh': '我在公司和家裡都工作。',
                       'en': 'I work both at the workplace and at home.',
                       'ja': '私は職場と家の両方で仕事をする。'}},
               {'vi': 'Cả bố tôi, cả mẹ tôi đều đã nghỉ hưu.',
                'kr': {'ko': '아버지와 어머니 모두 정년퇴직하셨다.',
                       'zh': '父親和母親都已經退休了。',
                       'en': 'Both my father and mother have retired.',
                       'ja': '父も母も定年退職しました。'}}]},
 {'headword': 'càng… càng…',
  'pos': None,
  'meaning': {'ko': '성질 또는 활동의 증가 또는 감소를 나타내기 위해 사용함.',
              'zh': '用於表示性質或活動的增加或減少。',
              'en': 'Used to indicate an increase or decrease in a quality or activity.',
              'ja': '性質または活動の増加または減少を表すために使用します。'},
  'examples': [{'vi': 'Cô gái này càng lớn càng xinh đẹp.',
                'kr': {'ko': '이 여자는 성장하면 할수록 더 아름다워진다.',
                       'zh': '這個女人越長大越漂亮。',
                       'en': 'The more this woman grows up, the more beautiful she becomes.',
                       'ja': 'この女性は成長すればするほどより美しくなる。'}},
               {'vi': 'Anh ấy càng học càng giỏi.',
                'kr': {'ko': '그는 공부를 하면 할수록 더 나아진다.',
                       'zh': '他越學習就越進步。',
                       'en': 'The more he studies, the better he gets.',
                       'ja': '彼は勉強すればするほど良くなる。'}}]},
 {'headword': 'càng ngày càng …',
  'pos': None,
  'meaning': {'ko': '날이 갈수록, 날로 (시간이 흘러갈수록 더욱 … 하다 라는 표현.)',
              'zh': '隨著日子過去,日益(表示"隨著時間流逝,越來越……"的表達。)',
              'en': 'as days go by, day by day (an expression meaning "the more time passes, the more …")',
              'ja': '日が経つにつれて、日増しに(時間が経つにつれてますます…であるという表現。)'},
  'examples': [{'vi': 'Càng ngày càng có nhiều người đi du lịch Việt Nam.',
                'kr': {'ko': '날이 갈수록 베트남에 여행 가는 사람들이 많아진다.',
                       'zh': '隨著日子過去,去越南旅行的人越來越多。',
                       'en': 'As days go by, more people travel to Vietnam.',
                       'ja': '日が経つにつれて、ベトナムへ旅行に行く人が多くなる。'}},
               {'vi': 'Mẹ tôi càng già càng yếu.',
                'kr': {'ko': '나의 어머니는 늙어갈수록 더욱 약해진다.',
                       'zh': '我的母親越老越虛弱。',
                       'en': 'As my mother grows older, she becomes weaker.',
                       'ja': '私の母は年を取れば取るほどさらに弱くなる。'}}]},
 {'headword': 'chả cần … đâu',
  'pos': None,
  'meaning': {'ko': '… 은 필요 없다. (구어체에서 사용하는 부정 표현.)',
              'zh': '…不需要。（口語中使用的否定表達方式。）',
              'en': '… is not needed. (A negative expression used in spoken/colloquial language.)',
              'ja': '…は必要ない。（口語体で使う否定表現。）'},
  'examples': [{'vi': 'Chả cần thực đơn đâu.',
                'kr': {'ko': '메뉴판은 필요 없어요.',
                       'zh': '不需要菜單。',
                       'en': "I don't need the menu.",
                       'ja': 'メニューは必要ありません。'}},
               {'vi': 'Thực đơn chẳng cần đâu.',
                'kr': {'ko': '메뉴판은 필요 없어요.',
                       'zh': '不需要菜單。',
                       'en': "I don't need the menu.",
                       'ja': 'メニューは必要ありません。'}}]},
 {'headword': 'chắc là',
  'pos': None,
  'meaning': {'ko': '정확하지는 않지만 확실한 것 같다.',
              'zh': '雖然不準確,但似乎是確定的。',
              'en': "It's not exact, but it seems certain.",
              'ja': '正確ではないが確かなようだ。'},
  'examples': [{'vi': 'Anh ho nhiều quá. Chắc là anh bị cảm, phải không?',
                'kr': {'ko': '당신은 기침을 매우 많이 하네요. 확실히 감기 걸린 것 맞죠?',
                       'zh': '您咳嗽得很厲害呢。肯定是感冒了對吧？',
                       'en': "You're coughing a lot. You definitely have a cold, right?",
                       'ja': 'あなたはとてもたくさん咳をしていますね。確かに風邪をひいたんですよね？'}},
               {'vi': 'Nhanh lên. chắc là mọi người đang đợi chúng ta.',
                'kr': {'ko': '빨리. 확실히 모든 사람들이 우리를 기다리고 있을 거야.',
                       'zh': '快點。大家肯定都在等我們。',
                       'en': 'Hurry up. Everyone must be waiting for us.',
                       'ja': '急いで。きっとみんなが私たちを待っているよ。'}}]},
 {'headword': 'chỉ…(A) mà…(B)',
  'pos': None,
  'meaning': {'ko': '이 구문은 A 와 B 간의 모순성 또는 비상관성을 나타냄.',
              'zh': '此句型表示A與B之間的矛盾性或不相關性。',
              'en': 'This construction expresses contradiction or lack of correlation between A and B.',
              'ja': 'この構文はAとBの間の矛盾性または無関係性を表す。'},
  'examples': [{'vi': 'Chỉ có một tháng mà làm xong nhà.',
                'kr': {'ko': '단지 한 달 만에 집을 다 지었다.',
                       'zh': '僅用一個月就把房子蓋好了。',
                       'en': 'The house was completely built in just one month.',
                       'ja': 'たった一か月で家を建て終えた。'}},
               {'vi': 'Chỉ ăn rau mà không đủ tiền.',
                'kr': {'ko': '단지 야채만 먹었는데 돈이 부족했다.',
                       'zh': '只吃了蔬菜，錢還是不夠。',
                       'en': "I only ate vegetables, but I still didn't have enough money.",
                       'ja': '野菜だけ食べたのに、お金が足りなかった。'}}]},
 {'headword': 'cho thêm … nữa',
  'pos': None,
  'meaning': {'ko': '~을 더 추가해 주세요. 무엇인가를 보충해 줄 것을 요구하기 위해 사용하는 표현.)',
              'zh': '請再加~。（用於要求補充某物的表達方式。）',
              'en': 'Please add more ~. (An expression used to ask for something to be added/supplemented.)',
              'ja': '~をもっと追加してください。（何かを補充してもらうよう要求するために使う表現。）'},
  'examples': [{'vi': 'Yêu cầu gia hạn cho thêm 1 năm nữa.',
                'kr': {'ko': '1년을 더 연장해 줄 것을 요구한다.',
                       'zh': '要求再延長一年。',
                       'en': 'Requests that it be extended by one more year.',
                       'ja': 'もう1年延長してくれるよう要求する。'}},
               {'vi': 'Đề nghị cho thêm 10 sinh viên nữa đi Việt Nam.',
                'kr': {'ko': '10명의 학생이 더 베트남에 가도록 제의하다.',
                       'zh': '提議再讓10名學生去越南。',
                       'en': 'Proposes that 10 more students go to Vietnam.',
                       'ja': 'さらに10人の学生がベトナムに行くよう提案する。'}}]},
 {'headword': 'chưa … gì (cả)',
  'pos': None,
  'meaning': {'ko': '이 구문은 부정적인 의미나 절대적 부정을 강조하기 위해 사용됨.',
              'zh': '此句型用於強調否定意義或絕對否定。',
              'en': 'This construction is used to emphasize a negative meaning or absolute negation.',
              'ja': 'この構文は否定的な意味や絶対的否定を強調するために使われる。'},
  'examples': [{'vi': 'Tôi chưa uống gì, chưa tiêm gì cả.',
                'kr': {'ko': '저는 어떤 약을 먹거나 주사를 맞지 않았습니다.',
                       'zh': '我沒有吃任何藥,也沒有打針。',
                       'en': "I haven't taken any medicine or had any injections.",
                       'ja': '私はどんな薬も飲んでいませんし、注射も打っていません。'}},
               {'vi': 'Anh đã gặp ai chưa? Tôi không gặp ai cả.',
                'kr': {'ko': '당신은 누구를 만난 적이 있습니까? 저는 아무도 만나지 않았습니다.',
                       'zh': '您見過誰嗎？我誰也沒見過。',
                       'en': "Have you met anyone? I haven't met anyone.",
                       'ja': 'あなたは誰かに会ったことがありますか？私は誰にも会っていません。'}}]},
 {'headword': 'có … nào … hơn không?',
  'pos': None,
  'meaning': {'ko': '이 구문은 선택을 요구하는 질문인데 nào 앞에는 명사 또는 지시 형용사 등이 놓이고 nào 뒤에는 형용사가 있어야 함.',
              'zh': '此句型是要求做出選擇的疑問句,nào前面要放名詞或指示形容詞,nào後面必須有形容詞。',
              'en': 'This construction is a question requiring a choice; a noun or demonstrative adjective '
                    'is placed before "nào", and an adjective must follow "nào".',
              'ja': 'この構文は選択を求める疑問文で、nàoの前には名詞または指示形容詞などが置かれ、nàoの後には形容詞がなければならない。'},
  'examples': [{'vi': 'Có cái bút nào đẹp hơn không?',
                'kr': {'ko': '더 예쁜 펜이 있나요?',
                       'zh': '有更漂亮的筆嗎？',
                       'en': 'Are there prettier pens?',
                       'ja': 'もっときれいなペンはありますか？'}},
               {'vi': 'Có đôi giày nào rẻ hơn không?',
                'kr': {'ko': '더 싼 신발이 있나요?',
                       'zh': '有更便宜的鞋子嗎？',
                       'en': 'Are there cheaper shoes?',
                       'ja': 'もっと安い靴はありますか？'}}]},
 {'headword': 'có thể … được không?',
  'pos': None,
  'meaning': {'ko': '이 구문은 행동 또는 요구, 제안, 허락의 가능성을 묻는 의문문에서 사용됨.',
              'zh': '此句型用於詢問行動、要求、建議或許可的可能性的疑問句中。',
              'en': 'This construction is used in questions asking about the possibility of an action, '
                    'request, suggestion, or permission.',
              'ja': 'この構文は行動または要求、提案、許可の可能性を尋ねる疑問文で使われる。'},
  'examples': [{'vi': 'Tôi có thể ngủ ở đây được không?',
                'kr': {'ko': '나는 여기서 잘 수 있습니까?',
                       'zh': '我可以在這裡睡覺嗎?',
                       'en': 'Can I sleep here?',
                       'ja': '私はここで寝てもいいですか?'}},
               {'vi': 'Tôi có thể vào được không?',
                'kr': {'ko': '내가 들어갈 수 있습니까?',
                       'zh': '我可以進去嗎?',
                       'en': 'May I come in?',
                       'ja': '私は入ってもいいですか?'}}]},
 {'headword': 'cũng như …',
  'pos': None,
  'meaning': {'ko': '비교 구문에 사용함.',
              'zh': '用於比較句型。',
              'en': 'Used in comparative constructions.',
              'ja': '比較構文に使用します。'},
  'examples': [{'vi': 'Người Hàn Quốc cũng giống như người Việt Nam.',
                'kr': {'ko': '한국 사람은 베트남 사람과 비슷하다.',
                       'zh': '韓國人和越南人相似。',
                       'en': 'Korean people are similar to Vietnamese people.',
                       'ja': '韓国人はベトナム人と似ている。'}},
               {'vi': 'Món ăn Hàn Quốc cũng như món ăn Việt Nam.',
                'kr': {'ko': '한국 음식은 베트남 음식과 비슷하다.',
                       'zh': '韓國料理和越南料理相似。',
                       'en': 'Korean food is similar to Vietnamese food.',
                       'ja': '韓国料理はベトナム料理と似ている。'}}]},
 {'headword': 'dù … (cũng/nhưng) …',
  'pos': None,
  'meaning': {'ko': '비록 …이지만, …라 하더라도 (예상과 다른 결과가 뒤따름을 나타냄.)',
              'zh': '雖然……（表示儘管如此，結果卻出乎意料。）',
              'en': 'Even though …, although … (Used to show a result contrary to what might be expected.)',
              'ja': 'たとえ…でも、…としても（予想に反する結果が続くことを表す。）'},
  'examples': [{'vi': 'Dù người Ga-ba-ôn đã lừa dối dân Y-sơ-ra-ên, nhưng dân Y-sơ-ra-ên vẫn giữ lời hứa với họ.',
                'kr': {'ko': '기브온 사람들이 이스라엘 백성을 속였지만, 이스라엘 백성은 그들과 한 약속을 계속 지켰다.',
                       'zh': '雖然基遍人欺騙了以色列人，以色列人還是遵守了跟他們立下的承諾。',
                       'en': 'Although the Gibeonites had deceived the Israelites, the Israelites still kept their promise to them.',
                       'ja': 'ギベオン人はイスラエル人をだましたが、イスラエル人は彼らとの約束を守り続けた。'}},
               {'vi': 'Dù bị đối xử bất công, chúng ta có thể kiên nhẫn chờ đợi Đức Giê-hô-va sửa lại mọi điều đúng lúc.',
                'kr': {'ko': '불공정한 대우를 받더라도, 우리는 여호와께서 때가 되면 모든 것을 바로잡아 주실 것을 참을성 있게 기다릴 수 있다.',
                       'zh': '即使受到不公平的對待，我們也可以耐心地等候耶和華在適當的時候糾正一切。',
                       'en': 'Even when treated unjustly, we can patiently wait for Jehovah to correct everything in due time.',
                       'ja': 'たとえ不当な扱いを受けても、わたしたちはエホバが時が来れば全てを正してくださることを忍耐強く待つことができる。'}}]},
 {'headword': 'đã./ … bao giờ chưa / đã bao giờ … chưa',
  'pos': None,
  'meaning': {'ko': '언제 … 한 적 있습니까? (태어나서 지금까지) Đã 는 없어도 됨.',
              'zh': '曾經…過嗎？（從出生到現在）可以不加 Đã。',
              'en': 'Have you ever ...? (from birth until now) "Đã" can be omitted.',
              'ja': '今まで…したことがありますか？（生まれてから今まで）Đãはなくても構いません。'},
  'examples': [{'vi': 'Anh đã gặp cô ấy bao giờ chưa?',
                'kr': {'ko': '당신은 그녀를 만난 적 있습니까?',
                       'zh': '您見過她嗎？',
                       'en': 'Have you ever met her?',
                       'ja': 'あなたは彼女に会ったことがありますか？'}},
               {'vi': 'Anh đã bao giờ đi Hà Nội chưa?',
                'kr': {'ko': '당신은 하노이에 간 적 있습니까?',
                       'zh': '您去過河內嗎？',
                       'en': 'Have you ever been to Hanoi?',
                       'ja': 'あなたはハノイに行ったことがありますか？'}}]},
 {'headword': 'đã … chưa',
  'pos': None,
  'meaning': {'ko': '문장 끝 위치 : ~했습니까? (시간적개념 의문문)/ 동사앞 위치 : 아직 ~ 않다.(시간적개념 부정문)',
              'zh': '位於句末：~了嗎？（時間概念疑問句）/ 位於動詞前：還沒~。（時間概念否定句）',
              'en': 'At the end of a sentence: Have you ~? (a time-concept question) / Before the verb: not '
                    'yet ~. (a time-concept negative)',
              'ja': '文末の位置：～しましたか？（時間概念の疑問文）／動詞前の位置：まだ～ない。（時間概念の否定文）'},
  'examples': [{'vi': 'Cô đã ăn cơm chưa? - Rồi, tôi đã ăn cơm rồi.',
                'kr': {'ko': '아가씨 밥 먹었습니까? -네, 저는 밥 먹었습니다.',
                       'zh': '小姐，你吃飯了嗎？－是的，我吃過飯了。',
                       'en': 'Miss, have you eaten? — Yes, I have eaten.',
                       'ja': 'お嬢さん、ご飯を食べましたか。－はい、食べました。'}},
               {'vi': 'Anh ấy (đã) có gia đình chưa? - Chưa, anh ấy chưa có gia đình.',
                'kr': {'ko': '그는 결혼했습니까? -아니요, 그는 아직 결혼하지 않았습니다.',
                       'zh': '他結婚了嗎?——不,他還沒有結婚。',
                       'en': 'Is he married? - No, he is not married yet.',
                       'ja': '彼は結婚していますか?―いいえ、彼はまだ結婚していません。'}}]},
 {'headword': 'đến … để …',
  'pos': None,
  'meaning': {'ko': '… 을 하기 위해 … 에 도착하다.',
              'zh': '為了做…而到達…。',
              'en': 'arrive at … in order to do ….',
              'ja': '…をするために…に到着する。'},
  'examples': [{'vi': 'Tôi đến đây để gặp anh.',
                'kr': {'ko': '나는 당신을 만나기 위해 이곳에 왔다.',
                       'zh': '我為了見您來到了這裡。',
                       'en': 'I came here to meet you.',
                       'ja': '私はあなたに会うためにここに来た。'}},
               {'vi': 'Tôi đến để mời anh.',
                'kr': {'ko': '나는 당신을 초청하기 위해 왔다.',
                       'zh': '我是來邀請您的。',
                       'en': 'I came to invite you.',
                       'ja': '私はあなたを招待するために来た。'}}]},
 {'headword': 'đổi …(1) … để lấy …',
  'pos': None,
  'meaning': {'ko': '각 명사와 함께 사용하여 서로 교환하고자 할 때 사용함.',
              'zh': '與各個名詞一起使用，用於表示彼此交換的時候。',
              'en': 'Used together with each noun when expressing an exchange between them.',
              'ja': 'それぞれの名詞と一緒に使い、互いに交換しようとするときに使用します。'},
  'examples': [{'vi': 'Tôi muốn đổi đô la để lấy tiền Việt.',
                'kr': {'ko': '나는 달러를 바꿔서 베트남 동을 받고 싶다.',
                       'zh': '我想把美元換成越南盾。',
                       'en': 'I want to exchange dollars for Vietnamese dong.',
                       'ja': '私はドルを両替してベトナムドンをもらいたい。'}},
               {'vi': 'Tôi muốn đổi tiền đô la để lấy tiền Won(tiền Hàn Quốc).',
                'kr': {'ko': '나는 달러를 바꿔서 (한국 돈)원화를 받고 싶다.',
                       'zh': '我想把美元換成(韓幣)韓元。',
                       'en': 'I want to exchange dollars for (Korean money) won.',
                       'ja': '私はドルを両替して(韓国のお金)ウォンをもらいたい。'}}]},
 {'headword': 'đối với … (1)thì …(2) là …',
  'pos': None,
  'meaning': {'ko': '어떤 일에 관한 어떤 사람의 가능성과 태도 등에 대해 평가하기 위해 사용됨.',
              'zh': '用於評價某人對某件事的可能性、態度等。',
              'en': "Used to evaluate a person's ability, attitude, etc., regarding a certain matter.",
              'ja': 'ある事柄に関するある人の可能性や態度などを評価するために使用されます。'},
  'examples': [{'vi': 'Đối với tôi thì vấn đề này rất đơn giản.',
                'kr': {'ko': '나에게 있어 이 문제는 매우 간단하다.',
                       'zh': '對我來說,這個問題非常簡單。',
                       'en': 'For me, this problem is very simple.',
                       'ja': '私にとってこの問題はとても簡単だ。'}},
               {'vi': 'Đối với anh ấy việc học tập là quan trọng nhất.',
                'kr': {'ko': '그에게 공부는 가장 중요하다.',
                       'zh': '對他來說,學習是最重要的。',
                       'en': 'To him, studying is the most important thing.',
                       'ja': '彼にとって勉強が最も重要だ。'}}]},
 {'headword': 'đồng ý',
  'pos': None,
  'meaning': {'ko': '동의하다.(찬성의 뜻을 나타냄.)',
              'zh': '同意。（表示贊成的意思。）',
              'en': 'To agree. (Expresses approval.)',
              'ja': '同意する。（賛成の意を表す。）'},
  'examples': [{'vi': 'Tôi đồng ý.',
                'kr': {'ko': '나는 동의 한다.', 'zh': '我同意。', 'en': 'I agree.', 'ja': '私は同意する。'}},
               {'vi': 'Tôi đồng ý với anh về vấn đề này.',
                'kr': {'ko': '나는 이 문제에 대해 당신에게 동의한다.',
                       'zh': '關於這個問題,我同意您的看法。',
                       'en': 'I agree with you on this issue.',
                       'ja': '私はこの問題についてあなたに同意する。'}}]},
 {'headword': 'gì … cũng',
  'pos': None,
  'meaning': {'ko': '(Nào … cũng) 비슷하지만 범위가 더 크고 아직 모르는 상태에서 사용함.',
              'zh': '(Nào … cũng) 意思類似，但範圍更大，在尚不清楚的狀態下使用。',
              'en': "(Nào … cũng) is similar, but the scope is broader and it's used when the specifics are "
                    'still unknown.',
              'ja': '(Nào … cũng) は似ていますが、範囲がより広く、まだわからない状態で使用します。'},
  'examples': [{'vi': 'Việc gì anh ấy cũng biết.',
                'kr': {'ko': '그는 무슨 일이든 알고 있다.',
                       'zh': '他什麼事都知道。',
                       'en': 'He knows anything (everything).',
                       'ja': '彼はどんなことでも知っている。'}},
               {'vi': 'Món gì anh ấy cũng ăn được.',
                'kr': {'ko': '그는 무슨 요리든 먹을 수 있다.',
                       'zh': '他什麼菜都能吃。',
                       'en': 'He can eat any dish.',
                       'ja': '彼はどんな料理でも食べられる。'}},
               {'vi': 'Cô ấy nấu món gì cũng ngon.',
                'kr': {'ko': '그녀가 하는 어떤 요리든 맛있다.',
                       'zh': '她做的任何菜都很好吃。',
                       'en': 'Whatever dish she makes is delicious.',
                       'ja': '彼女が作るどんな料理もおいしい。'}}]},
 {'headword': 'giúp…(ai)…làm gì',
  'pos': None,
  'meaning': {'ko': '(누가) 무엇을 하도록 돕다. (상대방이 어떤 행동·상태에 이르도록 도와줄 때 사용.)',
              'zh': '幫助（某人）做某事。（用於幫助對方達到某種行為或狀態時。）',
              'en': 'To help (someone) do something. (Used when helping the other person reach some action or '
                    'state.)',
              'ja': '（誰かが）何かをするのを助ける。（相手がある行動や状態に至るのを助けるときに使用。）'},
  'examples': [{'vi': 'Làm sao để giúp học viên hiểu rõ về Đức Giê-hô-va?',
                'kr': {'ko': '연구생이 여호와를 정확히 알도록 어떻게 도울 수 있을까?',
                       'zh': '要怎麼幫助學員確切認識耶和華呢?',
                       'en': 'How can we help the student come to know Jehovah accurately?',
                       'ja': 'どうすればレッスン生がエホバのことを正確に知るのを助けられるだろうか。'}},
               {'vi': 'Câu hỏi hay giúp anh ấy suy ngẫm sâu hơn về nguyên tắc Kinh Thánh.',
                'kr': {'ko': '좋은 질문은 그가 성경 원칙에 대해 더 깊이 숙고하도록 도와준다.',
                       'zh': '好的問題能幫助他更深入地思考聖經原則。',
                       'en': 'A good question helps him reflect more deeply on the Bible principle.',
                       'ja': '良い質問は，彼が聖書の原則についてより深く考える助けになる。'}}]},
 {'headword': 'hình như',
  'pos': None,
  'meaning': {'ko': '마치 ~ 인것 같다.', 'zh': '好像~一樣。', 'en': 'It seems as if ~.', 'ja': 'まるで～のようだ。'},
  'examples': [{'vi': 'Hình như ông ấy đi về nhà rồi.',
                'kr': {'ko': '그분은 집에 돌아간 것 같다.',
                       'zh': '那位好像回家了。',
                       'en': 'It seems that he/she has gone back home.',
                       'ja': 'その方は家に帰ったようだ。'}},
               {'vi': 'Cô ấy hình như không muốn gặp tôi.',
                'kr': {'ko': '그녀는 나를 만나는 것을 원하지 않는 것 같다.',
                       'zh': '她好像不想見我。',
                       'en': "It seems she doesn't want to meet me.",
                       'ja': '彼女は私に会いたくないようだ。'}}]},
 {'headword': 'không còn … nữa',
  'pos': None,
  'meaning': {'ko': '더 이상 …하지 않다, 이제 …이 아니다 (예전에는 그랬지만 지금은 상태가 바뀌었음을 나타냄.)',
              'zh': '不再……了（表示以前如此，但現在情況已經改變。）',
              'en': 'No longer …, not … anymore (Used to show that something used to be the case but is not now.)',
              'ja': 'もう…ない、もはや…ではない（以前はそうだったが今は状態が変わったことを表す。）'},
  'examples': [{'vi': 'Nhờ đọc sách Ê-sai, chị ấy không còn cảm thấy cô đơn nữa.',
                'kr': {'ko': '이사야서를 읽은 덕분에, 그 자매는 더 이상 외로움을 느끼지 않게 되었다.',
                       'zh': '由於閱讀了以賽亞書，那位姐妹不再感到孤單了。',
                       'en': 'Thanks to reading the book of Isaiah, the sister no longer felt lonely.',
                       'ja': 'イザヤ書を読んだおかげで、その姉妹はもう孤独を感じなくなった。'}},
               {'vi': 'Khi Đức Giê-hô-va tha thứ, ngài không còn nhớ đến tội lỗi của chúng ta nữa.',
                'kr': {'ko': '여호와께서 용서하실 때, 그분은 우리의 죄를 더 이상 기억하지 않으신다.',
                       'zh': '耶和華寬恕的時候，他不再記得我們的罪了。',
                       'en': 'When Jehovah forgives, he no longer remembers our sins.',
                       'ja': 'エホバが許してくださるとき，もうわたしたちの罪を思い出されない。'}}]},
 {'headword': 'không … gì',
  'pos': None,
  'meaning': {'ko': '의견을 완벽하게 부정하기 위해 사용함.',
              'zh': '用於完全否定意見。',
              'en': 'Used to completely negate an opinion.',
              'ja': '意見を完全に否定するために使用します。'},
  'examples': [{'vi': 'Tôi không biết gì về ông ta.',
                'kr': {'ko': '나는 그분에 관해 아무것도 알지 못한다.',
                       'zh': '我對那位一無所知。',
                       'en': "I don't know anything about that person.",
                       'ja': '私はその方について何も知らない。'}},
               {'vi': 'Cô ấy không nói gì về việc đó.',
                'kr': {'ko': '그녀는 그 일에 관해서 아무것도 말하지 않았다.',
                       'zh': '她對那件事什麼都沒說。',
                       'en': 'She said nothing about that matter.',
                       'ja': '彼女はそのことについて何も言わなかった。'}}]},
 {'headword': 'không … gì cả',
  'pos': None,
  'meaning': {'ko': '이 구문은 동사 또는 형용사와 함께 사용되어 부정을 강조함.',
              'zh': '此句型與動詞或形容詞一起使用,強調否定。',
              'en': 'This construction is used with a verb or adjective to emphasize negation.',
              'ja': 'この構文は動詞または形容詞と共に使われ、否定を強調する。'},
  'examples': [{'vi': 'Anh ấy không nói gì cả.',
                'kr': {'ko': '그는 아무것도 말하지 않습니다.',
                       'zh': '他什麼也不說。',
                       'en': "He doesn't say anything.",
                       'ja': '彼は何も言いません。'}},
               {'vi': 'Cô ấy không đẹp gì cả.',
                'kr': {'ko': '그녀는 조금도 예쁘지 않습니다.',
                       'zh': '她一點也不漂亮。',
                       'en': 'She is not pretty at all.',
                       'ja': '彼女は少しもきれいではありません。'}}]},
 {'headword': 'không …… đâu',
  'pos': None,
  'meaning': {'ko': '~가 아니다. (부정을 강조하기 위해 사용)',
              'zh': '不是~。（用於強調否定）',
              'en': 'not ~. (Used to emphasize negation)',
              'ja': '~ではない。（否定を強調するために使用）'},
  'examples': [{'vi': 'Anh ấy không đến đâu.',
                'kr': {'ko': '그는 오지 않았다.', 'zh': '他沒有來。', 'en': "He didn't come.", 'ja': '彼は来なかった。'}},
               {'vi': 'Không xa lắm đâu.',
                'kr': {'ko': '멀지 않다.', 'zh': '不遠。', 'en': "It's not far.", 'ja': '遠くない。'}}]},
 {'headword': 'không được …',
  'pos': None,
  'meaning': {'ko': '이 구문은 동사 앞에 위치하여 억제 또는 불가능한 뜻을 나타냄.',
              'zh': '此句型位於動詞前,表示抑制或不可能的意思。',
              'en': 'This construction is placed before a verb to express restraint or impossibility.',
              'ja': 'この構文は動詞の前に置かれ、抑制または不可能の意味を表す。'},
  'examples': [{'vi': 'Ở đây không được hút thuốc lá.',
                'kr': {'ko': '여기서는 담배를 피울 수 없습니다.',
                       'zh': '這裡不能抽菸。',
                       'en': 'You cannot smoke here.',
                       'ja': 'ここではタバコを吸うことができません。'}},
               {'vi': 'Anh không được nói với ai cả.',
                'kr': {'ko': '당신은 누구와도 말할 수 없습니다.',
                       'zh': '您不能和任何人說話。',
                       'en': 'You cannot talk to anyone.',
                       'ja': 'あなたは誰とも話すことができません。'}}]},
 {'headword': 'không những … mà còn …',
  'pos': None,
  'meaning': {'ko': '~뿐만 아니라 ~ 이기도 하다.',
              'zh': '不僅~，還~。',
              'en': 'Not only ~, but also ~.',
              'ja': '~だけでなく~でもある。'},
  'examples': [{'vi': 'Anh ấy không những mua nhà mà còn mua xe hơi nữa.',
                'kr': {'ko': '그는 집을 샀을 뿐만 아니라 차도 샀다.',
                       'zh': '他不僅買了房子,還買了車。',
                       'en': 'He not only bought a house but also a car.',
                       'ja': '彼は家を買っただけでなく、車も買った。'}},
               {'vi': 'Cô ấy không chỉ thông minh mà còn chăm chỉ nữa.',
                'kr': {'ko': '그녀는 똑똑할 뿐만 아니라 열심히 한다.',
                       'zh': '她不僅聰明,而且很努力。',
                       'en': 'She is not only smart but also hardworking.',
                       'ja': '彼女は賢いだけでなく、一生懸命だ。'}}]},
 {'headword': 'làm ơn … giúp(hộ,giùm) …',
  'pos': None,
  'meaning': {'ko': '이 구문은 누군가의 도움에 힘입을 때 사용하는 공손한 표현법임.',
              'zh': '此句型是在依靠某人的幫助時使用的禮貌表達方式。',
              'en': "This is a polite expression used when relying on someone's help.",
              'ja': 'この構文は誰かの助けを借りるときに使う丁寧な表現法である。'},
  'examples': [{'vi': 'Anh làm ơn gọi cảnh sát giúp tôi.',
                'kr': {'ko': '저에게 경찰을 불러 주세요.',
                       'zh': '請幫我叫警察。',
                       'en': 'Please call the police for me.',
                       'ja': '私に警察を呼んでください。'}},
               {'vi': 'Anh làm ơn mở giúp cái khóa.',
                'kr': {'ko': '자물쇠를 여는데 도와주세요.',
                       'zh': '請幫我開鎖。',
                       'en': 'Please help me open the lock.',
                       'ja': '錠を開けるのを手伝ってください。'}}]},
 {'headword': 'mời…(ai)…làm gì',
  'pos': None,
  'meaning': {'ko': '(누가)무엇을 하기를 청하다. (상대방에게 어떤 행동을 할 것을 청할 때 사용.)',
              'zh': '請求（某人）做某事。（用於請求對方做某種行為時。）',
              'en': 'To ask (someone) to do something. (Used when requesting the other person to do some '
                    'action.)',
              'ja': '（誰かに）何かをするよう頼む。（相手にある行動をするよう頼むときに使用。）'},
  'examples': [{'vi': 'Mời anh vào nhà!',
                'kr': {'ko': '집안으로 들어오세요!',
                       'zh': '請進屋裡來!',
                       'en': 'Please come inside the house!',
                       'ja': '家の中にお入りください!'}},
               {'vi': 'Mời ông uống cà phê ạ!',
                'kr': {'ko': '커피 드세요!',
                       'zh': '請喝咖啡!',
                       'en': 'Please have some coffee!',
                       'ja': 'コーヒーをどうぞ!'}}]},
 {'headword': 'muốn … cần …',
  'pos': None,
  'meaning': {'ko': '동사 앞에 위치하여 주어의 요구나 소망을 나타냄.',
              'zh': '位於動詞前面，表示主語的要求或願望。',
              'en': "Placed before a verb, expressing the subject's request or wish.",
              'ja': '動詞の前に位置して、主語の要求や願望を表す。'},
  'examples': [{'vi': 'Tôi cần đổi tiền.',
                'kr': {'ko': '나는 환전하고자 한다.',
                       'zh': '我打算換錢。',
                       'en': 'I intend to exchange currency.',
                       'ja': '私は両替をしようと思う。'}},
               {'vi': 'Tôi muốn đổi tiền.',
                'kr': {'ko': '나는 환전하고 싶다.',
                       'zh': '我想換錢。',
                       'en': 'I want to exchange currency.',
                       'ja': '私は両替をしたい。'}}]},
 {'headword': 'muốn … thì(phải) …',
  'pos': None,
  'meaning': {'ko': '~을 원한다면 ~해야만 한다. (목적과 행동사이의 긴밀한 관계를 나타내기 위한 표현.)',
              'zh': '如果想要~，就必須~。（用於表示目的與行動之間緊密關係的表達方式。）',
              'en': 'If you want ~, you must ~. (An expression showing a close relationship between a '
                    'purpose and an action.)',
              'ja': '~を望むなら~しなければならない。（目的と行動の間の緊密な関係を表すための表現。）'},
  'examples': [{'vi': 'Muốn giỏi thì phải học.',
                'kr': {'ko': '잘하기를 원하면 공부해야만 한다.',
                       'zh': '如果想做得好,就必須學習。',
                       'en': 'If you want to do well, you must study.',
                       'ja': '上手になりたいなら勉強しなければならない。'}},
               {'vi': 'Muốn ăn thì lăn vào bếp.',
                'kr': {'ko': '먹고 싶으면 부엌으로 들어가라.',
                       'zh': '想吃的話就進廚房去。',
                       'en': 'If you want to eat, go into the kitchen.',
                       'ja': '食べたければ台所に入りなさい。'}}]},
 {'headword': 'muốn biết … thế nào?',
  'pos': None,
  'meaning': {'ko': '… 이 어떤지 알고 싶다. (간접적으로 질문하는 의문문 표현.)',
              'zh': '想知道…怎麼樣。（間接提問的疑問句表達方式。）',
              'en': 'want to know how … is. (An indirect question expression.)',
              'ja': '…がどうなのか知りたい。（間接的に質問する疑問文の表現。）'},
  'examples': [{'vi': 'Tôi muốn biết khí hậu và thời tiết bây giờ thế nào.',
                'kr': {'ko': '나는 지금 기후와 날씨가 어떤지 알고 싶습니다.',
                       'zh': '我現在想知道氣候和天氣怎麼樣。',
                       'en': 'I want to know what the climate and weather are like now.',
                       'ja': '私は今、気候と天気がどうなのか知りたいです。'}},
               {'vi': 'Anh ấy muốn biết công việc của chị hiện nay thế nào.',
                'kr': {'ko': '그는 그녀의 일이 현재 어떤지 알고 싶습니다.',
                       'zh': '他想知道她現在的工作情況怎麼樣。',
                       'en': 'He wants to know how her work is currently going.',
                       'ja': '彼は彼女の仕事が今どうなのか知りたがっています。'}}]},
 {'headword': 'nào… cũng…/ …nào cũng…',
  'pos': None,
  'meaning': {'ko': 'nào… cũng… 무엇이든…역시/ …nào cũng… 항상 (A주어 B보어 C동사, 형용사)',
              'zh': 'nào… cũng… 無論什麼…也／…nào cũng… 總是（A主語 B補語 C動詞、形容詞）',
              'en': 'nào… cũng… — whatever … also / …nào cũng… always (A subject, B complement, C '
                    'verb/adjective)',
              'ja': 'nào… cũng… 何でも…もまた／…nào cũng… いつも（A主語 B補語 C動詞、形容詞）'},
  'examples': [{'vi': 'Người nào cũng dễ thương.',
                'kr': {'ko': '어떤 사람이든 다 사랑스럽다.',
                       'zh': '不管是誰都很可愛。',
                       'en': 'Anyone at all is lovable.',
                       'ja': 'どんな人でもみんな愛らしい。'}},
               {'vi': 'Tối nào ông ấy cũng uống rượu.',
                'kr': {'ko': '그는 어떤 저녁이든 역시 술을 마신다.',
                       'zh': '無論哪天晚上他都會喝酒。',
                       'en': 'No matter which evening, he drinks alcohol too.',
                       'ja': '彼はどんな夜でもやはり酒を飲む。'}}]},
 {'headword': 'nếu …… thì …',
  'pos': None,
  'meaning': {'ko': '만약 (원인 문장) 그러면 (결과문장)',
              'zh': '如果（原因句）那麼（結果句）',
              'en': 'If (cause clause), then (result clause)',
              'ja': 'もし（原因文）それなら（結果文）'},
  'examples': [{'vi': 'Nếu đi bằng xe lửa thì mất khoảng 12 tiếng.',
                'kr': {'ko': '만약 기차를 타고 간다면 대략 12시간 걸릴 것이다.',
                       'zh': '如果坐火車去的話，大概要花12個小時。',
                       'en': 'If you go by train, it will take about 12 hours.',
                       'ja': 'もし電車に乗って行くなら、およそ12時間かかるでしょう。'}},
               {'vi': 'Nếu có tiền thì tôi sẽ đi du lịch nước ngoài.',
                'kr': {'ko': '만약 돈이 있다면 나는 외국으로 여행갈 것이다.',
                       'zh': '如果有錢的話，我就去國外旅行。',
                       'en': 'If I had money, I would travel abroad.',
                       'ja': 'もしお金があれば、私は外国へ旅行に行くでしょう。'}}]},
 {'headword': 'nếu không có … thì … cũng được',
  'pos': None,
  'meaning': {'ko': '이 구문은 전자가 없으면 후자를 인정한다는 의미를 나타냄.',
              'zh': '此句型表示“若無前者,則承認後者”的意思。',
              'en': 'This construction expresses the meaning that if the former is absent, the latter is '
                    'accepted.',
              'ja': 'この構文は前者がなければ後者を認めるという意味を表す。'},
  'examples': [{'vi': 'Nếu không có màu đen thì màu nâu cũng được.',
                'kr': {'ko': '만약 검은색이 없으면 갈색도 괜찮아요.',
                       'zh': '如果沒有黑色的，棕色的也可以。',
                       'en': "If there's no black, brown is fine too.",
                       'ja': 'もし黒色がなければ、茶色でも大丈夫です。'}},
               {'vi': 'Nếu không có bút bi thì bút chì cũng được.',
                'kr': {'ko': '만약 볼펜이 없으면 연필도 괜찮아요.',
                       'zh': '如果沒有圓珠筆，鉛筆也可以。',
                       'en': "If there's no ballpoint pen, a pencil is fine too.",
                       'ja': 'もしボールペンがなければ、鉛筆でも大丈夫です。'}}]},
 {'headword': 'nghe nói',
  'pos': None,
  'meaning': {'ko': '말하는 것을 듣다.', 'zh': '聽別人說話。', 'en': 'To listen to someone speaking.', 'ja': '話すのを聞く。'},
  'examples': [{'vi': 'Nghe nói vịnh Hạ Long rất đẹp.',
                'kr': {'ko': 'Hạ Long가 매우 아름답다고 들었다.',
                       'zh': '聽說下龍灣（Hạ Long）非常美麗。',
                       'en': 'I heard that Hạ Long is very beautiful.',
                       'ja': 'ハロン（Hạ Long）はとても美しいと聞いた。'}},
               {'vi': 'Tôi nghe nói cô ấy sắp đi du lịch ở Pháp một tháng.',
                'kr': {'ko': '나는 그녀가 프랑스로 한 달간 여행 갈 것이라고 들었다.',
                       'zh': '我聽說她要去法國旅行一個月。',
                       'en': 'I heard that she is going to travel to France for a month.',
                       'ja': '私は彼女がフランスへ1か月間旅行に行くと聞いた。'}}]},
 {'headword': 'nhờ (ai) … giúp đỡ',
  'pos': None,
  'meaning': {'ko': '이 구문은 다른 사람에게 도움을 요청하거나 제안할 때 사용함.',
              'zh': '此句型用於向他人請求幫助或提出建議時。',
              'en': 'This construction is used when asking someone else for help or making a suggestion.',
              'ja': 'この構文は他の人に助けを求めたり、提案したりするときに使う。'},
  'examples': [{'vi': 'Tôi nhờ anh giúp đỡ.',
                'kr': {'ko': '나는 당신이 도와주셨으면 해요.',
                       'zh': '我希望您能幫我。',
                       'en': 'I hope you would help me.',
                       'ja': '私はあなたに助けてほしいです。'}},
               {'vi': 'Anh ấy nhờ chị giúp đỡ.',
                'kr': {'ko': '그는 당신이 도와주셨으면 합니다.',
                       'zh': '他希望您能幫忙。',
                       'en': 'He hopes that you would help.',
                       'ja': '彼はあなたに助けてほしいと思っています。'}}]},
 {'headword': 'nhờ … mà …',
  'pos': None,
  'meaning': {'ko': '~한 덕분에 …하게 되다 (원인·계기와 그로 인한 좋은 결과를 나타냄. 위의 "nhờ (ai) … giúp đỡ"와 달리 사람에게 도움을 청하는 표현이 아니라, 어떤 행동·사건이 원인이 되어 좋은 결과로 이어졌음을 설명할 때 씀.)',
              'zh': '多虧……才……（表示原因、契機以及由此帶來的好結果。與上面的「nhờ (ai) … giúp đỡ」不同，這不是向人求助的說法，而是用來說明某個行動、事件成為原因，進而帶來好結果。）',
              'en': 'Thanks to …, … happens (Shows a cause or occasion and the good result it leads to. Unlike "nhờ (ai) … giúp đỡ" above, this is not about asking a person for help — it explains how some action or event became the cause of a good outcome.)',
              'ja': '～のおかげで…することになる（原因・きっかけと、それによる良い結果を表す。上の「nhờ (ai) … giúp đỡ」とは異なり、人に助けを求める表現ではなく、ある行動や出来事が原因となって良い結果につながったことを説明するときに使う。）'},
  'examples': [{'vi': 'Nhờ đọc Kinh Thánh mỗi ngày mà tôi hiểu rõ hơn về phẩm chất của Đức Giê-hô-va.',
                'kr': {'ko': '매일 성경을 읽은 덕분에, 나는 여호와의 성품을 더 잘 알게 되었다.',
                       'zh': '多虧每天閱讀聖經，我才更清楚知道耶和華的特質。',
                       'en': 'Thanks to reading the Bible every day, I came to know Jehovah\'s qualities better.',
                       'ja': '毎日聖書を読んだおかげで，エホバの特質をもっとよく知るようになった。'}},
               {'vi': 'Nhờ suy ngẫm về công trình sáng tạo mà chúng ta nhận biết được sự khôn ngoan của Đức Giê-hô-va.',
                'kr': {'ko': '창조물에 대해 묵상한 덕분에, 우리는 여호와의 지혜를 알아볼 수 있다.',
                       'zh': '多虧沉思受造物，我們才能認識到耶和華的智慧。',
                       'en': 'Thanks to meditating on the works of creation, we can recognize Jehovah\'s wisdom.',
                       'ja': '創造物について熟考したおかげで，わたしたちはエホバの知恵を認識できる。'}}]},
 {'headword': 'sở dĩ … là vì(là do) …',
  'pos': None,
  'meaning': {'ko': '… 한 이유는 … 때문이다. (결과가 앞에 나오고 원인이 뒤에 위치함.)',
              'zh': '…的原因是因為…。（結果在前，原因在後。）',
              'en': 'The reason … is because …. (The result comes first and the cause comes after.)',
              'ja': '…した理由は…だからだ。（結果が先に来て、原因が後ろに位置する。）'},
  'examples': [{'vi': 'Sở dĩ bạn Minh nghỉ học là vì tưởng hôm đó là Chủ Nhật.',
                'kr': {'ko': 'Minh친구가 학교를 쉰 것은 그날이 일요일이라 생각했기 때문이다.',
                       'zh': 'Minh的朋友沒去上學，是因為以為那天是星期天。',
                       'en': "Minh's friend skipped school because he thought that day was Sunday.",
                       'ja': 'ミンの友達が学校を休んだのは、その日が日曜日だと思ったからだ。'}},
               {'vi': 'Sở dĩ bạn Minh tưởng Chủ Nhật là do bạn Minh say rượu.',
                'kr': {'ko': 'Minh 친구가 일요일이라 생각한 것은 Minh이 술에 취했기 때문이다.',
                       'zh': 'Minh的朋友以為是星期天，是因為Minh喝醉了。',
                       'en': "Minh's friend thought it was Sunday because Minh was drunk.",
                       'ja': 'ミンの友達が日曜日だと思ったのは、ミンが酔っていたからだ。'}}]},
 {'headword': 'tên tôi là …',
  'pos': None,
  'meaning': {'ko': '나의 이름은 … 이다. (자신의 이름을 소개 할 때 사용함.)',
              'zh': '我的名字是……。(用於介紹自己名字時使用。)',
              'en': "My name is …. (Used when introducing one's own name.)",
              'ja': '私の名前は…である。(自分の名前を紹介するときに使う。)'},
  'examples': [{'vi': 'Tên tôi là Hoan Minh.',
                'kr': {'ko': '나의 이름은 Hoan Minh입니다.',
                       'zh': '我的名字是Hoan Minh。',
                       'en': 'My name is Hoan Minh.',
                       'ja': '私の名前はHoan Minhです。'}},
               {'vi': 'Tôi tên là Hoan Minh.',
                'kr': {'ko': '나의 이름은 Hoan Minh입니다.',
                       'zh': '我的名字是Hoan Minh。',
                       'en': 'My name is Hoan Minh.',
                       'ja': '私の名前はHoan Minhです。'}}]},
 {'headword': 'thay vì …',
  'pos': None,
  'meaning': {'ko': '…하는 대신에, …하지 않고 (한 가지 대신 다른 것을 선택함을 나타냄.)',
              'zh': '……而不是……（表示選擇一件事而非另一件事。）',
              'en': 'Instead of …, rather than … (Used to indicate choosing one thing over another.)',
              'ja': '…する代わりに、…ではなく（一つを選んで他のものの代わりにすることを表す。）'},
  'examples': [{'vi': 'Thay vì trình bày thông tin chung chung, hãy dùng Kinh Thánh để khích lệ và đưa ra gợi ý cụ thể.',
                'kr': {'ko': '일반적인 정보를 제시하는 대신, 성경을 사용해 격려하고 구체적인 제안을 하십시오.',
                       'zh': '與其講一些籠統的資訊，不如運用聖經來鼓勵並提出具體的建議。',
                       'en': 'Instead of presenting general information, use the Bible to encourage and give specific suggestions.',
                       'ja': '一般的な情報を伝える代わりに、聖書を用いて励まし、具体的な提案をしてください。'}},
               {'vi': 'Khi anh nói một cách tự nhiên thay vì viết ra từng từ rồi đọc, cử tọa sẽ dễ tập trung và hiểu thông tin hơn.',
                'kr': {'ko': '원고를 한 자 한 자 적어서 읽는 대신 자연스럽게 말하면, 청중이 더 쉽게 집중하고 내용을 이해할 수 있습니다.',
                       'zh': '與其把講稿逐字寫下來讀出，不如自然地說話，這樣聽眾會更容易專心並理解內容。',
                       'en': 'When you speak naturally instead of writing out every word and reading it, the audience will find it easier to concentrate and understand the information.',
                       'ja': '一語一語書き出して読む代わりに自然に話せば、聴衆はもっと集中しやすく、内容も理解しやすくなります。'}}]},
 {'headword': 'thấy … thế nào?',
  'pos': None,
  'meaning': {'ko': '이 구문은 어떤 것에 대한 의견을 물을 때 사용함.',
              'zh': '此句型用於詢問對某事的意見時。',
              'en': 'This construction is used when asking for an opinion about something.',
              'ja': 'この構文は何かについての意見を尋ねるときに使う。'},
  'examples': [{'vi': 'Anh thấy chị ấy dạo này thế nào?',
                'kr': {'ko': '당신은 그녀가 요즘 어떻다고 생각합니까?',
                       'zh': '您覺得她最近怎麼樣？',
                       'en': 'What do you think she is like these days?',
                       'ja': 'あなたは彼女が最近どうだと思いますか？'}},
               {'vi': 'Ông thấy sức khoẻ của ông như thế nào?',
                'kr': {'ko': '당신은 자신의 건강이 어떻다고 느끼십니까?',
                       'zh': '您覺得自己的健康狀況怎麼樣？',
                       'en': 'How do you feel about your own health?',
                       'ja': 'あなたはご自分の健康がどうだと感じていますか？'}}]},
 {'headword': 'thì … thì',
  'pos': None,
  'meaning': {'ko': 'Thì A thì B : A와 B 문장(내용)이 반대되는 것이 옴./ ~는 좋은데 ~는 나쁘다.',
              'zh': 'Thì A thì B：A和B兩句（內容）相反。／~好，但~不好。',
              'en': 'Thì A thì B: A and B (their content) are opposite. / ~ is good, but ~ is bad.',
              'ja': 'Thì A thì B：AとBの文（内容）が反対になる。／~は良いが~は悪い。'},
  'examples': [{'vi': 'Phòng ăn thì quá hẹp, phòng tắm thì quá rộng.',
                'kr': {'ko': '주방은 매우 좁고 욕실은 매우 넓다.',
                       'zh': '廚房很窄,浴室很寬敞。',
                       'en': 'The kitchen is very narrow and the bathroom is very spacious.',
                       'ja': '台所はとても狭く、浴室はとても広い。'}},
               {'vi': 'Vợ thì chăm, chồng thì lười.',
                'kr': {'ko': '아내는 부지런하고 남편은 게으르다.',
                       'zh': '妻子勤勞，丈夫懶惰。',
                       'en': 'The wife is diligent, and the husband is lazy.',
                       'ja': '妻は勤勉で、夫は怠け者だ。'}}]},
 {'headword': 'thử xem / Thử … xem',
  'pos': None,
  'meaning': {'ko': "'시험 삼아 해 보다'의 의미임.",
              'zh': "意思是'試著做做看'。",
              'en': "It means 'to try doing something (as a trial)'.",
              'ja': '「試しにやってみる」という意味です。'},
  'examples': [{'vi': 'Ăn thử xem.',
                'kr': {'ko': '한 번 맛보세요(시험 삼아 드셔보세요).',
                       'zh': '請嘗一嘗(試著吃一下)。',
                       'en': 'Please have a taste (try it once).',
                       'ja': '一度味見してみてください(試しに召し上がってみてください)。'}},
               {'vi': 'Làm thử mấy việc này xem.',
                'kr': {'ko': '이 몇 가지 일들을 시험 삼아 해보세요.',
                       'zh': '請試著做一下這幾件事。',
                       'en': 'Please try doing these few things.',
                       'ja': 'これらいくつかのことを試しにやってみてください。'}}]},
 {'headword': 'tương đối …',
  'pos': None,
  'meaning': {'ko': '이 단어는 형용사 앞에 위치하여 그 정도를 나타냄.',
              'zh': '此詞位於形容詞前,表示其程度。',
              'en': 'This word is placed before an adjective to indicate its degree.',
              'ja': 'この単語は形容詞の前に置かれ、その程度を表す。'},
  'examples': [{'vi': 'Thầy giáo tương đối đẹp trai.',
                'kr': {'ko': '선생님은 상대적으로 볼 때 미남이셔.',
                       'zh': '相對來說，老師算是帥的。',
                       'en': 'Relatively speaking, the teacher is handsome.',
                       'ja': '相対的に見ると、先生はハンサムです。'}},
               {'vi': 'Thầy giáo rất đẹp trai.',
                'kr': {'ko': '선생님은 굉장히 미남이셔.',
                       'zh': '老師非常帥。',
                       'en': 'The teacher is very handsome.',
                       'ja': '先生はとてもハンサムです。'}}]},
 {'headword': 'tuy … nhưng',
  'pos': None,
  'meaning': {'ko': 'Tuy A nhưng B : A에도 불구하고 B/ 비록A 일지라도 B',
              'zh': 'Tuy A nhưng B：儘管A，B／即使A，B也……',
              'en': 'Tuy A nhưng B: B despite A / Even though A, B',
              'ja': 'Tuy A nhưng B：AにもかかわらずB／たとえAであってもB'},
  'examples': [{'vi': 'Cô ấy tuy không đẹp nhưng rất thông minh.',
                'kr': {'ko': '그녀는 예쁘지 않지만 매우 똑똑하다.',
                       'zh': '她雖然不漂亮,但是很聰明。',
                       'en': 'She is not pretty, but she is very smart.',
                       'ja': '彼女はきれいではないが、とても賢い。'}},
               {'vi': 'Tuy không đẹp nhưng cô ấy rất thông minh.',
                'kr': {'ko': '예쁘지 않지만 그녀는 매우 똑똑하다.',
                       'zh': '雖然不漂亮，但她非常聰明。',
                       'en': "She's not pretty, but she is very smart.",
                       'ja': '綺麗ではないけれど、彼女はとても賢い。'}}]},
 {'headword': 'vì … nên',
  'pos': None,
  'meaning': {'ko': '… 때문에 그래서 … (원인과 결과를 나타내는 표현.)',
              'zh': '…因為所以…（表示原因和結果的表達方式。）',
              'en': '… because, so … (An expression showing cause and effect.)',
              'ja': '…なので、それで…（原因と結果を表す表現。）'},
  'examples': [{'vi': 'Vì mưa nên tôi không đi chơi được.',
                'kr': {'ko': '비가 오기 때문에 나는 놀러가지 않았다.',
                       'zh': '因為下雨，我沒有出去玩。',
                       'en': "Because it rained, I didn't go out to play.",
                       'ja': '雨が降ったので、私は遊びに行きませんでした。'}},
               {'vi': 'Vì Minh nói sai nên một bạn không đồng ý.',
                'kr': {'ko': 'Minh이 틀리게 말했기 때문에 한 친구는 동의하지 않았다.',
                       'zh': '因為Minh說錯了，一個朋友不同意。',
                       'en': 'Because Minh said it incorrectly, one friend did not agree.',
                       'ja': 'ミンが間違って言ったので、ある友達は同意しなかった。'}}]},
 {'headword': 'vì sao (tại sao)…',
  'pos': None,
  'meaning': {'ko': '왜 … ? (원인, 이유를 물어보는 표현.)',
              'zh': '為什麼…？（詢問原因、理由的表達方式。）',
              'en': 'Why ...? (An expression used to ask for a cause or reason.)',
              'ja': 'なぜ…？（原因や理由を尋ねる表現。）'},
  'examples': [{'vi': 'Tại sao anh đi học muộn?',
                'kr': {'ko': '너는 왜 공부하러 늦게 오니?',
                       'zh': '你為什麼很晚才來學習？',
                       'en': 'Why do you come late to study?',
                       'ja': 'あなたはなぜ勉強しに遅く来るの？'}},
               {'vi': 'Vì sao anh đi ngủ muộn?',
                'kr': {'ko': '너는 왜 늦게 잠자러 가니?',
                       'zh': '你為什麼很晚才去睡覺？',
                       'en': 'Why do you go to sleep late?',
                       'ja': 'あなたはなぜ遅く寝に行くの？'}}]},
 {'headword': 'vừa … vừa …',
  'pos': None,
  'meaning': {'ko': '이 구문은 동시에 일어나거나 존재하는 두 개의 행동, 상태, 성질을 나타내기 위해 사용됨.',
              'zh': '此句型用於表示同時發生或存在的兩個動作、狀態或性質。',
              'en': 'This construction is used to express two actions, states, or qualities that occur or '
                    'exist simultaneously.',
              'ja': 'この構文は同時に起こる、または存在する二つの動作、状態、性質を表すために使われる。'},
  'examples': [{'vi': 'Ông ấy vừa to vừa béo.',
                'kr': {'ko': '그분은 크고 뚱뚱하시다.',
                       'zh': '那位又高又胖。',
                       'en': 'He/She is tall and big.',
                       'ja': 'その方は大きくて太っていらっしゃる。'}},
               {'vi': 'Cô ấy vừa ăn cơm vừa nói chuyện.',
                'kr': {'ko': '그녀는 밥을 먹으며 말했다.',
                       'zh': '她一邊吃飯一邊說話。',
                       'en': 'She spoke while eating.',
                       'ja': '彼女はご飯を食べながら話した。'}}]}]
