# "문법 및 작문 연습" tab data.
#
# Teaches Vietnamese sentence structure by growing one short sentence word by word,
# the same technique used in the original PPTX conversation-training deck
# ("Đây → Đây là → Đây là số → Đây là số điện thoại ..."), but organized as a
# grammar curriculum instead of situational dialogue: starting from the smallest
# possible sentence (subject + verb) and adding one grammatical piece at a time
# (object, place, time, adjective, possessive, frequency adverb, modal/auxiliary
# verb, degree adverb, negation, question, connector), reusing a small closed set
# of common subjects/verbs/adjectives/adverbs throughout so the learner sees the
# same words recombine rather than memorizing new vocabulary each step.
#
# Every Vietnamese phrase is stored as "pairs": a list of [vietnamese_segment,
# korean_gloss] tuples, one per word/phrase unit, IN VIETNAMESE WORD ORDER. The
# renderer lays each pair out as its own column (Vietnamese segment on top in
# the bigger accent-colored font, its Korean gloss centered directly underneath
# in a smaller font) so the two lines line up word-for-word even though Vietnamese
# words are wider than their Korean glosses -- rather than two independently
# flowing lines of text that drift out of alignment.
#
# The two headline contrasts with Korean, called out in GRAMMAR_INTRO and then
# re-illustrated inside the units themselves:
#   1. 서술어 위치: Korean is SOV (predicate last); Vietnamese is SVO (predicate
#      right after the subject).
#   2. 수식어 위치: Korean modifies before the noun (adjective + noun); Vietnamese
#      modifies after the noun (noun + adjective) -- same for possessives.
# A third, subtler point is added so the picture isn't over-simplified: not every
# modifier in Vietnamese trails its head word. Frequency/tense/modal words
# (thường, đã, đang, sẽ, phải, muốn ...) sit BEFORE the verb, same relative
# order as Korean, and degree words like "rất" sit BEFORE the adjective they
# intensify. Only the noun-adjective and noun-possessive relationship flips.
#
# "title"/"desc"/"note" and every Korean gloss ("kr" fields, and each pair's second
# element) are stored as {"ko","zh","en","ja"} dicts so js_json() (see build_app.py)
# serializes them straight into JS objects app_logic.js's T() helper can read directly.
# A step with no standalone Korean-sentence translation keeps "kr" as a plain empty
# string (not a dict) -- T() passes a plain string straight through either way.

GRAMMAR_INTRO = [{'title': {'ko': '① 서술어 위치: 한국어는 맨 뒤, 베트남어는 주어 바로 다음',
            'zh': '① 謂語位置：韓語在最後，越南語在主語之後',
            'en': '① Position of the predicate: at the very end in Korean, right after the subject '
                  'in Vietnamese',
            'ja': '① 述語の位置：韓国語は一番最後、ベトナム語は主語のすぐ後',
            'de': '① Position des Prädikats: Im Koreanischen ganz am Ende, im Vietnamesischen '
                  'direkt nach dem Subjekt'},
  'desc': {'ko': "한국어는 '주어 + 목적어 + 서술어' 순서로 서술어(동사)가 문장 맨 끝에 와요. 베트남어는 '주어 + 서술어 + 목적어' 순서로, 서술어가 "
                 '주어 바로 다음에 와요. 목적어·장소·시간 등은 모두 서술어 뒤에 붙습니다.',
           'zh': '韓語的語序是“主語+賓語+謂語”,謂語(動詞)位於句子的最後。越南語的語序是“主語+謂語+賓語”,謂語緊跟在主語之後。賓語、地點、時間等都放在謂語之後。',
           'en': "Korean follows the order 'subject + object + predicate', with the predicate "
                 '(verb) coming at the very end of the sentence. Vietnamese follows the order '
                 "'subject + predicate + object', with the predicate coming right after the "
                 'subject. Objects, places, times, etc. all come after the predicate.',
           'ja': '韓国語は「主語+目的語+述語」の順序で、述語(動詞)が文の一番最後に来ます。ベトナム語は「主語+述語+目的語」の順序で、述語が主語のすぐ後に来ます。目的語·場所·時間などはすべて述語の後に付きます。',
           'de': 'Im Deutschen und Koreanischen steht das Prädikat oft am Ende oder nach '
                 'bestimmten Regeln, aber im Vietnamesischen gilt die feste Reihenfolge „Subjekt + '
                 'Prädikat + Objekt“ – das Prädikat (Verb) folgt also direkt auf das Subjekt. '
                 'Objekte, Ortsangaben, Zeitangaben usw. werden alle nach dem Prädikat angefügt.'},
  'examples': [{'kr': {'ko': '나는 밥을 먹는다.',
                       'zh': '我吃飯。',
                       'en': 'I eat.',
                       'ja': '私はご飯を食べる。',
                       'de': 'Ich esse.'},
                'vi': 'Tôi ăn cơm.',
                'pairs': [['Tôi',
                           {'ko': '나(주어)',
                            'zh': '我(主語)',
                            'en': 'I (subject)',
                            'ja': '私(主語)',
                            'de': 'ich (Subjekt)'}],
                          ['ăn',
                           {'ko': '먹다(서술어)',
                            'zh': '吃（謂語）',
                            'en': 'to eat (predicate)',
                            'ja': '食べる（述語）',
                            'de': 'essen (Prädikat)'}],
                          ['cơm.',
                           {'ko': '밥(목적어)',
                            'zh': '飯（賓語）',
                            'en': 'rice (object)',
                            'ja': 'ご飯（目的語）',
                            'de': 'Reis/Essen (Objekt)'}]],
                'note': {'ko': '한국어는 서술어가 끝, 베트남어는 서술어가 둘째',
                         'zh': '韓語謂語在最後,越南語謂語在第二位',
                         'en': 'Korean: predicate at the end; Vietnamese: predicate second',
                         'ja': '韓国語は述語が最後、ベトナム語は述語が二番目',
                         'de': 'Im Koreanischen steht das Prädikat am Ende, im Vietnamesischen an '
                               'zweiter Stelle'}}]},
 {'title': {'ko': '② 수식어 위치: 한국어는 앞에서, 베트남어는 뒤에서',
            'zh': '② 修飾語位置：韓語在前，越南語在後',
            'en': '② Position of modifiers: before the noun in Korean, after it in Vietnamese',
            'ja': '② 修飾語の位置：韓国語は前から、ベトナム語は後ろから',
            'de': '② Position der Modifikatoren: Vor dem Nomen im Deutschen/Koreanischen, danach '
                  'im Vietnamesischen'},
  'desc': {'ko': "한국어는 꾸미는 말(형용사, '나의' 같은 소유격)이 꾸밈을 받는 명사 앞에 와요. 베트남어는 반대로, 명사가 먼저 나오고 꾸미는 말이 그 뒤에 "
                 '붙어요.',
           'zh': '韓語中修飾語(形容詞、像“我的”這樣的所有格)放在被修飾的名詞前面。越南語則相反,名詞先出現,修飾語跟在其後。',
           'en': 'In Korean, modifiers (adjectives, possessives like "my") come before the noun '
                 "they modify. In Vietnamese, it's the opposite — the noun comes first, followed "
                 'by the modifier.',
           'ja': '韓国語では修飾語(形容詞や「私の」のような所有格)が修飾される名詞の前に来ます。ベトナム語は逆に、名詞が先に来て、修飾語がその後に付きます。',
           'de': 'Im Deutschen und Koreanischen stehen beschreibende Wörter (Adjektive oder '
                 'Possessive wie „mein“) vor dem Nomen. Im Vietnamesischen ist es genau umgekehrt: '
                 'Das Nomen steht an erster Stelle, und die Bestimmung folgt dahinter.'},
  'examples': [{'kr': {'ko': '맛있는 밥',
                       'zh': '好吃的飯',
                       'en': 'delicious rice/meal',
                       'ja': 'おいしいご飯',
                       'de': 'leckeres Essen / leckerer Reis'},
                'vi': 'cơm ngon',
                'pairs': [['cơm',
                           {'ko': '밥(명사)',
                            'zh': '飯（名詞）',
                            'en': 'rice (noun)',
                            'ja': 'ご飯（名詞）',
                            'de': 'Reis/Essen (Nomen)'}],
                          ['ngon',
                           {'ko': '맛있는(형용사)',
                            'zh': '好吃的（形容詞）',
                            'en': 'delicious (adjective)',
                            'ja': 'おいしい（形容詞）',
                            'de': 'lecker (Adjektiv)'}]],
                'note': {'ko': '형용사가 명사 뒤로',
                         'zh': '形容詞放在名詞後面',
                         'en': 'Adjective goes after the noun',
                         'ja': '形容詞が名詞の後ろに',
                         'de': 'Adjektiv steht hinter dem Nomen'}},
               {'kr': {'ko': '나의 집 / 내 집',
                       'zh': '我的家 / 我家',
                       'en': 'my house / my house',
                       'ja': '私の家 / 私の家',
                       'de': 'mein Haus'},
                'vi': 'nhà của tôi',
                'pairs': [['nhà',
                           {'ko': '집(명사)',
                            'zh': '家(名詞)',
                            'en': 'house (noun)',
                            'ja': '家(名詞)',
                            'de': 'Haus (Nomen)'}],
                          ['của',
                           {'ko': '의(소유격)',
                            'zh': '的（所有格）',
                            'en': "'s (possessive case)",
                            'ja': 'の（所有格）',
                            'de': 'von / Genitivpartikel'}],
                          ['tôi',
                           {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私', 'de': 'ich, mir'}]],
                'note': {'ko': '소유격도 명사 뒤로',
                         'zh': '所有格也放在名詞後面',
                         'en': 'The possessive also comes after the noun',
                         'ja': '所有格も名詞の後ろに',
                         'de': 'Auch das Possessiv folgt hinter dem Nomen'}}]},
 {'title': {'ko': '③ 주의: 모든 수식어가 뒤로 가진 않아요',
            'zh': '③ 注意：並非所有修飾語都放在後面',
            'en': '③ Note: not all modifiers go after the noun',
            'ja': '③ 注意：すべての修飾語が後ろに来るわけではありません',
            'de': '③ Achtung: Nicht alle Bestimmungen stehen hinter dem Bezugswort'},
  'desc': {'ko': '명사를 꾸미는 형용사·소유격은 뒤로 가지만, 동사를 꾸미는 빈도부사(thường 자주, luôn 항상)나 시제·조동사 표지(đã 과거, đang '
                 '~하는 중, sẽ ~할 것, phải ~해야 함, muốn ~하고 싶음)는 한국어처럼 동사 앞에 옵니다. 형용사를 꾸미는 정도부사(rất '
                 '매우)도 형용사 앞에 와요.',
           'zh': '修飾名詞的形容詞、所有格放在後面，但修飾動詞的頻度副詞（thường經常、luôn總是）或時態·助動詞標記（đã過去、đang正在、sẽ將要、phải必須、muốn想要）則和韓語一樣放在動詞前面。修飾形容詞的程度副詞（rất非常）也放在形容詞前面。',
           'en': 'Adjectives and possessives that modify nouns come after the noun, but frequency '
                 'adverbs that modify verbs (thường "often", luôn "always") or tense/auxiliary '
                 'markers (đã "past", đang "in the process of", sẽ "will", phải "must", muốn "want '
                 'to") come before the verb, just like in Korean. Degree adverbs that modify '
                 'adjectives (rất "very") also come before the adjective.',
           'ja': '名詞を修飾する形容詞・所有格は後ろに来ますが、動詞を修飾する頻度副詞（thường よく、luôn いつも）や時制・助動詞の標識（đã 過去、đang '
                 '～している最中、sẽ ～するだろう、phải ～しなければならない、muốn ～したい）は韓国語と同じように動詞の前に来ます。形容詞を修飾する程度副詞（rất '
                 'とても）も形容詞の前に来ます。',
           'de': 'Adjektive und Possessive, die ein Nomen bestimmen, stehen dahinter. Doch '
                 'Häufigkeitsadverbien, die ein Verb bestimmen (thường „oft“, luôn „immer“), oder '
                 'Tempus-/Modal-Partikeln (đã Vergangenheit, đang Verlaufsform, sẽ Zukunft, phải '
                 'müssen, muốn möchten) stehen vor dem Verb. Auch Gradadverbien (rất „sehr“), die '
                 'ein Adjektiv verstärken, stehen vor dem Adjektiv.'},
  'examples': [{'kr': {'ko': '나는 자주 먹는다.',
                       'zh': '我經常吃。',
                       'en': 'I eat often.',
                       'ja': '私はよく食べる。',
                       'de': 'Ich esse oft.'},
                'vi': 'Tôi thường ăn.',
                'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私', 'de': 'ich'}],
                          ['thường',
                           {'ko': '자주(부사)',
                            'zh': '經常(副詞)',
                            'en': 'often (adverb)',
                            'ja': 'よく(副詞)',
                            'de': 'oft (Adverb)'}],
                          ['ăn.',
                           {'ko': '먹다(동사)',
                            'zh': '吃（動詞）',
                            'en': 'to eat (verb)',
                            'ja': '食べる（動詞）',
                            'de': 'essen (Verb)'}]],
                'note': {'ko': '부사가 동사 앞 — 한국어와 같은 순서',
                         'zh': '副詞在動詞前面 — 與韓語語序相同',
                         'en': 'The adverb comes before the verb — the same order as in Korean',
                         'ja': '副詞は動詞の前 — 韓国語と同じ語順',
                         'de': 'Adverb vor dem Verb'}},
               {'kr': {'ko': '매우 맛있는',
                       'zh': '非常好吃的',
                       'en': 'very delicious',
                       'ja': 'とてもおいしい',
                       'de': 'sehr lecker'},
                'vi': 'rất ngon',
                'pairs': [['rất',
                           {'ko': '매우(정도부사)',
                            'zh': '非常（程度副詞）',
                            'en': 'very (degree adverb)',
                            'ja': 'とても（程度副詞）',
                            'de': 'sehr (Gradadverb)'}],
                          ['ngon',
                           {'ko': '맛있는(형용사)',
                            'zh': '好吃的（形容詞）',
                            'en': 'delicious (adjective)',
                            'ja': 'おいしい（形容詞）',
                            'de': 'lecker (Adjektiv)'}]],
                'note': {'ko': '정도부사가 형용사 앞 — 한국어와 같은 순서',
                         'zh': '程度副詞在形容詞前——與韓語語序相同',
                         'en': 'Degree adverb before adjective — same order as in Korean',
                         'ja': '程度副詞が形容詞の前——韓国語と同じ語順',
                         'de': 'Gradadverb vor dem Adjektiv'}}]}]

GRAMMAR_UNITS = [{'title': {'ko': '1. 가장 짧은 문장 — 주어 + 서술어',
            'zh': '1. 最短的句子 — 主語 + 謂語',
            'en': '1. The shortest sentence — Subject + Predicate',
            'ja': '1. 最も短い文 — 主語＋述語',
            'de': '1. Der kürzeste Satz — Subjekt + Prädikat'},
  'note': {'ko': "베트남어 문장의 뼈대는 '주어 + 서술어'예요. 이것만으로도 완전한 문장이 됩니다. 서술어 자리에는 동사가 올 수도, 형용사가 그대로 올 수도 "
                 "있어요(형용사에는 '이다'에 해당하는 là가 필요 없어요). 명사가 서술어처럼 쓰이는 경우에만 là를 붙여요(주어 + là + 보어).",
           'zh': '越南語句子的骨架是"主語 + '
                 '謂語"。僅憑這個就能構成完整的句子。謂語的位置可以是動詞，也可以直接是形容詞（形容詞不需要相當於"是"的là）。只有當名詞被用作謂語時，才加上là（主語 + '
                 'là + 補語）。',
           'en': 'The backbone of a Vietnamese sentence is "subject + predicate." This alone makes '
                 'a complete sentence. The predicate slot can be filled by a verb, or an adjective '
                 'can go there as is (adjectives don\'t need là, which corresponds to "to be"). '
                 'Only when a noun is used as the predicate is là attached (subject + là + '
                 'complement).',
           'ja': 'ベトナム語の文の骨組みは「主語＋述語」です。これだけで完全な文になります。述語の位置には動詞が来ることも、形容詞がそのまま来ることもあります（形容詞には「である」に当たるlàは必要ありません）。名詞が述語のように使われる場合にのみlàを付けます（主語＋là＋補語）。',
           'de': 'Das Grundgerüst eines vietnamesischen Satzes ist „Subjekt + Prädikat“. Das '
                 'allein bildet bereits einen vollständigen Satz. An der Stelle des Prädikats kann '
                 'ein Verb oder direkt ein Adjektiv stehen (Adjektive benötigen kein „là“ für '
                 '„sein“). Nur wenn ein Nomen als Prädikat fungiert, wird „là“ angefügt (Subjekt + '
                 'là + Komplement).'},
  'steps': [{'vi': 'Tôi',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私', 'de': 'ich'}]],
             'kr': ''},
            {'vi': 'Tôi ăn.',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私', 'de': 'ich'}],
                       ['ăn.',
                        {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる', 'de': 'essen'}]],
             'kr': {'ko': '나는 먹는다.',
                    'zh': '我吃飯。',
                    'en': 'I eat.',
                    'ja': '私は食べる。',
                    'de': 'Ich esse.'}},
            {'vi': 'Trời lạnh.',
             'pairs': [['Trời',
                        {'ko': '날씨', 'zh': '天氣', 'en': 'weather', 'ja': '天気', 'de': 'das Wetter'}],
                       ['lạnh.',
                        {'ko': '춥다',
                         'zh': '冷',
                         'en': 'to be cold',
                         'ja': '寒い',
                         'de': 'kalt sein'}]],
             'kr': {'ko': '날씨가 춥다.',
                    'zh': '天氣很冷。',
                    'en': 'The weather is cold.',
                    'ja': '天気が寒い。',
                    'de': 'Das Wetter ist kalt.'}},
            {'vi': 'Tôi là học viên.',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私', 'de': 'ich'}],
                       ['là', {'ko': '이다', 'zh': '是', 'en': 'to be', 'ja': 'である/です', 'de': 'sein'}],
                       ['học viên.',
                        {'ko': '학생', 'zh': '學生', 'en': 'student', 'ja': '学生', 'de': 'Schüler'}]],
             'kr': {'ko': '나는 학생이다.',
                    'zh': '我是學生。',
                    'en': 'I am a student.',
                    'ja': '私は学生だ。',
                    'de': 'Ich bin ein Schüler.'}}]},
 {'title': {'ko': '2. 목적어 추가 — 서술어 바로 뒤에',
            'zh': '2. 添加賓語 — 緊接謂語之後',
            'en': '2. Adding an object — right after the predicate',
            'ja': '2. 目的語の追加 — 述語のすぐ後ろに',
            'de': '2. Hinzufügen eines Objekts — direkt nach dem Prädikat'},
  'note': {'ko': "한국어는 '밥을 먹는다'(목적어-서술어)지만, 베트남어는 '먹는다-밥'(서술어-목적어) 순서예요.",
           'zh': '韓語是“吃飯”(賓語-謂語),但越南語的語序是“吃-飯”(謂語-賓語)。',
           'en': "Korean is '밥을 먹는다' (object-predicate), but Vietnamese follows the order "
                 "'eat-rice' (predicate-object).",
           'ja': '韓国語は「ご飯を食べる」(目的語-述語)ですが、ベトナム語は「食べる-ご飯」(述語-目的語)の順序です。',
           'de': 'Im Vietnamesischen folgt die Reihenfolge „Verb + Objekt“ (essen + Reis), also '
                 'steht das Objekt unmittelbar hinter dem Prädikat.'},
  'steps': [{'vi': 'Tôi ăn',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私', 'de': 'ich'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる', 'de': 'essen'}]],
             'kr': ''},
            {'vi': 'Tôi ăn cơm.',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私', 'de': 'ich'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる', 'de': 'essen'}],
                       ['cơm.',
                        {'ko': '밥',
                         'zh': '飯',
                         'en': 'rice / meal',
                         'ja': 'ご飯',
                         'de': 'Reis / Essen'}]],
             'kr': {'ko': '나는 밥을 먹는다.',
                    'zh': '我吃飯。',
                    'en': 'I eat.',
                    'ja': '私はご飯を食べる。',
                    'de': 'Ich esse.'}}]},
 {'title': {'ko': '3. 장소 추가 — 문장 뒤쪽에',
            'zh': '3. 添加地點 — 位於句子後部',
            'en': '3. Adding a place — toward the end of the sentence',
            'ja': '3. 場所の追加 — 文の後ろの方に',
            'de': '3. Hinzufügen einer Ortsangabe — gegen Ende des Satzes'},
  'note': {'ko': "'~에서'에 해당하는 ở + 장소는 목적어 뒤, 문장 뒤쪽에 붙어요.",
           'zh': "相當於'~에서'的 ở + 地點，接在賓語之後，位於句子靠後的位置。",
           'en': "ở + place, which corresponds to '~에서', comes after the object, toward the end of "
                 'the sentence.',
           'ja': "'~에서'に当たる ở + 場所は、目的語の後ろ、文の後ろの方に付きます。",
           'de': '„ở + Ort“ (an/in + Ort) steht nach dem Objekt gegen Ende des Satzes.'},
  'steps': [{'vi': 'Tôi ăn cơm',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私', 'de': 'ich'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる', 'de': 'essen'}],
                       ['cơm',
                        {'ko': '밥',
                         'zh': '飯',
                         'en': 'rice / meal',
                         'ja': 'ご飯',
                         'de': 'Reis / Essen'}]],
             'kr': ''},
            {'vi': 'Tôi ăn cơm ở nhà.',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私', 'de': 'ich'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる', 'de': 'essen'}],
                       ['cơm',
                        {'ko': '밥',
                         'zh': '飯',
                         'en': 'rice / meal',
                         'ja': 'ご飯',
                         'de': 'Reis / Essen'}],
                       ['ở',
                        {'ko': '~에서',
                         'zh': '在~（從……/在某地）',
                         'en': 'at/from ~',
                         'ja': '~で（場所）',
                         'de': 'in / an'}],
                       ['nhà.',
                        {'ko': '집', 'zh': '家', 'en': 'house', 'ja': '家', 'de': 'Haus / Zuhause'}]],
             'kr': {'ko': '나는 집에서 밥을 먹는다.',
                    'zh': '我在家吃飯。',
                    'en': 'I eat at home.',
                    'ja': '私は家でご飯を食べる。',
                    'de': 'Ich esse zu Hause.'}}]},
 {'title': {'ko': '4. 시간 추가 — 문장 맨 뒤에',
            'zh': '4. 添加時間 — 位於句子最後',
            'en': '4. Adding time — at the very end of the sentence',
            'ja': '4. 時間の追加 — 文の一番最後に',
            'de': '4. Hinzufügen einer Zeitangabe — ganz am Ende des Satzes'},
  'note': {'ko': "'~에'(시각·때)에 해당하는 vào + 시간은 보통 문장의 맨 뒤에 와요.",
           'zh': "相當於'~에'（時刻·時間）的 vào + 時間，通常放在句子的最後。",
           'en': "vào + time, which corresponds to '~에' (time/hour), usually comes at the very end "
                 'of the sentence.',
           'ja': "'~에'（時刻・時）に当たる vào + 時間は、普通文の一番後ろに来ます。",
           'de': '„vào + Zeit“ (am/um + Zeitangabe) steht üblicherweise ganz am Ende des Satzes.'},
  'steps': [{'vi': 'Tôi ăn cơm ở nhà',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私', 'de': 'ich'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる', 'de': 'essen'}],
                       ['cơm',
                        {'ko': '밥',
                         'zh': '飯',
                         'en': 'rice / meal',
                         'ja': 'ご飯',
                         'de': 'Reis / Essen'}],
                       ['ở',
                        {'ko': '~에서',
                         'zh': '在~（從……/在某地）',
                         'en': 'at/from ~',
                         'ja': '~で（場所）',
                         'de': 'in / an'}],
                       ['nhà',
                        {'ko': '집', 'zh': '家', 'en': 'house', 'ja': '家', 'de': 'Haus / Zuhause'}]],
             'kr': ''},
            {'vi': 'Tôi ăn cơm ở nhà vào buổi sáng.',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私', 'de': 'ich'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる', 'de': 'essen'}],
                       ['cơm',
                        {'ko': '밥',
                         'zh': '飯',
                         'en': 'rice / meal',
                         'ja': 'ご飯',
                         'de': 'Reis / Essen'}],
                       ['ở',
                        {'ko': '~에서',
                         'zh': '在~（從……/在某地）',
                         'en': 'at/from ~',
                         'ja': '~で（場所）',
                         'de': 'in / an'}],
                       ['nhà',
                        {'ko': '집', 'zh': '家', 'en': 'house', 'ja': '家', 'de': 'Haus / Zuhause'}],
                       ['vào',
                        {'ko': '~에',
                         'zh': '在~（時間/地點）',
                         'en': 'at/in/to ~',
                         'ja': '~に',
                         'de': 'an / am'}],
                       ['buổi sáng.',
                        {'ko': '아침', 'zh': '早上', 'en': 'morning', 'ja': '朝', 'de': 'Morgen'}]],
             'kr': {'ko': '나는 아침에 집에서 밥을 먹는다.',
                    'zh': '我早上在家吃飯。',
                    'en': 'I eat at home in the morning.',
                    'ja': '私は朝、家でご飯を食べる。',
                    'de': 'Ich esse morgens zu Hause.'}}]},
 {'title': {'ko': '5. 형용사로 명사 꾸미기 — 명사 뒤에 (핵심 대조)',
            'zh': '5. 用形容詞修飾名詞 — 位於名詞之後（核心對照）',
            'en': '5. Modifying a noun with an adjective — after the noun (key contrast)',
            'ja': '5. 形容詞で名詞を修飾する — 名詞の後ろに（重要な対照）',
            'de': '5. Nomen mit Adjektiv näher bestimmen — nach dem Nomen (wichtiger Unterschied)'},
  'note': {'ko': "'맛있는 밥'은 한국어에서 형용사가 먼저지만, 베트남어는 cơm ngon(밥 맛있는)처럼 명사가 먼저예요.",
           'zh': "'好吃的飯'在韓語中形容詞在前，但越南語像 cơm ngon（飯 好吃的）一樣，名詞在前。",
           'en': "For 'delicious rice', the adjective comes first in Korean, but in Vietnamese, as "
                 'in cơm ngon (rice - delicious), the noun comes first.',
           'ja': '「おいしいご飯」は韓国語では形容詞が先ですが、ベトナム語は cơm ngon（ご飯 おいしい）のように名詞が先です。',
           'de': 'Während das Adjektiv im Deutschen vor dem Nomen steht („leckeres Essen“), steht '
                 'im Vietnamesischen das Nomen an erster Stelle, gefolgt vom Adjektiv: cơm ngon '
                 '(Essen - lecker).'},
  'steps': [{'vi': 'cơm',
             'pairs': [['cơm',
                        {'ko': '밥',
                         'zh': '飯',
                         'en': 'rice / meal',
                         'ja': 'ご飯',
                         'de': 'Reis / Essen'}]],
             'kr': ''},
            {'vi': 'cơm ngon',
             'pairs': [['cơm',
                        {'ko': '밥',
                         'zh': '飯',
                         'en': 'rice / meal',
                         'ja': 'ご飯',
                         'de': 'Reis / Essen'}],
                       ['ngon',
                        {'ko': '맛있는',
                         'zh': '好吃的',
                         'en': 'delicious',
                         'ja': 'おいしい',
                         'de': 'lecker'}]],
             'kr': {'ko': '맛있는 밥',
                    'zh': '好吃的飯',
                    'en': 'delicious rice/meal',
                    'ja': 'おいしいご飯',
                    'de': 'leckeres Essen / leckerer Reis'}},
            {'vi': 'Tôi ăn cơm ngon ở nhà vào buổi sáng.',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私', 'de': 'ich'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる', 'de': 'essen'}],
                       ['cơm',
                        {'ko': '밥',
                         'zh': '飯',
                         'en': 'rice / meal',
                         'ja': 'ご飯',
                         'de': 'Reis / Essen'}],
                       ['ngon',
                        {'ko': '맛있는',
                         'zh': '好吃的',
                         'en': 'delicious',
                         'ja': 'おいしい',
                         'de': 'lecker'}],
                       ['ở',
                        {'ko': '~에서',
                         'zh': '在~（從……/在某地）',
                         'en': 'at/from ~',
                         'ja': '~で（場所）',
                         'de': 'in / an'}],
                       ['nhà',
                        {'ko': '집', 'zh': '家', 'en': 'house', 'ja': '家', 'de': 'Haus / Zuhause'}],
                       ['vào',
                        {'ko': '~에',
                         'zh': '在~（時間/地點）',
                         'en': 'at/in/to ~',
                         'ja': '~に',
                         'de': 'an / am'}],
                       ['buổi sáng.',
                        {'ko': '아침', 'zh': '早上', 'en': 'morning', 'ja': '朝', 'de': 'Morgen'}]],
             'kr': {'ko': '나는 아침에 집에서 맛있는 밥을 먹는다.',
                    'zh': '我早上在家吃好吃的飯。',
                    'en': 'I eat delicious food at home in the morning.',
                    'ja': '私は朝、家でおいしいご飯を食べる。',
                    'de': 'Ich esse morgens zu Hause leckeres Essen.'}}]},
 {'title': {'ko': '6. 소유격으로 명사 꾸미기 — 명사 뒤에',
            'zh': '6. 用所有格修飾名詞 — 位於名詞之後',
            'en': '6. Modifying a noun with a possessive — after the noun',
            'ja': '6. 所有格で名詞を修飾する — 名詞の後ろに',
            'de': '6. Nomen mit Possessiv näher bestimmen — nach dem Nomen'},
  'note': {'ko': "'내 집'도 마찬가지로 nhà của tôi(집 의 나)처럼 명사가 먼저, 소유격이 나중이에요.",
           'zh': "'我的家'也一樣，像 nhà của tôi（家 的 我）一樣，名詞在前，所有格在後。",
           'en': "Likewise for 'my house': as in nhà của tôi (house - of - I), the noun comes "
                 'first and the possessive comes after.',
           'ja': '「私の家」も同様に、nhà của tôi（家 の 私）のように名詞が先、所有格が後になります。',
           'de': 'Genauso wie beim Adjektiv: Bei „mein Haus“ steht im Vietnamesischen das Nomen '
                 'zuerst und die Besitzangabe danach: nhà của tôi (Haus - von - mir).'},
  'steps': [{'vi': 'nhà',
             'pairs': [['nhà',
                        {'ko': '집', 'zh': '家', 'en': 'house', 'ja': '家', 'de': 'Haus / Zuhause'}]],
             'kr': ''},
            {'vi': 'nhà của tôi',
             'pairs': [['nhà',
                        {'ko': '집', 'zh': '家', 'en': 'house', 'ja': '家', 'de': 'Haus / Zuhause'}],
                       ['của',
                        {'ko': '의',
                         'zh': '的',
                         'en': "'s (possessive particle)",
                         'ja': 'の',
                         'de': 'von / (Possessiv)'}],
                       ['tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私', 'de': 'ich, mir'}]],
             'kr': {'ko': '내 집 / 나의 집',
                    'zh': '我家 / 我的家',
                    'en': 'my house / my house',
                    'ja': '私の家 / 私の家',
                    'de': 'mein Haus'}},
            {'vi': 'Đây là nhà của tôi.',
             'pairs': [['Đây',
                        {'ko': '여기', 'zh': '這裡', 'en': 'here', 'ja': 'ここ', 'de': 'dies / hier'}],
                       ['là', {'ko': '이다', 'zh': '是', 'en': 'to be', 'ja': 'である/です', 'de': 'sein'}],
                       ['nhà',
                        {'ko': '집', 'zh': '家', 'en': 'house', 'ja': '家', 'de': 'Haus / Zuhause'}],
                       ['của',
                        {'ko': '의',
                         'zh': '的',
                         'en': "'s (possessive particle)",
                         'ja': 'の',
                         'de': 'von / (Possessiv)'}],
                       ['tôi.',
                        {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私', 'de': 'ich, mir'}]],
             'kr': {'ko': '여기는 내 집이다.',
                    'zh': '這裡是我的家。',
                    'en': 'This is my house.',
                    'ja': 'ここは私の家です。',
                    'de': 'Das ist mein Haus.'}}]},
 {'title': {'ko': '7. 빈도부사 추가 — 동사 앞에 (한국어와 같은 순서)',
            'zh': '7. 添加頻率副詞 — 位於動詞之前（與韓語語序相同）',
            'en': '7. Adding adverbs of frequency — before the verb (same order as Korean)',
            'ja': '7. 頻度副詞の追加 — 動詞の前に（韓国語と同じ語順）',
            'de': '7. Häufigkeitsadverbien hinzufügen — vor dem Verb'},
  'note': {'ko': 'thường(보통·자주), luôn luôn(항상), cũng(또한) 같은 빈도부사는 한국어처럼 동사 앞에 와요.',
           'zh': '像 thường（通常·經常）、luôn luôn（總是）、cũng（也）這樣的頻率副詞，和韓語一樣放在動詞前面。',
           'en': 'Frequency adverbs like thường (usually, often), luôn luôn (always), and cũng '
                 '(also) come before the verb, just like in Korean.',
           'ja': 'thường（普通・よく）、luôn luôn（いつも）、cũng（また）のような頻度副詞は、韓国語と同じように動詞の前に来ます。',
           'de': 'Häufigkeitsadverbien wie thường (gewöhnlich, oft), luôn luôn (immer) und cũng '
                 '(auch) stehen vor dem Verb.'},
  'steps': [{'vi': 'Tôi ăn cơm ở nhà.',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私', 'de': 'ich'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる', 'de': 'essen'}],
                       ['cơm',
                        {'ko': '밥',
                         'zh': '飯',
                         'en': 'rice / meal',
                         'ja': 'ご飯',
                         'de': 'Reis / Essen'}],
                       ['ở',
                        {'ko': '~에서',
                         'zh': '在~（從……/在某地）',
                         'en': 'at/from ~',
                         'ja': '~で（場所）',
                         'de': 'in / an'}],
                       ['nhà.',
                        {'ko': '집', 'zh': '家', 'en': 'house', 'ja': '家', 'de': 'Haus / Zuhause'}]],
             'kr': ''},
            {'vi': 'Tôi thường ăn cơm ở nhà.',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私', 'de': 'ich'}],
                       ['thường',
                        {'ko': '보통',
                         'zh': '通常',
                         'en': 'usually / normal',
                         'ja': '普通',
                         'de': 'gewöhnlich / normalerweise'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる', 'de': 'essen'}],
                       ['cơm',
                        {'ko': '밥',
                         'zh': '飯',
                         'en': 'rice / meal',
                         'ja': 'ご飯',
                         'de': 'Reis / Essen'}],
                       ['ở',
                        {'ko': '~에서',
                         'zh': '在~（從……/在某地）',
                         'en': 'at/from ~',
                         'ja': '~で（場所）',
                         'de': 'in / an'}],
                       ['nhà.',
                        {'ko': '집', 'zh': '家', 'en': 'house', 'ja': '家', 'de': 'Haus / Zuhause'}]],
             'kr': {'ko': '나는 보통 집에서 밥을 먹는다.',
                    'zh': '我通常在家吃飯。',
                    'en': 'I usually eat at home.',
                    'ja': '私はふだん家でご飯を食べる。',
                    'de': 'Ich esse gewöhnlich zu Hause.'}}]},
 {'title': {'ko': '8. 조동사 추가 — 동사 앞에',
            'zh': '8. 添加助動詞 — 位於動詞之前',
            'en': '8. Adding an auxiliary verb — before the verb',
            'ja': '8. 助動詞の追加 — 動詞の前に',
            'de': '8. Modalverben und Hilfswörter hinzufügen — vor dem Verb'},
  'note': {'ko': 'muốn(~하고 싶다), phải(~해야 한다), có thể(~할 수 있다)·không thể(~할 수 없다), nên(~하는 게 좋다), '
                 'đang(~하는 중), sẽ(~할 것이다), đã(~했다) 모두 동사 바로 앞에 옵니다.',
           'zh': 'muốn（想要~）、phải（必須~）、có thể（能~）·không '
                 'thể（不能~）、nên（最好~）、đang（正在~）、sẽ（將要~）、đã（已經~）都放在動詞的正前方。',
           'en': 'muốn (want to ~), phải (must ~), có thể (can ~) · không thể (cannot ~), nên '
                 '(should ~), đang (~ing), sẽ (will ~), and đã (~ed) all come right before the '
                 'verb.',
           'ja': 'muốn（~したい）、phải（~しなければならない）、có thể（~できる）・không '
                 'thể（~できない）、nên（~する方がよい）、đang（~している最中）、sẽ（~するだろう）、đã（~した）はすべて動詞のすぐ前に来ます。',
           'de': 'muốn (wollen / möchten), phải (müssen), có thể (können) / không thể (nicht '
                 'können), nên (sollte), đang (Verlaufsform), sẽ (Zukunft) und đã (Vergangenheit) '
                 'stehen alle direkt vor dem Verb.'},
  'steps': [{'vi': 'Tôi ăn cơm',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私', 'de': 'ich'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる', 'de': 'essen'}],
                       ['cơm',
                        {'ko': '밥',
                         'zh': '飯',
                         'en': 'rice / meal',
                         'ja': 'ご飯',
                         'de': 'Reis / Essen'}]],
             'kr': ''},
            {'vi': 'Tôi muốn ăn cơm.',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私', 'de': 'ich'}],
                       ['muốn',
                        {'ko': '~하고 싶다',
                         'zh': '想要~',
                         'en': 'want to ~',
                         'ja': '~したい',
                         'de': 'möchten / wollen'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる', 'de': 'essen'}],
                       ['cơm.',
                        {'ko': '밥',
                         'zh': '飯',
                         'en': 'rice / meal',
                         'ja': 'ご飯',
                         'de': 'Reis / Essen'}]],
             'kr': {'ko': '나는 밥을 먹고 싶다.',
                    'zh': '我想吃飯。',
                    'en': 'I want to eat.',
                    'ja': '私はご飯を食べたい。',
                    'de': 'Ich möchte essen.'}},
            {'vi': 'Tôi phải đi học.',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私', 'de': 'ich'}],
                       ['phải',
                        {'ko': '~해야 한다',
                         'zh': '必須~',
                         'en': 'must ~',
                         'ja': '~しなければならない',
                         'de': 'müssen'}],
                       ['đi', {'ko': '가다', 'zh': '去', 'en': 'to go', 'ja': '行く', 'de': 'gehen'}],
                       ['học.',
                        {'ko': '공부(하러)',
                         'zh': '（去）學習',
                         'en': '(to go) study',
                         'ja': '勉強（しに）',
                         'de': 'lernen (gehen)'}]],
             'kr': {'ko': '나는 학교에 가야 한다.',
                    'zh': '我得去學校。',
                    'en': 'I have to go to school.',
                    'ja': '私は学校に行かなければならない。',
                    'de': 'Ich muss zur Schule gehen.'}},
            {'vi': 'Tôi có thể ăn cơm.',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私', 'de': 'ich'}],
                       ['có thể',
                        {'ko': '~할 수 있다', 'zh': '能~', 'en': 'can ~', 'ja': '~できる', 'de': 'können'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる', 'de': 'essen'}],
                       ['cơm.',
                        {'ko': '밥',
                         'zh': '飯',
                         'en': 'rice / meal',
                         'ja': 'ご飯',
                         'de': 'Reis / Essen'}]],
             'kr': {'ko': '나는 밥을 먹을 수 있다.',
                    'zh': '我能吃飯。',
                    'en': 'I can eat.',
                    'ja': '私はご飯を食べられる。',
                    'de': 'Ich kann essen.'}},
            {'vi': 'Tôi không thể ăn cơm.',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私', 'de': 'ich'}],
                       ['không thể',
                        {'ko': '~할 수 없다',
                         'zh': '不能~',
                         'en': 'cannot ~',
                         'ja': '~できない',
                         'de': 'nicht können'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる', 'de': 'essen'}],
                       ['cơm.',
                        {'ko': '밥',
                         'zh': '飯',
                         'en': 'rice / meal',
                         'ja': 'ご飯',
                         'de': 'Reis / Essen'}]],
             'kr': {'ko': '나는 밥을 먹을 수 없다.',
                    'zh': '我不能吃飯。',
                    'en': 'I cannot eat.',
                    'ja': '私はご飯を食べられない。',
                    'de': 'Ich kann nicht essen.'}},
            {'vi': 'Bạn nên ăn cơm.',
             'pairs': [['Bạn', {'ko': '너', 'zh': '你', 'en': 'you', 'ja': 'お前、君', 'de': 'du'}],
                       ['nên',
                        {'ko': '~하는 게 좋다',
                         'zh': '最好~',
                         'en': "should ~ / it's better to ~",
                         'ja': '~する方がよい',
                         'de': 'sollte'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる', 'de': 'essen'}],
                       ['cơm.',
                        {'ko': '밥',
                         'zh': '飯',
                         'en': 'rice / meal',
                         'ja': 'ご飯',
                         'de': 'Reis / Essen'}]],
             'kr': {'ko': '너는 밥을 먹는 게 좋겠다.',
                    'zh': '你最好吃飯。',
                    'en': 'You should eat.',
                    'ja': 'あなたはご飯を食べたほうがいい。',
                    'de': 'Du solltest essen.'}},
            {'vi': 'Tôi đang ăn cơm.',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私', 'de': 'ich'}],
                       ['đang',
                        {'ko': '~하는 중',
                         'zh': '正在~',
                         'en': 'in the middle of ~ing',
                         'ja': '~している最中',
                         'de': 'gerade dabei sein zu'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる', 'de': 'essen'}],
                       ['cơm.',
                        {'ko': '밥',
                         'zh': '飯',
                         'en': 'rice / meal',
                         'ja': 'ご飯',
                         'de': 'Reis / Essen'}]],
             'kr': {'ko': '나는 밥을 먹고 있다.',
                    'zh': '我正在吃飯。',
                    'en': 'I am eating.',
                    'ja': '私はご飯を食べている。',
                    'de': 'Ich esse gerade.'}},
            {'vi': 'Tôi sẽ ăn cơm.',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私', 'de': 'ich'}],
                       ['sẽ',
                        {'ko': '~할 것이다',
                         'zh': '將要~',
                         'en': 'will ~',
                         'ja': '~するつもりだ',
                         'de': 'werden'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる', 'de': 'essen'}],
                       ['cơm.',
                        {'ko': '밥',
                         'zh': '飯',
                         'en': 'rice / meal',
                         'ja': 'ご飯',
                         'de': 'Reis / Essen'}]],
             'kr': {'ko': '나는 밥을 먹을 것이다.',
                    'zh': '我將要吃飯。',
                    'en': 'I will eat.',
                    'ja': '私はご飯を食べるつもりだ。',
                    'de': 'Ich werde essen.'}},
            {'vi': 'Tôi đã ăn cơm.',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私', 'de': 'ich'}],
                       ['đã',
                        {'ko': '~했다',
                         'zh': '~了',
                         'en': '~ed',
                         'ja': '~した',
                         'de': '(Vergangenheit)'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる', 'de': 'essen'}],
                       ['cơm.',
                        {'ko': '밥',
                         'zh': '飯',
                         'en': 'rice / meal',
                         'ja': 'ご飯',
                         'de': 'Reis / Essen'}]],
             'kr': {'ko': '나는 밥을 먹었다.',
                    'zh': '我吃了飯。',
                    'en': 'I ate.',
                    'ja': '私はご飯を食べた。',
                    'de': 'Ich habe gegessen.'}}]},
 {'title': {'ko': '9. 정도부사 + 형용사 — 형용사 앞에',
            'zh': '9. 程度副詞＋形容詞 — 位於形容詞之前',
            'en': '9. Degree adverb + adjective — before the adjective',
            'ja': '9. 程度副詞＋形容詞 — 形容詞の前に',
            'de': '9. Gradadverb + Adjektiv — vor dem Adjektiv'},
  'note': {'ko': 'rất(매우) 같은 정도부사는 형용사를 꾸미는 말이라, 형용사 앞에 와요. (형용사 자체는 명사 뒤인데, 정도부사는 그 형용사 앞!)',
           'zh': '像 rất（非常）這樣的程度副詞是用來修飾形容詞的，所以放在形容詞前面。（形容詞本身在名詞後面，但程度副詞在那個形容詞前面！）',
           'en': 'Degree adverbs like rất (very) modify adjectives, so they come before the '
                 'adjective. (The adjective itself comes after the noun, but the degree adverb '
                 'comes before that adjective!)',
           'ja': 'rất（とても）のような程度副詞は形容詞を修飾する言葉なので、形容詞の前に来ます。（形容詞自体は名詞の後ろですが、程度副詞はその形容詞の前です！）',
           'de': 'Gradadverbien wie rất (sehr) bestimmen das Adjektiv näher und stehen daher '
                 'direkt vor dem Adjektiv. (Das Adjektiv selbst steht hinter dem Nomen, aber das '
                 'Gradadverb steht vor dem Adjektiv!)'},
  'steps': [{'vi': 'cơm ngon',
             'pairs': [['cơm',
                        {'ko': '밥',
                         'zh': '飯',
                         'en': 'rice / meal',
                         'ja': 'ご飯',
                         'de': 'Reis / Essen'}],
                       ['ngon',
                        {'ko': '맛있는',
                         'zh': '好吃的',
                         'en': 'delicious',
                         'ja': 'おいしい',
                         'de': 'lecker'}]],
             'kr': ''},
            {'vi': 'cơm rất ngon',
             'pairs': [['cơm',
                        {'ko': '밥',
                         'zh': '飯',
                         'en': 'rice / meal',
                         'ja': 'ご飯',
                         'de': 'Reis / Essen'}],
                       ['rất', {'ko': '매우', 'zh': '非常', 'en': 'very', 'ja': 'とても', 'de': 'sehr'}],
                       ['ngon',
                        {'ko': '맛있는',
                         'zh': '好吃的',
                         'en': 'delicious',
                         'ja': 'おいしい',
                         'de': 'lecker'}]],
             'kr': {'ko': '매우 맛있는 밥',
                    'zh': '非常好吃的飯',
                    'en': 'very delicious rice/meal',
                    'ja': 'とてもおいしいご飯',
                    'de': 'sehr leckeres Essen'}},
            {'vi': 'Tôi ăn cơm rất ngon.',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私', 'de': 'ich'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる', 'de': 'essen'}],
                       ['cơm',
                        {'ko': '밥',
                         'zh': '飯',
                         'en': 'rice / meal',
                         'ja': 'ご飯',
                         'de': 'Reis / Essen'}],
                       ['rất', {'ko': '매우', 'zh': '非常', 'en': 'very', 'ja': 'とても', 'de': 'sehr'}],
                       ['ngon.',
                        {'ko': '맛있는',
                         'zh': '好吃的',
                         'en': 'delicious',
                         'ja': 'おいしい',
                         'de': 'lecker'}]],
             'kr': {'ko': '나는 매우 맛있는 밥을 먹는다.',
                    'zh': '我吃非常好吃的飯。',
                    'en': 'I eat very delicious food.',
                    'ja': '私はとてもおいしいご飯を食べる。',
                    'de': 'Ich esse sehr leckeres Essen.'}}]},
 {'title': {'ko': '10. 부정문 — không을 동사(또는 형용사) 앞에',
            'zh': '10. 否定句 — 在動詞（或形容詞）前加 không',
            'en': '10. Negative sentences — put không before the verb (or adjective)',
            'ja': '10. 否定文 — không を動詞（または形容詞）の前に',
            'de': '10. Verneinungssätze — không vor das Verb (oder Adjektiv) setzen'},
  'note': {'ko': '부정은 không을 서술어 바로 앞에 넣으면 돼요.',
           'zh': '否定只要把 không 放在謂語前面即可。',
           'en': 'To make it negative, just put "không" right before the predicate.',
           'ja': '否定は「không」を述語の直前に入れればいいです。',
           'de': 'Um einen Satz zu verneinen, setzt man einfach „không“ direkt vor das Prädikat.'},
  'steps': [{'vi': 'Tôi ăn cơm',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私', 'de': 'ich'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる', 'de': 'essen'}],
                       ['cơm',
                        {'ko': '밥',
                         'zh': '飯',
                         'en': 'rice / meal',
                         'ja': 'ご飯',
                         'de': 'Reis / Essen'}]],
             'kr': ''},
            {'vi': 'Tôi không ăn cơm.',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私', 'de': 'ich'}],
                       ['không', {'ko': '안', 'zh': '裡面', 'en': 'inside', 'ja': '中', 'de': 'nicht'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる', 'de': 'essen'}],
                       ['cơm.',
                        {'ko': '밥',
                         'zh': '飯',
                         'en': 'rice / meal',
                         'ja': 'ご飯',
                         'de': 'Reis / Essen'}]],
             'kr': {'ko': '나는 밥을 안 먹는다.',
                    'zh': '我不吃飯。',
                    'en': "I don't eat.",
                    'ja': '私はご飯を食べない。',
                    'de': 'Ich esse nicht.'}},
            {'vi': 'Cơm không ngon.',
             'pairs': [['Cơm',
                        {'ko': '밥',
                         'zh': '飯',
                         'en': 'rice / meal',
                         'ja': 'ご飯',
                         'de': 'Reis / Essen'}],
                       ['không', {'ko': '안', 'zh': '裡面', 'en': 'inside', 'ja': '中', 'de': 'nicht'}],
                       ['ngon.',
                        {'ko': '맛있다',
                         'zh': '好吃',
                         'en': 'to be delicious',
                         'ja': 'おいしい',
                         'de': 'lecker sein'}]],
             'kr': {'ko': '밥이 맛없다.',
                    'zh': '飯不好吃。',
                    'en': "The rice isn't tasty.",
                    'ja': 'ご飯がおいしくない。',
                    'de': 'Das Essen ist nicht lecker.'}}]},
 {'title': {'ko': '11. 의문문 — 예/아니오 (có ... không으로 감싸기)',
            'zh': '11. 疑問句 — 是/否（用 có ... không 包裹）',
            'en': '11. Yes/No questions (wrapping the sentence with có ... không)',
            'ja': '11. 疑問文 — はい／いいえ（có ... không で挟む）',
            'de': '11. Ja/Nein-Fragen (Satzklammer mit có ... không)'},
  'note': {'ko': "'~합니까?'라고 물을 땐 서술어 앞에 có, 문장 끝에 không을 붙여요. 직역하면 '~있다 ... ~없다?' 구조예요.",
           'zh': "問'~합니까？（做~嗎？）'時，在謂語前加 có，在句末加 không。直譯的話是'~有…~沒有？'的結構。",
           'en': "When asking '~합니까?' (Do you ~?), put có before the predicate and không at the "
                 "end of the sentence. Literally, it's structured like '~ have ... ~ not have?'",
           'ja': '「~합니까？」と尋ねるときは、述語の前に có、文末に không を付けます。直訳すると「~ある…~ない？」という構造です。',
           'de': 'Bei der Frage „... tust du ...?“ setzt man „có“ vor das Prädikat und „không“ an '
                 'das Satzende. Wörtlich entspricht dies dem Schema „... vorhanden ... nicht '
                 'vorhanden?“.'},
  'steps': [{'vi': 'Bạn ăn cơm.',
             'pairs': [['Bạn', {'ko': '너', 'zh': '你', 'en': 'you', 'ja': 'お前、君', 'de': 'du'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる', 'de': 'essen'}],
                       ['cơm.',
                        {'ko': '밥',
                         'zh': '飯',
                         'en': 'rice / meal',
                         'ja': 'ご飯',
                         'de': 'Reis / Essen'}]],
             'kr': ''},
            {'vi': 'Bạn có ăn cơm không?',
             'pairs': [['Bạn', {'ko': '너', 'zh': '你', 'en': 'you', 'ja': 'お前、君', 'de': 'du'}],
                       ['có',
                        {'ko': '(의문)있다',
                         'zh': '（疑問）有',
                         'en': '(question) have / there is',
                         'ja': '（疑問）ある',
                         'de': '(Fragepartikel)'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる', 'de': 'essen'}],
                       ['cơm',
                        {'ko': '밥',
                         'zh': '飯',
                         'en': 'rice / meal',
                         'ja': 'ご飯',
                         'de': 'Reis / Essen'}],
                       ['không?',
                        {'ko': '(의문)없다',
                         'zh': '（疑問）沒有',
                         'en': "(question) not have / there isn't",
                         'ja': '（疑問）ない',
                         'de': '(Fragepartikel / nicht?)'}]],
             'kr': {'ko': '너 밥 먹어?',
                    'zh': '你吃飯嗎?',
                    'en': 'Are you eating?',
                    'ja': 'ご飯食べる?',
                    'de': 'Isst du?'}}]},
 {'title': {'ko': '12. 의문문 — 완료 여부 (~ chưa?)',
            'zh': '12. 疑問句 — 是否完成（~ chưa？）',
            'en': '12. Questions about completion (~ chưa?)',
            'ja': '12. 疑問文 — 完了かどうか（~ chưa？）',
            'de': '12. Fragen nach Vollendung (~ chưa?)'},
  'note': {'ko': "'아직 ~했어요?'처럼 이미 했는지를 물을 땐 문장 끝에 chưa?를 붙여요. 대답은 '이미 했다' rồi, '아직 안 했다' chưa. 단, "
                 '대답에서 chưa는 동사 앞으로 자리를 옮겨요.',
           'zh': "像'還~了嗎？'一樣，問是否已經做了某事時，在句末加 chưa？回答是'已經做了'用 rồi，'還沒做'用 chưa。不過，回答中的 chưa 要移到動詞前面。",
           'en': "When asking whether something has already been done, like 'Have you ~ yet?', add "
                 "chưa? at the end of the sentence. The answer is rồi for 'already done' and chưa "
                 "for 'not yet'. However, in the answer, chưa moves to before the verb.",
           'ja': '「まだ~しましたか？」のように、すでにしたかどうかを尋ねるときは、文末に chưa？を付けます。答えは「すでにした」rồi、「まだしていない」chưa '
                 'です。ただし、答えの中では chưa は動詞の前に位置が移ります。',
           'de': 'Um zu fragen, ob etwas bereits getan wurde („Hast du schon ...?“), hängt man '
                 '„chưa?“ an das Satzende. Die Antwort lautet „rồi“ für „bereits getan“ und „chưa“ '
                 'für „noch nicht“. In der Antwort wandert „chưa“ jedoch vor das Verb.'},
  'steps': [{'vi': 'Bạn ăn cơm chưa?',
             'pairs': [['Bạn', {'ko': '너', 'zh': '你', 'en': 'you', 'ja': 'お前、君', 'de': 'du'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる', 'de': 'essen'}],
                       ['cơm',
                        {'ko': '밥',
                         'zh': '飯',
                         'en': 'rice / meal',
                         'ja': 'ご飯',
                         'de': 'Reis / Essen'}],
                       ['chưa?',
                        {'ko': '(완료?)아직',
                         'zh': '（完成？）還沒',
                         'en': '(Completed?) Not yet',
                         'ja': '（完了？）まだ',
                         'de': '(schon / noch nicht?)'}]],
             'kr': {'ko': '너 밥 먹었어?',
                    'zh': '你吃飯了嗎?',
                    'en': 'Did you eat?',
                    'ja': 'ご飯食べた?',
                    'de': 'Hast du schon gegessen?'}},
            {'vi': 'Tôi ăn cơm rồi.',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私', 'de': 'ich'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる', 'de': 'essen'}],
                       ['cơm',
                        {'ko': '밥',
                         'zh': '飯',
                         'en': 'rice / meal',
                         'ja': 'ご飯',
                         'de': 'Reis / Essen'}],
                       ['rồi.',
                        {'ko': '이미(완료)',
                         'zh': '已經(完成)',
                         'en': 'already (completed)',
                         'ja': 'すでに(完了)',
                         'de': 'schon / bereits'}]],
             'kr': {'ko': '나는 밥을 (이미) 먹었어.',
                    'zh': '我(已經)吃過飯了。',
                    'en': 'I already ate.',
                    'ja': '私はご飯を(すでに)食べた。',
                    'de': 'Ich habe schon gegessen.'}},
            {'vi': 'Tôi chưa ăn cơm.',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私', 'de': 'ich'}],
                       ['chưa',
                        {'ko': '아직 (안)',
                         'zh': '還（沒）',
                         'en': 'not yet',
                         'ja': 'まだ（〜ない）',
                         'de': 'noch nicht'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる', 'de': 'essen'}],
                       ['cơm.',
                        {'ko': '밥',
                         'zh': '飯',
                         'en': 'rice / meal',
                         'ja': 'ご飯',
                         'de': 'Reis / Essen'}]],
             'kr': {'ko': '나는 아직 밥을 안 먹었어.',
                    'zh': '我還沒吃飯。',
                    'en': "I haven't eaten yet.",
                    'ja': '私はまだご飯を食べていない。',
                    'de': 'Ich habe noch nicht gegessen.'}}]},
 {'title': {'ko': '13. 의문문 — 의문사 (누가·무엇·어디·언제·왜·어떻게)',
            'zh': '13. 疑問句 — 疑問詞（誰·什麼·哪裡·何時·為什麼·怎麼）',
            'en': '13. Question words (who, what, where, when, why, how)',
            'ja': '13. 疑問文 — 疑問詞（誰・何・どこ・いつ・なぜ・どのように）',
            'de': '13. Fragewörter (wer, was, wo, wann, warum, wie)'},
  'note': {'ko': '의문사는 대개 원래 그 말이 있던 자리에 그대로 들어가요 — ai(누가)는 주어 자리, gì(무엇)는 목적어 자리, ở đâu(어디서)는 장소 '
                 '자리, khi nào(언제)는 시간 자리, thế nào(어떻게)는 서술어 뒤. 다만 tại sao(왜)는 예외로 문장 맨 앞에 옵니다.',
           'zh': '疑問詞通常放在原本那個詞所在的位置 — ai（誰）放在主語位置，gì（什麼）放在賓語位置，ở đâu（哪裡）放在地點位置，khi '
                 'nào（何時）放在時間位置，thế nào（怎麼樣）放在謂語後面。不過 tại sao（為什麼）是例外，放在句子最前面。',
           'en': 'Interrogative words usually go in the same position the corresponding word would '
                 'normally occupy — ai (who) goes in the subject position, gì (what) in the object '
                 'position, ở đâu (where) in the place position, khi nào (when) in the time '
                 'position, and thế nào (how) after the predicate. However, tại sao (why) is an '
                 'exception and comes at the very beginning of the sentence.',
           'ja': '疑問詞は通常、元々その言葉があった位置にそのまま入ります — ai（誰が）は主語の位置、gì（何を）は目的語の位置、ở đâu（どこで）は場所の位置、khi '
                 'nào（いつ）は時間の位置、thế nào（どのように）は述語の後ろ。ただし tại sao（なぜ）は例外で、文の一番前に来ます。',
           'de': 'Fragewörter stehen im Vietnamesischen meist an der Stelle, an der auch die '
                 'gesuchte Information im Aussagesatz stehen würde: ai (wer) an der '
                 'Subjektposition, gì (was) an der Objektposition, ở đâu (wo) an der Ortsposition, '
                 'khi nào (wann) an der Zeitposition und thế nào (wie) nach dem Prädikat. Eine '
                 'Ausnahme bildet tại sao (warum), das ganz an den Satzanfang gestellt wird.'},
  'steps': [{'vi': 'Ai ăn cơm?',
             'pairs': [['Ai', {'ko': '누가', 'zh': '誰', 'en': 'who', 'ja': '誰が', 'de': 'wer'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる', 'de': 'essen'}],
                       ['cơm?',
                        {'ko': '밥',
                         'zh': '飯',
                         'en': 'rice / meal',
                         'ja': 'ご飯',
                         'de': 'Reis / Essen'}]],
             'kr': {'ko': '누가 밥을 먹어요?',
                    'zh': '誰吃飯？',
                    'en': 'Who eats rice?',
                    'ja': '誰がご飯を食べますか？',
                    'de': 'Wer isst Reis?'}},
            {'vi': 'Bạn ăn gì?',
             'pairs': [['Bạn', {'ko': '너', 'zh': '你', 'en': 'you', 'ja': 'お前、君', 'de': 'du'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる', 'de': 'essen'}],
                       ['gì?', {'ko': '무엇', 'zh': '什麼', 'en': 'what', 'ja': '何', 'de': 'was'}]],
             'kr': {'ko': '너 뭐 먹어?',
                    'zh': '你吃什麼?',
                    'en': 'What are you eating?',
                    'ja': '何食べる?',
                    'de': 'Was isst du?'}},
            {'vi': 'Bạn ăn cơm ở đâu?',
             'pairs': [['Bạn', {'ko': '너', 'zh': '你', 'en': 'you', 'ja': 'お前、君', 'de': 'du'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる', 'de': 'essen'}],
                       ['cơm',
                        {'ko': '밥',
                         'zh': '飯',
                         'en': 'rice / meal',
                         'ja': 'ご飯',
                         'de': 'Reis / Essen'}],
                       ['ở đâu?',
                        {'ko': '어디에서', 'zh': '在哪裡', 'en': 'where', 'ja': 'どこで', 'de': 'wo'}]],
             'kr': {'ko': '너 어디서 밥 먹어?',
                    'zh': '你在哪裡吃飯？',
                    'en': 'Where do you eat?',
                    'ja': 'あなたはどこでご飯を食べる？',
                    'de': 'Wo isst du?'}},
            {'vi': 'Bạn ăn cơm khi nào?',
             'pairs': [['Bạn', {'ko': '너', 'zh': '你', 'en': 'you', 'ja': 'お前、君', 'de': 'du'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる', 'de': 'essen'}],
                       ['cơm',
                        {'ko': '밥',
                         'zh': '飯',
                         'en': 'rice / meal',
                         'ja': 'ご飯',
                         'de': 'Reis / Essen'}],
                       ['khi nào?',
                        {'ko': '언제', 'zh': '什麼時候', 'en': 'when', 'ja': 'いつ', 'de': 'wann'}]],
             'kr': {'ko': '너 언제 밥 먹어?',
                    'zh': '你什麼時候吃飯？',
                    'en': 'When do you eat?',
                    'ja': 'あなたはいつご飯を食べる？',
                    'de': 'Wann isst du?'}},
            {'vi': 'Tại sao bạn ăn cơm?',
             'pairs': [['Tại sao',
                        {'ko': '왜', 'zh': '為什麼', 'en': 'why', 'ja': 'なぜ', 'de': 'warum'}],
                       ['bạn', {'ko': '너', 'zh': '你', 'en': 'you', 'ja': 'お前、君', 'de': 'du'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる', 'de': 'essen'}],
                       ['cơm?',
                        {'ko': '밥',
                         'zh': '飯',
                         'en': 'rice / meal',
                         'ja': 'ご飯',
                         'de': 'Reis / Essen'}]],
             'kr': {'ko': '너 왜 밥 먹어?',
                    'zh': '你為什麼吃飯？',
                    'en': 'Why do you eat?',
                    'ja': 'あなたはなぜご飯を食べる？',
                    'de': 'Warum isst du?'}},
            {'vi': 'Cơm thế nào?',
             'pairs': [['Cơm',
                        {'ko': '밥',
                         'zh': '飯',
                         'en': 'rice / meal',
                         'ja': 'ご飯',
                         'de': 'Reis / Essen'}],
                       ['thế nào?',
                        {'ko': '어때',
                         'zh': '怎麼樣',
                         'en': 'How about (it)?',
                         'ja': 'どう？',
                         'de': 'wie'}]],
             'kr': {'ko': '밥 어때?',
                    'zh': '吃飯怎麼樣？',
                    'en': 'How about rice?',
                    'ja': 'ご飯はどう？',
                    'de': 'Wie ist das Essen?'}}]},
 {'title': {'ko': '14. 의문문 — 선택 의문문 (A hay B?)',
            'zh': '14. 疑問句 — 選擇疑問句（A hay B？）',
            'en': '14. Alternative questions (A hay B?)',
            'ja': '14. 疑問文 — 選択疑問文（A hay B？）',
            'de': '14. Alternativfragen (A hay B?)'},
  'note': {'ko': "hay(아니면·또는)로 두 선택지를 이으면 'A할래 B할래?' 같은 선택 의문문이 돼요.",
           'zh': "用 hay（或者·或是）連接兩個選項，就變成'要A還是要B？'這樣的選擇疑問句。",
           'en': "Connecting two options with hay (or) forms an alternative question like 'Do you "
                 "want A or B?'",
           'ja': 'hay（あるいは・または）で2つの選択肢をつなぐと、「Aする？Bする？」のような選択疑問文になります。',
           'de': 'Wenn man zwei Optionen mit „hay“ (oder) verbindet, bildet man eine Auswahlsatz- '
                 'bzw. Alternativfrage wie „Möchtest du A oder B?“.'},
  'steps': [{'vi': 'Bạn ăn cơm.',
             'pairs': [['Bạn', {'ko': '너', 'zh': '你', 'en': 'you', 'ja': 'お前、君', 'de': 'du'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる', 'de': 'essen'}],
                       ['cơm.',
                        {'ko': '밥',
                         'zh': '飯',
                         'en': 'rice / meal',
                         'ja': 'ご飯',
                         'de': 'Reis / Essen'}]],
             'kr': ''},
            {'vi': 'Bạn ăn cơm hay ăn phở?',
             'pairs': [['Bạn', {'ko': '너', 'zh': '你', 'en': 'you', 'ja': 'お前、君', 'de': 'du'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる', 'de': 'essen'}],
                       ['cơm',
                        {'ko': '밥',
                         'zh': '飯',
                         'en': 'rice / meal',
                         'ja': 'ご飯',
                         'de': 'Reis / Essen'}],
                       ['hay', {'ko': '아니면', 'zh': '或者', 'en': 'or', 'ja': 'それとも', 'de': 'oder'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる', 'de': 'essen'}],
                       ['phở?',
                        {'ko': '쌀국수',
                         'zh': '河粉',
                         'en': 'rice noodles (phở)',
                         'ja': 'フォー（米粉麺）',
                         'de': 'Phở (Nudelsuppe)'}]],
             'kr': {'ko': '밥 먹을래 아니면 쌀국수 먹을래?',
                    'zh': '你要吃飯還是吃米粉？',
                    'en': 'Do you want to eat rice or pho (rice noodles)?',
                    'ja': 'ご飯を食べる？それとも米粉（フォー）を食べる？',
                    'de': 'Möchtest du Reis oder Phở essen?'}}]},
 {'title': {'ko': '15. 접속어로 문장 잇기',
            'zh': '15. 用連接詞連接句子',
            'en': '15. Connecting sentences with conjunctions',
            'ja': '15. 接続語で文をつなぐ',
            'de': '15. Sätze mit Konjunktionen verbinden'},
  'note': {'ko': 'và(그리고), nhưng(그러나), vì...nên(~때문에 ~하다)로 짧은 문장 두 개를 이어 더 긴 문장을 만들 수 있어요.',
           'zh': '用 và（而且）、nhưng（但是）、vì...nên（因為~所以~）可以把兩個短句連接成更長的句子。',
           'en': 'You can connect two short sentences into a longer one using và (and), nhưng '
                 '(but), and vì...nên (because ~, so ~).',
           'ja': 'và（そして）、nhưng（しかし）、vì...nên（~なので~する）を使って、2つの短い文をつないでより長い文を作ることができます。',
           'de': 'Man kann zwei kurze Sätze mit và (und), nhưng (aber) oder vì...nên (weil ..., '
                 'deshalb ...) zu einem längeren Satz verbinden.'},
  'steps': [{'vi': 'Tôi ăn cơm và tôi uống nước.',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私', 'de': 'ich'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる', 'de': 'essen'}],
                       ['cơm',
                        {'ko': '밥',
                         'zh': '飯',
                         'en': 'rice / meal',
                         'ja': 'ご飯',
                         'de': 'Reis / Essen'}],
                       ['và', {'ko': '그리고', 'zh': '而且,和', 'en': 'and', 'ja': 'そして', 'de': 'und'}],
                       ['tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私', 'de': 'ich, mir'}],
                       ['uống',
                        {'ko': '마시다', 'zh': '喝', 'en': 'to drink', 'ja': '飲む', 'de': 'trinken'}],
                       ['nước.', {'ko': '물', 'zh': '水', 'en': 'water', 'ja': '水', 'de': 'Wasser'}]],
             'kr': {'ko': '나는 밥을 먹고 물을 마신다.',
                    'zh': '我吃飯然後喝水。',
                    'en': 'I eat and drink water.',
                    'ja': '私はご飯を食べて水を飲む。',
                    'de': 'Ich esse und trinke Wasser.'}},
            {'vi': 'Tôi thích cơm nhưng tôi không thích nước.',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私', 'de': 'ich'}],
                       ['thích',
                        {'ko': '좋아하다',
                         'zh': '喜歡',
                         'en': 'to like',
                         'ja': '好きだ',
                         'de': 'mögen / gefallen'}],
                       ['cơm',
                        {'ko': '밥',
                         'zh': '飯',
                         'en': 'rice / meal',
                         'ja': 'ご飯',
                         'de': 'Reis / Essen'}],
                       ['nhưng',
                        {'ko': '그러나', 'zh': '但是', 'en': 'but, however', 'ja': 'しかし', 'de': 'aber'}],
                       ['tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私', 'de': 'ich, mir'}],
                       ['không', {'ko': '안', 'zh': '裡面', 'en': 'inside', 'ja': '中', 'de': 'nicht'}],
                       ['thích',
                        {'ko': '좋아하다',
                         'zh': '喜歡',
                         'en': 'to like',
                         'ja': '好きだ',
                         'de': 'mögen / gefallen'}],
                       ['nước.', {'ko': '물', 'zh': '水', 'en': 'water', 'ja': '水', 'de': 'Wasser'}]],
             'kr': {'ko': '나는 밥은 좋아하지만 물은 안 좋아한다.',
                    'zh': '我喜歡飯,但不喜歡水。',
                    'en': "I like rice but I don't like water.",
                    'ja': '私はご飯は好きだが、水は好きではない。',
                    'de': 'Ich mag Reis, aber ich mag kein Wasser.'}},
            {'vi': 'Vì tôi đói nên tôi ăn cơm.',
             'pairs': [['Vì',
                        {'ko': '~때문에',
                         'zh': '因為~',
                         'en': 'because of ~',
                         'ja': '~のために',
                         'de': 'weil'}],
                       ['tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私', 'de': 'ich, mir'}],
                       ['đói',
                        {'ko': '배고프다',
                         'zh': '餓',
                         'en': 'to be hungry',
                         'ja': 'お腹がすく',
                         'de': 'hungrig sein'}],
                       ['nên',
                        {'ko': '그래서',
                         'zh': '所以',
                         'en': 'so, therefore',
                         'ja': 'それで',
                         'de': 'deshalb / so'}],
                       ['tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私', 'de': 'ich, mir'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる', 'de': 'essen'}],
                       ['cơm.',
                        {'ko': '밥',
                         'zh': '飯',
                         'en': 'rice / meal',
                         'ja': 'ご飯',
                         'de': 'Reis / Essen'}]],
             'kr': {'ko': '나는 배가 고파서 밥을 먹는다.',
                    'zh': '我因為肚子餓所以吃飯。',
                    'en': "I eat because I'm hungry.",
                    'ja': '私はお腹が空いたのでご飯を食べる。',
                    'de': 'Weil ich Hunger habe, esse ich.'}}]},
 {'title': {'ko': '16. 다양한 동사로 연습 — đọc sách (책 읽기)',
            'zh': '16. 用各種動詞練習 — đọc sách（讀書）',
            'en': '16. Practice with various verbs — đọc sách (reading a book)',
            'ja': '16. さまざまな動詞で練習 — đọc sách（本を読む）',
            'de': '16. Übung mit verschiedenen Verben — đọc sách (ein Buch lesen)'},
  'note': {'ko': '지금까지 배운 문형을 다른 동사·목적어로 연습해요. đọc(읽다) + sách(책).',
           'zh': '用不同的動詞·賓語練習到目前為止學過的句型。đọc(讀)+ sách(書)。',
           'en': 'Practice the sentence pattern learned so far with different verbs and objects. '
                 'đọc (to read) + sách (book).',
           'ja': 'これまで学んだ文型を別の動詞·目的語で練習しましょう。đọc(読む)+ sách(本)。',
           'de': 'Üben Sie das bisher gelernte Satzmuster mit verschiedenen Verben und Objekten: '
                 'đọc (lesen) + sách (Buch).'},
  'steps': [{'vi': 'Tôi đọc.',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私', 'de': 'ich'}],
                       ['đọc.',
                        {'ko': '읽다', 'zh': '讀', 'en': 'to read', 'ja': '読む', 'de': 'lesen'}]],
             'kr': {'ko': '나는 읽는다.',
                    'zh': '我讀。',
                    'en': 'I read.',
                    'ja': '私は読む。',
                    'de': 'Ich lese.'}},
            {'vi': 'Tôi đọc sách.',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私', 'de': 'ich'}],
                       ['đọc', {'ko': '읽다', 'zh': '讀', 'en': 'to read', 'ja': '読む', 'de': 'lesen'}],
                       ['sách.', {'ko': '책', 'zh': '書', 'en': 'book', 'ja': '本', 'de': 'Buch'}]],
             'kr': {'ko': '나는 책을 읽는다.',
                    'zh': '我讀書。',
                    'en': 'I read a book.',
                    'ja': '私は本を読む。',
                    'de': 'Ich lese ein Buch.'}},
            {'vi': 'Tôi thường đọc sách ở nhà vào buổi tối.',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私', 'de': 'ich'}],
                       ['thường',
                        {'ko': '보통',
                         'zh': '通常',
                         'en': 'usually / normal',
                         'ja': '普通',
                         'de': 'gewöhnlich / normalerweise'}],
                       ['đọc', {'ko': '읽다', 'zh': '讀', 'en': 'to read', 'ja': '読む', 'de': 'lesen'}],
                       ['sách', {'ko': '책', 'zh': '書', 'en': 'book', 'ja': '本', 'de': 'Buch'}],
                       ['ở',
                        {'ko': '~에서',
                         'zh': '在~（從……/在某地）',
                         'en': 'at/from ~',
                         'ja': '~で（場所）',
                         'de': 'in / an'}],
                       ['nhà',
                        {'ko': '집', 'zh': '家', 'en': 'house', 'ja': '家', 'de': 'Haus / Zuhause'}],
                       ['vào',
                        {'ko': '~에',
                         'zh': '在~（時間/地點）',
                         'en': 'at/in/to ~',
                         'ja': '~に',
                         'de': 'an / am'}],
                       ['buổi tối.',
                        {'ko': '저녁', 'zh': '晚上', 'en': 'evening', 'ja': '夕方', 'de': 'Abend'}]],
             'kr': {'ko': '나는 보통 저녁에 집에서 책을 읽는다.',
                    'zh': '我通常晚上在家看書。',
                    'en': 'I usually read books at home in the evening.',
                    'ja': '私はふだん夕方に家で本を読む。',
                    'de': 'Ich lese abends gewöhnlich zu Hause ein Buch.'}}]},
 {'title': {'ko': '17. 다양한 동사로 연습 — đi nhóm họp (집회 가기)',
            'zh': '17. 用各種動詞練習 — đi nhóm họp（去聚會）',
            'en': '17. Practice with various verbs — đi nhóm họp (going to the meeting)',
            'ja': '17. さまざまな動詞で練習 — đi nhóm họp（集会に行く）',
            'de': '17. Übung mit verschiedenen Verben — đi nhóm họp (zur Zusammenkunft gehen)'},
  'note': {'ko': 'đi(가다) + nhóm họp(집회).',
           'zh': 'đi（去）+ nhóm họp（聚會）。',
           'en': 'đi (to go) + nhóm họp (meeting).',
           'ja': 'đi（行く）+ nhóm họp（集会）。',
           'de': 'đi (gehen) + nhóm họp (Zusammenkunft).'},
  'steps': [{'vi': 'Tôi đi.',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私', 'de': 'ich'}],
                       ['đi.', {'ko': '가다', 'zh': '去', 'en': 'to go', 'ja': '行く', 'de': 'gehen'}]],
             'kr': {'ko': '나는 간다.', 'zh': '我去。', 'en': 'I go.', 'ja': '私は行く。', 'de': 'Ich gehe.'}},
            {'vi': 'Tôi đi nhóm họp.',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私', 'de': 'ich'}],
                       ['đi', {'ko': '가다', 'zh': '去', 'en': 'to go', 'ja': '行く', 'de': 'gehen'}],
                       ['nhóm họp.',
                        {'ko': '집회',
                         'zh': '聚會',
                         'en': 'meeting',
                         'ja': '集会',
                         'de': 'Zusammenkunft'}]],
             'kr': {'ko': '나는 집회에 간다.',
                    'zh': '我去聚會。',
                    'en': 'I go to the meeting.',
                    'ja': '私は集会に行く。',
                    'de': 'Ich gehe zur Zusammenkunft.'}},
            {'vi': 'Tôi muốn đi nhóm họp vào buổi tối.',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私', 'de': 'ich'}],
                       ['muốn',
                        {'ko': '~하고 싶다',
                         'zh': '想要~',
                         'en': 'want to ~',
                         'ja': '~したい',
                         'de': 'möchten / wollen'}],
                       ['đi', {'ko': '가다', 'zh': '去', 'en': 'to go', 'ja': '行く', 'de': 'gehen'}],
                       ['nhóm họp',
                        {'ko': '집회',
                         'zh': '聚會',
                         'en': 'meeting',
                         'ja': '集会',
                         'de': 'Zusammenkunft'}],
                       ['vào',
                        {'ko': '~에',
                         'zh': '在~（時間/地點）',
                         'en': 'at/in/to ~',
                         'ja': '~に',
                         'de': 'an / am'}],
                       ['buổi tối.',
                        {'ko': '저녁', 'zh': '晚上', 'en': 'evening', 'ja': '夕方', 'de': 'Abend'}]],
             'kr': {'ko': '나는 저녁에 집회에 가고 싶다.',
                    'zh': '我晚上想去聚會。',
                    'en': 'I want to go to the meeting in the evening.',
                    'ja': '私は夕方に集会に行きたい。',
                    'de': 'Ich möchte abends zur Zusammenkunft gehen.'}},
            {'vi': 'Bạn có đi nhóm họp không?',
             'pairs': [['Bạn', {'ko': '너', 'zh': '你', 'en': 'you', 'ja': 'お前、君', 'de': 'du'}],
                       ['có',
                        {'ko': '(의문)있다',
                         'zh': '（疑問）有',
                         'en': '(question) have / there is',
                         'ja': '（疑問）ある',
                         'de': '(Fragepartikel)'}],
                       ['đi', {'ko': '가다', 'zh': '去', 'en': 'to go', 'ja': '行く', 'de': 'gehen'}],
                       ['nhóm họp',
                        {'ko': '집회',
                         'zh': '聚會',
                         'en': 'meeting',
                         'ja': '集会',
                         'de': 'Zusammenkunft'}],
                       ['không?',
                        {'ko': '(의문)없다',
                         'zh': '（疑問）沒有',
                         'en': "(question) not have / there isn't",
                         'ja': '（疑問）ない',
                         'de': '(Fragepartikel / nicht?)'}]],
             'kr': {'ko': '너 집회에 가?',
                    'zh': '你去聚會嗎？',
                    'en': 'Are you going to the meeting?',
                    'ja': 'あなたは集会に行く？',
                    'de': 'Gehst du zur Zusammenkunft?'}}]},
 {'title': {'ko': '18. 다양한 동사로 연습 — học Kinh Thánh (성경 공부하기)',
            'zh': '18. 用各種動詞練習 — học Kinh Thánh（學習聖經）',
            'en': '18. Practice with various verbs — học Kinh Thánh (studying the Bible)',
            'ja': '18. さまざまな動詞で練習 — học Kinh Thánh（聖書を学ぶ）',
            'de': '18. Übung mit verschiedenen Verben — học Kinh Thánh (die Bibel studieren)'},
  'note': {'ko': 'học(공부하다) + Kinh Thánh(성경).',
           'zh': 'học（學習）+ Kinh Thánh（聖經）。',
           'en': 'học (to study) + Kinh Thánh (the Bible).',
           'ja': 'học（勉強する）+ Kinh Thánh（聖書）。',
           'de': 'học (lernen / studieren) + Kinh Thánh (die Bibel).'},
  'steps': [{'vi': 'Tôi học.',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私', 'de': 'ich'}],
                       ['học.',
                        {'ko': '공부하다',
                         'zh': '學習',
                         'en': 'to study',
                         'ja': '勉強する',
                         'de': 'lernen / studieren'}]],
             'kr': {'ko': '나는 공부한다.',
                    'zh': '我學習。',
                    'en': 'I study.',
                    'ja': '私は勉強する。',
                    'de': 'Ich lerne.'}},
            {'vi': 'Tôi học Kinh Thánh.',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私', 'de': 'ich'}],
                       ['học',
                        {'ko': '공부하다',
                         'zh': '學習',
                         'en': 'to study',
                         'ja': '勉強する',
                         'de': 'lernen / studieren'}],
                       ['Kinh Thánh.',
                        {'ko': '성경',
                         'zh': '聖經',
                         'en': 'the Bible',
                         'ja': '聖書',
                         'de': 'die Bibel'}]],
             'kr': {'ko': '나는 성경을 공부한다.',
                    'zh': '我研讀聖經。',
                    'en': 'I study the Bible.',
                    'ja': '私は聖書を勉強する。',
                    'de': 'Ich studiere die Bibel.'}},
            {'vi': 'Tôi muốn học Kinh Thánh mỗi ngày.',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私', 'de': 'ich'}],
                       ['muốn',
                        {'ko': '~하고 싶다',
                         'zh': '想要~',
                         'en': 'want to ~',
                         'ja': '~したい',
                         'de': 'möchten / wollen'}],
                       ['học',
                        {'ko': '공부하다',
                         'zh': '學習',
                         'en': 'to study',
                         'ja': '勉強する',
                         'de': 'lernen / studieren'}],
                       ['Kinh Thánh',
                        {'ko': '성경', 'zh': '聖經', 'en': 'the Bible', 'ja': '聖書', 'de': 'die Bibel'}],
                       ['mỗi ngày.',
                        {'ko': '매일',
                         'zh': '每天',
                         'en': 'every day',
                         'ja': '毎日',
                         'de': 'jeden Tag'}]],
             'kr': {'ko': '나는 매일 성경을 공부하고 싶다.',
                    'zh': '我想每天研讀聖經。',
                    'en': 'I want to study the Bible every day.',
                    'ja': '私は毎日聖書を勉強したい。',
                    'de': 'Ich möchte jeden Tag die Bibel studieren.'}}]},
 {'title': {'ko': '19. 다양한 동사로 연습 — Bạn đi làm (일하러 가기)',
            'zh': '19. 用各種動詞練習 — Bạn đi làm（去工作）',
            'en': '19. Practice with various verbs — Bạn đi làm (going to work)',
            'ja': '19. さまざまな動詞で練習 — Bạn đi làm（仕事に行く）',
            'de': '19. Übung mit verschiedenen Verben — Bạn đi làm (zur Arbeit gehen)'},
  'note': {'ko': "làm(일하다)이 đi 뒤에 오면 '일하러(출근)'라는 뜻이 돼요. 상대방(bạn·너)을 주어로 연습해요.",
           'zh': "làm（工作）放在 đi 後面，就變成'去工作（上班）'的意思。用對方（bạn·你）作主語來練習。",
           'en': "When làm (to work) follows đi, it means 'to go to work (commute)'. Practice "
                 'using the other person (bạn, you) as the subject.',
           'ja': 'làm（働く）が đi の後ろに来ると、「働きに（出勤）」という意味になります。相手（bạn・あなた）を主語にして練習します。',
           'de': 'Wenn làm (arbeiten) auf đi folgt, bedeutet es „zur Arbeit gehen / pendeln“. Üben '
                 'Sie mit dem Gegenüber (bạn, du) als Subjekt.'},
  'steps': [{'vi': 'Bạn đi.',
             'pairs': [['Bạn', {'ko': '너', 'zh': '你', 'en': 'you', 'ja': 'お前、君', 'de': 'du'}],
                       ['đi.', {'ko': '가다', 'zh': '去', 'en': 'to go', 'ja': '行く', 'de': 'gehen'}]],
             'kr': {'ko': '너는 간다.',
                    'zh': '你去。',
                    'en': 'You go.',
                    'ja': 'あなたは行く。',
                    'de': 'Du gehst.'}},
            {'vi': 'Bạn đi làm.',
             'pairs': [['Bạn', {'ko': '너', 'zh': '你', 'en': 'you', 'ja': 'お前、君', 'de': 'du'}],
                       ['đi', {'ko': '가다', 'zh': '去', 'en': 'to go', 'ja': '行く', 'de': 'gehen'}],
                       ['làm.',
                        {'ko': '일(하러)',
                         'zh': '工作(去做)',
                         'en': 'work (to do)',
                         'ja': '仕事(をしに)',
                         'de': 'arbeiten (gehen)'}]],
             'kr': {'ko': '너는 일하러 간다.',
                    'zh': '你去工作。',
                    'en': 'You go to work.',
                    'ja': 'あなたは働きに行く。',
                    'de': 'Du gehst zur Arbeit.'}},
            {'vi': 'Bạn có đi làm không?',
             'pairs': [['Bạn', {'ko': '너', 'zh': '你', 'en': 'you', 'ja': 'お前、君', 'de': 'du'}],
                       ['có',
                        {'ko': '(의문)있다',
                         'zh': '（疑問）有',
                         'en': '(question) have / there is',
                         'ja': '（疑問）ある',
                         'de': '(Fragepartikel)'}],
                       ['đi', {'ko': '가다', 'zh': '去', 'en': 'to go', 'ja': '行く', 'de': 'gehen'}],
                       ['làm',
                        {'ko': '일(하러)',
                         'zh': '工作(去做)',
                         'en': 'work (to do)',
                         'ja': '仕事(をしに)',
                         'de': 'arbeiten (gehen)'}],
                       ['không?',
                        {'ko': '(의문)없다',
                         'zh': '（疑問）沒有',
                         'en': "(question) not have / there isn't",
                         'ja': '（疑問）ない',
                         'de': '(Fragepartikel / nicht?)'}]],
             'kr': {'ko': '너 출근해?',
                    'zh': '你去上班嗎？',
                    'en': 'Are you going to work?',
                    'ja': 'あなたは出勤する？',
                    'de': 'Gehst du zur Arbeit?'}}]},
 {'title': {'ko': '20. 다양한 동사로 연습 — Bạn đi học (공부하러 가기)',
            'zh': '20. 用各種動詞練習 — Bạn đi học（去學習）',
            'en': '20. Practice with various verbs — Bạn đi học (going to study)',
            'ja': '20. さまざまな動詞で練習 — Bạn đi học（勉強しに行く）',
            'de': '20. Übung mit verschiedenen Verben — Bạn đi học (zur Schule gehen / lernen '
                  'gehen)'},
  'note': {'ko': "học(공부하다)이 đi 뒤에 오면 '공부하러(학교에)'라는 뜻이 돼요.",
           'zh': "học（學習）放在 đi 後面，就變成'去學習（上學）'的意思。",
           'en': "When học (to study) follows đi, it means 'to go study (at school)'.",
           'ja': 'học（勉強する）が đi の後ろに来ると、「勉強しに（学校へ）」という意味になります。',
           'de': 'Wenn học (lernen) auf đi folgt, bedeutet es „zur Schule gehen / lernen gehen“.'},
  'steps': [{'vi': 'Bạn đi.',
             'pairs': [['Bạn', {'ko': '너', 'zh': '你', 'en': 'you', 'ja': 'お前、君', 'de': 'du'}],
                       ['đi.', {'ko': '가다', 'zh': '去', 'en': 'to go', 'ja': '行く', 'de': 'gehen'}]],
             'kr': {'ko': '너는 간다.',
                    'zh': '你去。',
                    'en': 'You go.',
                    'ja': 'あなたは行く。',
                    'de': 'Du gehst.'}},
            {'vi': 'Bạn đi học.',
             'pairs': [['Bạn', {'ko': '너', 'zh': '你', 'en': 'you', 'ja': 'お前、君', 'de': 'du'}],
                       ['đi', {'ko': '가다', 'zh': '去', 'en': 'to go', 'ja': '行く', 'de': 'gehen'}],
                       ['học.',
                        {'ko': '공부(하러)',
                         'zh': '（去）學習',
                         'en': '(to go) study',
                         'ja': '勉強（しに）',
                         'de': 'lernen (gehen)'}]],
             'kr': {'ko': '너는 학교에 간다.',
                    'zh': '你去學校。',
                    'en': 'You go to school.',
                    'ja': 'あなたは学校に行く。',
                    'de': 'Du gehst zur Schule.'}},
            {'vi': 'Bạn đi học chưa?',
             'pairs': [['Bạn', {'ko': '너', 'zh': '你', 'en': 'you', 'ja': 'お前、君', 'de': 'du'}],
                       ['đi', {'ko': '가다', 'zh': '去', 'en': 'to go', 'ja': '行く', 'de': 'gehen'}],
                       ['học',
                        {'ko': '공부(하러)',
                         'zh': '（去）學習',
                         'en': '(to go) study',
                         'ja': '勉強（しに）',
                         'de': 'lernen (gehen)'}],
                       ['chưa?',
                        {'ko': '(완료?)아직',
                         'zh': '（完成？）還沒',
                         'en': '(Completed?) Not yet',
                         'ja': '（完了？）まだ',
                         'de': '(schon / noch nicht?)'}]],
             'kr': {'ko': '너 학교 갔어?',
                    'zh': '你去學校了嗎？',
                    'en': 'Did you go to school?',
                    'ja': 'あなたは学校に行った？',
                    'de': 'Bist du schon zur Schule gegangen?'}}]}]
