# "문법 및 작문 연습" tab data.
#
# Teaches Vietnamese sentence structure by growing one short sentence word by word,
# the same technique used in the original PPTX conversation-training deck
# ("Đây → Đây là → Đây là số → Đây là số điện thoại ..."), but organized as a
# grammar curriculum instead of situational dialogue: starting from the smallest
# possible sentence (subject + verb) and adding one grammatical piece at a time
# (object, place, time, adjective, possessive, frequency adverb, modal/auxiliary
# verb, degree adverb, negation, question, connector), reusing a small closed set
# of common subjects/verbs/adjectives/adverbs throughout so the learner sees the
# same words recombine rather than memorizing new vocabulary each step.
#
# Every Vietnamese phrase is stored as "pairs": a list of [vietnamese_segment,
# korean_gloss] tuples, one per word/phrase unit, IN VIETNAMESE WORD ORDER. The
# renderer lays each pair out as its own column (Vietnamese segment on top in
# the bigger accent-colored font, its Korean gloss centered directly underneath
# in a smaller font) so the two lines line up word-for-word even though Vietnamese
# words are wider than their Korean glosses -- rather than two independently
# flowing lines of text that drift out of alignment.
#
# The two headline contrasts with Korean, called out in GRAMMAR_INTRO and then
# re-illustrated inside the units themselves:
#   1. 서술어 위치: Korean is SOV (predicate last); Vietnamese is SVO (predicate
#      right after the subject).
#   2. 수식어 위치: Korean modifies before the noun (adjective + noun); Vietnamese
#      modifies after the noun (noun + adjective) -- same for possessives.
# A third, subtler point is added so the picture isn't over-simplified: not every
# modifier in Vietnamese trails its head word. Frequency/tense/modal words
# (thường, đã, đang, sẽ, phải, muốn ...) sit BEFORE the verb, same relative
# order as Korean, and degree words like "rất" sit BEFORE the adjective they
# intensify. Only the noun-adjective and noun-possessive relationship flips.
#
# "title"/"desc"/"note" and every Korean gloss ("kr" fields, and each pair's second
# element) are stored as {"ko","zh","en","ja"} dicts so js_json() (see build_app.py)
# serializes them straight into JS objects app_logic.js's T() helper can read directly.
# A step with no standalone Korean-sentence translation keeps "kr" as a plain empty
# string (not a dict) -- T() passes a plain string straight through either way.

GRAMMAR_INTRO = [{'title': {'ko': '① 서술어 위치: 한국어는 맨 뒤, 베트남어는 주어 바로 다음',
            'zh': '① 謂語位置：韓語在最後，越南語在主語之後',
            'en': '① Position of the predicate: at the very end in Korean, right after the subject in '
                  'Vietnamese',
            'ja': '① 述語の位置：韓国語は一番最後、ベトナム語は主語のすぐ後'},
  'desc': {'ko': "한국어는 '주어 + 목적어 + 서술어' 순서로 서술어(동사)가 문장 맨 끝에 와요. 베트남어는 '주어 + 서술어 + 목적어' 순서로, 서술어가 주어 바로 다음에 "
                 '와요. 목적어·장소·시간 등은 모두 서술어 뒤에 붙습니다.',
           'zh': '韓語的語序是“主語+賓語+謂語”,謂語(動詞)位於句子的最後。越南語的語序是“主語+謂語+賓語”,謂語緊跟在主語之後。賓語、地點、時間等都放在謂語之後。',
           'en': "Korean follows the order 'subject + object + predicate', with the predicate (verb) coming "
                 "at the very end of the sentence. Vietnamese follows the order 'subject + predicate + "
                 "object', with the predicate coming right after the subject. Objects, places, times, etc. "
                 'all come after the predicate.',
           'ja': '韓国語は「主語+目的語+述語」の順序で、述語(動詞)が文の一番最後に来ます。ベトナム語は「主語+述語+目的語」の順序で、述語が主語のすぐ後に来ます。目的語·場所·時間などはすべて述語の後に付きます。'},
  'examples': [{'kr': {'ko': '나는 밥을 먹는다.', 'zh': '我吃飯。', 'en': 'I eat.', 'ja': '私はご飯を食べる。'},
                'vi': 'Tôi ăn cơm.',
                'pairs': [['Tôi', {'ko': '나(주어)', 'zh': '我(主語)', 'en': 'I (subject)', 'ja': '私(主語)'}],
                          ['ăn',
                           {'ko': '먹다(서술어)', 'zh': '吃（謂語）', 'en': 'to eat (predicate)', 'ja': '食べる（述語）'}],
                          ['cơm.', {'ko': '밥(목적어)', 'zh': '飯（賓語）', 'en': 'rice (object)', 'ja': 'ご飯（目的語）'}]],
                'note': {'ko': '한국어는 서술어가 끝, 베트남어는 서술어가 둘째',
                         'zh': '韓語謂語在最後,越南語謂語在第二位',
                         'en': 'Korean: predicate at the end; Vietnamese: predicate second',
                         'ja': '韓国語は述語が最後、ベトナム語は述語が二番目'}}]},
 {'title': {'ko': '② 수식어 위치: 한국어는 앞에서, 베트남어는 뒤에서',
            'zh': '② 修飾語位置：韓語在前，越南語在後',
            'en': '② Position of modifiers: before the noun in Korean, after it in Vietnamese',
            'ja': '② 修飾語の位置：韓国語は前から、ベトナム語は後ろから'},
  'desc': {'ko': "한국어는 꾸미는 말(형용사, '나의' 같은 소유격)이 꾸밈을 받는 명사 앞에 와요. 베트남어는 반대로, 명사가 먼저 나오고 꾸미는 말이 그 뒤에 붙어요.",
           'zh': '韓語中修飾語(形容詞、像“我的”這樣的所有格)放在被修飾的名詞前面。越南語則相反,名詞先出現,修飾語跟在其後。',
           'en': 'In Korean, modifiers (adjectives, possessives like "my") come before the noun they modify. '
                 "In Vietnamese, it's the opposite — the noun comes first, followed by the modifier.",
           'ja': '韓国語では修飾語(形容詞や「私の」のような所有格)が修飾される名詞の前に来ます。ベトナム語は逆に、名詞が先に来て、修飾語がその後に付きます。'},
  'examples': [{'kr': {'ko': '맛있는 밥', 'zh': '好吃的飯', 'en': 'delicious rice/meal', 'ja': 'おいしいご飯'},
                'vi': 'cơm ngon',
                'pairs': [['cơm', {'ko': '밥(명사)', 'zh': '飯（名詞）', 'en': 'rice (noun)', 'ja': 'ご飯（名詞）'}],
                          ['ngon',
                           {'ko': '맛있는(형용사)',
                            'zh': '好吃的（形容詞）',
                            'en': 'delicious (adjective)',
                            'ja': 'おいしい（形容詞）'}]],
                'note': {'ko': '형용사가 명사 뒤로',
                         'zh': '形容詞放在名詞後面',
                         'en': 'Adjective goes after the noun',
                         'ja': '形容詞が名詞の後ろに'}},
               {'kr': {'ko': '나의 집 / 내 집', 'zh': '我的家 / 我家', 'en': 'my house / my house', 'ja': '私の家 / 私の家'},
                'vi': 'nhà của tôi',
                'pairs': [['nhà', {'ko': '집(명사)', 'zh': '家(名詞)', 'en': 'house (noun)', 'ja': '家(名詞)'}],
                          ['của',
                           {'ko': '의(소유격)', 'zh': '的（所有格）', 'en': "'s (possessive case)", 'ja': 'の（所有格）'}],
                          ['tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私'}]],
                'note': {'ko': '소유격도 명사 뒤로',
                         'zh': '所有格也放在名詞後面',
                         'en': 'The possessive also comes after the noun',
                         'ja': '所有格も名詞の後ろに'}}]},
 {'title': {'ko': '③ 주의: 모든 수식어가 뒤로 가진 않아요',
            'zh': '③ 注意：並非所有修飾語都放在後面',
            'en': '③ Note: not all modifiers go after the noun',
            'ja': '③ 注意：すべての修飾語が後ろに来るわけではありません'},
  'desc': {'ko': '명사를 꾸미는 형용사·소유격은 뒤로 가지만, 동사를 꾸미는 빈도부사(thường 자주, luôn 항상)나 시제·조동사 표지(đã 과거, đang ~하는 중, sẽ '
                 '~할 것, phải ~해야 함, muốn ~하고 싶음)는 한국어처럼 동사 앞에 옵니다. 형용사를 꾸미는 정도부사(rất 매우)도 형용사 앞에 와요.',
           'zh': '修飾名詞的形容詞、所有格放在後面，但修飾動詞的頻度副詞（thường經常、luôn總是）或時態·助動詞標記（đã過去、đang正在、sẽ將要、phải必須、muốn想要）則和韓語一樣放在動詞前面。修飾形容詞的程度副詞（rất非常）也放在形容詞前面。',
           'en': 'Adjectives and possessives that modify nouns come after the noun, but frequency adverbs '
                 'that modify verbs (thường "often", luôn "always") or tense/auxiliary markers (đã "past", '
                 'đang "in the process of", sẽ "will", phải "must", muốn "want to") come before the verb, '
                 'just like in Korean. Degree adverbs that modify adjectives (rất "very") also come before '
                 'the adjective.',
           'ja': '名詞を修飾する形容詞・所有格は後ろに来ますが、動詞を修飾する頻度副詞（thường よく、luôn いつも）や時制・助動詞の標識（đã 過去、đang ～している最中、sẽ '
                 '～するだろう、phải ～しなければならない、muốn ～したい）は韓国語と同じように動詞の前に来ます。形容詞を修飾する程度副詞（rất とても）も形容詞の前に来ます。'},
  'examples': [{'kr': {'ko': '나는 자주 먹는다.', 'zh': '我經常吃。', 'en': 'I eat often.', 'ja': '私はよく食べる。'},
                'vi': 'Tôi thường ăn.',
                'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私'}],
                          ['thường',
                           {'ko': '자주(부사)', 'zh': '經常(副詞)', 'en': 'often (adverb)', 'ja': 'よく(副詞)'}],
                          ['ăn.', {'ko': '먹다(동사)', 'zh': '吃（動詞）', 'en': 'to eat (verb)', 'ja': '食べる（動詞）'}]],
                'note': {'ko': '부사가 동사 앞 — 한국어와 같은 순서',
                         'zh': '副詞在動詞前面 — 與韓語語序相同',
                         'en': 'The adverb comes before the verb — the same order as in Korean',
                         'ja': '副詞は動詞の前 — 韓国語と同じ語順'}},
               {'kr': {'ko': '매우 맛있는', 'zh': '非常好吃的', 'en': 'very delicious', 'ja': 'とてもおいしい'},
                'vi': 'rất ngon',
                'pairs': [['rất',
                           {'ko': '매우(정도부사)',
                            'zh': '非常（程度副詞）',
                            'en': 'very (degree adverb)',
                            'ja': 'とても（程度副詞）'}],
                          ['ngon',
                           {'ko': '맛있는(형용사)',
                            'zh': '好吃的（形容詞）',
                            'en': 'delicious (adjective)',
                            'ja': 'おいしい（形容詞）'}]],
                'note': {'ko': '정도부사가 형용사 앞 — 한국어와 같은 순서',
                         'zh': '程度副詞在形容詞前——與韓語語序相同',
                         'en': 'Degree adverb before adjective — same order as in Korean',
                         'ja': '程度副詞が形容詞の前——韓国語と同じ語順'}}]}]

GRAMMAR_UNITS = [{'title': {'ko': '1. 가장 짧은 문장 — 주어 + 서술어',
            'zh': '1. 最短的句子 — 主語 + 謂語',
            'en': '1. The shortest sentence — Subject + Predicate',
            'ja': '1. 最も短い文 — 主語＋述語'},
  'note': {'ko': "베트남어 문장의 뼈대는 '주어 + 서술어'예요. 이것만으로도 완전한 문장이 됩니다. 서술어 자리에는 동사가 올 수도, 형용사가 그대로 올 수도 있어요(형용사에는 "
                 "'이다'에 해당하는 là가 필요 없어요). 명사가 서술어처럼 쓰이는 경우에만 là를 붙여요(주어 + là + 보어).",
           'zh': '越南語句子的骨架是"主語 + 謂語"。僅憑這個就能構成完整的句子。謂語的位置可以是動詞，也可以直接是形容詞（形容詞不需要相當於"是"的là）。只有當名詞被用作謂語時，才加上là（主語 + là + 補語）。',
           'en': 'The backbone of a Vietnamese sentence is "subject + predicate." This alone makes a '
                 'complete sentence. The predicate slot can be filled by a verb, or an adjective can go '
                 'there as is (adjectives don\'t need là, which corresponds to "to be"). Only when a noun is '
                 'used as the predicate is là attached (subject + là + complement).',
           'ja': 'ベトナム語の文の骨組みは「主語＋述語」です。これだけで完全な文になります。述語の位置には動詞が来ることも、形容詞がそのまま来ることもあります（形容詞には「である」に当たるlàは必要ありません）。名詞が述語のように使われる場合にのみlàを付けます（主語＋là＋補語）。'},
  'steps': [{'vi': 'Tôi', 'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私'}]], 'kr': ''},
            {'vi': 'Tôi ăn.',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私'}],
                       ['ăn.', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる'}]],
             'kr': {'ko': '나는 먹는다.', 'zh': '我吃飯。', 'en': 'I eat.', 'ja': '私は食べる。'}},
            {'vi': 'Trời lạnh.',
             'pairs': [['Trời', {'ko': '날씨', 'zh': '天氣', 'en': 'weather', 'ja': '天気'}],
                       ['lạnh.', {'ko': '춥다', 'zh': '冷', 'en': 'to be cold', 'ja': '寒い'}]],
             'kr': {'ko': '날씨가 춥다.', 'zh': '天氣很冷。', 'en': 'The weather is cold.', 'ja': '天気が寒い。'}},
            {'vi': 'Tôi là học viên.',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私'}],
                       ['là', {'ko': '이다', 'zh': '是', 'en': 'to be', 'ja': 'である/です'}],
                       ['học viên.', {'ko': '학생', 'zh': '學生', 'en': 'student', 'ja': '学生'}]],
             'kr': {'ko': '나는 학생이다.', 'zh': '我是學生。', 'en': 'I am a student.', 'ja': '私は学生だ。'}}]},
 {'title': {'ko': '2. 목적어 추가 — 서술어 바로 뒤에',
            'zh': '2. 添加賓語 — 緊接謂語之後',
            'en': '2. Adding an object — right after the predicate',
            'ja': '2. 目的語の追加 — 述語のすぐ後ろに'},
  'note': {'ko': "한국어는 '밥을 먹는다'(목적어-서술어)지만, 베트남어는 '먹는다-밥'(서술어-목적어) 순서예요.",
           'zh': '韓語是“吃飯”(賓語-謂語),但越南語的語序是“吃-飯”(謂語-賓語)。',
           'en': "Korean is '밥을 먹는다' (object-predicate), but Vietnamese follows the order 'eat-rice' "
                 '(predicate-object).',
           'ja': '韓国語は「ご飯を食べる」(目的語-述語)ですが、ベトナム語は「食べる-ご飯」(述語-目的語)の順序です。'},
  'steps': [{'vi': 'Tôi ăn',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる'}]],
             'kr': ''},
            {'vi': 'Tôi ăn cơm.',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる'}],
                       ['cơm.', {'ko': '밥', 'zh': '飯', 'en': 'rice / meal', 'ja': 'ご飯'}]],
             'kr': {'ko': '나는 밥을 먹는다.', 'zh': '我吃飯。', 'en': 'I eat.', 'ja': '私はご飯を食べる。'}}]},
 {'title': {'ko': '3. 장소 추가 — 문장 뒤쪽에',
            'zh': '3. 添加地點 — 位於句子後部',
            'en': '3. Adding a place — toward the end of the sentence',
            'ja': '3. 場所の追加 — 文の後ろの方に'},
  'note': {'ko': "'~에서'에 해당하는 ở + 장소는 목적어 뒤, 문장 뒤쪽에 붙어요.",
           'zh': "相當於'~에서'的 ở + 地點，接在賓語之後，位於句子靠後的位置。",
           'en': "ở + place, which corresponds to '~에서', comes after the object, toward the end of the "
                 'sentence.',
           'ja': "'~에서'に当たる ở + 場所は、目的語の後ろ、文の後ろの方に付きます。"},
  'steps': [{'vi': 'Tôi ăn cơm',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる'}],
                       ['cơm', {'ko': '밥', 'zh': '飯', 'en': 'rice / meal', 'ja': 'ご飯'}]],
             'kr': ''},
            {'vi': 'Tôi ăn cơm ở nhà.',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる'}],
                       ['cơm', {'ko': '밥', 'zh': '飯', 'en': 'rice / meal', 'ja': 'ご飯'}],
                       ['ở', {'ko': '~에서', 'zh': '在~（從……/在某地）', 'en': 'at/from ~', 'ja': '~で（場所）'}],
                       ['nhà.', {'ko': '집', 'zh': '家', 'en': 'house', 'ja': '家'}]],
             'kr': {'ko': '나는 집에서 밥을 먹는다.', 'zh': '我在家吃飯。', 'en': 'I eat at home.', 'ja': '私は家でご飯を食べる。'}}]},
 {'title': {'ko': '4. 시간 추가 — 문장 맨 뒤에',
            'zh': '4. 添加時間 — 位於句子最後',
            'en': '4. Adding time — at the very end of the sentence',
            'ja': '4. 時間の追加 — 文の一番最後に'},
  'note': {'ko': "'~에'(시각·때)에 해당하는 vào + 시간은 보통 문장의 맨 뒤에 와요.",
           'zh': "相當於'~에'（時刻·時間）的 vào + 時間，通常放在句子的最後。",
           'en': "vào + time, which corresponds to '~에' (time/hour), usually comes at the very end of the "
                 'sentence.',
           'ja': "'~에'（時刻・時）に当たる vào + 時間は、普通文の一番後ろに来ます。"},
  'steps': [{'vi': 'Tôi ăn cơm ở nhà',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる'}],
                       ['cơm', {'ko': '밥', 'zh': '飯', 'en': 'rice / meal', 'ja': 'ご飯'}],
                       ['ở', {'ko': '~에서', 'zh': '在~（從……/在某地）', 'en': 'at/from ~', 'ja': '~で（場所）'}],
                       ['nhà', {'ko': '집', 'zh': '家', 'en': 'house', 'ja': '家'}]],
             'kr': ''},
            {'vi': 'Tôi ăn cơm ở nhà vào buổi sáng.',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる'}],
                       ['cơm', {'ko': '밥', 'zh': '飯', 'en': 'rice / meal', 'ja': 'ご飯'}],
                       ['ở', {'ko': '~에서', 'zh': '在~（從……/在某地）', 'en': 'at/from ~', 'ja': '~で（場所）'}],
                       ['nhà', {'ko': '집', 'zh': '家', 'en': 'house', 'ja': '家'}],
                       ['vào', {'ko': '~에', 'zh': '在~（時間/地點）', 'en': 'at/in/to ~', 'ja': '~に'}],
                       ['buổi sáng.', {'ko': '아침', 'zh': '早上', 'en': 'morning', 'ja': '朝'}]],
             'kr': {'ko': '나는 아침에 집에서 밥을 먹는다.',
                    'zh': '我早上在家吃飯。',
                    'en': 'I eat at home in the morning.',
                    'ja': '私は朝、家でご飯を食べる。'}}]},
 {'title': {'ko': '5. 형용사로 명사 꾸미기 — 명사 뒤에 (핵심 대조)',
            'zh': '5. 用形容詞修飾名詞 — 位於名詞之後（核心對照）',
            'en': '5. Modifying a noun with an adjective — after the noun (key contrast)',
            'ja': '5. 形容詞で名詞を修飾する — 名詞の後ろに（重要な対照）'},
  'note': {'ko': "'맛있는 밥'은 한국어에서 형용사가 먼저지만, 베트남어는 cơm ngon(밥 맛있는)처럼 명사가 먼저예요.",
           'zh': "'好吃的飯'在韓語中形容詞在前，但越南語像 cơm ngon（飯 好吃的）一樣，名詞在前。",
           'en': "For 'delicious rice', the adjective comes first in Korean, but in Vietnamese, as in cơm "
                 'ngon (rice - delicious), the noun comes first.',
           'ja': '「おいしいご飯」は韓国語では形容詞が先ですが、ベトナム語は cơm ngon（ご飯 おいしい）のように名詞が先です。'},
  'steps': [{'vi': 'cơm',
             'pairs': [['cơm', {'ko': '밥', 'zh': '飯', 'en': 'rice / meal', 'ja': 'ご飯'}]],
             'kr': ''},
            {'vi': 'cơm ngon',
             'pairs': [['cơm', {'ko': '밥', 'zh': '飯', 'en': 'rice / meal', 'ja': 'ご飯'}],
                       ['ngon', {'ko': '맛있는', 'zh': '好吃的', 'en': 'delicious', 'ja': 'おいしい'}]],
             'kr': {'ko': '맛있는 밥', 'zh': '好吃的飯', 'en': 'delicious rice/meal', 'ja': 'おいしいご飯'}},
            {'vi': 'Tôi ăn cơm ngon ở nhà vào buổi sáng.',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる'}],
                       ['cơm', {'ko': '밥', 'zh': '飯', 'en': 'rice / meal', 'ja': 'ご飯'}],
                       ['ngon', {'ko': '맛있는', 'zh': '好吃的', 'en': 'delicious', 'ja': 'おいしい'}],
                       ['ở', {'ko': '~에서', 'zh': '在~（從……/在某地）', 'en': 'at/from ~', 'ja': '~で（場所）'}],
                       ['nhà', {'ko': '집', 'zh': '家', 'en': 'house', 'ja': '家'}],
                       ['vào', {'ko': '~에', 'zh': '在~（時間/地點）', 'en': 'at/in/to ~', 'ja': '~に'}],
                       ['buổi sáng.', {'ko': '아침', 'zh': '早上', 'en': 'morning', 'ja': '朝'}]],
             'kr': {'ko': '나는 아침에 집에서 맛있는 밥을 먹는다.',
                    'zh': '我早上在家吃好吃的飯。',
                    'en': 'I eat delicious food at home in the morning.',
                    'ja': '私は朝、家でおいしいご飯を食べる。'}}]},
 {'title': {'ko': '6. 소유격으로 명사 꾸미기 — 명사 뒤에',
            'zh': '6. 用所有格修飾名詞 — 位於名詞之後',
            'en': '6. Modifying a noun with a possessive — after the noun',
            'ja': '6. 所有格で名詞を修飾する — 名詞の後ろに'},
  'note': {'ko': "'내 집'도 마찬가지로 nhà của tôi(집 의 나)처럼 명사가 먼저, 소유격이 나중이에요.",
           'zh': "'我的家'也一樣，像 nhà của tôi（家 的 我）一樣，名詞在前，所有格在後。",
           'en': "Likewise for 'my house': as in nhà của tôi (house - of - I), the noun comes first and the "
                 'possessive comes after.',
           'ja': '「私の家」も同様に、nhà của tôi（家 の 私）のように名詞が先、所有格が後になります。'},
  'steps': [{'vi': 'nhà', 'pairs': [['nhà', {'ko': '집', 'zh': '家', 'en': 'house', 'ja': '家'}]], 'kr': ''},
            {'vi': 'nhà của tôi',
             'pairs': [['nhà', {'ko': '집', 'zh': '家', 'en': 'house', 'ja': '家'}],
                       ['của', {'ko': '의', 'zh': '的', 'en': "'s (possessive particle)", 'ja': 'の'}],
                       ['tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私'}]],
             'kr': {'ko': '내 집 / 나의 집', 'zh': '我家 / 我的家', 'en': 'my house / my house', 'ja': '私の家 / 私の家'}},
            {'vi': 'Đây là nhà của tôi.',
             'pairs': [['Đây', {'ko': '여기', 'zh': '這裡', 'en': 'here', 'ja': 'ここ'}],
                       ['là', {'ko': '이다', 'zh': '是', 'en': 'to be', 'ja': 'である/です'}],
                       ['nhà', {'ko': '집', 'zh': '家', 'en': 'house', 'ja': '家'}],
                       ['của', {'ko': '의', 'zh': '的', 'en': "'s (possessive particle)", 'ja': 'の'}],
                       ['tôi.', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私'}]],
             'kr': {'ko': '여기는 내 집이다.', 'zh': '這裡是我的家。', 'en': 'This is my house.', 'ja': 'ここは私の家です。'}}]},
 {'title': {'ko': '7. 빈도부사 추가 — 동사 앞에 (한국어와 같은 순서)',
            'zh': '7. 添加頻率副詞 — 位於動詞之前（與韓語語序相同）',
            'en': '7. Adding adverbs of frequency — before the verb (same order as Korean)',
            'ja': '7. 頻度副詞の追加 — 動詞の前に（韓国語と同じ語順）'},
  'note': {'ko': 'thường(보통·자주), luôn luôn(항상), cũng(또한) 같은 빈도부사는 한국어처럼 동사 앞에 와요.',
           'zh': '像 thường（通常·經常）、luôn luôn（總是）、cũng（也）這樣的頻率副詞，和韓語一樣放在動詞前面。',
           'en': 'Frequency adverbs like thường (usually, often), luôn luôn (always), and cũng (also) come '
                 'before the verb, just like in Korean.',
           'ja': 'thường（普通・よく）、luôn luôn（いつも）、cũng（また）のような頻度副詞は、韓国語と同じように動詞の前に来ます。'},
  'steps': [{'vi': 'Tôi ăn cơm ở nhà.',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる'}],
                       ['cơm', {'ko': '밥', 'zh': '飯', 'en': 'rice / meal', 'ja': 'ご飯'}],
                       ['ở', {'ko': '~에서', 'zh': '在~（從……/在某地）', 'en': 'at/from ~', 'ja': '~で（場所）'}],
                       ['nhà.', {'ko': '집', 'zh': '家', 'en': 'house', 'ja': '家'}]],
             'kr': ''},
            {'vi': 'Tôi thường ăn cơm ở nhà.',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私'}],
                       ['thường', {'ko': '보통', 'zh': '通常', 'en': 'usually / normal', 'ja': '普通'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる'}],
                       ['cơm', {'ko': '밥', 'zh': '飯', 'en': 'rice / meal', 'ja': 'ご飯'}],
                       ['ở', {'ko': '~에서', 'zh': '在~（從……/在某地）', 'en': 'at/from ~', 'ja': '~で（場所）'}],
                       ['nhà.', {'ko': '집', 'zh': '家', 'en': 'house', 'ja': '家'}]],
             'kr': {'ko': '나는 보통 집에서 밥을 먹는다.',
                    'zh': '我通常在家吃飯。',
                    'en': 'I usually eat at home.',
                    'ja': '私はふだん家でご飯を食べる。'}}]},
 {'title': {'ko': '8. 조동사 추가 — 동사 앞에',
            'zh': '8. 添加助動詞 — 位於動詞之前',
            'en': '8. Adding an auxiliary verb — before the verb',
            'ja': '8. 助動詞の追加 — 動詞の前に'},
  'note': {'ko': 'muốn(~하고 싶다), phải(~해야 한다), có thể(~할 수 있다)·không thể(~할 수 없다), nên(~하는 게 좋다), đang(~하는 '
                 '중), sẽ(~할 것이다), đã(~했다) 모두 동사 바로 앞에 옵니다.',
           'zh': 'muốn（想要~）、phải（必須~）、có thể（能~）·không thể（不能~）、nên（最好~）、đang（正在~）、sẽ（將要~）、đã（已經~）都放在動詞的正前方。',
           'en': 'muốn (want to ~), phải (must ~), có thể (can ~) · không thể (cannot ~), nên (should ~), '
                 'đang (~ing), sẽ (will ~), and đã (~ed) all come right before the verb.',
           'ja': 'muốn（~したい）、phải（~しなければならない）、có thể（~できる）・không '
                 'thể（~できない）、nên（~する方がよい）、đang（~している最中）、sẽ（~するだろう）、đã（~した）はすべて動詞のすぐ前に来ます。'},
  'steps': [{'vi': 'Tôi ăn cơm',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる'}],
                       ['cơm', {'ko': '밥', 'zh': '飯', 'en': 'rice / meal', 'ja': 'ご飯'}]],
             'kr': ''},
            {'vi': 'Tôi muốn ăn cơm.',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私'}],
                       ['muốn', {'ko': '~하고 싶다', 'zh': '想要~', 'en': 'want to ~', 'ja': '~したい'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる'}],
                       ['cơm.', {'ko': '밥', 'zh': '飯', 'en': 'rice / meal', 'ja': 'ご飯'}]],
             'kr': {'ko': '나는 밥을 먹고 싶다.', 'zh': '我想吃飯。', 'en': 'I want to eat.', 'ja': '私はご飯を食べたい。'}},
            {'vi': 'Tôi phải đi học.',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私'}],
                       ['phải', {'ko': '~해야 한다', 'zh': '必須~', 'en': 'must ~', 'ja': '~しなければならない'}],
                       ['đi', {'ko': '가다', 'zh': '去', 'en': 'to go', 'ja': '行く'}],
                       ['học.', {'ko': '공부(하러)', 'zh': '（去）學習', 'en': '(to go) study', 'ja': '勉強（しに）'}]],
             'kr': {'ko': '나는 학교에 가야 한다.',
                    'zh': '我得去學校。',
                    'en': 'I have to go to school.',
                    'ja': '私は学校に行かなければならない。'}},
            {'vi': 'Tôi có thể ăn cơm.',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私'}],
                       ['có thể', {'ko': '~할 수 있다', 'zh': '能~', 'en': 'can ~', 'ja': '~できる'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる'}],
                       ['cơm.', {'ko': '밥', 'zh': '飯', 'en': 'rice / meal', 'ja': 'ご飯'}]],
             'kr': {'ko': '나는 밥을 먹을 수 있다.', 'zh': '我能吃飯。', 'en': 'I can eat.', 'ja': '私はご飯を食べられる。'}},
            {'vi': 'Tôi không thể ăn cơm.',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私'}],
                       ['không thể', {'ko': '~할 수 없다', 'zh': '不能~', 'en': 'cannot ~', 'ja': '~できない'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる'}],
                       ['cơm.', {'ko': '밥', 'zh': '飯', 'en': 'rice / meal', 'ja': 'ご飯'}]],
             'kr': {'ko': '나는 밥을 먹을 수 없다.', 'zh': '我不能吃飯。', 'en': 'I cannot eat.', 'ja': '私はご飯を食べられない。'}},
            {'vi': 'Bạn nên ăn cơm.',
             'pairs': [['Bạn', {'ko': '너', 'zh': '你', 'en': 'you', 'ja': 'お前、君'}],
                       ['nên',
                        {'ko': '~하는 게 좋다',
                         'zh': '最好~',
                         'en': "should ~ / it's better to ~",
                         'ja': '~する方がよい'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる'}],
                       ['cơm.', {'ko': '밥', 'zh': '飯', 'en': 'rice / meal', 'ja': 'ご飯'}]],
             'kr': {'ko': '너는 밥을 먹는 게 좋겠다.',
                    'zh': '你最好吃飯。',
                    'en': 'You should eat.',
                    'ja': 'あなたはご飯を食べたほうがいい。'}},
            {'vi': 'Tôi đang ăn cơm.',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私'}],
                       ['đang', {'ko': '~하는 중', 'zh': '正在~', 'en': 'in the middle of ~ing', 'ja': '~している最中'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる'}],
                       ['cơm.', {'ko': '밥', 'zh': '飯', 'en': 'rice / meal', 'ja': 'ご飯'}]],
             'kr': {'ko': '나는 밥을 먹고 있다.', 'zh': '我正在吃飯。', 'en': 'I am eating.', 'ja': '私はご飯を食べている。'}},
            {'vi': 'Tôi sẽ ăn cơm.',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私'}],
                       ['sẽ', {'ko': '~할 것이다', 'zh': '將要~', 'en': 'will ~', 'ja': '~するつもりだ'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる'}],
                       ['cơm.', {'ko': '밥', 'zh': '飯', 'en': 'rice / meal', 'ja': 'ご飯'}]],
             'kr': {'ko': '나는 밥을 먹을 것이다.', 'zh': '我將要吃飯。', 'en': 'I will eat.', 'ja': '私はご飯を食べるつもりだ。'}},
            {'vi': 'Tôi đã ăn cơm.',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私'}],
                       ['đã', {'ko': '~했다', 'zh': '~了', 'en': '~ed', 'ja': '~した'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる'}],
                       ['cơm.', {'ko': '밥', 'zh': '飯', 'en': 'rice / meal', 'ja': 'ご飯'}]],
             'kr': {'ko': '나는 밥을 먹었다.', 'zh': '我吃了飯。', 'en': 'I ate.', 'ja': '私はご飯を食べた。'}}]},
 {'title': {'ko': '9. 정도부사 + 형용사 — 형용사 앞에',
            'zh': '9. 程度副詞＋形容詞 — 位於形容詞之前',
            'en': '9. Degree adverb + adjective — before the adjective',
            'ja': '9. 程度副詞＋形容詞 — 形容詞の前に'},
  'note': {'ko': 'rất(매우) 같은 정도부사는 형용사를 꾸미는 말이라, 형용사 앞에 와요. (형용사 자체는 명사 뒤인데, 정도부사는 그 형용사 앞!)',
           'zh': '像 rất（非常）這樣的程度副詞是用來修飾形容詞的，所以放在形容詞前面。（形容詞本身在名詞後面，但程度副詞在那個形容詞前面！）',
           'en': 'Degree adverbs like rất (very) modify adjectives, so they come before the adjective. (The '
                 'adjective itself comes after the noun, but the degree adverb comes before that adjective!)',
           'ja': 'rất（とても）のような程度副詞は形容詞を修飾する言葉なので、形容詞の前に来ます。（形容詞自体は名詞の後ろですが、程度副詞はその形容詞の前です！）'},
  'steps': [{'vi': 'cơm ngon',
             'pairs': [['cơm', {'ko': '밥', 'zh': '飯', 'en': 'rice / meal', 'ja': 'ご飯'}],
                       ['ngon', {'ko': '맛있는', 'zh': '好吃的', 'en': 'delicious', 'ja': 'おいしい'}]],
             'kr': ''},
            {'vi': 'cơm rất ngon',
             'pairs': [['cơm', {'ko': '밥', 'zh': '飯', 'en': 'rice / meal', 'ja': 'ご飯'}],
                       ['rất', {'ko': '매우', 'zh': '非常', 'en': 'very', 'ja': 'とても'}],
                       ['ngon', {'ko': '맛있는', 'zh': '好吃的', 'en': 'delicious', 'ja': 'おいしい'}]],
             'kr': {'ko': '매우 맛있는 밥', 'zh': '非常好吃的飯', 'en': 'very delicious rice/meal', 'ja': 'とてもおいしいご飯'}},
            {'vi': 'Tôi ăn cơm rất ngon.',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる'}],
                       ['cơm', {'ko': '밥', 'zh': '飯', 'en': 'rice / meal', 'ja': 'ご飯'}],
                       ['rất', {'ko': '매우', 'zh': '非常', 'en': 'very', 'ja': 'とても'}],
                       ['ngon.', {'ko': '맛있는', 'zh': '好吃的', 'en': 'delicious', 'ja': 'おいしい'}]],
             'kr': {'ko': '나는 매우 맛있는 밥을 먹는다.',
                    'zh': '我吃非常好吃的飯。',
                    'en': 'I eat very delicious food.',
                    'ja': '私はとてもおいしいご飯を食べる。'}}]},
 {'title': {'ko': '10. 부정문 — không을 동사(또는 형용사) 앞에',
            'zh': '10. 否定句 — 在動詞（或形容詞）前加 không',
            'en': '10. Negative sentences — put không before the verb (or adjective)',
            'ja': '10. 否定文 — không を動詞（または形容詞）の前に'},
  'note': {'ko': '부정은 không을 서술어 바로 앞에 넣으면 돼요.',
           'zh': '否定只要把 không 放在謂語前面即可。',
           'en': 'To make it negative, just put "không" right before the predicate.',
           'ja': '否定は「không」を述語の直前に入れればいいです。'},
  'steps': [{'vi': 'Tôi ăn cơm',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる'}],
                       ['cơm', {'ko': '밥', 'zh': '飯', 'en': 'rice / meal', 'ja': 'ご飯'}]],
             'kr': ''},
            {'vi': 'Tôi không ăn cơm.',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私'}],
                       ['không', {'ko': '안', 'zh': '裡面', 'en': 'inside', 'ja': '中'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる'}],
                       ['cơm.', {'ko': '밥', 'zh': '飯', 'en': 'rice / meal', 'ja': 'ご飯'}]],
             'kr': {'ko': '나는 밥을 안 먹는다.', 'zh': '我不吃飯。', 'en': "I don't eat.", 'ja': '私はご飯を食べない。'}},
            {'vi': 'Cơm không ngon.',
             'pairs': [['Cơm', {'ko': '밥', 'zh': '飯', 'en': 'rice / meal', 'ja': 'ご飯'}],
                       ['không', {'ko': '안', 'zh': '裡面', 'en': 'inside', 'ja': '中'}],
                       ['ngon.', {'ko': '맛있다', 'zh': '好吃', 'en': 'to be delicious', 'ja': 'おいしい'}]],
             'kr': {'ko': '밥이 맛없다.', 'zh': '飯不好吃。', 'en': "The rice isn't tasty.", 'ja': 'ご飯がおいしくない。'}}]},
 {'title': {'ko': '11. 의문문 — 예/아니오 (có ... không으로 감싸기)',
            'zh': '11. 疑問句 — 是/否（用 có ... không 包裹）',
            'en': '11. Yes/No questions (wrapping the sentence with có ... không)',
            'ja': '11. 疑問文 — はい／いいえ（có ... không で挟む）'},
  'note': {'ko': "'~합니까?'라고 물을 땐 서술어 앞에 có, 문장 끝에 không을 붙여요. 직역하면 '~있다 ... ~없다?' 구조예요.",
           'zh': "問'~합니까？（做~嗎？）'時，在謂語前加 có，在句末加 không。直譯的話是'~有…~沒有？'的結構。",
           'en': "When asking '~합니까?' (Do you ~?), put có before the predicate and không at the end of the "
                 "sentence. Literally, it's structured like '~ have ... ~ not have?'",
           'ja': '「~합니까？」と尋ねるときは、述語の前に có、文末に không を付けます。直訳すると「~ある…~ない？」という構造です。'},
  'steps': [{'vi': 'Bạn ăn cơm.',
             'pairs': [['Bạn', {'ko': '너', 'zh': '你', 'en': 'you', 'ja': 'お前、君'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる'}],
                       ['cơm.', {'ko': '밥', 'zh': '飯', 'en': 'rice / meal', 'ja': 'ご飯'}]],
             'kr': ''},
            {'vi': 'Bạn có ăn cơm không?',
             'pairs': [['Bạn', {'ko': '너', 'zh': '你', 'en': 'you', 'ja': 'お前、君'}],
                       ['có',
                        {'ko': '(의문)있다', 'zh': '（疑問）有', 'en': '(question) have / there is', 'ja': '（疑問）ある'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる'}],
                       ['cơm', {'ko': '밥', 'zh': '飯', 'en': 'rice / meal', 'ja': 'ご飯'}],
                       ['không?',
                        {'ko': '(의문)없다',
                         'zh': '（疑問）沒有',
                         'en': "(question) not have / there isn't",
                         'ja': '（疑問）ない'}]],
             'kr': {'ko': '너 밥 먹어?', 'zh': '你吃飯嗎?', 'en': 'Are you eating?', 'ja': 'ご飯食べる?'}}]},
 {'title': {'ko': '12. 의문문 — 완료 여부 (~ chưa?)',
            'zh': '12. 疑問句 — 是否完成（~ chưa？）',
            'en': '12. Questions about completion (~ chưa?)',
            'ja': '12. 疑問文 — 完了かどうか（~ chưa？）'},
  'note': {'ko': "'아직 ~했어요?'처럼 이미 했는지를 물을 땐 문장 끝에 chưa?를 붙여요. 대답은 '이미 했다' rồi, '아직 안 했다' chưa. 단, 대답에서 chưa는 "
                 '동사 앞으로 자리를 옮겨요.',
           'zh': "像'還~了嗎？'一樣，問是否已經做了某事時，在句末加 chưa？回答是'已經做了'用 rồi，'還沒做'用 chưa。不過，回答中的 chưa 要移到動詞前面。",
           'en': "When asking whether something has already been done, like 'Have you ~ yet?', add chưa? at "
                 "the end of the sentence. The answer is rồi for 'already done' and chưa for 'not yet'. "
                 'However, in the answer, chưa moves to before the verb.',
           'ja': '「まだ~しましたか？」のように、すでにしたかどうかを尋ねるときは、文末に chưa？を付けます。答えは「すでにした」rồi、「まだしていない」chưa です。ただし、答えの中では '
                 'chưa は動詞の前に位置が移ります。'},
  'steps': [{'vi': 'Bạn ăn cơm chưa?',
             'pairs': [['Bạn', {'ko': '너', 'zh': '你', 'en': 'you', 'ja': 'お前、君'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる'}],
                       ['cơm', {'ko': '밥', 'zh': '飯', 'en': 'rice / meal', 'ja': 'ご飯'}],
                       ['chưa?',
                        {'ko': '(완료?)아직', 'zh': '（完成？）還沒', 'en': '(Completed?) Not yet', 'ja': '（完了？）まだ'}]],
             'kr': {'ko': '너 밥 먹었어?', 'zh': '你吃飯了嗎?', 'en': 'Did you eat?', 'ja': 'ご飯食べた?'}},
            {'vi': 'Tôi ăn cơm rồi.',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる'}],
                       ['cơm', {'ko': '밥', 'zh': '飯', 'en': 'rice / meal', 'ja': 'ご飯'}],
                       ['rồi.',
                        {'ko': '이미(완료)', 'zh': '已經(完成)', 'en': 'already (completed)', 'ja': 'すでに(完了)'}]],
             'kr': {'ko': '나는 밥을 (이미) 먹었어.',
                    'zh': '我(已經)吃過飯了。',
                    'en': 'I already ate.',
                    'ja': '私はご飯を(すでに)食べた。'}},
            {'vi': 'Tôi chưa ăn cơm.',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私'}],
                       ['chưa', {'ko': '아직 (안)', 'zh': '還（沒）', 'en': 'not yet', 'ja': 'まだ（〜ない）'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる'}],
                       ['cơm.', {'ko': '밥', 'zh': '飯', 'en': 'rice / meal', 'ja': 'ご飯'}]],
             'kr': {'ko': '나는 아직 밥을 안 먹었어.',
                    'zh': '我還沒吃飯。',
                    'en': "I haven't eaten yet.",
                    'ja': '私はまだご飯を食べていない。'}}]},
 {'title': {'ko': '13. 의문문 — 의문사 (누가·무엇·어디·언제·왜·어떻게)',
            'zh': '13. 疑問句 — 疑問詞（誰·什麼·哪裡·何時·為什麼·怎麼）',
            'en': '13. Question words (who, what, where, when, why, how)',
            'ja': '13. 疑問文 — 疑問詞（誰・何・どこ・いつ・なぜ・どのように）'},
  'note': {'ko': '의문사는 대개 원래 그 말이 있던 자리에 그대로 들어가요 — ai(누가)는 주어 자리, gì(무엇)는 목적어 자리, ở đâu(어디서)는 장소 자리, khi '
                 'nào(언제)는 시간 자리, thế nào(어떻게)는 서술어 뒤. 다만 tại sao(왜)는 예외로 문장 맨 앞에 옵니다.',
           'zh': '疑問詞通常放在原本那個詞所在的位置 — ai（誰）放在主語位置，gì（什麼）放在賓語位置，ở đâu（哪裡）放在地點位置，khi nào（何時）放在時間位置，thế '
                 'nào（怎麼樣）放在謂語後面。不過 tại sao（為什麼）是例外，放在句子最前面。',
           'en': 'Interrogative words usually go in the same position the corresponding word would normally '
                 'occupy — ai (who) goes in the subject position, gì (what) in the object position, ở đâu '
                 '(where) in the place position, khi nào (when) in the time position, and thế nào (how) '
                 'after the predicate. However, tại sao (why) is an exception and comes at the very '
                 'beginning of the sentence.',
           'ja': '疑問詞は通常、元々その言葉があった位置にそのまま入ります — ai（誰が）は主語の位置、gì（何を）は目的語の位置、ở đâu（どこで）は場所の位置、khi '
                 'nào（いつ）は時間の位置、thế nào（どのように）は述語の後ろ。ただし tại sao（なぜ）は例外で、文の一番前に来ます。'},
  'steps': [{'vi': 'Ai ăn cơm?',
             'pairs': [['Ai', {'ko': '누가', 'zh': '誰', 'en': 'who', 'ja': '誰が'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる'}],
                       ['cơm?', {'ko': '밥', 'zh': '飯', 'en': 'rice / meal', 'ja': 'ご飯'}]],
             'kr': {'ko': '누가 밥을 먹어요?', 'zh': '誰吃飯？', 'en': 'Who eats rice?', 'ja': '誰がご飯を食べますか？'}},
            {'vi': 'Bạn ăn gì?',
             'pairs': [['Bạn', {'ko': '너', 'zh': '你', 'en': 'you', 'ja': 'お前、君'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる'}],
                       ['gì?', {'ko': '무엇', 'zh': '什麼', 'en': 'what', 'ja': '何'}]],
             'kr': {'ko': '너 뭐 먹어?', 'zh': '你吃什麼?', 'en': 'What are you eating?', 'ja': '何食べる?'}},
            {'vi': 'Bạn ăn cơm ở đâu?',
             'pairs': [['Bạn', {'ko': '너', 'zh': '你', 'en': 'you', 'ja': 'お前、君'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる'}],
                       ['cơm', {'ko': '밥', 'zh': '飯', 'en': 'rice / meal', 'ja': 'ご飯'}],
                       ['ở đâu?', {'ko': '어디에서', 'zh': '在哪裡', 'en': 'where', 'ja': 'どこで'}]],
             'kr': {'ko': '너 어디서 밥 먹어?', 'zh': '你在哪裡吃飯？', 'en': 'Where do you eat?', 'ja': 'あなたはどこでご飯を食べる？'}},
            {'vi': 'Bạn ăn cơm khi nào?',
             'pairs': [['Bạn', {'ko': '너', 'zh': '你', 'en': 'you', 'ja': 'お前、君'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる'}],
                       ['cơm', {'ko': '밥', 'zh': '飯', 'en': 'rice / meal', 'ja': 'ご飯'}],
                       ['khi nào?', {'ko': '언제', 'zh': '什麼時候', 'en': 'when', 'ja': 'いつ'}]],
             'kr': {'ko': '너 언제 밥 먹어?', 'zh': '你什麼時候吃飯？', 'en': 'When do you eat?', 'ja': 'あなたはいつご飯を食べる？'}},
            {'vi': 'Tại sao bạn ăn cơm?',
             'pairs': [['Tại sao', {'ko': '왜', 'zh': '為什麼', 'en': 'why', 'ja': 'なぜ'}],
                       ['bạn', {'ko': '너', 'zh': '你', 'en': 'you', 'ja': 'お前、君'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる'}],
                       ['cơm?', {'ko': '밥', 'zh': '飯', 'en': 'rice / meal', 'ja': 'ご飯'}]],
             'kr': {'ko': '너 왜 밥 먹어?', 'zh': '你為什麼吃飯？', 'en': 'Why do you eat?', 'ja': 'あなたはなぜご飯を食べる？'}},
            {'vi': 'Cơm thế nào?',
             'pairs': [['Cơm', {'ko': '밥', 'zh': '飯', 'en': 'rice / meal', 'ja': 'ご飯'}],
                       ['thế nào?', {'ko': '어때', 'zh': '怎麼樣', 'en': 'How about (it)?', 'ja': 'どう？'}]],
             'kr': {'ko': '밥 어때?', 'zh': '吃飯怎麼樣？', 'en': 'How about rice?', 'ja': 'ご飯はどう？'}}]},
 {'title': {'ko': '14. 의문문 — 선택 의문문 (A hay B?)',
            'zh': '14. 疑問句 — 選擇疑問句（A hay B？）',
            'en': '14. Alternative questions (A hay B?)',
            'ja': '14. 疑問文 — 選択疑問文（A hay B？）'},
  'note': {'ko': "hay(아니면·또는)로 두 선택지를 이으면 'A할래 B할래?' 같은 선택 의문문이 돼요.",
           'zh': "用 hay（或者·或是）連接兩個選項，就變成'要A還是要B？'這樣的選擇疑問句。",
           'en': "Connecting two options with hay (or) forms an alternative question like 'Do you want A or "
                 "B?'",
           'ja': 'hay（あるいは・または）で2つの選択肢をつなぐと、「Aする？Bする？」のような選択疑問文になります。'},
  'steps': [{'vi': 'Bạn ăn cơm.',
             'pairs': [['Bạn', {'ko': '너', 'zh': '你', 'en': 'you', 'ja': 'お前、君'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる'}],
                       ['cơm.', {'ko': '밥', 'zh': '飯', 'en': 'rice / meal', 'ja': 'ご飯'}]],
             'kr': ''},
            {'vi': 'Bạn ăn cơm hay ăn phở?',
             'pairs': [['Bạn', {'ko': '너', 'zh': '你', 'en': 'you', 'ja': 'お前、君'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる'}],
                       ['cơm', {'ko': '밥', 'zh': '飯', 'en': 'rice / meal', 'ja': 'ご飯'}],
                       ['hay', {'ko': '아니면', 'zh': '或者', 'en': 'or', 'ja': 'それとも'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる'}],
                       ['phở?', {'ko': '쌀국수', 'zh': '河粉', 'en': 'rice noodles (phở)', 'ja': 'フォー（米粉麺）'}]],
             'kr': {'ko': '밥 먹을래 아니면 쌀국수 먹을래?',
                    'zh': '你要吃飯還是吃米粉？',
                    'en': 'Do you want to eat rice or pho (rice noodles)?',
                    'ja': 'ご飯を食べる？それとも米粉（フォー）を食べる？'}}]},
 {'title': {'ko': '15. 접속어로 문장 잇기',
            'zh': '15. 用連接詞連接句子',
            'en': '15. Connecting sentences with conjunctions',
            'ja': '15. 接続語で文をつなぐ'},
  'note': {'ko': 'và(그리고), nhưng(그러나), vì...nên(~때문에 ~하다)로 짧은 문장 두 개를 이어 더 긴 문장을 만들 수 있어요.',
           'zh': '用 và（而且）、nhưng（但是）、vì...nên（因為~所以~）可以把兩個短句連接成更長的句子。',
           'en': 'You can connect two short sentences into a longer one using và (and), nhưng (but), and '
                 'vì...nên (because ~, so ~).',
           'ja': 'và（そして）、nhưng（しかし）、vì...nên（~なので~する）を使って、2つの短い文をつないでより長い文を作ることができます。'},
  'steps': [{'vi': 'Tôi ăn cơm và tôi uống nước.',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる'}],
                       ['cơm', {'ko': '밥', 'zh': '飯', 'en': 'rice / meal', 'ja': 'ご飯'}],
                       ['và', {'ko': '그리고', 'zh': '而且,和', 'en': 'and', 'ja': 'そして'}],
                       ['tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私'}],
                       ['uống', {'ko': '마시다', 'zh': '喝', 'en': 'to drink', 'ja': '飲む'}],
                       ['nước.', {'ko': '물', 'zh': '水', 'en': 'water', 'ja': '水'}]],
             'kr': {'ko': '나는 밥을 먹고 물을 마신다.',
                    'zh': '我吃飯然後喝水。',
                    'en': 'I eat and drink water.',
                    'ja': '私はご飯を食べて水を飲む。'}},
            {'vi': 'Tôi thích cơm nhưng tôi không thích nước.',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私'}],
                       ['thích', {'ko': '좋아하다', 'zh': '喜歡', 'en': 'to like', 'ja': '好きだ'}],
                       ['cơm', {'ko': '밥', 'zh': '飯', 'en': 'rice / meal', 'ja': 'ご飯'}],
                       ['nhưng', {'ko': '그러나', 'zh': '但是', 'en': 'but, however', 'ja': 'しかし'}],
                       ['tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私'}],
                       ['không', {'ko': '안', 'zh': '裡面', 'en': 'inside', 'ja': '中'}],
                       ['thích', {'ko': '좋아하다', 'zh': '喜歡', 'en': 'to like', 'ja': '好きだ'}],
                       ['nước.', {'ko': '물', 'zh': '水', 'en': 'water', 'ja': '水'}]],
             'kr': {'ko': '나는 밥은 좋아하지만 물은 안 좋아한다.',
                    'zh': '我喜歡飯,但不喜歡水。',
                    'en': "I like rice but I don't like water.",
                    'ja': '私はご飯は好きだが、水は好きではない。'}},
            {'vi': 'Vì tôi đói nên tôi ăn cơm.',
             'pairs': [['Vì', {'ko': '~때문에', 'zh': '因為~', 'en': 'because of ~', 'ja': '~のために'}],
                       ['tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私'}],
                       ['đói', {'ko': '배고프다', 'zh': '餓', 'en': 'to be hungry', 'ja': 'お腹がすく'}],
                       ['nên', {'ko': '그래서', 'zh': '所以', 'en': 'so, therefore', 'ja': 'それで'}],
                       ['tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私'}],
                       ['ăn', {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる'}],
                       ['cơm.', {'ko': '밥', 'zh': '飯', 'en': 'rice / meal', 'ja': 'ご飯'}]],
             'kr': {'ko': '나는 배가 고파서 밥을 먹는다.',
                    'zh': '我因為肚子餓所以吃飯。',
                    'en': "I eat because I'm hungry.",
                    'ja': '私はお腹が空いたのでご飯を食べる。'}}]},
 {'title': {'ko': '16. 다양한 동사로 연습 — đọc sách (책 읽기)',
            'zh': '16. 用各種動詞練習 — đọc sách（讀書）',
            'en': '16. Practice with various verbs — đọc sách (reading a book)',
            'ja': '16. さまざまな動詞で練習 — đọc sách（本を読む）'},
  'note': {'ko': '지금까지 배운 문형을 다른 동사·목적어로 연습해요. đọc(읽다) + sách(책).',
           'zh': '用不同的動詞·賓語練習到目前為止學過的句型。đọc(讀)+ sách(書)。',
           'en': 'Practice the sentence pattern learned so far with different verbs and objects. đọc (to '
                 'read) + sách (book).',
           'ja': 'これまで学んだ文型を別の動詞·目的語で練習しましょう。đọc(読む)+ sách(本)。'},
  'steps': [{'vi': 'Tôi đọc.',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私'}],
                       ['đọc.', {'ko': '읽다', 'zh': '讀', 'en': 'to read', 'ja': '読む'}]],
             'kr': {'ko': '나는 읽는다.', 'zh': '我讀。', 'en': 'I read.', 'ja': '私は読む。'}},
            {'vi': 'Tôi đọc sách.',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私'}],
                       ['đọc', {'ko': '읽다', 'zh': '讀', 'en': 'to read', 'ja': '読む'}],
                       ['sách.', {'ko': '책', 'zh': '書', 'en': 'book', 'ja': '本'}]],
             'kr': {'ko': '나는 책을 읽는다.', 'zh': '我讀書。', 'en': 'I read a book.', 'ja': '私は本を読む。'}},
            {'vi': 'Tôi thường đọc sách ở nhà vào buổi tối.',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私'}],
                       ['thường', {'ko': '보통', 'zh': '通常', 'en': 'usually / normal', 'ja': '普通'}],
                       ['đọc', {'ko': '읽다', 'zh': '讀', 'en': 'to read', 'ja': '読む'}],
                       ['sách', {'ko': '책', 'zh': '書', 'en': 'book', 'ja': '本'}],
                       ['ở', {'ko': '~에서', 'zh': '在~（從……/在某地）', 'en': 'at/from ~', 'ja': '~で（場所）'}],
                       ['nhà', {'ko': '집', 'zh': '家', 'en': 'house', 'ja': '家'}],
                       ['vào', {'ko': '~에', 'zh': '在~（時間/地點）', 'en': 'at/in/to ~', 'ja': '~に'}],
                       ['buổi tối.', {'ko': '저녁', 'zh': '晚上', 'en': 'evening', 'ja': '夕方'}]],
             'kr': {'ko': '나는 보통 저녁에 집에서 책을 읽는다.',
                    'zh': '我通常晚上在家看書。',
                    'en': 'I usually read books at home in the evening.',
                    'ja': '私はふだん夕方に家で本を読む。'}}]},
 {'title': {'ko': '17. 다양한 동사로 연습 — đi nhóm họp (집회 가기)',
            'zh': '17. 用各種動詞練習 — đi nhóm họp（去聚會）',
            'en': '17. Practice with various verbs — đi nhóm họp (going to the meeting)',
            'ja': '17. さまざまな動詞で練習 — đi nhóm họp（集会に行く）'},
  'note': {'ko': 'đi(가다) + nhóm họp(집회).',
           'zh': 'đi（去）+ nhóm họp（聚會）。',
           'en': 'đi (to go) + nhóm họp (meeting).',
           'ja': 'đi（行く）+ nhóm họp（集会）。'},
  'steps': [{'vi': 'Tôi đi.',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私'}],
                       ['đi.', {'ko': '가다', 'zh': '去', 'en': 'to go', 'ja': '行く'}]],
             'kr': {'ko': '나는 간다.', 'zh': '我去。', 'en': 'I go.', 'ja': '私は行く。'}},
            {'vi': 'Tôi đi nhóm họp.',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私'}],
                       ['đi', {'ko': '가다', 'zh': '去', 'en': 'to go', 'ja': '行く'}],
                       ['nhóm họp.', {'ko': '집회', 'zh': '聚會', 'en': 'meeting', 'ja': '集会'}]],
             'kr': {'ko': '나는 집회에 간다.', 'zh': '我去聚會。', 'en': 'I go to the meeting.', 'ja': '私は集会に行く。'}},
            {'vi': 'Tôi muốn đi nhóm họp vào buổi tối.',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私'}],
                       ['muốn', {'ko': '~하고 싶다', 'zh': '想要~', 'en': 'want to ~', 'ja': '~したい'}],
                       ['đi', {'ko': '가다', 'zh': '去', 'en': 'to go', 'ja': '行く'}],
                       ['nhóm họp', {'ko': '집회', 'zh': '聚會', 'en': 'meeting', 'ja': '集会'}],
                       ['vào', {'ko': '~에', 'zh': '在~（時間/地點）', 'en': 'at/in/to ~', 'ja': '~に'}],
                       ['buổi tối.', {'ko': '저녁', 'zh': '晚上', 'en': 'evening', 'ja': '夕方'}]],
             'kr': {'ko': '나는 저녁에 집회에 가고 싶다.',
                    'zh': '我晚上想去聚會。',
                    'en': 'I want to go to the meeting in the evening.',
                    'ja': '私は夕方に集会に行きたい。'}},
            {'vi': 'Bạn có đi nhóm họp không?',
             'pairs': [['Bạn', {'ko': '너', 'zh': '你', 'en': 'you', 'ja': 'お前、君'}],
                       ['có',
                        {'ko': '(의문)있다', 'zh': '（疑問）有', 'en': '(question) have / there is', 'ja': '（疑問）ある'}],
                       ['đi', {'ko': '가다', 'zh': '去', 'en': 'to go', 'ja': '行く'}],
                       ['nhóm họp', {'ko': '집회', 'zh': '聚會', 'en': 'meeting', 'ja': '集会'}],
                       ['không?',
                        {'ko': '(의문)없다',
                         'zh': '（疑問）沒有',
                         'en': "(question) not have / there isn't",
                         'ja': '（疑問）ない'}]],
             'kr': {'ko': '너 집회에 가?',
                    'zh': '你去聚會嗎？',
                    'en': 'Are you going to the meeting?',
                    'ja': 'あなたは集会に行く？'}}]},
 {'title': {'ko': '18. 다양한 동사로 연습 — học Kinh Thánh (성경 공부하기)',
            'zh': '18. 用各種動詞練習 — học Kinh Thánh（學習聖經）',
            'en': '18. Practice with various verbs — học Kinh Thánh (studying the Bible)',
            'ja': '18. さまざまな動詞で練習 — học Kinh Thánh（聖書を学ぶ）'},
  'note': {'ko': 'học(공부하다) + Kinh Thánh(성경).',
           'zh': 'học（學習）+ Kinh Thánh（聖經）。',
           'en': 'học (to study) + Kinh Thánh (the Bible).',
           'ja': 'học（勉強する）+ Kinh Thánh（聖書）。'},
  'steps': [{'vi': 'Tôi học.',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私'}],
                       ['học.', {'ko': '공부하다', 'zh': '學習', 'en': 'to study', 'ja': '勉強する'}]],
             'kr': {'ko': '나는 공부한다.', 'zh': '我學習。', 'en': 'I study.', 'ja': '私は勉強する。'}},
            {'vi': 'Tôi học Kinh Thánh.',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私'}],
                       ['học', {'ko': '공부하다', 'zh': '學習', 'en': 'to study', 'ja': '勉強する'}],
                       ['Kinh Thánh.', {'ko': '성경', 'zh': '聖經', 'en': 'the Bible', 'ja': '聖書'}]],
             'kr': {'ko': '나는 성경을 공부한다.', 'zh': '我研讀聖經。', 'en': 'I study the Bible.', 'ja': '私は聖書を勉強する。'}},
            {'vi': 'Tôi muốn học Kinh Thánh mỗi ngày.',
             'pairs': [['Tôi', {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私'}],
                       ['muốn', {'ko': '~하고 싶다', 'zh': '想要~', 'en': 'want to ~', 'ja': '~したい'}],
                       ['học', {'ko': '공부하다', 'zh': '學習', 'en': 'to study', 'ja': '勉強する'}],
                       ['Kinh Thánh', {'ko': '성경', 'zh': '聖經', 'en': 'the Bible', 'ja': '聖書'}],
                       ['mỗi ngày.', {'ko': '매일', 'zh': '每天', 'en': 'every day', 'ja': '毎日'}]],
             'kr': {'ko': '나는 매일 성경을 공부하고 싶다.',
                    'zh': '我想每天研讀聖經。',
                    'en': 'I want to study the Bible every day.',
                    'ja': '私は毎日聖書を勉強したい。'}}]},
 {'title': {'ko': '19. 다양한 동사로 연습 — Bạn đi làm (일하러 가기)',
            'zh': '19. 用各種動詞練習 — Bạn đi làm（去工作）',
            'en': '19. Practice with various verbs — Bạn đi làm (going to work)',
            'ja': '19. さまざまな動詞で練習 — Bạn đi làm（仕事に行く）'},
  'note': {'ko': "làm(일하다)이 đi 뒤에 오면 '일하러(출근)'라는 뜻이 돼요. 상대방(bạn·너)을 주어로 연습해요.",
           'zh': "làm（工作）放在 đi 後面，就變成'去工作（上班）'的意思。用對方（bạn·你）作主語來練習。",
           'en': "When làm (to work) follows đi, it means 'to go to work (commute)'. Practice using the "
                 'other person (bạn, you) as the subject.',
           'ja': 'làm（働く）が đi の後ろに来ると、「働きに（出勤）」という意味になります。相手（bạn・あなた）を主語にして練習します。'},
  'steps': [{'vi': 'Bạn đi.',
             'pairs': [['Bạn', {'ko': '너', 'zh': '你', 'en': 'you', 'ja': 'お前、君'}],
                       ['đi.', {'ko': '가다', 'zh': '去', 'en': 'to go', 'ja': '行く'}]],
             'kr': {'ko': '너는 간다.', 'zh': '你去。', 'en': 'You go.', 'ja': 'あなたは行く。'}},
            {'vi': 'Bạn đi làm.',
             'pairs': [['Bạn', {'ko': '너', 'zh': '你', 'en': 'you', 'ja': 'お前、君'}],
                       ['đi', {'ko': '가다', 'zh': '去', 'en': 'to go', 'ja': '行く'}],
                       ['làm.', {'ko': '일(하러)', 'zh': '工作(去做)', 'en': 'work (to do)', 'ja': '仕事(をしに)'}]],
             'kr': {'ko': '너는 일하러 간다.', 'zh': '你去工作。', 'en': 'You go to work.', 'ja': 'あなたは働きに行く。'}},
            {'vi': 'Bạn có đi làm không?',
             'pairs': [['Bạn', {'ko': '너', 'zh': '你', 'en': 'you', 'ja': 'お前、君'}],
                       ['có',
                        {'ko': '(의문)있다', 'zh': '（疑問）有', 'en': '(question) have / there is', 'ja': '（疑問）ある'}],
                       ['đi', {'ko': '가다', 'zh': '去', 'en': 'to go', 'ja': '行く'}],
                       ['làm', {'ko': '일(하러)', 'zh': '工作(去做)', 'en': 'work (to do)', 'ja': '仕事(をしに)'}],
                       ['không?',
                        {'ko': '(의문)없다',
                         'zh': '（疑問）沒有',
                         'en': "(question) not have / there isn't",
                         'ja': '（疑問）ない'}]],
             'kr': {'ko': '너 출근해?', 'zh': '你去上班嗎？', 'en': 'Are you going to work?', 'ja': 'あなたは出勤する？'}}]},
 {'title': {'ko': '20. 다양한 동사로 연습 — Bạn đi học (공부하러 가기)',
            'zh': '20. 用各種動詞練習 — Bạn đi học（去學習）',
            'en': '20. Practice with various verbs — Bạn đi học (going to study)',
            'ja': '20. さまざまな動詞で練習 — Bạn đi học（勉強しに行く）'},
  'note': {'ko': "học(공부하다)이 đi 뒤에 오면 '공부하러(학교에)'라는 뜻이 돼요.",
           'zh': "học（學習）放在 đi 後面，就變成'去學習（上學）'的意思。",
           'en': "When học (to study) follows đi, it means 'to go study (at school)'.",
           'ja': 'học（勉強する）が đi の後ろに来ると、「勉強しに（学校へ）」という意味になります。'},
  'steps': [{'vi': 'Bạn đi.',
             'pairs': [['Bạn', {'ko': '너', 'zh': '你', 'en': 'you', 'ja': 'お前、君'}],
                       ['đi.', {'ko': '가다', 'zh': '去', 'en': 'to go', 'ja': '行く'}]],
             'kr': {'ko': '너는 간다.', 'zh': '你去。', 'en': 'You go.', 'ja': 'あなたは行く。'}},
            {'vi': 'Bạn đi học.',
             'pairs': [['Bạn', {'ko': '너', 'zh': '你', 'en': 'you', 'ja': 'お前、君'}],
                       ['đi', {'ko': '가다', 'zh': '去', 'en': 'to go', 'ja': '行く'}],
                       ['học.', {'ko': '공부(하러)', 'zh': '（去）學習', 'en': '(to go) study', 'ja': '勉強（しに）'}]],
             'kr': {'ko': '너는 학교에 간다.', 'zh': '你去學校。', 'en': 'You go to school.', 'ja': 'あなたは学校に行く。'}},
            {'vi': 'Bạn đi học chưa?',
             'pairs': [['Bạn', {'ko': '너', 'zh': '你', 'en': 'you', 'ja': 'お前、君'}],
                       ['đi', {'ko': '가다', 'zh': '去', 'en': 'to go', 'ja': '行く'}],
                       ['học', {'ko': '공부(하러)', 'zh': '（去）學習', 'en': '(to go) study', 'ja': '勉強（しに）'}],
                       ['chưa?',
                        {'ko': '(완료?)아직', 'zh': '（完成？）還沒', 'en': '(Completed?) Not yet', 'ja': '（完了？）まだ'}]],
             'kr': {'ko': '너 학교 갔어?', 'zh': '你去學校了嗎？', 'en': 'Did you go to school?', 'ja': 'あなたは学校に行った？'}}]}]
