# "교과 > 문법 특강" subtab -- 연결사(connectives), 동사-위치(motion verbs),
# 위치 전치사(position prepositions), 길찾기 대화문(direction dialogues).
# Transcribed verbatim from pages 94-103 of the course booklet.
# (The A-Z 문법 사전 104-entry dictionary lives in grammar_dict_data.py.)
#
# Every Korean-language field ("kr", "ex_kr", "label", dialogue "title"/line "kr") is
# stored as a {"ko","zh","en","ja"} dict so js_json() (see build_app.py) serializes it
# straight into a JS object app_logic.js's T() helper can read directly.

CONNECTIVES = [{'no': 1,
  'label': {'ko': '소유의 의미를 표시하는 연결사 : (~의) — của',
            'zh': '表示所有意義的連接詞：(~的) — của',
            'en': "Connective marking possession: (~'s) — của",
            'ja': '所有の意味を表す接続詞：（〜の）— của',
            'de': 'Konjunktion/Partikel zum Ausdruck des Besitzes: (~s / von ~) — của',
            'fr': 'Conjonction/Particule marquant la possession : (de ~) — của',
            'pl': 'Spójnik/Partuła wyrażająca przynależność: (dopełniacz / ~a, ~u) — của'},
  'examples': [{'vi': 'Nhà của tôi rất đẹp.',
                'kr': {'ko': '나의 집은 매우 아름답다.',
                       'zh': '我的家非常漂亮。',
                       'en': 'My house is very beautiful.',
                       'ja': '私の家はとても美しい。',
                       'de': 'Mein Haus ist sehr schön.',
                       'fr': 'Ma maison est très belle.',
                       'pl': 'Mój dom jest bardzo piękny.'}},
               {'vi': 'Chị ấy mượn hai quyển sách của tôi.',
                'kr': {'ko': '그녀는 나의 책 2권을 빌렸다.',
                       'zh': '她借了我的兩本書。',
                       'en': 'She borrowed 2 of my books.',
                       'ja': '彼女は私の本を2冊借りた。',
                       'de': 'Sie hat zwei meiner Bücher ausgeliehen.',
                       'fr': 'Elle a emprunté deux de mes livres.',
                       'pl': 'Ona pożyczyła dwie moje książki.'}}]},
 {'no': 2,
  'label': {'ko': '수단이나 재료 방식을 나타내는 연결사 : (~으로) — bằng',
            'zh': '表示手段、材料或方式的連接詞：(用~) — bằng',
            'en': 'Connective indicating means, material, or method: (with/by ~) — bằng',
            'ja': '手段や材料・方法を表す接続詞：（〜で）— bằng',
            'de': 'Konjunktion/Präposition für Mittel, Material oder Methode: (mit / mittels ~) — '
                  'bằng',
            'fr': 'Conjonction/Préposition indiquant le moyen, le matériau ou la méthode : (en / '
                  'avec / au moyen de ~) — bằng',
            'pl': 'Spójnik/Przyimek wskazujący środek, materiał lub sposób: (narzędnik / za pomocą '
                  '~) — bằng'},
  'examples': [{'vi': 'Minh đi học bằng xe máy.',
                'kr': {'ko': 'Minh은 오토바이로 학교에 간다.',
                       'zh': 'Minh騎摩托車去學校。',
                       'en': 'Minh goes to school by motorbike.',
                       'ja': 'ミンはバイクで学校に行く。',
                       'de': 'Minh fährt mit dem Motorrad zur Schule.',
                       'fr': "Minh va à l'école à moto.",
                       'pl': 'Minh jeździ do szkoły motocyklem.'}}]},
 {'no': 3,
  'label': {'ko': '원인을 나타내는 연결사 : (~때문에) — vì / do / bởi',
            'zh': '表示原因的連接詞：(因為~) — vì / do / bởi',
            'en': 'Connective indicating cause: (because of ~) — vì / do / bởi',
            'ja': '原因を表す接続詞：（〜のため）— vì / do / bởi',
            'de': 'Konjunktionen zur Angabe des Grundes: (weil / wegen ~) — vì / do / bởi',
            'fr': 'Conjonctions exprimant la cause : (parce que / à cause de ~) — vì / do / bởi',
            'pl': 'Spójniki wskazujące przyczynę: (ponieważ / z powodu ~) — vì / do / bởi'},
  'examples': [{'vi': 'Em ấy khóc vì bố mẹ mắng.',
                'kr': {'ko': '부모가 꾸중을 하기 때문에 그 아이는 울고 있다.',
                       'zh': '因為父母在訓斥，那個孩子正在哭。',
                       'en': 'Because the parents are scolding, the child is crying.',
                       'ja': '両親が叱っているので、その子供は泣いています。',
                       'de': 'Das Kind weint, weil die Eltern schimpfen.',
                       'fr': "L'enfant pleure parce que ses parents le grondent.",
                       'pl': 'Dziecko płacze, ponieważ rodzice je karcą.'}},
               {'vi': 'Nó bị cảm do đi nắng.',
                'kr': {'ko': '더운데 돌아다녔기 때문에 그는 감기가 들었다.',
                       'zh': '因為天熱還到處走動，他感冒了。',
                       'en': 'Because he went around in the heat, he caught a cold.',
                       'ja': '暑いのに歩き回ったので、彼は風邪をひいた。',
                       'de': 'Er hat sich erkältet, weil er in der Hitze herumlief.',
                       'fr': "Il a attrapé un rhume parce qu'il est resté sous le soleil.",
                       'pl': 'Przeziębił się, bo chodził na upale.'}},
               {'vi': 'Chị ấy không cố gắng được nữa bởi mệt quá rồi.',
                'kr': {'ko': '그녀는 너무 피곤하기 때문에 더 이상 노력하지 못한다.',
                       'zh': '因為她太累了,所以無法再繼續努力。',
                       'en': "Because she is too tired, she can't try any harder.",
                       'ja': '彼女はとても疲れているので、これ以上頑張れない。',
                       'de': 'Sie kann sich nicht mehr anstrengen, weil sie zu müde ist.',
                       'fr': "Elle ne peut plus faire d'efforts parce qu'elle est trop fatiguée.",
                       'pl': 'Ona nie może się już więcej starać, ponieważ jest zbyt zmęczona.'}}]},
 {'no': 4,
  'label': {'ko': '사물의 시작과 끝을 나타내는 연결사 : (~부터, ~까지) — từ...đến',
            'zh': '表示事物起點和終點的連接詞：(從~，到~) — từ...đến',
            'en': 'Connective indicating the start and end of something: (from ~, to ~) — từ...đến',
            'ja': '物事の始まりと終わりを表す接続詞：（〜から、〜まで）— từ...đến',
            'de': 'Konjunktionen für Anfang und Ende: (von ~ bis ~) — từ...đến',
            'fr': "Conjonctions marquant le début et la fin : (de ~ à ~ / depuis ~ jusqu'à ~) — "
                  'từ...đến',
            'pl': 'Spójniki wskazujące początek i koniec: (od ~ do ~) — từ...đến'},
  'examples': [{'vi': 'Minh làm việc từ 8 giờ sáng đến 5 giờ chiều.',
                'kr': {'ko': 'Minh은 아침 8시부터 저녁 5시까지 일한다.',
                       'zh': 'Minh從早上8點工作到晚上5點。',
                       'en': 'Minh works from 8 a.m. to 5 p.m.',
                       'ja': 'ミンは朝8時から夕方5時まで働く。',
                       'de': 'Minh arbeitet von 8 Uhr morgens bis 5 Uhr nachmittags.',
                       'fr': "Minh travaille de 8 heures du matin à 5 heures de l'après-midi.",
                       'pl': 'Minh pracuje od 8 rano do 5 po południu.'}},
               {'vi': 'Đêm qua tôi thức đến 12 giờ.',
                'kr': {'ko': '어제 밤 나는 12시까지 잠을 자지 않았다.',
                       'zh': '昨晚我到12點都沒睡。',
                       'en': "Last night, I didn't sleep until 12 o'clock.",
                       'ja': '昨夜、私は12時まで眠りませんでした。',
                       'de': 'Gestern Nacht war ich bis 12 Uhr wach.',
                       'fr': "Hier soir, je suis resté éveillé jusqu'à minuit.",
                       'pl': 'Zeszłej nocy nie spałem do godziny 12.'}}]},
 {'no': 5,
  'label': {'ko': '목적을 나타내는 연결사 : (~하기 위하여) — để',
            'zh': '表示目的的連接詞：（為了~）— để',
            'en': 'A conjunction indicating purpose: (in order to ~) — để',
            'ja': '目的を表す接続詞：（～するために）— để',
            'de': 'Konjunktion zur Angabe des Zwecks: (um zu ~ / damit ~) — để',
            'fr': 'Conjonction exprimant le but : (pour / afin de ~) — để',
            'pl': 'Spójnik wyrażający cel: (aby / żeby / w celu ~) — để'},
  'examples': [{'vi': 'Tôi đến Việt Nam để học tiếng Việt.',
                'kr': {'ko': '나는 베트남어를 배우기 위해 베트남에 왔다.',
                       'zh': '我為了學越南語來到了越南。',
                       'en': 'I came to Vietnam to learn Vietnamese.',
                       'ja': '私はベトナム語を学ぶためにベトナムに来た。',
                       'de': 'Ich bin nach Vietnam gekommen, um Vietnamesisch zu lernen.',
                       'fr': 'Je suis venu au Vietnam pour apprendre le vietnamien.',
                       'pl': 'Przyjechałem do Wietnamu, aby uczyć się wietnamskiego.'}},
               {'vi': 'Nó hát để làm mẹ vui.',
                'kr': {'ko': '그는 어머니를 기쁘게 하기 위해 노래를 불렀다.',
                       'zh': '他為了讓母親高興而唱了歌。',
                       'en': 'He sang a song to make his mother happy.',
                       'ja': '彼は母を喜ばせるために歌を歌った。',
                       'de': 'Er hat gesungen, um seine Mutter zu erfreuen.',
                       'fr': 'Il a chanté pour faire plaisir à sa mère.',
                       'pl': 'Zaśpiewał piosenkę, żeby sprawić radość mamie.'}}]},
 {'no': 6,
  'label': {'ko': '지점을 나타내는 연결사 : (~에서) — tại / ở',
            'zh': '表示地點的連接詞:(~在)——tại / ở',
            'en': 'A connective indicating a location: (at ~) — tại / ở',
            'ja': '地点を表す接続詞:(~で)——tại / ở',
            'de': 'Präposition/Verbindungswort zur Angabe des Ortes: (in / an / bei ~) — tại / ở',
            'fr': 'Préposition/Connecteur indiquant le lieu : (à / dans / en ~) — tại / ở',
            'pl': 'Przyimek/Łącznik wskazujący miejsce: (w / na / przy ~) — tại / ở'},
  'examples': [{'vi': 'Ông ấy sống tại quê nhà.',
                'kr': {'ko': '그는 시골에서 살고 있다.',
                       'zh': '他住在鄉下。',
                       'en': 'He lives in the countryside.',
                       'ja': '彼は田舎に住んでいる。',
                       'de': 'Er lebt auf dem Land.',
                       'fr': 'Il vit à la campagne (dans son village natal).',
                       'pl': 'On mieszka na wsi (w rodzinnej miejscowości).'}},
               {'vi': 'Quyển sách của chị ở trên bàn.',
                'kr': {'ko': '언니의 책은 책상에 있다.',
                       'zh': '姐姐的書在書桌上。',
                       'en': "My older sister's book is on the desk.",
                       'ja': '姉の本は机の上にあります。',
                       'de': 'Das Buch meiner Schwester liegt auf dem Tisch.',
                       'fr': 'Le livre de ma sœur est sur la table.',
                       'pl': 'Książka mojej siostry leży na biurku.'}}]},
 {'no': 7,
  'label': {'ko': '위치를 나타내는 연결사 : (안에)(밖에)(위에)(아래에) — trong / ngoài / trên / dưới',
            'zh': '表示位置的連接詞：(裡面)(外面)(上面)(下面) — trong / ngoài / trên / dưới',
            'en': 'Connective indicating location: (inside)(outside)(on top of)(below) — trong / '
                  'ngoài / trên / dưới',
            'ja': '位置を表す接続詞：（中に）（外に）（上に）（下に）— trong / ngoài / trên / dưới',
            'de': 'Lokale Präpositionen/Verbindungswörter: (in / außerhalb / auf / unter) — trong '
                  '/ ngoài / trên / dưới',
            'fr': 'Prépositions/Connecteurs de position : (dans / hors de / sur / sous) — trong / '
                  'ngoài / trên / dưới',
            'pl': 'Przyimki/Łączniki położenia: (wewnątrz / na zewnątrz / na / pod) — trong / '
                  'ngoài / trên / dưới'},
  'examples': [{'vi': 'Họ học trong ở nhà.',
                'kr': {'ko': '그들은 집안에서 공부한다.',
                       'zh': '他們在家裡學習。',
                       'en': 'They study inside the house.',
                       'ja': '彼らは家の中で勉強する。',
                       'de': 'Sie lernen im Haus.',
                       'fr': "Ils étudient à l'intérieur de la maison.",
                       'pl': 'Oni uczą się w domu.'}},
               {'vi': 'Nó nằm ngủ ở ngoài vườn.',
                'kr': {'ko': '그는 정원에서 누워 잔다.',
                       'zh': '他躺在院子裡睡覺。',
                       'en': 'He lies down and sleeps in the garden.',
                       'ja': '彼は庭で横になって眠る。',
                       'de': 'Er liegt und schläft draußen im Garten.',
                       'fr': 'Il dort dehors dans le jardin.',
                       'pl': 'On leży i śpi w ogrodzie.'}},
               {'vi': 'Anh ấy làm việc ở trên tầng ba.',
                'kr': {'ko': '그는 3층에서 일하고 있다.',
                       'zh': '他在三樓工作。',
                       'en': 'He is working on the 3rd floor.',
                       'ja': '彼は3階で働いている。',
                       'de': 'Er arbeitet im 3. Stock.',
                       'fr': 'Il travaille au troisième étage.',
                       'pl': 'On pracuje na trzecim piętrze.'}},
               {'vi': 'Mẹ chị đang nấu cơm ở dưới bếp.',
                'kr': {'ko': '언니의 어머니는 지금 부엌에서 밥을 짓고 계셔요.',
                       'zh': '她的母親正在廚房做飯。',
                       'en': 'Her mother is cooking rice in the kitchen.',
                       'ja': '彼女の母は台所でご飯を炊いている。',
                       'de': 'Ihre Mutter kocht gerade unten in der Küche.',
                       'fr': 'Sa mère fait la cuisine en bas dans la cuisine.',
                       'pl': 'Jej mama gotuje obiad na dole w kuchni.'}}]},
 {'no': 8,
  'label': {'ko': '비교를 나타내는 연결사 : (~처럼) — như',
            'zh': '表示比較的連接詞：(像~一樣) — như',
            'en': 'Connective indicating comparison: (like ~) — như',
            'ja': '比較を表す接続詞：（〜のように）— như',
            'de': 'Vergleichskonjunktion: (wie ~) — như',
            'fr': 'Conjonction de comparaison : (comme ~) — như',
            'pl': 'Spójnik porównawczy: (jak ~) — như'},
  'examples': [{'vi': 'Phong cảnh ở đây đẹp như bức tranh.',
                'kr': {'ko': '여기의 경치는 마치 그림처럼 아름답다.',
                       'zh': '這裡的景色美得像畫一樣。',
                       'en': 'The scenery here is as beautiful as a painting.',
                       'ja': 'ここの景色はまるで絵のように美しい。',
                       'de': 'Die Landschaft hier ist wunderschön wie ein Gemälde.',
                       'fr': "Le paysage ici est aussi beau qu'un tableau.",
                       'pl': 'Tutejszy krajobraz jest piękny jak obraz.'}},
               {'vi': 'Cô ấy nói như hát.',
                'kr': {'ko': '그녀는 노래 부르듯이 말한다.',
                       'zh': '她說話就像唱歌一樣。',
                       'en': 'She speaks as if singing.',
                       'ja': '彼女は歌うように話す。',
                       'de': 'Sie spricht, als würde sie singen.',
                       'fr': 'Elle parle comme si elle chantait.',
                       'pl': 'Ona mówi tak, jakby śpiewała.'}}]},
 {'no': 9,
  'label': {'ko': '관계와 상태 표현을 나타내는 연결사 : (~와 함께, 에게, ~로) — với',
            'zh': '表示關係和狀態的連接詞：（和~一起、給、以~）— với',
            'en': 'A connector expressing relationships and states: (with ~, to, as ~) — với',
            'ja': '関係と状態の表現を表す接続詞：（~と一緒に、~に、~として）— với',
            'de': 'Verbindungswort für Beziehung und Begleitung: (mit ~, zu, gegenüber) — với',
            'fr': "Connecteur exprimant la relation et l'accompagnement : (avec ~, envers, à) — "
                  'với',
            'pl': 'Łącznik wyrażający relację i towarzyszenie: (z ~, do, wobec) — với'},
  'examples': [{'vi': 'Bà ấy phàn nàn với tôi về nhiều điều.',
                'kr': {'ko': '그 부인은 나에게 많은 것들에 대해 불평했다.',
                       'zh': '那位夫人向我抱怨了很多事情。',
                       'en': 'That lady complained to me about many things.',
                       'ja': 'その婦人は私にたくさんのことについて不平を言った。',
                       'de': 'Die Dame hat sich bei mir über viele Dinge beschwert.',
                       'fr': "Cette dame s'est plainte auprès de moi de beaucoup de choses.",
                       'pl': 'Ta pani narzekała przede mną na wiele spraw.'}},
               {'vi': 'Đây là chuyện bí mật, đừng nói với ai.',
                'kr': {'ko': '이것은 비밀 이야기예요. 누구하고도 이야기하지 마세요.',
                       'zh': '這是一個秘密。請不要和任何人說。',
                       'en': "This is a secret. Please don't talk about it with anyone.",
                       'ja': 'これは秘密の話です。誰にも話さないでください。',
                       'de': 'Das ist ein Geheimnis, sprich mit niemandem darüber.',
                       'fr': "C'est un secret, n'en parle à personne.",
                       'pl': 'To tajemnica, nie mów nikomu.'}}]},
 {'no': 10,
  'label': {'ko': '활동의 방향과 범위를 나타내는 연결사 : (~관해서) — về',
            'zh': '表示活動方向和範圍的連接詞:(關於~)——về',
            'en': 'A connective indicating the direction and scope of an activity: (about ~) — về',
            'ja': '活動の方向と範囲を表す接続詞:(~について)——về',
            'de': 'Verbindungswort für Richtung und Gegenstand/Thema: (über ~ / in Richtung) — về',
            'fr': 'Connecteur indiquant la direction ou le domaine/thème : (vers / à propos de ~) '
                  '— về',
            'pl': 'Łącznik wskazujący kierunek lub zakres/temat: (w stronę / o ~, na temat ~) — '
                  'về'},
  'examples': [{'vi': 'Em bé chạy về phía mẹ.',
                'kr': {'ko': '꼬마는 어머니 쪽으로 달려간다.',
                       'zh': '小孩朝媽媽那邊跑去。',
                       'en': 'The little child runs toward the mother.',
                       'ja': '子供は母親の方へ走っていく。',
                       'de': 'Das kleine Kind rennt zur Mutter.',
                       'fr': 'Le petit enfant court vers sa mère.',
                       'pl': 'Małe dziecko biegnie w stronę mamy.'}},
               {'vi': 'Anh ấy có năng khiếu về âm nhạc.',
                'kr': {'ko': '그는 음악에 대해 소질이 있다.',
                       'zh': '他在音樂方面有天賦。',
                       'en': 'He has talent for music.',
                       'ja': '彼は音楽に対して才能がある。',
                       'de': 'Er hat eine Begabung für Musik.',
                       'fr': 'Il a un talent pour la musique.',
                       'pl': 'On ma talent muzyczny.'}}]},
 {'no': 11,
  'label': {'ko': '행동의 목적과 대상을 나타내는 연결사 : (~하도록, ~에게) — cho',
            'zh': '表示行動的目的和對象的連接詞:(為了~,給~)——cho',
            'en': 'A connective indicating the purpose and object of an action: (so that ~, to ~) '
                  '— cho',
            'ja': '行動の目的と対象を表す接続詞:(~するように、~に)——cho',
            'de': 'Verbindungswort für Zweck und Empfänger: (damit ~, für ~, an) — cho',
            'fr': 'Connecteur marquant le but ou le destinataire : (afin que ~, pour ~, à) — cho',
            'pl': 'Łącznik wskazujący cel lub odbiorcę: (żeby ~, dla ~, komuś) — cho'},
  'examples': [{'vi': 'Chúng ta nên đi bằng xe máy cho nhanh.',
                'kr': {'ko': '좀 빨리 가기 위해 우리들은 오토바이로 가야한다.',
                       'zh': '為了快點去,我們得騎摩托車去。',
                       'en': 'In order to go a bit faster, we have to go by motorbike.',
                       'ja': '少し早く行くために、私たちはバイクで行かなければならない。',
                       'de': 'Wir sollten mit dem Motorrad fahren, damit es schneller geht.',
                       'fr': 'Nous devrions y aller à moto pour que ce soit plus rapide.',
                       'pl': 'Powinniśmy pojechać motocyklem, żeby było szybciej.'}},
               {'vi': 'Anh Phát thích hát cho các anh chị.',
                'kr': {'ko': 'Phát 형제는 형제, 자매들에게 노래 불러주는 것을 좋아한다.',
                       'zh': 'Phát弟兄喜歡給弟兄姐妹們唱歌。',
                       'en': 'Brother Phát likes singing for the brothers and sisters.',
                       'ja': 'ファット兄弟は兄弟姉妹たちに歌を歌ってあげるのが好きだ。',
                       'de': 'Bruder Phát singt gerne für die Brüder und Schwestern.',
                       'fr': 'Frère Phát aime chanter pour les frères et sœurs.',
                       'pl': 'Brat Phát lubi śpiewać dla braci i sióstr.'}}]},
 {'no': 12,
  'label': {'ko': '설명의 의미를 나타내는 관계사 : — mà',
            'zh': '表示說明意義的關係詞：— mà',
            'en': 'Relative word indicating an explanatory meaning: — mà',
            'ja': '説明の意味を表す関係詞：— mà',
            'de': 'Relativpartikel mit erläuternder Funktion: — mà',
            'fr': 'Particule relative à valeur explicative : — mà',
            'pl': 'Zaimek względny o funkcji objaśniającej: — mà'},
  'examples': [{'vi': 'Cô gái mà anh gặp hôm qua tên là Hoa.',
                'kr': {'ko': '당신이 어제 만난 아가씨의 이름은 Hoa이다.',
                       'zh': '您昨天見到的那位小姐名叫Hoa。',
                       'en': 'The name of the young lady you met yesterday is Hoa.',
                       'ja': 'あなたが昨日会った女性の名前はHoaです。',
                       'de': 'Die junge Frau, die du gestern getroffen hast, heißt Hoa.',
                       'fr': "La jeune fille que tu as rencontrée hier s'appelle Hoa.",
                       'pl': 'Młoda kobieta, którą wczoraj spotkałeś, ma na imię Hoa.'}},
               {'vi': 'Tôi đã mua được quyển sách mà ông giới thiệu hôm trước.',
                'kr': {'ko': '당신이 전날 소개해 준 책을 나는 샀다.',
                       'zh': '我買了您前幾天介紹給我的書。',
                       'en': 'I bought the book you recommended to me the other day.',
                       'ja': 'あなたが先日紹介してくれた本を私は買いました。',
                       'de': 'Ich habe das Buch gekauft, das Sie mir neulich empfohlen haben.',
                       'fr': "J'ai acheté le livre que vous m'aviez recommandé l'autre jour.",
                       'pl': 'Kupiłem książkę, którą pan mi niedawno polecił.'}}]},
 {'no': 13,
  'label': {'ko': '대등 연결사 : — và / với / cùng với / cũng như / rồi / hay / hoặc / không...mà cũng '
                  'không',
            'zh': '並列連接詞： — và / với / cùng với / cũng như / rồi / hay / hoặc / không...mà cũng '
                  'không',
            'en': 'Coordinating conjunctions: — và / với / cùng với / cũng như / rồi / hay / hoặc '
                  '/ không...mà cũng không',
            'ja': '並列接続詞：— và / với / cùng với / cũng như / rồi / hay / hoặc / không...mà cũng '
                  'không',
            'de': 'Nebenordnende Konjunktionen: — và / với / cùng với / cũng như / rồi / hay / '
                  'hoặc / không...mà cũng không',
            'fr': 'Conjonctions de coordination : — và / với / cùng với / cũng như / rồi / hay / '
                  'hoặc / không...mà cũng không',
            'pl': 'Spójniki współrzędne: — và / với / cùng với / cũng như / rồi / hay / hoặc / '
                  'không...mà cũng không'},
  'examples': [{'vi': 'Minh và Phát là bạn thân.',
                'kr': {'ko': 'Minh과 Phát은 친한 친구이다.',
                       'zh': 'Minh和Phát是好朋友。',
                       'en': 'Minh and Phát are close friends.',
                       'ja': 'ミンとファットは親しい友達だ。',
                       'de': 'Minh und Phát sind enge Freunde.',
                       'fr': 'Minh et Phát sont des amis proches.',
                       'pl': 'Minh i Phát są bliskimi przyjaciółmi.'}},
               {'vi': 'Chiều qua tôi gặp Minh với Phát ở thư viện.',
                'kr': {'ko': '어제 오후 Minh과 Phát은 도서관에서 만났다.',
                       'zh': '昨天下午Minh和Phát在圖書館見面了。',
                       'en': 'Yesterday afternoon, Minh and Phát met at the library.',
                       'ja': '昨日の午後、MinhとPhátは図書館で会いました。',
                       'de': 'Gestern Nachmittag habe ich Minh und Phát in der Bibliothek '
                             'getroffen.',
                       'fr': "Hier après-midi, j'ai rencontré Minh et Phát à la bibliothèque.",
                       'pl': 'Wczoraj po południu spotkałem Minha i Pháta w bibliotece.'}},
               {'vi': 'Chị ấy mua cam cùng với táo.',
                'kr': {'ko': '그녀는 귤을 사과와 같이 샀다.',
                       'zh': '她把橘子和蘋果一起買了。',
                       'en': 'She bought tangerines along with apples.',
                       'ja': '彼女はみかんをりんごと一緒に買った。',
                       'de': 'Sie kaufte Orangen zusammen mit Äpfeln.',
                       'fr': 'Elle a acheté des oranges avec des pommes.',
                       'pl': 'Kupiła pomarańcze razem z jabłkami.'}},
               {'vi': 'Anh ấy cũng như tôi, đều là người tốt.',
                'kr': {'ko': '그는 나와 마찬가지로 모두 좋은 사람이에요.',
                       'zh': '他和我一樣,都是好人。',
                       'en': 'He, just like me, is a good person.',
                       'ja': '彼は私と同じくいい人です。',
                       'de': 'Er ist, genauso wie ich, ein guter Mensch.',
                       'fr': 'Lui, tout comme moi, est une bonne personne.',
                       'pl': 'On, tak samo jak ja, jest dobrym człowiekiem.'}},
               {'vi': 'Anh ấy chờ chị một lúc rồi đi.',
                'kr': {'ko': '그 남자는 당신을 잠시 기다린 뒤 갔다.',
                       'zh': '那個男人稍等了你一會兒之後就走了。',
                       'en': 'That man waited for you for a while and then left.',
                       'ja': 'その男はあなたをしばらく待ってから去った。',
                       'de': 'Er wartete eine Weile auf sie und ging dann.',
                       'fr': "Il l'a attendue un moment puis est parti.",
                       'pl': 'Poczekał na nią chwilę, a potem poszedł.'}},
               {'vi': 'Nó đang học bài hay ngủ đấy?',
                'kr': {'ko': '그는 공부를 하고 있어요, 아니면 자고 있어요?',
                       'zh': '他是在學習,還是在睡覺?',
                       'en': 'Is he studying, or is he sleeping?',
                       'ja': '彼は勉強していますか、それとも寝ていますか?',
                       'de': 'Lernt er gerade oder schläft er?',
                       'fr': "Est-ce qu'il étudie ou est-ce qu'il dort ?",
                       'pl': 'Czy on się uczy, czy śpi?'}},
               {'vi': 'Tối ngày mai hoặc tối ngày kia tôi sẽ đến anh.',
                'kr': {'ko': '내일 저녁 혹은 모레 저녁 내가 당신한테 갈 것입니다.',
                       'zh': '明天晚上或者後天晚上我會去找您。',
                       'en': 'Tomorrow evening or the evening after tomorrow, I will come to you.',
                       'ja': '明日の夕方か明後日の夕方、私はあなたのところに行きます。',
                       'de': 'Morgen Abend oder übermorgen Abend komme ich zu dir.',
                       'fr': 'Demain soir ou après-demain soir, je viendrai chez toi.',
                       'pl': 'Jutro wieczorem albo pojutrze wieczorem przyjdę do ciebie.'}},
               {'vi': 'Anh đến không sớm mà cũng không muộn.',
                'kr': {'ko': '당신은 일찍 온 것도 아니고 그렇다고 늦게 온 것도 아니다.',
                       'zh': '您既不是早到，也不是晚到。',
                       'en': 'You neither came early nor came late.',
                       'ja': 'あなたは早く来たわけでもなく、かといって遅く来たわけでもない。',
                       'de': 'Du bist weder früh noch spät gekommen.',
                       'fr': "Tu n'es arrivé ni tôt ni tard.",
                       'pl': 'Nie przyszedłeś ani za wcześnie, ani za późno.'}}]},
 {'no': 14,
  'label': {'ko': '역접 연결 : 상반 관계를 갖고 있는 단어결합이나 두 문장을 연결하기 위해 쓰입니다. — mà / nhưng / huống hồ / còn / '
                  'tuy...nhưng / mặc dù...nhưng',
            'zh': '逆接連接：用於連接具有相反關係的詞組或兩個句子。 — mà / nhưng / huống hồ / còn / tuy...nhưng / mặc '
                  'dù...nhưng',
            'en': 'Adversative connection: used to connect word combinations or two sentences that '
                  'have a contrasting relationship. — mà / nhưng / huống hồ / còn / tuy...nhưng / '
                  'mặc dù...nhưng',
            'ja': '逆接：相反する関係を持つ語の組み合わせや二つの文をつなぐために使われます。 — mà / nhưng / huống hồ / còn / '
                  'tuy...nhưng / mặc dù...nhưng',
            'de': 'Gegensätzliche (adversative) Verbindung: Verbindet Wörter oder Sätze mit '
                  'gegensätzlicher Bedeutung. — mà / nhưng / huống hồ / còn / tuy...nhưng / mặc '
                  'dù...nhưng',
            'fr': "Connexion d'opposition (adversative) : utilisée pour relier des mots ou phrases "
                  'de sens opposé. — mà / nhưng / huống hồ / còn / tuy...nhưng / mặc dù...nhưng',
            'pl': 'Połączenie przeciwstawne: łączy słowa lub zdania o przeciwstawnym znaczeniu. — '
                  'mà / nhưng / huống hồ / còn / tuy...nhưng / mặc dù...nhưng'},
  'examples': [{'vi': 'Cái bút này rẻ mà đẹp.',
                'kr': {'ko': '이 필기구는 싸지만 아름답다.',
                       'zh': '這支文具便宜但很漂亮。',
                       'en': 'This writing instrument is cheap but beautiful.',
                       'ja': 'この筆記用具は安いが美しい。',
                       'de': 'Dieser Stift ist billig, aber schön.',
                       'fr': 'Ce stylo est bon marché mais joli.',
                       'pl': 'To pióro jest tanie, ale ładne.'}},
               {'vi': 'Đi bằng xe máy mệt nhưng tiện.',
                'kr': {'ko': '오토바이로 가는 것이 피곤하지만 그러나 편리하다.',
                       'zh': '騎摩托車雖然累，但很方便。',
                       'en': 'Going by motorbike is tiring, but convenient.',
                       'ja': 'バイクで行くのは疲れるが、便利だ。',
                       'de': 'Mit dem Motorrad zu fahren ist anstrengend, aber praktisch.',
                       'fr': 'Voyager à moto est fatigant mais pratique.',
                       'pl': 'Jazda motocyklem jest męcząca, ale wygodna.'}},
               {'vi': 'Nó không có tiền mua xe đạp huống hồ xe máy.',
                'kr': {'ko': '그는 자전거 살 돈이 없는데 오토바이는 말할 필요도 없다.',
                       'zh': '他連買自行車的錢都沒有,更不用說摩托車了。',
                       'en': "He doesn't even have money to buy a bicycle, let alone a motorbike.",
                       'ja': '彼は自転車を買うお金もないのに、オートバイは言うまでもない。',
                       'de': 'Er hat nicht einmal Geld für ein Fahrrad, geschweige denn für ein '
                             'Motorrad.',
                       'fr': "Il n'a même pas d'argent pour acheter un vélo, encore moins une "
                             'moto.',
                       'pl': 'On nie ma pieniędzy nawet na rower, a co dopiero na motocykl.'}},
               {'vi': 'Nó gầy còn em nó béo.',
                'kr': {'ko': '그는 말랐는데 그의 동생은 뚱뚱하다.',
                       'zh': '他很瘦,但他的弟弟(妹妹)很胖。',
                       'en': 'He is thin, but his younger sibling is fat.',
                       'ja': '彼は痩せているが、彼の弟(妹)は太っている。',
                       'de': 'Er ist dünn, während sein jüngeres Geschwister dick ist.',
                       'fr': 'Il est mince, tandis que son jeune frère est gros.',
                       'pl': 'On jest szczupły, podczas gdy jego młodsze rodzeństwo jest tęgie.'}},
               {'vi': 'Tuy không có bản đồ nhưng cô ấy vẫn không lạc đường.',
                'kr': {'ko': '비록 지도가 없지만 그녀는 여전히 길을 잃지 않았다.',
                       'zh': '雖然沒有地圖，但她依然沒有迷路。',
                       'en': 'Although there was no map, she still did not get lost.',
                       'ja': '地図がなかったけれど、彼女は道に迷いませんでした。',
                       'de': 'Obwohl sie keine Karte hatte, hat sie sich nicht verlaufen.',
                       'fr': "Bien qu'elle n'ait pas de carte, elle ne s'est pas perdue.",
                       'pl': 'Chociaż nie miała mapy, to i tak się nie zgubiła.'}},
               {'vi': 'Mặc dù thất bại nhiều lần nhưng anh ấy vẫn không nản lòng.',
                'kr': {'ko': '비록 여러 번 실패를 했지만 그러나 그는 여전히 낙담하지 않았다.',
                       'zh': '雖然他失敗了好幾次，但他依然沒有氣餒。',
                       'en': 'Although he failed many times, he still did not lose heart.',
                       'ja': '彼は何度も失敗したけれど、それでも落胆しませんでした。',
                       'de': 'Obwohl er viele Male gescheitert ist, hat er den Mut nicht verloren.',
                       'fr': "Bien qu'il ait échoué plusieurs fois, il ne s'est pas découragé.",
                       'pl': 'Chociaż wielokrotnie poniósł porażkę, nie stracił zapału.'}}]},
 {'no': 15,
  'label': {'ko': '순접 연결 : 순접 연결은 가설과 결과 그리고 원인과 결과 두 가지 종류가 있습니다. — nếu...(thì) / giá...(thì) / '
                  'hễ...là / vì...mà / tại...nên / vì...nên / sở dĩ...là vì',
            'zh': '順接連接：順接連接分為假設與結果、原因與結果兩種。 — nếu...(thì) / giá...(thì) / hễ...là / vì...mà / '
                  'tại...nên / vì...nên / sở dĩ...là vì',
            'en': 'Concordant (agreeing) connection: there are two types — hypothesis-and-result, '
                  'and cause-and-result. — nếu...(thì) / giá...(thì) / hễ...là / vì...mà / '
                  'tại...nên / vì...nên / sở dĩ...là vì',
            'ja': '順接：順接には仮定と結果、原因と結果の2種類があります。 — nếu...(thì) / giá...(thì) / hễ...là / vì...mà / '
                  'tại...nên / vì...nên / sở dĩ...là vì',
            'de': 'Kausale und konditionale Satzverbindung: Es gibt zwei Arten – Bedingung & Folge '
                  'sowie Ursache & Wirkung. — nếu...(thì) / giá...(thì) / hễ...là / vì...mà / '
                  'tại...nên / vì...nên / sở dĩ...là vì',
            'fr': 'Connexion logique : comprend la condition-conséquence et la cause-effet. — '
                  'nếu...(thì) / giá...(thì) / hễ...là / vì...mà / tại...nên / vì...nên / sở '
                  'dĩ...là vì',
            'pl': 'Połączenie wynikowe i przyczynowo-skutkowe: obejmuje warunek-skutek oraz '
                  'przyczynę-skutek. — nếu...(thì) / giá...(thì) / hễ...là / vì...mà / tại...nên / '
                  'vì...nên / sở dĩ...là vì'},
  'examples': [{'vi': 'Nếu chị đến muộn (thì) sẽ không gặp anh ấy.',
                'kr': {'ko': '만약 당신이 늦게 도착하면 그를 만나지 못할 것이다.',
                       'zh': '如果您晚到，就見不到他了。',
                       'en': "If you arrive late, you won't be able to meet him.",
                       'ja': 'もしあなたが遅く着いたら、彼に会えないでしょう。',
                       'de': 'Wenn du zu spät kommst, wirst du ihn nicht treffen.',
                       'fr': 'Si tu arrives en retard, tu ne le rencontreras pas.',
                       'pl': 'Jeśli przyjedziesz za późno, to się z nim nie spotkasz.'}},
               {'vi': 'Giá anh ấy ở nhà (thì) đã không bị tai nạn.',
                'kr': {'ko': '만약 그가 집에 있었다면 재난을 당하지 않았을 텐데.',
                       'zh': '如果他當時在家，就不會遭遇災難了。',
                       'en': "If he had been at home, he wouldn't have suffered the disaster.",
                       'ja': 'もし彼が家にいたなら、災難に遭わなかっただろうに。',
                       'de': 'Wäre er zu Hause geblieben, hätte er keinen Unfall gehabt.',
                       'fr': "S'il était resté à la maison, il n'aurait pas eu d'accident.",
                       'pl': 'Gdyby był w domu, nie uległby wypadkowi.'}},
               {'vi': 'Hễ trời lạnh là bà ấy bị ho.',
                'kr': {'ko': '날씨가 춥기만 하면 그 부인은 기침을 한다.',
                       'zh': '只要天氣一冷,那位夫人就會咳嗽。',
                       'en': 'Whenever the weather gets cold, that lady coughs.',
                       'ja': '天気が寒くなりさえすれば、その婦人は咳をする。',
                       'de': 'Sobald es kalt wird, muss die Dame husten.',
                       'fr': "Dès qu'il fait froid, cette dame tousse.",
                       'pl': 'Ilekroć robi się zimno, ta pani kaszle.'}},
               {'vi': 'Chắc chắn em sẽ đỗ nếu em cố gắng học.',
                'kr': {'ko': '만약 네가 열심히 공부하면 분명히 너는 시험에 합격할 것이다.',
                       'zh': '如果你努力學習，你一定會通過考試的。',
                       'en': 'If you study hard, you will definitely pass the exam.',
                       'ja': 'もし君が一生懸命勉強すれば、きっと君は試験に合格するだろう。',
                       'de': 'Du wirst die Prüfung sicher bestehen, wenn du fleißig lernst.',
                       'fr': "Tu réussiras certainement l'examen si tu étudies avec assiduité.",
                       'pl': 'Na pewno zdasz egzamin, jeśli będziesz pilnie się uczyć.'}},
               {'vi': 'Vì anh không đến mà chị ấy buồn.',
                'kr': {'ko': '그가 안 오기 때문에 그녀는 슬퍼한다.',
                       'zh': '因為他不來,所以她很傷心。',
                       'en': 'She is sad because he is not coming.',
                       'ja': '彼が来ないので彼女は悲しんでいる。',
                       'de': 'Weil du nicht kommst, ist sie traurig.',
                       'fr': 'Parce que tu ne viens pas, elle est triste.',
                       'pl': 'Ona jest smutna, ponieważ ty nie przychodzisz.'}},
               {'vi': 'Tại đường tắc nên tôi đến muộn.',
                'kr': {'ko': '길이 막혔기 때문에 나는 늦게 왔다.',
                       'zh': '因為堵車,所以我來晚了。',
                       'en': 'Because the road was blocked, I came late.',
                       'ja': '道が渋滞していたので、私は遅く来た。',
                       'de': 'Weil die Straße verstopft war, bin ich zu spät gekommen.',
                       'fr': 'Parce que la route était embouteillée, je suis arrivé en retard.',
                       'pl': 'Spóźniłem się, ponieważ ulica była zakorkowana.'}},
               {'vi': 'Xe tôi bị hỏng nên tôi đến muộn.',
                'kr': {'ko': '내 차가 고장이 났기 때문에 나는 늦게 도착했다.',
                       'zh': '因為我的車壞了,所以我遲到了。',
                       'en': 'Because my car broke down, I arrived late.',
                       'ja': '私の車が故障したので、私は遅く到着した。',
                       'de': 'Weil mein Auto eine Panne hatte, bin ich zu spät angekommen.',
                       'fr': 'Parce que ma voiture est tombée en panne, je suis arrivé en retard.',
                       'pl': 'Przyjechałem późno, ponieważ zepsuł mi się samochód.'}},
               {'vi': 'Tôi đau đầu vì không ngủ được.',
                'kr': {'ko': '잠을 잘 수 없었기 때문에 나는 머리가 아프다.',
                       'zh': '因為睡不著覺,所以我頭疼。',
                       'en': "Because I couldn't sleep, I have a headache.",
                       'ja': '眠ることができなかったので、私は頭が痛い。',
                       'de': 'Ich habe Kopfschmerzen, weil ich nicht schlafen konnte.',
                       'fr': "J'ai mal à la tête parce que je n'ai pas pu dormir.",
                       'pl': 'Boli mnie głowa, ponieważ nie mogłem spać.'}},
               {'vi': 'Sở dĩ mẹ mắng nó là vì nó hư.',
                'kr': {'ko': '당연히 어머니가 그를 야단치는 것은 그의 행실이 나쁘기 때문이다.',
                       'zh': '母親責罵他，當然是因為他行為不端。',
                       'en': 'Naturally, the reason his mother scolds him is because of his bad '
                             'behavior.',
                       'ja': '当然、母が彼を叱るのは彼の行いが悪いからだ。',
                       'de': 'Dass die Mutter mit ihm schimpft, liegt natürlich daran, dass er '
                             'sich schlecht benommen hat.',
                       'fr': "La raison pour laquelle sa mère le gronde, c'est qu'il s'est mal "
                             'conduit.',
                       'pl': 'Powodem, dla którego mama go karci, jest jego złe zachowanie.'}}]}]

MOTION_VERBS = [{'vi': 'Đi',
  'kr': {'ko': '가다',
         'zh': '去',
         'en': 'to go',
         'ja': '行く',
         'de': 'gehen',
         'fr': 'aller',
         'pl': 'iść'},
  'ex_vi': 'Chúng ta đi học.',
  'ex_kr': {'ko': '우리는 학교에 갑니다.',
            'zh': '我們去學校。',
            'en': 'We go to school.',
            'ja': '私たちは学校に行きます。',
            'de': 'Wir gehen zur Schule.',
            'fr': "Nous allons à l'école.",
            'pl': 'Idziemy do szkoły.'}},
 {'vi': 'Đến',
  'kr': {'ko': '도착하다',
         'zh': '到達',
         'en': 'to arrive',
         'ja': '到着する',
         'de': 'ankommen',
         'fr': 'arriver',
         'pl': 'przybywać / docierać'},
  'ex_vi': 'Tôi đến nhà của anh.',
  'ex_kr': {'ko': '나는 당신 집에 도착했습니다.',
            'zh': '我到您家了。',
            'en': 'I have arrived at your house.',
            'ja': '私はあなたの家に着きました。',
            'de': 'Ich bin bei dir zu Hause angekommen.',
            'fr': 'Je suis arrivé chez toi.',
            'pl': 'Przybyłem do twojego domu.'}},
 {'vi': 'Vào',
  'kr': {'ko': '들어오다',
         'zh': '進來',
         'en': 'to come in',
         'ja': '入って来る',
         'de': 'hereinkommen / hineingehen',
         'fr': 'entrer',
         'pl': 'wchodzić'},
  'ex_vi': 'Chúng tôi vào được không?',
  'ex_kr': {'ko': '우리가 들어가도 될까요?',
            'zh': '我們可以進去嗎？',
            'en': 'May we come in?',
            'ja': '私たちが入ってもいいですか。',
            'de': 'Dürfen wir hereinkommen?',
            'fr': 'Pouvons-nous entrer ?',
            'pl': 'Czy możemy wejść?'}},
 {'vi': 'Ra',
  'kr': {'ko': '나가다',
         'zh': '出去',
         'en': 'to go out',
         'ja': '出る、出かける',
         'de': 'hinausgehen',
         'fr': 'sortir',
         'pl': 'wychodzić'},
  'ex_vi': 'Ra cửa này.',
  'ex_kr': {'ko': '이 문으로 나갑니다.',
            'zh': '從這扇門出去。',
            'en': 'Go out through this door.',
            'ja': 'この扉から出ます。',
            'de': 'Gehen Sie durch diese Tür hinaus.',
            'fr': 'Sortez par cette porte.',
            'pl': 'Proszę wyjść tymi drzwiami.'}},
 {'vi': 'Lên',
  'kr': {'ko': '올라가다',
         'zh': '上去',
         'en': 'to go up',
         'ja': '上がる',
         'de': 'hinaufgehen / nach oben',
         'fr': 'monter',
         'pl': 'wchodzić na górę'},
  'ex_vi': 'Lên tầng hai.',
  'ex_kr': {'ko': '2층까지 올라가다.',
            'zh': '上到2樓。',
            'en': 'Go up to the 2nd floor.',
            'ja': '2階まで上がる。',
            'de': 'In den 2. Stock hinaufgehen.',
            'fr': 'Monter au deuxième étage.',
            'pl': 'Wejść na drugie piętro.'}},
 {'vi': 'Xuống',
  'kr': {'ko': '내려가다',
         'zh': '下去',
         'en': 'to go down',
         'ja': '下りる',
         'de': 'hinuntergehen / aussteigen',
         'fr': 'descendre',
         'pl': 'schodzić / wysiadać'},
  'ex_vi': 'Anh muốn xuống đâu?',
  'ex_kr': {'ko': '어디에 내려 드릴까요?',
            'zh': '要在哪裡讓您下車呢？',
            'en': 'Where would you like me to drop you off?',
            'ja': 'どこで降ろしましょうか。',
            'de': 'Wo möchten Sie aussteigen?',
            'fr': 'Où souhaitez-vous descendre ?',
            'pl': 'Gdzie chciałby pan wysiąść?'}},
 {'vi': 'Qua',
  'kr': {'ko': '통과하다',
         'zh': '通過',
         'en': 'to pass through',
         'ja': '通過する',
         'de': 'überqueren / vorbeigehen',
         'fr': 'traverser / passer',
         'pl': 'przechodzić / mijać'},
  'ex_vi': 'Nó đi qua bên kia đường.',
  'ex_kr': {'ko': '그는 건너편 길가를 지나고 있다.',
            'zh': '他正經過對面的街道。',
            'en': 'He is passing along the street on the other side.',
            'ja': '彼は向かい側の道を通っている。',
            'de': 'Er geht auf der anderen Straßenseite vorbei.',
            'fr': "Il passe de l'autre côté de la rue.",
            'pl': 'On przechodzi po drugiej stronie ulicy.'}},
 {'vi': 'Về',
  'kr': {'ko': '돌아가다',
         'zh': '回去',
         'en': 'to go back / return',
         'ja': '帰る',
         'de': 'zurückkehren / nach Hause gehen',
         'fr': 'rentrer / retourner',
         'pl': 'wracać'},
  'ex_vi': 'Khi nào về nhà?',
  'ex_kr': {'ko': '언제 집에 돌아가나요?',
            'zh': '什麼時候回家呢？',
            'en': 'When are you going home?',
            'ja': 'いつ家に帰りますか。',
            'de': 'Wann gehst du nach Hause?',
            'fr': 'Quand rentres-tu à la maison ?',
            'pl': 'Kiedy wracasz do domu?'}},
 {'vi': 'Sang',
  'kr': {'ko': '건너가다',
         'zh': '過去；穿過',
         'en': 'to cross over',
         'ja': '渡る',
         'de': 'hinübergehen / herüberkommen',
         'fr': "traverser / passer de l'autre côté",
         'pl': 'przeprawiać się / przyjeżdżać'},
  'ex_vi': 'Anh sang Hàn Quốc bao lâu rồi?',
  'ex_kr': {'ko': '당신은 한국에 온 지 얼마나 됐습니까?',
            'zh': '您來韓國多久了？',
            'en': 'How long has it been since you came to Korea?',
            'ja': 'あなたは韓国に来てからどのくらいになりますか？',
            'de': 'Wie lange ist es her, dass Sie nach Korea gekommen sind?',
            'fr': 'Depuis combien de temps êtes-vous arrivé en Corée ?',
            'pl': 'Od jak dawna jest pan w Korei?'}}]

POSITION_PREPS = [{'vi': 'Trước',
  'kr': {'ko': '앞',
         'zh': '前面',
         'en': 'front',
         'ja': '前',
         'de': 'vorne / vor',
         'fr': 'devant / avant',
         'pl': 'przed / z przodu'}},
 {'vi': 'Dưới',
  'kr': {'ko': '아래',
         'zh': '下面',
         'en': 'below',
         'ja': '下',
         'de': 'unten / unter',
         'fr': 'sous / en bas',
         'pl': 'pod / na dole'}},
 {'vi': 'Sau',
  'kr': {'ko': '뒤',
         'zh': '後面',
         'en': 'back / behind',
         'ja': '後ろ',
         'de': 'hinten / hinter',
         'fr': 'derrière / après',
         'pl': 'za / z tyłu'}},
 {'vi': 'Giữa',
  'kr': {'ko': '사이',
         'zh': '之間',
         'en': 'between',
         'ja': '間',
         'de': 'zwischen',
         'fr': 'entre / au milieu',
         'pl': 'pomiędzy / w środku'}},
 {'vi': 'Bên phải',
  'kr': {'ko': '오른쪽',
         'zh': '右邊',
         'en': 'right (side)',
         'ja': '右側',
         'de': 'rechts / rechte Seite',
         'fr': 'à droite',
         'pl': 'po prawej stronie'}},
 {'vi': 'Trong',
  'kr': {'ko': '안에',
         'zh': '裡面、之內',
         'en': 'inside',
         'ja': '中に',
         'de': 'drinnen / in',
         'fr': "dans / à l'intérieur",
         'pl': 'w / wewnątrz'}},
 {'vi': 'Bên trái',
  'kr': {'ko': '왼쪽',
         'zh': '左邊',
         'en': 'left (side)',
         'ja': '左側',
         'de': 'links / linke Seite',
         'fr': 'à gauche',
         'pl': 'po lewej stronie'}},
 {'vi': 'Cạnh',
  'kr': {'ko': '옆',
         'zh': '旁邊',
         'en': 'side',
         'ja': '隣',
         'de': 'neben / an der Seite',
         'fr': 'à côté de / près de',
         'pl': 'obok / przy'}},
 {'vi': 'Trên',
  'kr': {'ko': '위',
         'zh': '上面',
         'en': 'above',
         'ja': '上',
         'de': 'oben / auf',
         'fr': 'sur / au-dessus',
         'pl': 'na / powyżej'}},
 {'vi': 'Đối diện',
  'kr': {'ko': '건너편',
         'zh': '對面',
         'en': 'the opposite side; across',
         'ja': '向かい側',
         'de': 'gegenüber',
         'fr': 'en face / vis-à-vis',
         'pl': 'naprzeciwko'}}]

POSITION_EXAMPLES = [{'vi': 'A ở (phía) trước B.',
  'kr': {'ko': 'A는 B 앞에 있다.',
         'zh': 'A在B前面。',
         'en': 'A is in front of B.',
         'ja': 'AはBの前にある。',
         'de': 'A ist vor B.',
         'fr': 'A est devant B.',
         'pl': 'A jest przed B.'}},
 {'vi': 'C ở giữa A và B.',
  'kr': {'ko': 'C는 A와 B 사이에 있다.',
         'zh': 'C在A和B之間。',
         'en': 'C is between A and B.',
         'ja': 'CはAとBの間にある。',
         'de': 'C ist zwischen A und B.',
         'fr': 'C est entre A et B.',
         'pl': 'C jest między A i B.'}},
 {'vi': 'A ở cạnh B.',
  'kr': {'ko': 'A는 B 옆에 있다.',
         'zh': 'A在B旁邊。',
         'en': 'A is next to B.',
         'ja': 'AはBの隣にある。',
         'de': 'A ist neben B.',
         'fr': 'A est à côté de B.',
         'pl': 'A jest obok B.'}},
 {'vi': 'A đối diện với B.',
  'kr': {'ko': 'B 건너편이 A이다.',
         'zh': 'B對面是A。',
         'en': 'Across from B is A.',
         'ja': 'Bの向かい側がAだ。',
         'de': 'Gegenüber von B ist A.',
         'fr': 'En face de B se trouve A.',
         'pl': 'Naprzeciwko B znajduje się A.'}}]

DIRECTION_DIALOGUES = [{'title': {'ko': '왕국회관 가는 길',
            'zh': '去王國聚會所的路',
            'en': 'The way to the Kingdom Hall',
            'ja': '王国会館への道',
            'de': 'Der Weg zum Königreichssaal',
            'fr': 'Le chemin vers la Salle du Royaume',
            'pl': 'Droga do Sali Królestwa'},
  'lines': [{'who': 'A',
             'vi': 'Xin lỗi, anh làm ơn cho tôi hỏi (Phòng Nước Trời) ở đâu ạ?',
             'kr': {'ko': '실례합니다. 왕국회관이 어디에 있는지 여쭤봐도 될까요?',
                    'zh': '不好意思，請問王國聚會所在哪裡？',
                    'en': 'Excuse me. May I ask where the Kingdom Hall is?',
                    'ja': 'すみません。王国会館はどこにあるか伺ってもいいですか。',
                    'de': 'Entschuldigung, darf ich fragen, wo der Königreichssaal ist?',
                    'fr': "Excusez-moi, s'il vous plaît, puis-je vous demander où se trouve la "
                          'Salle du Royaume ?',
                    'pl': 'Przepraszam, czy mógłby mi pan powiedzieć, gdzie znajduje się Sala '
                          'Królestwa?'}},
            {'who': 'B',
             'vi': '(Phòng Nước Trời) ở phố Du-Ryu, bên cạnh bảo tàng, đối diện trường tiểu học.',
             'kr': {'ko': '왕국회관은 두류길에 있으며, 박물관 옆이고 초등학교 건너편에 있습니다.',
                    'zh': '王國聚會所位於Duryu-gil，博物館旁邊，小學對面。',
                    'en': 'The Kingdom Hall is on Duryu-gil, next to the museum, across from the '
                          'elementary school.',
                    'ja': '王国会館はドゥリュキルにあり、博物館の隣で、小学校の向かいにあります。',
                    'de': 'Der Königreichssaal befindet sich in der Duryu-Straße, neben dem '
                          'Museum, gegenüber der Grundschule.',
                    'fr': 'La Salle du Royaume se trouve dans la rue Duryu, à côté du musée, en '
                          "face de l'école primaire.",
                    'pl': 'Sala Królestwa znajduje się na ulicy Duryu, obok muzeum, naprzeciwko '
                          'szkoły podstawowej.'}},
            {'who': 'A',
             'vi': 'Bây giờ tôi phải đi đường nào để đến đó ạ?',
             'kr': {'ko': '지금 내가 그곳에 가려면 어떤 길로 가야 합니까?',
                    'zh': '我現在要去那裡的話,該走哪條路?',
                    'en': 'If I want to go there now, which way should I go?',
                    'ja': '今私がそこに行くには、どの道を行けばいいですか?',
                    'de': 'Welchen Weg muss ich jetzt nehmen, um dorthin zu gelangen?',
                    'fr': "Quel chemin dois-je prendre maintenant pour m'y rendre ?",
                    'pl': 'Którą drogą powinienem teraz pójść, aby tam dotrzeć?'}},
            {'who': 'B',
             'vi': 'Bây giờ chúng ta đang ở trung tâm ngoại ngữ.',
             'kr': {'ko': '지금 우리는 외국어 학원에 있습니다.',
                    'zh': '我們現在在外語補習班。',
                    'en': 'We are now at a foreign language academy.',
                    'ja': '今私たちは外国語学院にいます。',
                    'de': 'Wir befinden uns jetzt im Fremdspracheninstitut.',
                    'fr': 'Nous sommes actuellement au centre de langues étrangères.',
                    'pl': 'Obecnie jesteśmy w szkole języków obcych.'}},
            {'who': 'B',
             'vi': 'Anh (đi thẳng) theo phố Cửa Đông, đến (ngã ba) thì (rẽ phải), rồi (đi thẳng) '
                   'phố trung tâm khoảng 300m.',
             'kr': {'ko': '당신은 끄어 동 길로 직진하고, 삼거리에 도착하면 오른쪽으로 쭝떰길로 약 300미터 직진하세요.',
                    'zh': '您沿著Cửa Đông路直走，到達三岔路口後，向右沿著Trung Tâm路直走約300米。',
                    'en': 'Go straight along Cửa Đông Street, and when you reach the three-way '
                          'intersection, turn right and go straight along Trung Tâm Street for '
                          'about 300 meters.',
                    'ja': 'あなたはCửa Đông通りをまっすぐ進み、三差路に着いたら右に曲がってTrung Tâm通りを約300メートルまっすぐ進んでください。',
                    'de': 'Gehen Sie geradeaus auf der Cửa Đông-Straße; wenn Sie an eine '
                          'Drei-Wege-Kreuzung kommen, biegen Sie rechts ab und gehen Sie auf der '
                          'Trung Tâm-Straße etwa 300 Meter geradeaus.',
                    'fr': 'Allez tout droit sur la rue Cửa Đông ; arrivé au carrefour en T, '
                          'tournez à droite et continuez tout droit sur la rue Trung Tâm pendant '
                          'environ 300 mètres.',
                    'pl': 'Proszę iść prosto ulicą Cửa Đông; na skrzyżowaniu trójstronnym proszę '
                          'skręcić w prawo i iść prosto ulicą Trung Tâm około 300 metrów.'}},
            {'who': 'B',
             'vi': 'Đến (ngã tư) thì (rẽ trái).',
             'kr': {'ko': '사거리에 도착하면 왼쪽으로 가세요.',
                    'zh': '到十字路口後請向左走。',
                    'en': 'When you reach the intersection, go left.',
                    'ja': '交差点に着いたら左に行ってください。',
                    'de': 'Wenn Sie an die Kreuzung kommen, biegen Sie links ab.',
                    'fr': 'Arrivé au croisement, tournez à gauche.',
                    'pl': 'Na skrzyżowaniu proszę skręcić w lewo.'}},
            {'who': 'B',
             'vi': 'Đó chính là phố Du-Ryu. (Phòng Nước Trời) sẽ ở bên phải.',
             'kr': {'ko': '그곳은 두류길입니다. 왕국회관은 오른쪽에 있습니다.',
                    'zh': '那裡是斗流路(Duryu-gil)。王國聚會所在右邊。',
                    'en': 'That place is Duryu-gil. The Kingdom Hall is on the right.',
                    'ja': 'そこは斗流(トゥリュ)通りです。王国会館は右側にあります。',
                    'de': 'Das ist die Duryu-Straße. Der Königreichssaal befindet sich auf der '
                          'rechten Seite.',
                    'fr': "C'est précisément la rue Duryu. La Salle du Royaume se trouvera sur la "
                          'droite.',
                    'pl': 'To właśnie ulica Duryu. Sala Królestwa będzie po prawej stronie.'}},
            {'who': 'A',
             'vi': 'Cám ơn anh.',
             'kr': {'ko': '감사합니다.',
                    'zh': '謝謝。',
                    'en': 'Thank you.',
                    'ja': 'ありがとうございます。',
                    'de': 'Vielen Dank!',
                    'fr': 'Merci beaucoup !',
                    'pl': 'Dziękuję bardzo!'}}]},
 {'title': {'ko': '식당 가는 길',
            'zh': '去餐廳的路',
            'en': 'The way to the restaurant',
            'ja': 'レストランへの道',
            'de': 'Der Weg zum Restaurant',
            'fr': 'Le chemin vers le restaurant',
            'pl': 'Droga do restauracji'},
  'lines': [{'who': 'A',
             'vi': 'Xin lỗi, nhà hàng KOREANA ở đâu ạ?',
             'kr': {'ko': '실례합니다. 코리아나 식당이 어디 있습니까?',
                    'zh': '不好意思，請問Koreana餐廳在哪裡？',
                    'en': 'Excuse me. Where is the Koreana restaurant?',
                    'ja': 'すみません。コリアナ食堂はどこにありますか。',
                    'de': 'Entschuldigung, wo ist das Restaurant KOREANA?',
                    'fr': 'Excusez-moi, où se trouve le restaurant KOREANA ?',
                    'pl': 'Przepraszam, gdzie znajduje się restauracja KOREANA?'}},
            {'who': 'B',
             'vi': 'Anh đi thẳng qua (hai ngã tư) đến (một ngã ba) (rẽ phải).',
             'kr': {'ko': '당신은 직진해서 두 군데의 사거리를 지나 삼거리에 도착하면 오른쪽으로 가세요.',
                    'zh': '您直走經過兩個十字路口，到達三岔路口後向右轉。',
                    'en': 'Go straight, pass through two intersections, and when you reach the '
                          'three-way junction, turn right.',
                    'ja': 'あなたはまっすぐ進んで二つの十字路を通り過ぎ、三差路に着いたら右に曲がってください。',
                    'de': 'Gehen Sie geradeaus über zwei Kreuzungen hinweg; wenn Sie an eine '
                          'Drei-Wege-Kreuzung kommen, biegen Sie rechts ab.',
                    'fr': 'Allez tout droit en traversant deux carrefours ; arrivé à une '
                          'intersection en T, tournez à droite.',
                    'pl': 'Proszę iść prosto przez dwa skrzyżowania; na skrzyżowaniu w kształcie '
                          'litery T proszę skręcić w prawo.'}},
            {'who': 'B',
             'vi': 'Sau đó (đi thẳng) (khoảng 200 mét). Đến (ngã tư) thì (rẽ trái).',
             'kr': {'ko': '그 후에 약 200미터 직진하세요. 사거리에 도착하면 왼쪽으로 가세요.',
                    'zh': '之後請直走大約200米。到達十字路口後請往左轉。',
                    'en': 'After that, go straight for about 200 meters. When you reach the '
                          'intersection, turn left.',
                    'ja': 'その後、約200メートル直進してください。交差点に着いたら左に曲がってください。',
                    'de': 'Gehen Sie danach etwa 200 Meter geradeaus. An der Kreuzung biegen Sie '
                          'links ab.',
                    'fr': 'Après cela, continuez tout droit sur environ 200 mètres. Au carrefour, '
                          'tournez à gauche.',
                    'pl': 'Następnie proszę iść prosto około 200 metrów. Na skrzyżowaniu proszę '
                          'skręcić w lewo.'}},
            {'who': 'B',
             'vi': 'Nhà hàng KOREANA ở (bên phải).',
             'kr': {'ko': '코리아나 식당은 오른쪽에 있습니다.',
                    'zh': '高麗亞娜餐廳在右邊。',
                    'en': 'Koreana Restaurant is on the right.',
                    'ja': 'コリアナ食堂は右側にあります。',
                    'de': 'Das Restaurant KOREANA befindet sich auf der rechten Seite.',
                    'fr': 'Le restaurant KOREANA se trouve sur la droite.',
                    'pl': 'Restauracja KOREANA znajduje się po prawej stronie.'}},
            {'who': 'A',
             'vi': 'Từ đây đến nhà hàng có xa không?',
             'kr': {'ko': '여기서부터 식당까지는 멉니까?',
                    'zh': '從這裡到餐廳遠嗎？',
                    'en': 'Is it far from here to the restaurant?',
                    'ja': 'ここからレストランまで遠いですか。',
                    'de': 'Ist es von hier bis zum Restaurant weit?',
                    'fr': "Est-ce loin d'ici jusqu'au restaurant ?",
                    'pl': 'Czy stąd do restauracji jest daleko?'}},
            {'who': 'B',
             'vi': 'Không xa lắm. Khoảng 1 kilômét.',
             'kr': {'ko': '멀지 않습니다. 약 1킬로미터입니다.',
                    'zh': '不遠。大約1公里。',
                    'en': "It's not far. It's about 1 kilometer.",
                    'ja': '遠くありません。約1キロメートルです。',
                    'de': 'Nicht sehr weit. Ungefähr 1 Kilometer.',
                    'fr': "Ce n'est pas très loin. Environ 1 kilomètre.",
                    'pl': 'Niedaleko. Około 1 kilometra.'}},
            {'who': 'A',
             'vi': 'Cám ơn nhiều.',
             'kr': {'ko': '대단히 고맙습니다.',
                    'zh': '非常感謝。',
                    'en': 'Thank you very much.',
                    'ja': '大変ありがとうございます。',
                    'de': 'Vielen herzlichen Dank!',
                    'fr': 'Merci infiniment !',
                    'pl': 'Bardzo dziękuję!'}}]}]
