# LPD_LESSONS -- curated short representative example sentences (5-8 per lesson) from
# the JW.org brochure 'Love People—Make Disciples' (lessons 1-12 + appendices A-C),
# in vi/ko/zh/en/ja. This is a small illustrative selection, not a full-text transcription.
LPD_LESSONS = [{'kind': 'lesson',
  'lines': [{'en': 'We are more likely to have a good conversation if we start with a topic that interests the other '
                   'person.',
             'ja': '相手が興味を持っている話題で話し始めた方が、会話が弾みます。',
             'ko': '상대방이 관심을 가질 만한 점에 대해 이야기하면 대화가 잘 이어질 가능성이 높습니다.',
             'vi': 'Nếu chúng ta bắt chuyện bằng đề tài mà người ta quan tâm thì sẽ dễ hơn để có cuộc trò chuyện ý '
                   'nghĩa.',
             'zh': '如果我們先聊聊對方感興趣的話題，就比較容易聊下去。'},
            {'en': 'Do not insist on starting a conversation on a topic you had in mind.',
             'ja': '自分が話したい話題で無理に会話を始めようとしないでください。',
             'ko': '자신이 생각해 둔 주제로만 대화하려고 하지 마십시오.',
             'vi': 'Đừng khăng khăng bắt chuyện bằng đề tài mà anh chị muốn nói.',
             'zh': '不要總是用你準備好的話題開始交談。'},
            {'en': 'What is the person currently doing? What might he be thinking about?',
             'ja': 'この人は今何をしているところだろう。どんなことを考えているだろう。',
             'ko': '상대방은 지금 무엇을 하고 있지? 어떤 생각을 하고 있을까?',
             'vi': 'Người đó đang làm gì? Có thể người đó đang nghĩ đến điều gì?',
             'zh': '對方正在做什麼？他可能在想什麼？'},
            {'en': 'Is this a good time to talk to the person?',
             'ja': '今話しても大丈夫だろうか。別の時の方がいいだろうか。',
             'ko': '지금은 그와 대화를 나누기에 좋은 때일까?',
             'vi': 'Đây có phải là lúc thuận tiện để nói chuyện với người đó không?',
             'zh': '現在跟他說話恰當嗎？'},
            {'en': "Don't talk too much.",
             'ja': '自分ばかり話さないようにしましょう。',
             'ko': '말을 너무 많이 하지 마십시오.',
             'vi': 'Đừng nói quá nhiều.',
             'zh': '不要說個不停。'},
            {'en': 'Encourage the other person to express himself. When appropriate, ask questions.',
             'ja': '上手に質問して、相手にも話してもらうようにします。',
             'ko': '상대방이 자기 생각을 편하게 이야기할 수 있게 해 주십시오. 적절한 경우에는 질문을 하십시오.',
             'vi': 'Khuyến khích người đó nêu quan điểm. Đặt câu hỏi khi thích hợp.',
             'zh': '請對方說說自己的看法。在適當的時候提出問題。'}],
  'num': 1,
  'title': {'en': 'Interest in Others', 'ja': '相手のことを考えて', 'ko': '사람들에 대한 관심', 'vi': 'Quan tâm', 'zh': '關心'}},
 {'kind': 'lesson',
  'lines': [{'en': 'If we allow a conversation to develop naturally, it is more likely that the other person will '
                   'feel at ease and be open to discussing our message.',
             'ja': '自然な流れで会話できれば，相手も身構えずに会話に応じ，聖書からのメッセージを聞いてみようという気持ちになるかもしれません。',
             'ko': '대화가 자연스럽게 흘러가면, 상대방이 편한 마음으로 우리의 소식에 귀를 기울일 가능성이 높습니다.',
             'vi': 'Nếu chúng ta để cuộc trò chuyện diễn ra tự nhiên thì người nghe sẽ dễ cảm thấy thoải mái và sẵn '
                   'sàng nghe thông điệp của mình hơn.',
             'zh': '如果我們自然地交談，對方就會比較自在，更願意聽我們傳講的信息。'},
            {'en': "A person's facial expressions and body language can reveal a lot.",
             'ja': '相手の表情や態度などからいろいろなことが分かるものです。',
             'ko': '상대방의 표정과 몸짓을 보면 많은 것을 알 수 있습니다.',
             'vi': 'Nét mặt, cử chỉ và điệu bộ của một người cho chúng ta biết nhiều về người đó.',
             'zh': '一個人的表情、姿勢、動作能透露出他的想法。'},
            {'en': 'You might introduce a Bible truth by simply asking, "Did you know that . . . ?"',
             'ja': '会話できる人なら，「こんなことをお聞きになったことがありますか」といった質問をして聖書の話題を持ち出せるかもしれません。',
             'ko': "그렇다면 성경 진리를 전하기 위해 '혹시 ··· 을 알고 계셨나요?' 하고 간단히 질문할 수 있습니다.",
             'vi': 'Anh chị có thể bắt đầu nói về một đề tài Kinh Thánh bằng cách đơn giản hỏi: "Ông/Bà có biết…?".',
             'zh': '也許你可以簡單地說「你知道嗎……」，然後提到聖經裡的一個觀點。'},
            {'en': 'Avoid forcing a conversation with someone who does not want to talk.',
             'ja': '話したくないと思っている人と無理に会話しようとする必要はありません。',
             'ko': '이야기를 하고 싶어 하지 않는 사람에게 대화를 강요하지 마십시오.',
             'vi': 'Nếu người ta không muốn nói chuyện thì chúng ta đừng ép họ.',
             'zh': '看看對方是否願意跟你聊，不願意的話就別勉強。'},
            {'en': 'Sometimes, this may mean waiting until the next conversation you have with the person.',
             'ja': '場合によっては，次にその人と話せる時まで待った方がよいかもしれません。',
             'ko': '어떤 경우에는 다음에 만날 때까지 기다려야 할 수도 있습니다.',
             'vi': 'Có khi chúng ta phải chờ đến lần trò chuyện kế tiếp mới có thể làm thế.',
             'zh': '有時，等到下次再說會更好。'},
            {'en': 'A conversation may go in an unexpected direction.',
             'ja': '相手が予想外のことを言うこともあるでしょう。',
             'ko': '대화가 예상하지 못한 방향으로 흘러갈 수 있습니다.',
             'vi': 'Một cuộc trò chuyện có thể bất ngờ chuyển hướng.',
             'zh': '有時談話會朝著你意想不到的方向發展。'},
            {'en': 'So be willing to share something that is relevant to the person, even if that means discussing a '
                   'different Bible truth than the one you had in mind.',
             'ja': 'そういうときには，自分が話そうと思っていたことと違うとしても，その人に合ったことを聖書から話すようにしましょう。',
             'ko': '그럴 경우, 원래 전해 주려고 생각했던 성경 진리와는 다르더라도 상대방에게 의미가 있는 점을 알려 주십시오.',
             'vi': 'Vì thế, hãy sẵn sàng chia sẻ một đề tài Kinh Thánh phù hợp với nhu cầu của người nghe, cho dù đó '
                   'không phải là đề tài mình định nói.',
             'zh': '要是你發現對方更關心別的事，就算跟你設想的不一樣，也要樂意調整話題，分享聖經在這方面是怎麼說的。'}],
  'num': 2,
  'title': {'en': 'Naturalness', 'ja': '自然に', 'ko': '자연스러움', 'vi': 'Tự nhiên', 'zh': '自然'}},
 {'kind': 'lesson',
  'lines': [{'en': 'A person will be more likely to listen to our message if he senses that we care about him.',
             'ja': '相手を心から気遣っていることが伝われば、その人は話を聞いてみようという気持ちになるかもしれません。',
             'ko': '상대방은 우리가 그에게 진실한 관심이 있다고 느끼면 우리가 전하는 소식에 귀 기울일 가능성이 높습니다.',
             'vi': 'Một người dễ lắng nghe thông điệp của chúng ta hơn nếu thấy chúng ta quan tâm đến họ.',
             'zh': '如果一個人感受到我們的關心，就可能會更願意聽好消息。'},
            {'en': 'Try to imagine how he feels.',
             'ja': 'その人の身になって考えましょう。',
             'ko': '그가 어떤 생각을 하고 있을지 상상해 보십시오.',
             'vi': 'Cố gắng hình dung người đó cảm thấy thế nào.',
             'zh': '想像一下，如果你是對方，你會有什麼感覺。'},
            {'en': 'Doing so will help you to show kindness in a natural and sincere manner.',
             'ja': 'そうすれば、相手に心から親切にできるでしょう。',
             'ko': '이런 점에 대해 생각해 보면 자연스럽고 진실한 태도로 친절을 나타낼 수 있을 것입니다.',
             'vi': 'Làm thế sẽ giúp anh chị thể hiện lòng nhân từ một cách tự nhiên và chân thành.',
             'zh': '你這樣思考一下，就會仁慈地對待他，也會更真誠自然。'},
            {'en': 'Show that you care about what matters to a person by listening.',
             'ja': '相手の話をよく聞いて、気に掛けていることが伝わるようにしましょう。',
             'ko': '귀 기울여 잘 들음으로 그가 중요하게 생각하는 문제에 진실한 관심이 있다는 것을 나타내십시오.',
             'vi': 'Hãy cho thấy anh chị chú ý đến điều mà một người quan tâm bằng cách lắng nghe.',
             'zh': '要認真聽對方說話，這樣他就能感受到你的關心。'},
            {'en': 'If he tells you how he feels about something or mentions a problem he is facing, do not change '
                   'the subject.',
             'ja': '相手が自分の考えや気持ち、いま大変なことなどについて話してくれたら、話題を変えようとせず、誠実に耳を傾けてください。',
             'ko': '그가 자신의 감정이나 자신이 겪고 있는 문제에 대해 이야기하면, 화제를 돌리지 마십시오.',
             'vi': 'Nếu người ấy cho biết cảm nghĩ về điều nào đó hoặc nói đến vấn đề đang gặp phải, đừng chuyển đề '
                   'tài.',
             'zh': '如果他說出自己的感受或難處，不要岔開話題。'},
            {'en': 'When you feel compassion for the person and truly want to help him, it will come through in the '
                   'way you speak.',
             'ja': '相手を思いやって助けになりたいと思っていることは、話し方に表れるものです。',
             'ko': '우리가 상대방을 염려하고 진정으로 돕고 싶은 마음이 있으면, 우리가 말하는 방식에 그 점이 드러날 것입니다.',
             'vi': 'Khi anh chị quan tâm và thật sự muốn giúp đỡ, người nghe sẽ cảm nhận được điều đó qua cách anh '
                   'chị nói.',
             'zh': '對方能從你說的話感受到你是不是理解他，是不是真的想幫助他。'},
            {'en': 'Acts of kindness can open the door to a conversation.',
             'ja': '親切にしたことがきっかけで会話が始まるかもしれません。',
             'ko': '친절한 행동이 좋은 대화로 이어질 수 있습니다.',
             'vi': 'Hành động nhân từ có thể mở đường cho cuộc trò chuyện.',
             'zh': '你仁慈待人，對方也許會更願意跟你交談。'}],
  'num': 3,
  'title': {'en': 'Kindness', 'ja': '親切に', 'ko': '친절', 'vi': 'Nhân từ', 'zh': '仁慈'}},
 {'kind': 'lesson',
  'lines': [{'en': 'Avoid giving the impression that you know everything and that the other person knows nothing.',
             'ja': '自分は何でも知っていて相手は無知だと言っているかのような印象を与えないようにしましょう。',
             'ko': '우리가 상대방보다 훨씬 더 많이 알고 있다는 인상을 주지 마십시오.',
             'vi': 'Tránh làm như thể mình biết mọi điều, còn người kia chẳng biết gì cả.',
             'zh': '避免讓對方覺得自己無所不知而對方一無所知，防止給人高高在上的感覺。'},
            {'en': "God's Word contains thoughts that touch people's hearts.",
             'ja': '神の言葉である聖書には、人の心を動かす力があります。',
             'ko': '하느님의 말씀에 들어 있는 진리는 사람들의 마음을 감동시킵니다.',
             'vi': 'Ý tưởng trong Lời Đức Chúa Trời có thể động đến lòng người ta.',
             'zh': '上帝的話語能深深打動人的心。'},
            {'en': 'We do not want to argue.',
             'ja': '相手を言い負かそうとしないでください。',
             'ko': '우리는 논쟁을 벌이기를 원하지 않습니다.',
             'vi': 'Chúng ta không muốn tranh cãi.',
             'zh': '不要強迫對方認同觀點，避免爭辯。'},
            {'en': 'Remain mild.',
             'ja': 'いつも穏やかでいる。',
             'ko': '온화한 태도를 나타내십시오.',
             'vi': 'Tỏ ra mềm mại.',
             'zh': '保持溫和。'},
            {'en': 'Our message is more appealing when we present it humbly and respectfully.',
             'ja': '謙遜に敬意を込めて話せば、聞く人は聖書のメッセージを受け入れやすくなります。',
             'ko': '우리가 전하는 소식은 겸손하고 존중심 있는 태도로 말할 때 더 호소력이 있습니다.',
             'vi': 'Thông điệp của chúng ta sẽ thu hút hơn nếu chúng ta trình bày một cách khiêm nhường và tôn '
                   'trọng.',
             'zh': '傳道時保持謙卑、尊重對方，別人就會更願意聽。'},
            {'en': 'How did Paul show humility in the way he spoke to King Agrippa?',
             'ja': 'パウロが謙遜だったことは、アグリッパ王への接し方のどんなところに表れていますか。',
             'ko': '바울은 아그리파왕에게 이야기할 때 어떻게 겸손을 나타냈습니까?',
             'vi': 'Phao-lô thể hiện sự khiêm nhường như thế nào qua cách nói chuyện với vua A-ríp-ba?',
             'zh': '為什麼說保羅對亞基帕王說話時態度很謙卑？'}],
  'num': 4,
  'title': {'en': 'Humility', 'ja': '謙遜に', 'ko': '겸손', 'vi': 'Khiêm nhường', 'zh': '謙卑'}},
 {'kind': 'lesson',
  'lines': [{'en': 'People are more likely to listen to us if we carefully choose what we say as well as how and '
                   'when we say it.',
             'ja': '何を、どのように、どんなタイミングで言うかをよく考えるなら、相手は話を聞こうという気持ちになるかもしれません。',
             'ko': '우리가 무슨 말을 언제 어떻게 할지 주의 깊이 생각한 다음 말한다면 사람들이 우리의 말에 귀 기울일 가능성이 높습니다.',
             'vi': 'Người khác sẽ dễ lắng nghe hơn nếu chúng ta cẩn thận lựa chọn lời nói, cách nói và thời điểm '
                   'nói.',
             'zh': '我們仔細想想該說什麼、怎麼說、什麼時候說，別人可能會更願意聽我們傳講的信息。'},
            {'en': 'For example, when speaking with someone from a non-Christian background, you may need to adjust '
                   'the way you introduce the Bible or how you refer to Jesus.',
             'ja': 'クリスチャンではない人と話すときには、「聖書」や「イエス」といった言葉を初めから使うのではなく、伝え方を工夫するとよい場合もあります。',
             'ko': '예를 들어, 기독교를 믿지 않는 사람과 이야기할 경우 성경이나 예수라는 말 대신 다른 표현을 사용할 수 있습니다.',
             'vi': 'Chẳng hạn, khi nói với người không theo Ki-tô giáo, có lẽ anh chị cần điều chỉnh cách giới thiệu '
                   'Kinh Thánh hoặc cách nói về Chúa Giê-su.',
             'zh': '比如，你跟一個沒有基督教背景的人傳道，在提到聖經或耶穌時，可能要換個讓他更容易接受的說法。'},
            {'en': 'Allow him to express himself freely.',
             'ja': '相手が自分の思っていることを何でも言えるようにしてください。',
             'ko': '그가 자신의 생각을 자유롭게 이야기할 수 있게 하십시오.',
             'vi': 'Hãy để người đó thoải mái bày tỏ quan điểm.',
             'zh': '讓他暢所欲言。'},
            {'en': 'If he says something that conflicts with Bible teachings, resist any urge to argue.',
             'ja': '聖書の教えと違うことを言ったとしても、すぐに反論しないようにします。',
             'ko': '성경의 가르침과 맞지 않는 말을 하더라도 즉시 반박하지 마십시오.',
             'vi': 'Nếu người đó nói một điều trái với Kinh Thánh, đừng vội phản đối.',
             'zh': '如果他提到一些違背聖經的觀點，不要馬上反駁他。'},
            {'en': 'By listening to him, you gain insight into his viewpoint.',
             'ja': 'よく話を聞けば、相手の見方や考え方を知ることができます。',
             'ko': '그의 말에 귀 기울이면 그가 어떤 생각을 갖고 있는지 잘 알게 될 것입니다.',
             'vi': 'Nhờ lắng nghe, anh chị sẽ hiểu rõ hơn về quan điểm của người đó.',
             'zh': '你繼續聽他說，就能進一步了解他的想法。'},
            {'en': 'He may sincerely believe that his religious beliefs are correct.',
             'ja': '自分の宗教の教えを誠実に信じている人もいます。',
             'ko': '그는 자신의 신앙이 옳다고 진심으로 믿고 있을 수 있습니다.',
             'vi': 'Người đó có thể thật lòng tin rằng tín ngưỡng của mình là đúng.',
             'zh': '對方可能堅信自己的宗教信仰是對的。'},
            {'en': 'Build common ground first, and then progressively help him understand what the Bible teaches.',
             'ja': 'まずはお互いの考えの共通点を探し、それから少しずつ聖書の教えを知ってもらうようにしましょう。',
             'ko': '먼저 서로 공감하는 점을 기초로 대화를 이어 나가십시오. 그런 다음 그가 점진적으로 성경의 가르침을 이해할 수 있도록 도와주십시오.',
             'vi': 'Trước hết hãy tạo điểm chung, rồi từng bước giúp người đó hiểu điều Kinh Thánh dạy.',
             'zh': '先講一些雙方都認同的觀點，然後再一步步地幫助他明白聖經是怎麼說的。'}],
  'num': 5,
  'title': {'en': 'Tact', 'ja': '機転を利かせて', 'ko': '존중심', 'vi': 'Tế nhị', 'zh': '尊重'}},
 {'kind': 'lesson',
  'lines': [{'en': 'We need boldness to preach the Kingdom message impartially.',
             'ja': 'どんな人にも、ためらうことなく王国の良い知らせを伝えることが大切です。',
             'ko': '모든 사람에게 편견 없이 왕국 소식을 전파하려면 담대함이 필요합니다.',
             'vi': 'Chúng ta cần sự dạn dĩ để rao giảng thông điệp Nước Trời một cách không thiên vị.',
             'zh': '我們要有勇氣，才能向各種各樣的人傳講王國的信息。'},
            {'en': "God's spirit empowered Jesus to preach, and it can empower you too.",
             'ja': 'イエスがためらわずに伝道できたのは、聖なる力の助けがあったからです。',
             'ko': '하느님의 영은 예수에게 전파하는 데 필요한 힘을 주었습니다. 그 영은 우리에게도 그런 힘을 줄 수 있습니다.',
             'vi': 'Thần khí Đức Chúa Trời đã thêm sức cho Chúa Giê-su để rao giảng, và cũng có thể thêm sức cho '
                   'chúng ta.',
             'zh': '上帝的神聖力量讓耶穌勇敢地傳道，這股力量也能讓你鼓起勇氣。'},
            {'en': 'Ask Jehovah for boldness to preach to those you might find intimidating.',
             'ja': '少し怖いと感じても勇気を出して話せるよう、エホバに祈ってください。',
             'ko': '말을 건네기가 두렵게 느껴지는 사람들에게도 담대하게 전파할 수 있도록 도와 달라고 여호와께 기도하십시오.',
             'vi': 'Hãy cầu xin Đức Giê-hô-va ban sự dạn dĩ để anh chị rao giảng cho những người mà mình cảm thấy sợ '
                   'tiếp cận.',
             'zh': '要是你不敢向某些人傳道，就要懇求耶和華賜給你勇氣。'},
            {'en': 'We may hesitate to approach some people because of their physical appearance, social or economic '
                   'status, lifestyle, or religious beliefs.',
             'ja': '相手の外見、肩書き、生活レベル、ライフスタイル、宗教などが理由で、話すのをためらってしまうことがあるかもしれません。',
             'ko': '상대방의 외모, 사회적·경제적 지위, 생활 방식, 종교적 배경 때문에 다가가기가 꺼려질 수 있습니다.',
             'vi': 'Chúng ta có thể ngần ngại tiếp cận với một số người vì vẻ bề ngoài, địa vị xã hội, tình trạng '
                   'kinh tế, lối sống hoặc tín ngưỡng của họ.',
             'zh': '我們可能因為對方的外表、社會地位、經濟狀況、生活方式或宗教信仰而猶豫。'},
            {'en': 'Jehovah and Jesus can read hearts; we cannot.',
             'ja': '私たちはエホバやイエスと違って、人の心の中は分かりません。',
             'ko': '여호와와 예수께서는 사람들의 마음을 읽으실 수 있지만 우리에게는 그런 능력이 없습니다.',
             'vi': 'Đức Giê-hô-va và Chúa Giê-su đọc được lòng, còn chúng ta thì không.',
             'zh': '我們不能像耶和華和耶穌那樣看透人心。'},
            {'en': "No one is beyond the reach of Jehovah's mercy.",
             'ja': 'エホバはあらゆる人を助けたいと思っています。',
             'ko': '누구든 여호와의 자비를 받을 수 있습니다.',
             'vi': 'Mọi người đều có cơ hội nhận được sự thương xót của Đức Giê-hô-va.',
             'zh': '耶和華有能力幫助任何人作出改變。'},
            {'en': 'Avoid arguing.',
             'ja': '口論にならないようにします。',
             'ko': '논쟁을 피하십시오.',
             'vi': 'Tránh tranh cãi.',
             'zh': '不要爭辯。'},
            {'en': 'Politely end the conversation if the person is unreceptive to the good news or if you feel '
                   'unsafe.',
             'ja': '相手に良い知らせを聞く気がなかったり、身の危険を感じたりするときには、会話を切り上げましょう。',
             'ko': '상대방이 좋은 소식을 듣고 싶어 하지 않거나, 계속 이야기하는 것이 안전하지 않다고 느껴진다면 정중하게 대화를 끝내십시오.',
             'vi': 'Hãy lịch sự kết thúc cuộc trò chuyện nếu người mình gặp không muốn nghe tin mừng hoặc nếu anh '
                   'chị cảm thấy không an toàn.',
             'zh': '要是對方真的不想聽，或你覺得有危險，就要禮貌地結束談話，然後離開。'}],
  'num': 6,
  'title': {'en': 'Boldness', 'ja': 'ためらわずに', 'ko': '담대함', 'vi': 'Dạn dĩ', 'zh': '勇氣'}},
 {'kind': 'lesson',
  'lines': [{'en': 'We need to invest time and effort to make effective return visits and to start Bible studies.',
             'ja': '次につながる再訪問をし、聖書レッスンを始めるためには、時間や労力を惜しまないことが大切です。',
             'ko': '효과적인 재방문을 하고 성서 연구를 시작하려면 시간과 노력을 들여야 합니다.',
             'vi': 'Chúng ta cần bỏ thời gian và công sức để thăm lại một cách hữu hiệu và bắt đầu các cuộc học hỏi.',
             'zh': '我們需要付出時間和精力，才能讓續訪有成效，開始一個聖經課程。'},
            {'en': "Adapt your schedule to the other person's.",
             'ja': '相手の予定に合わせる。',
             'ko': '상대방에게 편리한 시간에 맞추십시오.',
             'vi': 'Sẵn sàng thăm người chú ý vào lúc thuận tiện cho họ.',
             'zh': '配合對方的時間。'},
            {'en': 'When would I be most likely to contact him?',
             'ja': 'どの曜日や時間帯なら会えるだろうか。',
             'ko': '그를 만날 가능성이 가장 높은 때는 언제인가?',
             'vi': 'Khi nào là thời điểm tốt nhất để gặp họ?',
             'zh': '什麼時候最容易見到他？'},
            {'en': 'Be willing to follow up, even if the time is inconvenient for you.',
             'ja': 'それが自分にとってあまり都合が良くない時間だとしても、できるだけ相手に合わせましょう。',
             'ko': '자신에게 편리한 시간이 아니더라도 기꺼이 상대방의 상황에 맞추십시오.',
             'vi': 'Hãy sẵn sàng thăm lại, ngay cả vào lúc bất tiện cho mình.',
             'zh': '即使對你來說不方便，也要儘量配合對方的時間。'},
            {'en': 'Make an appointment.',
             'ja': '次回の約束をする。',
             'ko': '다시 대화를 나눌 약속을 하십시오.',
             'vi': 'Hẹn trước.',
             'zh': '約定時間。'},
            {'en': 'Remain hopeful.',
             'ja': '簡単に諦めない。',
             'ko': '긍정적인 생각을 가지십시오.',
             'vi': 'Đừng mất hy vọng.',
             'zh': '保持積極。'},
            {'en': 'Do not quickly assume that a person who is rarely at home or is often busy is not interested.',
             'ja': '相手がほとんど家にいない、あるいは忙しくてなかなか話せないからといって、関心がないのだろうとすぐに決め付けないでください。',
             'ko': '상대방이 집에 거의 없거나 항상 바쁘다고 해서 그가 관심이 없다고 속단하지 마십시오.',
             'vi': 'Không nên vội cho rằng người hiếm khi ở nhà hoặc thường bận rộn là người không chú ý.',
             'zh': '就算對方常常不在家或很忙，也不要認為他一定沒興趣。'}],
  'num': 7,
  'title': {'en': 'Perseverance', 'ja': '粘り強く', 'ko': '끈기', 'vi': 'Kiên trì', 'zh': '堅持不懈'}},
 {'kind': 'lesson',
  'lines': [{'en': 'How did Jesus’ brothers initially respond to his message?',
             'ja': 'イエスの弟たちは最初のうち、イエスの教えにどう反応しましたか。',
             'ko': '예수의 동생들은 그분이 전하신 소식에 처음에 어떤 반응을 보였습니까?',
             'vi': 'Lúc đầu, các em trai của Chúa Giê-su phản ứng thế nào trước thông điệp của ngài?',
             'zh': '耶穌的弟弟們一開始對耶穌傳講的信息有什麼反應？'},
            {'en': 'What shows that Jesus did not give up on his brother James?',
             'ja': 'イエスが弟ヤコブのことを諦めなかったとどうして分かりますか。',
             'ko': '무엇을 보면 예수께서 동생 야고보를 포기하지 않으셨다는 것을 알 수 있습니까?',
             'vi': 'Điều gì cho thấy Chúa Giê-su đã không bỏ cuộc trong việc giúp em mình là Gia-cơ?',
             'zh': '我們怎麼知道耶穌沒有放棄弟弟雅各？'},
            {'en': 'We need to be patient because some people take longer than others to respond to the good news.',
             'ja': '良い知らせを聞いて受け入れるまでに時間がかかる人もいるので、辛抱強さが必要です。',
             'ko': '어떤 사람들은 좋은 소식을 받아들이는 데 시간이 오래 걸리기 때문에 우리는 참을성을 보여야 합니다.',
             'vi': 'Chúng ta cần kiên nhẫn vì một số người cần nhiều thời gian hơn người khác để hưởng ứng tin mừng.',
             'zh': '每個人對好消息的反應都不一樣，有些人需要多一點時間，所以我們要有耐心。'},
            {'en': 'If the person does not immediately agree to a Bible study, do not pressure him.',
             'ja': '相手に今のところ聖書を学ぶ気がない場合、プレッシャーをかけないようにしましょう。',
             'ko': '성서 연구를 제의했을 때 즉시 받아들이지 않더라도 강요하지 마십시오.',
             'vi': 'Nếu một người không đồng ý tìm hiểu Kinh Thánh ngay, đừng ép người đó.',
             'zh': '如果對方沒有馬上答應學習聖經，不要勉強他。'},
            {'en': 'Each person is unique.',
             'ja': '人によって考え方や感じ方が違います。',
             'ko': '사람마다 상황이나 성향이 다릅니다.',
             'vi': 'Mỗi người mỗi khác.',
             'zh': '每個人都不一樣。'},
            {'en': 'Does he face pressure from relatives or neighbors?',
             'ja': '親族や近所の人の目が気になっているのでしょうか。',
             'ko': '친족이나 이웃에게 압력을 받고 있습니까?',
             'vi': 'Họ có bị người thân hay hàng xóm gây áp lực không?',
             'zh': '他很在意親戚或鄰居的看法嗎？'},
            {'en': 'Ask Jehovah to help you remain positive and tactful.',
             'ja': '前向きな見方を保って上手に相手の心を動かせるよう、エホバに助けを求めて祈りましょう。',
             'ko': '긍정적인 생각을 유지하고 그를 지혜롭게 도울 수 있게 해 달라고 여호와께 청하십시오.',
             'vi': 'Hãy cầu xin Đức Giê-hô-va giúp anh chị giữ thái độ tích cực và tế nhị.',
             'zh': '求耶和華讓我們積極地看待續訪對象，用合適的方法幫助他。'}],
  'num': 8,
  'title': {'en': 'Patience', 'ja': '辛抱強く', 'ko': '참을성', 'vi': 'Kiên nhẫn', 'zh': '耐心'}},
 {'kind': 'lesson',
  'lines': [{'en': 'Why were Jesus and his apostles hoping "to be by themselves"?',
             'ja': 'イエスと使徒たちが「自分たちだけに」なりたいと思ったのはどうしてですか。',
             'ko': '예수와 사도들은 왜 "따로 있으려고" 했습니까?',
             'vi': 'Tại sao Chúa Giê-su và các sứ đồ muốn được "đi riêng đến nơi hẻo lánh"?',
             'zh': '為什麼耶穌和使徒們「離開人群」？'},
            {'en': 'What motivated Jesus to teach the crowd?',
             'ja': 'イエスが集まった人たちを教えることにしたのは，どんな気持ちからですか。',
             'ko': '예수께서는 왜 무리를 가르치셨습니까?',
             'vi': 'Điều gì thôi thúc Chúa Giê-su dạy đoàn dân?',
             'zh': '為什麼耶穌後來又開始教導他們？'},
            {'en': 'Empathy moves us to care about people, not just about our message.',
             'ja': '伝えたい内容について考えるだけでなく，親身になって相手のことを考えるのも大切です。',
             'ko': '감정 이입을 한다면 단지 좋은 소식을 전하려고만 하는 것이 아니라 사람들을 도우려는 마음이 들 것입니다.',
             'vi': 'Sự đồng cảm thúc đẩy chúng ta quan tâm đến người khác, chứ không chỉ tập trung vào thông điệp '
                   'của mình.',
             'zh': '我們將心比心就會關心對方，不會只想著怎麼傳道。'},
            {'en': 'Allow the person to express himself.',
             'ja': '思ったことや感じたことを自由に言える雰囲気をつくりましょう。',
             'ko': '상대방이 자신의 생각을 표현할 수 있게 하십시오.',
             'vi': 'Hãy để người chú ý bày tỏ quan điểm.',
             'zh': '讓他暢所欲言。'},
            {'en': 'Do not interrupt him or quickly dismiss his feelings, concerns, or objections.',
             'ja': '相手が自分の気持ちや気掛かりなことを話してくれたり，反対意見を言ったりするとき，遮ったり軽く受け流したりしないでください。',
             'ko': '그의 말을 끊지 마십시오. 그가 자신의 감정을 표현하거나 걱정거리를 이야기하거나 이의를 제기할 때 별것 아니라는 듯이 무시하지 마십시오.',
             'vi': 'Đừng ngắt lời hoặc lờ đi cảm xúc, mối quan tâm hay lời phản đối của họ.',
             'zh': '不要打斷他，也不要忽視他的感受、憂慮和觀點。'},
            {'en': 'Why does he need to hear the truth?',
             'ja': 'この人にとって真理が必要なのはどうしてだろう。',
             'ko': '그 사람은 왜 진리의 소식을 들을 필요가 있는가?',
             'vi': 'Tại sao người đó cần nghe chân lý?',
             'zh': '為什麼他需要聽到好消息？'},
            {'en': 'How would studying the Bible make his daily life and his future better?',
             'ja': '聖書を学ぶことで，この人は今も将来もどんなふうに幸せになれるだろう。',
             'ko': '성서 연구를 하면 그의 현재의 삶과 앞으로의 삶이 어떻게 더 나아질 것인가?',
             'vi': 'Việc tìm hiểu Kinh Thánh sẽ giúp người đó có đời sống và tương lai tốt đẹp hơn như thế nào?',
             'zh': '如果他學習聖經，為什麼會過得更快樂？他的未來會有什麼希望？'}],
  'num': 9,
  'title': {'en': 'Empathy', 'ja': '親身になって', 'ko': '감정 이입', 'vi': 'Đồng cảm', 'zh': '將心比心'}},
 {'kind': 'lesson',
  'lines': [{'en': 'Why might Nicodemus have preferred to approach Jesus at night?',
             'ja': 'ニコデモが夜にイエスに会いに行ったのはどうしてだと考えられますか。',
             'ko': '니고데모가 밤에 예수를 찾아온 것은 무슨 이유 때문일 수 있습니까?',
             'vi': 'Có lẽ tại sao Ni-cô-đem muốn đến gặp Chúa Giê-su vào ban đêm?',
             'zh': '為什麼尼哥德慕選擇在晚上去找耶穌？'},
            {'en': 'We show that we love people by being committed to helping them become disciples.',
             'ja': 'キリストの弟子になれるよう献身的に人を助けることによって、愛を示せます。',
             'ko': '열의를 갖고 제자 삼는 일을 함으로 사람들에 대한 사랑을 나타낼 수 있습니다.',
             'vi': 'Chúng ta cho thấy mình yêu thương người khác bằng cách tận tụy giúp họ trở thành môn đồ.',
             'zh': '我們愛別人，就會下定決心，努力幫助他們成為基督徒。'},
            {'en': 'Study at a time and place convenient for your Bible student.',
             'ja': '聖書レッスンの時間や場所を相手の都合に合わせる。',
             'ko': '성서 연구생에게 편리한 때에 그가 원하는 장소에서 연구하십시오.',
             'vi': 'Học vào thời gian và địa điểm thuận tiện cho học viên.',
             'zh': '在聖經學生方便的時間和地點學習。'},
            {'en': 'Study regularly.',
             'ja': 'レッスンを欠かさない。',
             'ko': '정기적으로 연구하십시오.',
             'vi': 'Học đều đặn.',
             'zh': '定期學習。'},
            {'en': 'If you will be away, do not cancel the study session.',
             'ja': '自分が不在のときもレッスンをキャンセルしなくて済むよう、次のことを考えてみてください。',
             'ko': '상황상 연구를 사회할 수 없다면, 연구를 취소하지 말고 다음과 같은 점을 고려해 보십시오.',
             'vi': 'Nếu đi vắng, đừng hủy buổi học.',
             'zh': '如果你有事，不要馬上取消討論，先想一想。'},
            {'en': 'Pray for the right attitude.',
             'ja': '正しい見方ができるよう祈る。',
             'ko': '올바른 태도를 갖게 도와 달라고 기도하십시오.',
             'vi': 'Cầu xin để có thái độ đúng.',
             'zh': '求耶和華讓你有正確的態度。'},
            {'en': 'Likely your student has many good qualities.',
             'ja': 'その人にはいいところがたくさんあるはずです。',
             'ko': '아마도 그에게는 좋은 특성이 많이 있을 것입니다.',
             'vi': 'Hẳn học viên có nhiều phẩm chất tốt.',
             'zh': '你的學生肯定有不少優點。'}],
  'num': 10,
  'title': {'en': 'Commitment', 'ja': '献身的に', 'ko': '열의', 'vi': 'Tận tụy', 'zh': '決心'}},
 {'kind': 'lesson',
  'lines': [{'en': 'When we teach in a simple way, people will remember what we taught them and we will touch their '
                   'hearts.',
             'ja': 'シンプルに分かりやすく教えると、要点が覚えやすくなり、相手の心に響きます。',
             'ko': '간단명료하게 가르치면 사람들은 감동을 받고 배운 내용을 오래 기억할 것입니다.',
             'vi': 'Khi chúng ta dạy dỗ đơn giản, người ta sẽ nhớ điều chúng ta dạy và được động đến lòng.',
             'zh': '如果我們用簡單明瞭的方式教導人，就更容易幫助他們記住要點，打動他們的心。'},
            {'en': 'Rather than relating all that you know about a subject, focus on the material in the study '
                   'publication.',
             'ja': '学んでいる内容について自分が知っていることを全部伝えようとするのではなく、教材の要点を際立たせてください。',
             'ko': '다루는 주제에 대해 자신이 알고 있는 것을 전부 말하려고 하지 말고 연구용 출판물에 나오는 내용에 초점을 맞추십시오.',
             'vi': 'Thay vì nói mọi điều anh chị biết về một đề tài, hãy tập trung vào thông tin trong ấn phẩm học '
                   'hỏi.',
             'zh': '討論要集中在教材本身，不需要補充太多細節。'},
            {'en': 'After you ask a question, wait patiently for your student to answer.',
             'ja': '質問をしたら、相手が答えてくれるまで辛抱強く待ちましょう。',
             'ko': '질문을 한 다음에는 연구생이 대답할 때까지 참을성 있게 기다려 주십시오.',
             'vi': 'Sau khi đặt câu hỏi, hãy kiên nhẫn chờ học viên trả lời.',
             'zh': '你提出問題後，要耐心地等待學生回答。'},
            {'en': 'Once your student understands the main point, move on.',
             'ja': '学んでいる人が要点を理解できたら、次に進みます。',
             'ko': '연구생이 요점을 이해했다면 다음 내용으로 넘어가십시오.',
             'vi': 'Một khi học viên đã hiểu điểm chính, hãy chuyển sang điểm kế tiếp.',
             'zh': '一旦學生理解了要點，就繼續往下討論。'},
            {'en': 'For example, before beginning a lesson about the resurrection, you might briefly review what the '
                   'student has already learned about the condition of the dead.',
             'ja': '復活についてのレッスンを始める前に、死んだ人の状態についての聖書の教えを少し復習するとよいかもしれません。',
             'ko': '예를 들어 부활에 대한 내용을 연구하기 전에, 연구생이 죽은 사람의 상태에 대해 이미 배운 내용을 간단히 복습해 볼 수 있을 것입니다.',
             'vi': 'Chẳng hạn, trước khi bắt đầu bài học về sự sống lại, anh chị có thể ôn lại vắn tắt điều người đó '
                   'đã học về tình trạng của người chết.',
             'zh': '比如，討論關於復活的那一課之前，可以先簡單地溫習一下人死後的情況是怎樣的。'},
            {'en': 'Is the illustration simple?',
             'ja': 'この例はシンプルだろうか。',
             'ko': '그 예나 비유는 간단한가?',
             'vi': 'Minh họa này có đơn giản không?',
             'zh': '這個比喻簡單嗎？'},
            {'en': 'Will my student easily understand it?',
             'ja': '相手にとって分かりやすいだろうか。',
             'ko': '연구생이 쉽게 이해할 것인가?',
             'vi': 'Học viên sẽ dễ hiểu minh họa này không?',
             'zh': '學生容易理解這個比喻嗎？'},
            {'en': 'Will it help my student to remember the main point—not just the illustration?',
             'ja': 'どんな例だったかだけでなく、例で伝えたかったことが心に残るだろうか。',
             'ko': '연구생이 요점을 기억하는 데 도움이 될 것인가? 아니면 예나 비유만 기억에 남을 것인가?',
             'vi': 'Minh họa này sẽ giúp học viên nhớ điểm chính hay là chỉ nhớ minh họa?',
             'zh': '這個比喻能幫助他記住要點嗎？'}],
  'num': 11,
  'title': {'en': 'Simplicity',
            'ja': '分かりやすく',
            'ko': '간단명료하게 가르치기',
            'vi': 'Đơn giản',
            'zh': '簡單明瞭'}},
 {'kind': 'lesson',
  'lines': [{'en': 'Why did Jesus need both love and courage to counsel the man?',
             'ja': 'イエスがこの男性に愛情を抱き、しっかり向き合っていたことが、どんなことに表れていますか。',
             'ko': '그 젊은이에게 조언하는 데 왜 사랑과 용기가 필요했습니까?',
             'vi': 'Tại sao Chúa Giê-su cần cả tình yêu thương lẫn sự can đảm để khuyên người ấy?',
             'zh': '耶穌向他提出勸告，為什麼既要有愛心，也要坦率？'},
            {'en': 'We need to speak lovingly yet frankly with our students to help them make spiritual progress.',
             'ja': '聖書を学んでいる人がエホバとの絆を強めていけるように、伝えるべきことは愛情を込めつつ率直に伝える必要があります。',
             'ko': '연구생이 영적으로 발전하도록 돕기 위해서는 사랑을 보이면서도 솔직하게 이야기해 줄 필요가 있습니다.',
             'vi': 'Chúng ta cần nói một cách yêu thương nhưng thẳng thắn với học viên để giúp họ tiến bộ về thiêng '
                   'liêng.',
             'zh': '我們需要仁慈又坦率地告訴學生，他要怎麼做才能進步。'},
            {'en': 'Commend your student regularly for his progress.',
             'ja': '学んでいる人の努力や進歩をよく褒めるようにしましょう。',
             'ko': '연구생이 발전하고 있는 점에 대해 자주 칭찬해 주십시오.',
             'vi': 'Thường xuyên khen học viên về sự tiến bộ của họ.',
             'zh': '常常留意學生進步的地方並稱讚他。'},
            {'en': 'If my student is not progressing toward baptism, what is hindering him?',
             'ja': 'この人はバプテスマに向かって成長しているだろうか。成長していないなら、何が原因なんだろう。',
             'ko': '연구생이 침례받을 정도로 발전하는 데 방해가 되는 것은 무엇인가?',
             'vi': 'Nếu học viên không tiến bộ đến bước báp-têm, thì điều gì đang cản trở họ?',
             'zh': '如果學生遲遲不受浸，是什麼妨礙他進步呢？'},
            {'en': 'Pray for the courage to discuss frankly and lovingly what your student needs to do.',
             'ja': 'その人がイエスの弟子になるために必要なことについて愛情を込めて率直に話し合えるよう、エホバに祈って力をもらいましょう。',
             'ko': '연구생이 발전하기 위해 해야 할 일에 관해 솔직하면서도 사랑에 찬 방식으로 이야기할 수 있게 용기를 달라고 기도하십시오.',
             'vi': 'Hãy cầu xin Đức Giê-hô-va ban sự can đảm để thảo luận với học viên một cách thẳng thắn và yêu '
                   'thương về những điều họ cần làm.',
             'zh': '求耶和華給你勇氣，以仁慈又坦率的方式跟學生談一談，讓他看出該怎麼做。'},
            {'en': 'Is my student applying what he is learning?',
             'ja': '学んだことを実践しているだろうか。',
             'ko': '연구생은 배우는 내용을 적용하고 있는가?',
             'vi': 'Học viên có đang áp dụng những điều mình học không?',
             'zh': '他會把學到的用出來嗎？'},
            {'en': 'Tactfully explain why you are discontinuing the study.',
             'ja': 'レッスンを中止する場合、その理由を親切に説明してください。',
             'ko': '연구를 중단하는 이유를 친절하게 설명해 주십시오.',
             'vi': 'Tế nhị giải thích tại sao anh chị ngưng cuộc học hỏi.',
             'zh': '溫和地解釋你為什麼要停止跟他討論。'},
            {'en': 'Let him know what progress he needs to make before you will resume the study.',
             'ja': 'どんなことを努力したらレッスンを再開できるか伝えます。',
             'ko': '연구를 다시 시작하려면 어떤 면에서 발전해야 하는지 이야기해 주십시오.',
             'vi': 'Cho biết người ấy cần tiến bộ trong khía cạnh nào nếu muốn học lại.',
             'zh': '告訴學生怎麼做就可以恢復討論。'}],
  'num': 12,
  'title': {'en': 'Courage', 'ja': 'しっかり向き合って', 'ko': '용기', 'vi': 'Can đảm', 'zh': '坦率'}},
 {'kind': 'appendix',
  'lines': [{'vi': 'Các biến cố và thái độ của người ta thời nay cho thấy sắp có sự thay đổi.',
            'ko': '지금 일어나고 있는 일들과 사람들이 나타내는 태도를 보면 이 세상에 곧 변화가 있을 것임을 알 수 있습니다.',
            'zh': '最近的世界大事和社會風氣顯示，一場重大的改變將要發生。',
            'en': 'Current events and attitudes indicate a change is near.',
            'ja': '今起きていることや世の中の様子を見ると，もうすぐ世界が大きく変わることが分かる。'},
           {'vi': '“Ông có bao giờ nghe về các biến cố và thái độ của người ta thời nay cho thấy sắp có sự thay đổi không?”',
            'ko': '지금 일어나고 있는 일들과 사람들이 나타내는 태도를 보면 이 세상에 곧 큰 변화가 있을 것이라는 말을 들어 보신 적 있나요?',
            'zh': '「你聽說過嗎？」最近的世界大事和社會風氣顯示，一場重大的改變將要發生。',
            'en': '“Have you ever heard that current events and attitudes indicate a change is near?”',
            'ja': '「こんなことをお聞きになったことがありますか?」今起きていることや世の中の様子を見ると，もうすぐ世界が大きく変わることが分かる。'},
           {'vi': 'Trái đất sẽ không bao giờ bị hủy diệt.',
            'ko': '지구는 결코 멸망되지 않을 것입니다.',
            'zh': '地球不會被毀滅。',
            'en': 'The earth will never be destroyed.',
            'ja': '地球が滅びることはない。'},
           {'vi': '“Ông có bao giờ nghe về trái đất sẽ không bao giờ bị hủy diệt không?”',
            'ko': '지구가 결코 멸망되지 않을 것이라는 말을 들어 보신 적 있나요?',
            'zh': '「你聽說過嗎？」地球不會被毀滅。',
            'en': '“Have you ever heard that the earth will never be destroyed?”',
            'ja': '「こんなことをお聞きになったことがありますか?」地球が滅びることはない。'},
           {'vi': 'Môi trường trái đất sẽ được khôi phục.',
            'ko': '환경 문제가 해결되고 땅이 낙원이 될 것입니다.',
            'zh': '不會再有污染和極端氣候。',
            'en': 'The earth’s environment will be restored.',
            'ja': '環境問題はなくなる。'},
           {'vi': '“Ông có bao giờ nghe về môi trường trái đất sẽ được khôi phục không?”',
            'ko': '환경 문제가 해결되고 땅이 낙원이 될 것이라는 말을 들어 보신 적 있나요?',
            'zh': '「你聽說過嗎？」不會再有污染和極端氣候。',
            'en': '“Have you ever heard that the earth’s environment will be restored?”',
            'ja': '「こんなことをお聞きになったことがありますか?」環境問題はなくなる。'},
           {'vi': 'Mọi người sẽ có sức khỏe hoàn hảo.',
            'ko': '모든 사람이 아프지 않고 건강해질 것입니다.',
            'zh': '每個人都會健健康康，不再生病。',
            'en': 'Everyone will have perfect health.',
            'ja': '全ての人が健康になる。'},
           {'vi': '“Ông có bao giờ nghe về mọi người sẽ có sức khỏe hoàn hảo không?”',
            'ko': '모든 사람이 아프지 않고 건강해질 것이라는 말을 들어 보신 적 있나요?',
            'zh': '「你聽說過嗎？」每個人都會健健康康，不再生病。',
            'en': '“Have you ever heard that everyone will have perfect health?”',
            'ja': '「こんなことをお聞きになったことがありますか?」全ての人が健康になる。'},
           {'vi': 'Bạn có thể sống trên đất mãi mãi.',
            'ko': '죽지 않고 땅에서 영원히 살게 될 것입니다.',
            'zh': '人可以在地上永遠快樂地生活。',
            'en': 'You can live forever on earth.',
            'ja': '地球でいつまでも幸せに暮らせる。'},
           {'vi': '“Ông có bao giờ nghe về bạn có thể sống trên đất mãi mãi không?”',
            'ko': '죽지 않고 땅에서 영원히 살게 될 것이라는 말을 들어 보신 적 있나요?',
            'zh': '「你聽說過嗎？」人可以在地上永遠快樂地生活。',
            'en': '“Have you ever heard that you can live forever on earth?”',
            'ja': '「こんなことをお聞きになったことがありますか?」地球でいつまでも幸せに暮らせる。'},
           {'vi': 'Người chồng cần “yêu vợ như yêu chính mình”.',
            'ko': '남편은 “자신을 사랑하듯이 아내를 사랑”해야 합니다.',
            'zh': '丈夫應該愛妻子，就像愛自己一樣。',
            'en': 'A husband should “love his wife as he does himself.”',
            'ja': '夫が「自分を愛するように妻を愛」することは大切。'},
           {'vi': '“Ông có bao giờ nghe về người chồng cần “yêu vợ như yêu chính mình” không?”',
            'ko': '남편이 “자신을 사랑하듯이 아내를 사랑”해야 한다는 말을 들어 보신 적 있나요?',
            'zh': '「你聽說過嗎？」丈夫應該愛妻子，就像愛自己一樣。',
            'en': '“Have you ever heard that a husband should “love his wife as he does himself.”?”',
            'ja': '「こんなことをお聞きになったことがありますか?」夫が「自分を愛するように妻を愛」することは大切。'},
           {'vi': 'Người vợ cần kính trọng chồng sâu xa.',
            'ko': '아내는 남편을 깊이 존경해야 합니다.',
            'zh': '妻子應該尊敬丈夫。',
            'en': 'A wife should deeply respect her husband.',
            'ja': '妻が夫に心から敬意を払うことは大切。'},
           {'vi': '“Ông có bao giờ nghe về người vợ cần kính trọng chồng sâu xa không?”',
            'ko': '아내가 남편을 깊이 존경해야 한다는 말을 들어 보신 적 있나요?',
            'zh': '「你聽說過嗎？」妻子應該尊敬丈夫。',
            'en': '“Have you ever heard that a wife should deeply respect her husband?”',
            'ja': '「こんなことをお聞きになったことがありますか?」妻が夫に心から敬意を払うことは大切。'},
           {'vi': 'Vợ chồng phải chung thủy với nhau.',
            'ko': '남편과 아내는 서로에게 충실해야 합니다.',
            'zh': '人應該對配偶忠貞。',
            'en': 'A husband and a wife should be loyal to each other.',
            'ja': '結婚の絆を大切にする夫婦はうまくいく。'},
           {'vi': '“Ông có bao giờ nghe về vợ chồng phải chung thủy với nhau không?”',
            'ko': '남편과 아내가 서로에게 충실해야 한다는 말을 들어 보신 적 있나요?',
            'zh': '「你聽說過嗎？」人應該對配偶忠貞。',
            'en': '“Have you ever heard that a husband and a wife should be loyal to each other?”',
            'ja': '「こんなことをお聞きになったことがありますか?」結婚の絆を大切にする夫婦はうまくいく。'},
           {'vi': 'Những người con tôn trọng và vâng lời cha mẹ sẽ thành công.',
            'ko': '부모를 존경하고 부모의 말에 순종하는 자녀는 행복하고 성공적인 삶을 살게 됩니다.',
            'zh': '孩子尊敬父母，聽父母的話，就會幸福快樂。',
            'en': 'Children who respect and obey their parents will succeed.',
            'ja': '親を敬って言うことを聞く子供は幸せになれる。'},
           {'vi': '“Ông có bao giờ nghe về những người con tôn trọng và vâng lời cha mẹ sẽ thành công không?”',
            'ko': '부모를 존경하고 부모의 말에 순종하는 자녀는 행복하고 성공적인 삶을 살게 된다는 말을 들어 보신 적 있나요?',
            'zh': '「你聽說過嗎？」孩子尊敬父母，聽父母的話，就會幸福快樂。',
            'en': '“Have you ever heard that children who respect and obey their parents will succeed?”',
            'ja': '「こんなことをお聞きになったことがありますか?」親を敬って言うことを聞く子供は幸せになれる。'},
           {'vi': 'Đức Chúa Trời có tên.', 'ko': '하느님에게는 이름이 있습니다.', 'zh': '上帝有個名字。', 'en': 'God has a name.', 'ja': '神には名前がある。'},
           {'vi': '“Ông có bao giờ nghe về Đức Chúa Trời có tên không?”',
            'ko': '하느님에게 이름이 있다는 말을 들어 보신 적 있나요?',
            'zh': '「你聽說過嗎？」上帝有個名字。',
            'en': '“Have you ever heard that God has a name?”',
            'ja': '「こんなことをお聞きになったことがありますか?」神には名前がある。'},
           {'vi': 'Đức Chúa Trời ban cho chúng ta một thông điệp quan trọng.',
            'ko': '하느님은 우리에게 중요한 소식을 알려 주셨습니다.',
            'zh': '上帝有重要的話要告訴我們。',
            'en': 'God communicates with us.',
            'ja': '神は人間に自分の考えを伝えている。'},
           {'vi': '“Ông có bao giờ nghe về Đức Chúa Trời ban cho chúng ta một thông điệp quan trọng không?”',
            'ko': '하느님이 우리에게 중요한 소식을 알려 주셨다는 말을 들어 보신 적 있나요?',
            'zh': '「你聽說過嗎？」上帝有重要的話要告訴我們。',
            'en': '“Have you ever heard that God communicates with us?”',
            'ja': '「こんなことをお聞きになったことがありますか?」神は人間に自分の考えを伝えている。'},
           {'vi': 'Đức Chúa Trời công bằng và không thiên vị.',
            'ko': '하느님은 공정하시고 편견이 없으십니다.',
            'zh': '上帝是不偏心的。',
            'en': 'God is fair and unbiased.',
            'ja': '神は誰に対しても公平。'},
           {'vi': '“Ông có bao giờ nghe về Đức Chúa Trời công bằng và không thiên vị không?”',
            'ko': '하느님은 공정하시고 편견이 없으시다는 말을 들어 보신 적 있나요?',
            'zh': '「你聽說過嗎？」上帝是不偏心的。',
            'en': '“Have you ever heard that God is fair and unbiased?”',
            'ja': '「こんなことをお聞きになったことがありますか?」神は誰に対しても公平。'},
           {'vi': 'Đức Chúa Trời muốn giúp đỡ chúng ta.',
            'ko': '하느님은 우리를 돕고 싶어 하십니다.',
            'zh': '上帝很想幫助我們。',
            'en': 'God wants to help us.',
            'ja': '神は私たちのことを助けたいと思っている。'},
           {'vi': '“Ông có bao giờ nghe về Đức Chúa Trời muốn giúp đỡ chúng ta không?”',
            'ko': '하느님이 우리를 돕고 싶어 하신다는 말을 들어 보신 적 있나요?',
            'zh': '「你聽說過嗎？」上帝很想幫助我們。',
            'en': '“Have you ever heard that God wants to help us?”',
            'ja': '「こんなことをお聞きになったことがありますか?」神は私たちのことを助けたいと思っている。'},
           {'vi': 'Đức Chúa Trời muốn chúng ta cầu nguyện với ngài.',
            'ko': '하느님은 우리가 그분에게 기도하기를 바라십니다.',
            'zh': '上帝希望我們向他祈禱。',
            'en': 'God wants us to pray to him.',
            'ja': '神は私たちの祈りを聞きたいと思っている。'},
           {'vi': '“Ông có bao giờ nghe về Đức Chúa Trời muốn chúng ta cầu nguyện với ngài không?”',
            'ko': '하느님이 우리가 그분에게 기도하기를 바라신다는 말을 들어 보신 적 있나요?',
            'zh': '「你聽說過嗎？」上帝希望我們向他祈禱。',
            'en': '“Have you ever heard that God wants us to pray to him?”',
            'ja': '「こんなことをお聞きになったことがありますか?」神は私たちの祈りを聞きたいと思っている。'},
           {'vi': 'Kinh Thánh dạy chúng ta cách cầu nguyện.',
            'ko': '성경은 기도하는 방법을 알려 줍니다.',
            'zh': '聖經告訴我們該怎樣祈禱。',
            'en': 'The Bible teaches us how to pray.',
            'ja': '聖書を読むと，どう祈ったらいいかが分かる。'},
           {'vi': '“Ông có bao giờ nghe về Kinh Thánh dạy chúng ta cách cầu nguyện không?”',
            'ko': '성경이 기도하는 방법을 알려 준다는 말을 들어 보신 적 있나요?',
            'zh': '「你聽說過嗎？」聖經告訴我們該怎樣祈禱。',
            'en': '“Have you ever heard that the Bible teaches us how to pray?”',
            'ja': '「こんなことをお聞きになったことがありますか?」聖書を読むと，どう祈ったらいいかが分かる。'},
           {'vi': 'Chúng ta nên thường xuyên cầu nguyện.',
            'ko': '우리는 자주 기도해야 합니다.',
            'zh': '我們應該常常禱告。',
            'en': 'We should pray often.',
            'ja': '何度も祈ることは大切。'},
           {'vi': '“Ông có bao giờ nghe về chúng ta nên thường xuyên cầu nguyện không?”',
            'ko': '우리가 자주 기도해야 한다는 말을 들어 보신 적 있나요?',
            'zh': '「你聽說過嗎？」我們應該常常禱告。',
            'en': '“Have you ever heard that we should pray often?”',
            'ja': '「こんなことをお聞きになったことがありますか?」何度も祈ることは大切。'},
           {'vi': 'Chúa Giê-su là thầy vĩ đại và lời khuyên của ngài luôn hữu ích.',
            'ko': '예수는 훌륭한 선생님이셨으며 그분의 가르침은 오늘날 우리에게도 도움이 됩니다.',
            'zh': '耶穌是偉大的導師，他的勸告永遠不會過時。',
            'en': 'Jesus was a great teacher whose advice always works.',
            'ja': 'イエスのアドバイスは今でも役に立つ。'},
           {'vi': '“Ông có bao giờ nghe về Chúa Giê-su là thầy vĩ đại và lời khuyên của ngài luôn hữu ích không?”',
            'ko': '예수는 훌륭한 선생님이셨으며 그분의 가르침이 오늘날 우리에게도 도움이 된다는 말을 들어 보신 적 있나요?',
            'zh': '「你聽說過嗎？」耶穌是偉大的導師，他的勸告永遠不會過時。',
            'en': '“Have you ever heard that Jesus was a great teacher whose advice always works?”',
            'ja': '「こんなことをお聞きになったことがありますか?」イエスのアドバイスは今でも役に立つ。'},
           {'vi': 'Chúa Giê-su báo trước những biến cố mà chúng ta thấy ngày nay.',
            'ko': '예수는 오늘날 일어나는 일들을 예언했습니다.',
            'zh': '耶穌預告在我們的時代會有一些大事發生。',
            'en': 'Jesus foretold events we see today.',
            'ja': 'イエスが予告した通りのことが今起きている。'},
           {'vi': '“Ông có bao giờ nghe về Chúa Giê-su báo trước những biến cố mà chúng ta thấy ngày nay không?”',
            'ko': '예수가 오늘날 일어나는 일들을 예언했다는 말을 들어 보신 적 있나요?',
            'zh': '「你聽說過嗎？」耶穌預告在我們的時代會有一些大事發生。',
            'en': '“Have you ever heard that Jesus foretold events we see today?”',
            'ja': '「こんなことをお聞きになったことがありますか?」イエスが予告した通りのことが今起きている。'},
           {'vi': 'Chúa Giê-su là Con Đức Chúa Trời.',
            'ko': '예수는 하느님의 아들입니다.',
            'zh': '耶穌是上帝的兒子。',
            'en': 'Jesus is God’s Son.',
            'ja': 'イエスは神の子。'},
           {'vi': '“Ông có bao giờ nghe về Chúa Giê-su là Con Đức Chúa Trời không?”',
            'ko': '예수가 하느님의 아들이라는 말을 들어 보신 적 있나요?',
            'zh': '「你聽說過嗎？」耶穌是上帝的兒子。',
            'en': '“Have you ever heard that Jesus is God’s Son?”',
            'ja': '「こんなことをお聞きになったことがありますか?」イエスは神の子。'},
           {'vi': 'Chúa Giê-su không phải là Đức Chúa Trời Toàn Năng.',
            'ko': '예수는 전능한 하느님이 아닙니다.',
            'zh': '耶穌不是上帝。',
            'en': 'Jesus is not God Almighty.',
            'ja': 'イエスは神ではない。'},
           {'vi': '“Ông có bao giờ nghe về Chúa Giê-su không phải là Đức Chúa Trời Toàn Năng không?”',
            'ko': '예수가 전능한 하느님이 아니라는 말을 들어 보신 적 있나요?',
            'zh': '「你聽說過嗎？」耶穌不是上帝。',
            'en': '“Have you ever heard that Jesus is not God Almighty?”',
            'ja': '「こんなことをお聞きになったことがありますか?」イエスは神ではない。'},
           {'vi': 'Nước Trời là một chính phủ có thật ở trên trời.',
            'ko': '하느님의 왕국은 하늘에 있는 실제 정부입니다.',
            'zh': '上帝的王國是上帝在天上設立的政府。',
            'en': 'God’s Kingdom is a real government in heaven.',
            'ja': '神は地球を治めるために王国をつくった。天に政府がある。'},
           {'vi': '“Ông có bao giờ nghe về Nước Trời là một chính phủ có thật ở trên trời không?”',
            'ko': '하느님의 왕국이 하늘에 있는 실제 정부라는 말을 들어 보신 적 있나요?',
            'zh': '「你聽說過嗎？」上帝的王國是上帝在天上設立的政府。',
            'en': '“Have you ever heard that God’s Kingdom is a real government in heaven?”',
            'ja': '「こんなことをお聞きになったことがありますか?」神は地球を治めるために王国をつくった。天に政府がある。'},
           {'vi': 'Nước Trời sẽ thay thế mọi chính phủ loài người.',
            'ko': '앞으로는 인간 정부가 아니라 하느님의 왕국이 온 땅을 다스릴 것입니다.',
            'zh': '上帝會用他的王國取代世上的所有政府。',
            'en': 'God’s Kingdom will replace human governments.',
            'ja': '人間の政府はなくなり，神の王国の政府が世界中を治めるようになる。'},
           {'vi': '“Ông có bao giờ nghe về Nước Trời sẽ thay thế mọi chính phủ loài người không?”',
            'ko': '앞으로는 인간 정부가 아니라 하느님의 왕국이 온 땅을 다스릴 것이라는 말을 들어 보신 적 있나요?',
            'zh': '「你聽說過嗎？」上帝會用他的王國取代世上的所有政府。',
            'en': '“Have you ever heard that God’s Kingdom will replace human governments?”',
            'ja': '「こんなことをお聞きになったことがありますか?」人間の政府はなくなり，神の王国の政府が世界中を治めるようになる。'},
           {'vi': 'Nước Trời là giải pháp duy nhất cho các vấn đề của nhân loại.',
            'ko': '하느님의 왕국만이 인류가 겪고 있는 모든 문제를 해결할 수 있습니다.',
            'zh': '只有上帝建立的王國能徹底解決人類的問題。',
            'en': 'God’s Kingdom is the only solution to mankind’s problems.',
            'ja': '世の中のいろいろな問題を全て解決できるのは，神の王国だけ。'},
           {'vi': '“Ông có bao giờ nghe về Nước Trời là giải pháp duy nhất cho các vấn đề của nhân loại không?”',
            'ko': '하느님의 왕국만이 인류가 겪고 있는 모든 문제를 해결할 수 있다는 말을 들어 보신 적 있나요?',
            'zh': '「你聽說過嗎？」只有上帝建立的王國能徹底解決人類的問題。',
            'en': '“Have you ever heard that God’s Kingdom is the only solution to mankind’s problems?”',
            'ja': '「こんなことをお聞きになったことがありますか?」世の中のいろいろな問題を全て解決できるのは，神の王国だけ。'},
           {'vi': 'Đức Chúa Trời không gây ra đau khổ.',
            'ko': '우리가 겪는 고난은 하느님 때문이 아닙니다.',
            'zh': '世上的苦難不是上帝造成的。',
            'en': 'God does not cause our suffering.',
            'ja': '神が私たちを苦しめることはない。'},
           {'vi': '“Ông có bao giờ nghe về Đức Chúa Trời không gây ra đau khổ không?”',
            'ko': '우리가 겪는 고난이 하느님 때문이 아니라는 말을 들어 보신 적 있나요?',
            'zh': '「你聽說過嗎？」世上的苦難不是上帝造成的。',
            'en': '“Have you ever heard that God does not cause our suffering?”',
            'ja': '「こんなことをお聞きになったことがありますか?」神が私たちを苦しめることはない。'},
           {'vi': 'Sa-tan cai trị thế gian này.',
            'ko': '이 세상은 사탄이 통치하고 있습니다.',
            'zh': '統治全世界的是魔鬼撒但。',
            'en': 'Satan rules this world.',
            'ja': 'サタンが世界を支配している。'},
           {'vi': '“Ông có bao giờ nghe về Sa-tan cai trị thế gian này không?”',
            'ko': '이 세상을 사탄이 통치하고 있다는 말을 들어 보신 적 있나요?',
            'zh': '「你聽說過嗎？」統治全世界的是魔鬼撒但。',
            'en': '“Have you ever heard that Satan rules this world?”',
            'ja': '「こんなことをお聞きになったことがありますか?」サタンが世界を支配している。'},
           {'vi': 'Đức Chúa Trời thấy sự đau khổ của bạn và muốn giúp bạn.',
            'ko': '하느님은 우리가 고난을 겪을 때 도와주고 싶어 하십니다.',
            'zh': '上帝看到你受苦，很想幫助你。',
            'en': 'God cares about your suffering.',
            'ja': '私たちが苦しいとき，神は助けたいと思っている。'},
           {'vi': '“Ông có bao giờ nghe về Đức Chúa Trời thấy sự đau khổ của bạn và muốn giúp bạn không?”',
            'ko': '하느님은 우리가 고난을 겪을 때 도와주고 싶어 하신다는 말을 들어 보신 적 있나요?',
            'zh': '「你聽說過嗎？」上帝看到你受苦，很想幫助你。',
            'en': '“Have you ever heard that God cares about your suffering?”',
            'ja': '「こんなことをお聞きになったことがありますか?」私たちが苦しいとき，神は助けたいと思っている。'},
           {'vi': 'Đức Chúa Trời sắp chấm dứt mọi đau khổ.',
            'ko': '하느님이 곧 모든 고난을 없애실 것입니다.',
            'zh': '上帝很快就會消除苦難。',
            'en': 'God will soon end suffering.',
            'ja': '神は間もなく全ての苦しみをなくす。'},
           {'vi': '“Ông có bao giờ nghe về Đức Chúa Trời sắp chấm dứt mọi đau khổ không?”',
            'ko': '하느님이 곧 모든 고난을 없애실 것이라는 말을 들어 보신 적 있나요?',
            'zh': '「你聽說過嗎？」上帝很快就會消除苦難。',
            'en': '“Have you ever heard that God will soon end suffering?”',
            'ja': '「こんなことをお聞きになったことがありますか?」神は間もなく全ての苦しみをなくす。'},
           {'vi': 'Người chết không có ý thức và không chịu khổ.',
            'ko': '죽은 사람은 의식이 없으며 고통도 느끼지 못합니다.',
            'zh': '人死了就什麼都不知道，不會再受苦。',
            'en': 'The dead are unconscious; they are not suffering.',
            'ja': '死んだ人は何も考えたり感じたりしない。苦しむこともない。'},
           {'vi': '“Ông có bao giờ nghe về người chết không có ý thức và không chịu khổ không?”',
            'ko': '죽은 사람은 의식이 없으며 고통도 느끼지 못한다는 말을 들어 보신 적 있나요?',
            'zh': '「你聽說過嗎？」人死了就什麼都不知道，不會再受苦。',
            'en': '“Have you ever heard that the dead are unconscious; they are not suffering?”',
            'ja': '「こんなことをお聞きになったことがありますか?」死んだ人は何も考えたり感じたりしない。苦しむこともない。'},
           {'vi': 'Người chết không thể giúp hoặc làm hại chúng ta.',
            'ko': '죽은 사람은 우리에게 도움을 주거나 해를 끼칠 수 없습니다.',
            'zh': '死去的人不能幫助或傷害我們。',
            'en': 'The dead cannot help us or harm us.',
            'ja': '死んだ人は私たちを助けることはできず，何か悪さをすることもない。'},
           {'vi': '“Ông có bao giờ nghe về người chết không thể giúp hoặc làm hại chúng ta không?”',
            'ko': '죽은 사람은 우리에게 도움을 주거나 해를 끼칠 수 없다는 말을 들어 보신 적 있나요?',
            'zh': '「你聽說過嗎？」死去的人不能幫助或傷害我們。',
            'en': '“Have you ever heard that the dead cannot help us or harm us?”',
            'ja': '「こんなことをお聞きになったことがありますか?」死んだ人は私たちを助けることはできず，何か悪さをすることもない。'},
           {'vi': 'Những người thân yêu quá cố sẽ được sống lại.',
            'ko': '사망한 가족과 친구들이 부활될 것입니다.',
            'zh': '死去的親朋好友會再次活過來。',
            'en': 'Dead loved ones will be resurrected.',
            'ja': '亡くなった人は生き返る。'},
           {'vi': '“Ông có bao giờ nghe về những người thân yêu quá cố sẽ được sống lại không?”',
            'ko': '사망한 가족과 친구들이 부활될 것이라는 말을 들어 보신 적 있나요?',
            'zh': '「你聽說過嗎？」死去的親朋好友會再次活過來。',
            'en': '“Have you ever heard that dead loved ones will be resurrected?”',
            'ja': '「こんなことをお聞きになったことがありますか?」亡くなった人は生き返る。'},
           {'vi': '“Sẽ không còn sự chết”.',
            'ko': '“더 이상 죽음이 없을 것입니다.”',
            'zh': '以後不會再有死亡。',
            'en': '“Death will be no more.”',
            'ja': '「死はなくな[る]」。'},
           {'vi': '“Ông có bao giờ nghe về “sẽ không còn sự chết” không?”',
            'ko': '“더 이상 죽음이 없을 것”이라는 말을 들어 보신 적 있나요?',
            'zh': '「你聽說過嗎？」以後不會再有死亡。',
            'en': '“Have you ever heard that “death will be no more.”?”',
            'ja': '「こんなことをお聞きになったことがありますか?」「死はなくな[る]」。'},
           {'vi': 'Không phải mọi tôn giáo đều làm hài lòng Đức Chúa Trời.',
            'ko': '모든 종교를 하느님이 좋아하시는 것은 아닙니다.',
            'zh': '上帝不是什麼宗教都接納。',
            'en': 'Not all religions please God.',
            'ja': '全ての宗教が神から見て良いものというわけではない。'},
           {'vi': '“Ông có bao giờ nghe về không phải mọi tôn giáo đều làm hài lòng Đức Chúa Trời không?”',
            'ko': '모든 종교를 하느님이 좋아하시는 것은 아니라는 말을 들어 보신 적 있나요?',
            'zh': '「你聽說過嗎？」上帝不是什麼宗教都接納。',
            'en': '“Have you ever heard that not all religions please God?”',
            'ja': '「こんなことをお聞きになったことがありますか?」全ての宗教が神から見て良いものというわけではない。'},
           {'vi': 'Đức Chúa Trời ghét sự đạo đức giả.',
            'ko': '하느님은 위선을 싫어하십니다.',
            'zh': '上帝憎恨虛偽的宗教。',
            'en': 'God hates hypocrisy.',
            'ja': '宗教の名の下に行われる偽善は神に許されない。'},
           {'vi': '“Ông có bao giờ nghe về Đức Chúa Trời ghét sự đạo đức giả không?”',
            'ko': '하느님은 위선을 싫어하신다는 말을 들어 보신 적 있나요?',
            'zh': '「你聽說過嗎？」上帝憎恨虛偽的宗教。',
            'en': '“Have you ever heard that God hates hypocrisy?”',
            'ja': '「こんなことをお聞きになったことがありますか?」宗教の名の下に行われる偽善は神に許されない。'},
           {'vi': 'Tình yêu thương chân thật là dấu hiệu nhận diện tôn giáo thật.',
            'ko': '진정한 사랑을 보이는 종교가 참종교입니다.',
            'zh': '真摯的愛心是正確宗教的標誌。',
            'en': 'Genuine love identifies true religion.',
            'ja': '正しい宗教は，皆が愛を表しているかどうかで見分けられる。'},
           {'vi': '“Ông có bao giờ nghe về tình yêu thương chân thật là dấu hiệu nhận diện tôn giáo thật không?”',
            'ko': '진정한 사랑을 보이는 종교가 참종교라는 말을 들어 보신 적 있나요?',
            'zh': '「你聽說過嗎？」真摯的愛心是正確宗教的標誌。',
            'en': '“Have you ever heard that genuine love identifies true religion?”',
            'ja': '「こんなことをお聞きになったことがありますか?」正しい宗教は，皆が愛を表しているかどうかで見分けられる。'}],
  'num': 'A',
  'title': {'en': 'Truths We Love to Teach',
            'ja': '会う人たちにぜひ知ってもらいたいこと',
            'ko': '우리가 사람들에게 알려 주고 싶은 진리',
            'vi': 'Những sự thật mà chúng ta thích chia sẻ',
            'zh': '我們常常傳講的真理'}},
 {'kind': 'appendix',
  'lines': [{'en': 'When someone raises a sincere question or concern, we are happy to continue the conversation.',
             'ja': '話している相手から誠実な態度で質問されたり、意見を言われたりする場合、ぜひとも会話を続けたいと思うことでしょう。',
             'ko': '어떤 사람이 진실한 태도로 우리와는 다른 생각을 표현하거나 질문을 한다면, 우리는 기꺼이 그와 계속 대화를 나눌 것입니다.',
             'vi': 'Khi người ta thành thật nêu câu hỏi hoặc điều mà họ quan tâm, chúng ta sẵn lòng trò chuyện với '
                   'họ.',
             'zh': '傳道時，如果對方態度真誠，就算他提出疑問或不同的觀點，我們也很願意跟他交談。'},
            {'en': 'We want to speak with people who may be "rightly disposed for everlasting life."',
             'ja': '私たちは「永遠の命を得るための正しい態度を持つ」人たちを見つけて助けたいと思っているからです。',
             'ko': '우리는 "영원한 생명을 얻기에 합당한 성향"을 가지고 있을 수 있는 사람들과 대화하기를 원합니다.',
             'vi': 'Chúng ta muốn nói chuyện với những ai có thể là người "có lòng ngay thẳng để hưởng sự sống vĩnh '
                   'cửu".',
             'zh': '我們很想找到「有正確的態度而可以得到永遠生命的人」。'},
            {'en': 'But what if a person is angry, wants to argue, or does not want to talk right now?',
             'ja': 'しかし、相手が怒りをぶつけてきたり、議論しようとしてきたり、話す気がなさそうだったりする場合はどうでしょうか。',
             'ko': '하지만 어떤 사람이 화를 내거나, 논쟁하려고 하거나, 대화를 나누기를 원하지 않는다면 어떻게 해야 합니까?',
             'vi': 'Nhưng nếu một người tỏ ra giận dữ, muốn tranh cãi hoặc không muốn nói chuyện vào lúc đó thì sao?',
             'zh': '但如果對方開始生氣、想爭論，或不想談下去，該怎麼辦呢？'},
            {'en': 'Calmly and tactfully end the conversation.',
             'ja': '落ち着いて上手に会話を切り上げるようにしましょう。',
             'ko': '침착하고 정중한 태도로 대화를 끝내십시오.',
             'vi': 'Hãy bình tĩnh và tử tế kết thúc cuộc trò chuyện.',
             'zh': '要溫和有禮地結束談話。'},
            {'en': 'Try to leave on good terms so that the person may be willing to converse with us in the future.',
             'ja': '相手に良い印象を残すことができれば、その人は別の機会に話を聞いてみようという気持ちになるかもしれません。',
             'ko': '존중심을 보이면서 친절하게 대화를 마무리한다면 그 사람은 나중에 우리와 대화하고 싶은 마음이 들 수 있습니다.',
             'vi': 'Hãy cố gắng rời đi trong sự ôn hòa. Nhờ thế, có thể người đó sẽ sẵn sàng nói chuyện với chúng ta '
                   'trong tương lai.',
             'zh': '你尊重對方，給他留下好印象，也許他以後會願意跟你交流。'}],
  'num': 'B',
  'title': {'en': 'Should You End the Conversation?',
            'ja': '会話を続けるか続けないか',
            'ko': '대화를 끝내야 하는 경우',
            'vi': 'Có nên kết thúc cuộc trò chuyện?',
            'zh': '我該結束談話嗎？'}},
 {'kind': 'appendix',
  'lines': [{'en': 'Much prayerful thought and research went into producing Enjoy Life Forever!',
             'ja': '「いつまでも幸せに暮らせます」を出版するに当たって、兄弟たちは祈りつつよく考え、入念なリサーチを行いました。',
             'ko': '「행복한 삶을 영원히 누리십시오!」는 많은 기도와 연구와 조사를 거쳐 만들어졌습니다.',
             'vi': 'Các anh đã cầu nguyện và nghiên cứu rất nhiều khi biên soạn sách Vui sống mãi mãi!',
             'zh': '《永遠享受美好的生命》是弟兄們反覆禱告、精心構思的成果。'},
            {'en': 'Open and close with prayer, unless the student objects.',
             'ja': '相手が同意するなら、祈りで始めて祈りで終えてください。',
             'ko': '연구생이 반대하지 않는다면 기도로 연구를 시작하고 마치십시오.',
             'vi': 'Mở đầu và kết thúc bằng lời cầu nguyện, ngoại trừ trường hợp học viên không muốn.',
             'zh': '只要學生不反對，開始和結束時都禱告。'},
            {'en': 'When starting a main section, read the focus line for that section and highlight a few of the '
                   'lesson titles.',
             'ja': '各セクションに入る時には、ポイントの部分を読み、どんなレッスンがあるか幾つかのタイトルを挙げてください。',
             'ko': '각 부를 시작할 때 "소개" 부분을 읽고, 차례에 나오는 몇 과의 제목을 언급하십시오.',
             'vi': 'Khi bắt đầu một phần trong sách, hãy đọc câu "Trọng tâm" và nêu một vài tựa bài.',
             'zh': '開始新的單元時，讀一讀這個單元的學習重點，並簡單提到某幾課的題目。'},
            {'en': 'Draw attention to the artwork in the "Dig Deeper" section, and ask the student to comment on it.',
             'ja': '「もっと調べよう」の部分にある挿絵に注意を引き、コメントしてもらいます。',
             'ko': '"더 깊이 알아보기" 부분에 나오는 삽화에 주의를 이끌면서 연구생이 삽화에 대해 해설해 보게 하십시오.',
             'vi': 'Hướng sự chú ý đến các hình trong mục "Đào sâu", và mời học viên bình luận.',
             'zh': '請學生看看「深入挖掘」裡的圖片，問問他有什麼想法。'},
            {'en': 'Try to cover each lesson in one session.',
             'ja': 'できるだけ毎回1つのレッスンを終えるようにします。',
             'ko': '한 번 연구할 때 한 과를 다 마치기 위해 노력하십시오.',
             'vi': 'Cố gắng hoàn tất một bài trong mỗi buổi học.',
             'zh': '儘量每次討論完一課。'},
            {'en': 'Keep thinking about your student.',
             'ja': '学んでいる人のことをいつも気に掛けましょう。',
             'ko': '연구생에 대해 계속 생각하십시오.',
             'vi': 'Tiếp tục nghĩ về học viên.',
             'zh': '不時想想學生的需要。'}],
  'num': 'C',
  'title': {'en': 'How to Conduct Bible Studies Using Enjoy Life Forever!',
            'ja': '「いつまでも幸せに暮らせます」を使って上手に教えるには',
            'ko': '「행복한 삶을 영원히 누리십시오!」를 사용하여 성서 연구를 사회하는 방법',
            'vi': 'Cách điều khiển cuộc học hỏi bằng sách Vui sống mãi mãi!',
            'zh': '怎樣用《美好生命》跟學生討論？'}}]
