# "교과 > 제공 연설" and "교과 > 기도와 노래" subtabs.
# Transcribed verbatim from the course booklet (pdf_layout_marked_v2.txt).
#
# Translatable Korean text fields (talk subtitle, each dialogue line's "kr", each song's
# title_kr, each prayer line's "kr") are stored as {"ko","zh","en","ja"} dicts so js_json()
# (see build_app.py) serializes them straight into JS objects that app_logic.js's T() helper
# can read directly. Non-translatable fields (who, vi, title_vi, scripture, and every song
# lyric's vi/kr -- lyric "kr" is always None, only the vi is shown) are left as plain strings.

OFFER_TALKS = [{'lines': [{'kr': {'de': 'Hallo.',
                    'en': 'Hello.',
                    'fr': 'Bonjour.',
                    'ja': 'こんにちは。',
                    'ko': '안녕하세요.',
                    'pl': 'Dzień dobry.',
                    'zh': '您好。'},
             'vi': 'Xin chào.',
             'who': 'A'},
            {'kr': {'de': 'Hallo.',
                    'en': 'Hello.',
                    'fr': 'Bonjour.',
                    'ja': 'こんにちは。',
                    'ko': '안녕하세요.',
                    'pl': 'Dzień dobry.',
                    'zh': '您好。'},
             'vi': 'Xin chào.',
             'who': 'B'},
            {'kr': {'de': 'Mein Name ist {{MY_NAME}}. Entschuldigung, wie heißen Sie?',
                    'en': "My name is {{MY_NAME}}. What's your name?",
                    'fr': "Je m'appelle {{MY_NAME}}. Pardon, comment vous vous appelez ?",
                    'ja': '私の名前は{{MY_NAME}}です。お名前は何とおっしゃいますか?',
                    'ko': '제 이름은 {{MY_NAME}}입니다. 성함이 어떻게 되세요?',
                    'pl': 'Nazywam się {{MY_NAME}}. Przepraszam, jak masz na imię?',
                    'zh': '我叫{{MY_NAME}}。請問您怎麼稱呼?'},
             'vi': 'Tôi tên là {{MY_NAME}}. Xin lỗi, bạn tên là gì?',
             'who': 'A'},
            {'kr': {'de': 'Mein Name ist Thanh.',
                    'en': 'My name is Thanh.',
                    'fr': "Je m'appelle Thanh.",
                    'ja': '私の名前はThanhです。',
                    'ko': '제 이름은 Thanh입니다.',
                    'pl': 'Nazywam się Thanh.',
                    'zh': '我叫Thanh。'},
             'vi': 'Tôi tên là Thanh.',
             'who': 'B'},
            {'kr': {'de': 'Das ist {{COMPANION}}.',
                    'en': 'This is {{COMPANION}}.',
                    'fr': 'Voici {{COMPANION}}.',
                    'ja': 'こちらは{{COMPANION}}です。',
                    'ko': '이 사람은 {{COMPANION}}예요.',
                    'pl': 'To jest {{COMPANION}}.',
                    'zh': '這位是{{COMPANION}}。'},
             'vi': 'Đây là {{COMPANION}}.',
             'who': 'A'},
            {'kr': {'de': 'Schön, Sie kennenzulernen.',
                    'en': 'Nice to meet you.',
                    'fr': 'Enchanté de faire votre connaissance.',
                    'ja': 'お会いできて嬉しいです。',
                    'ko': '만나서 반갑습니다.',
                    'pl': 'Miło mi cię poznać.',
                    'zh': '很高興認識您。'},
             'vi': 'Tôi rất vui được gặp bạn.',
             'who': 'C'},
            {'kr': {'de': 'Ganz meinerseits, freut mich auch.',
                    'en': 'Nice to meet you too.',
                    'fr': 'Moi de même, enchanté de faire votre connaissance.',
                    'ja': '私もお会いできて嬉しいです。',
                    'ko': '저도 만나서 반갑습니다.',
                    'pl': 'Mnie również miło cię poznać.',
                    'zh': '我也很高興認識您。'},
             'vi': 'Tôi cũng rất vui được gặp bạn.',
             'who': 'B'},
            {'kr': {'de': 'Woher kommen Sie ursprünglich?',
                    'en': 'Where is your hometown?',
                    'fr': "D'où venez-vous à l'origine ?",
                    'ja': 'ご出身はどちらですか?',
                    'ko': '고향이 어디세요?',
                    'pl': 'Skąd pochodzisz?',
                    'zh': '請問您的故鄉是哪裡?'},
             'vi': 'Bạn quê ở đâu?',
             'who': 'A'},
            {'kr': {'de': 'Meine Heimatstadt ist Hanoi.',
                    'en': 'My hometown is Hanoi.',
                    'fr': 'Je viens de Hanoï.',
                    'ja': '私の出身はハノイです。',
                    'ko': '제 고향은 하노이입니다.',
                    'pl': 'Pochodzę z Hanoi.',
                    'zh': '我的故鄉是河內。'},
             'vi': 'Tôi quê ở Hà Nội.',
             'who': 'B'}],
  'number': 1,
  'subtitle': {'de': 'Begrüßung und Vorstellung, Herkunft',
               'en': 'Greetings and Introduction, Origin',
               'fr': 'Salutations, présentation et origine',
               'ja': 'あいさつと自己紹介、出身地',
               'ko': '인사와 소개, 출신',
               'pl': 'Powitania, przedstawianie się i pochodzenie',
               'zh': '問候與自我介紹、出身地'}},
 {'lines': [{'kr': {'de': 'Guten Tag, wie geht es Ihnen? (Sind Sie gesund?)',
                    'en': 'Hello, how have you been? (Are you healthy?)',
                    'fr': 'Bonjour, comment allez-vous ? (Êtes-vous en bonne santé ?)',
                    'ja': 'こんにちは。お元気でしたか?(お体は元気ですか?)',
                    'ko': '안녕하세요? 잘 지내셨어요? (건강하세요?)',
                    'pl': 'Dzień dobry, jak się masz? (Czy wszystko u ciebie w porządku?)',
                    'zh': '您好嗎?最近過得好嗎?(身體健康嗎?)'},
             'vi': 'Xin chào. Bạn có khỏe không?',
             'who': 'A'},
            {'kr': {'de': 'Danke, mir geht es gut. Und Ihnen?',
                    'en': "Thank you. I've been well. Have you been well?",
                    'fr': 'Merci, je vais bien. Et vous ?',
                    'ja': 'ありがとうございます。元気に過ごしていました。お元気でしたか?',
                    'ko': '고마워요. 잘 지냈어요. 잘 지냈어요?',
                    'pl': 'Dziękuję, dobrze. A u ciebie?',
                    'zh': '謝謝。我過得很好。您過得好嗎?'},
             'vi': 'Cảm ơn bạn. Tôi khỏe. Còn bạn thế nào?',
             'who': 'B'},
            {'kr': {'de': 'Mir geht es auch gut. Sind Sie Student?',
                    'en': "I've been well too. Are you a university student?",
                    'fr': 'Je vais bien aussi. Êtes-vous étudiant ?',
                    'ja': '私も元気に過ごしていました。大学生ですか?',
                    'ko': '저도 잘 지냈어요. 대학생이에요?',
                    'pl': 'U mnie też dobrze. Czy jesteś studentem?',
                    'zh': '我也過得很好。您是大學生嗎?'},
             'vi': 'Tôi cũng khỏe. Bạn có phải là sinh viên không?',
             'who': 'A'},
            {'kr': {'de': 'Ja, das stimmt.',
                    'en': "Yes, that's right.",
                    'fr': "Oui, c'est exact.",
                    'ja': 'はい、そうです。',
                    'ko': '네. 맞아요.',
                    'pl': 'Tak, zgadza się.',
                    'zh': '是的,沒錯。'},
             'vi': 'Dạ, phải.',
             'who': 'B'},
            {'kr': {'de': 'Wie lange sind Sie schon in Korea?',
                    'en': 'How long have you been in Korea?',
                    'fr': 'Depuis combien de temps êtes-vous en Corée ?',
                    'ja': '韓国に来てどのくらいになりますか?',
                    'ko': '한국에 온 지 얼마나 됐어요?',
                    'pl': 'Od jak dawna jesteś w Korei?',
                    'zh': '您來韓國多久了?'},
             'vi': 'Bạn sang Hàn Quốc được bao lâu rồi?',
             'who': 'A'},
            {'kr': {'de': 'Ich bin seit drei Jahren in Korea. Wie lange lernen Sie schon Vietnamesisch?',
                    'en': "I've been in Korea for 3 years. How long have you been studying Vietnamese?",
                    'fr': 'Je suis en Corée depuis trois ans. Depuis combien de temps apprenez-vous le vietnamien ?',
                    'ja': '韓国に来て3年になります。ベトナム語を勉強してどのくらいになりますか?',
                    'ko': '한국에 온 지 3년 됐어요. 베트남어 공부한 지 얼마나 됐어요?',
                    'pl': 'Jestem w Korei od trzech lat. A od jak dawna uczysz się wietnamskiego?',
                    'zh': '我來韓國三年了。您學越南語多久了?'},
             'vi': 'Tôi sang Hàn Quốc được ba năm rồi. Bạn học tiếng Việt được bao lâu rồi?',
             'who': 'B'},
            {'kr': {'de': 'Ich lerne seit einer Woche Vietnamesisch.',
                    'en': "I've been studying Vietnamese for a week.",
                    'fr': "J'apprends le vietnamien depuis une semaine.",
                    'ja': 'ベトナム語を勉強して1週間になります。',
                    'ko': '베트남어 공부한 지 일주일 됐어요.',
                    'pl': 'Uczę się wietnamskiego od tygodnia.',
                    'zh': '我學越南語一個星期了。'},
             'vi': 'Tôi học tiếng Việt được một tuần rồi.',
             'who': 'A'}],
  'number': 2,
  'subtitle': {'de': 'Begrüßung und persönlicher Hintergrund',
               'en': 'Greetings and Personal Background',
               'fr': 'Salutations et parcours personnel',
               'ja': 'あいさつと個人の経歴',
               'ko': '인사와 개인 이력',
               'pl': 'Powitania i sytuacja życiowa',
               'zh': '問候與個人經歷'}},
 {'lines': [{'kr': {'de': 'Das sind meine Kontaktdaten. Könnten Sie mir vielleicht auch Ihre Telefonnummer geben?',
                    'en': 'This is my contact information. Could I get your contact information as well?',
                    'fr': 'Voici mes coordonnées. Pourriez-vous me donner votre numéro de téléphone ?',
                    'ja': 'これは私の連絡先です。よろしければ連絡先を教えていただけますか?',
                    'ko': '이건 제 연락처에요. 혹시 연락처 주실 수 있을까요?',
                    'pl': 'Oto moje dane kontaktowe. Czy mógłbyś podać mi swój numer telefonu?',
                    'zh': '這是我的聯絡方式。可以請您也給我您的聯絡方式嗎?'},
             'vi': 'Đây là số điện thoại của tôi. Bạn có thể cho tôi số điện thoại được không?',
             'who': 'A'},
            {'kr': {'de': 'Meine Nummer ist {{MY_PHONE}}.',
                    'en': 'My number is {{MY_PHONE}}.',
                    'fr': 'Mon numéro est le {{MY_PHONE}}.',
                    'ja': '私の番号は{{MY_PHONE}}です。',
                    'ko': '제 번호는 {{MY_PHONE}}에요.',
                    'pl': 'Mój numer to {{MY_PHONE}}.',
                    'zh': '我的號碼是{{MY_PHONE}}。'},
             'vi': 'Số điện thoại của tôi là {{MY_PHONE}}.',
             'who': 'B'},
            {'kr': {'de': 'Vielen Dank! Wie alt sind Sie?',
                    'en': 'Thank you! How old are you?',
                    'fr': 'Merci beaucoup ! Quel âge avez-vous ?',
                    'ja': 'ありがとうございます!おいくつですか?',
                    'ko': '감사합니다! 몇 살이에요?',
                    'pl': 'Dziękuję bardzo! Ile masz lat?',
                    'zh': '謝謝!請問您幾歲?'},
             'vi': 'Cảm ơn bạn! Bạn bao nhiêu tuổi?',
             'who': 'A'},
            {'kr': {'de': 'Ich bin {{LISTENER_AGE}} Jahre alt. Und wie alt sind Sie?',
                    'en': 'I am {{LISTENER_AGE}} years old. How old are you?',
                    'fr': "J'ai {{LISTENER_AGE}} ans. Et vous, quel âge avez-vous ?",
                    'ja': '私は{{LISTENER_AGE}}歳です。あなたは何歳ですか?',
                    'ko': '저는 {{LISTENER_AGE}}살이에요. 당신은 몇 살이에요?',
                    'pl': 'Mam {{LISTENER_AGE}} lat. A ty ile masz lat?',
                    'zh': '我{{LISTENER_AGE}}歲。您幾歲?'},
             'vi': 'Tôi {{LISTENER_AGE}} tuổi. Còn bạn bao nhiêu tuổi?',
             'who': 'B'},
            {'kr': {'de': 'Ich bin {{MY_AGE}} Jahre alt. Sind Sie verheiratet?',
                    'en': 'I am {{MY_AGE}} years old. Are you married?',
                    'fr': "J'ai {{MY_AGE}} ans. Êtes-vous marié(e) ?",
                    'ja': '私は{{MY_AGE}}歳です。ご結婚されていますか?',
                    'ko': '저는 {{MY_AGE}}살이에요. 결혼은 하셨나요?',
                    'pl': 'Mam {{MY_AGE}} lat. Czy jesteś w związku małżeńskim?',
                    'zh': '我{{MY_AGE}}歲。您結婚了嗎?'},
             'vi': 'Tôi {{MY_AGE}} tuổi. Bạn đã kết hôn chưa?',
             'who': 'A'},
            {'kr': {'de': 'Ich bin verheiratet. Und Sie?',
                    'en': "I'm married. Are you married?",
                    'fr': 'Oui, je suis marié(e). Et vous ?',
                    'ja': '結婚しています。あなたは結婚していますか?',
                    'ko': '결혼했어요. 당신은 결혼했나요?',
                    'pl': 'Tak, jestem w związku małżeńskim. A ty?',
                    'zh': '我結婚了。您結婚了嗎?'},
             'vi': 'Tôi đã kết hôn rồi. Bạn có lập gia đình chưa?',
             'who': 'B'},
            {'kr': {'de': '{{MARITAL_A}}',
                    'en': '{{MARITAL_A}}',
                    'fr': '{{MARITAL_A}}',
                    'ja': '{{MARITAL_A}}',
                    'ko': '{{MARITAL_A}}',
                    'pl': '{{MARITAL_A}}',
                    'zh': '{{MARITAL_A}}'},
             'vi': '{{MARITAL_A}}',
             'who': 'A'}],
  'number': 3,
  'subtitle': {'de': 'Telefonnummer, Alter und Familienstand',
               'en': 'Phone Number, Age, and Marital Status',
               'fr': 'Numéro de téléphone, âge et situation familiale',
               'ja': '電話番号と年齢、結婚の有無',
               'ko': '전화번호와 나이, 결혼여부',
               'pl': 'Numer telefonu, wiek i stan cywilny',
               'zh': '電話號碼、年齡與婚姻狀況'}},
 {'lines': [{'kr': {'de': 'Könnten wir uns ein andermal wieder treffen?',
                    'en': 'Could we meet again next time?',
                    'fr': 'Pourrions-nous nous revoir une prochaine fois ?',
                    'ja': '今度また会っていただけますか?',
                    'ko': '다음에 다시 만날 수 있을까요?',
                    'pl': 'Czy moglibyśmy spotkać się ponownie następnym razem?',
                    'zh': '我們下次可以再見面嗎?'},
             'vi': 'Chúng ta sẽ gặp lần khác được không?',
             'who': 'A'},
            {'kr': {'de': 'Ja, gerne.',
                    'en': 'Yes.',
                    'fr': 'Oui, avec plaisir.',
                    'ja': 'はい。',
                    'ko': '네.',
                    'pl': 'Tak, z przyjemnością.',
                    'zh': '好的。'},
             'vi': 'Dạ được.',
             'who': 'B'},
            {'kr': {'de': 'Wo könnten wir uns treffen? Wohnen Sie hier in der Nähe?',
                    'en': 'Where shall we meet? Is your house nearby?',
                    'fr': "Où pourrions-nous nous retrouver ? Habitez-vous près d'ici ?",
                    'ja': 'どこで会いましょうか?お宅はこの近くですか?',
                    'ko': '어디서 만날까요? 집이 근처인가요?',
                    'pl': 'Gdzie moglibyśmy się spotkać? Czy mieszkasz w pobliżu?',
                    'zh': '我們要在哪裡見面呢?您家在附近嗎?'},
             'vi': 'Chúng ta có thể gặp nhau ở đâu? Nhà bạn có gần đây không?',
             'who': 'A'},
            {'kr': {'de': 'Ja, ich wohne ganz in der Nähe.',
                    'en': "Yes. It's close to here.",
                    'fr': "Oui, j'habite tout près d'ici.",
                    'ja': 'はい、ここから近いです。',
                    'ko': '네. 여기에서 가까워요.',
                    'pl': 'Tak, mieszkam bardzo blisko stąd.',
                    'zh': '是的,離這裡很近。'},
             'vi': 'Dạ. Nhà tôi ở gần đây.',
             'who': 'B'},
            {'kr': {'de': 'Wann würde es Ihnen am besten passen?',
                    'en': 'When would be convenient for you?',
                    'fr': 'Quel moment vous conviendrait le mieux ?',
                    'ja': 'いつがご都合よろしいですか?',
                    'ko': '언제가 편리하실까요?',
                    'pl': 'Kiedy najbardziej ci pasuje?',
                    'zh': '您什麼時候方便呢?'},
             'vi': 'Khi nào thì tiện cho bạn?',
             'who': 'A'},
            {'kr': {'de': 'Am Wochenende habe ich frei.',
                    'en': 'I rest on weekends.',
                    'fr': "J'ai congé le week-end.",
                    'ja': '週末は休みです。',
                    'ko': '주말에 쉬어요.',
                    'pl': 'Mam wolne w weekend.',
                    'zh': '我週末休息。'},
             'vi': 'Tôi được nghỉ vào cuối tuần.',
             'who': 'B'},
            {'kr': {'de': 'Hätten Sie dann diesen Samstagnachmittag Zeit?',
                    'en': 'Then, do you have time this Saturday?',
                    'fr': 'Alors... auriez-vous du temps ce samedi après-midi ?',
                    'ja': 'では、今週の土曜日はお時間ありますか?',
                    'ko': '그럼 이번 주 토요일에 시간이 있나요?',
                    'pl': 'A więc... czy masz czas w tę sobotę po południu?',
                    'zh': '那麼這個星期六您有空嗎?'},
             'vi': 'Vậy... Chiều thứ bảy tuần này bạn có thời gian không?',
             'who': 'A'},
            {'kr': {'de': 'Tut mir leid, diesen Samstag bin ich beschäftigt. Sonntag würde mir besser passen.',
                    'en': "I'm sorry. I'm busy this Saturday. Sunday seems better.",
                    'fr': 'Désolé, ce samedi je suis occupé. Dimanche me conviendrait mieux.',
                    'ja': 'すみません。今週の土曜日は忙しいです。日曜日の方が良さそうです。',
                    'ko': '죄송합니다. 이번 주 토요일에는 바빠요. 일요일이 더 좋을 것 같아요.',
                    'pl': 'Przepraszam, w tę sobotę jestem zajęty. Niedziela byłaby lepsza.',
                    'zh': '不好意思,這個星期六我很忙。星期日應該比較好。'},
             'vi': 'Xin lỗi. Thứ bảy này thì tôi bận rồi. Chủ Nhật thì tiện hơn.',
             'who': 'B'},
            {'kr': {'de': 'In Ordnung. Dann treffen wir uns diesen Sonntag.',
                    'en': "Good. Then let's meet this Sunday.",
                    'fr': "D'accord. Alors retrouvons-nous ce dimanche.",
                    'ja': 'わかりました。では、今週の日曜日に会いましょう。',
                    'ko': '좋습니다. 그럼 이번 주 일요일에 만나요.',
                    'pl': 'Rozumiem. W takim razie spotkajmy się w tę niedzielę.',
                    'zh': '好的,那麼我們這個星期日見面吧。'},
             'vi': 'OK. Hẹn gặp vào Chủ Nhật này.',
             'who': 'A'},
            {'kr': {'de': 'Bis dann! Auf Wiedersehen.',
                    'en': 'See you next time.',
                    'fr': 'À bientôt ! Au revoir.',
                    'ja': 'また会いましょう。',
                    'ko': '다음에 만나요.',
                    'pl': 'Do zobaczenia! Do widzenia.',
                    'zh': '下次見。'},
             'vi': 'Hẹn gặp lại.',
             'who': 'B'}],
  'number': 4,
  'subtitle': {'de': 'Rückbesuch vereinbaren (Wohnort, Wochentag)',
               'en': 'Return Visit Appointment (Where You Live, Day of the Week)',
               'fr': 'Organiser une nouvelle visite (lieu d’habitation, jour de la semaine)',
               'ja': '再訪問の約束(住んでいる場所、曜日)',
               'ko': '재방문 약속(사는 곳, 요일)',
               'pl': 'Umawianie ponownej wizyty (miejsce zamieszkania, dzień tygodnia)',
               'zh': '再訪問預約(住處、星期)'}},
 {'lines': [{'kr': {'de': 'Haben Sie schon einmal davon gehört, dass Gott einen Namen hat?',
                    'en': 'Have you heard that God has a name?',
                    'fr': 'Avez-vous déjà entendu dire que Dieu a un nom ?',
                    'ja': '神に名前があることを聞いたことがありますか?',
                    'ko': '하느님에게 이름이 있다는 걸 들어보셨나요?',
                    'pl': 'Czy słyszałeś kiedyś o tym, że Bóg ma imię?',
                    'zh': '您聽說過上帝有名字嗎?'},
             'vi': 'Bạn có bao giờ nghe danh của Đức Chúa Trời chưa?',
             'who': 'A'},
            {'kr': {'de': 'Der Name Gottes? Ich wusste gar nicht, dass Gott einen Namen hat.',
                    'en': "God's name? I didn't know God had a name.",
                    'fr': 'Le nom de Dieu ? Je ne savais pas que Dieu avait un nom.',
                    'ja': '神の名前ですか？神に名前があるとは知りませんでした。',
                    'ko': '하느님의 이름이요? 하느님에게 이름이 있는지 몰랐어요.',
                    'pl': 'Imię Boga? Nie wiedziałem, że Bóg ma imię.',
                    'zh': '上帝的名字？我不知道上帝有名字。'},
             'vi': 'Danh Đức Chúa Trời hả? Tôi không biết là Đức Chúa Trời có danh riêng.',
             'who': 'B'},
            {'kr': {'de': 'Viele sind überrascht, wenn sie das erfahren. Darf ich Ihnen ein kurzes Video zeigen? '
                          '(Video zum Traktat „Was ist Gott für eine Person?“ ansehen.) Was sagt dieses Video über den '
                          'Namen Gottes?',
                    'en': 'Some people are surprised to learn that. May I show you a short video? (Watch the tract '
                          'video "What Is God Like?") What does this video tell us God\'s name is?',
                    'fr': "Beaucoup de gens sont surpris de l'apprendre. Puis-je vous montrer une courte vidéo ? "
                          "(Regarder la vidéo du tract « Qui est vraiment Dieu ? ».) D'après cette vidéo, quel est le "
                          'nom de Dieu ?',
                    'ja': 'それを知って驚く方もいらっしゃいますよ。動画を一つお見せしてもよろしいですか？（パンフレット「真の神とはどのような方ですか」の動画を見る。）この動画では、神の名前は何だと教えていますか。',
                    'ko': '그걸 알고 놀라는 분들이 계시지요. 제가 동영상 하나 보여 드려도 될까요? (‘참 하느님은 어떤 분입니까?’ 전도지 동영상을 본다.) 이 동영상은 하느님의 이름이 '
                          '무엇이라고 알려주나요?',
                    'pl': 'Wiele osób jest tym zaskoczonych. Czy mogę pokazać ci krótki film? (Oglądanie filmu z '
                          'traktatu „Kim tak naprawdę jest Bóg?”). Jak według tego filmu Bóg ma na imię?',
                    'zh': '有些人知道這件事後會感到驚訝。我可以給您看一段影片嗎？（觀看單張《真正的上帝是怎樣的一位？》的影片。）這段影片告訴我們上帝的名字是什麼呢？'},
             'vi': 'Người ta ngạc nhiên khi biết điều đó. Tôi cho bạn xem một video được không? (xem video tờ chuyên '
                   'đề ʻÔng Trời là ai?’) Video này cho biết danh của Đức Chúa Trời là gì?',
             'who': 'A'},
            {'kr': {'de': 'Der Name Gottes ist Jehova.',
                    'en': "God's name is Jehovah.",
                    'fr': 'Le nom de Dieu est Jéhovah.',
                    'ja': '神の名前はエホバなんですね。',
                    'ko': '하느님의 이름이 여호와네요.',
                    'pl': 'Bóg ma na imię Jehowa.',
                    'zh': '上帝的名字是耶和華。'},
             'vi': 'Danh Đức Chúa Trời là Giê-ho-va.',
             'who': 'B'},
            {'kr': {'de': 'Wenn wir Gottes Namen kennen, können wir ihm näherkommen.',
                    'en': "Knowing God's name can help us draw closer to him.",
                    'fr': 'Connaître le nom de Dieu peut nous aider à nous approcher de lui.',
                    'ja': '神の名前を知ると、神により近づくことができます。',
                    'ko': '하느님의 이름을 알면 그분과 가까워질 수 있어요.',
                    'pl': 'Poznanie imienia Bożego może pomóc nam zbliżyć się do Niego.',
                    'zh': '知道上帝的名字，可以幫助我們與他更親近。'},
             'vi': 'Nếu biết danh Đức Chúa Trời thì chúng ta có thể đến gần Ngài.',
             'who': 'A'}],
  'number': 5,
  'subtitle': {'de': 'Der Name Gottes (Video vorstellen)',
               'en': "God's Name (Video Introduction)",
               'fr': 'Le nom de Dieu (présentation d’une vidéo)',
               'ja': '神の名前(動画紹介)',
               'ko': '하느님의 이름(동영상 소개)',
               'pl': 'Imię Boże (wprowadzenie filmu)',
               'zh': '上帝的名字(影片介紹)'}},
 {'lines': [{'kr': {'de': 'Was ist Ihrer Meinung nach das Geheimnis einer glücklichen Familie?',
                    'en': 'What do you think is the secret to a happy family?',
                    'fr': "D'après vous, quel est le secret d'une famille heureuse ?",
                    'ja': '家族が幸せになる秘訣は何だと思われますか。',
                    'ko': '가족이 행복할 수 있는 비결이 무엇이라고 생각하시나요?',
                    'pl': 'Jak myślisz, co jest kluczem do szczęścia w rodzinie?',
                    'zh': '您認為家庭幸福的秘訣是什麼呢？'},
             'vi': 'Theo bạn, bí quyết giúp gia đình hạnh phúc là gì?',
             'who': 'A'},
            {'kr': {'de': 'Ich denke, das Wichtigste ist Liebe.',
                    'en': 'I think having love is important.',
                    'fr': "Je pense que l'amour est le plus important.",
                    'ja': '愛があることが大切だと思います。',
                    'ko': '사랑이 있는 것이 중요하다고 생각해요.',
                    'pl': 'Myślę, że najważniejsza jest miłość.',
                    'zh': '我覺得有愛是很重要的。'},
             'vi': 'Tôi nghĩ điều quan trọng là có tình yêu thương.',
             'who': 'B'},
            {'kr': {'de': 'Das stimmt. Liebe ist wirklich wichtig. Sehen wir uns doch einmal an, was die Bibel sagt. '
                          'Würden Sie diesen Bibeltext bitte laut vorlesen? Epheser 5:33',
                    'en': "That's right. Love really is important. Shall we take note of what the Bible says? Could "
                          'you read this scripture out loud? Ephesians 5:33',
                    'fr': "C'est vrai. L'amour est vraiment essentiel. Voyons ce que dit la Bible. Pourriez-vous lire "
                          'ce verset à voix haute ? Éphésiens 5:33.',
                    'ja': 'そうですね。愛は本当に大切です。聖書では何と述べているか、見てみましょうか。この聖句を声に出して読んでいただけますか。エフェソス5:33',
                    'ko': '맞아요. 사랑이 정말 중요하죠. 성경에서는 무엇이라고 하는지 유의해보실까요. 이 성구를 소리 내서 읽어주시겠어요. 에베소 5:33',
                    'pl': 'To prawda. Miłość jest naprawdę ważna. Zobaczmy, co mówi Biblia. Czy mógłbyś przeczytać ten '
                          'werset na głos? Efezjan 5:33.',
                    'zh': '沒錯，愛真的很重要。我們來看看聖經怎麼說好嗎？可以請您把這節經文念出來嗎？以弗所書5:33'},
             'vi': 'Tôi đồng ý. Tình yêu thương rất quan trọng. Hãy để ý những gì Kinh Thánh nói. Xin mời đọc lớn '
                   'tiếng câu Kinh Thánh này. Ê-phê-sô 5:33.',
             'who': 'A'},
            {'kr': {'de': '„Aber auch jeder von euch soll seine Frau so lieben wie sich selbst. Die Frau ihrerseits '
                          'soll tiefen Respekt vor ihrem Mann haben.“',
                    'en': '"Each one of you must love his wife as he does himself; and the wife should have deep '
                          'respect for her husband."',
                    'fr': '« Cependant, chacun de vous doit aimer sa femme comme lui-même ; de son côté, la femme doit '
                          'avoir un profond respect pour son mari. »',
                    'ja': '「あなた方各自も自分自身を愛するように妻を愛しなさい。そして，妻は夫に対して深い敬意を持つべきです」',
                    'ko': '“여러분도 각자 자신을 사랑하듯이 아내를 사랑하십시오. 그리고 아내는 남편에 대해 깊은 존경심을 가져야 합니다.”',
                    'pl': '„Ale też niech każdy z was kocha swoją żonę jak samego siebie. Z kolei żona powinna mieć '
                          'głęboki respekt dla swojego męża.”',
                    'zh': '「你們各人都要愛自己的妻子，好像愛自己一樣；妻子也要對丈夫深懷敬重之心。」'},
             'vi': '“Mỗi người phải yêu vợ như yêu chính mình, còn vợ thì nên kính trọng chồng sâu xa.”',
             'who': 'B'},
            {'kr': {'de': 'Vielen Dank. Finden Sie diesen Rat alltagstauglich?',
                    'en': 'Thank you. Do you think this counsel is practical?',
                    'fr': 'Merci. Pensez-vous que ce conseil soit pratique ?',
                    'ja': 'ありがとうございます。この言葉は実用的だと思われますか。',
                    'ko': '감사합니다. 이 말씀이 실용적이라고 생각하시나요?',
                    'pl': 'Dziękuję. Czy uważasz, że ta rada jest praktyczna?',
                    'zh': '謝謝您。您覺得這段話實用嗎？'},
             'vi': 'Cám ơn. Bạn nghĩ lời này có thiết thực không?',
             'who': 'A'},
            {'kr': {'de': 'Auf jeden Fall. Ich versuche auch, mich daran zu halten.',
                    'en': 'Of course. I try to do this myself.',
                    'fr': "Absolument. J'essaie moi-même de l'appliquer.",
                    'ja': 'もちろんです。私もそうしようと努力しています。',
                    'ko': '당연하죠. 저도 이렇게 하려고 노력하는걸요.',
                    'pl': 'Tak, zdecydowanie. Sam staram się ją stosować.',
                    'zh': '當然啊，我也在努力這樣做。'},
             'vi': 'Chắc chắn rồi. Tôi đang cố gắng làm vậy.',
             'who': 'B'},
            {'kr': {'de': 'Sehr schön.',
                    'en': "That's very good.",
                    'fr': "C'est très bien.",
                    'ja': 'とてもいいですね。',
                    'ko': '아주 좋네요.',
                    'pl': 'To bardzo dobrze.',
                    'zh': '太好了。'},
             'vi': 'Rất tốt.',
             'who': 'A'}],
  'number': 6,
  'subtitle': {'de': 'Ein glückliches Familienleben (Bibeltext vorstellen)',
               'en': 'Family Happiness (Scripture Introduction)',
               'fr': 'Le bonheur familial (présentation d’un verset)',
               'ja': '家庭の幸せ（聖句紹介）',
               'ko': '가정의 행복(성구 소개)',
               'pl': 'Szczęście w rodzinie (odczytanie wersetu)',
               'zh': '家庭幸福（經文介紹）'}},
 {'lines': [{'kr': {'de': 'Wir alle haben schon geliebte Menschen durch den Tod verloren. Was meinen Sie zu dieser '
                          'Frage? (Traktat „Wird es je ein Wiedersehen mit den Toten geben?“ zeigen – die wörtliche '
                          'vietnamesische Formulierung lautet: „Ist mit dem Tod alles vorbei?“)',
                    'en': 'We have all lost someone we love. What do you think about this question? (Tract "Can We See '
                          'Our Dead Loved Ones Again?" — the literal Vietnamese phrase is "Is death the end?")',
                    'fr': 'Nous avons tous perdu des êtres chers. Que pensez-vous de cette question ? (Montrer le '
                          "tract « Re reverra-t-on un jour nos proches disparus ? » — l'expression vietnamienne "
                          'littérale est : « La mort est-elle la fin de tout ? »)',
                    'ja': '私たちは皆、愛する人を亡くした経験があります。この質問についてどう思われますか。（パンフレット「亡くなった家族や友人にまた会えますか」―ベトナム語を直訳すると「死んだら終わりですか」という表現になります）',
                    'ko': '우리 모두는 사랑하는 사람과 사별한 적이 있죠. 혹시 이 질문에 대해 어떻게 생각하세요? (전도지 “사망한 가족이나 친구를 다시 만날 수 있습니까?” -베트남어 '
                          '직역 표현은 “죽으면 끝입니까?”)',
                    'pl': 'Wszyscy tracimy bliskie nam osoby. Co sądzisz o takim pytaniu? (Pokazanie traktatu „Czy '
                          'umarli mogą ożyć?” — dosłowne wietnamskie wyrażenie: „Czy śmierć to koniec wszystkiego?”)',
                    'zh': '我們每個人都曾經失去過所愛的人。您對這個問題有什麼看法呢？（傳單《能不能再見到去世的親友？》——越南語直譯的說法是「死了就是終結嗎？」）'},
             'vi': 'Tất cả chúng ta đều có người thân yêu đã mất. Vậy bạn nghĩ gì về câu hỏi này? (cho xem tờ chuyên '
                   'đề “Có phải chết là hết?)',
             'who': 'A'},
            {'kr': {'de': 'Ich denke, mit dem Tod ist alles vorbei.',
                    'en': 'I think death is the end.',
                    'fr': "Je pense qu'avec la mort, tout est fini.",
                    'ja': '死んだら終わりだと思います。',
                    'ko': '전 죽으면 끝이라고 생각해요.',
                    'pl': 'Myślę, że śmierć to koniec wszystkiego.',
                    'zh': '我覺得人死了就什麼都沒有了。'},
             'vi': 'Tôi nghĩ rằng khi một người chết thì là hết.',
             'who': 'B'},
            {'kr': {'de': 'So denken Sie also. Könnten unsere verstorbenen Lieben denn wirklich wieder lebendig '
                          'werden?',
                    'en': "I see, that's what you think. Well, is it really possible for our deceased loved ones to "
                          'live again?',
                    'fr': "C'est ce que vous pensez. Alors, nos proches disparus peuvent-ils vraiment revivre un jour "
                          '?',
                    'ja': 'そう思っていらっしゃるのですね。では、亡くなった愛する人が本当によみがえることはあるのでしょうか。',
                    'ko': '그렇게 생각하시는군요. 그럼 과연 사망한 사랑하는 사람이 다시 살아날 수 있을까요?',
                    'pl': 'Rozumiem, że tak uważasz. Ale czy nasi zmarli bliscy naprawdę mogą jeszcze ożyć?',
                    'zh': '原來您是這麼想的。那麼，去世的親人真的有可能復活嗎？'},
             'vi': 'Bạn nghĩ như vậy. Thế thì người thân yêu đã qua đời có thể được sống lại không?',
             'who': 'A'},
            {'kr': {'de': 'Das klingt wunderschön, ist aber wohl schwer zu glauben.',
                    'en': 'That sounds wonderful, but I find it hard to believe.',
                    'fr': "C'est une belle perspective, mais cela semble difficile à croire.",
                    'ja': 'とても良い話ですが、信じることができません。',
                    'ko': '너무 좋은 말이지만 믿을 수가 없네요.',
                    'pl': 'To piękna myśl, ale trudno w to uwierzyć.',
                    'zh': '這話聽起來很好，但我無法相信。'},
             'vi': 'Nghe quá tuyệt vời nhưng chắc là khó tin.',
             'who': 'B'},
            {'kr': {'de': 'Das ist wirklich nicht leicht zu glauben. Aber die Bibel zeigt, dass Gott sie auferwecken '
                          'wird. Mehr dazu finden Sie auf JW.ORG. (Kontaktkärtchen überreichen)',
                    'en': 'It is hard to believe. But the Bible tells us that God will resurrect them. You can find '
                          'out more at JW.ORG. (Offer JW card)',
                    'fr': "C'est vrai que c'est difficile à croire. Mais la Bible promet que Dieu va les ressusciter. "
                          'Pour en savoir plus, vous pouvez vous rendre sur JW.ORG. (Laisser une carte de contact JW)',
                    'ja': '信じにくいお話ですよね。しかし聖書には、神がその人たちを復活させてくださると書かれています。詳しくはJW.ORGでご覧ください。（JWカードを渡す）',
                    'ko': '믿기 힘든 말이긴 하죠. 하지만 성경에서는 하느님께서 그들을 부활시키실 것이라고 알려주지요. 더 자세한 점은 JW.ORG에서 알아보세요.(JW카드 제공)',
                    'pl': 'To prawda, niełatwo w to uwierzyć. Ale Biblia obiecuje, że Bóg ich wskrzesi. Więcej '
                          'informacji możesz znaleźć w serwisie JW.ORG. (Wręczenie wizytówki JW)',
                    'zh': '確實不容易相信。不過聖經告訴我們，上帝會使他們復活。您可以到JW.ORG網站進一步瞭解。（提供JW卡片）'},
             'vi': 'Đúng là một điều khó tin. Nhưng Kinh Thánh cho biết rằng Đức Chúa Trời sẽ làm cho họ sống lại. Để '
                   'biết thêm, xin vào trang JW.org. (để lại thẻ JW)',
             'who': 'A'},
            {'kr': {'de': 'Ja, danke.',
                    'en': 'Yes.',
                    'fr': 'Oui, merci.',
                    'ja': 'はい。',
                    'ko': '네.',
                    'pl': 'Tak, dziękuję.',
                    'zh': '好的。'},
             'vi': 'Dạ.',
             'who': 'B'}],
  'number': 7,
  'subtitle': {'de': 'Tod (Traktat und Kontaktkärtchen anbieten)',
               'en': 'Death (Offer tract and JW card)',
               'fr': 'La mort (proposer un tract et une carte de visite JW)',
               'ja': '死（パンフレットとJWカードを渡す）',
               'ko': '사망(전도지와 JW카드 제공)',
               'pl': 'Śmierć (zaproponowanie traktatu i wizytówki JW)',
               'zh': '死亡（提供傳單和JW卡片）'}},
 {'lines': [{'kr': {'de': 'Haben Sie schon einmal davon gehört, dass wir für immer glücklich leben können?',
                    'en': 'Have you heard that we can live happily forever?',
                    'fr': 'Avez-vous déjà entendu dire que nous pourrions vivre heureux pour toujours ?',
                    'ja': '私たちが永遠に幸せに生きられるということを聞いたことがありますか。',
                    'ko': '우리가 영원히 행복하게 살 수 있다는 점을 들어 보셨나요?',
                    'pl': 'Czy słyszałeś kiedyś o tym, że możemy żyć szczęśliwie na zawsze?',
                    'zh': '您有沒有聽說過我們可以永遠幸福地活著呢？'},
             'vi': 'Bạn có bao giờ nghe về chúng ta có thể vui sống mãi mãi chưa?',
             'who': 'A'},
            {'kr': {'de': 'Nein, davon habe ich noch nie gehört.',
                    'en': "No, this is the first time I've heard that.",
                    'fr': "Non, je n'en ai jamais entendu parler.",
                    'ja': 'いいえ、そのような話は初めて聞きます。',
                    'ko': '아니요, 그런 이야기는 처음 들어요.',
                    'pl': 'Nie, nigdy o tym nie słyszałem.',
                    'zh': '沒有，我第一次聽到這種說法。'},
             'vi': 'Chưa. Tôi chưa nghe điều đó bao giờ.',
             'who': 'B'},
            {'kr': {'de': 'Tatsächlich? In Psalm 37:29 sagt die Bibel Folgendes. Könnten Sie diesen Vers bitte kurz '
                          'vorlesen?',
                    'en': 'I see. The Bible tells us this at Psalm 37:29. Could you read it for me?',
                    'fr': 'Vraiment ? Voici ce que la Bible déclare en Psaume 37:29. Pourriez-vous lire ce verset ?',
                    'ja': 'そうですか。聖書の詩編37編29節にはこう書かれています。ここを読んでいただけますか。',
                    'ko': '그렇군요. 성경 시편 37편 29절 에서는 이렇게 알려줘요. 여기를 좀 읽어주시겠어요?',
                    'pl': 'Naprawdę? Zobaczmy, co mówi Biblia w Psalmie 37:29. Czy mógłbyś przeczytać ten werset?',
                    'zh': '原來如此。聖經詩篇37篇29節這樣告訴我們。可以請您讀一下這節經文嗎？'},
             'vi': 'Vậy à. Kinh Thánh Thi-thiên 37:29 cho biết như sau. Bạn có thể đọc giúp tôi câu này được không?',
             'who': 'A'},
            {'kr': {'de': '„Die Gerechten werden die Erde besitzen und für immer darauf leben.“',
                    'en': '"The righteous will possess the earth, and they will live forever on it."',
                    'fr': '« Les justes posséderont la terre et ils y vivront éternellement. »',
                    'ja': '「義人は地を所有し，とこしえにその上に住む」',
                    'ko': '“의로운 자들은 땅을 차지하고 거기서 영원히 살 것입니다.”',
                    'pl': '„Prawi posiądą ziemię i będą na niej żyć na zawsze.”',
                    'zh': '「義人必承受地土，永遠住在其上。」'},
             'vi': '“Người công chính sẽ hưởng trái đất và được sống trên đó mãi mãi”.',
             'who': 'B'},
            {'kr': {'de': 'Vielen Dank. Dieser Vers zeigt, dass Gott uns verspricht, für immer glücklich leben zu '
                          'können.',
                    'en': 'Thank you. This scripture shows us that God is promising that we can live happily forever.',
                    'fr': 'Merci. Ce verset montre que Dieu nous promet de vivre heureux pour toujours.',
                    'ja': 'ありがとうございます。この聖句から、神が私たちに永遠に幸せに生きられるよう約束してくださっていることが分かります。',
                    'ko': '고마워요. 이 말씀을 보면 하느님께서 우리가 영원히 행복하게 살 수 있도록 약속하고 계신다는 것을 알 수 있어요.',
                    'pl': 'Dziękuję. Ten werset pokazuje, że Bóg obiecuje nam szczęśliwe życie na zawsze.',
                    'zh': '謝謝您。這節經文讓我們看到，上帝應許我們可以永遠幸福地活著。'},
             'vi': 'Cảm ơn bạn. Qua câu này, chúng ta thấy rằng Đức Chúa Trời hứa cho chúng ta cơ hội sống hạnh phúc '
                   'mãi mãi.',
             'who': 'A'}],
  'number': 8,
  'subtitle': {'de': 'Die Zukunft (Bibeltext vorstellen)',
               'en': 'The Future (Scripture Introduction)',
               'fr': 'L’avenir (présentation d’un verset)',
               'ja': '将来（聖句紹介）',
               'ko': '미래(성구 소개)',
               'pl': 'Przyszłość (odczytanie wersetu)',
               'zh': '未來（經文介紹）'}},
 {'lines': [{'kr': {'de': 'Jehovas Zeugen bieten allen Menschen an, die Bibel kostenlos kennenzulernen.',
                    'en': "Jehovah's Witnesses offer free help to study the Bible.",
                    'fr': 'Les Témoins de Jéhovah proposent à tous de découvrir gratuitement la Bible.',
                    'ja': 'エホバの証人は無料で聖書を学ぶお手伝いをしています。',
                    'ko': '여호와의 증인은 무료로 성경을 공부해 보시도록 도와 드리고 있어요.',
                    'pl': 'Świadkowie Jehowy proponują wszystkim bezpłatny kurs poznawania Biblii.',
                    'zh': '耶和華見證人免費幫助大家學習聖經。'},
             'vi': 'Nhân Chứng Giê-hô-va mời mọi người tìm hiểu Kinh Thánh miễn phí.',
             'who': ''},
            {'kr': {'de': 'Dieses kurze Video zeigt, warum es sich lohnt, die Bibel kennenzulernen.',
                    'en': 'This short video shows why we should study the Bible.',
                    'fr': "Cette courte vidéo montre pourquoi il vaut la peine d'examiner la Bible.",
                    'ja': 'この短い動画は、私たちがなぜ聖書を学ぶべきかを教えてくれます。',
                    'ko': '이 짧은 동영상은 우리가 왜 성경을 배워야 하는지 그 이유를 보여줘요.',
                    'pl': 'Ten krótki film wyjaśnia, dlaczego warto poznawać Biblię.',
                    'zh': '這段短片會讓您瞭解，我們為什麼應該學習聖經。'},
             'vi': 'Video ngắn này cho thấy lý do vì sao chúng ta nên tìm hiểu Kinh Thánh.',
             'who': ''},
            {'kr': {'de': '(Video „Warum lohnt sich ein genaueres Hinsehen?“ ansehen)',
                    'en': '(Watch the video "Why Study the Bible?")',
                    'fr': '(Regarder la vidéo « Pourquoi étudier la Bible ? »)',
                    'ja': '（「なぜ聖書を調べるべきですか」の動画を見る）',
                    'ko': '(‘왜 성경을 알아봐야 합니까?’ 동영상을 본다)',
                    'pl': '(Obejrzenie filmu „Dlaczego warto studiować Biblię?”)',
                    'zh': '（觀看《為什麼要認識聖經？》的影片。）'},
             'vi': '(xem video ʻtại sao tìm hiểu Kinh Thánh?’)',
             'who': ''},
            {'kr': {'de': 'Wir können anhand dieses Buches Gespräche über die Bibel führen.',
                    'en': 'You can use this book to study the Bible.',
                    'fr': 'Nous pouvons utiliser ce livre pour discuter de la Bible.',
                    'ja': 'この本を使って聖書を学ぶことができます。',
                    'ko': '이 책을 사용해서 성경을 공부하실 수 있어요.',
                    'pl': 'Możemy skorzystać z tej książki do omawiania Biblii.',
                    'zh': '您可以使用這本書來學習聖經。'},
             'vi': 'Chúng ta có thể dùng quyển sách này để thảo luận.',
             'who': ''},
            {'kr': {'de': 'Ich biete kostenlose Bibelkurse für zu Hause an.',
                    'en': "I'm offering a free Bible study.",
                    'fr': 'Je propose des cours bibliques gratuits à domicile.',
                    'ja': '私は無料の聖書研究をご紹介しています。',
                    'ko': '저는 무료 성경 공부를 소개하고 있어요.',
                    'pl': 'Prowadzę bezpłatne domowe kursy biblijne.',
                    'zh': '我正在介紹免費的聖經研究課程。'},
             'vi': 'Tôi đang mời mọi người tìm hiểu Kinh Thánh miễn phí tại nhà.',
             'who': ''},
            {'kr': {'de': 'Wussten Sie schon? In nur wenigen Minuten können Sie Antworten auf wichtige Fragen finden.',
                    'en': 'Did you know that just a few minutes of your time can help you find answers to important '
                          'questions?',
                    'fr': 'Le saviez-vous ? En quelques minutes seulement, vous pouvez trouver des réponses à des '
                          'questions importantes.',
                    'ja': '数分お時間をいただくだけで、重要な質問への答えが分かるということをご存じですか。',
                    'ko': '몇 분만 시간을 내시면 중요한 질문에 대한 답을 알아보실 수 있다는 걸 아시나요?',
                    'pl': 'Czy wiesz, że w zaledwie kilka minut możesz znaleźć odpowiedzi na ważne pytania?',
                    'zh': '您知道嗎，只要花幾分鐘時間，就能找到重要問題的答案。'},
             'vi': 'Bạn có biết không? Chỉ trong vài phút, bạn có thể tìm được lời giải đáp cho một câu hỏi quan '
                   'trọng.',
             'who': ''},
            {'kr': {'de': 'Dieses Video zeigt, wie ein Bibelkurs abläuft.',
                    'en': 'This video shows how a Bible study is conducted.',
                    'fr': 'Cette vidéo montre comment se déroule un cours biblique.',
                    'ja': 'この動画は、聖書研究がどのように進められるかを示しています。',
                    'ko': '이 동영상은 성경 공부가 어떻게 진행되는지를 보여 줍니다.',
                    'pl': 'Ten film pokazuje, jak wygląda kurs biblijny.',
                    'zh': '這段影片會讓您瞭解聖經研究是如何進行的。'},
             'vi': 'Video này sẽ cho thấy buổi tìm hiểu Kinh Thánh diễn ra như thế nào.',
             'who': ''},
            {'kr': {'de': '(Video „Wie läuft ein Bibelkurs ab?“ ansehen)',
                    'en': '(Watch the video "How Is a Bible Study Conducted?")',
                    'fr': '(Regarder la vidéo « Comment se passe un cours biblique ? »)',
                    'ja': '（「聖書研究はどのように行われますか」の動画を見る）',
                    'ko': '(‘성경 공부는 어떻게 진행됩니까?’ 동영상을 본다)',
                    'pl': '(Obejrzenie filmu „Jak wygląda kurs biblijny?”)',
                    'zh': '（觀看《聖經研究是怎麼進行的？》的影片。）'},
             'vi': '(xem video ʻBuổi tìm hiểu Kinh Thánh diễn ra như thế nào?’)',
             'who': ''},
            {'kr': {'de': 'Möchten Sie die Bibel gemeinsam mit mir kennenlernen?',
                    'en': 'Would you like to study the Bible with me?',
                    'fr': 'Aimeriez-vous découvrir la Bible avec moi ?',
                    'ja': '私と一緒に聖書を学んでみませんか。',
                    'ko': '저와 성경을 공부해 보지 않으시겠어요?',
                    'pl': 'Czy chciałbyś poznawać ze mną Biblię?',
                    'zh': '您願不願意跟我一起學習聖經呢？'},
             'vi': 'Bạn có muốn tìm hiểu Kinh Thánh với tôi không?',
             'who': ''}],
  'number': 9,
  'subtitle': {'de': 'Einen Bibelkurs anbieten (Video vorstellen)',
               'en': 'How to Offer a Bible Study (Video Introduction)',
               'fr': 'Comment proposer un cours biblique (présentation d’une vidéo)',
               'ja': '聖書研究の勧め方（動画紹介）',
               'ko': '성서연구 제안방법(동영상 소개)',
               'pl': 'Jak zaproponować kurs biblijny (wprowadzenie filmu)',
               'zh': '提議聖經研究的方法（影片介紹）'}},
 {'lines': [{'kr': {'de': 'Schauen wir uns gemeinsam Punkt 3 an. Lesen wir dazu Psalm 119:105.',
                    'en': "Let's look at point 3 together. Now let's read Psalm 119:105.",
                    'fr': 'Regardons ensemble le point 3. Lisons maintenant Psaume 119:105.',
                    'ja': '一緒にポイント3を見てみましょう。では詩編119編105節を読んでみます。',
                    'ko': '우리 함께 3번 요점을 살펴봐요. 이제 시편 119:105을 읽어 볼게요.',
                    'pl': 'Przyjrzyjmy się wspólnie punktowi 3. Przeczytajmy teraz Psalm 119:105.',
                    'zh': '我們一起來看看第3點。現在我們來讀一下詩篇119:105。'},
             'vi': 'Chúng ta cùng xem xét điểm số 3 nhé. Chúng ta hãy đọc Thi-thiên 119:105.',
             'who': 'A'},
            {'kr': {'de': '(Liest vor.)',
                    'en': '(Read)',
                    'fr': '(Lit.)',
                    'ja': '（読む）',
                    'ko': '(읽음)',
                    'pl': '(Czyta).',
                    'zh': '（讀出）'},
             'vi': '(Đọc.)',
             'who': 'B'},
            {'kr': {'de': 'Wie dachte der Schreiber dieses Psalms über die Bibel?',
                    'en': 'What did the writer of this psalm think about the Bible?',
                    'fr': "Que pensait l'auteur de ce psaume à propos de la Bible ?",
                    'ja': 'この詩を書いた人は聖書についてどう考えていましたか。',
                    'ko': '이 시를 지은 사람은 성경에 대해 어떻게 생각했나요?',
                    'pl': 'Co autor tego psalmu myślał o Biblii?',
                    'zh': '這首詩的作者對聖經有什麼看法呢？'},
             'vi': 'Người viết câu này nghĩ gì về Kinh Thánh?',
             'who': 'A'},
            {'kr': {'de': 'Der Schreiber empfand die Bibel als eine Leuchte und ein Licht für uns.',
                    'en': 'I think the Bible is a lamp and a light to us.',
                    'fr': 'Il pensait que la Bible est une lampe et une lumière pour nous.',
                    'ja': '聖書は私たちにとってともし火であり、光だと思います。',
                    'ko': '성경이 우리에게 등불과 빛이라고 생각해요.',
                    'pl': 'Uważał, że Biblia jest dla nas lampą i światłem.',
                    'zh': '我覺得聖經對我們來說是一盞燈，也是一道光。'},
             'vi': 'Người viết nghĩ rằng Kinh Thánh là ngọn đèn và ánh sáng cho chúng ta.',
             'who': 'B'},
            {'kr': {'de': 'Ganz genau! Was denken Sie über die Bibel?',
                    'en': "That's right! What do you think about the Bible?",
                    'fr': "C'est tout à fait ça ! Et vous, que pensez-vous de la Bible ?",
                    'ja': 'そうですね！あなたは聖書についてどう思いますか？',
                    'ko': '맞아요! 당신은 성경에 대해 어떻게 생각하나요?',
                    'pl': 'Dokładnie tak! A ty co myślisz o Biblii?',
                    'zh': '沒錯！你覺得聖經怎麼樣呢？'},
             'vi': 'Đúng rồi! Bạn nghĩ sao về Kinh Thánh?',
             'who': 'A'},
            {'kr': {'de': 'Ich denke auch, dass die Bibel uns Orientierung geben kann.',
                    'en': 'I also think the Bible can guide us.',
                    'fr': 'Je pense aussi que la Bible peut nous guider.',
                    'ja': '私も聖書は私たちを導いてくれると思います。',
                    'ko': '저도 성경이 우리를 인도해 줄 수 있다고 생각해요.',
                    'pl': 'Też uważam, że Biblia może być dla nas przewodnikiem.',
                    'zh': '我也覺得聖經能夠指引我們。'},
             'vi': 'Tôi cũng nghĩ là Kinh Thánh có thể hướng dẫn chúng ta.',
             'who': 'B'},
            {'kr': {'de': 'Sehr gut. Schauen wir uns diese Abbildung an. Was ist auf diesem Bild zu sehen?',
                    'en': 'Very good. Please take a look at this picture. What scene is shown in this picture?',
                    'fr': 'Très bien. Regardez cette illustration. Que se passe-t-il sur cette image ?',
                    'ja': 'とてもいいですね。この挿絵をご覧ください。この挿絵はどんな場面ですか？',
                    'ko': '아주 좋아요. 이 삽화를 한번 보세요. 이 삽화는 어떤 장면인가요?',
                    'pl': 'Bardzo dobrze. Spójrz na tę ilustrację. Co na niej widać?',
                    'zh': '非常好。請看看這幅插圖，這幅插圖是什麼場景呢？'},
             'vi': 'Rất tốt. Hãy xem hình này nhé. Chuyện gì đang diễn ra trong hình này?',
             'who': 'A'},
            {'kr': {'de': 'Jemand geht nachts auf einem dunklen Weg und leuchtet sich mit einer Taschenlampe den Weg '
                          'aus. Die Bibel ist wie so eine Taschenlampe.',
                    'en': 'A person is walking on a dark road at night, shining a flashlight to light the way. The '
                          'Bible is like that flashlight.',
                    'fr': "Une personne marche sur une route sombre la nuit et s'éclaire avec une lampe de poche. La "
                          'Bible est comme cette lampe.',
                    'ja': 'ある人が夜、暗い道を歩きながら懐中電灯で道を照らしています。聖書も懐中電灯のようなものです。',
                    'ko': '어떤 사람이 밤에 어두운 길을 걸어가면서 손전등으로 길을 비추고 있어요. 성경도 손전등과 같아요.',
                    'pl': 'Człowiek idzie nocą ciemną drogą i oświetla sobie drogę latarką. Biblia jest jak ta lampa.',
                    'zh': '有一個人在夜晚走在黑暗的路上，用手電筒照亮道路。聖經就像手電筒一樣。'},
             'vi': 'Một người đang đi bộ trên con đường tối vào ban đêm và dùng đèn pin để soi đường. Kinh Thánh cũng '
                   'giống như một chiếc đèn pin.',
             'who': 'B'},
            {'kr': {'de': 'Wunderbar! Gehen wir zum nächsten Punkt über.',
                    'en': "Excellent! Let's move on to the next point.",
                    'fr': 'Excellent ! Passons au point suivant.',
                    'ja': 'すばらしいです！次のポイントに進みましょう。',
                    'ko': '훌륭해요! 다음 요점으로 넘어가 볼게요.',
                    'pl': 'Świetnie! Przejdźmy do następnego punktu.',
                    'zh': '太好了！我們來看下一個要點吧。'},
             'vi': 'Tuyệt vời! Chúng ta sang điểm tiếp theo nhé.',
             'who': 'A'}],
  'number': 10,
  'subtitle': {'de': 'Einen Bibelkurs leiten („Glücklich – für immer“, Lektion 1, Punkt 3)',
               'en': 'Conducting a Bible Study (행누, Lesson 1, Point 3)',
               'fr': 'Diriger un cours biblique (« Vivez pour toujours ! », leçon 1, point 3)',
               'ja': '聖書研究の進め方（행누 第1課 ポイント3）',
               'ko': '성서연구 사회(행누 1과 요점3)',
               'pl': 'Prowadzenie kursu biblijnego (broszura/książka „Już zawsze ciesz się życiem!”, lekcja 1, punkt '
                     '3)',
               'zh': '聖經研究示範（행누 第1課 要點3）'}},
 {'lines': [{'kr': {'de': 'Haben Sie diesen Sonntagnachmittag Zeit? Ich möchte Sie herzlich zu einer Zusammenkunft im '
                          'Königreichssaal einladen.',
                    'en': "Do you have time this Sunday afternoon? I'd like to invite you to a meeting held at the "
                          'Kingdom Hall.',
                    'fr': "Avez-vous un moment ce dimanche après-midi ? J'aimerais vous inviter à une réunion à la "
                          'Salle du Royaume.',
                    'ja': '今週の日曜日の午後、お時間はありますか？王国会館で開かれる集会にご招待したいのですが。',
                    'ko': '이번 일요일 오후에 시간 있어요? 왕국회관에서 열리는 집회에 초대하고 싶어요.',
                    'pl': 'Czy masz czas w tę niedzielę po południu? Chciałbym zaprosić cię na zebranie do Sali '
                          'Królestwa.',
                    'zh': '這個星期天下午你有時間嗎？我想邀請你參加在王國聚會所舉行的聚會。'},
             'vi': 'Chiều Chủ Nhật này bạn có rảnh không? Tôi muốn mời bạn tham dự buổi nhóm họp tại Phòng Nước Trời.',
             'who': 'A'},
            {'kr': {'de': 'Zu einer Zusammenkunft?',
                    'en': 'A meeting?',
                    'fr': 'Une réunion ?',
                    'ja': '集会ですか？',
                    'ko': '집회요?',
                    'pl': 'Na zebranie?',
                    'zh': '聚會嗎？'},
             'vi': 'Nhóm họp hả?',
             'who': 'B'},
            {'kr': {'de': 'Ja. Die Zusammenkünfte werden auf Vietnamesisch abgehalten. Jeder ist herzlich willkommen '
                          'und der Eintritt ist frei. Wollen wir uns kurz dieses Video ansehen? (Das erwartet Sie in '
                          'einem Königreichssaal)',
                    'en': "Yes, it's a meeting held in Vietnamese. Anyone can attend for free. Shall we watch this "
                          'video together? (What is a Kingdom Hall?)',
                    'fr': "Oui. Les réunions se déroulent en vietnamien. Tout le monde peut y assister et l'entrée est "
                          'gratuite. Regarderons-nous cette vidéo ensemble ? (Que se passe-t-il dans une Salle du '
                          'Royaume ?)',
                    'ja': 'はい。ベトナム語で行われる集会です。誰でも無料で参加できます。この動画を一緒に見てみましょうか。（王国会館とはどんな所ですか？）',
                    'ko': '네. 베트남어로 제공되는 집회예요. 누구나 무료로 참석할 수 있어요. 이 동영상을 같이 볼까요. (왕국회관은 어떤 곳 입니까?)',
                    'pl': 'Tak. Zebrania odbywają się w języku wietnamskim. Każdy może przyjść, a wstęp jest '
                          'bezpłatny. Czy obejrzymy razem ten film? (Jak wyglądają zebrania w Sali Królestwa?)',
                    'zh': '是的，這是用越南語進行的聚會，任何人都可以免費參加。我們一起看看這段影片好嗎？（王國聚會所是什麼樣的地方？）'},
             'vi': 'Dạ. Các buổi nhóm họp được diễn ra bằng tiếng Việt Nam. Ai muốn tham gia cũng đến được và vào cửa '
                   'miễn phí. Tôi mời bạn cùng xem video này. (Điều gì diễn ra tại Phòng Nước Trời?)',
             'who': 'A'},
            {'kr': {'de': 'Um wie viel Uhr beginnt die Zusammenkunft?',
                    'en': 'What time is the meeting?',
                    'fr': 'À quelle heure a lieu la réunion ?',
                    'ja': '集会は何時にありますか？',
                    'ko': '집회가 몇 시에 있나요?',
                    'pl': 'O której godzinie odbywa się zebranie?',
                    'zh': '聚會是幾點開始呢？'},
             'vi': 'Mấy giờ có nhóm họp?',
             'who': 'B'},
            {'kr': {'de': 'Die Zusammenkunft beginnt um 16 Uhr.',
                    'en': 'It starts at 4 p.m.',
                    'fr': 'La réunion commence à 16 heures.',
                    'ja': '午後4時に始まります。',
                    'ko': '오후 4시에 시작해요.',
                    'pl': 'Zebranie zaczyna się o 16:00.',
                    'zh': '下午4點開始。'},
             'vi': 'Buổi nhóm họp bắt đầu lúc bốn giờ chiều.',
             'who': 'A'}],
  'number': 11,
  'subtitle': {'de': 'Einladung zu den Zusammenkünften',
               'en': 'Meeting Invitation',
               'fr': 'Invitation aux réunions',
               'ja': '集会へのご招待',
               'ko': '집회 초대',
               'pl': 'Zaproszenie na zebranie',
               'zh': '聚會邀請'}}]

KINGDOM_SONGS = [
 {'number': 12,
  'title_kr': {'ko': '위대한 하느님, 여호와',
               'zh': '偉大的上帝，耶和華',
               'en': 'Great God, Jehovah',
               'ja': '偉大な神、エホバ'},
  'title_vi': 'Đức Giê-hô-va, ngài thật vĩ đại',
  'scripture': 'Xuất Ai Cập 34:6, 7',
  'verses': [[{'vi': 'Hỡi Cha Giê-hô-va, đấng cai trị tối cao,', 'kr': {'ko': '지존하신 통치자, 여호와 아버지시여,',
                                                                       'zh': '至高的統治者，耶和華天父啊，',
                                                                       'en': 'O Father Jehovah, the Sovereign Most High,',
                                                                       'ja': 'いと高き支配者エホバなる父よ、'}},
             {'vi': 'ngài yêu thương, công chính vô cùng,', 'kr': {'ko': '당신은 사랑과 공의가 한없으시며,',
                                                                   'zh': '你充滿慈愛與公義，',
                                                                   'en': 'you are boundless in love and righteousness,',
                                                                   'ja': 'あなたは限りない愛と義に満ちておられます。'}},
             {'vi': 'được ca khen, tôn vinh trên hết.', 'kr': {'ko': '그 무엇보다 찬양과 영광을 받으실 분입니다.',
                                                               'zh': '應當受到至高的讚美和榮耀。',
                                                               'en': 'You deserve praise and glory above all else.',
                                                               'ja': '何よりも賛美と栄光を受けるにふさわしい方です。'}},
             {'vi': 'Lối Cha tuyệt hảo thay với bao điều sáng khôn.', 'kr': {'ko': '아버지의 길은 완전하고 지혜로 가득합니다.',
                                                                             'zh': '天父的道路完美無瑕，充滿智慧。',
                                                                             'en': 'Your ways are perfect, full of wisdom.',
                                                                             'ja': '父の道は完全で、知恵に満ちています。'}},
             {'vi': 'Ngài là Vua vinh hiển, quyền năng.', 'kr': {'ko': '당신은 영광스럽고 능력 있는 왕이십니다.',
                                                                 'zh': '你是榮耀又大能的君王。',
                                                                 'en': 'You are the glorious and mighty King.',
                                                                 'ja': 'あなたは栄光に満ちた、力強い王です。'}}],
            [{'vi': 'Chúng con thật biết ơn bởi Cha hằng xót thương.', 'kr': {'ko': '늘 자비를 베푸시는 아버지께 참으로 감사드립니다.',
                                                                              'zh': '我們衷心感謝天父不斷施予的憐憫。',
                                                                              'en': 'We are truly grateful for your constant mercy.',
                                                                              'ja': '絶えず憐れみを示してくださる父に、心から感謝します。'}},
             {'vi': 'Ngài nghiêng tai nghe tiếng kêu cầu', 'kr': {'ko': '당신은 우리의 부르짖음에 귀를 기울이시고',
                                                                  'zh': '你側耳聆聽我們的呼求，',
                                                                  'en': 'You bend your ear to hear our cries',
                                                                  'ja': 'あなたは私たちの叫びに耳を傾け'}},
             {'vi': 'và gần bên quan tâm, chăm sóc.', 'kr': {'ko': '가까이 계시며 돌보아 주십니다.',
                                                             'zh': '親近我們，眷顧看顧我們。',
                                                             'en': 'and stay close, caring for us.',
                                                             'ja': 'そばにいて世話をしてくださいます。'}},
             {'vi': 'Chúa khuyên dạy chúng con bước theo đường thẳng ngay.', 'kr': {'ko': '주는 우리가 올바른 길로 걷도록 훈계해 주십니다.',
                                                                                    'zh': '主教導我們走正直的道路。',
                                                                                    'en': 'The Lord instructs us to walk in the straight path.',
                                                                                    'ja': '主は私たちがまっすぐな道を歩むよう教え諭してくださいます。'}},
             {'vi': 'Hằng ngày Cha nâng đỡ, ủi an.', 'kr': {'ko': '아버지께서는 날마다 우리를 붙들어 주시고 위로해 주십니다.',
                                                            'zh': '天父天天扶持我們，安慰我們。',
                                                            'en': 'Every day our Father upholds and comforts us.',
                                                            'ja': '父は日々、私たちを支え、慰めてくださいます。'}}],
            [{'vi': 'Chúng con thành kính dâng tiếng ca ngợi đến Cha.', 'kr': {'ko': '우리는 경건한 마음으로 아버지께 찬양을 드립니다.',
                                                                               'zh': '我們懷著虔敬的心，向天父獻上讚美。',
                                                                               'en': 'We reverently offer up praise to our Father.',
                                                                               'ja': '私たちは敬虔な思いをもって、父に賛美をささげます。'}},
             {'vi': 'Bầu trời rao ra hiển vinh ngài,', 'kr': {'ko': '하늘은 당신의 영광을 선포하며,',
                                                              'zh': '諸天宣揚你的榮耀，',
                                                              'en': 'The heavens declare your glory,',
                                                              'ja': '天はあなたの栄光を宣言し'}},
             {'vi': 'vật muôn nơi tôn vinh danh thánh.', 'kr': {'ko': '만물이 곳곳에서 그 거룩한 이름을 영예롭게 합니다.',
                                                                'zh': '萬物處處尊崇你的聖名。',
                                                                'en': 'all creation everywhere honors your holy name.',
                                                                'ja': '万物はいたるところであなたの聖なる名をたたえます。'}},
             {'vi': 'Suốt trong đời chúng con hát khen Giê-hô-va,', 'kr': {'ko': '우리는 평생토록 여호와를 찬양하는 노래를 부르며,',
                                                                           'zh': '我們一生都要歌頌耶和華，',
                                                                           'en': 'All our life we will sing praises to Jehovah,',
                                                                           'ja': '私たちは生涯を通してエホバを賛美して歌い'}},
             {'vi': 'nguyện xin Cha nghe tiếng ngợi ca.', 'kr': {'ko': '아버지께서 우리의 찬양 소리를 들어 주시기를 기도합니다.',
                                                                 'zh': '願天父垂聽我們的頌讚之聲。',
                                                                 'en': 'We pray that our Father will hear our song of praise.',
                                                                 'ja': '父が私たちの賛美の声を聞いてくださるよう願います。'}}]
             ]},
 {'number': 18,
  'title_kr': {'ko': '대속 마련에 감사합니다',
               'zh': '感謝救贖的安排',
               'en': 'Thankful for the Ransom Arrangement',
               'ja': '贖いの備えに感謝します'},
  'title_vi': 'Biết ơn về giá chuộc',
  'scripture': 'Lu-ca 22:20',
  'verses': [[{'vi': 'Mọi người hôm nay đứng trước', 'kr': {'ko': '오늘 우리 모두는',
                                                           'zh': '今天，我們眾人站在',
                                                           'en': 'Today we all stand before',
                                                           'ja': '今日、私たちは皆'}},
             {'vi': 'ngôi Cha uy nghi, cao trọng.', 'kr': {'ko': '위엄 있고 존귀하신 아버지의 보좌 앞에 서 있습니다.',
                                                           'zh': '威嚴尊貴的天父寶座前。',
                                                           'en': 'your majestic, exalted throne, O Father.',
                                                           'ja': '威厳に満ちた尊い父の御座の前に立っています。'}},
             {'vi': 'Tạ ơn Chúa đã ban Con một', 'kr': {'ko': '독생자를 주신 주께 감사드립니다.',
                                                        'zh': '感謝主賜下獨生子，',
                                                        'en': 'We thank the Lord for giving his only Son',
                                                        'ja': 'ひとり子を与えてくださった主に感謝します。'}},
             {'vi': 'chịu tội thay cho chúng con.', 'kr': {'ko': '그분은 우리를 위해 죄를 대신 짊어지셨습니다.',
                                                           'zh': '為我們代罪受苦。',
                                                           'en': 'to bear our sin in our place.',
                                                           'ja': '私たちの代わりに罪を負ってくださいました。'}},
             {'vi': 'Tình yêu thương Cha quá lớn!', 'kr': {'ko': '아버지의 사랑은 얼마나 크신지요!',
                                                           'zh': '天父的愛是何等浩大！',
                                                           'en': "How great is the Father's love!",
                                                           'ja': '父の愛はなんと大きいことでしょう。'}},
             {'vi': 'Chúng con được Cha thương xót,', 'kr': {'ko': '우리는 아버지의 자비를 입어',
                                                             'zh': '我們蒙天父憐憫，',
                                                             'en': "We have received the Father's mercy,",
                                                             'ja': '私たちは父の憐れみを受け'}},
             {'vi': 'sống trong hy vọng, hướng tới tương lai', 'kr': {'ko': '소망 안에서 살아가며 미래를 향해 나아갑니다.',
                                                                      'zh': '活在盼望之中，邁向未來，',
                                                                      'en': 'living in hope, looking toward a future',
                                                                      'ja': '希望のうちに生き、未来へと向かっています。'}},
             {'vi': 'đầy ân phước dư tràn', 'kr': {'ko': '그 미래는 넘치는 축복으로 가득합니다.',
                                                   'zh': '那充滿豐盛祝福的未來。',
                                                   'en': 'overflowing with rich blessings.',
                                                   'ja': 'それは豊かな祝福にあふれています。'}},
             {'vi': '(ĐIỆP KHÚC)', 'kr': {'ko': '(후렴)', 'zh': '（副歌）', 'en': '(CHORUS)', 'ja': '（コーラス）'}},
             {'vi': 'Nhờ nơi huyết báu Con một của Cha,', 'kr': {'ko': '아버지의 독생자가 흘리신 보배로운 피로 말미암아,',
                                                                 'zh': '藉著天父獨生子的寶血，',
                                                                 'en': "Through the precious blood of the Father's only Son,",
                                                                 'ja': '父のひとり子の尊い血のゆえに'}},
             {'vi': 'giờ ai tin Chúa sẽ được cứu chuộc.', 'kr': {'ko': '이제 믿는 사람은 누구나 구속받게 됩니다.',
                                                                 'zh': '現在凡信主的人都必得救贖。',
                                                                 'en': 'now everyone who believes in the Lord will be redeemed.',
                                                                 'ja': '今、主を信じる人は皆、贖われます。'}},
             {'vi': 'Một lòng tôn kính,', 'kr': {'ko': '우리는 한마음으로 경의를 표하며,',
                                                 'zh': '我們一心敬重，',
                                                 'en': 'With one heart, in reverence,',
                                                 'ja': '私たちは心を一つにして敬い'}},
             {'vi': 'chúng con ca khen danh ngài đời đời không thôi.', 'kr': {'ko': '영원토록 그치지 않고 그분의 이름을 찬양합니다.',
                                                                              'zh': '永永遠遠不停地頌讚他的名。',
                                                                              'en': 'we will praise his name forever without ceasing.',
                                                                              'ja': '永遠に絶えることなく、その名を賛美します。'}}],
            [{'vi': 'Vì yêu thương nên chính Đấng', 'kr': {'ko': '사랑으로 말미암아',
                                                           'zh': '出於愛，',
                                                           'en': 'Out of love,',
                                                           'ja': '愛のゆえに'}},
             {'vi': 'Ki-tô hy sinh thân mình,', 'kr': {'ko': '그리스도께서는 자신의 몸을 바치셨고,',
                                                       'zh': '基督獻上自己的身體，',
                                                       'en': 'Christ sacrificed his own body,',
                                                       'ja': 'キリストはご自分の体を犠牲にし'}},
             {'vi': 'chịu đau đớn, chết cho nhân loại,', 'kr': {'ko': '고통을 당하시고 인류를 위해 죽으셨으며,',
                                                                'zh': '為全人類受苦至死，',
                                                                'en': 'suffering and dying for mankind,',
                                                                'ja': '人類のために苦しみを受けて死なれました。'}},
             {'vi': 'đẩy lùi đêm đen tối tăm.', 'kr': {'ko': '어두운 밤을 물리치셨습니다.',
                                                       'zh': '驅散了黑暗的長夜。',
                                                       'en': 'driving back the dark night.',
                                                       'ja': '暗い夜を退けてくださいました。'}},
             {'vi': 'Nhờ ngài, mai đây chết chóc', 'kr': {'ko': '그분 덕분에 머지않아 죽음은',
                                                          'zh': '因著他，將來死亡',
                                                          'en': 'Because of him, death will one day',
                                                          'ja': '彼のおかげで、やがて死は'}},
             {'vi': 'sẽ luôn chìm trong quên lãng.', 'kr': {'ko': '영원히 잊혀지고 말 것입니다.',
                                                            'zh': '將永遠被遺忘。',
                                                            'en': 'be forever forgotten.',
                                                            'ja': '永遠に忘れ去られるでしょう。'}},
             {'vi': 'Chúng con vui mừng, háo hức trông mong', 'kr': {'ko': '우리는 기쁘고 설레는 마음으로',
                                                                     'zh': '我們滿心歡喜，殷切期待',
                                                                     'en': 'We rejoice, eagerly looking forward',
                                                                     'ja': '私たちは喜び、心を躍らせながら'}},
             {'vi': 'nhận sự sống muôn đời.', 'kr': {'ko': '영원한 생명을 받을 날을 고대합니다.',
                                                     'zh': '得享永遠的生命。',
                                                     'en': 'to receiving everlasting life.',
                                                     'ja': '永遠の命を受けることを待ち望んでいます。'}},
             {'vi': '(ĐIỆP KHÚC)', 'kr': {'ko': '(후렴)', 'zh': '（副歌）', 'en': '(CHORUS)', 'ja': '（コーラス）'}},
             {'vi': 'Nhờ nơi huyết báu Con một của Cha,', 'kr': {'ko': '아버지의 독생자가 흘리신 보배로운 피로 말미암아,',
                                                                 'zh': '藉著天父獨生子的寶血，',
                                                                 'en': "Through the precious blood of the Father's only Son,",
                                                                 'ja': '父のひとり子の尊い血のゆえに'}},
             {'vi': 'giờ ai tin Chúa sẽ được cứu chuộc.', 'kr': {'ko': '이제 믿는 사람은 누구나 구속받게 됩니다.',
                                                                 'zh': '現在凡信主的人都必得救贖。',
                                                                 'en': 'now everyone who believes in the Lord will be redeemed.',
                                                                 'ja': '今、主を信じる人は皆、贖われます。'}},
             {'vi': 'Một lòng tôn kính,', 'kr': {'ko': '우리는 한마음으로 경의를 표하며,',
                                                 'zh': '我們一心敬重，',
                                                 'en': 'With one heart, in reverence,',
                                                 'ja': '私たちは心を一つにして敬い'}},
             {'vi': 'chúng con ca khen danh ngài đời đời không thôi.', 'kr': {'ko': '영원토록 그치지 않고 그분의 이름을 찬양합니다.',
                                                                              'zh': '永永遠遠不停地頌讚他的名。',
                                                                              'en': 'we will praise his name forever without ceasing.',
                                                                              'ja': '永遠に絶えることなく、その名を賛美します。'}}]
             ]},
 {'number': 46,
  'title_kr': {'ko': '여호와여 감사합니다',
               'zh': '感謝你，耶和華',
               'en': 'Thank You, Jehovah',
               'ja': 'エホバ、感謝します'},
  'title_vi': 'Cảm tạ Cha Giê-hô-va',
  'scripture': '1 Tê-sa-lô-ni-ca 5:18',
  'verses': [[{'vi': 'Lạy Cha Giê-hô-va, xin cám ơn Cha đêm ngày,', 'kr': {'ko': '여호와 아버지, 밤낮으로 감사드립니다,',
                                                                          'zh': '耶和華天父啊，我們晝夜感謝你，',
                                                                          'en': 'Father Jehovah, we thank you day and night,',
                                                                          'ja': 'エホバなる父よ、昼も夜も感謝します。'}},
             {'vi': 'sự sáng Cha chiếu rọi trên chúng con rạng ngời.', 'kr': {'ko': '아버지의 빛이 우리 위에 찬란히 비춥니다.',
                                                                              'zh': '你的光輝燦爛地照耀在我們身上。',
                                                                              'en': 'your light shines brightly upon us.',
                                                                              'ja': 'あなたの光が私たちの上に輝いています。'}},
             {'vi': 'Tạ ơn Cha hết lòng vì phước ân kêu cầu ngài,', 'kr': {'ko': '당신을 부를 수 있는 은혜를 진심으로 감사드리며,',
                                                                           'zh': '我們全心感謝你賜下呼求你的恩典，',
                                                                           'en': 'We thank you with all our heart for the privilege of calling on you,',
                                                                           'ja': 'あなたを呼び求められる恵みに心から感謝し'}},
             {'vi': 'hầu chúng con cùng trao mọi lo lắng cho ngài.', 'kr': {'ko': '우리의 모든 염려를 당신께 맡길 수 있게 하십니다.',
                                                                            'zh': '好讓我們把一切憂慮都交託給你。',
                                                                            'en': 'so that we may cast all our worries upon you.',
                                                                            'ja': 'すべての思い煩いをあなたに委ねることができます。'}}],
            [{'vi': 'Lạy Cha Giê-hô-va, xin cám ơn ban Con một,', 'kr': {'ko': '여호와 아버지, 독생자를 주셔서 감사합니다,',
                                                                         'zh': '耶和華天父啊，感謝你賜下獨生子，',
                                                                         'en': 'Father Jehovah, thank you for giving your only Son,',
                                                                         'ja': 'エホバなる父よ、ひとり子を与えてくださり感謝します。'}},
             {'vi': 'do đức tin vững mạnh, nay thắng thế gian rồi.', 'kr': {'ko': '굳센 믿음으로 이제 세상을 이기셨습니다.',
                                                                            'zh': '他憑著堅定的信心，如今已經勝過了世界。',
                                                                            'en': 'through steadfast faith, he has now overcome the world.',
                                                                            'ja': '揺るがぬ信仰によって、今や世に打ち勝たれました。'}},
             {'vi': 'Tạ ơn Cha dắt dìu, dạy chúng con theo đường ngài', 'kr': {'ko': '우리를 인도하시고 당신의 길을 따르도록 가르치시니 감사합니다.',
                                                                               'zh': '感謝天父引導我們，教導我們遵行你的道路，',
                                                                               'en': 'We thank you for leading us and teaching us to follow your way,',
                                                                               'ja': '私たちを導き、あなたの道に従うよう教えてくださり感謝します。'}},
             {'vi': 'hầu chúng con làm theo lời thề ước dâng mình.', 'kr': {'ko': '우리가 헌신 서약을 지켜 나갈 수 있게 하십니다.',
                                                                            'zh': '好使我們履行獻身的誓約。',
                                                                            'en': 'so that we may fulfill our vow of dedication.',
                                                                            'ja': '献身の誓いを果たすことができるようにしてくださいます。'}}],
            [{'vi': 'Lạy Cha Giê-hô-va, xin cám ơn ban vinh dự', 'kr': {'ko': '여호와 아버지, 영예를 주셔서 감사합니다',
                                                                        'zh': '耶和華天父啊，感謝你賜下尊榮，',
                                                                        'en': 'Father Jehovah, thank you for the honor you give us',
                                                                        'ja': 'エホバなる父よ、光栄を与えてくださり感謝します。'}},
             {'vi': 'rao báo danh thánh ngài, chân lý cho bao người.', 'kr': {'ko': '당신의 거룩한 이름과 진리를 많은 사람에게 전하게 하십니다.',
                                                                              'zh': '讓我們向眾人宣揚你的聖名和真理。',
                                                                              'en': 'to proclaim your holy name and the truth to many people.',
                                                                              'ja': '聖なる名と真理を多くの人に宣べ伝えられるようにしてくださいます。'}},
             {'vi': 'Tạ ơn Cha xóa sạch mọi khổ đau mai không còn,', 'kr': {'ko': '머지않아 모든 고통을 깨끗이 없애 주실 것을 감사드리며,',
                                                                            'zh': '感謝天父，將來要徹底除去一切痛苦，',
                                                                            'en': 'We thank you that soon all suffering will be wiped away,',
                                                                            'ja': 'やがてすべての苦しみを完全に取り除いてくださることに感謝し'}},
             {'vi': 'và Nước trên trời mang lại ân phước muôn đời.', 'kr': {'ko': '하늘 왕국이 영원한 축복을 가져다줄 것입니다.',
                                                                            'zh': '天上的王國將帶來永遠的祝福。',
                                                                            'en': 'and the Kingdom in heaven will bring everlasting blessings.',
                                                                            'ja': '天の王国が永遠の祝福をもたらしてくれます。'}}]
             ]}]

PRAYER_TEMPLATE = {'lines': [{'kr': {'de': 'Lieber Vater Jehova,',
                   'en': 'Dear Father Jehovah,',
                   'fr': 'Cher Père Jéhovah,',
                   'ja': '天の父エホバ、',
                   'ko': '여호와 아버지께',
                   'pl': 'Drogi Ojcze Jehowo,',
                   'zh': '親愛的天父耶和華，'},
            'vi': 'Lạy Cha Giê-hô-va,'},
           {'kr': {'de': 'wir danken dir, dass wir zusammenkommen können, um mehr über dein Wort zu lernen und die '
                         'vietnamesische Sprache zu vertiefen.',
                   'en': 'Thank you for allowing us to gather together to learn more about your Word and to study '
                         'Vietnamese.',
                   'fr': 'nous te remercions de nous permettre de nous réunir pour en apprendre davantage sur ta '
                         'Parole et pour étudier le vietnamien.',
                   'ja': '私たちが共に集まり、あなたの言葉についてもっと学び、ベトナム語を学ぶことができるようにしてくださり、感謝いたします。',
                   'ko': '저희가 모여서 아버지의 말씀에 대하여 더 배우고, 베트남어를 배우도록 도와 주셔서 감사합니다.',
                   'pl': 'dziękujemy Ci, że możemy się spotkać, aby uczyć się o Twoim Słowie i uczyć się języka '
                         'wietnamskiego.',
                   'zh': '感謝你讓我們聚在一起，更深入地學習你的話語，也學習越南語。'},
            'vi': 'Xin cám ơn Cha giúp chúng con nhóm lại để học thêm về lời Cha và học tiếng Việt.'},
           {'kr': {'de': 'Wir danken dir für das Leben, das du uns geschenkt hast.',
                   'en': 'We thank you for the life you have given us.',
                   'fr': 'Nous te remercions pour la vie que tu nous as donnée.',
                   'ja': 'あなたが私たちに与えてくださった命に感謝いたします。',
                   'ko': '저희는 아버지께서 저희에게 주신 생명에 대해 감사합니다.',
                   'pl': 'Dziękujemy Ci za życie, które nam dałeś.',
                   'zh': '我們感謝你賜給我們生命。'},
            'vi': 'Chúng con cám ơn Cha về sự sống mà Cha ban cho chúng con.'},
           {'kr': {'de': 'Wir danken dir, dass wir dein Wort studieren dürfen.',
                   'en': 'We thank you for allowing us to study your Word.',
                   'fr': "Nous te remercions de nous permettre d'étudier ta Parole.",
                   'ja': 'あなたの言葉を研究することをお許しくださり、感謝いたします。',
                   'ko': '저희는 아버지께서 저희가 아버지의 말씀을 공부하도록 허락해 주셔서 감사합니다.',
                   'pl': 'Dziękujemy Ci, że możemy studiować Twoje Słowo.',
                   'zh': '我們感謝你容許我們研讀你的話語。'},
            'vi': 'Chúng con cám ơn Cha cho phép chúng con tìm hiểu lời Cha.'},
           {'kr': {'de': 'Wir danken dir für die Hoffnung, die du uns durch die Bibel schenkst.',
                   'en': 'We thank you for the hope you give us through the Bible.',
                   'fr': "Nous te remercions pour l'espérance que tu nous donnes par la Bible.",
                   'ja': '聖書を通して私たちに希望を与えてくださり、感謝いたします。',
                   'ko': '저희는 아버지께서 성서를 통해서 저희에게 희망을 주셔서 감사합니다.',
                   'pl': 'Dziękujemy Ci za nadzieję, jaką dajesz nam w Biblii.',
                   'zh': '我們感謝你藉著聖經賜給我們希望。'},
            'vi': 'Chúng con cám ơn Cha ban hy vọng cho chúng con qua Kinh Thánh.'},
           {'kr': {'de': 'Wir bitten dich um deinen heiligen Geist.',
                   'en': 'We ask you to give us your holy spirit.',
                   'fr': 'Nous te prions de nous accorder ton esprit saint.',
                   'ja': '私たちに聖霊を与えてくださるようお願いいたします。',
                   'ko': '저희는 아버지께서 저희에게 성령을 주시기를 청합니다.',
                   'pl': 'Prosimy Cię, abyś udzielił nam swojego świętego ducha.',
                   'zh': '我們懇求你賜給我們聖靈。'},
            'vi': 'Chúng con cầu xin Cha ban thần khí thánh cho chúng con.'},
           {'kr': {'de': 'Wir bitten dich, unser gemeinsames Lernen zu segnen.',
                   'en': 'We ask you to bless our time of study.',
                   'fr': "Nous te demandons de bénir notre moment d'étude.",
                   'ja': '私たちの学びの時を祝福してくださるようお願いいたします。',
                   'ko': '저희는 아버지께서 저희의 공부 시간을 축복하시기를 청합니다.',
                   'pl': 'Prosimy Cię, abyś pobłogosławił ten czas nauki.',
                   'zh': '我們懇求你祝福我們的學習時間。'},
            'vi': 'Chúng con cầu xin Cha ban phước cho buổi học của chúng con.'},
           {'kr': {'de': 'Wir bitten dich, uns zu helfen, diese Lektion gut zu verstehen.',
                   'en': 'We ask you to help us understand this lesson.',
                   'fr': 'Nous te prions de nous aider à bien comprendre cette leçon.',
                   'ja': '私たちがこのレッスンを理解できるよう、お助けください。',
                   'ko': '저희는 아버지께서 저희가 이 과를 이해하도록 도와주시기를 청합니다.',
                   'pl': 'Prosimy Cię, abyś pomógł nam dobrze zrozumieć tę lekcję.',
                   'zh': '我們懇求你幫助我們明白這一課。'},
            'vi': 'Chúng con cầu xin Cha giúp chúng con hiểu được bài học này.'},
           {'kr': {'de': 'Bitte beschütze uns in unserem täglichen Leben.',
                   'en': 'Please protect us in our daily life.',
                   'fr': "Protège-nous, s'il te plaît, dans notre vie quotidienne.",
                   'ja': '日々の生活の中で私たちをお守りください。',
                   'ko': '아버지께서 매일의 생활에서 저희를 보호해 주시옵소서.',
                   'pl': 'Prosimy, chroń nas w codziennym życiu.',
                   'zh': '求你在日常生活中保護我們。'},
            'vi': 'Xin Cha che chở chúng con trong đời sống hằng ngày.'},
           {'kr': {'de': 'Bitte steh uns bei, wenn wir vor schweren Problemen stehen.',
                   'en': 'Please help us when we face difficult problems.',
                   'fr': "Aide-nous, s'il te plaît, lorsque nous affrontons des difficultés.",
                   'ja': '私たちが困難な問題に直面するとき、お助けください。',
                   'ko': '아버지께서 저희가 어려운 문제를 만날 때 도와 주시옵소서.',
                   'pl': 'Prosimy, pomagaj nam, gdy napotykamy trudności.',
                   'zh': '求你在我們遇到困難時幫助我們。'},
            'vi': 'Xin Cha giúp chúng con khi gặp vấn đề khó khăn.'},
           {'kr': {'de': 'Bitte hilf uns, dir gehorsam zu sein.',
                   'en': 'Please help us to obey you.',
                   'fr': "Aide-nous, s'il te plaît, à t'obéir.",
                   'ja': 'あなたに従うことができるよう、お助けください。',
                   'ko': '아버지께서 저희가 아버지의 말씀에 순종하도록 도와주시옵소서.',
                   'pl': 'Prosimy, pomóż nam być Ci posłusznymi.',
                   'zh': '求你幫助我們順從你。'},
            'vi': 'Xin Cha giúp chúng con vâng lời Cha.'},
           {'kr': {'de': 'Bitte vergib uns unsere Fehler und Sünden.',
                   'en': 'Please forgive our sins.',
                   'fr': "Pardonne-nous, s'il te plaît, nos péchés.",
                   'ja': '私たちの罪をお赦しください。',
                   'ko': '아버지께서 저희의 죄를 용서하여 주시옵소서.',
                   'pl': 'Prosimy, przebacz nam nasze grzechy.',
                   'zh': '求你饒恕我們的罪。'},
            'vi': 'Xin Cha tha thứ tội lỗi của chúng con.'},
           {'kr': {'de': 'Wir beten im Namen von Jesus Christus.',
                   'en': 'We pray in the name of Christ Jesus.',
                   'fr': 'Nous prions au nom de Jésus Christ.',
                   'ja': 'キリスト・イエスの名によって祈ります。',
                   'ko': '예수 그리스도 이름으로 기도 드립니다.',
                   'pl': 'Modlimy się w imię Jezusa Chrystusa.',
                   'zh': '我們奉基督耶穌的名禱告。'},
            'vi': 'Chúng con cầu nguyện nhân danh Chúa Giê-su Ki-tô.'},
           {'kr': {'de': 'Amen.', 'en': 'Amen.', 'fr': 'Amen.', 'ja': 'アーメン。', 'ko': '아멘.', 'pl': 'Amen.', 'zh': '阿們。'},
            'vi': 'A-men.'}],
 'note': None}
