# "교과 > 제공 연설" and "교과 > 기도와 노래" subtabs.
# Transcribed verbatim from the course booklet (pdf_layout_marked_v2.txt).
#
# Translatable Korean text fields (talk subtitle, each dialogue line's "kr", each song's
# title_kr, each prayer line's "kr") are stored as {"ko","zh","en","ja"} dicts so js_json()
# (see build_app.py) serializes them straight into JS objects that app_logic.js's T() helper
# can read directly. Non-translatable fields (who, vi, title_vi, scripture, and every song
# lyric's vi/kr -- lyric "kr" is always None, only the vi is shown) are left as plain strings.

OFFER_TALKS = [{'number': 1,
  'subtitle': {'ko': '인사와 소개, 출신',
               'zh': '問候與自我介紹、出身地',
               'en': 'Greetings and Introduction, Origin',
               'ja': 'あいさつと自己紹介、出身地'},
  'lines': [{'who': 'A',
             'vi': 'Xin chào.',
             'kr': {'ko': '안녕하세요.', 'zh': '您好。', 'en': 'Hello.', 'ja': 'こんにちは。'}},
            {'who': 'B',
             'vi': 'Xin chào.',
             'kr': {'ko': '안녕하세요.', 'zh': '您好。', 'en': 'Hello.', 'ja': 'こんにちは。'}},
            {'who': 'A',
             'vi': 'Tôi tên là {{MY_NAME}}. Xin lỗi, bạn tên là gì?',
             'kr': {'ko': '제 이름은 {{MY_NAME}}입니다. 성함이 어떻게 되세요?',
                    'zh': '我叫{{MY_NAME}}。請問您怎麼稱呼?',
                    'en': "My name is {{MY_NAME}}. What's your name?",
                    'ja': '私の名前は{{MY_NAME}}です。お名前は何とおっしゃいますか?'}},
            {'who': 'B',
             'vi': 'Tôi tên là Thanh.',
             'kr': {'ko': '제 이름은 Thanh입니다.',
                    'zh': '我叫Thanh。',
                    'en': 'My name is Thanh.',
                    'ja': '私の名前はThanhです。'}},
            {'who': 'A',
             'vi': 'Đây là {{COMPANION}}.',
             'kr': {'ko': '이 사람은 {{COMPANION}}예요.',
                    'zh': '這位是{{COMPANION}}。',
                    'en': 'This is {{COMPANION}}.',
                    'ja': 'こちらは{{COMPANION}}です。'}},
            {'who': 'C',
             'vi': 'Tôi rất vui được gặp bạn.',
             'kr': {'ko': '만나서 반갑습니다.', 'zh': '很高興認識您。', 'en': 'Nice to meet you.', 'ja': 'お会いできて嬉しいです。'}},
            {'who': 'B',
             'vi': 'Tôi cũng rất vui được gặp bạn.',
             'kr': {'ko': '저도 만나서 반갑습니다.',
                    'zh': '我也很高興認識您。',
                    'en': 'Nice to meet you too.',
                    'ja': '私もお会いできて嬉しいです。'}},
            {'who': 'A',
             'vi': 'Bạn quê ở đâu?',
             'kr': {'ko': '고향이 어디세요?',
                    'zh': '請問您的故鄉是哪裡?',
                    'en': 'Where is your hometown?',
                    'ja': 'ご出身はどちらですか?'}},
            {'who': 'B',
             'vi': 'Tôi quê ở Hà Nội.',
             'kr': {'ko': '제 고향은 하노이입니다.',
                    'zh': '我的故鄉是河內。',
                    'en': 'My hometown is Hanoi.',
                    'ja': '私の出身はハノイです。'}}]},
 {'number': 2,
  'subtitle': {'ko': '인사와 개인 이력',
               'zh': '問候與個人經歷',
               'en': 'Greetings and Personal Background',
               'ja': 'あいさつと個人の経歴'},
  'lines': [{'who': 'A',
             'vi': 'Xin chào. Bạn có khỏe không?',
             'kr': {'ko': '안녕하세요? 잘 지내셨어요? (건강하세요?)',
                    'zh': '您好嗎?最近過得好嗎?(身體健康嗎?)',
                    'en': 'Hello, how have you been? (Are you healthy?)',
                    'ja': 'こんにちは。お元気でしたか?(お体は元気ですか?)'}},
            {'who': 'B',
             'vi': 'Cảm ơn bạn. Tôi khỏe. Còn bạn thế nào?',
             'kr': {'ko': '고마워요. 잘 지냈어요. 잘 지냈어요?',
                    'zh': '謝謝。我過得很好。您過得好嗎?',
                    'en': "Thank you. I've been well. Have you been well?",
                    'ja': 'ありがとうございます。元気に過ごしていました。お元気でしたか?'}},
            {'who': 'A',
             'vi': 'Tôi cũng khỏe. Bạn có phải là sinh viên không?',
             'kr': {'ko': '저도 잘 지냈어요. 대학생이에요?',
                    'zh': '我也過得很好。您是大學生嗎?',
                    'en': "I've been well too. Are you a university student?",
                    'ja': '私も元気に過ごしていました。大学生ですか?'}},
            {'who': 'B',
             'vi': 'Dạ, phải.',
             'kr': {'ko': '네. 맞아요.', 'zh': '是的,沒錯。', 'en': "Yes, that's right.", 'ja': 'はい、そうです。'}},
            {'who': 'A',
             'vi': 'Bạn sang Hàn Quốc được bao lâu rồi?',
             'kr': {'ko': '한국에 온 지 얼마나 됐어요?',
                    'zh': '您來韓國多久了?',
                    'en': 'How long have you been in Korea?',
                    'ja': '韓国に来てどのくらいになりますか?'}},
            {'who': 'B',
             'vi': 'Tôi sang Hàn Quốc được ba năm rồi. Bạn học tiếng Việt được bao lâu rồi?',
             'kr': {'ko': '한국에 온 지 3년 됐어요. 베트남어 공부한 지 얼마나 됐어요?',
                    'zh': '我來韓國三年了。您學越南語多久了?',
                    'en': "I've been in Korea for 3 years. How long have you been studying Vietnamese?",
                    'ja': '韓国に来て3年になります。ベトナム語を勉強してどのくらいになりますか?'}},
            {'who': 'A',
             'vi': 'Tôi học tiếng Việt được một tuần rồi.',
             'kr': {'ko': '베트남어 공부한 지 일주일 됐어요.',
                    'zh': '我學越南語一個星期了。',
                    'en': "I've been studying Vietnamese for a week.",
                    'ja': 'ベトナム語を勉強して1週間になります。'}}]},
 {'number': 3,
  'subtitle': {'ko': '전화번호와 나이, 결혼여부',
               'zh': '電話號碼、年齡與婚姻狀況',
               'en': 'Phone Number, Age, and Marital Status',
               'ja': '電話番号と年齢、結婚の有無'},
  'lines': [{'who': 'A',
             'vi': 'Đây là số điện thoại của tôi. Bạn có thể cho tôi số điện thoại được không?',
             'kr': {'ko': '이건 제 연락처에요. 혹시 연락처 주실 수 있을까요?',
                    'zh': '這是我的聯絡方式。可以請您也給我您的聯絡方式嗎?',
                    'en': 'This is my contact information. Could I get your contact information as well?',
                    'ja': 'これは私の連絡先です。よろしければ連絡先を教えていただけますか?'}},
            {'who': 'B',
             'vi': 'Số điện thoại của tôi là {{MY_PHONE}}.',
             'kr': {'ko': '제 번호는 {{MY_PHONE}}에요.',
                    'zh': '我的號碼是{{MY_PHONE}}。',
                    'en': 'My number is {{MY_PHONE}}.',
                    'ja': '私の番号は{{MY_PHONE}}です。'}},
            {'who': 'A',
             'vi': 'Cảm ơn bạn! Bạn bao nhiêu tuổi?',
             'kr': {'ko': '감사합니다! 몇 살이에요?',
                    'zh': '謝謝!請問您幾歲?',
                    'en': 'Thank you! How old are you?',
                    'ja': 'ありがとうございます!おいくつですか?'}},
            {'who': 'B',
             'vi': 'Tôi {{LISTENER_AGE}} tuổi. Còn bạn bao nhiêu tuổi?',
             'kr': {'ko': '저는 {{LISTENER_AGE}}살이에요. 당신은 몇 살이에요?',
                    'zh': '我{{LISTENER_AGE}}歲。您幾歲?',
                    'en': 'I am {{LISTENER_AGE}} years old. How old are you?',
                    'ja': '私は{{LISTENER_AGE}}歳です。あなたは何歳ですか?'}},
            {'who': 'A',
             'vi': 'Tôi {{MY_AGE}} tuổi. Bạn đã kết hôn chưa?',
             'kr': {'ko': '저는 {{MY_AGE}}살이에요. 결혼은 하셨나요?',
                    'zh': '我{{MY_AGE}}歲。您結婚了嗎?',
                    'en': 'I am {{MY_AGE}} years old. Are you married?',
                    'ja': '私は{{MY_AGE}}歳です。ご結婚されていますか?'}},
            {'who': 'B',
             'vi': 'Tôi đã kết hôn rồi. Bạn có lập gia đình chưa?',
             'kr': {'ko': '결혼했어요. 당신은 결혼했나요?',
                    'zh': '我結婚了。您結婚了嗎?',
                    'en': "I'm married. Are you married?",
                    'ja': '結婚しています。あなたは結婚していますか?'}},
            {'who': 'A',
             'vi': '{{MARITAL_A}}',
             'kr': {'ko': '{{MARITAL_A}}',
                    'zh': '{{MARITAL_A}}',
                    'en': '{{MARITAL_A}}',
                    'ja': '{{MARITAL_A}}'}}]},
 {'number': 4,
  'subtitle': {'ko': '재방문 약속(사는 곳, 요일)',
               'zh': '再訪問預約(住處、星期)',
               'en': 'Return Visit Appointment (Where You Live, Day of the Week)',
               'ja': '再訪問の約束(住んでいる場所、曜日)'},
  'lines': [{'who': 'A',
             'vi': 'Chúng ta sẽ gặp lần khác được không?',
             'kr': {'ko': '다음에 다시 만날 수 있을까요?',
                    'zh': '我們下次可以再見面嗎?',
                    'en': 'Could we meet again next time?',
                    'ja': '今度また会っていただけますか?'}},
            {'who': 'B', 'vi': 'Dạ được.', 'kr': {'ko': '네.', 'zh': '好的。', 'en': 'Yes.', 'ja': 'はい。'}},
            {'who': 'A',
             'vi': 'Chúng ta có thể gặp nhau ở đâu? Nhà bạn có gần đây không?',
             'kr': {'ko': '어디서 만날까요? 집이 근처인가요?',
                    'zh': '我們要在哪裡見面呢?您家在附近嗎?',
                    'en': 'Where shall we meet? Is your house nearby?',
                    'ja': 'どこで会いましょうか?お宅はこの近くですか?'}},
            {'who': 'B',
             'vi': 'Dạ. Nhà tôi ở gần đây.',
             'kr': {'ko': '네. 여기에서 가까워요.',
                    'zh': '是的,離這裡很近。',
                    'en': "Yes. It's close to here.",
                    'ja': 'はい、ここから近いです。'}},
            {'who': 'A',
             'vi': 'Khi nào thì tiện cho bạn?',
             'kr': {'ko': '언제가 편리하실까요?',
                    'zh': '您什麼時候方便呢?',
                    'en': 'When would be convenient for you?',
                    'ja': 'いつがご都合よろしいですか?'}},
            {'who': 'B',
             'vi': 'Tôi được nghỉ vào cuối tuần.',
             'kr': {'ko': '주말에 쉬어요.', 'zh': '我週末休息。', 'en': 'I rest on weekends.', 'ja': '週末は休みです。'}},
            {'who': 'A',
             'vi': 'Vậy... Chiều thứ bảy tuần này bạn có thời gian không?',
             'kr': {'ko': '그럼 이번 주 토요일에 시간이 있나요?',
                    'zh': '那麼這個星期六您有空嗎?',
                    'en': 'Then, do you have time this Saturday?',
                    'ja': 'では、今週の土曜日はお時間ありますか?'}},
            {'who': 'B',
             'vi': 'Xin lỗi. Thứ bảy này thì tôi bận rồi. Chủ Nhật thì tiện hơn.',
             'kr': {'ko': '죄송합니다. 이번 주 토요일에는 바빠요. 일요일이 더 좋을 것 같아요.',
                    'zh': '不好意思,這個星期六我很忙。星期日應該比較好。',
                    'en': "I'm sorry. I'm busy this Saturday. Sunday seems better.",
                    'ja': 'すみません。今週の土曜日は忙しいです。日曜日の方が良さそうです。'}},
            {'who': 'A',
             'vi': 'OK. Hẹn gặp vào Chủ Nhật này.',
             'kr': {'ko': '좋습니다. 그럼 이번 주 일요일에 만나요.',
                    'zh': '好的,那麼我們這個星期日見面吧。',
                    'en': "Good. Then let's meet this Sunday.",
                    'ja': 'わかりました。では、今週の日曜日に会いましょう。'}},
            {'who': 'B',
             'vi': 'Hẹn gặp lại.',
             'kr': {'ko': '다음에 만나요.', 'zh': '下次見。', 'en': 'See you next time.', 'ja': 'また会いましょう。'}}]},
 {'number': 5,
  'subtitle': {'ko': '하느님의 이름(동영상 소개)',
               'zh': '上帝的名字(影片介紹)',
               'en': "God's Name (Video Introduction)",
               'ja': '神の名前(動画紹介)'},
  'lines': [{'who': 'A',
             'vi': 'Bạn có bao giờ nghe danh của Đức Chúa Trời chưa?',
             'kr': {'ko': '하느님에게 이름이 있다는 걸 들어보셨나요?',
                    'zh': '您聽說過上帝有名字嗎?',
                    'en': 'Have you heard that God has a name?',
                    'ja': '神に名前があることを聞いたことがありますか?'}},
            {'who': 'B',
             'vi': 'Danh Đức Chúa Trời hả? Tôi không biết là Đức Chúa Trời có danh riêng.',
             'kr': {'ko': '하느님의 이름이요? 하느님에게 이름이 있는지 몰랐어요.',
                    'zh': '上帝的名字？我不知道上帝有名字。',
                    'en': "God's name? I didn't know God had a name.",
                    'ja': '神の名前ですか？神に名前があるとは知りませんでした。'}},
            {'who': 'A',
             'vi': 'Người ta ngạc nhiên khi biết điều đó. Tôi cho bạn xem một video được không? (xem video '
                   'tờ chuyên đề ʻÔng Trời là ai?’) Video này cho biết danh của Đức Chúa Trời là gì?',
             'kr': {'ko': '그걸 알고 놀라는 분들이 계시지요. 제가 동영상 하나 보여 드려도 될까요? (‘참 하느님은 어떤 분입니까?’ 전도지 동영상을 본다.) 이 동영상은 '
                          '하느님의 이름이 무엇이라고 알려주나요?',
                    'zh': '有些人知道這件事後會感到驚訝。我可以給您看一段影片嗎？（觀看單張《真正的上帝是怎樣的一位？》的影片。）這段影片告訴我們上帝的名字是什麼呢？',
                    'en': 'Some people are surprised to learn that. May I show you a short video? (Watch the '
                          'tract video "What Is God Like?") What does this video tell us God\'s name is?',
                    'ja': 'それを知って驚く方もいらっしゃいますよ。動画を一つお見せしてもよろしいですか？（パンフレット「真の神とはどのような方ですか」の動画を見る。）この動画では、神の名前は何だと教えていますか。'}},
            {'who': 'B',
             'vi': 'Danh Đức Chúa Trời là Giê-ho-va.',
             'kr': {'ko': '하느님의 이름이 여호와네요.',
                    'zh': '上帝的名字是耶和華。',
                    'en': "God's name is Jehovah.",
                    'ja': '神の名前はエホバなんですね。'}},
            {'who': 'A',
             'vi': 'Nếu biết danh Đức Chúa Trời thì chúng ta có thể đến gần Ngài.',
             'kr': {'ko': '하느님의 이름을 알면 그분과 가까워질 수 있어요.',
                    'zh': '知道上帝的名字，可以幫助我們與他更親近。',
                    'en': "Knowing God's name can help us draw closer to him.",
                    'ja': '神の名前を知ると、神により近づくことができます。'}}]},
 {'number': 6,
  'subtitle': {'ko': '가정의 행복(성구 소개)',
               'zh': '家庭幸福（經文介紹）',
               'en': 'Family Happiness (Scripture Introduction)',
               'ja': '家庭の幸せ（聖句紹介）'},
  'lines': [{'who': 'A',
             'vi': 'Theo bạn, bí quyết giúp gia đình hạnh phúc là gì?',
             'kr': {'ko': '가족이 행복할 수 있는 비결이 무엇이라고 생각하시나요?',
                    'zh': '您認為家庭幸福的秘訣是什麼呢？',
                    'en': 'What do you think is the secret to a happy family?',
                    'ja': '家族が幸せになる秘訣は何だと思われますか。'}},
            {'who': 'B',
             'vi': 'Tôi nghĩ điều quan trọng là có tình yêu thương.',
             'kr': {'ko': '사랑이 있는 것이 중요하다고 생각해요.',
                    'zh': '我覺得有愛是很重要的。',
                    'en': 'I think having love is important.',
                    'ja': '愛があることが大切だと思います。'}},
            {'who': 'A',
             'vi': 'Tôi đồng ý. Tình yêu thương rất quan trọng. Hãy để ý những gì Kinh Thánh nói. Xin mời '
                   'đọc lớn tiếng câu Kinh Thánh này. Ê-phê-sô 5:33.',
             'kr': {'ko': '맞아요. 사랑이 정말 중요하죠. 성경에서는 무엇이라고 하는지 유의해보실까요. 이 성구를 소리 내서 읽어주시겠어요. 에베소 5:33',
                    'zh': '沒錯，愛真的很重要。我們來看看聖經怎麼說好嗎？可以請您把這節經文念出來嗎？以弗所書5:33',
                    'en': "That's right. Love really is important. Shall we take note of what the Bible "
                          'says? Could you read this scripture out loud? Ephesians 5:33',
                    'ja': 'そうですね。愛は本当に大切です。聖書では何と述べているか、見てみましょうか。この聖句を声に出して読んでいただけますか。エフェソス5:33'}},
            {'who': 'B',
             'vi': '“Mỗi người phải yêu vợ như yêu chính mình, còn vợ thì nên kính trọng chồng sâu xa.”',
             'kr': {'ko': '“여러분도 각자 자신을 사랑하듯이 아내를 사랑하십시오. 그리고 아내는 남편에 대해 깊은 존경심을 가져야 합니다.”',
                    'zh': '「你們各人都要愛自己的妻子，好像愛自己一樣；妻子也要對丈夫深懷敬重之心。」',
                    'en': '"Each one of you must love his wife as he does himself; and the wife should have '
                          'deep respect for her husband."',
                    'ja': '「あなた方各自も自分自身を愛するように妻を愛しなさい。そして，妻は夫に対して深い敬意を持つべきです」'}},
            {'who': 'A',
             'vi': 'Cám ơn. Bạn nghĩ lời này có thiết thực không?',
             'kr': {'ko': '감사합니다. 이 말씀이 실용적이라고 생각하시나요?',
                    'zh': '謝謝您。您覺得這段話實用嗎？',
                    'en': 'Thank you. Do you think this counsel is practical?',
                    'ja': 'ありがとうございます。この言葉は実用的だと思われますか。'}},
            {'who': 'B',
             'vi': 'Chắc chắn rồi. Tôi đang cố gắng làm vậy.',
             'kr': {'ko': '당연하죠. 저도 이렇게 하려고 노력하는걸요.',
                    'zh': '當然啊，我也在努力這樣做。',
                    'en': 'Of course. I try to do this myself.',
                    'ja': 'もちろんです。私もそうしようと努力しています。'}},
            {'who': 'A',
             'vi': 'Rất tốt.',
             'kr': {'ko': '아주 좋네요.', 'zh': '太好了。', 'en': "That's very good.", 'ja': 'とてもいいですね。'}}]},
 {'number': 7,
  'subtitle': {'ko': '사망(전도지와 JW카드 제공)',
               'zh': '死亡（提供傳單和JW卡片）',
               'en': 'Death (Offer tract and JW card)',
               'ja': '死（パンフレットとJWカードを渡す）'},
  'lines': [{'who': 'A',
             'vi': 'Tất cả chúng ta đều có người thân yêu đã mất. Vậy bạn nghĩ gì về câu hỏi này? (cho xem '
                   'tờ chuyên đề “Có phải chết là hết?)',
             'kr': {'ko': '우리 모두는 사랑하는 사람과 사별한 적이 있죠. 혹시 이 질문에 대해 어떻게 생각하세요? (전도지 “사망한 가족이나 친구를 다시 만날 수 '
                          '있습니까?” -베트남어 직역 표현은 “죽으면 끝입니까?”)',
                    'zh': '我們每個人都曾經失去過所愛的人。您對這個問題有什麼看法呢？（傳單《能不能再見到去世的親友？》——越南語直譯的說法是「死了就是終結嗎？」）',
                    'en': 'We have all lost someone we love. What do you think about this question? (Tract '
                          '"Can We See Our Dead Loved Ones Again?" — the literal Vietnamese phrase is "Is '
                          'death the end?")',
                    'ja': '私たちは皆、愛する人を亡くした経験があります。この質問についてどう思われますか。（パンフレット「亡くなった家族や友人にまた会えますか」―ベトナム語を直訳すると「死んだら終わりですか」という表現になります）'}},
            {'who': 'B',
             'vi': 'Tôi nghĩ rằng khi một người chết thì là hết.',
             'kr': {'ko': '전 죽으면 끝이라고 생각해요.',
                    'zh': '我覺得人死了就什麼都沒有了。',
                    'en': 'I think death is the end.',
                    'ja': '死んだら終わりだと思います。'}},
            {'who': 'A',
             'vi': 'Bạn nghĩ như vậy. Thế thì người thân yêu đã qua đời có thể được sống lại không?',
             'kr': {'ko': '그렇게 생각하시는군요. 그럼 과연 사망한 사랑하는 사람이 다시 살아날 수 있을까요?',
                    'zh': '原來您是這麼想的。那麼，去世的親人真的有可能復活嗎？',
                    'en': "I see, that's what you think. Well, is it really possible for our deceased loved "
                          'ones to live again?',
                    'ja': 'そう思っていらっしゃるのですね。では、亡くなった愛する人が本当によみがえることはあるのでしょうか。'}},
            {'who': 'B',
             'vi': 'Nghe quá tuyệt vời nhưng chắc là khó tin.',
             'kr': {'ko': '너무 좋은 말이지만 믿을 수가 없네요.',
                    'zh': '這話聽起來很好，但我無法相信。',
                    'en': 'That sounds wonderful, but I find it hard to believe.',
                    'ja': 'とても良い話ですが、信じることができません。'}},
            {'who': 'A',
             'vi': 'Đúng là một điều khó tin. Nhưng Kinh Thánh cho biết rằng Đức Chúa Trời sẽ làm cho họ '
                   'sống lại. Để biết thêm, xin vào trang jw.org. (để lại thẻ JW)',
             'kr': {'ko': '믿기 힘든 말이긴 하죠. 하지만 성경에서는 하느님께서 그들을 부활시키실 것이라고 알려주지요. 더 자세한 점은 JW.ORG에서 알아보세요.(JW카드 '
                          '제공)',
                    'zh': '確實不容易相信。不過聖經告訴我們，上帝會使他們復活。您可以到JW.ORG網站進一步瞭解。（提供JW卡片）',
                    'en': 'It is hard to believe. But the Bible tells us that God will resurrect them. You '
                          'can find out more at JW.ORG. (Offer JW card)',
                    'ja': '信じにくいお話ですよね。しかし聖書には、神がその人たちを復活させてくださると書かれています。詳しくはJW.ORGでご覧ください。（JWカードを渡す）'}},
            {'who': 'B', 'vi': 'Dạ.', 'kr': {'ko': '네.', 'zh': '好的。', 'en': 'Yes.', 'ja': 'はい。'}}]},
 {'number': 8,
  'subtitle': {'ko': '미래(성구 소개)',
               'zh': '未來（經文介紹）',
               'en': 'The Future (Scripture Introduction)',
               'ja': '将来（聖句紹介）'},
  'lines': [{'who': 'A',
             'vi': 'Bạn có bao giờ nghe về chúng ta có thể vui sống mãi mãi chưa?',
             'kr': {'ko': '우리가 영원히 행복하게 살 수 있다는 점을 들어 보셨나요?',
                    'zh': '您有沒有聽說過我們可以永遠幸福地活著呢？',
                    'en': 'Have you heard that we can live happily forever?',
                    'ja': '私たちが永遠に幸せに生きられるということを聞いたことがありますか。'}},
            {'who': 'B',
             'vi': 'Chưa. Tôi chưa nghe điều đó bao giờ.',
             'kr': {'ko': '아니요, 그런 이야기는 처음 들어요.',
                    'zh': '沒有，我第一次聽到這種說法。',
                    'en': "No, this is the first time I've heard that.",
                    'ja': 'いいえ、そのような話は初めて聞きます。'}},
            {'who': 'A',
             'vi': 'Vậy à. Kinh Thánh Thi-thiên 37:29 cho biết như sau. Bạn có thể đọc giúp tôi câu này '
                   'được không?',
             'kr': {'ko': '그렇군요. 성경 시편 37편 29절 에서는 이렇게 알려줘요. 여기를 좀 읽어주시겠어요?',
                    'zh': '原來如此。聖經詩篇37篇29節這樣告訴我們。可以請您讀一下這節經文嗎？',
                    'en': 'I see. The Bible tells us this at Psalm 37:29. Could you read it for me?',
                    'ja': 'そうですか。聖書の詩編37編29節にはこう書かれています。ここを読んでいただけますか。'}},
            {'who': 'B',
             'vi': '“Người công chính sẽ hưởng trái đất và được sống trên đó mãi mãi”.',
             'kr': {'ko': '“의로운 자들은 땅을 차지하고 거기서 영원히 살 것입니다.”',
                    'zh': '「義人必承受地土，永遠住在其上。」',
                    'en': '"The righteous will possess the earth, and they will live forever on it."',
                    'ja': '「義人は地を所有し，とこしえにその上に住む」'}},
            {'who': 'A',
             'vi': 'Cảm ơn bạn. Qua câu này, chúng ta thấy rằng Đức Chúa Trời hứa cho chúng ta cơ hội sống '
                   'hạnh phúc mãi mãi.',
             'kr': {'ko': '고마워요. 이 말씀을 보면 하느님께서 우리가 영원히 행복하게 살 수 있도록 약속하고 계신다는 것을 알 수 있어요.',
                    'zh': '謝謝您。這節經文讓我們看到，上帝應許我們可以永遠幸福地活著。',
                    'en': 'Thank you. This scripture shows us that God is promising that we can live happily '
                          'forever.',
                    'ja': 'ありがとうございます。この聖句から、神が私たちに永遠に幸せに生きられるよう約束してくださっていることが分かります。'}}]},
 {'number': 9,
  'subtitle': {'ko': '성서연구 제안방법(동영상 소개)',
               'zh': '提議聖經研究的方法（影片介紹）',
               'en': 'How to Offer a Bible Study (Video Introduction)',
               'ja': '聖書研究の勧め方（動画紹介）'},
  'lines': [{'who': '',
             'vi': 'Nhân Chứng Giê-hô-va mời mọi người tìm hiểu Kinh Thánh miễn phí.',
             'kr': {'ko': '여호와의 증인은 무료로 성경을 공부해 보시도록 도와 드리고 있어요.',
                    'zh': '耶和華見證人免費幫助大家學習聖經。',
                    'en': "Jehovah's Witnesses offer free help to study the Bible.",
                    'ja': 'エホバの証人は無料で聖書を学ぶお手伝いをしています。'}},
            {'who': '',
             'vi': 'Video ngắn này cho thấy lý do vì sao chúng ta nên tìm hiểu Kinh Thánh.',
             'kr': {'ko': '이 짧은 동영상은 우리가 왜 성경을 배워야 하는지 그 이유를 보여줘요.',
                    'zh': '這段短片會讓您瞭解，我們為什麼應該學習聖經。',
                    'en': 'This short video shows why we should study the Bible.',
                    'ja': 'この短い動画は、私たちがなぜ聖書を学ぶべきかを教えてくれます。'}},
            {'who': '',
             'vi': '(xem video ʻtại sao tìm hiểu Kinh Thánh?’)',
             'kr': {'ko': '(‘왜 성경을 알아봐야 합니까?’ 동영상을 본다)',
                    'zh': '（觀看《為什麼要認識聖經？》的影片。）',
                    'en': '(Watch the video "Why Study the Bible?")',
                    'ja': '（「なぜ聖書を調べるべきですか」の動画を見る）'}},
            {'who': '',
             'vi': 'Chúng ta có thể dùng quyển sách này để thảo luận.',
             'kr': {'ko': '이 책을 사용해서 성경을 공부하실 수 있어요.',
                    'zh': '您可以使用這本書來學習聖經。',
                    'en': 'You can use this book to study the Bible.',
                    'ja': 'この本を使って聖書を学ぶことができます。'}},
            {'who': '',
             'vi': 'Tôi đang mời mọi người tìm hiểu Kinh Thánh miễn phí tại nhà.',
             'kr': {'ko': '저는 무료 성경 공부를 소개하고 있어요.',
                    'zh': '我正在介紹免費的聖經研究課程。',
                    'en': "I'm offering a free Bible study.",
                    'ja': '私は無料の聖書研究をご紹介しています。'}},
            {'who': '',
             'vi': 'Bạn có biết không? Chỉ trong vài phút, bạn có thể tìm được lời giải đáp cho một câu hỏi '
                   'quan trọng.',
             'kr': {'ko': '몇 분만 시간을 내시면 중요한 질문에 대한 답을 알아보실 수 있다는 걸 아시나요?',
                    'zh': '您知道嗎，只要花幾分鐘時間，就能找到重要問題的答案。',
                    'en': 'Did you know that just a few minutes of your time can help you find answers to '
                          'important questions?',
                    'ja': '数分お時間をいただくだけで、重要な質問への答えが分かるということをご存じですか。'}},
            {'who': '',
             'vi': 'Video này sẽ cho thấy buổi tìm hiểu Kinh Thánh diễn ra như thế nào.',
             'kr': {'ko': '이 동영상은 성경 공부가 어떻게 진행되는지를 보여 줍니다.',
                    'zh': '這段影片會讓您瞭解聖經研究是如何進行的。',
                    'en': 'This video shows how a Bible study is conducted.',
                    'ja': 'この動画は、聖書研究がどのように進められるかを示しています。'}},
            {'who': '',
             'vi': '(xem video ʻBuổi tìm hiểu Kinh Thánh diễn ra như thế nào?’)',
             'kr': {'ko': '(‘성경 공부는 어떻게 진행됩니까?’ 동영상을 본다)',
                    'zh': '（觀看《聖經研究是怎麼進行的？》的影片。）',
                    'en': '(Watch the video "How Is a Bible Study Conducted?")',
                    'ja': '（「聖書研究はどのように行われますか」の動画を見る）'}},
            {'who': '',
             'vi': 'Bạn có muốn tìm hiểu Kinh Thánh với tôi không?',
             'kr': {'ko': '저와 성경을 공부해 보지 않으시겠어요?',
                    'zh': '您願不願意跟我一起學習聖經呢？',
                    'en': 'Would you like to study the Bible with me?',
                    'ja': '私と一緒に聖書を学んでみませんか。'}}]},
 {'number': 10,
  'subtitle': {'ko': '성서연구 사회(행누 1과 요점3)',
               'zh': '聖經研究示範（행누 第1課 要點3）',
               'en': 'Conducting a Bible Study (행누, Lesson 1, Point 3)',
               'ja': '聖書研究の進め方（행누 第1課 ポイント3）'},
  'lines': [{'who': 'A',
             'vi': 'Chúng ta cùng xem xét điểm số 3 nhé. Chúng ta hãy đọc Thi-thiên 119:105.',
             'kr': {'ko': '우리 함께 3번 요점을 살펴봐요. 이제 시편 119:105을 읽어 볼게요.',
                    'zh': '我們一起來看看第3點。現在我們來讀一下詩篇119:105。',
                    'en': "Let's look at point 3 together. Now let's read Psalm 119:105.",
                    'ja': '一緒にポイント3を見てみましょう。では詩編119編105節を読んでみます。'}},
            {'who': 'B', 'vi': '(Đọc.)', 'kr': {'ko': '(읽음)', 'zh': '（讀出）', 'en': '(Read)', 'ja': '（読む）'}},
            {'who': 'A',
             'vi': 'Người viết câu này nghĩ gì về Kinh Thánh?',
             'kr': {'ko': '이 시를 지은 사람은 성경에 대해 어떻게 생각했나요?',
                    'zh': '這首詩的作者對聖經有什麼看法呢？',
                    'en': 'What did the writer of this psalm think about the Bible?',
                    'ja': 'この詩を書いた人は聖書についてどう考えていましたか。'}},
            {'who': 'B',
             'vi': 'Người viết nghĩ rằng Kinh Thánh là ngọn đèn và ánh sáng cho chúng ta.',
             'kr': {'ko': '성경이 우리에게 등불과 빛이라고 생각해요.',
                    'zh': '我覺得聖經對我們來說是一盞燈，也是一道光。',
                    'en': 'I think the Bible is a lamp and a light to us.',
                    'ja': '聖書は私たちにとってともし火であり、光だと思います。'}},
            {'who': 'A',
             'vi': 'Đúng rồi! Bạn nghĩ sao về Kinh Thánh?',
             'kr': {'ko': '맞아요! 당신은 성경에 대해 어떻게 생각하나요?',
                    'zh': '沒錯！你覺得聖經怎麼樣呢？',
                    'en': "That's right! What do you think about the Bible?",
                    'ja': 'そうですね！あなたは聖書についてどう思いますか？'}},
            {'who': 'B',
             'vi': 'Tôi cũng nghĩ là Kinh Thánh có thể hướng dẫn chúng ta.',
             'kr': {'ko': '저도 성경이 우리를 인도해 줄 수 있다고 생각해요.',
                    'zh': '我也覺得聖經能夠指引我們。',
                    'en': 'I also think the Bible can guide us.',
                    'ja': '私も聖書は私たちを導いてくれると思います。'}},
            {'who': 'A',
             'vi': 'Rất tốt. Hãy xem hình này nhé. Chuyện gì đang diễn ra trong hình này?',
             'kr': {'ko': '아주 좋아요. 이 삽화를 한번 보세요. 이 삽화는 어떤 장면인가요?',
                    'zh': '非常好。請看看這幅插圖，這幅插圖是什麼場景呢？',
                    'en': 'Very good. Please take a look at this picture. What scene is shown in this '
                          'picture?',
                    'ja': 'とてもいいですね。この挿絵をご覧ください。この挿絵はどんな場面ですか？'}},
            {'who': 'B',
             'vi': 'Một người đang đi bộ trên con đường tối vào ban đêm và dùng đèn pin để soi đường. Kinh '
                   'Thánh cũng giống như một chiếc đèn pin.',
             'kr': {'ko': '어떤 사람이 밤에 어두운 길을 걸어가면서 손전등으로 길을 비추고 있어요. 성경도 손전등과 같아요.',
                    'zh': '有一個人在夜晚走在黑暗的路上，用手電筒照亮道路。聖經就像手電筒一樣。',
                    'en': 'A person is walking on a dark road at night, shining a flashlight to light the '
                          'way. The Bible is like that flashlight.',
                    'ja': 'ある人が夜、暗い道を歩きながら懐中電灯で道を照らしています。聖書も懐中電灯のようなものです。'}},
            {'who': 'A',
             'vi': 'Tuyệt vời! Chúng ta sang điểm tiếp theo nhé.',
             'kr': {'ko': '훌륭해요! 다음 요점으로 넘어가 볼게요.',
                    'zh': '太好了！我們來看下一個要點吧。',
                    'en': "Excellent! Let's move on to the next point.",
                    'ja': 'すばらしいです！次のポイントに進みましょう。'}}]},
 {'number': 11,
  'subtitle': {'ko': '집회 초대', 'zh': '聚會邀請', 'en': 'Meeting Invitation', 'ja': '集会へのご招待'},
  'lines': [{'who': 'A',
             'vi': 'Chiều Chủ Nhật này bạn có rảnh không? Tôi muốn mời bạn tham dự buổi nhóm họp tại Phòng '
                   'Nước Trời.',
             'kr': {'ko': '이번 일요일 오후에 시간 있어요? 왕국회관에서 열리는 집회에 초대하고 싶어요.',
                    'zh': '這個星期天下午你有時間嗎？我想邀請你參加在王國聚會所舉行的聚會。',
                    'en': "Do you have time this Sunday afternoon? I'd like to invite you to a meeting held "
                          'at the Kingdom Hall.',
                    'ja': '今週の日曜日の午後、お時間はありますか？王国会館で開かれる集会にご招待したいのですが。'}},
            {'who': 'B',
             'vi': 'Nhóm họp hả?',
             'kr': {'ko': '집회요?', 'zh': '聚會嗎？', 'en': 'A meeting?', 'ja': '集会ですか？'}},
            {'who': 'A',
             'vi': 'Dạ. Các buổi nhóm họp được diễn ra bằng tiếng Việt Nam. Ai muốn tham gia cũng đến được '
                   'và vào cửa miễn phí. Tôi mời bạn cùng xem video này. (Điều gì diễn ra tại Phòng Nước '
                   'Trời?)',
             'kr': {'ko': '네. 베트남어로 제공되는 집회예요. 누구나 무료로 참석할 수 있어요. 이 동영상을 같이 볼까요. (왕국회관은 어떤 곳 입니까?)',
                    'zh': '是的，這是用越南語進行的聚會，任何人都可以免費參加。我們一起看看這段影片好嗎？（王國聚會所是什麼樣的地方？）',
                    'en': "Yes, it's a meeting held in Vietnamese. Anyone can attend for free. Shall we "
                          'watch this video together? (What is a Kingdom Hall?)',
                    'ja': 'はい。ベトナム語で行われる集会です。誰でも無料で参加できます。この動画を一緒に見てみましょうか。（王国会館とはどんな所ですか？）'}},
            {'who': 'B',
             'vi': 'Mấy giờ có nhóm họp?',
             'kr': {'ko': '집회가 몇 시에 있나요?',
                    'zh': '聚會是幾點開始呢？',
                    'en': 'What time is the meeting?',
                    'ja': '集会は何時にありますか？'}},
            {'who': 'A',
             'vi': 'Buổi nhóm họp bắt đầu lúc bốn giờ chiều.',
             'kr': {'ko': '오후 4시에 시작해요.',
                    'zh': '下午4點開始。',
                    'en': 'It starts at 4 p.m.',
                    'ja': '午後4時に始まります。'}}]}]

KINGDOM_SONGS = [
 {'number': 12,
  'title_kr': {'ko': '위대한 하느님, 여호와',
               'zh': '偉大的上帝，耶和華',
               'en': 'Great God, Jehovah',
               'ja': '偉大な神、エホバ'},
  'title_vi': 'Đức Giê-hô-va, ngài thật vĩ đại',
  'scripture': 'Xuất Ai Cập 34:6, 7',
  'verses': [[{'vi': 'Hỡi Cha Giê-hô-va, đấng cai trị tối cao,', 'kr': {'ko': '지존하신 통치자, 여호와 아버지시여,',
                                                                       'zh': '至高的統治者，耶和華天父啊，',
                                                                       'en': 'O Father Jehovah, the Sovereign Most High,',
                                                                       'ja': 'いと高き支配者エホバなる父よ、'}},
             {'vi': 'ngài yêu thương, công chính vô cùng,', 'kr': {'ko': '당신은 사랑과 공의가 한없으시며,',
                                                                   'zh': '你充滿慈愛與公義，',
                                                                   'en': 'you are boundless in love and righteousness,',
                                                                   'ja': 'あなたは限りない愛と義に満ちておられます。'}},
             {'vi': 'được ca khen, tôn vinh trên hết.', 'kr': {'ko': '그 무엇보다 찬양과 영광을 받으실 분입니다.',
                                                               'zh': '應當受到至高的讚美和榮耀。',
                                                               'en': 'You deserve praise and glory above all else.',
                                                               'ja': '何よりも賛美と栄光を受けるにふさわしい方です。'}},
             {'vi': 'Lối Cha tuyệt hảo thay với bao điều sáng khôn.', 'kr': {'ko': '아버지의 길은 완전하고 지혜로 가득합니다.',
                                                                             'zh': '天父的道路完美無瑕，充滿智慧。',
                                                                             'en': 'Your ways are perfect, full of wisdom.',
                                                                             'ja': '父の道は完全で、知恵に満ちています。'}},
             {'vi': 'Ngài là Vua vinh hiển, quyền năng.', 'kr': {'ko': '당신은 영광스럽고 능력 있는 왕이십니다.',
                                                                 'zh': '你是榮耀又大能的君王。',
                                                                 'en': 'You are the glorious and mighty King.',
                                                                 'ja': 'あなたは栄光に満ちた、力強い王です。'}}],
            [{'vi': 'Chúng con thật biết ơn bởi Cha hằng xót thương.', 'kr': {'ko': '늘 자비를 베푸시는 아버지께 참으로 감사드립니다.',
                                                                              'zh': '我們衷心感謝天父不斷施予的憐憫。',
                                                                              'en': 'We are truly grateful for your constant mercy.',
                                                                              'ja': '絶えず憐れみを示してくださる父に、心から感謝します。'}},
             {'vi': 'Ngài nghiêng tai nghe tiếng kêu cầu', 'kr': {'ko': '당신은 우리의 부르짖음에 귀를 기울이시고',
                                                                  'zh': '你側耳聆聽我們的呼求，',
                                                                  'en': 'You bend your ear to hear our cries',
                                                                  'ja': 'あなたは私たちの叫びに耳を傾け'}},
             {'vi': 'và gần bên quan tâm, chăm sóc.', 'kr': {'ko': '가까이 계시며 돌보아 주십니다.',
                                                             'zh': '親近我們，眷顧看顧我們。',
                                                             'en': 'and stay close, caring for us.',
                                                             'ja': 'そばにいて世話をしてくださいます。'}},
             {'vi': 'Chúa khuyên dạy chúng con bước theo đường thẳng ngay.', 'kr': {'ko': '주님은 우리가 올바른 길로 걷도록 훈계해 주십니다.',
                                                                                    'zh': '主教導我們走正直的道路。',
                                                                                    'en': 'The Lord instructs us to walk in the straight path.',
                                                                                    'ja': '主は私たちがまっすぐな道を歩むよう教え諭してくださいます。'}},
             {'vi': 'Hằng ngày Cha nâng đỡ, ủi an.', 'kr': {'ko': '아버지께서는 날마다 우리를 붙들어 주시고 위로해 주십니다.',
                                                            'zh': '天父天天扶持我們，安慰我們。',
                                                            'en': 'Every day our Father upholds and comforts us.',
                                                            'ja': '父は日々、私たちを支え、慰めてくださいます。'}}],
            [{'vi': 'Chúng con thành kính dâng tiếng ca ngợi đến Cha.', 'kr': {'ko': '우리는 경건한 마음으로 아버지께 찬양을 드립니다.',
                                                                               'zh': '我們懷著虔敬的心，向天父獻上讚美。',
                                                                               'en': 'We reverently offer up praise to our Father.',
                                                                               'ja': '私たちは敬虔な思いをもって、父に賛美をささげます。'}},
             {'vi': 'Bầu trời rao ra hiển vinh ngài,', 'kr': {'ko': '하늘은 당신의 영광을 선포하며,',
                                                              'zh': '諸天宣揚你的榮耀，',
                                                              'en': 'The heavens declare your glory,',
                                                              'ja': '天はあなたの栄光を宣言し'}},
             {'vi': 'vật muôn nơi tôn vinh danh thánh.', 'kr': {'ko': '만물이 곳곳에서 그 거룩한 이름을 영예롭게 합니다.',
                                                                'zh': '萬物處處尊崇你的聖名。',
                                                                'en': 'all creation everywhere honors your holy name.',
                                                                'ja': '万物はいたるところであなたの聖なる名をたたえます。'}},
             {'vi': 'Suốt trong đời chúng con hát khen Giê-hô-va,', 'kr': {'ko': '우리는 평생토록 여호와를 찬양하는 노래를 부르며,',
                                                                           'zh': '我們一生都要歌頌耶和華，',
                                                                           'en': 'All our life we will sing praises to Jehovah,',
                                                                           'ja': '私たちは生涯を通してエホバを賛美して歌い'}},
             {'vi': 'nguyện xin Cha nghe tiếng ngợi ca.', 'kr': {'ko': '아버지께서 우리의 찬양 소리를 들어 주시기를 기도합니다.',
                                                                 'zh': '願天父垂聽我們的頌讚之聲。',
                                                                 'en': 'We pray that our Father will hear our song of praise.',
                                                                 'ja': '父が私たちの賛美の声を聞いてくださるよう願います。'}}]
             ]},
 {'number': 18,
  'title_kr': {'ko': '대속 마련에 감사합니다',
               'zh': '感謝救贖的安排',
               'en': 'Thankful for the Ransom Arrangement',
               'ja': '贖いの備えに感謝します'},
  'title_vi': 'Biết ơn về giá chuộc',
  'scripture': 'Lu-ca 22:20',
  'verses': [[{'vi': 'Mọi người hôm nay đứng trước', 'kr': {'ko': '오늘 우리 모두는',
                                                           'zh': '今天，我們眾人站在',
                                                           'en': 'Today we all stand before',
                                                           'ja': '今日、私たちは皆'}},
             {'vi': 'ngôi Cha uy nghi, cao trọng.', 'kr': {'ko': '위엄 있고 존귀하신 아버지의 보좌 앞에 서 있습니다.',
                                                           'zh': '威嚴尊貴的天父寶座前。',
                                                           'en': 'your majestic, exalted throne, O Father.',
                                                           'ja': '威厳に満ちた尊い父の御座の前に立っています。'}},
             {'vi': 'Tạ ơn Chúa đã ban Con một', 'kr': {'ko': '독생자를 주신 주님께 감사드립니다.',
                                                        'zh': '感謝主賜下獨生子，',
                                                        'en': 'We thank the Lord for giving his only Son',
                                                        'ja': 'ひとり子を与えてくださった主に感謝します。'}},
             {'vi': 'chịu tội thay cho chúng con.', 'kr': {'ko': '그분은 우리를 위해 죄를 대신 짊어지셨습니다.',
                                                           'zh': '為我們代罪受苦。',
                                                           'en': 'to bear our sin in our place.',
                                                           'ja': '私たちの代わりに罪を負ってくださいました。'}},
             {'vi': 'Tình yêu thương Cha quá lớn!', 'kr': {'ko': '아버지의 사랑은 얼마나 크신지요!',
                                                           'zh': '天父的愛是何等浩大！',
                                                           'en': "How great is the Father's love!",
                                                           'ja': '父の愛はなんと大きいことでしょう。'}},
             {'vi': 'Chúng con được Cha thương xót,', 'kr': {'ko': '우리는 아버지의 자비를 입어',
                                                             'zh': '我們蒙天父憐憫，',
                                                             'en': "We have received the Father's mercy,",
                                                             'ja': '私たちは父の憐れみを受け'}},
             {'vi': 'sống trong hy vọng, hướng tới tương lai', 'kr': {'ko': '소망 안에서 살아가며 미래를 향해 나아갑니다.',
                                                                      'zh': '活在盼望之中，邁向未來，',
                                                                      'en': 'living in hope, looking toward a future',
                                                                      'ja': '希望のうちに生き、未来へと向かっています。'}},
             {'vi': 'đầy ân phước dư tràn', 'kr': {'ko': '그 미래는 넘치는 축복으로 가득합니다.',
                                                   'zh': '那充滿豐盛祝福的未來。',
                                                   'en': 'overflowing with rich blessings.',
                                                   'ja': 'それは豊かな祝福にあふれています。'}},
             {'vi': '(ĐIỆP KHÚC)', 'kr': {'ko': '(후렴)', 'zh': '（副歌）', 'en': '(CHORUS)', 'ja': '（コーラス）'}},
             {'vi': 'Nhờ nơi huyết báu Con một của Cha,', 'kr': {'ko': '아버지의 독생자가 흘리신 보배로운 피로 말미암아,',
                                                                 'zh': '藉著天父獨生子的寶血，',
                                                                 'en': "Through the precious blood of the Father's only Son,",
                                                                 'ja': '父のひとり子の尊い血のゆえに'}},
             {'vi': 'giờ ai tin Chúa sẽ được cứu chuộc.', 'kr': {'ko': '이제 믿는 사람은 누구나 구속받게 됩니다.',
                                                                 'zh': '現在凡信主的人都必得救贖。',
                                                                 'en': 'now everyone who believes in the Lord will be redeemed.',
                                                                 'ja': '今、主を信じる人は皆、贖われます。'}},
             {'vi': 'Một lòng tôn kính,', 'kr': {'ko': '우리는 한마음으로 경의를 표하며,',
                                                 'zh': '我們一心敬重，',
                                                 'en': 'With one heart, in reverence,',
                                                 'ja': '私たちは心を一つにして敬い'}},
             {'vi': 'chúng con ca khen danh ngài đời đời không thôi.', 'kr': {'ko': '영원토록 그치지 않고 그분의 이름을 찬양합니다.',
                                                                              'zh': '永永遠遠不停地頌讚他的名。',
                                                                              'en': 'we will praise his name forever without ceasing.',
                                                                              'ja': '永遠に絶えることなく、その名を賛美します。'}}],
            [{'vi': 'Vì yêu thương nên chính Đấng', 'kr': {'ko': '사랑으로 말미암아',
                                                           'zh': '出於愛，',
                                                           'en': 'Out of love,',
                                                           'ja': '愛のゆえに'}},
             {'vi': 'Ki-tô hy sinh thân mình,', 'kr': {'ko': '그리스도께서는 자신의 몸을 바치셨고,',
                                                       'zh': '基督獻上自己的身體，',
                                                       'en': 'Christ sacrificed his own body,',
                                                       'ja': 'キリストはご自分の体を犠牲にし'}},
             {'vi': 'chịu đau đớn, chết cho nhân loại,', 'kr': {'ko': '고통을 당하시고 인류를 위해 죽으셨으며,',
                                                                'zh': '為全人類受苦至死，',
                                                                'en': 'suffering and dying for mankind,',
                                                                'ja': '人類のために苦しみを受けて死なれました。'}},
             {'vi': 'đẩy lùi đêm đen tối tăm.', 'kr': {'ko': '어두운 밤을 물리치셨습니다.',
                                                       'zh': '驅散了黑暗的長夜。',
                                                       'en': 'driving back the dark night.',
                                                       'ja': '暗い夜を退けてくださいました。'}},
             {'vi': 'Nhờ ngài, mai đây chết chóc', 'kr': {'ko': '그분 덕분에 머지않아 죽음은',
                                                          'zh': '因著他，將來死亡',
                                                          'en': 'Because of him, death will one day',
                                                          'ja': '彼のおかげで、やがて死は'}},
             {'vi': 'sẽ luôn chìm trong quên lãng.', 'kr': {'ko': '영원히 잊혀지고 말 것입니다.',
                                                            'zh': '將永遠被遺忘。',
                                                            'en': 'be forever forgotten.',
                                                            'ja': '永遠に忘れ去られるでしょう。'}},
             {'vi': 'Chúng con vui mừng, háo hức trông mong', 'kr': {'ko': '우리는 기쁘고 설레는 마음으로',
                                                                     'zh': '我們滿心歡喜，殷切期待',
                                                                     'en': 'We rejoice, eagerly looking forward',
                                                                     'ja': '私たちは喜び、心を躍らせながら'}},
             {'vi': 'nhận sự sống muôn đời.', 'kr': {'ko': '영원한 생명을 받을 날을 고대합니다.',
                                                     'zh': '得享永遠的生命。',
                                                     'en': 'to receiving everlasting life.',
                                                     'ja': '永遠の命を受けることを待ち望んでいます。'}},
             {'vi': '(ĐIỆP KHÚC)', 'kr': {'ko': '(후렴)', 'zh': '（副歌）', 'en': '(CHORUS)', 'ja': '（コーラス）'}},
             {'vi': 'Nhờ nơi huyết báu Con một của Cha,', 'kr': {'ko': '아버지의 독생자가 흘리신 보배로운 피로 말미암아,',
                                                                 'zh': '藉著天父獨生子的寶血，',
                                                                 'en': "Through the precious blood of the Father's only Son,",
                                                                 'ja': '父のひとり子の尊い血のゆえに'}},
             {'vi': 'giờ ai tin Chúa sẽ được cứu chuộc.', 'kr': {'ko': '이제 믿는 사람은 누구나 구속받게 됩니다.',
                                                                 'zh': '現在凡信主的人都必得救贖。',
                                                                 'en': 'now everyone who believes in the Lord will be redeemed.',
                                                                 'ja': '今、主を信じる人は皆、贖われます。'}},
             {'vi': 'Một lòng tôn kính,', 'kr': {'ko': '우리는 한마음으로 경의를 표하며,',
                                                 'zh': '我們一心敬重，',
                                                 'en': 'With one heart, in reverence,',
                                                 'ja': '私たちは心を一つにして敬い'}},
             {'vi': 'chúng con ca khen danh ngài đời đời không thôi.', 'kr': {'ko': '영원토록 그치지 않고 그분의 이름을 찬양합니다.',
                                                                              'zh': '永永遠遠不停地頌讚他的名。',
                                                                              'en': 'we will praise his name forever without ceasing.',
                                                                              'ja': '永遠に絶えることなく、その名を賛美します。'}}]
             ]},
 {'number': 46,
  'title_kr': {'ko': '여호와여 감사합니다',
               'zh': '感謝你，耶和華',
               'en': 'Thank You, Jehovah',
               'ja': 'エホバ、感謝します'},
  'title_vi': 'Cảm tạ Cha Giê-hô-va',
  'scripture': '1 Tê-sa-lô-ni-ca 5:18',
  'verses': [[{'vi': 'Lạy Cha Giê-hô-va, xin cám ơn Cha đêm ngày,', 'kr': {'ko': '여호와 아버지, 밤낮으로 감사드립니다,',
                                                                          'zh': '耶和華天父啊，我們晝夜感謝你，',
                                                                          'en': 'Father Jehovah, we thank you day and night,',
                                                                          'ja': 'エホバなる父よ、昼も夜も感謝します。'}},
             {'vi': 'sự sáng Cha chiếu rọi trên chúng con rạng ngời.', 'kr': {'ko': '아버지의 빛이 우리 위에 찬란히 비춥니다.',
                                                                              'zh': '你的光輝燦爛地照耀在我們身上。',
                                                                              'en': 'your light shines brightly upon us.',
                                                                              'ja': 'あなたの光が私たちの上に輝いています。'}},
             {'vi': 'Tạ ơn Cha hết lòng vì phước ân kêu cầu ngài,', 'kr': {'ko': '당신을 부를 수 있는 은혜를 진심으로 감사드리며,',
                                                                           'zh': '我們全心感謝你賜下呼求你的恩典，',
                                                                           'en': 'We thank you with all our heart for the privilege of calling on you,',
                                                                           'ja': 'あなたを呼び求められる恵みに心から感謝し'}},
             {'vi': 'hầu chúng con cùng trao mọi lo lắng cho ngài.', 'kr': {'ko': '우리의 모든 염려를 당신께 맡길 수 있게 하십니다.',
                                                                            'zh': '好讓我們把一切憂慮都交託給你。',
                                                                            'en': 'so that we may cast all our worries upon you.',
                                                                            'ja': 'すべての思い煩いをあなたに委ねることができます。'}}],
            [{'vi': 'Lạy Cha Giê-hô-va, xin cám ơn ban Con một,', 'kr': {'ko': '여호와 아버지, 독생자를 주셔서 감사합니다,',
                                                                         'zh': '耶和華天父啊，感謝你賜下獨生子，',
                                                                         'en': 'Father Jehovah, thank you for giving your only Son,',
                                                                         'ja': 'エホバなる父よ、ひとり子を与えてくださり感謝します。'}},
             {'vi': 'do đức tin vững mạnh, nay thắng thế gian rồi.', 'kr': {'ko': '굳센 믿음으로 이제 세상을 이기셨습니다.',
                                                                            'zh': '他憑著堅定的信心，如今已經勝過了世界。',
                                                                            'en': 'through steadfast faith, he has now overcome the world.',
                                                                            'ja': '揺るがぬ信仰によって、今や世に打ち勝たれました。'}},
             {'vi': 'Tạ ơn Cha dắt dìu, dạy chúng con theo đường ngài', 'kr': {'ko': '우리를 인도하시고 당신의 길을 따르도록 가르치시니 감사합니다.',
                                                                               'zh': '感謝天父引導我們，教導我們遵行你的道路，',
                                                                               'en': 'We thank you for leading us and teaching us to follow your way,',
                                                                               'ja': '私たちを導き、あなたの道に従うよう教えてくださり感謝します。'}},
             {'vi': 'hầu chúng con làm theo lời thề ước dâng mình.', 'kr': {'ko': '우리가 헌신 서약을 지켜 나갈 수 있게 하십니다.',
                                                                            'zh': '好使我們履行獻身的誓約。',
                                                                            'en': 'so that we may fulfill our vow of dedication.',
                                                                            'ja': '献身の誓いを果たすことができるようにしてくださいます。'}}],
            [{'vi': 'Lạy Cha Giê-hô-va, xin cám ơn ban vinh dự', 'kr': {'ko': '여호와 아버지, 영예를 주셔서 감사합니다',
                                                                        'zh': '耶和華天父啊，感謝你賜下尊榮，',
                                                                        'en': 'Father Jehovah, thank you for the honor you give us',
                                                                        'ja': 'エホバなる父よ、光栄を与えてくださり感謝します。'}},
             {'vi': 'rao báo danh thánh ngài, chân lý cho bao người.', 'kr': {'ko': '당신의 거룩한 이름과 진리를 많은 사람에게 전하게 하십니다.',
                                                                              'zh': '讓我們向眾人宣揚你的聖名和真理。',
                                                                              'en': 'to proclaim your holy name and the truth to many people.',
                                                                              'ja': '聖なる名と真理を多くの人に宣べ伝えられるようにしてくださいます。'}},
             {'vi': 'Tạ ơn Cha xóa sạch mọi khổ đau mai không còn,', 'kr': {'ko': '머지않아 모든 고통을 깨끗이 없애 주실 것을 감사드리며,',
                                                                            'zh': '感謝天父，將來要徹底除去一切痛苦，',
                                                                            'en': 'We thank you that soon all suffering will be wiped away,',
                                                                            'ja': 'やがてすべての苦しみを完全に取り除いてくださることに感謝し'}},
             {'vi': 'và Nước trên trời mang lại ân phước muôn đời.', 'kr': {'ko': '하늘 왕국이 영원한 축복을 가져다줄 것입니다.',
                                                                            'zh': '天上的王國將帶來永遠的祝福。',
                                                                            'en': 'and the Kingdom in heaven will bring everlasting blessings.',
                                                                            'ja': '天の王国が永遠の祝福をもたらしてくれます。'}}]
             ]}]

PRAYER_TEMPLATE = {'note': None,
 'lines': [{'vi': 'Lạy Cha Giê-hô-va,',
            'kr': {'ko': '여호와 아버지께',
                   'zh': '親愛的天父耶和華，',
                   'en': 'Dear Father Jehovah,',
                   'ja': '天の父エホバ、'}},
           {'vi': 'Xin cám ơn Cha giúp chúng con nhóm lại để học thêm về lời Cha và học tiếng Việt.',
            'kr': {'ko': '저희가 모여서 아버지의 말씀에 대하여 더 배우고, 베트남어를 배우도록 도와 주셔서 감사합니다.',
                   'zh': '感謝你讓我們聚在一起，更深入地學習你的話語，也學習越南語。',
                   'en': 'Thank you for allowing us to gather together to learn more about your Word and to study Vietnamese.',
                   'ja': '私たちが共に集まり、あなたの言葉についてもっと学び、ベトナム語を学ぶことができるようにしてくださり、感謝いたします。'}},
           {'vi': 'Chúng con cám ơn Cha về sự sống mà Cha ban cho chúng con.',
            'kr': {'ko': '저희는 아버지께서 저희에게 주신 생명에 대해 감사합니다.',
                   'zh': '我們感謝你賜給我們生命。',
                   'en': 'We thank you for the life you have given us.',
                   'ja': 'あなたが私たちに与えてくださった命に感謝いたします。'}},
           {'vi': 'Chúng con cám ơn Cha cho phép chúng con tìm hiểu lời Cha.',
            'kr': {'ko': '저희는 아버지께서 저희가 아버지의 말씀을 공부하도록 허락해 주셔서 감사합니다.',
                   'zh': '我們感謝你容許我們研讀你的話語。',
                   'en': 'We thank you for allowing us to study your Word.',
                   'ja': 'あなたの言葉を研究することをお許しくださり、感謝いたします。'}},
           {'vi': 'Chúng con cám ơn Cha ban hy vọng cho chúng con qua Kinh Thánh.',
            'kr': {'ko': '저희는 아버지께서 성서를 통해서 저희에게 희망을 주셔서 감사합니다.',
                   'zh': '我們感謝你藉著聖經賜給我們希望。',
                   'en': 'We thank you for the hope you give us through the Bible.',
                   'ja': '聖書を通して私たちに希望を与えてくださり、感謝いたします。'}},
           {'vi': 'Chúng con cầu xin Cha ban thần khí thánh cho chúng con.',
            'kr': {'ko': '저희는 아버지께서 저희에게 성령을 주시기를 청합니다.',
                   'zh': '我們懇求你賜給我們聖靈。',
                   'en': 'We ask you to give us your holy spirit.',
                   'ja': '私たちに聖霊を与えてくださるようお願いいたします。'}},
           {'vi': 'Chúng con cầu xin Cha ban phước cho buổi học của chúng con.',
            'kr': {'ko': '저희는 아버지께서 저희의 공부 시간을 축복하시기를 청합니다.',
                   'zh': '我們懇求你祝福我們的學習時間。',
                   'en': 'We ask you to bless our time of study.',
                   'ja': '私たちの学びの時を祝福してくださるようお願いいたします。'}},
           {'vi': 'Chúng con cầu xin Cha giúp chúng con hiểu được bài học này.',
            'kr': {'ko': '저희는 아버지께서 저희가 이 과를 이해하도록 도와주시기를 청합니다.',
                   'zh': '我們懇求你幫助我們明白這一課。',
                   'en': 'We ask you to help us understand this lesson.',
                   'ja': '私たちがこのレッスンを理解できるよう、お助けください。'}},
           {'vi': 'Xin Cha che chở chúng con trong đời sống hằng ngày.',
            'kr': {'ko': '아버지께서 매일의 생활에서 저희를 보호해 주시옵소서.',
                   'zh': '求你在日常生活中保護我們。',
                   'en': 'Please protect us in our daily life.',
                   'ja': '日々の生活の中で私たちをお守りください。'}},
           {'vi': 'Xin Cha giúp chúng con khi gặp vấn đề khó khăn.',
            'kr': {'ko': '아버지께서 저희가 어려운 문제를 만날 때 도와 주시옵소서.',
                   'zh': '求你在我們遇到困難時幫助我們。',
                   'en': 'Please help us when we face difficult problems.',
                   'ja': '私たちが困難な問題に直面するとき、お助けください。'}},
           {'vi': 'Xin Cha giúp chúng con vâng lời Cha.',
            'kr': {'ko': '아버지께서 저희가 아버지의 말씀에 순종하도록 도와주시옵소서.',
                   'zh': '求你幫助我們順從你。',
                   'en': 'Please help us to obey you.',
                   'ja': 'あなたに従うことができるよう、お助けください。'}},
           {'vi': 'Xin Cha tha thứ tội lỗi của chúng con.',
            'kr': {'ko': '아버지께서 저희의 죄를 용서하여 주시옵소서.',
                   'zh': '求你饒恕我們的罪。',
                   'en': 'Please forgive our sins.',
                   'ja': '私たちの罪をお赦しください。'}},
           {'vi': 'Chúng con cầu nguyện nhân danh Chúa Giê-su Ki-tô.',
            'kr': {'ko': '예수 그리스도 이름으로 기도 드립니다.',
                   'zh': '我們奉基督耶穌的名禱告。',
                   'en': 'We pray in the name of Christ Jesus.',
                   'ja': 'キリスト・イエスの名によって祈ります。'}},
           {'vi': 'A-men.',
            'kr': {'ko': '아멘.', 'zh': '阿們。', 'en': 'Amen.', 'ja': 'アーメン。'}}]}
