# Hand-transcribed from the 16-week course PDF (pages 7-12): tones, alphabet, consonants, vowels.
#
# Translatable fields are stored as {"ko","zh","en","ja","de","fr"} dicts so js_json() (see build_app.py)
# serializes them straight into JS objects app_logic.js's T() helper can read directly. The 'ko' field
# always makes its pronunciation-comparison point against a Hangul character or syllable (e.g. "한글의
# 'ㅂ'처럼"). The 'zh'/'en'/'ja'/'de'/'fr' fields do NOT translate that Hangul reference -- each instead compares
# against a sound/letter native to its own language, falling back to "no exact match, closest to English ___"
# only where that language truly lacks the sound. NORTH_SOUTH_DIFFS' per-example "north"/"south" fields
# (e.g. "자[za]"), its 'mark'/'symbol' fields, and the remaining -n/-ên/-t/-anh,ach/-inh,ich,ênh,êch
# final-consonant rows' descriptive text are a literal Korean-based phonetic (Hangul jamo + IPA) notation
# and are deliberately left untranslated in every language, same as rhyme_data.py's "kr"/"example_kr" fields.

TONES = [{'name': 'Thanh ngang',
  'kr': {'ko': '단평성', 'zh': '橫聲', 'en': 'level tone', 'ja': '横声', 'de': 'Ebener Ton', 'fr': 'Ton égal'},
  'mark': 'a',
  'symbol': {'ko': '(부호 없음)',
             'zh': '（無符號）',
             'en': '(no mark)',
             'ja': '（記号なし）',
             'de': '(kein Zeichen)',
             'fr': '(aucun signe)'},
  'desc': {'ko': '가장 높은 곳에서 시작하여 그대로 유지됩니다. 평탄하게, 살짝 높은 톤으로.',
           'zh': '從最高處開始並保持不變。平坦地，用稍高的音調。',
           'en': 'Starts at the highest point and stays there. Flat, at a slightly high tone.',
           'ja': '最も高いところから始まり、そのまま維持されます。平坦に、やや高いトーンで。',
           'de': 'Beginnt auf mittlerer bis höherer Tonlage und bleibt gleichmäßig eben.',
           'fr': 'Commence sur un registre moyen à aigu et reste plat et régulier.'}},
 {'name': 'Thanh sắc',
  'kr': {'ko': '상성', 'zh': '銳聲', 'en': 'rising tone', 'ja': '鋭声', 'de': 'Steigender Ton', 'fr': 'Ton montant'},
  'mark': 'á',
  'symbol': '◤ (dấu sắc)',
  'desc': {'ko': '약간 높은 곳에서 출발하여 가장 높은 곳까지 올라갑니다. 짧고 강하게 치켜올림.',
           'zh': '從稍高的位置開始，上升到最高點。短促而有力地上揚。',
           'en': 'It starts from a slightly high point and rises to the highest point. A short, strong rise.',
           'ja': 'やや高い位置から始まり、最も高い位置まで上がります。短く強く上げます。',
           'de': 'Beginnt etwas höher und steigt steil und kraftvoll nach oben an.',
           'fr': 'Commence un peu plus haut et monte de façon brève et vive.'}},
 {'name': 'Thanh huyền',
  'kr': {'ko': '장평성', 'zh': '玄聲', 'en': 'falling tone', 'ja': '玄声', 'de': 'Fallender Ton', 'fr': 'Ton descendant'},
  'mark': 'à',
  'symbol': '◣ (dấu huyền)',
  'desc': {'ko': '보통 높은 점에서 출발하여 차츰 내려가기 시작하여 약간 낮은 지점에서 끝납니다.',
           'zh': '通常從高點開始，逐漸下降，最後在稍低的位置結束。',
           'en': 'It usually starts at a high point, gradually descends, and ends at a slightly lower point.',
           'ja': '通常、高い位置から始まり、次第に下がっていき、やや低い位置で終わります。',
           'de': 'Beginnt sanft und fällt allmählich gleichmäßig tief ab.',
           'fr': 'Commence doucement et descend progressivement vers un registre grave.'}},
 {'name': 'Thanh hỏi',
  'kr': {'ko': '회성',
         'zh': '問聲',
         'en': 'dipping tone',
         'ja': '問声',
         'de': 'Frageton (fallend-steigend)',
         'fr': 'Ton descendant-montant (interrogatif)'},
  'mark': 'ả',
  'symbol': '◡ (dấu hỏi)',
  'desc': {'ko': '높은 점에서 출발한 뒤 약간 낮은 곳까지 내려갔다가 보통 높은 점까지 다시 올라갑니다.',
           'zh': '從高點出發後，先下降到稍低的地方，然後再次上升到普通的高點。',
           'en': 'It starts from a high point, descends to a slightly lower place, and then usually rises again to a '
                 'high point.',
           'ja': '高い点から始まった後、やや低いところまで下がってから、通常は高い点まで再び上がります。',
           'de': 'Fällt zunächst nach unten ab und steigt dann fragend wieder an.',
           'fr': "Descend d'abord légèrement puis remonte comme pour poser une question."}},
 {'name': 'Thanh ngã',
  'kr': {'ko': '거성',
         'zh': '跌聲',
         'en': 'creaky-rising tone',
         'ja': '跌声',
         'de': 'Unterbrochen steigender Ton',
         'fr': 'Ton montant avec coup de glotte'},
  'mark': 'ã',
  'symbol': '~ (dấu ngã)',
  'desc': {'ko': '높은 점에서 출발하고 갑자기 약간 낮은 점을 통해 가장 높은 곳까지 올라간 후에 끝납니다.',
           'zh': '從高點出發，突然經過稍低的點後上升到最高處，然後結束。',
           'en': 'It starts from a high point, suddenly passes through a slightly lower point, rises to the highest '
                 'point, and then ends.',
           'ja': '高い点から始まり、突然やや低い点を通ってから最も高いところまで上がって終わります。',
           'de': 'Beginnt hoch, wird durch einen Kehlkopfverschluss kurz unterbrochen und steigt dann steil an.',
           'fr': 'Commence haut, subit une brève interruption glottale, puis monte nettement.'}},
 {'name': 'Thanh nặng',
  'kr': {'ko': '하성',
         'zh': '重聲',
         'en': 'heavy tone',
         'ja': '重声',
         'de': 'Schwerer fallender Ton',
         'fr': 'Ton lourd (descendant bref)'},
  'mark': 'ạ',
  'symbol': '● (dấu nặng)',
  'desc': {'ko': '보통 높은 곳에서 출발하여 가장 낮은 지점까지 내려가 짧고 무겁게 끝납니다.',
           'zh': '通常從高處出發，下降到最低點，短促而沉重地結束。',
           'en': 'It usually starts from a high place, descends to the lowest point, and ends short and heavy.',
           'ja': '通常高いところから始まり、最も低い地点まで下がって、短く重く終わります。',
           'de': 'Fällt sofort steil nach unten ab und bricht kurz und schwer ab.',
           'fr': "Descend très rapidement vers le registre le plus grave et s'interrompt de façon brève et lourde."}}]

ALPHABET = [['a', '[a]'], ['ă', '[á]'], ['â', '[ớ]'], ['b', '[bê]'], ['c', '[xê]'], ['d', '[dê]'], ['đ', '[đê]'], ['e', '[e]'],
 ['ê', '[ê]'], ['g', '[gờ]'], ['h', '[hát]'], ['i', '[i ngắn]'], ['k', '[ca]'], ['l', '[e-lờ]'], ['m', '[e-mờ]'],
 ['n', '[e-nờ]'], ['o', '[o]'], ['ô', '[ô]'], ['ơ', '[ơ]'], ['p', '[pê]'], ['q', '[cu]'], ['r', '[e-rờ]'],
 ['s', '[ét-sì]'], ['t', '[tê]'], ['u', '[u]'], ['ư', '[ư]'], ['v', '[vê]'], ['x', '[ích-xì]'], ['y', '[y dài]']]
ALPHABET_NOTE = {'ko': '베트남어 문자는 기본 29개 알파벳입니다. 영어의 f, j, w, z는 없고, ă, â, đ, ê, ô, ơ, ư가 추가로 있습니다.',
 'zh': '越南語文字基本上有29個字母。沒有英語中的f、j、w、z，但另外有ă、â、đ、ê、ô、ơ、ư。',
 'en': "The Vietnamese alphabet has 29 basic letters. It doesn't have the English f, j, w, z, but it has ă, â, đ, ê, "
       'ô, ơ, ư in addition.',
 'ja': 'ベトナム語の文字は基本29個のアルファベットです。英語のf、j、w、zはなく、ă、â、đ、ê、ô、ơ、ưが追加であります。',
 'de': 'Das vietnamesische Alphabet umfasst 29 Grundbuchstaben. Die Buchstaben f, j, w und z gibt es nicht, dafür aber '
       'zusätzlich ă, â, đ, ê, ô, ơ und ư.',
 'fr': "L'alphabet vietnamien comprend 29 lettres de base. Il ne possède pas les lettres f, j, w et z de l'alphabet "
       'latin standard, mais comprend en plus ă, â, đ, ê, ô, ơ et ư.'}

CONSONANTS_SIMPLE = [['b',
  {'ko': "한글의 'ㅂ'처럼 발음하지만 양 입술을 뗄 때 좀 더 세게 발음합니다.",
   'zh': '沒有完全對應的注音符號，發音類似英語的b音，但雙唇分開時發音更用力一些。',
   'en': "It's pronounced like the English b, but the lips separate more forcefully.",
   'ja': '日本語のバ行の子音のように発音しますが、両唇を離すときにもう少し強く発音します。',
   'de': 'Wird wie ein deutsches b ausgesprochen, jedoch lösen sich die Lippen etwas kräftiger (implosiv).',
   'fr': 'Se prononce comme le b français, mais les lèvres se détachent plus vigoureusement (implosive).'},
  'ba, bơ'],
 ['c, k, q',
  {'ko': "한글의 'ㄲ'처럼 발음합니다. q는 u로 시작하는 음 앞에만 옵니다.",
   'zh': '發音像注音符號的ㄍ（不送氣的k音）。q只出現在以u開頭的音之前。',
   'en': 'It\'s pronounced like the k in "skate" (unaspirated, without a puff of air), not like the k in "kite". q '
         'appears only before a sound beginning with u.',
   'ja': '日本語のカ行の子音のように発音します。qはuで始まる音の前にのみ来ます。',
   'de': 'Wird wie ein deutsches k ohne Aspiration (ohne Hauch) ausgesprochen. q steht nur vor Lauten, die mit u '
         'beginnen.',
   'fr': "Se prononce comme un k sans souffle (non aspiré). q n'apparaît que devant un son commençant par u."},
  'cô, kéo, qua'],
 ['d',
  {'ko': "한글의 'ㅈ'처럼 발음합니다.",
   'zh': '沒有完全對應的注音符號，發音類似英語的z音。',
   'en': "It's pronounced like the English z.",
   'ja': '日本語のザ行の子音のように発音します。',
   'de': 'Wird im Norden wie ein weiches, stimmhaftes deutsches s (wie in „Sonne“) ausgesprochen.',
   'fr': 'Dans le Nord, se prononce comme un z sonore (comme le s dans « rose »).'},
  'da, dơ'],
 ['đ',
  {'ko': "한글의 'ㄷ'처럼 발음합니다.",
   'zh': '沒有完全對應的注音符號，發音類似英語的d音。',
   'en': "It's pronounced like the English d.",
   'ja': '日本語のダ行の子音のように発音します。',
   'de': 'Wird wie ein deutsches d ausgesprochen, mit leichtem Kehlkopfverschluss (implosiv).',
   'fr': 'Se prononce comme un d français, avec une légère fermeture glottale (implosive).'},
  'đi, đê'],
 ['g',
  {'ko': "한글의 'ㄱ'처럼 발음합니다.",
   'zh': '沒有完全對應的注音符號，發音類似英語的g音（濁音）。',
   'en': 'It\'s pronounced like the English g (as in "go").',
   'ja': '日本語のガ行の子音のように発音します。',
   'de': 'Wird wie ein deutsches g (wie in „gut“) oder leicht reibend ausgesprochen.',
   'fr': 'Se prononce comme le g dur français (comme dans « gare ») ou légèrement frotté.'},
  'gà, gai'],
 ['h',
  {'ko': "한글의 'ㅎ'처럼 발음합니다.",
   'zh': '發音像注音符號的ㄏ。',
   'en': "It's pronounced like the English h.",
   'ja': '日本語のハ行の子音のように発音します。',
   'de': 'Wird wie das deutsche h (wie in „Haus“) ausgesprochen.',
   'fr': 'Se prononce comme un h expiré (comme en anglais ou en allemand).'},
  'ho, hô'],
 ['l',
  {'ko': "한글의 'ㄹ'처럼 발음합니다.",
   'zh': '發音像注音符號的ㄌ。',
   'en': "It's pronounced like the English l.",
   'ja': '日本語のラ行の子音のように発音します。',
   'de': 'Wird wie das deutsche l (wie in „Lampe“) ausgesprochen.',
   'fr': 'Se prononce comme le l français.'},
  'la, lê'],
 ['m',
  {'ko': "한글의 'ㅁ'처럼 발음합니다.",
   'zh': '發音像注音符號的ㄇ。',
   'en': "It's pronounced like the English m.",
   'ja': '日本語のマ行の子音のように発音します。',
   'de': 'Wird wie das deutsche m (wie in „Mutter“) ausgesprochen.',
   'fr': 'Se prononce comme le m français.'},
  'ma, mơ'],
 ['n',
  {'ko': "한글의 'ㄴ'처럼 발음합니다.",
   'zh': '發音像注音符號的ㄋ。',
   'en': "It's pronounced like the English n.",
   'ja': '日本語のナ行の子音のように発音します。',
   'de': 'Wird wie das deutsche n (wie in „Name“) ausgesprochen.',
   'fr': 'Se prononce comme le n français.'},
  'no, na'],
 ['p',
  {'ko': "한글의 'ㅃ'처럼 발음합니다.",
   'zh': '發音像注音符號的ㄅ。',
   'en': 'It\'s pronounced like the p in "spin" (unaspirated, without a puff of air), not like the p in "pin".',
   'ja': '日本語のパ行の子音のように発音します。',
   'de': 'Wird wie ein stimmloses p ohne Hauch (unaspiriert) ausgesprochen.',
   'fr': 'Se prononce comme un p sourd sans souffle (non aspiré).'},
  'pin, sa pa'],
 ['r',
  {'ko': "한글의 'ㅈ'처럼 발음합니다.",
   'zh': '沒有完全對應的注音符號，發音類似英語的z音。',
   'en': "It's pronounced like the English z.",
   'ja': '日本語のザ行の子音のように発音します。',
   'de': 'Wird im Norden wie ein weiches stimmhaftes s [z] gesprochen, im Süden als gerolltes Zungen-r.',
   'fr': 'Dans le Nord, se prononce comme un z sonore [z] ; dans le Sud, comme un r roulé.'},
  'ra, ru'],
 ['s',
  {'ko': "한글의 'ㅅ(ㅆ)'처럼 발음합니다.",
   'zh': '發音像注音符號的ㄙ。',
   'en': "It's pronounced like the English s.",
   'ja': '日本語のサ行の子音のように発音します。',
   'de': 'Wird im Norden wie ein scharfes s (wie in „Wasser“) ausgesprochen, im Süden eher wie sch [ʂ].',
   'fr': 'Dans le Nord, se prononce comme un s sourd (comme dans « sel ») ; dans le Sud, plutôt rétroflexe comme [ʂ].'},
  'so, sai'],
 ['t',
  {'ko': "한글의 'ㄸ'처럼 발음합니다.",
   'zh': '發音像注音符號的ㄉ。',
   'en': 'It\'s pronounced like the t in "stop" (unaspirated, without a puff of air), not like the t in "top".',
   'ja': '日本語のタ行の子音のように発音します。',
   'de': 'Wird wie ein t ohne Aspiration (ohne Hauch) ausgesprochen.',
   'fr': 'Se prononce comme un t sans souffle (non aspiré).'},
  'ta, to'],
 ['x',
  {'ko': "한글의 'ㅆ'처럼 발음합니다.",
   'zh': '發音像注音符號的ㄙ。',
   'en': "It's pronounced like the English s.",
   'ja': '日本語のサ行の子音のように発音します。',
   'de': 'Wird wie ein scharfes s (wie in „Wasser“) ausgesprochen.',
   'fr': 'Se prononce comme un s sourd (comme dans « sel »).'},
  'xa, xe'],
 ['v',
  {'ko': "한글에는 'v'에 해당하는 음이 없습니다. 윗입술을 앞으로 내밀어 이로 아래 입술을 약간 물어서 발음합니다.",
   'zh': "華語（國語）沒有與'v'對應的音。將上唇向前突出，用牙齒輕咬下唇發音。",
   'en': 'This is the same as the English v.',
   'ja': "日本語には'v'に相当する音がありません。上唇を前に突き出し、歯で下唇を軽く噛んで発音します。",
   'de': 'Wird wie das deutsche w ausgesprochen (die oberen Zähne berühren leicht die Unterlippe).',
   'fr': 'Se prononce comme le v français (les dents supérieures effleurent la lèvre inférieure).'},
  'và, với']]
CONSONANTS_COMPLEX = [['ch, tr',
  {'ko': "한글의 'ㅉ'처럼 발음합니다. 현대 베트남어에서 ch와 tr의 음은 거의 같게 발음되지만, 일부 지방에서 ch음은 조금 더 가볍게 발음됩니다.",
   'zh': '發音像注音符號的ㄐ（不送氣）。在現代越南語中，ch和tr的發音幾乎相同，但在一些地區，ch音會發得稍微輕一些。',
   'en': 'It\'s pronounced like the ch in "chip", but without a puff of air (unaspirated). In modern Vietnamese, ch '
         'and tr are pronounced almost the same, but in some regions the ch sound is pronounced a bit more lightly.',
   'ja': '日本語のチャ行の子音のように発音します。現代ベトナム語ではchとtrの音はほぼ同じように発音されますが、一部の地方ではch音がやや軽く発音されます。',
   'de': 'Wird wie ein tsch ohne Hauch ausgesprochen. Im modernen Vietnamesisch klingen ch und tr fast gleich, in '
         'einigen Regionen wird ch jedoch etwas leichter gesprochen.',
   'fr': 'Se prononce comme « tch » sans souffle (non aspiré). En vietnamien moderne, ch et tr se prononcent presque '
         'de la même façon, bien que ch soit parfois plus léger dans certaines régions.'},
  'cho, tro'],
 ['kh',
  {'ko': "한글의 'ㅋ'처럼 발음합니다.",
   'zh': '發音像注音符號的ㄎ。',
   'en': 'It\'s pronounced like the k in "kite" (aspirated, with a puff of air).',
   'ja': '日本語のカ行の子音のように発音しますが、息を強く出して発音します。',
   'de': 'Wird wie das deutsche ch in „Bach“ ([x]) oder als behauchtes k ausgesprochen.',
   'fr': 'Se prononce comme la jota espagnole ou le ch allemand de « Bach » ([x]).'},
  'khô, khi'],
 ['nh',
  {'ko': "한글의 '니'처럼 발음합니다.",
   'zh': '發音像注音符號的ㄋㄧ（舌面鼻音）。',
   'en': 'It\'s pronounced like the "ny" in "canyon" (a palatal nasal sound).',
   'ja': '日本語の「に」に近い音です。',
   'de': 'Wird wie das spanische ñ oder wie gn in „Cognac“ als Gaumen-Nasallaut [ɲ] ausgesprochen.',
   'fr': 'Se prononce comme le « gn » français dans « montagne » ou le ñ espagnol (nasale palatale [ɲ]).'},
  'nho, nhi'],
 ['th',
  {'ko': "한글의 'ㅌ'처럼 발음합니다.",
   'zh': '發音像注音符號的ㄊ。',
   'en': 'It\'s pronounced like the t in "top" (aspirated, with a puff of air).',
   'ja': '日本語のタ行の子音のように発音しますが、息を強く出して発音します。',
   'de': 'Wird wie ein stark behauchtes deutsches t (wie in „Tee“) ausgesprochen.',
   'fr': 'Se prononce comme un t fortement aspiré (avec un souffle net).'},
  'tha, thu'],
 ['ph',
  {'ko': "한글의 'ㅍ'에 해당하나 정확한 음은 없는 대신 영어의 f음처럼 발음합니다.",
   'zh': '沒有完全對應的注音符號，發音像英語的f音。',
   'en': "It's pronounced like the English f.",
   'ja': '日本語には正確に一致する音がなく、英語のf音のように発音します。',
   'de': 'Wird wie das deutsche f (wie in „Foto“) ausgesprochen.',
   'fr': 'Se prononce comme le f français.'},
  'phê, pho'],
 ['gh',
  {'ko': "한글의 'ㄱ'처럼 발음하나 e, ê, i 등의 모음 앞에 위치합니다.",
   'zh': '沒有完全對應的注音符號，發音類似英語的g音（濁音），但位於e, ê, i等元音之前。',
   'en': 'It\'s pronounced like the English g (as in "go"), but is placed before vowels such as e, ê, i.',
   'ja': '日本語のガ行の子音のように発音しますが、e, ê, iなどの母音の前に位置します。',
   'de': 'Wird wie das einfache g ausgesprochen, steht jedoch vor den Vokalen e, ê und i.',
   'fr': "Se prononce comme le g dur, mais s'écrit gh devant les voyelles e, ê et i."},
  'ghi, ghe'],
 ['ng, ngh',
  {'ko': "한글의 '응으'에 해당하나 한국 사람이 발음하기 어려운 비음입니다. e, ê, i 등의 모음 앞에서는 ngh로 씁니다.",
   'zh': '華語（國語）沒有這個音（華語的ng只出現在音節結尾），但閩南語（台語）中有以ng開頭的字，例如「硬」(ngē)，可以參考閩南語的發音方式。e, ê, i等元音前寫作ngh。',
   'en': 'English doesn\'t have this sound at the beginning of a word, only at the end (as in "sing"). Try saying '
         '"sing" and then just the "-ng" part, then move that sound to the front of a word. Before vowels such as e, '
         'ê, i, it is written as ngh.',
   'ja': '日本語にはこの音が語頭に来ることはありません（「ん」に近い鼻音です）。日本語話者にとっても発音が難しい音です。e, ê, iなどの母音の前ではnghと表記します。',
   'de': 'Entspricht dem deutschen ng-Laut (wie in „singen“), steht im Vietnamesischen jedoch auch am Wortanfang. Vor '
         'den Vokalen e, ê und i wird es als ngh geschrieben.',
   'fr': 'Correspond au son « ng » de « parking », mais peut se trouver en début de mot en vietnamien. Devant e, ê et '
         "i, il s'écrit ngh."},
  'nga, nghe'],
 ['gi',
  {'ko': "'d'음과 같게 발음하고 전통적인 철자법에서 쓰입니다.",
   'zh': "發音與'd'相同，用於傳統拼寫法中。",
   'en': "It's pronounced the same as 'd', and is used in traditional spelling.",
   'ja': "'d'と同じように発音し、伝統的な綴り方で使われます。",
   'de': 'Wird im Norden wie d (stimmhaftes s [z]) ausgesprochen und in der traditionellen Rechtschreibung verwendet.',
   'fr': "Dans le Nord, se prononce comme d (un z sonore [z]) ; c'est une graphie traditionnelle."},
  'gì, gia']]

# North (Hanoi-standard) vs South (Ho Chi Minh-standard) pronunciation differences.
# These are the handful of well-established, textbook-level contrasts: three consonant
# pairs the North merges but the South keeps distinct (d/gi/r, s/x, ch/tr), the "v"
# consonant softening toward a "y" glide in colloquial Southern speech, and the hỏi/ngã
# tone merger in the South. A closing note flags the more variable final-consonant
# (-n/-ng, -t/-c) shift without over-claiming a fixed rule for it.
NORTH_SOUTH_DIFFS = [{'title': 'd-, gi-, r-',
  'north': {'ko': "셋 다 한글의 'ㅈ'에 가까운 소리로 똑같이 발음해요.",
            'zh': '三者的發音都接近英語的z音，讀音完全相同（華語沒有完全對應的注音符號）。',
            'en': 'All three are pronounced exactly the same, close to the English z sound.',
            'ja': '三つとも日本語のザ行に近い音で、同じように発音します。',
            'de': 'Alle drei werden im Norden völlig gleich ausgesprochen, ähnlich einem weichen, stimmhaften s [z].',
            'fr': "Dans le Nord, tous les trois se prononcent de façon identique, proche d'un z sonore [z]."},
  'south': {'ko': "d와 gi는 영어 yes의 y처럼 반모음 'y'에 가깝게, r은 혀를 굴리는 'ㄹㄹ'(스페인어 r과 비슷)로 서로 다르게 발음해요.",
            'zh': "d和gi的發音接近半元音'y'，像英語yes中的y，而r則是捲舌顫音（類似西班牙語的r），兩者發音不同。",
            'en': "d and gi are pronounced close to the semivowel 'y', like the y in English yes, while r is "
                  'pronounced as a rolled r (similar to Spanish r) — the two are pronounced differently.',
            'ja': "dとgiは英語yesのyのように半母音'y'に近く、rは舌を巻く巻き舌音（スペイン語のrに似ている）で、互いに異なって発音します。",
            'de': 'd und gi werden wie ein j-Halbvokal [j] gesprochen, während r als gerolltes Zungen-r gesprochen '
                  'wird – sie werden also unterschieden.',
            'fr': 'Dans le Sud, d et gi se prononcent comme un y semi-voyelle [j], tandis que r se prononce comme un r '
                  'roulé — ils sont donc distingués.'},
  'examples': [{'word': 'da',
                'mean': {'ko': '피부', 'zh': '皮膚', 'en': 'skin', 'ja': '肌', 'de': 'Haut', 'fr': 'peau'},
                'north': '자[za]',
                'south': '야[ja]'},
               {'word': 'gia',
                'mean': {'ko': '집·더하다',
                         'zh': '家·加',
                         'en': 'house · to add',
                         'ja': '家·加える',
                         'de': 'Haus · hinzufügen',
                         'fr': 'maison · ajouter'},
                'north': '자[za]',
                'south': '야[ja]'},
               {'word': 'Giê-hô-va',
                'mean': {'ko': '여호와', 'zh': '耶和華', 'en': 'Jehovah', 'ja': 'エホバ', 'de': 'Jehova', 'fr': 'Jéhovah'},
                'north': '제호바[zɛhova]',
                'south': '예호바[jɛhova]'},
               {'word': 'Giê-su',
                'mean': {'ko': '예수', 'zh': '耶穌', 'en': 'Jesus', 'ja': 'イエス', 'de': 'Jesus', 'fr': 'Jésus'},
                'north': '제수[zɛsu]',
                'south': '예수[jɛsu]'},
               {'word': 'ra',
                'mean': {'ko': '나가다',
                         'zh': '出去',
                         'en': 'to go out',
                         'ja': '出る、出かける',
                         'de': 'hinausgehen',
                         'fr': 'sortir'},
                'north': '자[za]',
                'south': '굴린 라[ra]'}]},
 {'title': 's-, x-',
  'north': {'ko': "둘 다 한글의 'ㅅ(ㅆ)'처럼 똑같이 발음해요.",
            'zh': '兩者的發音都和注音符號的ㄙ相同。',
            'en': 'Both are pronounced exactly the same, like the English s.',
            'ja': '両方とも日本語のサ行と同じように発音します。',
            'de': 'Beide werden im Norden völlig gleich wie ein scharfes s [s] ausgesprochen.',
            'fr': 'Dans le Nord, les deux se prononcent de façon identique comme un s sourd [s].'},
  'south': {'ko': "x는 북부와 같이 'ㅅ(ㅆ)'로, s는 혀를 살짝 말아 올리는 권설음(捲舌音, 영어 sh와 비슷하지만 더 가벼움)으로 서로 다르게 발음해요.",
            'zh': 'x和北部一樣發ㄙ音，s則發捲舌音（捲舌音，類似英語sh，但更輕），兩者發音不同。',
            'en': 'x is pronounced like the English s, just like in the North, while s is pronounced as a retroflex '
                  'sound made by curling the tongue up slightly (similar to English sh, but lighter) — the two are '
                  'pronounced differently.',
            'ja': 'xは北部と同じくサ行の音で、sは舌を軽く巻き上げる巻き舌音（捲舌音、英語のshに似ているがより軽い）で、互いに異なって発音します。',
            'de': 'x wird wie im Norden als s gesprochen, s dagegen mit leicht zurückgebogener Zunge retroflex '
                  '(ähnlich einem weichen sch [ʂ]) – sie werden also unterschieden.',
            'fr': 'Dans le Sud, x se prononce [s] comme au Nord, tandis que s est rétroflexe avec la langue légèrement '
                  'relevée [ʂ] — ils sont donc distingués.'},
  'examples': [{'word': 'sa',
                'mean': {'ko': '떨어지다', 'zh': '掉落', 'en': 'to fall', 'ja': '落ちる', 'de': 'fallen', 'fr': 'tomber'},
                'north': '사[sa]',
                'south': '말아 올린 샤[ʂa]'},
               {'word': 'xa',
                'mean': {'ko': '멀다',
                         'zh': '遠',
                         'en': 'to be far',
                         'ja': '遠い',
                         'de': 'weit entfernt sein',
                         'fr': 'loin, être éloigné'},
                'north': '사[sa]',
                'south': '사[sa]'}]},
 {'title': 'ch-, tr-',
  'north': {'ko': "둘 다 한글의 'ㅉ'처럼 똑같이 발음해요.",
            'zh': '兩者的發音都和注音符號的ㄐ相同（不送氣）。',
            'en': 'Both are pronounced exactly the same, like the ch in "chip" (unaspirated).',
            'ja': '両方とも日本語のチャ行と同じように発音します。',
            'de': 'Beide werden im Norden völlig gleich wie ein unbehauchtes tsch [c] ausgesprochen.',
            'fr': 'Dans le Nord, les deux se prononcent de façon identique comme un « tch » non aspiré [c].'},
  'south': {'ko': "ch는 북부와 같이 'ㅉ'로, tr은 혀를 말아 올리는 권설음(영어 ch와 비슷하되 더 무거움)으로 서로 다르게 발음해요.",
            'zh': 'ch和北部一樣發ㄐ音，tr則發捲舌音（類似英語ch，但更重），兩者發音不同。',
            'en': 'ch is pronounced the same as in the North, while tr is pronounced as a retroflex sound made by '
                  'curling the tongue up (similar to English ch, but heavier) — the two are pronounced differently.',
            'ja': 'chは北部と同じくチャ行の音で、trは舌を巻き上げる巻き舌音（英語のchに似ているが、より重い）で、互いに異なって発音します。',
            'de': 'ch wird wie im Norden gesprochen, tr dagegen retroflex mit zurückgebogener Zunge [ʈʂ] – sie werden '
                  'also unterschieden.',
            'fr': 'Dans le Sud, ch se prononce comme au Nord, tandis que tr est rétroflexe avec la langue relevée [ʈʂ] '
                  '— ils sont donc distingués.'},
  'examples': [{'word': 'cha',
                'mean': {'ko': '아버지', 'zh': '父親', 'en': 'father', 'ja': '父', 'de': 'Vater', 'fr': 'père'},
                'north': '짜[ca]',
                'south': '짜[ca]'},
               {'word': 'tra',
                'mean': {'ko': '조사하다',
                         'zh': '調查',
                         'en': 'to investigate',
                         'ja': '調査する',
                         'de': 'untersuchen',
                         'fr': 'enquêter, vérifier'},
                'north': '짜[ca]',
                'south': '말아 올린 짜[ʈʂa]'}]},
 {'title': 'v-',
  'north': {'ko': '영어 v처럼 윗니로 아랫입술을 살짝 물어 발음해요.',
            'zh': '像英語的v一樣，用上齒輕咬下唇發音。',
            'en': "Like the English v, it's pronounced by lightly biting the lower lip with the upper teeth.",
            'ja': '英語のvのように、上の歯で下唇を軽く噛んで発音します。',
            'de': 'Wird wie ein deutsches w gesprochen, indem die oberen Zähne die Unterlippe leicht berühren.',
            'fr': 'Se prononce comme un v français, les dents du haut touchant légèrement la lèvre inférieure.'},
  'south': {'ko': '특히 편한 대화체에서는 d, gi처럼 반모음 y[j]에 가깝게 발음되고, 미엔 떠이(Miền Tây) 지역에서는 [z]처럼 발음하기도 해요.',
            'zh': '尤其在輕鬆的口語中，發音接近半元音y[j]，與d、gi相似，而在湄西（Miền Tây）地區，有時也會發成[z]。',
            'en': "Especially in casual spoken style, it's pronounced close to the semivowel y[j], like d and gi, and "
                  'in the Miền Tây region it is sometimes pronounced like [z].',
            'ja': '特に気楽な話し言葉では、d、giのように半母音y[j]に近く発音され、ミエンタイ（Miền Tây）地域では[z]のように発音されることもあります。',
            'de': 'Vor allem in der Umgangssprache nähert es sich wie d und gi dem Halbvokal j [j] an; im westlichen '
                  'Mekong-Delta (Miền Tây) wird es manchmal wie [z] gesprochen.',
            'fr': 'Dans le langage familier, il tend à se prononcer comme une semi-voyelle [j] (comme d et gi) ; dans '
                  'le delta du Mékong (Miền Tây), il est parfois prononcé [z].'},
  'examples': [{'word': 'về',
                'mean': {'ko': '돌아가다',
                         'zh': '回去',
                         'en': 'to go back / return',
                         'ja': '帰る',
                         'de': 'zurückkehren',
                         'fr': 'retourner, rentrer'},
                'north': '베[vɛ]',
                'south': '예[jɛ]'},
               {'word': 'Việt Nam',
                'mean': {'ko': '베트남', 'zh': '越南', 'en': 'Vietnam', 'ja': 'ベトナム', 'de': 'Vietnam', 'fr': 'Vietnam'},
                'north': '비엣남[viɛt̚ nam]',
                'south': '이엑남[jiɛk̚ nam]'}]},
 {'title': {'ko': 'hỏi, ngã 성조',
            'zh': 'hỏi, ngã 聲調',
            'en': 'hỏi, ngã tones',
            'ja': 'hỏi, ngã 声調',
            'de': 'Töne hỏi und ngã',
            'fr': 'Tons hỏi et ngã'},
  'north': {'ko': 'hỏi(낮게 내렸다 다시 오름)와 ngã(급격히 끊었다 오름)를 분명히 다른 성조로 구별해요.',
            'zh': 'hỏi（先降後升）和ngã（驟然中斷後上揚）明確區分為不同的聲調。',
            'en': 'hỏi (falling then rising) and ngã (abruptly cut off then rising) are clearly distinguished as '
                  'different tones.',
            'ja': 'hỏi（低く下げてから再び上げる）とngã（急に途切れてから上がる）を明確に異なる声調として区別します。',
            'de': 'hỏi (fallend-steigend) und ngã (unterbrochen-steigend) werden klar als zwei verschiedene Töne '
                  'unterschieden.',
            'fr': 'Le hỏi (descendant-montant) et le ngã (montant avec coupure) sont clairement distingués comme deux '
                  'tons différents.'},
  'south': {'ko': '두 성조를 구별하지 않고 거의 같은, 낮게 내려가는 소리로 발음하는 경우가 많아요. (글로 쓸 때는 두 지역 모두 구별해서 씁니다.)',
            'zh': '很多情況下不區分這兩種聲調，而是發成幾乎相同的低降調。（書寫時兩地都會加以區分。）',
            'en': 'In many cases, the two tones are not distinguished and are instead pronounced almost identically, '
                  'as a low falling tone. (In writing, both regions still distinguish them.)',
            'ja': '二つの声調を区別せず、ほぼ同じ低く下がる音で発音することが多いです。（文字で書くときは、両地域とも区別して書きます。）',
            'de': 'Im Süden werden beide Töne oft nicht unterschieden und klingen fast gleich wie ein tief fallender '
                  'Ton. (In der Schrift unterscheiden beide Regionen sie weiterhin.)',
            'fr': 'Dans le Sud, ces deux tons sont souvent confondus et prononcés de manière presque identique, comme '
                  "un ton grave descendant. (À l'écrit, ils restent distincts dans tout le pays.)"},
  'examples': [{'word': 'nghỉ',
                'mean': {'ko': '쉬다 (hỏi)',
                         'zh': '休息 (hỏi)',
                         'en': 'to rest (hỏi)',
                         'ja': '休む (hỏi)',
                         'de': 'sich ausruhen (hỏi)',
                         'fr': 'se reposer (hỏi)'},
                'north': '낮게 내렸다 오름',
                'south': '낮게 내려가는 소리'},
               {'word': 'nghĩ',
                'mean': {'ko': '생각하다 (ngã)',
                         'zh': '想、思考 (ngã)',
                         'en': 'to think (ngã)',
                         'ja': '考える (ngã)',
                         'de': 'denken, nachdenken (ngã)',
                         'fr': 'penser, réfléchir (ngã)'},
                'north': '끊었다 오름',
                'south': '낮게 내려가는 소리 (nghỉ와 비슷하게 들림)'}]},
 {'title': '-ây',
  'north': {'ko': '어이[ʌ̆j]로 발음해요.',
            'zh': '發音為어이[ʌ̆j]。',
            'en': "It's pronounced as 어이[ʌ̆j].",
            'ja': '어이[ʌ̆j]と発音します。',
            'de': 'Wird als [ʌ̆j] ausgesprochen.',
            'fr': 'Se prononce [ʌ̆j].'},
  'south': {'ko': '아이[ăj]로 발음해요.',
            'zh': '發音為아이[ăj]。',
            'en': "It's pronounced as 아이[ăj].",
            'ja': '아이[ăj]と発音します。',
            'de': 'Wird als [ăj] ausgesprochen.',
            'fr': 'Se prononce [ăj].'},
  'examples': [{'word': 'ấy',
                'mean': {'ko': '그',
                         'zh': '他；那',
                         'en': 'he; that',
                         'ja': '彼；その',
                         'de': 'jener, jene, das',
                         'fr': 'ce, cet, cette'},
                'north': '어이[ʌ̆j]',
                'south': '아이[ăj]'},
               {'word': 'vậy',
                'mean': {'ko': '그렇게',
                         'zh': '那樣',
                         'en': 'like that, so',
                         'ja': 'そのように',
                         'de': 'so, auf diese Weise',
                         'fr': 'ainsi, comme cela'},
                'north': 'vㅓ이[vʌ̆j]',
                'south': '야이[jăj]'}]},
 {'title': '-ê',
  'north': {'ko': '에[ɛ]로 발음해요.',
            'zh': '發音為에[ɛ]。',
            'en': "It's pronounced as 에[ɛ].",
            'ja': '에[ɛ]と発音します。',
            'de': 'Wird als [ɛ] ausgesprochen.',
            'fr': 'Se prononce [ɛ].'},
  'south': {'ko': '에이[ɛj]로 발음해요.',
            'zh': '發音為에이[ɛj]。',
            'en': "It's pronounced as 에이[ɛj].",
            'ja': '에이[ɛj]と発音します。',
            'de': 'Wird als [ɛj] ausgesprochen.',
            'fr': 'Se prononce [ɛj].'},
  'examples': [{'word': 'để',
                'mean': {'ko': '...하기 위해',
                         'zh': '為了……',
                         'en': 'in order to ...',
                         'ja': '…するために',
                         'de': 'um zu ...',
                         'fr': 'pour, afin de'},
                'north': '데[ɗɛ]',
                'south': '데이[ɗɛj]'},
               {'word': 'kể',
                'mean': {'ko': '이야기하다', 'zh': '說話/聊天', 'en': 'to talk', 'ja': '話す', 'de': 'erzählen', 'fr': 'raconter'},
                'north': '께[kɛ]',
                'south': '께이[kɛj]'}]},
 {'title': '-n',
  'north': {'ko': "-n 받침은 'ㄴ'[n] 받침으로 발음해요.",
            'zh': "-n收音發音為'ㄴ'[n]收音。",
            'en': "The -n final is pronounced as the 'ㄴ'[n] final.",
            'ja': "-nパッチムは'ㄴ'[n]パッチムで発音します。",
            'de': 'Der Auslaut -n wird als klares [n] gesprochen.',
            'fr': 'La finale -n se prononce comme un n alvéolaire [n].'},
  'south': {'ko': "-n 받침은 'ㅇ'[ŋ] 받침에 가깝게 발음해요.",
            'zh': "-n收音發音接近'ㅇ'[ŋ]收音。",
            'en': "The -n final is pronounced close to the 'ㅇ'[ŋ] final.",
            'ja': "-nパッチムは'ㅇ'[ŋ]パッチムに近く発音します。",
            'de': 'Der Auslaut -n wird dem velaren [ŋ] angenähert.',
            'fr': 'La finale -n se rapproche de la nasale vélaire [ŋ].'},
  'examples': [{'word': 'ăn',
                'mean': {'ko': '먹다', 'zh': '吃', 'en': 'to eat', 'ja': '食べる', 'de': 'essen', 'fr': 'manger'},
                'north': '안[an]',
                'south': '앙[aŋ]'},
               {'word': 'bốn',
                'mean': {'ko': '숫자 4', 'zh': '數字4', 'en': 'Number 4', 'ja': '数字4', 'de': 'Zahl 4', 'fr': 'chiffre 4'},
                'north': '본[ɓo:n]',
                'south': '봉[ɓo:ŋ͡m]'}]},
 {'title': '-ên',
  'north': {'ko': "-ên은 '엔'[ɛn]으로 발음해요.",
            'zh': '-ên發音為엔[ɛn]。',
            'en': '-ên is pronounced as 엔[ɛn].',
            'ja': '-ênは엔[ɛn]と発音します。',
            'de': 'Wird als [ɛn] ausgesprochen.',
            'fr': 'Se prononce [ɛn].'},
  'south': {'ko': "-ên은 '엉'[əŋ]에 가깝게 발음해요.",
            'zh': '-ên發音接近엉[əŋ]。',
            'en': '-ên is pronounced close to 엉[əŋ].',
            'ja': '-ênは엉[əŋ]に近く発音します。',
            'de': 'Wird eher wie [əŋ] ausgesprochen.',
            'fr': 'Se rapproche de [əŋ].'},
  'examples': [{'word': 'bên',
                'mean': {'ko': '쪽·측', 'zh': '邊·側', 'en': 'side · side', 'ja': '側·方', 'de': 'Seite', 'fr': 'côté'},
                'north': '벤[bɛn]',
                'south': '벙[bəŋ]'},
               {'word': 'tên',
                'mean': {'ko': '이름', 'zh': '名字', 'en': 'name', 'ja': '名前', 'de': 'Name', 'fr': 'nom'},
                'north': '뗀[tɛn]',
                'south': '떵[təŋ]'}]},
 {'title': '-t',
  'north': {'ko': "-t 받침은 'ㅅ' 받침으로 발음해요.",
            'zh': "-t收音發音為'ㅅ'收音。",
            'en': "The -t final is pronounced as the 'ㅅ' final.",
            'ja': "-tパッチムは'ㅅ'パッチムで発音します。",
            'de': 'Der Auslaut -t wird als dentales [t̚] gesprochen.',
            'fr': 'La finale -t se prononce comme une occlusive dentale [t̚].'},
  'south': {'ko': "-t 받침을 'ㄱ' 받침처럼 발음해요.",
            'zh': "-t收音發音像'ㄱ'收音一樣。",
            'en': "The -t final is pronounced like the 'ㄱ' final.",
            'ja': "-tパッチムを'ㄱ'パッチムのように発音します。",
            'de': 'Der Auslaut -t wird wie ein k-Schlusslaut [k̚] gesprochen.',
            'fr': 'La finale -t se prononce comme une occlusive vélaire [k̚].'},
  'examples': [{'word': 'một',
                'mean': {'ko': '숫자 1', 'zh': '數字1', 'en': 'Number 1', 'ja': '数字1', 'de': 'Zahl 1', 'fr': 'chiffre 1'},
                'north': '못[mot̚]',
                'south': '목[mok̚]'},
               {'word': 'kẹt',
                'mean': {'ko': '끼다',
                         'zh': '戴,套上',
                         'en': 'to wear (accessories), to put on',
                         'ja': 'はめる、着ける',
                         'de': 'steckenbleiben, eingeklemmt sein',
                         'fr': 'être coincé, bloqué'},
                'north': '깻[ket̚]',
                'south': '깩[kek̚]'}]},
 {'title': '-anh, -ach',
  'north': {'ko': "-a는 아이[ɐj]로 읽고, -nh는 'ㅇ'[ɲ] 받침으로, -ch는 'ㄱ'[k̚] 받침으로 발음해요.",
            'zh': "-a讀作아이[ɐj]，-nh發音為'ㅇ'[ɲ]收音，-ch發音為'ㄱ'[k̚]收音。",
            'en': "-a is read as 아이[ɐj], -nh is pronounced with the 'ㅇ'[ɲ] final, and -ch is pronounced with the "
                  "'ㄱ'[k̚] final.",
            'ja': "-aは아이[ɐj]と読み、-nhは'ㅇ'[ɲ]パッチムで、-chは'ㄱ'[k̚]パッチムで発音します。",
            'de': '-a wird als [ɐj] gesprochen, -nh als palatales [ɲ] und -ch als palatales [k̚].',
            'fr': '-a se prononce [ɐj], -nh comme nasale palatale [ɲ] et -ch comme occlusive palatale [k̚].'},
  'south': {'ko': "-a는 아[a]로 읽고, -nh는 'ㄴ'[n] 받침으로, -ch는 'ㅅ'[t̚] 받침으로 발음해요.",
            'zh': "-a讀作아[a]，-nh發音為'ㄴ'[n]收音，-ch發音為'ㅅ'[t̚]收音。",
            'en': "-a is read as 아[a], -nh is pronounced with the 'ㄴ'[n] final, and -ch is pronounced with the 'ㅅ'[t̚] "
                  'final.',
            'ja': "-aは아[a]と読み、-nhは'ㄴ'[n]パッチムで、-chは'ㅅ'[t̚]パッチムで発音します。",
            'de': '-a wird als [a] gesprochen, -nh als [n] und -ch als [t̚].',
            'fr': '-a se prononce [a], -nh comme [n] et -ch comme [t̚].'},
  'examples': [{'word': 'anh',
                'mean': {'ko': '형·오빠',
                         'zh': '哥哥',
                         'en': 'older brother',
                         'ja': '兄',
                         'de': 'älterer Bruder',
                         'fr': 'frère aîné'},
                'north': '아잉·아인의 중간[ʔɐjɲ]',
                'south': '안[an]'},
               {'word': 'sách',
                'mean': {'ko': '책', 'zh': '書', 'en': 'book', 'ja': '本', 'de': 'Buch', 'fr': 'livre'},
                'north': '사익[sɐjk̚]',
                'south': '삿[sat̚]'}]},
 {'title': '-inh, -ich / -ênh, -êch',
  'north': {'ko': 'inh·ênh, ich·êch를 앞모음(i/ê)에 따라 서로 다른 구개음으로 구별해서 발음해요.',
            'zh': 'inh·ênh、ich·êch根據前元音（i/ê）的不同，作為不同的顎音加以區分發音。',
            'en': 'inh·ênh and ich·êch are distinguished and pronounced as different palatal sounds depending on the '
                  'preceding vowel (i/ê).',
            'ja': 'inh·ênh、ich·êchを前舌母音（i/ê）に応じて、互いに異なる口蓋音として区別して発音します。',
            'de': 'inh·ênh und ich·êch werden je nach vorangehendem Vokal (i/ê) als unterschiedliche Gaumenlaute '
                  'unterschieden.',
            'fr': 'inh·ênh et ich·êch sont distingués comme des sons palataux différents selon la voyelle précédente '
                  '(i/ê).'},
  'south': {'ko': '구개음 색채가 옅어지면서, i 계열(linh, lịch)은 -ưn, -ưt에 가까운 소리로, ê 계열(kênh, ếch)은 -en, -et에 가까운 소리로 서로 다르게 합쳐지는 '
                  '경향이 있어요.',
            'zh': '隨著顎音色彩變淡，i系列（linh, lịch）趨向於接近-ưn, -ưt的音，ê系列（kênh, ếch）趨向於接近-en, -et的音，兩者呈現出不同的合併趨勢。',
            'en': 'As the palatal quality weakens, the i-series (linh, lịch) tends to merge toward a sound close to '
                  '-ưn, -ưt, while the ê-series (kênh, ếch) tends to merge toward a sound close to -en, -et — the two '
                  'merge differently.',
            'ja': '口蓋音的な色合いが薄れるにつれ、i系列（linh, lịch）は-ưn, -ưtに近い音へ、ê系列（kênh, ếch）は-en, -etに近い音へと、互いに異なる形で合流する傾向があります。',
            'de': 'Da der palatale Charakter schwächer wird, nähert sich die i-Reihe (linh, lịch) Lauten wie -ưn, -ưt '
                  'an, während die ê-Reihe (kênh, ếch) Lauten wie -en, -et ähnelt.',
            'fr': "Le caractère palatal s'estompant, la série en i (linh, lịch) tend vers -ưn, -ưt, tandis que la "
                  'série en ê (kênh, ếch) tend vers -en, -et.'},
  'examples': [{'word': 'linh',
                'mean': {'ko': '영(靈)', 'zh': '靈', 'en': 'spirit', 'ja': '霊', 'de': 'Geist', 'fr': 'esprit'},
                'north': '링·린의 중간[liɲ]',
                'south': '른[lɨn]'},
               {'word': 'lịch',
                'mean': {'ko': '달력·역사(曆/歷)',
                         'zh': '日曆·歷史(曆/歷)',
                         'en': 'calendar · history (曆/歷)',
                         'ja': '暦・歴史（曆/歴）',
                         'de': 'Kalender · Geschichte',
                         'fr': 'calendrier · histoire'},
                'north': '릭[lik̚]',
                'south': '릇[lɨt̚]'},
               {'word': 'kênh',
                'mean': {'ko': '채널·수로',
                         'zh': '頻道·水道',
                         'en': 'channel · waterway',
                         'ja': 'チャンネル·水路',
                         'de': 'Kanal · Wasserweg',
                         'fr': 'chaîne · canal'},
                'north': '께잉·께인의 중간[kejɲ]',
                'south': '껜[ken]'},
               {'word': 'ếch',
                'mean': {'ko': '개구리', 'zh': '青蛙', 'en': 'frog', 'ja': 'カエル', 'de': 'Frosch', 'fr': 'grenouille'},
                'north': '에익[ejk̚]',
                'south': '엣[et̚]'}]}]
NORTH_SOUTH_NOTE = {'ko': "-anh/-ach, -inh/-ich, -ênh/-êch의 남부식 발음은 화자·지역에 따라 편차가 커서, 위 예시는 '이런 경향이 있다' 정도로 참고해 주세요. 이 밖에 일부 남부 지역에서는 받침 "
       '-n/-ng, -t/-c의 발음이 서로 가까워지는 경향도 있지만, 마찬가지로 정해진 규칙으로 배우기는 어려워요.',
 'zh': '-anh/-ach、-inh/-ich、-ênh/-êch的南部發音因說話者和地區而異，差異較大，上面的例子僅供參考，理解為“有這種傾向”即可。此外，部分南部地區韻尾 -n/-ng、-t/-c '
       '的發音也有互相接近的傾向，但同樣很難當作固定規則來學習。',
 'en': 'The Southern pronunciation of -anh/-ach, -inh/-ich, and -ênh/-êch varies considerably by speaker and region, '
       'so please take the examples above only as "a general tendency." In addition, in some Southern regions the '
       'pronunciations of the final consonants -n/-ng and -t/-c also tend to converge, but likewise this is difficult '
       'to learn as a fixed rule.',
 'ja': '-anh/-ach、-inh/-ich、-ênh/-êchの南部式発音は話者や地域によって差が大きいため、上記の例は「そのような傾向がある」程度の参考としてください。このほか一部の南部地域では、末子音 '
       '-n/-ng、-t/-c の発音が互いに近づく傾向もありますが、同様に決まった規則として学ぶのは難しいです。',
 'de': 'Die südliche Aussprache von -anh/-ach, -inh/-ich und -ênh/-êch variiert je nach Sprecher und Region erheblich, '
       'daher dienen die obigen Beispiele nur als allgemeine Orientierung. Zudem neigen in einigen südlichen Regionen '
       'auch die Auslaute -n/-ng und -t/-c dazu, sich anzunähern, was sich jedoch nicht als feste Regel '
       'verallgemeinern lässt.',
 'fr': 'La prononciation méridionale de -anh/-ach, -inh/-ich et -ênh/-êch varie considérablement selon les locuteurs '
       "et les régions ; les exemples ci-dessus ne sont donc donnés qu'à titre de tendance générale. De plus, dans "
       "certaines régions du Sud, les consonnes finales -n/-ng et -t/-c ont aussi tendance à se rapprocher, sans qu'il "
       "soit possible d'en faire une règle fixe."}
NORTH_SOUTH_EXTRA_NOTES = [{'ko': '하노이 발음을 기준으로, 파열음 /p, t, k/는 음절 끝에서 불파음화되어 각각 [p̚, t̚, k̚]로 실현돼요. (위 표에서 ̚ 표시가 이를 나타내요.)',
  'zh': '以河內發音為準，塞音/p, t, k/在音節末尾會變為不除阻音，分別實現為[p̚, t̚, k̚]。（上表中的 ̚ 符號即表示這一點。）',
  'en': 'Based on Hanoi pronunciation, the stops /p, t, k/ become unreleased at the end of a syllable, realized as '
        '[p̚, t̚, k̚] respectively. (The ̚ mark in the table above indicates this.)',
  'ja': 'ハノイ発音を基準に、破裂音/p, t, k/は音節の終わりで内破音化し、それぞれ[p̚, t̚, k̚]として実現されます。（上の表の ̚ の印がこれを表します。）',
  'de': 'Ausgehend von der Aussprache in Hanoi werden die Plosive /p, t, k/ am Silbenende nicht gelöst (implosiv) und '
        'als [p̚, t̚, k̚] realisiert. (Das Zeichen ̚ in der Tabelle oben zeigt dies an.)',
  'fr': 'Dans la prononciation de Hanoï, les occlusives /p, t, k/ en fin de syllabe ne sont pas relâchées (implosives) '
        "et sont réalisées sous les formes [p̚, t̚, k̚]. (Le symbole ̚ dans le tableau ci-dessus l'indique.)"},
 {'ko': '하노이 지방의 모음은 기본적으로 9개이며, 이 중 â[ʌ̆]와 ă[ă]는 다른 모음보다 짧게 발음돼요. â[ʌ̆]와 ơ[ɤ]의 차이는 그리 두드러지지 않아서, 인지적으로 구별이 되는지도 분명하지 '
        '않아요.',
  'zh': '河內地區的元音基本上有9個，其中â[ʌ̆]和ă[ă]比其他元音發音更短。â[ʌ̆]和ơ[ɤ]之間的差異並不十分明顯，因此在認知上是否能夠區分也並不清楚。',
  'en': 'Hanoi has basically 9 vowels, among which â[ʌ̆] and ă[ă] are pronounced shorter than the other vowels. The '
        "difference between â[ʌ̆] and ơ[ɤ] is not very pronounced, so it's not even clear whether it is cognitively "
        'distinguishable.',
  'ja': 'ハノイ地方の母音は基本的に9個あり、そのうちâ[ʌ̆]とă[ă]は他の母音より短く発音されます。â[ʌ̆]とơ[ɤ]の違いはあまり目立たないため、認知的に区別されているのかもはっきりしません。',
  'de': 'Im Dialekt von Hanoi gibt es im Wesentlichen 9 Vokale, von denen â[ʌ̆] und ă[ă] kürzer als die übrigen Vokale '
        'ausgesprochen werden. Der Unterschied zwischen â[ʌ̆] und ơ[ɤ] ist wenig ausgeprägt, sodass er kaum '
        'wahrnehmbar ist.',
  'fr': 'Le dialecte de Hanoï compte essentiellement 9 voyelles, parmi lesquelles â[ʌ̆] et ă[ă] sont prononcées plus '
        "brièvement que les autres. La différence entre â[ʌ̆] et ơ[ɤ] est si peu marquée qu'il est difficile de les "
        "distinguer nettement à l'oreille."},
 {'ko': '모음 i, ư, u([i], [ɨ], [u])는 자음 k, ng 앞에서는 [ɪ], [ɪ̈], [ʊ]로 발음돼요. 모음 표기가 항상 일관적이면 좋겠지만 실제로는 그렇지 않아서, 이중모음이나 받침이 '
        '있는 모음에서는 소리가 미묘하게 달라지는 경우가 있어요.',
  'zh': '元音i, ư, u（[i], [ɨ], [u]）在輔音k, ng前會發成[ɪ], [ɪ̈], [ʊ]。雖然希望元音標記始終保持一致，但實際上並非如此，因此在雙元音或帶韻尾的元音中，讀音有時會出現細微的差異。',
  'en': 'The vowels i, ư, u ([i], [ɨ], [u]) are pronounced as [ɪ], [ɪ̈], [ʊ] before the consonants k, ng. It would be '
        'nice if vowel notation were always consistent, but in reality it is not, so in diphthongs or vowels with a '
        'final consonant, the sound sometimes differs subtly.',
  'ja': '母音i, ư, u（[i], [ɨ], [u]）は子音k, ngの前では[ɪ], [ɪ̈], '
        '[ʊ]と発音されます。母音表記が常に一貫していればよいのですが、実際にはそうではないため、二重母音やパッチムのある母音では、音が微妙に異なる場合があります。',
  'de': 'Die Vokale i, ư, u ([i], [ɨ], [u]) werden vor den Konsonanten k und ng als [ɪ], [ɪ̈], [ʊ] gesprochen. Die '
        'Vokalschreibung ist in der Praxis nicht immer völlig einheitlich, sodass bei Diphthongen oder Vokalen mit '
        'Auslautkonsonant subtile Klangunterschiede auftreten können.',
  'fr': 'Les voyelles i, ư, u ([i], [ɨ], [u]) se prononcent [ɪ], [ɪ̈], [ʊ] devant les consonnes k et ng. La notation '
        "des voyelles n'étant pas toujours totalement uniforme dans la pratique, de subtiles variations peuvent "
        "apparaître dans les diphtongues ou les voyelles suivies d'une consonne finale."}]

VOWELS_SIMPLE = [['a',
  {'ko': "한글의 '아'에 해당합니다.",
   'zh': '相當於注音符號的ㄚ。',
   'en': 'It corresponds to the a in "father".',
   'ja': '日本語の「ア」に相当します。',
   'de': 'Entspricht dem offenen deutschen a (wie in „Vater“).',
   'fr': 'Correspond au son « a » ouvert du français (comme dans « papa »).'},
  'anh, cha'],
 ['ă',
  {'ko': "한글의 '아'에 해당하지만 위의 a와 비교할 때 입을 더 크게 벌리고 더 짧게 발음합니다.",
   'zh': '相當於注音符號的ㄚ，但與上面的a相比，嘴張得更大，發音更短。',
   'en': 'It corresponds to the a in "father", but compared to the a above, the mouth opens wider and it\'s pronounced '
         'shorter.',
   'ja': '日本語の「ア」に相当しますが、上のaと比べて口をより大きく開け、より短く発音します。',
   'de': 'Entspricht dem deutschen a, wird jedoch mit weiter geöffnetem Mund und deutlich kürzer ausgesprochen.',
   'fr': 'Correspond au son « a », mais prononcé plus brièvement et avec la bouche plus ouverte.'},
  'đắt, sắt'],
 ['â',
  {'ko': "한글의 '어'에 해당하지만 아래의 ơ와 비교할 때 입의 더 안쪽에서 더 짧게 발음합니다.",
   'zh': '相當於注音符號的ㄜ，但與下面的ơ相比，發音位置更靠口腔內側，且更短。',
   'en': 'It corresponds to the u in "cup" (a short, central vowel), but compared to the ơ below, it\'s pronounced '
         'further back in the mouth and shorter.',
   'ja': '日本語には正確に一致する音がありませんが、「ア」を口の奥のほうで短く発音したような音です。下のơと比べて、より奥でより短く発音します。',
   'de': 'Ein kurzer, zentraler Vokal, der im Vergleich zu ơ weiter hinten im Mundraum und kürzer gesprochen wird.',
   'fr': 'Voyelle centrale brève, prononcée plus en arrière dans la bouche et plus court que ơ.'},
  'mất, mật'],
 ['e',
  {'ko': "한글의 '애'에 해당하지만 입을 옆으로 넓게 벌리고 짧게 발음합니다.",
   'zh': '相當於注音符號的ㄝ，但嘴向兩側張得更寬，發音更短。',
   'en': 'It corresponds to the e in "bed", but the mouth is opened wide sideways and it\'s pronounced shorter.',
   'ja': '日本語の「エ」に相当しますが、口を横に大きく広げて短く発音します。',
   'de': 'Entspricht einem offenen kurzen e (wie in „Bett“), die Mundwinkel sind breit gezogen.',
   'fr': 'Correspond au son « è » ouvert (comme dans « fête »), les lèvres étirées vers les côtés.'},
  'nghe, khe'],
 ['ê',
  {'ko': "한글의 '에'에 해당하지만 e에 비해 약간 길게 발음합니다.",
   'zh': '相當於注音符號的ㄝ，但比e發音稍長一些。',
   'en': 'It corresponds to the e in "bed", but is pronounced slightly longer than e.',
   'ja': '日本語の「エ」に相当しますが、eに比べてやや長く発音します。',
   'de': 'Entspricht einem geschlosseneren deutschen e (wie in „See“), etwas länger als das offene e.',
   'fr': 'Correspond au son « é » fermé (comme dans « été »).'},
  'đê, dê'],
 ['i',
  {'ko': "한글의 '이'에 해당하는 음으로 짧게 발음합니다.",
   'zh': '是相當於注音符號ㄧ的音，發音較短。',
   'en': 'It is a sound corresponding to the ee in "see", pronounced short.',
   'ja': '日本語の「イ」に相当する音で、短く発音します。',
   'de': 'Entspricht einem kurzen deutschen i.',
   'fr': 'Correspond au son « i » bref du français.'},
  'đi, thi'],
 ['y',
  {'ko': "한글의 '이'에 해당하는 음으로 길게 발음합니다.",
   'zh': '是相當於注音符號ㄧ的音，發音較長。',
   'en': 'It is a sound corresponding to the ee in "see", pronounced long.',
   'ja': '日本語の「イ」に相当する音で、長く発音します。',
   'de': 'Entspricht dem deutschen i, wird jedoch in der Regel etwas länger gehalten.',
   'fr': 'Correspond au son « i », mais généralement prononcé plus longuement.'},
  'yêu, yên'],
 ['o',
  {'ko': "한글의 '오'에 해당하지만 입모양은 '어'발음처럼 입을 크게 벌리고 발음합니다.",
   'zh': '相當於注音符號的ㄛ，但發音時嘴巴張得更大，接近ㄜ的口型。',
   'en': 'It\'s similar to the o in "saw", pronounced with the mouth opened wide, similar to the mouth shape for the u '
         'in "cup".',
   'ja': '日本語の「オ」に近い音ですが、「ア」に近い口の開け方でより大きく口を開けて発音します。',
   'de': 'Entspricht einem offenen o (wie in „offen“), mit weiter geöffnetem Mund.',
   'fr': 'Correspond au son « o » ouvert (comme dans « pomme »), la bouche bien ouverte.'},
  'no, ho'],
 ['ô',
  {'ko': "한글의 '오'에 해당합니다.",
   'zh': '相當於注音符號的ㄛ。',
   'en': 'It corresponds to the o in "boat" (without the "w" glide at the end).',
   'ja': '日本語の「オ」に相当します。',
   'de': 'Entspricht dem geschlossenen deutschen o (wie in „Boot“).',
   'fr': 'Correspond au son « o » fermé (comme dans « beau » ou « tôt »).'},
  'khô, cô'],
 ['ơ',
  {'ko': "한글의 '어'에 해당합니다.",
   'zh': '相當於注音符號的ㄜ。',
   'en': 'It corresponds to the u in "cup".',
   'ja': '日本語には正確に一致する音がありませんが、「ア」と「オ」の中間のような音です。',
   'de': 'Ein ungerundeter Vokal zwischen a und o, ähnlich dem Laut in „cup“.',
   'fr': 'Voyelle intermédiaire non arrondie entre a et o, proche du « e » caduc mais plus ouverte.'},
  'mơ, tơ'],
 ['u',
  {'ko': "한글의 '우'에 해당합니다.",
   'zh': '相當於注音符號的ㄨ。',
   'en': 'It corresponds to the oo in "food".',
   'ja': '日本語の「ウ」よりも唇を丸めて発音します。',
   'de': 'Entspricht dem geschlossenen deutschen u (wie in „Mut“).',
   'fr': 'Correspond au son « ou » français (comme dans « loup »).'},
  'ru, thu'],
 ['ư',
  {'ko': "한글의 '으'에 해당합니다.",
   'zh': '相當於注音符號的ㄨ，但嘴唇不要圓起來，保持扁平發音。',
   'en': 'It\'s like the oo in "food", but without rounding the lips — keep the lips relaxed and flat.',
   'ja': '日本語の「ウ」に相当します。',
   'de': 'Wird wie ein u gesprochen, jedoch ohne die Lippen zu runden – die Lippen bleiben flach entspannt.',
   'fr': 'Se prononce comme « ou », mais sans arrondir les lèvres — les lèvres restent détendues et plates.'},
  'sư, hư']]
VOWELS_COMPLEX = [['iê, yê',
  {'ko': "한글의 '이에'에 해당하지만 단어를 만들 때는 뒤에 자음을 반드시 동반해야 합니다.",
   'zh': '相當於注音符號的ㄧㄝ，但構成單詞時後面必須伴隨輔音。',
   'en': 'It corresponds to the "ye" sound (as in "yes"), but when forming a word, it must be followed by a consonant.',
   'ja': '日本語の「イエ」に相当しますが、単語を作るときは後ろに子音を必ず伴わなければなりません。',
   'de': 'Entspricht einem „ie-e“-Diphthong; im Wort muss immer ein Endkonsonant folgen.',
   'fr': "Correspond à la diphtongue « i-é » ; dans un mot, elle doit obligatoirement être suivie d'une consonne."},
  'biết, yên'],
 ['ia',
  {'ko': "한글의 '이아'에 해당하지만, ia는 '이어'로 발음합니다.",
   'zh': '相當於注音符號的ㄧㄚ，但ia發音為ㄧ加上ㄜ（類似iê）。',
   'en': 'It corresponds to "ia" (ee-ah), but ia is pronounced as "i" plus the u in "cup" (similar to iê).',
   'ja': '「イア」に相当しますが、iaは「イ」の後にア-オの中間の音（iêと同様）を続けて発音します。',
   'de': 'Entspricht i plus einem zentralen Vokal (ähnlich wie iê, steht am Wortende ohne Endkonsonant).',
   'fr': "Correspond à « i » suivi d'une voyelle centrale (similaire à iê, mais sans consonne finale)."},
  'kia'],
 ['oa, ua',
  {'ko': "한글의 '오아, 우아'에 해당합니다.",
   'zh': '相當於注音符號的ㄛㄚ、ㄨㄚ。',
   'en': 'It corresponds to "oa" (as in "oh-ah") and "ua" (as in "oo-ah").',
   'ja': '日本語の「オア」「ウア」に相当します。',
   'de': 'Entspricht „o-a“ bzw. „u-a“ als gleitender Doppellaut.',
   'fr': 'Correspond aux sons glissés « ou-a ».'},
  'khoa, qua'],
 ['ưa, ươ',
  {'ko': "한글의 '으아, 으어'에 해당합니다. 현대 베트남어에서 ưa는 '으어'로 발음합니다.",
   'zh': '相當於ư（不圓唇的ㄨ）加ㄚ、ư加ㄜ。在現代越南語中，ưa發音為ươ。',
   'en': 'It corresponds to ư + a and ư + ơ (see ư and ơ above). In modern Vietnamese, ưa is pronounced as ươ.',
   'ja': 'ư（唇を丸めない「ウ」）+ア、ư+ơ（ア-オの中間の音）に相当します。現代ベトナム語ではưaはươと発音します。',
   'de': 'Kombination aus ư und a bzw. ơ. Im modernen Vietnamesisch wird ưa praktisch wie ươ gesprochen.',
   'fr': 'Combinaison de ư et a ou ơ. En vietnamien moderne, ưa se prononce pratiquement comme ươ.'},
  'mưa, mười'],
 ['oă, uă',
  {'ko': "한글의 '오아, 우아'에 해당합니다.",
   'zh': '相當於注音符號的ㄛㄚ、ㄨㄚ。',
   'en': 'It corresponds to "oa" (as in "oh-ah") and "ua" (as in "oo-ah").',
   'ja': '日本語の「オア」「ウア」に相当します。',
   'de': 'Entspricht gleitenden Lauten o/u plus kurzem ă.',
   'fr': "Correspond aux sons glissés o/ou suivis d'un ă bref."},
  'xoăn, quăn'],
 ['uơ, uâ',
  {'ko': "한글의 '우어'에 해당하며 â는 ơ보다 짧게 발음합니다.",
   'zh': '相當於ㄨ加ㄜ，â的發音比ơ更短。',
   'en': 'It corresponds to u + ơ (the u in "cup"), and â is pronounced shorter than ơ.',
   'ja': '「ウ」+ơ（ア-オの中間の音）に相当し、âはơより短く発音します。',
   'de': 'Entspricht u plus ơ, wobei â kürzer als ơ ausgesprochen wird.',
   'fr': 'Correspond à ou + ơ, â étant prononcé plus brièvement que ơ.'},
  'quơ, quân'],
 ['ue, oe',
  {'ko': "한글의 '우애, 오애'에 해당합니다.",
   'zh': '相當於注音符號的ㄨㄝ、ㄛㄝ。',
   'en': 'It corresponds to "ue" (oo-eh) and "oe" (oh-eh).',
   'ja': '「ウエ」「オエ」に相当します。',
   'de': 'Entspricht „u-e“ bzw. „o-e“.',
   'fr': 'Correspond à « ou-è ».'},
  'que, xoe'],
 ['uê',
  {'ko': "한글의 '우에'에 해당하지만 입술을 더 작게 오므려 발음합니다.",
   'zh': '相當於ㄨㄝ（ê音較長），但發音時嘴唇撮得更小。',
   'en': 'It corresponds to u + ê, but is pronounced with the lips pursed more tightly.',
   'ja': '「ウエ」に相当しますが、唇をより小さくすぼめて発音します。',
   'de': 'Entspricht u plus ê, wobei die Lippen enger gespitzt werden.',
   'fr': 'Correspond à ou + ê, les lèvres étant plus serrées.'},
  'quê, khuê'],
 ['uy',
  {'ko': "한글의 '우이'에 해당합니다.",
   'zh': '相當於注音符號的ㄨㄧ。',
   'en': 'It corresponds to "uy" (oo-ee).',
   'ja': '「ウイ」に相当します。',
   'de': 'Entspricht einem gleitenden „u-i“ ([wi]).',
   'fr': 'Correspond au son glissé « ou-i » ([wi]).'},
  'tuy, huy'],
 ['uyê',
  {'ko': "한글의 '우예'를 빠르게 연속하여 발음합니다.",
   'zh': '相當於ㄨ加ㄧㄝ（iê的音），需快速連讀發音。',
   'en': 'It corresponds to u + iê (the "ye" sound above), pronounced quickly and continuously.',
   'ja': '「ウ」+「イエ」（iêの音）に相当し、素早く続けて発音します。',
   'de': 'Entspricht u plus dem Diphthong iê, zügig zusammenhängend gesprochen.',
   'fr': 'Correspond à ou + la diphtongue iê, prononcés de façon rapide et continue.'},
  'tuyết, chuyên'],
 ['uya',
  {'ko': "한글의 '우야'에 해당하는데 베트남어 가운데 이 모음이 보편적으로 사용되는 단어는 khuya뿐입니다.",
   'zh': '相當於注音符號的ㄨㄧㄚ，但在越南語中，普遍使用這一元音的單詞只有khuya。',
   'en': 'It corresponds to "uya" (oo-ee-ah), and in Vietnamese, khuya is the only word in which this vowel is '
         'commonly used.',
   'ja': '「ウイア」に相当しますが、ベトナム語の中でこの母音が一般的に使われる単語はkhuyaだけです。',
   'de': 'Entspricht „u-i-a“; das einzige gebräuchliche vietnamesische Wort mit diesem Laut ist „khuya“.',
   'fr': "Correspond à « ou-i-a » ; le seul mot vietnamien d'usage courant comportant cette voyelle est « khuya »."},
  'khuya']]
