# -*- coding: utf-8 -*-
TONES = [{'name': 'Thanh ngang',
  'kr': {'ko': '단평성',
         'zh': '橫聲',
         'en': 'level tone',
         'ja': '横声',
         'de': 'Ebener Ton',
         'fr': 'Ton égal',
         'pl': 'Ton równy'},
  'mark': 'a',
  'symbol': {'ko': '(부호 없음)',
             'zh': '（無符號）',
             'en': '(no mark)',
             'ja': '（記号なし）',
             'de': '(kein Zeichen)',
             'fr': '(aucun signe)',
             'pl': '(brak znaku)'},
  'desc': {'ko': '가장 높은 곳에서 시작하여 그대로 유지됩니다. 평탄하게, 살짝 높은 톤으로.',
           'zh': '從最高處開始並保持不變。平坦地，用稍高的音調。',
           'en': 'Starts at the highest point and stays there. Flat, at a slightly high tone.',
           'ja': '最も高いところから始まり、そのまま維持されます。平坦に、やや高いトーンで。',
           'de': 'Beginnt auf mittlerer bis höherer Tonlage und bleibt gleichmäßig eben.',
           'fr': 'Commence sur un registre moyen à aigu et reste plat et régulier.',
           'pl': 'Zaczyna się na średnio-wysokim poziomie i pozostaje równy.'}},
 {'name': 'Thanh sắc',
  'kr': {'ko': '상성',
         'zh': '銳聲',
         'en': 'rising tone',
         'ja': '鋭声',
         'de': 'Steigender Ton',
         'fr': 'Ton montant',
         'pl': 'Ton wznoszący'},
  'mark': 'á',
  'symbol': '◤ (dấu sắc)',
  'desc': {'ko': '약간 높은 곳에서 출발하여 가장 높은 곳까지 올라갑니다. 짧고 강하게 치켜올림.',
           'zh': '從稍高的位置開始，上升到最高點。短促而有力地上揚。',
           'en': 'It starts from a slightly high point and rises to the highest point. A short, strong rise.',
           'ja': 'やや高い位置から始まり、最も高い位置まで上がります。短く強く上げます。',
           'de': 'Beginnt etwas höher und steigt steil und kraftvoll nach oben an.',
           'fr': 'Commence un peu plus haut et monte de façon brève et vive.',
           'pl': 'Zaczyna się nieco wyżej i wznosi się stromo i mocno w górę.'}},
 {'name': 'Thanh huyền',
  'kr': {'ko': '장평성',
         'zh': '玄聲',
         'en': 'falling tone',
         'ja': '玄声',
         'de': 'Fallender Ton',
         'fr': 'Ton descendant',
         'pl': 'Ton opadający'},
  'mark': 'à',
  'symbol': '◣ (dấu huyền)',
  'desc': {'ko': '보통 높은 점에서 출발하여 차츰 내려가기 시작하여 약간 낮은 지점에서 끝납니다.',
           'zh': '通常從高點開始，逐漸下降，最後在稍低的位置結束。',
           'en': 'It usually starts at a high point, gradually descends, and ends at a slightly lower point.',
           'ja': '通常、高い位置から始まり、次第に下がっていき、やや低い位置で終わります。',
           'de': 'Beginnt sanft und fällt allmählich gleichmäßig tief ab.',
           'fr': 'Commence doucement et descend progressivement vers un registre grave.',
           'pl': 'Zaczyna się łagodnie i stopniowo opada nisko.'}},
 {'name': 'Thanh hỏi',
  'kr': {'ko': '회성',
         'zh': '問聲',
         'en': 'dipping tone',
         'ja': '問声',
         'de': 'Frageton (fallend-steigend)',
         'fr': 'Ton descendant-montant (interrogatif)',
         'pl': 'Ton pytający (opadająco-wznoszący)'},
  'mark': 'ả',
  'symbol': '◡ (dấu hỏi)',
  'desc': {'ko': '높은 점에서 출발한 뒤 약간 낮은 곳까지 내려갔다가 보통 높은 점까지 다시 올라갑니다.',
           'zh': '從高點出發後，先下降到稍低的地方，然後再次上升到普通的高點。',
           'en': 'It starts from a high point, descends to a slightly lower place, and then usually rises again to a '
                 'high point.',
           'ja': '高い点から始まった後、やや低いところまで下がってから、通常は高い点まで再び上がります。',
           'de': 'Fällt zunächst nach unten ab und steigt dann fragend wieder an.',
           'fr': "Descend d'abord légèrement puis remonte comme pour poser une question.",
           'pl': 'Najpierw opada lekko w dół, a następnie unosi się pytająco w górę.'}},
 {'name': 'Thanh ngã',
  'kr': {'ko': '거성',
         'zh': '跌聲',
         'en': 'creaky-rising tone',
         'ja': '跌声',
         'de': 'Unterbrochen steigender Ton',
         'fr': 'Ton montant avec coup de glotte',
         'pl': 'Ton wznoszący z zwarciem krtaniowym'},
  'mark': 'ã',
  'symbol': '~ (dấu ngã)',
  'desc': {'ko': '높은 점에서 출발하고 갑자기 약간 낮은 점을 통해 가장 높은 곳까지 올라간 후에 끝납니다.',
           'zh': '從高點出發，突然經過稍低的點後上升到最高處，然後結束。',
           'en': 'It starts from a high point, suddenly passes through a slightly lower point, rises to the highest '
                 'point, and then ends.',
           'ja': '高い点から始まり、突然やや低い点を通ってから最も高いところまで上がって終わります。',
           'de': 'Beginnt hoch, wird durch einen Kehlkopfverschluss kurz unterbrochen und steigt dann steil an.',
           'fr': 'Commence haut, subit une brève interruption glottale, puis monte nettement.',
           'pl': 'Zaczyna się wysoko, zostaje na chwilę przerwany przez zwarcie krtaniowe, po czym gwałtownie '
                 'rośnie.'}},
 {'name': 'Thanh nặng',
  'kr': {'ko': '하성',
         'zh': '重聲',
         'en': 'heavy tone',
         'ja': '重声',
         'de': 'Schwerer fallender Ton',
         'fr': 'Ton lourd (descendant bref)',
         'pl': 'Ton ciężki (krótki opadający)'},
  'mark': 'ạ',
  'symbol': '● (dấu nặng)',
  'desc': {'ko': '보통 높은 곳에서 출발하여 가장 낮은 지점까지 내려가 짧고 무겁게 끝납니다.',
           'zh': '通常從高處出發，下降到最低點，短促而沉重地結束。',
           'en': 'It usually starts from a high place, descends to the lowest point, and ends short and heavy.',
           'ja': '通常高いところから始まり、最も低い地点まで下がって、短く重く終わります。',
           'de': 'Fällt sofort steil nach unten ab und bricht kurz und schwer ab.',
           'fr': "Descend très rapidement vers le registre le plus grave et s'interrompt de façon brève et lourde.",
           'pl': 'Gwałtownie opada do najniższego rejestru i urywa się krótko i ciężko.'}}]

ALPHABET = [['a', '[a]'],
 ['ă', '[á]'],
 ['â', '[ớ]'],
 ['b', '[bê]'],
 ['c', '[xê]'],
 ['d', '[dê]'],
 ['đ', '[đê]'],
 ['e', '[e]'],
 ['ê', '[ê]'],
 ['g', '[gờ]'],
 ['h', '[hát]'],
 ['i', '[i ngắn]'],
 ['k', '[ca]'],
 ['l', '[e-lờ]'],
 ['m', '[e-mờ]'],
 ['n', '[e-nờ]'],
 ['o', '[o]'],
 ['ô', '[ô]'],
 ['ơ', '[ơ]'],
 ['p', '[pê]'],
 ['q', '[cu]'],
 ['r', '[e-rờ]'],
 ['s', '[ét-sì]'],
 ['t', '[tê]'],
 ['u', '[u]'],
 ['ư', '[ư]'],
 ['v', '[vê]'],
 ['x', '[ích-xì]'],
 ['y', '[y dài]']]

ALPHABET_NOTE = {'ko': '베트남어 문자는 기본 29개 알파벳입니다. 영어의 f, j, w, z는 없고, ă, â, đ, ê, ô, ơ, ư가 추가로 있습니다.',
 'zh': '越南語文字基本上有29個字母。沒有英語中的f、j、w、z，但另外有ă、â、đ、ê、ô、ơ、ư。',
 'en': "The Vietnamese alphabet has 29 basic letters. It doesn't have the English f, j, w, z, but it has ă, â, đ, ê, "
       'ô, ơ, ư in addition.',
 'ja': 'ベトナム語の文字は基本29個のアルファベットです。英語のf、j、w、zはなく、ă、â、đ、ê、ô、ơ、ưが追加であります。',
 'de': 'Das vietnamesische Alphabet umfasst 29 Grundbuchstaben. Die Buchstaben f, j, w und z gibt es nicht, dafür aber '
       'zusätzlich ă, â, đ, ê, ô, ơ und ư.',
 'fr': "L'alphabet vietnamien comprend 29 lettres de base. Il ne possède pas les lettres f, j, w et z de l'alphabet "
       'latin standard, mais comprend en plus ă, â, đ, ê, ô, ơ et ư.',
 'pl': 'Alfabet wietnamski składa się z 29 liter podstawowych. Nie zawiera liter f, j, w, z, ale posiada dodatkowo '
       'litery ă, â, đ, ê, ô, ơ, ư.'}

CONSONANTS_SIMPLE = [['b',
  {'ko': "한글의 'ㅂ'처럼 발음하지만 양 입술을 뗄 때 좀 더 세게 발음합니다.",
   'zh': '沒有完全對應的注音符號，發音類似英語的b音，但雙唇分開時發音更用力一些。',
   'en': "It's pronounced like the English b, but the lips separate more forcefully.",
   'ja': '日本語のバ行の子音のように発音しますが、両唇を離すときにもう少し強く発音します。',
   'de': 'Wird wie ein deutsches b ausgesprochen, jedoch lösen sich die Lippen etwas kräftiger (implosiv).',
   'fr': 'Se prononce comme le b français, mais les lèvres se détachent plus vigoureusement (implosive).',
   'pl': 'Wymawia się jak polskie „b”, ale wargi rozwierają się nieco energiczniej (spółgłoska implozywna).'},
  'ba, bơ'],
 ['c, k, q',
  {'ko': "한글의 'ㄲ'처럼 발음합니다. q는 u로 시작하는 음 앞에만 옵니다.",
   'zh': '發音像注音符號的ㄍ（不送氣的k音）。q只出現在以u開頭的音之前。',
   'en': 'It\'s pronounced like the k in "skate" (unaspirated, without a puff of air), not like the k in "kite". q '
         'appears only before a sound beginning with u.',
   'ja': '日本語のカ行の子音のように発音します。qはuで始まる音の前にのみ来ます。',
   'de': 'Wird wie ein deutsches k ohne Aspiration (ohne Hauch) ausgesprochen. q steht nur vor Lauten, die mit u '
         'beginnen.',
   'fr': "Se prononce comme un k sans souffle (non aspiré). q n'apparaît que devant un son commençant par u.",
   'pl': 'Wymawia się jak polskie „k” bez przydechu. Litera „q” występuje wyłącznie przed dźwiękami zaczynającymi się '
         'od „u”.'},
  'cô, kéo, qua'],
 ['d',
  {'ko': "한글의 'ㅈ'처럼 발음합니다.",
   'zh': '沒有完全對應的注音符號，發音類似英語的z音。',
   'en': "It's pronounced like the English z.",
   'ja': '日本語のザ行の子音のように発音します。',
   'de': 'Wird im Norden wie ein weiches, stimmhaftes deutsches s (wie in „Sonne“) ausgesprochen.',
   'fr': 'Dans le Nord, se prononce comme un z sonore (comme le s dans « rose »).',
   'pl': 'Na północy wymawia się jak polskie dźwięczne „z”, na południu jak „j”.'},
  'da, dơ'],
 ['đ',
  {'ko': "한글의 'ㄷ'처럼 발음합니다.",
   'zh': '沒有完全對應的注音符號，發音類似英語的d音。',
   'en': "It's pronounced like the English d.",
   'ja': '日本語のダ行の子音のように発音します。',
   'de': 'Wird wie ein deutsches d ausgesprochen, mit leichtem Kehlkopfverschluss (implosiv).',
   'fr': 'Se prononce comme un d français, avec une légère fermeture glottale (implosive).',
   'pl': 'Wymawia się jak polskie „d”, z lekkim zwarciem krtaniowym (implozywne).'},
  'đi, đê'],
 ['g',
  {'ko': "한글의 'ㄱ'처럼 발음합니다.",
   'zh': '沒有完全對應的注音符號，發音類似英語的g音（濁音）。',
   'en': 'It\'s pronounced like the English g (as in "go").',
   'ja': '日本語のガ行の子音のように発音します。',
   'de': 'Wird wie ein deutsches g (wie in „gut“) oder leicht reibend ausgesprochen.',
   'fr': 'Se prononce comme le g dur français (comme dans « gare ») ou légèrement frotté.',
   'pl': 'Wymawia się jak polskie twarde „g” (jak w „góra”) lub lekko szczelinowo.'},
  'gà, gai'],
 ['h',
  {'ko': "한글의 'ㅎ'처럼 발음합니다.",
   'zh': '發音像注音符號的ㄏ。',
   'en': "It's pronounced like the English h.",
   'ja': '日本語のハ行の子音のように発音します。',
   'de': 'Wird wie das deutsche h (wie in „Haus“) ausgesprochen.',
   'fr': 'Se prononce comme un h expiré (comme en anglais ou en allemand).',
   'pl': 'Wymawia się jak polskie „h” (przydechowe).'},
  'ho, hô'],
 ['l',
  {'ko': "한글의 'ㄹ'처럼 발음합니다.",
   'zh': '發音像注音符號的ㄌ。',
   'en': "It's pronounced like the English l.",
   'ja': '日本語のラ行の子音のように発音します。',
   'de': 'Wird wie das deutsche l (wie in „Lampe“) ausgesprochen.',
   'fr': 'Se prononce comme le l français.',
   'pl': 'Wymawia się jak polskie „l”.'},
  'la, lê'],
 ['m',
  {'ko': "한글의 'ㅁ'처럼 발음합니다.",
   'zh': '發音像注音符號的ㄇ。',
   'en': "It's pronounced like the English m.",
   'ja': '日本語のマ行の子音のように発音します。',
   'de': 'Wird wie das deutsche m (wie in „Mutter“) ausgesprochen.',
   'fr': 'Se prononce comme le m français.',
   'pl': 'Wymawia się jak polskie „m”.'},
  'ma, mơ'],
 ['n',
  {'ko': "한글의 'ㄴ'처럼 발음합니다.",
   'zh': '發音像注音符號的ㄋ。',
   'en': "It's pronounced like the English n.",
   'ja': '日本語のナ行の子音のように発音します。',
   'de': 'Wird wie das deutsche n (wie in „Name“) ausgesprochen.',
   'fr': 'Se prononce comme le n français.',
   'pl': 'Wymawia się jak polskie „n”.'},
  'no, na'],
 ['p',
  {'ko': "한글의 'ㅃ'처럼 발음합니다.",
   'zh': '發音像注音符號的ㄅ。',
   'en': 'It\'s pronounced like the p in "spin" (unaspirated, without a puff of air), not like the p in "pin".',
   'ja': '日本語のパ行の子音のように発音します。',
   'de': 'Wird wie ein stimmloses p ohne Hauch (unaspiriert) ausgesprochen.',
   'fr': 'Se prononce comme un p sourd sans souffle (non aspiré).',
   'pl': 'Wymawia się jak polskie bezdźwięczne „p” bez przydechu.'},
  'pin, sa pa'],
 ['r',
  {'ko': "한글의 'ㅈ'처럼 발음합니다.",
   'zh': '沒有完全對應的注音符號，發音類似英語的z音。',
   'en': "It's pronounced like the English z.",
   'ja': '日本語のザ行の子音のように発音します。',
   'de': 'Wird im Norden wie ein weiches stimmhaftes s [z] gesprochen, im Süden als gerolltes Zungen-r.',
   'fr': 'Dans le Nord, se prononce comme un z sonore [z] ; dans le Sud, comme un r roulé.',
   'pl': 'Na północy wymawia się jak dźwięczne „z” [z], na południu jako drżące „r”.'},
  'ra, ru'],
 ['s',
  {'ko': "한글의 'ㅅ(ㅆ)'처럼 발음합니다.",
   'zh': '發音像注音符號的ㄙ。',
   'en': "It's pronounced like the English s.",
   'ja': '日本語のサ行の子音のように発音します。',
   'de': 'Wird im Norden wie ein scharfes s (wie in „Wasser“) ausgesprochen, im Süden eher wie sch [ʂ].',
   'fr': 'Dans le Nord, se prononce comme un s sourd (comme dans « sel ») ; dans le Sud, plutôt rétroflexe comme [ʂ].',
   'pl': 'Na północy wymawia się jak polskie „s”, na południu jako szumiące „sz” [ʂ].'},
  'so, sai'],
 ['t',
  {'ko': "한글의 'ㄸ'처럼 발음합니다.",
   'zh': '發音像注音符號的ㄉ。',
   'en': 'It\'s pronounced like the t in "stop" (unaspirated, without a puff of air), not like the t in "top".',
   'ja': '日本語のタ行の子音のように発音します。',
   'de': 'Wird wie ein t ohne Aspiration (ohne Hauch) ausgesprochen.',
   'fr': 'Se prononce comme un t sans souffle (non aspiré).',
   'pl': 'Wymawia się jak polskie „t” bez przydechu.'},
  'ta, to'],
 ['x',
  {'ko': "한글의 'ㅆ'처럼 발음합니다.",
   'zh': '發音像注音符號的ㄙ。',
   'en': "It's pronounced like the English s.",
   'ja': '日本語のサ行の子音のように発音します。',
   'de': 'Wird wie ein scharfes s (wie in „Wasser“) ausgesprochen.',
   'fr': 'Se prononce comme un s sourd (comme dans « sel »).',
   'pl': 'Wymawia się jak polskie bezdźwięczne „s”.'},
  'xa, xe'],
 ['v',
  {'ko': "한글에는 'v'에 해당하는 음이 없습니다. 윗입술을 앞으로 내밀어 이로 아래 입술을 약간 물어서 발음합니다.",
   'zh': "華語（國語）沒有與'v'對應的音。將上唇向前突出，用牙齒輕咬下唇發音。",
   'en': 'This is the same as the English v.',
   'ja': "日本語には'v'に相当する音がありません。上唇を前に突き出し、歯で下唇を軽く噛んで発音します。",
   'de': 'Wird wie das deutsche w ausgesprochen (die oberen Zähne berühren leicht die Unterlippe).',
   'fr': 'Se prononce comme le v français (les dents supérieures effleurent la lèvre inférieure).',
   'pl': 'Wymawia się jak polskie „w” (górne zęby lekko dotykają dolnej wargi).'},
  'và, với']]

CONSONANTS_COMPLEX = [['ch, tr',
  {'ko': "한글의 'ㅉ'처럼 발음합니다. 현대 베트남어에서 ch와 tr의 음은 거의 같게 발음되지만, 일부 지방에서 ch음은 조금 더 가볍게 발음됩니다.",
   'zh': '發音像注音符號的ㄐ（不送氣）。在現代越南語中，ch和tr的發音幾乎相同，但在一些地區，ch音會發得稍微輕一些。',
   'en': 'It\'s pronounced like the ch in "chip", but without a puff of air (unaspirated). In modern Vietnamese, ch '
         'and tr are pronounced almost the same, but in some regions the ch sound is pronounced a bit more lightly.',
   'ja': '日本語のチャ行の子音のように発音します。現代ベトナム語ではchとtrの音はほぼ同じように発音されますが、一部の地方ではch音がやや軽く発音されます。',
   'de': 'Wird wie ein tsch ohne Hauch ausgesprochen. Im modernen Vietnamesisch klingen ch und tr fast gleich, in '
         'einigen Regionen wird ch jedoch etwas leichter gesprochen.',
   'fr': 'Se prononce comme « tch » sans souffle (non aspiré). En vietnamien moderne, ch et tr se prononcent presque '
         'de la même façon, bien que ch soit parfois plus léger dans certaines régions.',
   'pl': 'Wymawia się jak miękkie „ć / cz” bez przydechu. We współczesnym wietnamskim „ch” i „tr” brzmią niemal '
         'identycznie, choć w niektórych regionach „ch” wymawia się nieco lżej.'},
  'cho, tro'],
 ['kh',
  {'ko': "한글의 'ㅋ'처럼 발음합니다.",
   'zh': '發音像注音符號的ㄎ。',
   'en': 'It\'s pronounced like the k in "kite" (aspirated, with a puff of air).',
   'ja': '日本語のカ行の子音のように発音しますが、息を強く出して発音します。',
   'de': 'Wird wie das deutsche ch in „Bach“ ([x]) oder als behauchtes k ausgesprochen.',
   'fr': 'Se prononce comme la jota espagnole ou le ch allemand de « Bach » ([x]).',
   'pl': 'Wymawia się jak polskie „ch” (jak w „chleb”) [x] lub mocno przydechowe „k”.'},
  'khô, khi'],
 ['nh',
  {'ko': "한글의 '니'처럼 발음합니다.",
   'zh': '發音像注音符號的ㄋㄧ（舌面鼻音）。',
   'en': 'It\'s pronounced like the "ny" in "canyon" (a palatal nasal sound).',
   'ja': '日本語の「に」に近い音です。',
   'de': 'Wird wie das spanische ñ oder wie gn in „Cognac“ als Gaumen-Nasallaut [ɲ] ausgesprochen.',
   'fr': 'Se prononce comme le « gn » français dans « montagne » ou le ñ espagnol (nasale palatale [ɲ]).',
   'pl': 'Wymawia się jak polskie miękkie „ń / ni” (spółgłoska nosowa podniebienna [ɲ]).'},
  'nho, nhi'],
 ['th',
  {'ko': "한글의 'ㅌ'처럼 발음합니다.",
   'zh': '發音像注音符號的ㄊ。',
   'en': 'It\'s pronounced like the t in "top" (aspirated, with a puff of air).',
   'ja': '日本語のタ行の子音のように発音しますが、息を強く出して発音します。',
   'de': 'Wird wie ein stark behauchtes deutsches t (wie in „Tee“) ausgesprochen.',
   'fr': 'Se prononce comme un t fortement aspiré (avec un souffle net).',
   'pl': 'Wymawia się jak „t” z silnym przydechem (jak w angielskim „tea”).'},
  'tha, thu'],
 ['ph',
  {'ko': "한글의 'ㅍ'에 해당하나 정확한 음은 없는 대신 영어의 f음처럼 발음합니다.",
   'zh': '沒有完全對應的注音符號，發音像英語的f音。',
   'en': "It's pronounced like the English f.",
   'ja': '日本語には正確に一致する音がなく、英語のf音のように発音します。',
   'de': 'Wird wie das deutsche f (wie in „Foto“) ausgesprochen.',
   'fr': 'Se prononce comme le f français.',
   'pl': 'Wymawia się jak polskie „f”.'},
  'phê, pho'],
 ['gh',
  {'ko': "한글의 'ㄱ'처럼 발음하나 e, ê, i 등의 모음 앞에 위치합니다.",
   'zh': '沒有完全對應的注音符號，發音類似英語的g音（濁音），但位於e, ê, i等元音之前。',
   'en': 'It\'s pronounced like the English g (as in "go"), but is placed before vowels such as e, ê, i.',
   'ja': '日本語のガ行の子音のように発音しますが、e, ê, iなどの母音の前に位置します。',
   'de': 'Wird wie das einfache g ausgesprochen, steht jedoch vor den Vokalen e, ê und i.',
   'fr': "Se prononce comme le g dur, mais s'écrit gh devant les voyelles e, ê et i.",
   'pl': 'Wymawia się jak zwykłe „g”, ale zapisuje się jako „gh” przed samogłoskami e, ê, i.'},
  'ghi, ghe'],
 ['ng, ngh',
  {'ko': "한글의 '응으'에 해당하나 한국 사람이 발음하기 어려운 비음입니다. e, ê, i 등의 모음 앞에서는 ngh로 씁니다.",
   'zh': '華語（國語）沒有這個音（華語的ng只出現在音節結尾），但閩南語（台語）中有以ng開頭的字，例如「硬」(ngē)，可以參考閩南語的發音方式。e, ê, i等元音前寫作ngh。',
   'en': 'English doesn\'t have this sound at the beginning of a word, only at the end (as in "sing"). Try saying '
         '"sing" and then just the "-ng" part, then move that sound to the front of a word. Before vowels such as e, '
         'ê, i, it is written as ngh.',
   'ja': '日本語にはこの音が語頭に来ることはありません（「ん」に近い鼻音です）。日本語話者にとっても発音が難しい音です。e, ê, iなどの母音の前ではnghと表記します。',
   'de': 'Entspricht dem deutschen ng-Laut (wie in „singen“), steht im Vietnamesischen jedoch auch am Wortanfang. Vor '
         'den Vokalen e, ê und i wird es als ngh geschrieben.',
   'fr': 'Correspond au son « ng » de « parking », mais peut se trouver en début de mot en vietnamien. Devant e, ê et '
         "i, il s'écrit ngh.",
   'pl': 'Odpowiada dźwiękowi [ŋ] (jak „ng” w angielskim „sing” lub przed k/g w polskim „bank”), ale w wietnamskim '
         'występuje też na początku słowa. Przed e, ê, i zapisuje się jako „ngh”.'},
  'nga, nghe'],
 ['gi',
  {'ko': "'d'음과 같게 발음하고 전통적인 철자법에서 쓰입니다.",
   'zh': "發音與'd'相同，用於傳統拼寫法中。",
   'en': "It's pronounced the same as 'd', and is used in traditional spelling.",
   'ja': "'d'と同じように発音し、伝統的な綴り方で使われます。",
   'de': 'Wird im Norden wie d (stimmhaftes s [z]) ausgesprochen und in der traditionellen Rechtschreibung verwendet.',
   'fr': "Dans le Nord, se prononce comme d (un z sonore [z]) ; c'est une graphie traditionnelle.",
   'pl': 'Na północy wymawia się identycznie jak „d” (dźwięczne „z” [z]); jest to tradycyjna pisownia.'},
  'gì, gia']]

VOWELS_SIMPLE = [['a',
  {'ko': "한글의 '아'에 해당합니다.",
   'zh': '相當於注音符號的ㄚ。',
   'en': 'It corresponds to the a in "father".',
   'ja': '日本語の「ア」に相当します。',
   'de': 'Entspricht dem offenen deutschen a (wie in „Vater“).',
   'fr': 'Correspond au son « a » ouvert du français (comme dans « papa »).',
   'pl': 'Odpowiada otwartemu polskiemu „a” (jak w „tata”).'},
  'anh, cha'],
 ['ă',
  {'ko': "한글의 '아'에 해당하지만 위의 a와 비교할 때 입을 더 크게 벌리고 더 짧게 발음합니다.",
   'zh': '相當於注音符號的ㄚ，但與上面的a相比，嘴張得更大，發音更短。',
   'en': 'It corresponds to the a in "father", but compared to the a above, the mouth opens wider and it\'s pronounced '
         'shorter.',
   'ja': '日本語の「ア」に相当しますが、上のaと比べて口をより大きく開け、より短く発音します。',
   'de': 'Entspricht dem deutschen a, wird jedoch mit weiter geöffnetem Mund und deutlich kürzer ausgesprochen.',
   'fr': 'Correspond au son « a », mais prononcé plus brièvement et avec la bouche plus ouverte.',
   'pl': 'Odpowiada polskiemu „a”, ale wymawia się z szerzej otwartymi ustami i znacznie krócej.'},
  'đắt, sắt'],
 ['â',
  {'ko': "한글의 '어'에 해당하지만 아래의 ơ와 비교할 때 입의 더 안쪽에서 더 짧게 발음합니다.",
   'zh': '相當於注音符號的ㄜ，但與下面的ơ相比，發音位置更靠口腔內側，且更短。',
   'en': 'It corresponds to the u in "cup" (a short, central vowel), but compared to the ơ below, it\'s pronounced '
         'further back in the mouth and shorter.',
   'ja': '日本語には正確に一致する音がありませんが、「ア」を口の奥のほうで短く発音したような音です。下のơと比べて、より奥でより短く発音します。',
   'de': 'Ein kurzer, zentraler Vokal, der im Vergleich zu ơ weiter hinten im Mundraum und kürzer gesprochen wird.',
   'fr': 'Voyelle centrale brève, prononcée plus en arrière dans la bouche et plus court que ơ.',
   'pl': 'Krótka samogłoska centralna (szwa), wymawiana głębiej w gardle i krócej niż ơ.'},
  'mất, mật'],
 ['e',
  {'ko': "한글의 '애'에 해당하지만 입을 옆으로 넓게 벌리고 짧게 발음합니다.",
   'zh': '相當於注音符號的ㄝ，但嘴向兩側張得更寬，發音更短。',
   'en': 'It corresponds to the e in "bed", but the mouth is opened wide sideways and it\'s pronounced shorter.',
   'ja': '日本語の「エ」に相当しますが、口を横に大きく広げて短く発音します。',
   'de': 'Entspricht einem offenen kurzen e (wie in „Bett“), die Mundwinkel sind breit gezogen.',
   'fr': 'Correspond au son « è » ouvert (comme dans « fête »), les lèvres étirées vers les côtés.',
   'pl': 'Odpowiada otwartemu krótkiemu „e” (jak w „echo”), z szeroko rozciągniętymi kącikami ust.'},
  'nghe, khe'],
 ['ê',
  {'ko': "한글의 '에'에 해당하지만 e에 비해 약간 길게 발음합니다.",
   'zh': '相當於注音符號的ㄝ，但比e發音稍長一些。',
   'en': 'It corresponds to the e in "bed", but is pronounced slightly longer than e.',
   'ja': '日本語の「エ」に相当しますが、eに比べてやや長く発音します。',
   'de': 'Entspricht einem geschlosseneren deutschen e (wie in „See“), etwas länger als das offene e.',
   'fr': 'Correspond au son « é » fermé (comme dans « été »).',
   'pl': 'Odpowiada przymkniętemu „e” (jak we francuskim „été” lub niemieckim „See”), nieco dłuższemu niż e.'},
  'đê, dê'],
 ['i',
  {'ko': "한글의 '이'에 해당하는 음으로 짧게 발음합니다.",
   'zh': '是相當於注音符號ㄧ的音，發音較短。',
   'en': 'It is a sound corresponding to the ee in "see", pronounced short.',
   'ja': '日本語の「イ」に相当する音で、短く発音します。',
   'de': 'Entspricht einem kurzen deutschen i.',
   'fr': 'Correspond au son « i » bref du français.',
   'pl': 'Odpowiada krótkiemu polskiemu „i”.'},
  'đi, thi'],
 ['y',
  {'ko': "한글의 '이'에 해당하는 음으로 길게 발음합니다.",
   'zh': '是相當於注音符號ㄧ的音，發音較長。',
   'en': 'It is a sound corresponding to the ee in "see", pronounced long.',
   'ja': '日本語の「イ」に相当する音で、長く発音します。',
   'de': 'Entspricht dem deutschen i, wird jedoch in der Regel etwas länger gehalten.',
   'fr': 'Correspond au son « i », mais généralement prononcé plus longuement.',
   'pl': 'Odpowiada polskiemu „i”, zazwyczaj wymawianemu nieco dłużej.'},
  'yêu, yên'],
 ['o',
  {'ko': "한글의 '오'에 해당하지만 입모양은 '어'발음처럼 입을 크게 벌리고 발음합니다.",
   'zh': '相當於注音符號的ㄛ，但發音時嘴巴張得更大，接近ㄜ的口型。',
   'en': 'It\'s similar to the o in "saw", pronounced with the mouth opened wide, similar to the mouth shape for the u '
         'in "cup".',
   'ja': '日本語の「オ」に近い音ですが、「ア」に近い口の開け方でより大きく口を開けて発音します。',
   'de': 'Entspricht einem offenen o (wie in „offen“), mit weiter geöffnetem Mund.',
   'fr': 'Correspond au son « o » ouvert (comme dans « pomme »), la bouche bien ouverte.',
   'pl': 'Odpowiada otwartemu „o” (jak w „kot”), z szeroko otwartymi ustami.'},
  'no, ho'],
 ['ô',
  {'ko': "한글의 '오'에 해당합니다.",
   'zh': '相當於注音符號的ㄛ。',
   'en': 'It corresponds to the o in "boat" (without the "w" glide at the end).',
   'ja': '日本語の「オ」に相当します。',
   'de': 'Entspricht dem geschlossenen deutschen o (wie in „Boot“).',
   'fr': 'Correspond au son « o » fermé (comme dans « beau » ou « tôt »).',
   'pl': 'Odpowiada przymkniętemu „o” (jak w niemieckim „Boot”).'},
  'khô, cô'],
 ['ơ',
  {'ko': "한글의 '어'에 해당합니다.",
   'zh': '相當於注音符號的ㄜ。',
   'en': 'It corresponds to the u in "cup".',
   'ja': '日本語には正確に一致する音がありませんが、「ア」と「オ」の中間のような音です。',
   'de': 'Ein ungerundeter Vokal zwischen a und o, ähnlich dem Laut in „cup“.',
   'fr': 'Voyelle intermédiaire non arrondie entre a et o, proche du « e » caduc mais plus ouverte.',
   'pl': 'Niezaokrąglona samogłoska pośrednia między a oraz o [ɤ], wymawiana z płaskimi wargami.'},
  'mơ, tơ'],
 ['u',
  {'ko': "한글의 '우'에 해당합니다.",
   'zh': '相當於注音符號的ㄨ。',
   'en': 'It corresponds to the oo in "food".',
   'ja': '日本語の「ウ」よりも唇を丸めて発音します。',
   'de': 'Entspricht dem geschlossenen deutschen u (wie in „Mut“).',
   'fr': 'Correspond au son « ou » français (comme dans « loup »).',
   'pl': 'Odpowiada przymkniętemu polskiemu „u”.'},
  'ru, thu'],
 ['ư',
  {'ko': "한글의 '으'에 해당합니다.",
   'zh': '相當於注音符號的ㄨ，但嘴唇不要圓起來，保持扁平發音。',
   'en': 'It\'s like the oo in "food", but without rounding the lips — keep the lips relaxed and flat.',
   'ja': '日本語の「ウ」に相当します。',
   'de': 'Wird wie ein u gesprochen, jedoch ohne die Lippen zu runden – die Lippen bleiben flach entspannt.',
   'fr': 'Se prononce comme « ou », mais sans arrondir les lèvres — les lèvres restent détendues et plates.',
   'pl': 'Wymawia się jak „u”, ale bez zaokrąglania warg – wargi pozostają całkowicie płaskie i rozluźnione [ɯ] '
         '(zbliżone do polskiego „y”, lecz wymawiane głębiej).'},
  'sư, hư']]

VOWELS_COMPLEX = [['iê, yê',
  {'ko': "한글의 '이에'에 해당하지만 단어를 만들 때는 뒤에 자음을 반드시 동반해야 합니다.",
   'zh': '相當於注音符號的ㄧㄝ，但構成單詞時後面必須伴隨輔音。',
   'en': 'It corresponds to the "ye" sound (as in "yes"), but when forming a word, it must be followed by a consonant.',
   'ja': '日本語の「イエ」に相当しますが、単語を作るときは後ろに子音を必ず伴わなければなりません。',
   'de': 'Entspricht einem „ie-e“-Diphthong; im Wort muss immer ein Endkonsonant folgen.',
   'fr': "Correspond à la diphtongue « i-é » ; dans un mot, elle doit obligatoirement être suivie d'une consonne.",
   'pl': 'Odpowiada dyftongowi „i-e”; w wyrazie zawsze musi po nim następować spółgłoska końcowa.'},
  'biết, yên'],
 ['ia',
  {'ko': "한글의 '이아'에 해당하지만, ia는 '이어'로 발음합니다.",
   'zh': '相當於注音符號的ㄧㄚ，但ia發音為ㄧ加上ㄜ（類似iê）。',
   'en': 'It corresponds to "ia" (ee-ah), but ia is pronounced as "i" plus the u in "cup" (similar to iê).',
   'ja': '「イア」に相当しますが、iaは「イ」の後にア-オの中間の音（iêと同様）を続けて発音します。',
   'de': 'Entspricht i plus einem zentralen Vokal (ähnlich wie iê, steht am Wortende ohne Endkonsonant).',
   'fr': "Correspond à « i » suivi d'une voyelle centrale (similaire à iê, mais sans consonne finale).",
   'pl': 'Odpowiada połączeniu „i” oraz samogłoski centralnej (podobne do iê, występuje na końcu wyrazu bez '
         'spółgłoski).'},
  'kia'],
 ['oa, ua',
  {'ko': "한글의 '오아, 우아'에 해당합니다.",
   'zh': '相當於注音符號的ㄛㄚ、ㄨㄚ。',
   'en': 'It corresponds to "oa" (as in "oh-ah") and "ua" (as in "oo-ah").',
   'ja': '日本語の「オア」「ウア」に相当します。',
   'de': 'Entspricht „o-a“ bzw. „u-a“ als gleitender Doppellaut.',
   'fr': 'Correspond aux sons glissés « ou-a ».',
   'pl': 'Odpowiada ślizgowym dwudźwiękom „o-a” lub „u-a”.'},
  'khoa, qua'],
 ['ưa, ươ',
  {'ko': "한글의 '으아, 으어'에 해당합니다. 현대 베트남어에서 ưa는 '으어'로 발음합니다.",
   'zh': '相當於ư（不圓唇的ㄨ）加ㄚ、ư加ㄜ。在現代越南語中，ưa發音為ươ。',
   'en': 'It corresponds to ư + a and ư + ơ (see ư and ơ above). In modern Vietnamese, ưa is pronounced as ươ.',
   'ja': 'ư（唇を丸めない「ウ」）+ア、ư+ơ（ア-オの中間の音）に相当します。現代ベトナム語ではưaはươと発音します。',
   'de': 'Kombination aus ư und a bzw. ơ. Im modernen Vietnamesisch wird ưa praktisch wie ươ gesprochen.',
   'fr': 'Combinaison de ư et a ou ơ. En vietnamien moderne, ưa se prononce pratiquement comme ươ.',
   'pl': 'Połączenie ư oraz a lub ơ. We współczesnym wietnamskim ưa wymawia się praktycznie jak ươ.'},
  'mưa, mười'],
 ['oă, uă',
  {'ko': "한글의 '오아, 우아'에 해당합니다.",
   'zh': '相當於注音符號的ㄛㄚ、ㄨㄚ。',
   'en': 'It corresponds to "oa" (as in "oh-ah") and "ua" (as in "oo-ah").',
   'ja': '日本語の「オア」「ウア」に相当します。',
   'de': 'Entspricht gleitenden Lauten o/u plus kurzem ă.',
   'fr': "Correspond aux sons glissés o/ou suivis d'un ă bref.",
   'pl': 'Odpowiada dźwiękom ślizgowym o/u, po których następuje krótkie ă.'},
  'xoăn, quăn'],
 ['uơ, uâ',
  {'ko': "한글의 '우어'에 해당하며 â는 ơ보다 짧게 발음합니다.",
   'zh': '相當於ㄨ加ㄜ，â的發音比ơ更短。',
   'en': 'It corresponds to u + ơ (the u in "cup"), and â is pronounced shorter than ơ.',
   'ja': '「ウ」+ơ（ア-オの中間の音）に相当し、âはơより短く発音します。',
   'de': 'Entspricht u plus ơ, wobei â kürzer als ơ ausgesprochen wird.',
   'fr': 'Correspond à ou + ơ, â étant prononcé plus brièvement que ơ.',
   'pl': 'Odpowiada połączeniu u + ơ, przy czym â wymawia się krócej niż ơ.'},
  'quơ, quân'],
 ['ue, oe',
  {'ko': "한글의 '우애, 오애'에 해당합니다.",
   'zh': '相當於注音符號的ㄨㄝ、ㄛㄝ。',
   'en': 'It corresponds to "ue" (oo-eh) and "oe" (oh-eh).',
   'ja': '「ウエ」「オエ」に相当します。',
   'de': 'Entspricht „u-e“ bzw. „o-e“.',
   'fr': 'Correspond à « ou-è ».',
   'pl': 'Odpowiada połączeniom „u-e” lub „o-e”.'},
  'que, xoe'],
 ['uê',
  {'ko': "한글의 '우에'에 해당하지만 입술을 더 작게 오므려 발음합니다.",
   'zh': '相當於ㄨㄝ（ê音較長），但發音時嘴唇撮得更小。',
   'en': 'It corresponds to u + ê, but is pronounced with the lips pursed more tightly.',
   'ja': '「ウエ」に相当しますが、唇をより小さくすぼめて発音します。',
   'de': 'Entspricht u plus ê, wobei die Lippen enger gespitzt werden.',
   'fr': 'Correspond à ou + ê, les lèvres étant plus serrées.',
   'pl': 'Odpowiada połączeniu u + ê, przy czym wargi są mocniej ściągnięte.'},
  'quê, khuê'],
 ['uy',
  {'ko': "한글의 '우이'에 해당합니다.",
   'zh': '相當於注音符號的ㄨㄧ。',
   'en': 'It corresponds to "uy" (oo-ee).',
   'ja': '「ウイ」に相当します。',
   'de': 'Entspricht einem gleitenden „u-i“ ([wi]).',
   'fr': 'Correspond au son glissé « ou-i » ([wi]).',
   'pl': 'Odpowiada połączeniu u + i ([wi]).'},
  'tuy, huy'],
 ['uyê',
  {'ko': "한글의 '우예'를 빠르게 연속하여 발음합니다.",
   'zh': '相當於ㄨ加ㄧㄝ（iê的音），需快速連讀發音。',
   'en': 'It corresponds to u + iê (the "ye" sound above), pronounced quickly and continuously.',
   'ja': '「ウ」+「イエ」（iêの音）に相当し、素早く続けて発音します。',
   'de': 'Entspricht u plus dem Diphthong iê, zügig zusammenhängend gesprochen.',
   'fr': 'Correspond à ou + la diphtongue iê, prononcés de façon rapide et continue.',
   'pl': 'Odpowiada u plus dwudźwiękowi iê, wymawianym płynnie i szybko.'},
  'tuyết, chuyên'],
 ['uya',
  {'ko': "한글의 '우야'에 해당하는데 베트남어 가운데 이 모음이 보편적으로 사용되는 단어는 khuya뿐입니다.",
   'zh': '相當於注音符號的ㄨㄧㄚ，但在越南語中，普遍使用這一元音的單詞只有khuya。',
   'en': 'It corresponds to "uya" (oo-ee-ah), and in Vietnamese, khuya is the only word in which this vowel is '
         'commonly used.',
   'ja': '「ウイア」に相当しますが、ベトナム語の中でこの母音が一般的に使われる単語はkhuyaだけです。',
   'de': 'Entspricht „u-i-a“; das einzige gebräuchliche vietnamesische Wort mit diesem Laut ist „khuya“.',
   'fr': "Correspond à « ou-i-a » ; le seul mot vietnamien d'usage courant comportant cette voyelle est « khuya ».",
   'pl': 'Odpowiada połączeniu „u-i-a”; jedynym powszechnym wietnamskim słowem z tą samogłoską jest „khuya”.'},
  'khuya']]

NORTH_SOUTH_NOTE = {'ko': "-anh/-ach, -inh/-ich, -ênh/-êch의 남부식 발음은 화자·지역에 따라 편차가 커서, 위 예시는 '이런 경향이 있다' 정도로 참고해 주세요. 이 밖에 일부 남부 지역에서는 받침 "
       '-n/-ng, -t/-c의 발음이 서로 가까워지는 경향도 있지만, 마찬가지로 정해진 규칙으로 배우기는 어려워요.',
 'zh': '-anh/-ach、-inh/-ich、-ênh/-êch的南部發音因說話者和地區而異，差異較大，上面的例子僅供參考，理解為“有這種傾向”即可。此外，部分南部地區韻尾 -n/-ng、-t/-c '
       '的發音也有互相接近的傾向，但同樣很難當作固定規則來學習。',
 'en': 'The Southern pronunciation of -anh/-ach, -inh/-ich, and -ênh/-êch varies considerably by speaker and region, '
       'so please take the examples above only as "a general tendency." In addition, in some Southern regions the '
       'pronunciations of the final consonants -n/-ng and -t/-c also tend to converge, but likewise this is difficult '
       'to learn as a fixed rule.',
 'ja': '-anh/-ach、-inh/-ich、-ênh/-êchの南部式発音は話者や地域によって差が大きいため、上記の例は「そのような傾向がある」程度の参考としてください。このほか一部の南部地域では、末子音 '
       '-n/-ng、-t/-c の発音が互いに近づく傾向もありますが、同様に決まった規則として学ぶのは難しいです。',
 'de': 'Die südliche Aussprache von -anh/-ach, -inh/-ich und -ênh/-êch variiert je nach Sprecher und Region erheblich, '
       'daher dienen die obigen Beispiele nur als allgemeine Orientierung. Zudem neigen in einigen südlichen Regionen '
       'auch die Auslaute -n/-ng und -t/-c dazu, sich anzunähern, was sich jedoch nicht als feste Regel '
       'verallgemeinern lässt.',
 'fr': 'La prononciation méridionale de -anh/-ach, -inh/-ich et -ênh/-êch varie considérablement selon les locuteurs '
       "et les régions ; les exemples ci-dessus ne sont donc donnés qu'à titre de tendance générale. De plus, dans "
       "certaines régions du Sud, les consonnes finales -n/-ng et -t/-c ont aussi tendance à se rapprocher, sans qu'il "
       "soit possible d'en faire une règle fixe.",
 'pl': 'Wymowa południowa zbitków -anh/-ach, -inh/-ich oraz -ênh/-êch różni się znacznie w zależności od mówcy i '
       'regionu, dlatego powyższe przykłady należy traktować jedynie jako ogólną tendencję. Ponadto w niektórych '
       'rejonach południa spółgłoski końcowe -n/-ng oraz -t/-c wykazują tendencję do zbliżania się w wymowie, lecz nie '
       'da się tego ująć w sztywną regułę.'}

NORTH_SOUTH_DIFFS = [{'title': 'd-, gi-, r-',
  'north': {'ko': '셋 다 보통 [z]로 같게 발음해요. 성대를 울리며 마찰로 내는 소리(영어 z와 비슷)라서 한국어 ㅈ과는 다른 소리예요.',
            'zh': '三者通常都念 [z]，接近英語的 z 音（華語沒有完全對應的注音符號）。',
            'en': 'All three are usually pronounced the same, [z], close to the English z sound.',
            'ja': '三つともふつうは同じ [z] で、日本語のザ行に近い音です。',
            'de': 'Alle drei werden im Norden meist gleich ausgesprochen, als stimmhaftes s [z].',
            'fr': 'Dans le Nord, les trois se prononcent généralement de la même façon, comme un z '
                  'sonore [z].',
            'pl': 'Na północy wszystkie trzy wymawia się zwykle tak samo, jak dźwięczne „z” [z].',
            'vi': 'Cả ba thường được đọc giống nhau là [z], gần với âm z của tiếng Anh.',
            'cs': 'Všechna tři se obvykle vyslovují stejně, jako znělé [z].',
            'zh_cn': '三者通常都读 [z]，接近英语的 z 音。',
            'hu': 'Északon mindhármat általában ugyanúgy, zöngés [z]-nek ejtik.',
            'id': 'Di Utara ketiganya biasanya dilafalkan sama, yaitu [z], mirip bunyi z.'},
  'south': {'ko': 'd와 gi는 반모음 [j](영어 yes의 y와 비슷)로, r은 [r]~[ɹ] 등 화자에 따라 다른 r 소리로 발음해서 서로 구별해요.',
            'zh': 'd 和 gi 念半母音 [j]（類似英語 yes 的 y），r 則依說話者念成 [r]~[ɹ] 等不同的 r 音，兩者有區別。',
            'en': 'd and gi are pronounced as the glide [j], like the y in English yes, while r is '
                  'an r sound such as [r]~[ɹ] that varies by speaker, so they are kept apart.',
            'ja': 'd と gi は英語 yes の y のような半母音 [j]、r は話者によって [r]~[ɹ] などさまざまな r 音で発音し、互いに区別します。',
            'de': 'd und gi werden als Halbvokal [j] gesprochen, r dagegen als ein je nach Sprecher '
                  'unterschiedliches r wie [r]~[ɹ] – sie werden also unterschieden.',
            'fr': 'Dans le Sud, d et gi se prononcent comme la semi-voyelle [j], tandis que r est '
                  'un r variable selon les locuteurs, comme [r]~[ɹ] — ils sont donc distingués.',
            'pl': 'd oraz gi wymawia się jak półsamogłoskę „j” [j], natomiast r jako różne, '
                  'zależnie od mówiącego, „r” w rodzaju [r]~[ɹ] — są więc rozróżniane.',
            'vi': 'd và gi đọc là bán nguyên âm [j] (gần y trong yes của tiếng Anh), còn r là âm r '
                  'khác nhau tùy người như [r]~[ɹ], nên chúng được phân biệt.',
            'cs': 'd a gi se vyslovují jako polosamohláska [j] (jako anglické y ve slově yes), r '
                  'jako různé r podle mluvčího, například [r]~[ɹ] – rozlišují se tedy.',
            'zh_cn': 'd 和 gi 读半元音 [j]（类似英语 yes 的 y），r 则因人而异读成 [r]~[ɹ] 等不同的 r 音，两者有区别。',
            'hu': 'A d és a gi [j] félhangzó (mint az angol yes y-ja), az r pedig beszélőnként '
                  'eltérő r-hang, például [r]~[ɹ], így megkülönböztetik őket.',
            'id': 'd dan gi dilafalkan sebagai semivokal [j] (seperti y dalam yes bahasa Inggris), '
                  'sedangkan r berupa bunyi r yang berbeda menurut penutur, misalnya [r]~[ɹ], '
                  'sehingga keduanya dibedakan.'},
  'examples': [{'word': 'da',
                'mean': {'ko': '피부',
                         'zh': '皮膚',
                         'en': 'skin',
                         'ja': '肌',
                         'de': 'Haut',
                         'fr': 'peau',
                         'pl': 'skóra',
                         'vi': 'da (bì)',
                         'cs': 'kůže',
                         'zh_cn': '皮肤',
                         'hu': 'bőr',
                         'id': 'kulit'},
                'north': '자[za]',
                'south': '야[ja]'},
               {'word': 'gia',
                'mean': {'ko': '집·더하다',
                         'zh': '家·加',
                         'en': 'house · to add',
                         'ja': '家·加える',
                         'de': 'Haus · hinzufügen',
                         'fr': 'maison · ajouter',
                         'pl': 'dom · dodawać',
                         'vi': 'nhà · thêm',
                         'cs': 'dům · přidat',
                         'zh_cn': '家·加',
                         'hu': 'ház · hozzáad',
                         'id': 'rumah · menambah'},
                'north': '자[za]',
                'south': '야[ja]'},
               {'word': 'Giê-hô-va',
                'mean': {'ko': '여호와',
                         'zh': '耶和華',
                         'en': 'Jehovah',
                         'ja': 'エホバ',
                         'de': 'Jehova',
                         'fr': 'Jéhovah',
                         'pl': 'Jehowa',
                         'vi': 'Giê-hô-va',
                         'cs': 'Jehova',
                         'zh_cn': '耶和华',
                         'hu': 'Jehova',
                         'id': 'Yehuwa'},
                'north': '제호바[zɛhova]',
                'south': '예호바[jɛhova]'},
               {'word': 'Giê-su',
                'mean': {'ko': '예수',
                         'zh': '耶穌',
                         'en': 'Jesus',
                         'ja': 'イエス',
                         'de': 'Jesus',
                         'fr': 'Jésus',
                         'pl': 'Jezus',
                         'vi': 'Giê-su',
                         'cs': 'Ježíš',
                         'zh_cn': '耶稣',
                         'hu': 'Jézus',
                         'id': 'Yesus'},
                'north': '제수[zɛsu]',
                'south': '예수[jɛsu]'},
               {'word': 'ra',
                'mean': {'ko': '나가다',
                         'zh': '出去',
                         'en': 'to go out',
                         'ja': '出る、出かける',
                         'de': 'hinausgehen',
                         'fr': 'sortir',
                         'pl': 'wychodzić',
                         'vi': 'đi ra',
                         'cs': 'vyjít ven',
                         'zh_cn': '出去',
                         'hu': 'kimegy',
                         'id': 'keluar'},
                'north': '자[za]',
                'south': '굴린 라[ra]'}]},
 {'title': 's-, x-',
  'north': {'ko': '보통 둘 다 [s]로 발음해서 같거나 거의 같게 들려요(한국어 화자에게는 ㅆ에 가깝게 들리기도 해요). 철자대로 또박또박 읽을 때는 구별하기도 '
                  '해요.',
            'zh': '通常兩者都念 [s]，聽起來相同或幾乎相同。照拼寫仔細朗讀時也有人會區分。',
            'en': 'Both are usually pronounced [s], so they sound the same or nearly so. Some '
                  'speakers keep them apart when reading carefully by the spelling.',
            'ja': 'ふつうはどちらも [s] と発音され、同じかほぼ同じに聞こえます。つづりどおり丁寧に読むときに区別する人もいます。',
            'de': 'Beide werden im Norden meist als [s] gesprochen und klingen gleich oder fast '
                  'gleich. Manche unterscheiden sie beim sorgfältigen Lesen nach der Schrift.',
            'fr': 'Dans le Nord, les deux se prononcent généralement [s] et sonnent pareil ou '
                  'presque. Certains les distinguent en lisant soigneusement d’après l’orthographe.',
            'pl': 'Na północy oba wymawia się zwykle jako [s], więc brzmią tak samo lub prawie tak '
                  'samo. Niektórzy rozróżniają je przy starannym czytaniu zgodnie z pisownią.',
            'vi': 'Thường cả hai đều đọc là [s] nên nghe giống hoặc gần giống nhau. Có người vẫn '
                  'phân biệt khi đọc cẩn thận theo chính tả.',
            'cs': 'Obě se obvykle vyslovují [s], takže znějí stejně nebo téměř stejně. Někteří je '
                  'při pečlivém čtení podle pravopisu rozlišují.',
            'zh_cn': '通常两者都读 [s]，听起来相同或几乎相同。照拼写认真朗读时也有人会区分。',
            'hu': 'Északon általában mindkettőt [s]-nek ejtik, így azonosan vagy majdnem azonosan '
                  'hangzanak. Gondos, helyesírás szerinti olvasáskor egyesek megkülönböztetik őket.',
            'id': 'Di Utara keduanya biasanya dilafalkan [s], sehingga terdengar sama atau hampir '
                  'sama. Sebagian penutur membedakannya saat membaca dengan cermat sesuai ejaan.'},
  'south': {'ko': '많은 지역에서 x는 [s], s는 혀를 뒤로 살짝 드는 [ʂ](또는 [ʃ])로 구별해요. 다만 호찌민시의 젊은 화자처럼 s도 [s]로 발음하는 '
                  '사람도 많아요.',
            'zh': '許多地區 x 念 [s]，s 念舌頭稍微向後抬起的 [ʂ]（或 [ʃ]），兩者有區別。不過也有很多人（例如胡志明市的年輕人）把 s 也念成 [s]。',
            'en': 'In many areas x is [s] and s is [ʂ] (or [ʃ]), with the tongue raised slightly '
                  'further back. Many speakers, such as younger people in Ho Chi Minh City, also '
                  'say s as [s].',
            'ja': '多くの地域で x は [s]、s は舌を少し奥に上げる [ʂ]（または [ʃ]）と区別します。ただしホーチミン市の若い話者のように s も [s] '
                  'で発音する人も多くいます。',
            'de': 'In vielen Gegenden ist x [s] und s [ʂ] (oder [ʃ]) mit etwas weiter hinten '
                  'angehobener Zunge. Viele, etwa jüngere Sprecher in Ho-Chi-Minh-Stadt, sprechen '
                  'aber auch s als [s].',
            'fr': 'Dans de nombreuses régions, x est [s] et s est [ʂ] (ou [ʃ]), la langue un peu '
                  'plus en arrière. Beaucoup de locuteurs, comme les jeunes de Hô Chi Minh-Ville, '
                  'prononcent toutefois aussi s comme [s].',
            'pl': 'W wielu regionach x to [s], a s to [ʂ] (lub [ʃ]) z językiem nieco dalej w tył. '
                  'Wiele osób, np. młodsze pokolenie w Ho Chi Minh, wymawia jednak także s jako '
                  '[s].',
            'vi': 'Ở nhiều nơi, x là [s] còn s là [ʂ] (hoặc [ʃ]), lưỡi hơi lùi về sau. Tuy vậy '
                  'nhiều người, như lớp trẻ ở TP. Hồ Chí Minh, cũng đọc s là [s].',
            'cs': 'V mnoha oblastech je x [s] a s [ʂ] (nebo [ʃ]) s jazykem lehce vzadu. Mnoho '
                  'mluvčích, například mladší generace v Ho Či Minově Městě, však vyslovuje i s '
                  'jako [s].',
            'zh_cn': '许多地区 x 读 [s]，s 读舌头稍微向后抬起的 [ʂ]（或 [ʃ]），两者有区别。不过也有很多人（比如胡志明市的年轻人）把 s 也读成 [s]。',
            'hu': 'Sok helyen az x [s], az s pedig kissé hátrébb képzett [ʂ] (vagy [ʃ]). Sokan, '
                  'például a Ho Si Minh-városi fiatalok, azonban az s-t is [s]-nek ejtik.',
            'id': 'Di banyak daerah x adalah [s] dan s adalah [ʂ] (atau [ʃ]) dengan lidah sedikit '
                  'lebih ke belakang. Namun banyak penutur, misalnya generasi muda di Kota Ho Chi '
                  'Minh, juga melafalkan s sebagai [s].'},
  'examples': [{'word': 'sa',
                'mean': {'ko': '떨어지다',
                         'zh': '掉落',
                         'en': 'to fall',
                         'ja': '落ちる',
                         'de': 'fallen',
                         'fr': 'tomber',
                         'pl': 'spadać',
                         'vi': 'rơi',
                         'cs': 'padat',
                         'zh_cn': '掉落',
                         'hu': 'leesik',
                         'id': 'jatuh'},
                'north': '싸[sa]',
                'south': '말아 올린 샤[ʂa]'},
               {'word': 'xa',
                'mean': {'ko': '멀다',
                         'zh': '遠',
                         'en': 'to be far',
                         'ja': '遠い',
                         'de': 'weit entfernt sein',
                         'fr': 'loin, être éloigné',
                         'pl': 'daleki',
                         'vi': 'xa',
                         'cs': 'být daleko',
                         'zh_cn': '远',
                         'hu': 'messze van',
                         'id': 'jauh'},
                'north': '싸[sa]',
                'south': '싸[sa]'}]},
 {'title': 'ch-, tr-',
  'north': {'ko': '보통 둘 다 [c]~[tɕ]로 같게 발음해요. 기식이 없어서 한국어 화자에게는 ㅉ에 가깝게 들리지만 같은 소리는 아니에요.',
            'zh': '通常兩者同音，念 [c]~[tɕ]，不送氣。',
            'en': 'Both are usually pronounced the same, [c]~[tɕ], without aspiration.',
            'ja': 'ふつうはどちらも同じ [c]~[tɕ] で、息を伴いません。',
            'de': 'Beide werden im Norden meist gleich gesprochen, [c]~[tɕ], unbehaucht.',
            'fr': 'Dans le Nord, les deux se prononcent généralement de la même façon, [c]~[tɕ], '
                  'sans aspiration.',
            'pl': 'Na północy oba wymawia się zwykle tak samo, [c]~[tɕ], bez przydechu.',
            'vi': 'Thường cả hai đều đọc giống nhau là [c]~[tɕ], không bật hơi.',
            'cs': 'Obě se obvykle vyslovují stejně, [c]~[tɕ], bez přídechu.',
            'zh_cn': '通常两者同音，读 [c]~[tɕ]，不送气。',
            'hu': 'Északon általában mindkettőt ugyanúgy, hehezet nélkül ejtik: [c]~[tɕ].',
            'id': 'Di Utara keduanya biasanya dilafalkan sama, [c]~[tɕ], tanpa aspirasi.'},
  'south': {'ko': '전통적으로 ch는 [c], tr은 혀끝을 뒤로 드는 권설음 [ʈ](흔히 [ʈʂ]처럼 들림)로 구별해요. 다만 젊은 화자를 중심으로 tr을 '
                  'ch처럼 발음하는 경우도 많아요.',
            'zh': '傳統上 ch 念 [c]，tr 念舌尖向後抬起的捲舌音 [ʈ]（常聽起來像 [ʈʂ]），兩者有區別。不過也有很多人（尤其是年輕人）把 tr 念成和 ch 一樣。',
            'en': 'Traditionally ch is [c] and tr is the retroflex [ʈ], with the tongue tip raised '
                  'further back (often sounding like [ʈʂ]). Many speakers, especially younger ones, '
                  'pronounce tr like ch.',
            'ja': '伝統的には ch は [c]、tr は舌先を奥に上げるそり舌音 [ʈ]（しばしば [ʈʂ] のように聞こえる）と区別します。ただし若い話者を中心に tr を '
                  'ch と同じに発音する人も多くいます。',
            'de': 'Traditionell ist ch [c] und tr das retroflexe [ʈ] mit weiter hinten angehobener '
                  'Zungenspitze (klingt oft wie [ʈʂ]). Viele, vor allem jüngere Sprecher, sprechen '
                  'tr aber wie ch.',
            'fr': 'Traditionnellement, ch est [c] et tr la rétroflexe [ʈ], pointe de la langue '
                  'relevée plus en arrière (souvent entendue comme [ʈʂ]). Beaucoup de locuteurs, '
                  'surtout jeunes, prononcent toutefois tr comme ch.',
            'pl': 'Tradycyjnie ch to [c], a tr to retrofleksyjne [ʈ] z czubkiem języka uniesionym '
                  'dalej w tył (często brzmi jak [ʈʂ]). Wiele osób, zwłaszcza młodszych, wymawia '
                  'jednak tr jak ch.',
            'vi': 'Theo truyền thống, ch là [c] còn tr là âm quặt lưỡi [ʈ], đầu lưỡi nâng lùi về '
                  'sau (thường nghe như [ʈʂ]). Nhiều người, nhất là lớp trẻ, đọc tr giống ch.',
            'cs': 'Tradičně je ch [c] a tr retroflexní [ʈ] se špičkou jazyka zdviženou víc vzadu '
                  '(často zní jako [ʈʂ]). Mnoho mluvčích, zvláště mladších, však vyslovuje tr jako '
                  'ch.',
            'zh_cn': '传统上 ch 读 [c]，tr 读舌尖向后抬起的卷舌音 [ʈ]（常听起来像 [ʈʂ]），两者有区别。不过也有很多人（尤其是年轻人）把 tr 读成和 ch '
                     '一样。',
            'hu': 'Hagyományosan a ch [c], a tr pedig a hátrébb emelt nyelvheggyel képzett '
                  'retroflex [ʈ] (gyakran [ʈʂ]-nek hangzik). Sokan, főleg a fiatalok, azonban a '
                  'tr-t is a ch-hoz hasonlóan ejtik.',
            'id': 'Secara tradisional ch adalah [c] dan tr adalah retrofleks [ʈ] dengan ujung lidah '
                  'terangkat lebih ke belakang (sering terdengar seperti [ʈʂ]). Namun banyak '
                  'penutur, terutama generasi muda, melafalkan tr seperti ch.'},
  'examples': [{'word': 'cha',
                'mean': {'ko': '아버지',
                         'zh': '父親',
                         'en': 'father',
                         'ja': '父',
                         'de': 'Vater',
                         'fr': 'père',
                         'pl': 'ojciec',
                         'vi': 'bố, cha',
                         'cs': 'otec',
                         'zh_cn': '父亲',
                         'hu': 'apa',
                         'id': 'ayah'},
                'north': '짜[ca]',
                'south': '짜[ca]'},
               {'word': 'tra',
                'mean': {'ko': '조사하다',
                         'zh': '調查',
                         'en': 'to investigate',
                         'ja': '調査する',
                         'de': 'untersuchen',
                         'fr': 'enquêter, vérifier',
                         'pl': 'badać, sprawdzać',
                         'vi': 'tra cứu',
                         'cs': 'zkoumat',
                         'zh_cn': '调查',
                         'hu': 'vizsgál',
                         'id': 'memeriksa'},
                'north': '짜[ca]',
                'south': '말아 올린 짜[ʈa]'}]},
 {'title': 'v-',
  'north': {'ko': '영어 v처럼 윗니로 아랫입술을 살짝 물어 발음해요.',
            'zh': '像英語的v一樣，用上齒輕咬下唇發音。',
            'en': "Like the English v, it's pronounced by lightly biting the lower lip with the upper teeth.",
            'ja': '英語のvのように、上の歯で下唇を軽く噛んで発音します。',
            'de': 'Wird wie ein deutsches w gesprochen, indem die oberen Zähne die Unterlippe leicht berühren.',
            'fr': 'Se prononce comme un v français, les dents du haut touchant légèrement la lèvre inférieure.',
            'pl': 'Wymawia się jak polskie „w” [v], przy czym górne zęby lekko dotykają dolnej wargi.'},
  'south': {'ko': '특히 편한 대화체에서는 d, gi처럼 반모음 y[j]에 가깝게 발음되고, 미엔 떠이(Miền Tây) 지역에서는 [z]처럼 발음하기도 해요.',
            'zh': '尤其在輕鬆的口語中，發音接近半元音y[j]，與d、gi相似，而在湄西（Miền Tây）地區，有時也會發成[z]。',
            'en': "Especially in casual spoken style, it's pronounced close to the semivowel y[j], like d and gi, and "
                  'in the Miền Tây region it is sometimes pronounced like [z].',
            'ja': '特に気楽な話し言葉では、d、giのように半母音y[j]に近く発音され、ミエンタイ（Miền Tây）地域では[z]のように発音されることもあります。',
            'de': 'Vor allem in der Umgangssprache nähert es sich wie d und gi dem Halbvokal j [j] an; im westlichen '
                  'Mekong-Delta (Miền Tây) wird es manchmal wie [z] gesprochen.',
            'fr': 'Dans le langage familier, il tend à se prononcer comme une semi-voyelle [j] (comme d et gi) ; dans '
                  'le delta du Mékong (Miền Tây), il est parfois prononcé [z].',
            'pl': 'W języku potocznym często zbliża się do półsamogłoski „j” [j] (jak d i gi); w delcie Mekongu (Miền '
                  'Tây) bywa wymawiane jako [z].'},
  'examples': [{'word': 'về',
                'mean': {'ko': '돌아가다',
                         'zh': '回去',
                         'en': 'to go back / return',
                         'ja': '帰る',
                         'de': 'zurückkehren',
                         'fr': 'retourner, rentrer',
                         'pl': 'wracać'},
                'north': '베[vɛ]',
                'south': '예[jɛ]'},
               {'word': 'Việt Nam',
                'mean': {'ko': '베트남',
                         'zh': '越南',
                         'en': 'Vietnam',
                         'ja': 'ベトナム',
                         'de': 'Vietnam',
                         'fr': 'Vietnam',
                         'pl': 'Wietnam'},
                'north': '비엣남[viɛt̚ nam]',
                'south': '이엑남[jiɛk̚ nam]'}]},
 {'title': {'ko': 'hỏi, ngã 성조',
            'zh': 'hỏi, ngã 聲調',
            'en': 'hỏi, ngã tones',
            'ja': 'hỏi, ngã 声調',
            'de': 'Töne hỏi und ngã',
            'fr': 'Tons hỏi et ngã',
            'pl': 'Tony hỏi i ngã'},
  'north': {'ko': 'hỏi(낮게 내렸다 다시 오름)와 ngã(급격히 끊었다 오름)를 분명히 다른 성조로 구별해요.',
            'zh': 'hỏi（先降後升）和ngã（驟然中斷後上揚）明確區分為不同的聲調。',
            'en': 'hỏi (falling then rising) and ngã (abruptly cut off then rising) are clearly distinguished as '
                  'different tones.',
            'ja': 'hỏi（低く下げてから再び上げる）とngã（急に途切れてから上がる）を明確に異なる声調として区別します。',
            'de': 'hỏi (fallend-steigend) und ngã (unterbrochen-steigend) werden klar als zwei verschiedene Töne '
                  'unterschieden.',
            'fr': 'Le hỏi (descendant-montant) et le ngã (montant avec coupure) sont clairement distingués comme deux '
                  'tons différents.',
            'pl': 'Tony hỏi (opadająco-wznoszący) oraz ngã (wznoszący z przerwaniem krtaniowym) są wyraźnie '
                  'rozróżniane jako dwa odrębne tony.'},
  'south': {'ko': '두 성조를 구별하지 않고 거의 같은, 낮게 내려가는 소리로 발음하는 경우가 많아요. (글로 쓸 때는 두 지역 모두 구별해서 씁니다.)',
            'zh': '很多情況下不區分這兩種聲調，而是發成幾乎相同的低降調。（書寫時兩地都會加以區分。）',
            'en': 'In many cases, the two tones are not distinguished and are instead pronounced almost identically, '
                  'as a low falling tone. (In writing, both regions still distinguish them.)',
            'ja': '二つの声調を区別せず、ほぼ同じ低く下がる音で発音することが多いです。（文字で書くときは、両地域とも区別して書きます。）',
            'de': 'Im Süden werden beide Töne oft nicht unterschieden und klingen fast gleich wie ein tief fallender '
                  'Ton. (In der Schrift unterscheiden beide Regionen sie weiterhin.)',
            'fr': 'Dans le Sud, ces deux tons sont souvent confondus et prononcés de manière presque identique, comme '
                  "un ton grave descendant. (À l'écrit, ils restent distincts dans tout le pays.)",
            'pl': 'Na południu oba tony często nie są rozróżniane w mowie i brzmią niemal identycznie jako niski ton '
                  'opadający. (W piśmie rozróżnia się je w całym kraju).'},
  'examples': [{'word': 'nghỉ',
                'mean': {'ko': '쉬다 (hỏi)',
                         'zh': '休息 (hỏi)',
                         'en': 'to rest (hỏi)',
                         'ja': '休む (hỏi)',
                         'de': 'sich ausruhen (hỏi)',
                         'fr': 'se reposer (hỏi)',
                         'pl': 'odpoczywać (hỏi)'},
                'north': '낮게 내렸다 오름',
                'south': '낮게 내려가는 소리'},
               {'word': 'nghĩ',
                'mean': {'ko': '생각하다 (ngã)',
                         'zh': '想、思考 (ngã)',
                         'en': 'to think (ngã)',
                         'ja': '考える (ngã)',
                         'de': 'denken, nachdenken (ngã)',
                         'fr': 'penser, réfléchir (ngã)',
                         'pl': 'myśleć (ngã)'},
                'north': '끊었다 오름',
                'south': '낮게 내려가는 소리 (nghỉ와 비슷하게 들림)'}]},
 {'title': '-ây',
  'north': {'ko': '어이[ʌ̆j]로 발음해요.',
            'zh': '發音為어이[ʌ̆j]。',
            'en': "It's pronounced as 어이[ʌ̆j].",
            'ja': '어이[ʌ̆j]と発音します。',
            'de': 'Wird als [ʌ̆j] ausgesprochen.',
            'fr': 'Se prononce [ʌ̆j].',
            'pl': 'Wymawia się jako [ʌ̆j].'},
  'south': {'ko': '아이[ăj]로 발음해요.',
            'zh': '發音為아이[ăj]。',
            'en': "It's pronounced as 아이[ăj].",
            'ja': '아이[ăj]と発音します。',
            'de': 'Wird als [ăj] ausgesprochen.',
            'fr': 'Se prononce [ăj].',
            'pl': 'Wymawia się jako [ăj].'},
  'examples': [{'word': 'ấy',
                'mean': {'ko': '그',
                         'zh': '他；那',
                         'en': 'he; that',
                         'ja': '彼；その',
                         'de': 'jener, jene, das',
                         'fr': 'ce, cet, cette',
                         'pl': 'tamten, ów'},
                'north': '어이[ʌ̆j]',
                'south': '아이[ăj]'},
               {'word': 'vậy',
                'mean': {'ko': '그렇게',
                         'zh': '那樣',
                         'en': 'like that, so',
                         'ja': 'そのように',
                         'de': 'so, auf diese Weise',
                         'fr': 'ainsi, comme cela',
                         'pl': 'tak, w ten sposób'},
                'north': 'vㅓ이[vʌ̆j]',
                'south': '야이[jăj]'}]},
 {'title': '-ê',
  'north': {'ko': '에[ɛ]로 발음해요.',
            'zh': '發音為에[ɛ]。',
            'en': "It's pronounced as 에[ɛ].",
            'ja': '에[ɛ]と発音します。',
            'de': 'Wird als [ɛ] ausgesprochen.',
            'fr': 'Se prononce [ɛ].',
            'pl': 'Wymawia się jako [ɛ].'},
  'south': {'ko': '에이[ɛj]로 발음해요.',
            'zh': '發音為에이[ɛj]。',
            'en': "It's pronounced as 에이[ɛj].",
            'ja': '에이[ɛj]と発音します。',
            'de': 'Wird als [ɛj] ausgesprochen.',
            'fr': 'Se prononce [ɛj].',
            'pl': 'Wymawia się jako [ɛj].'},
  'examples': [{'word': 'để',
                'mean': {'ko': '...하기 위해',
                         'zh': '為了……',
                         'en': 'in order to ...',
                         'ja': '…するために',
                         'de': 'um zu ...',
                         'fr': 'pour, afin de',
                         'pl': 'aby, żeby'},
                'north': '데[ɗɛ]',
                'south': '데이[ɗɛj]'},
               {'word': 'kể',
                'mean': {'ko': '이야기하다',
                         'zh': '說話/聊天',
                         'en': 'to talk',
                         'ja': '話す',
                         'de': 'erzählen',
                         'fr': 'raconter',
                         'pl': 'opowiadać'},
                'north': '께[kɛ]',
                'south': '께이[kɛj]'}]},
 {'title': '-n',
  'north': {'ko': "-n 받침은 'ㄴ'[n] 받침으로 발음해요.",
            'zh': "-n收音發音為'ㄴ'[n]收音。",
            'en': "The -n final is pronounced as the 'ㄴ'[n] final.",
            'ja': "-nパッチムは'ㄴ'[n]パッチムで発音します。",
            'de': 'Der Auslaut -n wird als klares [n] gesprochen.',
            'fr': 'La finale -n se prononce comme un n alvéolaire [n].',
            'pl': 'Spółgłoska końcowa -n wymawiana jest jako wyraźne przedniojęzykowo-dziąsłowe [n].'},
  'south': {'ko': "-n 받침은 'ㅇ'[ŋ] 받침에 가깝게 발음해요.",
            'zh': "-n收音發音接近'ㅇ'[ŋ]收音。",
            'en': "The -n final is pronounced close to the 'ㅇ'[ŋ] final.",
            'ja': "-nパッチムは'ㅇ'[ŋ]パッチムに近く発音します。",
            'de': 'Der Auslaut -n wird dem velaren [ŋ] angenähert.',
            'fr': 'La finale -n se rapproche de la nasale vélaire [ŋ].',
            'pl': 'Spółgłoska końcowa -n zbliża się do tylnojęzykowego [ŋ].'},
  'examples': [{'word': 'ăn',
                'mean': {'ko': '먹다',
                         'zh': '吃',
                         'en': 'to eat',
                         'ja': '食べる',
                         'de': 'essen',
                         'fr': 'manger',
                         'pl': 'jeść'},
                'north': '안[an]',
                'south': '앙[aŋ]'},
               {'word': 'bốn',
                'mean': {'ko': '숫자 4',
                         'zh': '數字4',
                         'en': 'Number 4',
                         'ja': '数字4',
                         'de': 'Zahl 4',
                         'fr': 'chiffre 4',
                         'pl': 'liczba 4'},
                'north': '본[ɓo:n]',
                'south': '봉[ɓo:ŋ͡m]'}]},
 {'title': '-ên',
  'north': {'ko': "-ên은 '엔'[ɛn]으로 발음해요.",
            'zh': '-ên發音為엔[ɛn]。',
            'en': '-ên is pronounced as 엔[ɛn].',
            'ja': '-ênは엔[ɛn]と発音します。',
            'de': 'Wird als [ɛn] ausgesprochen.',
            'fr': 'Se prononce [ɛn].',
            'pl': 'Wymawia się jako [ɛn].'},
  'south': {'ko': "-ên은 '엉'[əŋ]에 가깝게 발음해요.",
            'zh': '-ên發音接近엉[əŋ]。',
            'en': '-ên is pronounced close to 엉[əŋ].',
            'ja': '-ênは엉[əŋ]に近く発音します。',
            'de': 'Wird eher wie [əŋ] ausgesprochen.',
            'fr': 'Se rapproche de [əŋ].',
            'pl': 'Zbliża się w wymowie do [əŋ].'},
  'examples': [{'word': 'bên',
                'mean': {'ko': '쪽·측',
                         'zh': '邊·側',
                         'en': 'side · side',
                         'ja': '側·方',
                         'de': 'Seite',
                         'fr': 'côté',
                         'pl': 'strona, brzeg'},
                'north': '벤[bɛn]',
                'south': '벙[bəŋ]'},
               {'word': 'tên',
                'mean': {'ko': '이름',
                         'zh': '名字',
                         'en': 'name',
                         'ja': '名前',
                         'de': 'Name',
                         'fr': 'nom',
                         'pl': 'imię, nazwa'},
                'north': '뗀[tɛn]',
                'south': '떵[təŋ]'}]},
 {'title': '-t',
  'north': {'ko': "-t 받침은 'ㅅ' 받침으로 발음해요.",
            'zh': "-t收音發音為'ㅅ'收音。",
            'en': "The -t final is pronounced as the 'ㅅ' final.",
            'ja': "-tパッチムは'ㅅ'パッチムで発音します。",
            'de': 'Der Auslaut -t wird als dentales [t̚] gesprochen.',
            'fr': 'La finale -t se prononce comme une occlusive dentale [t̚].',
            'pl': 'Spółgłoska końcowa -t wymawiana jest jako zwarta zębowa [t̚].'},
  'south': {'ko': "-t 받침을 'ㄱ' 받침처럼 발음해요.",
            'zh': "-t收音發音像'ㄱ'收音一樣。",
            'en': "The -t final is pronounced like the 'ㄱ' final.",
            'ja': "-tパッチムを'ㄱ'パッチムのように発音します。",
            'de': 'Der Auslaut -t wird wie ein k-Schlusslaut [k̚] gesprochen.',
            'fr': 'La finale -t se prononce comme une occlusive vélaire [k̚].',
            'pl': 'Spółgłoska końcowa -t wymawiana jest jak k-końcowe [k̚].'},
  'examples': [{'word': 'một',
                'mean': {'ko': '숫자 1',
                         'zh': '數字1',
                         'en': 'Number 1',
                         'ja': '数字1',
                         'de': 'Zahl 1',
                         'fr': 'chiffre 1',
                         'pl': 'liczba 1'},
                'north': '못[mot̚]',
                'south': '목[mok̚]'},
               {'word': 'kẹt',
                'mean': {'ko': '끼다',
                         'zh': '戴,套上',
                         'en': 'to wear (accessories), to put on',
                         'ja': 'はめる、着ける',
                         'de': 'steckenbleiben, eingeklemmt sein',
                         'fr': 'être coincé, bloqué',
                         'pl': 'utknąć, zablokować się'},
                'north': '깻[ket̚]',
                'south': '깩[kek̚]'}]},
 {'title': '-anh, -ach',
  'north': {'ko': "-a는 아이[ɐj]로 읽고, -nh는 'ㅇ'[ɲ] 받침으로, -ch는 'ㄱ'[k̚] 받침으로 발음해요.",
            'zh': "-a讀作아이[ɐj]，-nh發音為'ㅇ'[ɲ]收音，-ch發音為'ㄱ'[k̚]收音。",
            'en': "-a is read as 아이[ɐj], -nh is pronounced with the 'ㅇ'[ɲ] final, and -ch is pronounced with the "
                  "'ㄱ'[k̚] final.",
            'ja': "-aは아이[ɐj]と読み、-nhは'ㅇ'[ɲ]パッチムで、-chは'ㄱ'[k̚]パッチムで発音します。",
            'de': '-a wird als [ɐj] gesprochen, -nh als palatales [ɲ] und -ch als palatales [k̚].',
            'fr': '-a se prononce [ɐj], -nh comme nasale palatale [ɲ] et -ch comme occlusive palatale [k̚].',
            'pl': '-a wymawia się jako [ɐj], -nh jako podniebienne [ɲ], a -ch jako podniebienne [k̚].'},
  'south': {'ko': "-a는 아[a]로 읽고, -nh는 'ㄴ'[n] 받침으로, -ch는 'ㅅ'[t̚] 받침으로 발음해요.",
            'zh': "-a讀作아[a]，-nh發音為'ㄴ'[n]收音，-ch發音為'ㅅ'[t̚]收音。",
            'en': "-a is read as 아[a], -nh is pronounced with the 'ㄴ'[n] final, and -ch is pronounced with the 'ㅅ'[t̚] "
                  'final.',
            'ja': "-aは아[a]と読み、-nhは'ㄴ'[n]パッチムで、-chは'ㅅ'[t̚]パッチムで発音します。",
            'de': '-a wird als [a] gesprochen, -nh als [n] und -ch als [t̚].',
            'fr': '-a se prononce [a], -nh comme [n] et -ch comme [t̚].',
            'pl': '-a wymawia się jako [a], -nh jako [n], a -ch jako [t̚].'},
  'examples': [{'word': 'anh',
                'mean': {'ko': '형·오빠',
                         'zh': '哥哥',
                         'en': 'older brother',
                         'ja': '兄',
                         'de': 'älterer Bruder',
                         'fr': 'frère aîné',
                         'pl': 'starszy brat'},
                'north': '아잉·아인의 중간[ʔɐjɲ]',
                'south': '안[an]'},
               {'word': 'sách',
                'mean': {'ko': '책', 'zh': '書', 'en': 'book', 'ja': '本', 'de': 'Buch', 'fr': 'livre', 'pl': 'książka'},
                'north': '싸익[sɐjk̚]',
                'south': '삿[sat̚]'}]},
 {'title': '-inh, -ich / -ênh, -êch',
  'north': {'ko': 'inh·ênh, ich·êch를 앞모음(i/ê)에 따라 서로 다른 구개음으로 구별해서 발음해요.',
            'zh': 'inh·ênh、ich·êch根據前元音（i/ê）的不同，作為不同的顎音加以區分發音。',
            'en': 'inh·ênh and ich·êch are distinguished and pronounced as different palatal sounds depending on the '
                  'preceding vowel (i/ê).',
            'ja': 'inh·ênh、ich·êchを前舌母音（i/ê）に応じて、互いに異なる口蓋音として区別して発音します。',
            'de': 'inh·ênh und ich·êch werden je nach vorangehendem Vokal (i/ê) als unterschiedliche Gaumenlaute '
                  'unterschieden.',
            'fr': 'inh·ênh et ich·êch sont distingués comme des sons palataux différents selon la voyelle précédente '
                  '(i/ê).',
            'pl': 'inh·ênh oraz ich·êch są rozróżniane jako różne głoski podniebienne w zależności od poprzedzającej '
                  'samogłoski (i/ê).'},
  'south': {'ko': '구개음 색채가 옅어지면서, i 계열(linh, lịch)은 -ưn, -ưt에 가까운 소리로, ê 계열(kênh, ếch)은 -en, -et에 가까운 소리로 서로 다르게 합쳐지는 '
                  '경향이 있어요.',
            'zh': '隨著顎音色彩變淡，i系列（linh, lịch）趨向於接近-ưn, -ưt的音，ê系列（kênh, ếch）趨向於接近-en, -et的音，兩者呈現出不同的合併趨勢。',
            'en': 'As the palatal quality weakens, the i-series (linh, lịch) tends to merge toward a sound close to '
                  '-ưn, -ưt, while the ê-series (kênh, ếch) tends to merge toward a sound close to -en, -et — the two '
                  'merge differently.',
            'ja': '口蓋音的な色合いが薄れるにつれ、i系列（linh, lịch）は-ưn, -ưtに近い音へ、ê系列（kênh, ếch）は-en, -etに近い音へと、互いに異なる形で合流する傾向があります。',
            'de': 'Da der palatale Charakter schwächer wird, nähert sich die i-Reihe (linh, lịch) Lauten wie -ưn, -ưt '
                  'an, während die ê-Reihe (kênh, ếch) Lauten wie -en, -et ähnelt.',
            'fr': "Le caractère palatal s'estompant, la série en i (linh, lịch) tend vers -ưn, -ưt, tandis que la "
                  'série en ê (kênh, ếch) tend vers -en, -et.',
            'pl': 'Ponieważ cechy podniebienne zanikają, seria z i (linh, lịch) zbliża się do -ưn, -ưt, podczas gdy '
                  'seria z ê (kênh, ếch) do -en, -et.'},
  'examples': [{'word': 'linh',
                'mean': {'ko': '영(靈)',
                         'zh': '靈',
                         'en': 'spirit',
                         'ja': '霊',
                         'de': 'Geist',
                         'fr': 'esprit',
                         'pl': 'duch'},
                'north': '링·린의 중간[liɲ]',
                'south': '른[lɨn]'},
               {'word': 'lịch',
                'mean': {'ko': '달력·역사(曆/歷)',
                         'zh': '日曆·歷史(曆/歷)',
                         'en': 'calendar · history (曆/歷)',
                         'ja': '暦・歴史（曆/歴）',
                         'de': 'Kalender · Geschichte',
                         'fr': 'calendrier · histoire',
                         'pl': 'kalendarz · historia'},
                'north': '릭[lik̚]',
                'south': '릇[lɨt̚]'},
               {'word': 'kênh',
                'mean': {'ko': '채널·수로',
                         'zh': '頻道·水道',
                         'en': 'channel · waterway',
                         'ja': 'チャンネル·水路',
                         'de': 'Kanal · Wasserweg',
                         'fr': 'chaîne · canal',
                         'pl': 'kanał wodny'},
                'north': '께잉·께인의 중간[kejɲ]',
                'south': '껜[ken]'},
               {'word': 'ếch',
                'mean': {'ko': '개구리',
                         'zh': '青蛙',
                         'en': 'frog',
                         'ja': 'カエル',
                         'de': 'Frosch',
                         'fr': 'grenouille',
                         'pl': 'żaba'},
                'north': '에익[ejk̚]',
                'south': '엣[et̚]'}]}]

NORTH_SOUTH_EXTRA_NOTES = [{'ko': '하노이 발음을 기준으로, 파열음 /p, t, k/는 음절 끝에서 불파음화되어 각각 [p̚, t̚, k̚]로 실현돼요. (위 표에서 ̚ 표시가 이를 나타내요.)',
  'zh': '以河內發音為準，塞音/p, t, k/在音節末尾會變為不除阻音，分別實現為[p̚, t̚, k̚]。（上表中的 ̚ 符號即表示這一點。）',
  'en': 'Based on Hanoi pronunciation, the stops /p, t, k/ become unreleased at the end of a syllable, realized as '
        '[p̚, t̚, k̚] respectively. (The ̚ mark in the table above indicates this.)',
  'ja': 'ハノイ発音を基準に、破裂音/p, t, k/は音節の終わりで内破音化し、それぞれ[p̚, t̚, k̚]として実現されます。（上の表の ̚ の印がこれを表します。）',
  'de': 'Ausgehend von der Aussprache in Hanoi werden die Plosive /p, t, k/ am Silbenende nicht gelöst (implosiv) und '
        'als [p̚, t̚, k̚] realisiert. (Das Zeichen ̚ in der Tabelle oben zeigt dies an.)',
  'fr': 'Dans la prononciation de Hanoï, les occlusives /p, t, k/ en fin de syllabe ne sont pas relâchées (implosives) '
        "et sont réalisées sous les formes [p̚, t̚, k̚]. (Le symbole ̚ dans le tableau ci-dessus l'indique.)",
  'pl': 'Opierając się na wymowie z Hanoi, spółgłoski zwarte /p, t, k/ na końcu sylaby nie mają plozji (implozywne) i '
        'są realizowane odpowiednio jako [p̚, t̚, k̚]. (Symbol ̚ w powyższej tabeli to wskazuje).'},
 {'ko': '하노이 지방의 모음은 기본적으로 9개이며, 이 중 â[ʌ̆]와 ă[ă]는 다른 모음보다 짧게 발음돼요. â[ʌ̆]와 ơ[ɤ]의 차이는 그리 두드러지지 않아서, 인지적으로 구별이 되는지도 분명하지 '
        '않아요.',
  'zh': '河內地區的元音基本上有9個，其中â[ʌ̆]和ă[ă]比其他元音發音更短。â[ʌ̆]和ơ[ɤ]之間的差異並不十分明顯，因此在認知上是否能夠區分也並不清楚。',
  'en': 'Hanoi has basically 9 vowels, among which â[ʌ̆] and ă[ă] are pronounced shorter than the other vowels. The '
        "difference between â[ʌ̆] and ơ[ɤ] is not very pronounced, so it's not even clear whether it is cognitively "
        'distinguishable.',
  'ja': 'ハノイ地方の母音は基本的に9個あり、そのうちâ[ʌ̆]とă[ă]は他の母音より短く発音されます。â[ʌ̆]とơ[ɤ]の違いはあまり目立たないため、認知的に区別されているのかもはっきりしません。',
  'de': 'Im Dialekt von Hanoi gibt es im Wesentlichen 9 Vokale, von denen â[ʌ̆] und ă[ă] kürzer als die übrigen Vokale '
        'ausgesprochen werden. Der Unterschied zwischen â[ʌ̆] und ơ[ɤ] ist wenig ausgeprägt, sodass er kaum '
        'wahrnehmbar ist.',
  'fr': 'Le dialecte de Hanoï compte essentiellement 9 voyelles, parmi lesquelles â[ʌ̆] et ă[ă] sont prononcées plus '
        "brièvement que les autres. La différence entre â[ʌ̆] et ơ[ɤ] est si peu marquée qu'il est difficile de les "
        "distinguer nettement à l'oreille.",
  'pl': 'Dialekt Hanoi obejmuje zasadniczo 9 samogłosek, z których â[ʌ̆] oraz ă[ă] wymawia się krócej niż pozostałe. '
        'Różnica między â[ʌ̆] a ơ[ɤ] jest tak nieznaczna, że jest niemal niedostrzegalna dla ucha.'},
 {'ko': '모음 i, ư, u([i], [ɨ], [u])는 자음 k, ng 앞에서는 [ɪ], [ɪ̈], [ʊ]로 발음돼요. 모음 표기가 항상 일관적이면 좋겠지만 실제로는 그렇지 않아서, 이중모음이나 받침이 '
        '있는 모음에서는 소리가 미묘하게 달라지는 경우가 있어요.',
  'zh': '元音i, ư, u（[i], [ɨ], [u]）在輔音k, ng前會發成[ɪ], [ɪ̈], [ʊ]。雖然希望元音標記始終保持一致，但實際上並非如此，因此在雙元音或帶韻尾的元音中，讀音有時會出現細微的差異。',
  'en': 'The vowels i, ư, u ([i], [ɨ], [u]) are pronounced as [ɪ], [ɪ̈], [ʊ] before the consonants k, ng. It would be '
        'nice if vowel notation were always consistent, but in reality it is not, so in diphthongs or vowels with a '
        'final consonant, the sound sometimes differs subtly.',
  'ja': '母音i, ư, u（[i], [ɨ], [u]）は子音k, ngの前では[ɪ], [ɪ̈], '
        '[ʊ]と発音されます。母音表記が常に一貫していればよいのですが、実際にはそうではないため、二重母音やパッチムのある母音では、音が微妙に異なる場合があります。',
  'de': 'Die Vokale i, ư, u ([i], [ɨ], [u]) werden vor den Konsonanten k und ng als [ɪ], [ɪ̈], [ʊ] gesprochen. Die '
        'Vokalschreibung ist in der Praxis nicht immer völlig einheitlich, sodass bei Diphthongen oder Vokalen mit '
        'Auslautkonsonant subtile Klangunterschiede auftreten können.',
  'fr': 'Les voyelles i, ư, u ([i], [ɨ], [u]) se prononcent [ɪ], [ɪ̈], [ʊ] devant les consonnes k et ng. La notation '
        "des voyelles n'étant pas toujours totalement uniforme dans la pratique, de subtiles variations peuvent "
        "apparaître dans les diphtongues ou les voyelles suivies d'une consonne finale.",
  'pl': 'Samogłoski i, ư, u ([i], [ɨ], [u]) przed spółgłoskami k oraz ng wymawia się jako [ɪ], [ɪ̈], [ʊ]. Zapis '
        'samogłosek w praktyce nie zawsze bywa w pełni jednolity, toteż przy dyftongach lub samogłoskach ze spółgłoską '
        'końcową mogą pojawiać się subtelne niuanse brzmieniowe.'}]
