# "교과 > 범용 언어 생성표" subtab.
# The booklet (pages 66-73) prints this master word bank 8 times as
# "범용 언어 생성표 -1" through "-8", each later table simply a prefix of the
# previous one (fewer rows, and from table 6 on, fewer columns) -- used as a
# set of progressively-smaller handouts for a substitution drill: pick one
# word from each column and combine it into "주어 + (조동사) + 동사 + (ở) + 장소".
# Rather than re-typing 8 near-duplicate tables, SENTENCE_GEN_BANK holds the
# full master table (stage -1, all 20 rows / 4 columns) once, and
# SENTENCE_GEN_STAGES records how each of the 8 printed handouts trims it.
#
# SENTENCE_GEN_INTRO and every "kr" gloss in SENTENCE_GEN_BANK are stored as
# {"ko","zh","en","ja"} dicts so js_json() (see build_app.py) serializes them
# straight into JS objects/strings app_logic.js's T() helper can read directly.

SENTENCE_GEN_INTRO = {'ko': '범용언어 생성법은 정해진 단어 은행에서 주어·조동사·동사·장소를 하나씩 골라 "주어 + (조동사) + 동사 + (ở) + 장소" 순서로 이어 붙이면 문장이 '
       '완성되는 연습법이에요. 학습반에서는 이 표를 총 8장(−1~−8)의 유인물로 나눠주는데, 뒤로 갈수록 표가 줄어들어요 (−1~−6은 줄 수가 점점 줄고, −7은 '
       "'장소' 칸이, −8은 '동사' 칸까지 빠져요) — 표가 작아질수록 스스로 채워야 할 부분이 많아지는 셈이에요.",
 'zh': '"通用語言生成法"是從固定的詞庫中依次選取主語、助動詞、動詞、地點，然後按照"主語 + (助動詞) + 動詞 + (ở) + '
       '地點"的順序拼接起來完成句子的練習法。學習班會把這張表分成共8張（−1~−8）講義發給學員，越往後表格越簡化（−1~−6的行數逐漸減少，−7去掉了"地點"欄，−8連"動詞"欄也去掉了）——表格越小，需要自己填寫的部分就越多。',
 'en': 'The "universal sentence generation method" is a practice technique where you pick a '
       'subject, auxiliary verb, verb, and place one at a time from a fixed word bank, then string '
       'them together in the order "subject + (auxiliary verb) + verb + (ở) + place" to complete a '
       'sentence. In the class, this table is handed out as a total of 8 sheets (−1 through −8), '
       'and the table gets smaller further along (−1 through −6 have progressively fewer rows, −7 '
       'drops the "place" column, and −8 drops even the "verb" column) — the smaller the table '
       'gets, the more you have to fill in yourself.',
 'ja': '「汎用言語生成法」とは、決まった単語バンクから主語・助動詞・動詞・場所を一つずつ選び、「主語＋（助動詞）＋動詞＋（ở）＋場所」の順につなげて文を完成させる練習法です。学習クラスではこの表を全8枚（−1〜−8）のプリントに分けて配りますが、後ろに行くほど表が小さくなります（−1〜−6は行数がだんだん減り、−7は「場所」の欄が、−8は「動詞」の欄までなくなります）－表が小さくなるほど、自分で埋めなければならない部分が多くなるわけです。',
 'de': 'Die „Universelle Satzbildungsmethode“ ist eine Übungsmethode, bei der man aus einer '
       'vorgegebenen Wortbank nacheinander Subjekt, Modalverb, Verb und Ort auswählt und sie in '
       'der Reihenfolge „Subjekt + (Modalverb) + Verb + (ở) + Ort“ zu einem vollständigen Satz '
       'zusammenfügt. Im Sprachkurs wird diese Tabelle in insgesamt 8 Handouts (−1 bis −8) '
       'ausgeteilt, wobei die Tabelle nach hinten hin immer kleiner wird (−1 bis −6 haben immer '
       'weniger Zeilen, in −7 entfällt die Spalte „Ort“ und in −8 sogar die Spalte „Verb“) – je '
       'kleiner die Tabelle wird, desto mehr muss man selbst ergänzen.'}

SENTENCE_GEN_BANK = {'subjects': [{'vi': 'Tôi', 'kr': {'ko': '나', 'zh': '我', 'en': 'I, me', 'ja': '私', 'de': 'ich'}},
              {'vi': 'Chúng tôi',
               'kr': {'ko': '우리(듣는 사람 제외)',
                      'zh': '我們（不包括聽者）',
                      'en': 'we (excluding the listener)',
                      'ja': '私たち（聞き手を除く）',
                      'de': 'wir (ohne Zuhörer)'}},
              {'vi': 'Chúng ta',
               'kr': {'ko': '우리(듣는 사람 포함)',
                      'zh': '我們（包括聽者）',
                      'en': 'we (including the listener)',
                      'ja': '私たち（聞き手を含む）',
                      'de': 'wir (mit Zuhörer)'}},
              {'vi': 'Anh',
               'kr': {'ko': '형제님/당신(남성)',
                      'zh': '弟兄/您(男性)',
                      'en': 'Brother / you (male)',
                      'ja': '兄弟/あなた(男性)',
                      'de': 'Bruder / du (männlich)'}},
              {'vi': 'Anh ấy',
               'kr': {'ko': '그 남자',
                      'zh': '那個男人',
                      'en': 'that man',
                      'ja': 'その男',
                      'de': 'er / jener Mann'}},
              {'vi': 'Chị',
               'kr': {'ko': '자매님/당신(여성)',
                      'zh': '姐妹/您(女性)',
                      'en': 'Sister / you (female)',
                      'ja': '姉妹/あなた(女性)',
                      'de': 'Schwester / du (weiblich)'}},
              {'vi': 'Chị ấy',
               'kr': {'ko': '그 여자',
                      'zh': '那個女人',
                      'en': 'that woman',
                      'ja': 'その女',
                      'de': 'sie / jene Frau'}},
              {'vi': 'Họ',
               'kr': {'ko': '그들', 'zh': '他們', 'en': 'they', 'ja': '彼ら', 'de': 'sie (Plural)'}},
              {'vi': 'Em tôi',
               'kr': {'ko': '내 동생',
                      'zh': '我的弟弟(妹妹)',
                      'en': 'my younger sibling',
                      'ja': '私の弟(妹)',
                      'de': 'mein jüngeres Geschwister'}},
              {'vi': 'Mẹ tôi',
               'kr': {'ko': '우리 어머니',
                      'zh': '我媽媽',
                      'en': 'my mother',
                      'ja': '私の母',
                      'de': 'meine Mutter'}},
              {'vi': 'Bố tôi',
               'kr': {'ko': '우리 아버지',
                      'zh': '我爸爸',
                      'en': 'my father',
                      'ja': '私の父',
                      'de': 'mein Vater'}},
              {'vi': 'Các anh chị',
               'kr': {'ko': '형제자매님들',
                      'zh': '弟兄姐妹們',
                      'en': 'brothers and sisters',
                      'ja': '兄弟姉妹の皆さん',
                      'de': 'Brüder und Schwestern'}},
              {'vi': 'Học viên của tôi',
               'kr': {'ko': '내 성경 공부생',
                      'zh': '我的聖經研究生',
                      'en': 'my Bible student',
                      'ja': '私の聖書研究生',
                      'de': 'mein Bibelschüler'}},
              {'vi': 'Người Việt',
               'kr': {'ko': '베트남 사람',
                      'zh': '越南人',
                      'en': 'Vietnamese person',
                      'ja': 'ベトナム人',
                      'de': 'Vietnamese / Vietnamesin'}},
              {'vi': 'Người Hàn',
               'kr': {'ko': '한국 사람',
                      'zh': '韓國人',
                      'en': 'Korean person',
                      'ja': '韓国人',
                      'de': 'Koreaner / Koreanerin'}},
              {'vi': 'Gia đình tôi',
               'kr': {'ko': '우리 가족',
                      'zh': '我們的家人',
                      'en': 'our family',
                      'ja': '私たちの家族',
                      'de': 'unsere Familie'}},
              {'vi': 'Anh Hùng',
               'kr': {'ko': '훙 형제',
                      'zh': 'Hưng弟兄',
                      'en': 'Brother Hưng',
                      'ja': 'Hưng兄弟',
                      'de': 'Bruder Hùng'}},
              {'vi': 'Chị Hoa',
               'kr': {'ko': '화 자매',
                      'zh': 'Hoa姐妹',
                      'en': 'Sister Hoa',
                      'ja': 'Hoa姉妹',
                      'de': 'Schwester Hoa'}},
              {'vi': 'Vợ anh Minh',
               'kr': {'ko': '밍 형제의 아내',
                      'zh': 'Minh弟兄的妻子',
                      'en': "Brother Minh's wife",
                      'ja': 'Minh兄弟の妻',
                      'de': 'die Frau von Bruder Minh'}},
              {'vi': 'Chồng chị Huyền',
               'kr': {'ko': '후이엔 자매의 남편',
                      'zh': 'Huyền姐妹的丈夫',
                      'en': "Sister Huyền's husband",
                      'ja': 'Huyền姉妹の夫',
                      'de': 'der Mann von Schwester Huyền'}}],
 'modals': [{'vi': 'có thể',
             'kr': {'ko': '~할 수 있다', 'zh': '能~', 'en': 'can ~', 'ja': '~できる', 'de': 'können'}},
            {'vi': 'thích',
             'kr': {'ko': '좋아하다',
                    'zh': '喜歡',
                    'en': 'to like',
                    'ja': '好きだ',
                    'de': 'gerne mögen / gefallen'}},
            {'vi': 'muốn',
             'kr': {'ko': '원하다',
                    'zh': '想要',
                    'en': 'to want',
                    'ja': '望む',
                    'de': 'wollen / möchten'}},
            {'vi': 'cần',
             'kr': {'ko': '필요하다',
                    'zh': '需要',
                    'en': 'to be necessary',
                    'ja': '必要だ',
                    'de': 'brauchen / nötig sein'}},
            {'vi': 'nên',
             'kr': {'ko': '~하는 게 좋다',
                    'zh': '最好~',
                    'en': "should ~ / it's better to ~",
                    'ja': '~する方がよい',
                    'de': 'sollte / am besten'}},
            {'vi': 'phải',
             'kr': {'ko': '~해야 한다',
                    'zh': '必須~',
                    'en': 'must ~',
                    'ja': '~しなければならない',
                    'de': 'müssen'}},
            {'vi': 'không thể',
             'kr': {'ko': '~할 수 없다',
                    'zh': '不能~',
                    'en': 'cannot ~',
                    'ja': '~できない',
                    'de': 'nicht können'}},
            {'vi': 'không thích',
             'kr': {'ko': '좋아하지 않다',
                    'zh': '不喜歡',
                    'en': 'to not like',
                    'ja': '好きではない',
                    'de': 'nicht mögen'}},
            {'vi': 'không muốn',
             'kr': {'ko': '원하지 않다',
                    'zh': '不想要',
                    'en': 'to not want',
                    'ja': '望まない',
                    'de': 'nicht wollen'}},
            {'vi': 'không cần',
             'kr': {'ko': '필요 없다',
                    'zh': '不需要',
                    'en': 'not needed',
                    'ja': '必要ない',
                    'de': 'nicht brauchen / nicht nötig'}},
            {'vi': 'không nên',
             'kr': {'ko': '~하지 않는 게 좋다',
                    'zh': '最好不要~',
                    'en': "it's better not to ~",
                    'ja': '~しない方がよい',
                    'de': 'sollte nicht / lieber nicht'}},
            {'vi': 'sẽ',
             'kr': {'ko': '~할 것이다(미래)',
                    'zh': '將要~（將來）',
                    'en': 'will ~ (future)',
                    'ja': '~するだろう（未来）',
                    'de': 'werden (Zukunft)'}},
            {'vi': 'đang',
             'kr': {'ko': '~하고 있다(진행)',
                    'zh': '正在~（進行）',
                    'en': '~ing (progressive)',
                    'ja': '~している（進行）',
                    'de': 'gerade tun (Verlaufsform)'}},
            {'vi': 'đã',
             'kr': {'ko': '~했다(과거)',
                    'zh': '~了（過去）',
                    'en': '~ed (past)',
                    'ja': '~した（過去）',
                    'de': 'haben/sein getan (Vergangenheit)'}},
            {'vi': 'cần phải',
             'kr': {'ko': '반드시 ~해야 한다',
                    'zh': '必須~',
                    'en': 'must ~',
                    'ja': '必ず～しなければならない',
                    'de': 'unbedingt müssen'}},
            {'vi': 'thường',
             'kr': {'ko': '보통',
                    'zh': '通常',
                    'en': 'usually / normal',
                    'ja': '普通',
                    'de': 'gewöhnlich / normalerweise'}},
            {'vi': 'luôn luôn',
             'kr': {'ko': '항상', 'zh': '總是', 'en': 'always', 'ja': 'いつも', 'de': 'immer'}},
            {'vi': 'thỉnh thoảng',
             'kr': {'ko': '가끔', 'zh': '偶爾', 'en': 'sometimes', 'ja': 'たまに', 'de': 'manchmal'}},
            {'vi': 'cũng', 'kr': {'ko': '또한', 'zh': '也', 'en': 'also', 'ja': 'また', 'de': 'auch'}},
            {'vi': 'vẫn',
             'kr': {'ko': '여전히',
                    'zh': '仍然',
                    'en': 'still',
                    'ja': '依然として',
                    'de': 'immer noch / weiterhin'}}],
 'verbs': [{'vi': 'đọc sách',
            'kr': {'ko': '책을 읽다',
                   'zh': '讀書',
                   'en': 'to read a book',
                   'ja': '本を読む',
                   'de': 'ein Buch lesen'}},
           {'vi': 'xem phim',
            'kr': {'ko': '영화를 보다',
                   'zh': '看電影',
                   'en': 'to watch a movie',
                   'ja': '映画を見る',
                   'de': 'einen Film schauen'}},
           {'vi': 'nghe nhạc',
            'kr': {'ko': '음악을 듣다',
                   'zh': '聽音樂',
                   'en': 'to listen to music',
                   'ja': '音楽を聞く',
                   'de': 'Musik hören'}},
           {'vi': 'ăn cơm',
            'kr': {'ko': '밥을 먹다',
                   'zh': '吃飯',
                   'en': 'to eat (a meal)',
                   'ja': 'ご飯を食べる',
                   'de': 'zu Mittag/Abend essen (eine Mahlzeit)'}},
           {'vi': 'chat',
            'kr': {'ko': '채팅하다', 'zh': '聊天', 'en': 'to chat', 'ja': 'チャットする', 'de': 'chatten'}},
           {'vi': 'nghỉ',
            'kr': {'ko': '쉬다', 'zh': '休息', 'en': 'to rest', 'ja': '休む', 'de': 'sich ausruhen'}},
           {'vi': 'xem TV',
            'kr': {'ko': 'TV를 보다',
                   'zh': '看電視',
                   'en': 'watch TV',
                   'ja': 'テレビを見る',
                   'de': 'fernsehen'}},
           {'vi': 'học tiếng Việt',
            'kr': {'ko': '베트남어를 공부하다',
                   'zh': '學習越南語',
                   'en': 'to study Vietnamese',
                   'ja': 'ベトナム語を勉強する',
                   'de': 'Vietnamesisch lernen'}},
           {'vi': 'đi rao giảng',
            'kr': {'ko': '전도하러 가다',
                   'zh': '去傳道',
                   'en': 'to go out preaching',
                   'ja': '伝道に行く',
                   'de': 'predigen gehen'}},
           {'vi': 'dạo mát',
            'kr': {'ko': '산책하다',
                   'zh': '散步',
                   'en': 'to take a walk',
                   'ja': '散歩する',
                   'de': 'spazieren gehen'}},
           {'vi': 'chuẩn bị bài',
            'kr': {'ko': '예습(준비)하다',
                   'zh': '預習（準備）',
                   'en': 'to preview (prepare)',
                   'ja': '予習（準備）する',
                   'de': 'den Unterricht vorbereiten'}},
           {'vi': 'bị ốm',
            'kr': {'ko': '아프다',
                   'zh': '生病、痛',
                   'en': 'to be sick / hurt',
                   'ja': '痛い、具合が悪い',
                   'de': 'krank sein'}},
           {'vi': 'học Kinh Thánh',
            'kr': {'ko': '성경을 공부하다',
                   'zh': '研讀聖經',
                   'en': 'to study the Bible',
                   'ja': '聖書を勉強する',
                   'de': 'die Bibel studieren'}},
           {'vi': 'đến gần Đức Chúa Trời',
            'kr': {'ko': '하느님께 가까이 가다',
                   'zh': '親近上帝',
                   'en': 'to draw close to God',
                   'ja': '神に近づく',
                   'de': 'Gott näherkommen'}},
           {'vi': 'hút thuốc lá',
            'kr': {'ko': '담배를 피우다', 'zh': '抽菸', 'en': 'to smoke', 'ja': 'たばこを吸う', 'de': 'rauchen'}},
           {'vi': 'sống hạnh phúc',
            'kr': {'ko': '행복하게 살다',
                   'zh': '幸福地生活',
                   'en': 'to live happily',
                   'ja': '幸せに暮らす',
                   'de': 'glücklich leben'}},
           {'vi': 'hiểu chân lý',
            'kr': {'ko': '진리를 이해하다',
                   'zh': '理解真理',
                   'en': 'to understand the truth',
                   'ja': '真理を理解する',
                   'de': 'die Wahrheit verstehen'}},
           {'vi': 'dọn vệ sinh',
            'kr': {'ko': '청소하다',
                   'zh': '打掃',
                   'en': 'to clean',
                   'ja': '掃除する',
                   'de': 'saubermachen / putzen'}},
           {'vi': 'tặng quà',
            'kr': {'ko': '선물을 주다',
                   'zh': '送禮物',
                   'en': 'to give a gift',
                   'ja': 'プレゼントをあげる',
                   'de': 'ein Geschenk machen'}},
           {'vi': 'học tiếng Anh',
            'kr': {'ko': '영어를 공부하다',
                   'zh': '學英語',
                   'en': 'to study English',
                   'ja': '英語を勉強する',
                   'de': 'Englisch lernen'}}],
 'places': [{'vi': 'nhà',
             'kr': {'ko': '집', 'zh': '家', 'en': 'house', 'ja': '家', 'de': 'zu Hause / Haus'}},
            {'vi': 'nhà bạn',
             'kr': {'ko': '친구 집',
                    'zh': '朋友家',
                    'en': "friend's house",
                    'ja': '友達の家',
                    'de': 'Haus eines Freundes'}},
            {'vi': 'ký túc xá',
             'kr': {'ko': '기숙사', 'zh': '宿舍', 'en': 'dormitory', 'ja': '寮', 'de': 'Wohnheim'}},
            {'vi': 'công ty',
             'kr': {'ko': '회사', 'zh': '公司', 'en': 'company', 'ja': '会社', 'de': 'Firma / Büro'}},
            {'vi': 'Phòng Nước Trời',
             'kr': {'ko': '왕국회관',
                    'zh': '王國聚會所',
                    'en': 'Kingdom Hall',
                    'ja': '王国会館',
                    'de': 'Königreichssaal'}},
            {'vi': 'đường phố',
             'kr': {'ko': '거리', 'zh': '街道', 'en': 'street', 'ja': '通り', 'de': 'Straße'}},
            {'vi': 'địa đàng',
             'kr': {'ko': '낙원', 'zh': '樂園', 'en': 'paradise', 'ja': '楽園', 'de': 'Paradies'}},
            {'vi': 'quán ăn',
             'kr': {'ko': '식당',
                    'zh': '餐廳',
                    'en': 'restaurant',
                    'ja': 'レストラン',
                    'de': 'Restaurant / Gaststätte'}},
            {'vi': 'thư viện',
             'kr': {'ko': '도서관', 'zh': '圖書館', 'en': 'library', 'ja': '図書館', 'de': 'Bibliothek'}},
            {'vi': 'trường học',
             'kr': {'ko': '학교', 'zh': '學校', 'en': 'school', 'ja': '学校', 'de': 'Schule'}},
            {'vi': 'công viên',
             'kr': {'ko': '공원', 'zh': '公園', 'en': 'park', 'ja': '公園', 'de': 'Park'}},
            {'vi': 'trái đất',
             'kr': {'ko': '지구', 'zh': '地球', 'en': 'Earth', 'ja': '地球', 'de': 'Erde'}},
            {'vi': 'thế giới mới',
             'kr': {'ko': '신세계', 'zh': '新世界', 'en': 'New World', 'ja': '新世界', 'de': 'neue Welt'}},
            {'vi': 'nhà quê',
             'kr': {'ko': '시골', 'zh': '鄉下', 'en': 'countryside', 'ja': '田舎', 'de': 'auf dem Land'}},
            {'vi': 'thành phố',
             'kr': {'ko': '도시', 'zh': '城市', 'en': 'city', 'ja': '都市', 'de': 'Stadt'}},
            {'vi': 'Hàn Quốc',
             'kr': {'ko': '한국', 'zh': '韓國', 'en': 'Korea', 'ja': '韓国', 'de': 'Korea'}},
            {'vi': 'Việt Nam',
             'kr': {'ko': '베트남', 'zh': '越南', 'en': 'Vietnam', 'ja': 'ベトナム', 'de': 'Vietnam'}},
            {'vi': 'Mỹ', 'kr': {'ko': '미국', 'zh': '美國', 'en': 'USA', 'ja': 'アメリカ', 'de': 'USA'}},
            {'vi': 'Trung Quốc',
             'kr': {'ko': '중국', 'zh': '中國', 'en': 'China', 'ja': '中国', 'de': 'China'}},
            {'vi': 'Nhật Bản',
             'kr': {'ko': '일본', 'zh': '日本', 'en': 'Japan', 'ja': '日本', 'de': 'Japan'}}]}

# rows / cols for handouts -1 .. -8, as printed in the booklet
SENTENCE_GEN_STAGES = [{'stage': 1, 'rows': 20, 'cols': 4},
 {'stage': 2, 'rows': 18, 'cols': 4},
 {'stage': 3, 'rows': 15, 'cols': 4},
 {'stage': 4, 'rows': 11, 'cols': 4},
 {'stage': 5, 'rows': 8, 'cols': 4},
 {'stage': 6, 'rows': 5, 'cols': 4},
 {'stage': 7, 'rows': 5, 'cols': 3},
 {'stage': 8, 'rows': 5, 'cols': 2}]
