# "신권 용어" (theocratic/Kingdom vocabulary) extracted from the 16-week course PDF
# (pages 25-32, section title "신권 용어"). Each entry: (viet, hanja_or_None, kr).
#
# Hanja is included only when EVERY content syllable of the Vietnamese term has a
# confident Sino-Vietnamese (Hán Việt) reading; a leading grammatical/native prefix that
# commonly nominalizes an abstract noun ("sự", "lòng") is stripped before that check, since
# it isn't itself the borrowed content word. Proper nouns, transliterations, loanwords, and
# phrases mixing in a native Vietnamese word are left without hanja.

VOCAB = [
    # 대회
    ("đại hội", "大會", "대회"),
    ("kịch", "劇", "드라마"),
    ("anh giám thị vòng quanh", None, "순회 감독자"),
    ("vòng quanh", None, "순회구"),
    ("hội nghị vòng quanh", None, "순회 대회"),
    ("tình nguyện viên", "情願員", "자원봉사자"),
    # 도덕과 가정
    ("ngoại tình", "外情", "간음"),
    ("kết hôn", "結婚", "결혼"),
    ("dạy dỗ", None, "교육"),
    ("kết hợp với người xấu", None, "나쁜 교제"),
    ("đạo đức", "道德", "도덕"),
    ("đồng tính luyến ái", "同性戀愛", "동성애"),
    ("người hôn phối không tin đạo", None, "믿지 않는 배우자"),
    ("trâng tráo", None, "방종한"),
    ("vô luân", "無倫", "부도덕한"),
    ("giải trí", None, "여가활동"),
    ("ly dị", "離異", "이혼"),
    # 법/정치
    ("giao ước", None, "계약"),
    ("chủ nghĩa quốc gia", "主義國家", "국가주의"),
    ("Hội Quốc Liên", None, "국제 연맹"),
    ("Liên hợp Quốc", None, "국제 연합"),
    ("áp lực bạn bè", None, "동배의 압력"),
    ("luật pháp Môi-se", None, "모세의 율법"),
    ("đương đầu với vấn đề", None, "문제에 대처하다"),
    ("sự bắt bớ", None, "박해"),
    ("nguyên tắc Kinh Thánh", "原則經聖", "성서원칙"),
    ("sự thử thách", None, "시련"),
    ("Mười Điều Răn", None, "십계명"),
    ("lương tâm", "良心", "양심"),
    ("tổ chức Đức Giê-hô-va", None, "여호와의 조직"),
    ("tổ chức", "組織", "조직"),
    ("đấng Trung Gian", "中間", "중개자"),
    ("sự trung lập", "中立", "중립"),
    ("hoạn nạn lớn", None, "큰 환난"),
    ("thỏa hiệp", "妥協", "타협하다"),
    # 사람/인격체
    ("mười hai sứ đồ", None, "12사도"),
    ("một trăm bốn mươi bốn ngàn người", None, "144,000명"),
    ("Y-sơ-ra-ên xưa", None, "고대 이스라엘"),
    ("sự công lý", "公理", "공의"),
    ("nhân từ bao la", None, "과분한 친절"),
    ("tín đồ được xức dầu", None, "기름부음받은 그리스도인"),
    ("tín đồ được xức dầu còn sốt lại", None, "기름부음받은 남은 자"),
    ("chiên khác", None, "다른 양들"),
    ("Con một", None, "독생자"),
    ("Ác quỉ", "惡鬼", "마귀"),
    ("Mê-si", None, "메시아"),
    ("Sa-tan Ác quỉ", None, "사탄 마귀"),
    ("bài giảng trên núi", None, "산상 수훈"),
    ("thần khí thánh", "神氣聖", "성령"),
    ("bông trái thần khí thánh", None, "성령의 열매"),
    ("Giê-hô-va Đức Chúa Trời", None, "여호와 하느님"),
    ("con dê", None, "염소"),
    ("Y-sơ-ra-ên thiêng liêng", None, "영적 이스라엘"),
    ("Giê-su Ki-tô", None, "예수 그리스도"),
    ("sự tha thứ", None, "용서"),
    ("người Do Thái", None, "유대인"),
    ("sự công chính", "公正", "의"),
    ("Y-sơ-ra-ên", None, "이스라엘"),
    ("người lân cận", None, "이웃"),
    ("bầy nhỏ", None, "적은 무리"),
    ("Đấng Toàn Năng", "全能", "전능자"),
    ("môn đồ", "門徒", "제자"),
    ("thiên sứ", "天使", "천사"),
    ("lòng trung thành", "忠誠", "충성"),
    ("tình yêu thương thành tín", None, "충성스러운 사랑"),
    ("đầy tớ trung tín và khôn ngoan", None, "충실하고 슬기로운 종"),
    ("một đám đông lớn", None, "큰 무리"),
    ("con của Đức Chúa Trời", None, "하느님의 아들"),
    ("anh em", None, "형제"),
    ("đoàn thể anh em", None, "형제 관계"),
    # 지리
    ("Biển Ga-li-lê", None, "갈릴리 바다"),
    ("Núi Si-nai", None, "시나이 산"),
    ("Núi Si-ôn", None, "시온 산"),
    ("Đất Hứa", None, "약속의 땅"),
    ("vườn Ê-đen", None, "에덴동산"),
    # 태도/행실
    ("thăng bằng", None, "균형 잡힌"),
    ("giá chuộc", None, "대속"),
    ("khích lệ", "激勵", "동기를 부여하다"),
    ("tâm trạng", "心狀", "마음 상태"),
    ("nêu gương mẫu", None, "모범을 보이다"),
    ("chủ nghĩa vật chất", "主義物質", "물질주의"),
    ("thái độ tiêu cực", "態度消極", "부정적인 태도"),
    ("khả năng suy xét", None, "사고력"),
    ("nhân cách mới", None, "새 인간성"),
    ("lối sống", None, "생활 방식"),
    ("tình trạng thiêng liêng", None, "영성"),
    ("thức ăn thiêng liêng", None, "영적 양식"),
    ("hết mình", None, "영혼을 다한"),
    ("nhân cách cũ", None, "옛 인간성"),
    ("nhận thức", "認識", "인식하다"),
    ("Thái độ chỉ nghĩ đến mình", None, "자아 제일 주의적인 태도"),
    ("tinh thần", "精神", "정신"),
    ("trung thực", "忠實", "정직한"),
    ("thái độ", "態度", "태도"),
    ("bước tiến", None, "행로"),
    # 하느님과의 관계
    ("cuộc học hỏi Kinh Thánh tại nhà", None, "가정성서연구"),
    ("buổi thờ phượng gia đình", None, "가족 숭배"),
    ("học hỏi cá nhân", None, "개인 연구"),
    ("lòng sùng kính", "崇敬", "경건한 정성"),
    ("làm chứng nơi công cộng", None, "공개 증거"),
    ("khu vực", "區域", "구역"),
    ("cầu nguyện", "求願", "기도"),
    ("nguyên tắc về quyền làm đầu", None, "머리 직분 원칙"),
    ("người công bố chưa báp têm", None, "미침례 전도인"),
    ("báo cáo", "報告", "보고하다"),
    ("tiên phong phụ trợ", "先鋒輔助", "보조 파이오니아"),
    ("phục tùng", "服從", "복종"),
    ("thánh chức rao giảng", None, "봉사의 직무"),
    ("người phục vụ", None, "봉사자"),
    ("ô uế", "汚穢", "불결한"),
    ("làm chứng bán chính thức", None, "비공식 증거"),
    ("giáo sĩ", "教士", "선교인"),
    ("học viên Kinh Thánh", "學員經聖", "성서 연구생"),
    ("sự vâng lời", None, "순종"),
    ("A-men", None, "아멘"),
    ("rao giảng", None, "야외 봉사"),
    ("nhóm rao giảng", None, "야외봉사를 위한 모임"),
    ("Nhân chứng Giê-hô-va", None, "여호와의 증인"),
    ("học hỏi", None, "연구(하다)"),
    ("công chính", "公正", "의로운"),
    ("thăm lại", None, "재방문"),
    ("người phụng sự trọn thời gian", None, "전 시간 봉사자"),
    ("người công bố", None, "전도인"),
    ("chia sẻ niềm tin", None, "전파"),
    ("tiên phong đều đều", None, "정규 파이오니아"),
    ("sự hiểu biết chính xác", None, "정확한 지식"),
    ("cách trình bày", None, "제공 방법(봉사,연설)"),
    ("phát hành", "發行", "제공하다(잡지)"),
    ("tin mừng", None, "좋은 소식"),
    ("kinh lạy Cha", None, "주기도문"),
    ("làm chứng", None, "증거하다"),
    ("sửa trị", None, "징계하다"),
    ("ân phước", "恩福", "축복"),
    ("ấn phẩm", "印品", "출판물"),
    ("lòng trung thành", "忠誠", "충실함"),
    ("sự trọn thành", None, "충절"),
    ("báp têm", None, "침례"),
    ("tiên phong", "先鋒", "파이오니아"),
    ("quan hệ với Đức Chúa Trời", None, "하느님과의 관계"),
    ("dâng mình", None, "헌신하다"),
    ("rao giảng từng nhà", None, "호별방문"),
    ("sự ăn năn", None, "회개"),
    ("ăn năn", None, "회개하다"),
    # 의료
    ("sự phá thai", None, "낙태"),
    ("ma túy", "麻醉", "마약"),
    ("truyền máu", None, "수혈"),
    ("căng thẳng", None, "스트레스"),
    ("thói nghiện rượu", None, "알코올 의존증"),
    ("bệnh AIDS", None, "에이즈"),
    ("trầm cảm", "沈感", "우울증"),
    ("Giấy uỷ quyền chăm sóc sức khỏe", None, "의료 위임장"),
    # 정부
    ("Nước Trời", None, "왕국"),
    ("hoàn vũ", "寰宇", "우주적인"),
    ("vấn đề", "問題", "쟁점"),
    ("chính phủ", "政府", "정부"),
    ("quyền tối thượng", "權最上", "주권"),
    ("quyền cai trị", None, "통치권"),
    ("Nước Đức Chúa Trời", None, "하느님의 왕국"),
    ("chính quyền", "政權", "행정부"),
    # 조직
    ("xây dựng", None, "건축"),
    ("Lối sống và thánh chức -Chương trình nhóm họp", None, "그리스도인 생활과 집회 교재"),
    ("Tỉnh Thức!", None, "깨어라"),
    ("bài hát", None, "노래"),
    ("sách hát", None, "노래책"),
    ("Video", None, "동영상"),
    ("Bê-tên", None, "베델"),
    ("thành viên Bê-tên", None, "베델성원"),
    ("từ điển", "辭典", "사전"),
    ("sách", None, "서적"),
    ("quầy sách báo", None, "서적부"),
    ("Trụ sở Trung ương", None, "세계 본부"),
    ("Phòng Nước Trời được xây cấp tốc", None, "속성 건축 왕국회관"),
    ("niên giám", "年鑑", "연감"),
    ("sự đặt trước", None, "예약"),
    ("Thánh chức Nước Trời", None, "우리의 왕국봉사"),
    ("Trung tâm giáo dục của Hội Tháp Canh", None, "워치타워 교육센터"),
    ("Wallkill", None, "월킬"),
    ("trang web", None, "웹사이트"),
    ("tạp chí", "雜誌", "잡지"),
    ("tờ chuyên đề", None, "전도지"),
    ("hội đồng lãnh đạo", "會同領導", "중앙장로회"),
    ("Ủy ban Chi nhánh", None, "지부 위원회"),
    ("buổi họp", None, "집회"),
    # 종교
    ("tôn giáo sai lầm", None, "거짓 종교"),
    ("hàng giáo phẩm", None, "교직자"),
    ("đạo Đấng Ki-tô", None, "그리스도교"),
    ("khối Ki-tô giáo", None, "그리스도교국"),
    ("tín đồ Đấng Ki-tô", None, "그리스도인"),
    ("phần Kinh Thánh tiếng Hy Lạp", None, "그리스도인 그리스어 성경"),
    ("người Pha-ri-si", None, "바리새인"),
    ("bất tử", "不死", "불멸의"),
    ("câu Kinh Thánh", "句經聖", "성구"),
    ("Kinh Thánh", "經聖", "성서"),
    ("sự thờ phượng thanh sạch", None, "순결한 숭배"),
    ("Sheol", None, "스올"),
    ("phụng sự", "奉事", "신성한 봉사"),
    ("ngày Sa-bát", None, "안식(일)"),
    ("ma thuật", "魔術", "영매술"),
    ("sự sống", None, "영혼"),
    ("Lễ Ngũ Tuần", "禮五旬", "오순절"),
    ("Lễ Vượt qua", None, "유월절"),
    ("mô mả chung của nhân loại", None, "인류의 일반 무덤"),
    ("Tra xem Kinh Thánh mỗi ngày", None, "일용할 성구"),
    ("chương", "章", "장"),
    ("câu", "句", "절"),
    ("thầy tế lễ", None, "제사장"),
    ("chức tế lễ", "職祭禮", "제사직"),
    ("tôn giáo", "宗教", "종교"),
    ("chân lý", "眞理", "진리"),
    ("tiến hoá", "進化", "진화"),
    ("sự sáng tạo", "創造", "창조"),
    ("Đấng Tạo Hoá", "造化", "창조주"),
    ("Ba-by-lôn Lớn", None, "큰 바빌론"),
    ("lời Đức Chúa Trời", None, "하느님의 말씀"),
    ("Hades", None, "하데스"),
    ("cây khổ hình", None, "형주"),
    ("trận nước lụt", None, "홍수"),
    ("phần Kinh Thánh tiếng Hê-bơ-rơ", None, "히브리어 성경"),
    # 회중
    ("anh giám thị", "監視", "감독자"),
    ("diễn văn công cộng", "演文公共", "공개강연"),
    ("lối sống một tín đồ", None, "그리스도인 생활(집회)"),
    ("sự đóng góp", None, "기부"),
    ("người đọc bài", None, "낭독자"),
    ("loại bỏ", None, "내보냈다"),
    ("thư viện", "書院", "도서실"),
    ("micrô", None, "마이크"),
    ("anh giám thị công tác", "監視工作", "봉사감독자"),
    ("phụ tá", "輔佐", "봉사의 종"),
    ("Lối sống và Thánh chức", None, "생활과 봉사 집회"),
    ("thư ký", "書記", "서기"),
    ("đọc Kinh Thánh", None, "성경 낭독"),
    ("kho báu từ Kinh Thánh", None, "성경에 담긴 보물(집회)"),
    ("thời gian", "時間", "시간"),
    ("cải thiện thánh chức", "改善聖職", "야외봉사에 힘쓰십시오(집회)"),
    ("bục giảng", None, "연단"),
    ("bài giảng", None, "연설"),
    ("viên ngọc thiêng liêng", None, "영적보물 찾기(집회)"),
    ("Trường dành cho người rao truyền Nước Trời", None, "왕국 전파자 학교"),
    ("Phòng Nước Trời", None, "왕국회관"),
    ("chỉ định", "指定", "임명하다.(과제)"),
    ("trưởng lão", "長老", "장로"),
    ("hội đồng trưởng lão", "會同長老", "장로의 회"),
    ("phiên họp trưởng lão", None, "장로회의"),
    ("giám thị điều phối", "監視調配", "조정자"),
    ("phần đọc Kinh Thánh hằng tuần", None, "주간 성서 읽기 범위"),
    ("Bữa Ăn Tối Của Chúa", None, "주의 만찬"),
    ("chủ đề", "主題", "주제"),
    ("buổi họp tạp chí Tháp Canh", None, "파수대 연구(집회)"),
    ("món biểu tượng", None, "표상물"),
    ("tiền đóng góp", None, "헌금"),
    ("hộp đóng góp", None, "헌금함"),
    ("hội thánh", "會聖", "회중"),
    ("phần học Kinh Thánh của hội thánh", None, "회중 성서 연구"),
]
