TIME_ORDER_NOTE = {
    'ko': '베트남어도 한국어처럼 시(giờ)를 먼저 말하고 분(phút)을 그 뒤에 말해요 (예: 8 giờ 30 phút = 8시 30분). 하지만 "아침", "오후"처럼 시간대를 나타내는 말은 베트남어에서 숫자 뒤에 와요 — 이 부분은 한국어·중국어·일본어와 반대되는 순서예요. 예를 들어 한국어로는 "아침 8시"라고 시간대를 먼저 말하지만, 베트남어로는 "8 giờ sáng"처럼 시간대(sáng)를 맨 뒤에 붙여요.',
    'zh': '越南語和韓語一樣，先說「時」(giờ)，再說「分」(phút)（例：8 giờ 30 phút＝8點30分）。但是像「早上」、「下午」這樣表示時段的詞，在越南語裡是放在數字後面的——這一點和韓語、中文、日語的順序相反。例如中文會說「早上8點」，把時段放在前面，但越南語卻說「8 giờ sáng」，把時段(sáng)放在最後面。',
    'en': 'Like Korean, Vietnamese says the hour (giờ) first and the minute (phút) after it (e.g., 8 giờ 30 phút = 8:30). But words for time of day, like "morning" or "afternoon," come after the number in Vietnamese — the opposite order from Korean, Chinese, and Japanese. For example, Korean says "morning 8 o\'clock" with the time-of-day word first, but Vietnamese says "8 giờ sáng," putting the time-of-day word (sáng) last.',
    'ja': 'ベトナム語も韓国語と同じように、時(giờ)を先に言い、分(phút)を後に言います（例：8 giờ 30 phút＝8時30分）。しかし「朝」「午後」のように時間帯を表す言葉は、ベトナム語では数字の後に来ます——この部分は韓国語・中国語・日本語と反対の順序です。例えば日本語では「朝8時」と時間帯を先に言いますが、ベトナム語では「8 giờ sáng」のように時間帯(sáng)を一番後ろに付けます。',
    'de': 'Wie im Deutschen nennt das Vietnamesische zuerst die Stunde (giờ) und danach die Minute (phút) (z. B. 8 giờ 30 phút = 8 Uhr 30). Wörter für die Tageszeit wie „morgens“ oder „nachmittags“ stehen im Vietnamesischen jedoch hinter der Uhrzeit – anders als im Deutschen, wo man sie davor setzt. Während man auf Deutsch „morgens um 8 Uhr“ sagt, heißt es auf Vietnamesisch „8 giờ sáng“, wobei die Tageszeit (sáng) ganz am Ende steht.'
}

TIME_RUOI_KEM_NOTE = {
    'ko': '30분은 rưỡi(반)라는 말로 줄여 말할 수 있어요 (예: 8 giờ rưỡi = 8시 반, 8 giờ 30 phút과 같은 뜻). 정각이 되기 몇 분 전을 말할 때는 kém(모자라다, ~전)을 써서 다음 시각에서 뺀 분을 나타내요 (예: 5 giờ kém 10 phút = 5시가 되기에 10분이 모자란 시각, 즉 4시 50분).',
    'zh': '30分可以用rưỡi（半）這個詞來簡稱（例：8 giờ rưỡi＝8點半，和8 giờ 30 phút意思相同）。要說差幾分到整點時，會用kém（差、不足）表示比下一個整點少幾分（例：5 giờ kém 10 phút＝離5點還差10分鐘，也就是4點50分）。',
    'en': '30 minutes can be shortened to rưỡi ("half") — e.g., 8 giờ rưỡi = 8:30, the same as 8 giờ 30 phút. To say a few minutes before the hour, use kém ("short of," "to") to show how many minutes are subtracted from the next hour — e.g., 5 giờ kém 10 phút = 10 minutes short of 5 o\'clock, i.e., 4:50.',
    'ja': '30分はrưỡi（半分）という言葉で短く言うことができます（例：8 giờ rưỡi＝8時半、8 giờ 30 phútと同じ意味）。正時になる数分前を言うときはkém（足りない、~前）を使って、次の時刻から引いた分を表します（例：5 giờ kém 10 phút＝5時になるのに10分足りない時刻、つまり4時50分）。',
    'de': '30 Minuten können mit „rưỡi“ („halb“) verkürzt werden (z. B. 8 giờ rưỡi = halb 9 / 8 Uhr 30, gleiche Bedeutung wie 8 giờ 30 phút). Um Minuten vor der vollen Stunde auszudrücken, verwendet man „kém“ („vor“ / „weniger“) für die abgezogenen Minuten bis zur nächsten Stunde (z. B. 5 giờ kém 10 phút = 10 vor 5, also 4 Uhr 50).'
}

TIME_PERIODS = [
    {'vi': 'sáng',
     'kr': {'ko': '아침, 오전 (대략 새벽~11시)', 'zh': '早上、上午（約凌晨~11點）',
            'en': 'Morning, AM (roughly dawn–11am)', 'ja': '朝、午前（だいたい未明~11時）',
            'de': 'Morgen, Vormittag (ca. Morgengrauen–11 Uhr)'}},
    {'vi': 'trưa',
     'kr': {'ko': '낮, 정오 (대략 11시~1시)', 'zh': '中午（約11點~1點）',
            'en': 'Midday, noon (roughly 11am–1pm)', 'ja': '昼、正午（だいたい11時~1時）',
            'de': 'Mittag (ca. 11–13 Uhr)'}},
    {'vi': 'chiều',
     'kr': {'ko': '오후 (대략 1시~6시)', 'zh': '下午（約1點~6點）',
            'en': 'Afternoon (roughly 1pm–6pm)', 'ja': '午後（だいたい1時~6時）',
            'de': 'Nachmittag (ca. 13–18 Uhr)'}},
    {'vi': 'tối',
     'kr': {'ko': '저녁 (대략 6시~10시)', 'zh': '晚上（約6點~10點）',
            'en': 'Evening (roughly 6pm–10pm)', 'ja': '夕方・夜（だいたい6時~10時）',
            'de': 'Abend (ca. 18–22 Uhr)'}},
    {'vi': 'đêm',
     'kr': {'ko': '밤, 심야 (대략 10시~새벽)', 'zh': '深夜（約10點~凌晨）',
            'en': 'Night, late night (roughly 10pm–dawn)', 'ja': '夜、深夜（だいたい10時~未明）',
            'de': 'Nacht, späte Nacht (ca. 22 Uhr–Morgengrauen)'}},
    {'vi': 'khuya',
     'kr': {'ko': '심야, 아주 늦은 밤 (대략 자정~새벽)', 'zh': '深夜、非常晚的夜晚（約半夜~凌晨）',
            'en': 'Late night, the small hours (roughly midnight–dawn)', 'ja': '深夜、夜更け（だいたい真夜中~未明）',
            'de': 'Späte Nacht, Mitternachtsstunden (ca. Mitternacht–Morgengrauen)'}},
]

TIME_HOURS = [
    {'vi': 'một giờ', 'kr': {'ko': '1시', 'zh': '1點', 'en': "1 o'clock", 'ja': '1時', 'de': '1 Uhr'}},
    {'vi': 'hai giờ', 'kr': {'ko': '2시', 'zh': '2點', 'en': "2 o'clock", 'ja': '2時', 'de': '2 Uhr'}},
    {'vi': 'ba giờ', 'kr': {'ko': '3시', 'zh': '3點', 'en': "3 o'clock", 'ja': '3時', 'de': '3 Uhr'}},
    {'vi': 'bốn giờ', 'kr': {'ko': '4시', 'zh': '4點', 'en': "4 o'clock", 'ja': '4時', 'de': '4 Uhr'}},
    {'vi': 'năm giờ', 'kr': {'ko': '5시', 'zh': '5點', 'en': "5 o'clock", 'ja': '5時', 'de': '5 Uhr'}},
    {'vi': 'sáu giờ', 'kr': {'ko': '6시', 'zh': '6點', 'en': "6 o'clock", 'ja': '6時', 'de': '6 Uhr'}},
    {'vi': 'bảy giờ', 'kr': {'ko': '7시', 'zh': '7點', 'en': "7 o'clock", 'ja': '7時', 'de': '7 Uhr'}},
    {'vi': 'tám giờ', 'kr': {'ko': '8시', 'zh': '8點', 'en': "8 o'clock", 'ja': '8時', 'de': '8 Uhr'}},
    {'vi': 'chín giờ', 'kr': {'ko': '9시', 'zh': '9點', 'en': "9 o'clock", 'ja': '9時', 'de': '9 Uhr'}},
    {'vi': 'mười giờ', 'kr': {'ko': '10시', 'zh': '10點', 'en': "10 o'clock", 'ja': '10時', 'de': '10 Uhr'}},
    {'vi': 'mười một giờ', 'kr': {'ko': '11시', 'zh': '11點', 'en': "11 o'clock", 'ja': '11時', 'de': '11 Uhr'}},
    {'vi': 'mười hai giờ', 'kr': {'ko': '12시', 'zh': '12點', 'en': "12 o'clock", 'ja': '12時', 'de': '12 Uhr'}},
    {'vi': 'mười ba giờ', 'kr': {'ko': '13시', 'zh': '13點', 'en': "13 o'clock", 'ja': '13時', 'de': '13 Uhr'}},
    {'vi': 'mười bốn giờ', 'kr': {'ko': '14시', 'zh': '14點', 'en': "14 o'clock", 'ja': '14時', 'de': '14 Uhr'}},
    {'vi': 'mười lăm giờ', 'kr': {'ko': '15시', 'zh': '15點', 'en': "15 o'clock", 'ja': '15時', 'de': '15 Uhr'}},
    {'vi': 'mười sáu giờ', 'kr': {'ko': '16시', 'zh': '16點', 'en': "16 o'clock", 'ja': '16時', 'de': '16 Uhr'}},
    {'vi': 'mười bảy giờ', 'kr': {'ko': '17시', 'zh': '17點', 'en': "17 o'clock", 'ja': '17時', 'de': '17 Uhr'}},
    {'vi': 'mười tám giờ', 'kr': {'ko': '18시', 'zh': '18點', 'en': "18 o'clock", 'ja': '18時', 'de': '18 Uhr'}},
    {'vi': 'mười chín giờ', 'kr': {'ko': '19시', 'zh': '19點', 'en': "19 o'clock", 'ja': '19時', 'de': '19 Uhr'}},
    {'vi': 'hai mươi giờ', 'kr': {'ko': '20시', 'zh': '20點', 'en': "20 o'clock", 'ja': '20時', 'de': '20 Uhr'}},
    {'vi': 'hai mươi mốt giờ', 'kr': {'ko': '21시', 'zh': '21點', 'en': "21 o'clock", 'ja': '21時', 'de': '21 Uhr'}},
    {'vi': 'hai mươi hai giờ', 'kr': {'ko': '22시', 'zh': '22點', 'en': "22 o'clock", 'ja': '22時', 'de': '22 Uhr'}},
    {'vi': 'hai mươi ba giờ', 'kr': {'ko': '23시', 'zh': '23點', 'en': "23 o'clock", 'ja': '23時', 'de': '23 Uhr'}},
    {'vi': 'hai mươi tư giờ', 'kr': {'ko': '24시', 'zh': '24點', 'en': "24 o'clock", 'ja': '24時', 'de': '24 Uhr'},
     'alt': ['hai tư giờ', 'hai mươi bốn giờ']},
]

TIME_EXAMPLES = [
    {'vi': 'tám giờ ba mươi phút sáng',
     'kr': {'ko': '아침 8시 30분', 'zh': '早上8點30分', 'en': '8:30 in the morning', 'ja': '朝8時30分', 'de': '8:30 Uhr morgens'}},
    {'vi': 'tám giờ rưỡi sáng',
     'kr': {'ko': '아침 8시 반 (위와 같은 시각)', 'zh': '早上8點半（和上面同一個時間）',
            'en': 'Half past 8 in the morning (same time as above)', 'ja': '朝8時半（上と同じ時刻）',
            'de': 'Halb 9 morgens (gleiche Uhrzeit wie oben)'}},
    {'vi': 'năm giờ kém mười phút',
     'kr': {'ko': '5시 10분 전, 즉 4시 50분', 'zh': '差10分5點，也就是4點50分',
            'en': '10 minutes to 5, i.e., 4:50', 'ja': '5時10分前、つまり4時50分',
            'de': '10 vor 5, also 4:50 Uhr'}},
    {'vi': 'mười hai giờ trưa',
     'kr': {'ko': '낮 12시, 정오', 'zh': '中午12點，正午', 'en': '12 noon', 'ja': '昼12時、正午', 'de': '12 Uhr mittags, Mittag'}},
    {'vi': 'mười hai giờ đêm',
     'kr': {'ko': '밤 12시, 자정', 'zh': '半夜12點，午夜', 'en': '12 midnight', 'ja': '夜12時、真夜中', 'de': '12 Uhr nachts, Mitternacht'}},
    {'vi': 'bảy giờ tối',
     'kr': {'ko': '저녁 7시', 'zh': '晚上7點', 'en': '7 in the evening', 'ja': '夕方7時', 'de': '7 Uhr abends (19 Uhr)'}},
]
