# -*- coding: utf-8 -*-
TONE_PAIRS = [{'t1': 'ngang',
  't2': 'ngang',
  't1_kr': {'ko': '단평성',
            'zh': '橫聲',
            'en': 'level tone',
            'ja': '横声',
            'de': 'Ebener Ton',
            'fr': 'Ton égal',
            'pl': 'Ton równy'},
  't2_kr': {'ko': '단평성',
            'zh': '橫聲',
            'en': 'level tone',
            'ja': '横声',
            'de': 'Ebener Ton',
            'fr': 'Ton égal',
            'pl': 'Ton równy'},
  't1_mark': 'a',
  't2_mark': 'a',
  'words': [{'vi': 'xe hơi',
             'kr': {'ko': '자동차',
                    'zh': '汽車',
                    'en': 'car',
                    'ja': '自動車',
                    'de': 'Auto',
                    'fr': 'voiture',
                    'pl': 'samochód'}},
            {'vi': 'công ty',
             'kr': {'ko': '회사',
                    'zh': '公司',
                    'en': 'company',
                    'ja': '会社',
                    'de': 'Firma, Unternehmen',
                    'fr': 'entreprise, société',
                    'pl': 'firma, przedsiębiorstwo'}},
            {'vi': 'sinh viên',
             'kr': {'ko': '대학생',
                    'zh': '大學生',
                    'en': 'college student',
                    'ja': '大学生',
                    'de': 'Student',
                    'fr': 'étudiant',
                    'pl': 'student'}},
            {'vi': 'anh trai',
             'kr': {'ko': '형·오빠',
                    'zh': '哥哥',
                    'en': 'older brother',
                    'ja': '兄',
                    'de': 'älterer Bruder',
                    'fr': 'frère aîné',
                    'pl': 'starszy brat'}}]},
 {'t1': 'ngang',
  't2': 'sac',
  't1_kr': {'ko': '단평성',
            'zh': '橫聲',
            'en': 'level tone',
            'ja': '横声',
            'de': 'Ebener Ton',
            'fr': 'Ton égal',
            'pl': 'Ton równy'},
  't2_kr': {'ko': '상성',
            'zh': '銳聲',
            'en': 'rising tone',
            'ja': '鋭声',
            'de': 'Steigender Ton',
            'fr': 'Ton montant',
            'pl': 'Ton wznoszący'},
  't1_mark': 'a',
  't2_mark': 'á',
  'words': [{'vi': 'xe máy',
             'kr': {'ko': '오토바이',
                    'zh': '摩托車',
                    'en': 'motorbike',
                    'ja': 'バイク',
                    'de': 'Motorrad, Moped',
                    'fr': 'moto, scooter',
                    'pl': 'motocykl, skuter'}},
            {'vi': 'con cá',
             'kr': {'ko': '물고기', 'zh': '魚', 'en': 'fish', 'ja': '魚', 'de': 'Fisch', 'fr': 'poisson', 'pl': 'ryba'}},
            {'vi': 'ăn sáng',
             'kr': {'ko': '아침 먹다',
                    'zh': '吃早餐',
                    'en': 'to eat breakfast',
                    'ja': '朝ご飯を食べる',
                    'de': 'frühstücken',
                    'fr': 'prendre le petit-déjeuner',
                    'pl': 'jeść śniadanie'}},
            {'vi': 'tin tức',
             'kr': {'ko': '뉴스',
                    'zh': '新聞',
                    'en': 'news',
                    'ja': 'ニュース',
                    'de': 'Nachrichten',
                    'fr': 'nouvelles, informations',
                    'pl': 'wiadomości'}}]},
 {'t1': 'ngang',
  't2': 'huyen',
  't1_kr': {'ko': '단평성',
            'zh': '橫聲',
            'en': 'level tone',
            'ja': '横声',
            'de': 'Ebener Ton',
            'fr': 'Ton égal',
            'pl': 'Ton równy'},
  't2_kr': {'ko': '장평성',
            'zh': '玄聲',
            'en': 'falling tone',
            'ja': '玄声',
            'de': 'Fallender Ton',
            'fr': 'Ton descendant',
            'pl': 'Ton opadający'},
  't1_mark': 'a',
  't2_mark': 'à',
  'words': [{'vi': 'con gà',
             'kr': {'ko': '닭',
                    'zh': '雞',
                    'en': 'chicken',
                    'ja': '鶏',
                    'de': 'Huhn',
                    'fr': 'poulet, poule',
                    'pl': 'kurczak, kura'}},
            {'vi': 'ăn mày',
             'kr': {'ko': '구걸하다',
                    'zh': '乞丐',
                    'en': 'beggar',
                    'ja': '乞食',
                    'de': 'betteln, Bettler',
                    'fr': 'mendiant, mendier',
                    'pl': 'żebrak, żebrać'}},
            {'vi': 'đi về',
             'kr': {'ko': '돌아가다',
                    'zh': '回去',
                    'en': 'to go back / return',
                    'ja': '帰る',
                    'de': 'zurückgehen, nach Hause gehen',
                    'fr': 'rentrer, retourner',
                    'pl': 'wracać'}},
            {'vi': 'chân thành',
             'kr': {'ko': '진심의',
                    'zh': '真心的',
                    'en': 'sincere',
                    'ja': '真心の',
                    'de': 'aufrichtig, herzlich',
                    'fr': 'sincère',
                    'pl': 'szczery, serdeczny'}}]},
 {'t1': 'ngang',
  't2': 'hoi',
  't1_kr': {'ko': '단평성',
            'zh': '橫聲',
            'en': 'level tone',
            'ja': '横声',
            'de': 'Ebener Ton',
            'fr': 'Ton égal',
            'pl': 'Ton równy'},
  't2_kr': {'ko': '회성',
            'zh': '問聲',
            'en': 'dipping tone',
            'ja': '問声',
            'de': 'Frageton (fallend-steigend)',
            'fr': 'Ton descendant-montant',
            'pl': 'Ton pytający'},
  't1_mark': 'a',
  't2_mark': 'ả',
  'words': [{'vi': 'vui vẻ',
             'kr': {'ko': '즐거운',
                    'zh': '愉快的',
                    'en': 'joyful',
                    'ja': '楽しい',
                    'de': 'fröhlich, heiter',
                    'fr': 'joyeux, gai',
                    'pl': 'wesoły, radosny'}},
            {'vi': 'con thỏ',
             'kr': {'ko': '토끼',
                    'zh': '兔子',
                    'en': 'rabbit',
                    'ja': 'うさぎ',
                    'de': 'Hase, Kaninchen',
                    'fr': 'lapin',
                    'pl': 'królik'}},
            {'vi': 'cây cỏ',
             'kr': {'ko': '나무와 풀, 삼림',
                    'zh': '草',
                    'en': 'grass',
                    'ja': '草',
                    'de': 'Gras, Pflanzen',
                    'fr': 'herbe, végétation',
                    'pl': 'trawa, roślinność'}},
            {'vi': 'ăn ở',
             'kr': {'ko': '거주하다',
                    'zh': '居住',
                    'en': 'to reside; to live',
                    'ja': '居住する',
                    'de': 'wohnen, leben',
                    'fr': 'résider, habiter',
                    'pl': 'mieszkać, żyć'}}]},
 {'t1': 'ngang',
  't2': 'nga',
  't1_kr': {'ko': '단평성',
            'zh': '橫聲',
            'en': 'level tone',
            'ja': '横声',
            'de': 'Ebener Ton',
            'fr': 'Ton égal',
            'pl': 'Ton równy'},
  't2_kr': {'ko': '거성',
            'zh': '跌聲',
            'en': 'creaky-rising tone',
            'ja': '跌声',
            'de': 'Unterbrochen steigender Ton',
            'fr': 'Ton montant interrompu',
            'pl': 'Ton łamany'},
  't1_mark': 'a',
  't2_mark': 'ã',
  'words': [{'vi': 'ngôn ngữ',
             'kr': {'ko': '언어',
                    'zh': '語言',
                    'en': 'language',
                    'ja': '言語',
                    'de': 'Sprache',
                    'fr': 'langue, langage',
                    'pl': 'język, mowa'}},
            {'vi': 'con muỗi',
             'kr': {'ko': '모기',
                    'zh': '蚊子',
                    'en': 'mosquito',
                    'ja': '蚊',
                    'de': 'Mücke',
                    'fr': 'moustique',
                    'pl': 'komar'}},
            {'vi': 'đôi đũa',
             'kr': {'ko': '젓가락 한 쌍',
                    'zh': '一雙筷子',
                    'en': 'a pair of chopsticks',
                    'ja': '箸一膳',
                    'de': 'ein Paar Essstäbchen',
                    'fr': 'une paire de baguettes',
                    'pl': 'para pałeczek'}},
            {'vi': 'thêm nữa',
             'kr': {'ko': '더',
                    'zh': '更',
                    'en': 'more',
                    'ja': 'もっと',
                    'de': 'noch mehr, weiter',
                    'fr': 'encore plus, davantage',
                    'pl': 'jeszcze więcej'}}]},
 {'t1': 'ngang',
  't2': 'nang',
  't1_kr': {'ko': '단평성',
            'zh': '橫聲',
            'en': 'level tone',
            'ja': '横声',
            'de': 'Ebener Ton',
            'fr': 'Ton égal',
            'pl': 'Ton równy'},
  't2_kr': {'ko': '하성',
            'zh': '重聲',
            'en': 'heavy tone',
            'ja': '重声',
            'de': 'Schwerer fallender Ton',
            'fr': 'Ton lourd',
            'pl': 'Ton ciężki'},
  't1_mark': 'a',
  't2_mark': 'ạ',
  'words': [{'vi': 'sinh nhật',
             'kr': {'ko': '생일',
                    'zh': '生日',
                    'en': 'birthday',
                    'ja': '誕生日',
                    'de': 'Geburtstag',
                    'fr': 'anniversaire',
                    'pl': 'urodziny'}},
            {'vi': 'con vịt',
             'kr': {'ko': '오리', 'zh': '鴨子', 'en': 'duck', 'ja': 'アヒル', 'de': 'Ente', 'fr': 'canard', 'pl': 'kaczka'}},
            {'vi': 'hôm nọ',
             'kr': {'ko': '그저께',
                    'zh': '前天',
                    'en': 'the day before yesterday',
                    'ja': '一昨日',
                    'de': 'vorgestern / neulich',
                    'fr': "avant-hier, l'autre jour",
                    'pl': 'przedwczoraj, niedawno'}},
            {'vi': 'thanh lịch',
             'kr': {'ko': '우아한',
                    'zh': '優雅的',
                    'en': 'elegant',
                    'ja': '優雅な',
                    'de': 'elegant',
                    'fr': 'élégant',
                    'pl': 'elegancki'}}]},
 {'t1': 'sac',
  't2': 'ngang',
  't1_kr': {'ko': '상성',
            'zh': '銳聲',
            'en': 'rising tone',
            'ja': '鋭声',
            'de': 'Steigender Ton',
            'fr': 'Ton montant',
            'pl': 'Ton wznoszący'},
  't2_kr': {'ko': '단평성',
            'zh': '橫聲',
            'en': 'level tone',
            'ja': '横声',
            'de': 'Ebener Ton',
            'fr': 'Ton égal',
            'pl': 'Ton równy'},
  't1_mark': 'á',
  't2_mark': 'a',
  'words': [{'vi': 'cá nhân',
             'kr': {'ko': '개인',
                    'zh': '個人',
                    'en': 'individual',
                    'ja': '個人',
                    'de': 'Individuum, persönlich',
                    'fr': 'individu, personnel',
                    'pl': 'indywidualny, osobisty'}},
            {'vi': 'sáng nay',
             'kr': {'ko': '오늘 아침',
                    'zh': '今天早上',
                    'en': 'this morning',
                    'ja': '今朝',
                    'de': 'heute Morgen',
                    'fr': 'ce matin',
                    'pl': 'dzisiaj rano'}},
            {'vi': 'quán ăn',
             'kr': {'ko': '식당',
                    'zh': '餐廳',
                    'en': 'restaurant',
                    'ja': 'レストラン',
                    'de': 'Restaurant, Lokal',
                    'fr': 'restaurant, cantine',
                    'pl': 'restauracja, jadłodajnia'}},
            {'vi': 'chú tôi',
             'kr': {'ko': '내 삼촌',
                    'zh': '我的叔叔(舅舅)',
                    'en': 'my uncle',
                    'ja': '私のおじ',
                    'de': 'mein Onkel',
                    'fr': 'mon oncle',
                    'pl': 'mój wujek'}}]},
 {'t1': 'sac',
  't2': 'sac',
  't1_kr': {'ko': '상성',
            'zh': '銳聲',
            'en': 'rising tone',
            'ja': '鋭声',
            'de': 'Steigender Ton',
            'fr': 'Ton montant',
            'pl': 'Ton wznoszący'},
  't2_kr': {'ko': '상성',
            'zh': '銳聲',
            'en': 'rising tone',
            'ja': '鋭声',
            'de': 'Steigender Ton',
            'fr': 'Ton montant',
            'pl': 'Ton wznoszący'},
  't1_mark': 'á',
  't2_mark': 'á',
  'words': [{'vi': 'cấp cứu',
             'kr': {'ko': '응급',
                    'zh': '緊急',
                    'en': 'emergency',
                    'ja': '応急、緊急',
                    'de': 'Notfall, Erste Hilfe',
                    'fr': 'urgence, premiers secours',
                    'pl': 'pogotowie, pierwsza pomoc'}},
            {'vi': 'chính xác',
             'kr': {'ko': '정확한',
                    'zh': '準確的',
                    'en': 'accurate',
                    'ja': '正確な',
                    'de': 'genau, präzise',
                    'fr': 'exact, précis',
                    'pl': 'dokładny, precyzyjny'}},
            {'vi': 'cố gắng',
             'kr': {'ko': '노력하다',
                    'zh': '努力',
                    'en': 'to make an effort',
                    'ja': '努力する',
                    'de': 'sich anstrengen, versuchen',
                    'fr': 'faire des efforts, essayer',
                    'pl': 'starać się, podejmować wysiłek'}},
            {'vi': 'phấn khích',
             'kr': {'ko': '흥분하다',
                    'zh': '興奮',
                    'en': 'to be excited',
                    'ja': '興奮する',
                    'de': 'aufgeregt, begeistert',
                    'fr': 'excité, enthousiaste',
                    'pl': 'podekscytowany'}}]},
 {'t1': 'sac',
  't2': 'huyen',
  't1_kr': {'ko': '상성',
            'zh': '銳聲',
            'en': 'rising tone',
            'ja': '鋭声',
            'de': 'Steigender Ton',
            'fr': 'Ton montant',
            'pl': 'Ton wznoszący'},
  't2_kr': {'ko': '장평성',
            'zh': '玄聲',
            'en': 'falling tone',
            'ja': '玄声',
            'de': 'Fallender Ton',
            'fr': 'Ton descendant',
            'pl': 'Ton opadający'},
  't1_mark': 'á',
  't2_mark': 'à',
  'words': [{'vi': 'khách hàng',
             'kr': {'ko': '고객',
                    'zh': '顧客',
                    'en': 'customer',
                    'ja': '顧客',
                    'de': 'Kunde',
                    'fr': 'client',
                    'pl': 'klient'}},
            {'vi': 'bánh mì',
             'kr': {'ko': '빵',
                    'zh': '麵包',
                    'en': 'bread',
                    'ja': 'パン',
                    'de': 'Brot',
                    'fr': 'pain',
                    'pl': 'chleb, pieczywo'}},
            {'vi': 'chính là',
             'kr': {'ko': '바로 ~이다',
                    'zh': '正是~',
                    'en': 'to be exactly ~',
                    'ja': 'まさに～だ',
                    'de': 'genau das ist ...',
                    'fr': "c'est exactement ...",
                    'pl': 'jest dokładnie...'}},
            {'vi': 'vé tàu',
             'kr': {'ko': '기차표',
                    'zh': '火車票',
                    'en': 'train ticket',
                    'ja': '列車の切符',
                    'de': 'Fahrkarte, Zugticket',
                    'fr': 'billet de train',
                    'pl': 'bilet kolejowy'}}]},
 {'t1': 'sac',
  't2': 'hoi',
  't1_kr': {'ko': '상성',
            'zh': '銳聲',
            'en': 'rising tone',
            'ja': '鋭声',
            'de': 'Steigender Ton',
            'fr': 'Ton montant',
            'pl': 'Ton wznoszący'},
  't2_kr': {'ko': '회성',
            'zh': '問聲',
            'en': 'dipping tone',
            'ja': '問声',
            'de': 'Frageton (fallend-steigend)',
            'fr': 'Ton descendant-montant',
            'pl': 'Ton pytający'},
  't1_mark': 'á',
  't2_mark': 'ả',
  'words': [{'vi': 'chính phủ',
             'kr': {'ko': '정부',
                    'zh': '政府',
                    'en': 'government',
                    'ja': '政府',
                    'de': 'Regierung',
                    'fr': 'gouvernement',
                    'pl': 'rząd'}},
            {'vi': 'kết quả',
             'kr': {'ko': '결과',
                    'zh': '結果',
                    'en': 'result',
                    'ja': '結果',
                    'de': 'Ergebnis, Resultat',
                    'fr': 'résultat',
                    'pl': 'wynik, rezultat'}},
            {'vi': 'khá giả',
             'kr': {'ko': '부유한',
                    'zh': '富有的',
                    'en': 'wealthy',
                    'ja': '裕福な',
                    'de': 'wohlhabend',
                    'fr': 'aisé, aisé financièrement',
                    'pl': 'zamożny'}},
            {'vi': 'mắc thử',
             'kr': {'ko': '입어보다',
                    'zh': '試穿',
                    'en': 'to try on (clothes)',
                    'ja': '試着する',
                    'de': 'anprobieren',
                    'fr': 'essayer (un vêtement)',
                    'pl': 'przymierzać (ubranie)'}}]},
 {'t1': 'sac',
  't2': 'nga',
  't1_kr': {'ko': '상성',
            'zh': '銳聲',
            'en': 'rising tone',
            'ja': '鋭声',
            'de': 'Steigender Ton',
            'fr': 'Ton montant',
            'pl': 'Ton wznoszący'},
  't2_kr': {'ko': '거성',
            'zh': '跌聲',
            'en': 'creaky-rising tone',
            'ja': '跌声',
            'de': 'Unterbrochen steigender Ton',
            'fr': 'Ton montant interrompu',
            'pl': 'Ton łamany'},
  't1_mark': 'á',
  't2_mark': 'ã',
  'words': [{'vi': 'bác sĩ',
             'kr': {'ko': '의사',
                    'zh': '醫生',
                    'en': 'doctor',
                    'ja': '医者',
                    'de': 'Arzt',
                    'fr': 'médecin, docteur',
                    'pl': 'lekarz'}},
            {'vi': 'chính giữa',
             'kr': {'ko': '한가운데',
                    'zh': '正中間',
                    'en': 'the very middle',
                    'ja': '真ん中',
                    'de': 'mitten drin, genau in der Mitte',
                    'fr': 'au beau milieu, en plein centre',
                    'pl': 'dokładnie pośrodku'}},
            {'vi': 'chính nghĩa',
             'kr': {'ko': '정의',
                    'zh': '正義',
                    'en': 'justice',
                    'ja': '正義',
                    'de': 'Gerechtigkeit',
                    'fr': 'justice',
                    'pl': 'sprawiedliwość, prawość'}},
            {'vi': 'khá dễ',
             'kr': {'ko': '꽤 쉬운',
                    'zh': '相當容易的',
                    'en': 'quite easy',
                    'ja': 'かなり簡単な',
                    'de': 'ziemlich einfach',
                    'fr': 'assez facile',
                    'pl': 'dość łatwy'}}]},
 {'t1': 'sac',
  't2': 'nang',
  't1_kr': {'ko': '상성',
            'zh': '銳聲',
            'en': 'rising tone',
            'ja': '鋭声',
            'de': 'Steigender Ton',
            'fr': 'Ton montant',
            'pl': 'Ton wznoszący'},
  't2_kr': {'ko': '하성',
            'zh': '重聲',
            'en': 'heavy tone',
            'ja': '重声',
            'de': 'Schwerer fallender Ton',
            'fr': 'Ton lourd',
            'pl': 'Ton ciężki'},
  't1_mark': 'á',
  't2_mark': 'ạ',
  'words': [{'vi': 'quyết định',
             'kr': {'ko': '결정하다',
                    'zh': '決定',
                    'en': 'to decide',
                    'ja': '決定する',
                    'de': 'entscheiden',
                    'fr': 'décider',
                    'pl': 'decydować'}},
            {'vi': 'kết hợp',
             'kr': {'ko': '결합하다',
                    'zh': '結合',
                    'en': 'to combine',
                    'ja': '結合する',
                    'de': 'verbinden, kombinieren',
                    'fr': 'associer, combiner',
                    'pl': 'łączyć, kojarzyć'}},
            {'vi': 'chính trị',
             'kr': {'ko': '정치',
                    'zh': '政治',
                    'en': 'politics',
                    'ja': '政治',
                    'de': 'Politik',
                    'fr': 'politique',
                    'pl': 'polityka'}},
            {'vi': 'cấp độ',
             'kr': {'ko': '정도',
                    'zh': '程度',
                    'en': 'degree',
                    'ja': '程度',
                    'de': 'Stufe, Grad',
                    'fr': 'niveau, degré',
                    'pl': 'stopień, poziom'}}]},
 {'t1': 'huyen',
  't2': 'ngang',
  't1_kr': {'ko': '장평성',
            'zh': '玄聲',
            'en': 'falling tone',
            'ja': '玄声',
            'de': 'Fallender Ton',
            'fr': 'Ton descendant',
            'pl': 'Ton opadający'},
  't2_kr': {'ko': '단평성',
            'zh': '橫聲',
            'en': 'level tone',
            'ja': '横声',
            'de': 'Ebener Ton',
            'fr': 'Ton égal',
            'pl': 'Ton równy'},
  't1_mark': 'à',
  't2_mark': 'a',
  'words': [{'vi': 'cà phê',
             'kr': {'ko': '커피', 'zh': '咖啡', 'en': 'coffee', 'ja': 'コーヒー', 'de': 'Kaffee', 'fr': 'café', 'pl': 'kawa'}},
            {'vi': 'bà con',
             'kr': {'ko': '친척',
                    'zh': '親戚',
                    'en': 'relative',
                    'ja': '親戚',
                    'de': 'Verwandte',
                    'fr': 'parents, proches',
                    'pl': 'krewni'}},
            {'vi': 'nhà ga',
             'kr': {'ko': '기차역',
                    'zh': '火車站',
                    'en': 'train station',
                    'ja': '(列車の)駅',
                    'de': 'Bahnhof',
                    'fr': 'gare',
                    'pl': 'stacja kolejowa'}},
            {'vi': 'trà xanh',
             'kr': {'ko': '녹차',
                    'zh': '綠茶',
                    'en': 'green tea',
                    'ja': '緑茶',
                    'de': 'Grüntee',
                    'fr': 'thé vert',
                    'pl': 'zielona herbata'}}]},
 {'t1': 'huyen',
  't2': 'sac',
  't1_kr': {'ko': '장평성',
            'zh': '玄聲',
            'en': 'falling tone',
            'ja': '玄声',
            'de': 'Fallender Ton',
            'fr': 'Ton descendant',
            'pl': 'Ton opadający'},
  't2_kr': {'ko': '상성',
            'zh': '銳聲',
            'en': 'rising tone',
            'ja': '鋭声',
            'de': 'Steigender Ton',
            'fr': 'Ton montant',
            'pl': 'Ton wznoszący'},
  't1_mark': 'à',
  't2_mark': 'á',
  'words': [{'vi': 'nhà máy',
             'kr': {'ko': '공장',
                    'zh': '工廠',
                    'en': 'factory',
                    'ja': '工場',
                    'de': 'Fabrik',
                    'fr': 'usine',
                    'pl': 'fabryka'}},
            {'vi': 'về nước',
             'kr': {'ko': '귀국하다',
                    'zh': '回國',
                    'en': "to return to one's home country",
                    'ja': '帰国する',
                    'de': 'ins Heimatland zurückkehren',
                    'fr': 'rentrer dans son pays',
                    'pl': 'wracać do ojczyzny'}},
            {'vi': 'bàn ghế',
             'kr': {'ko': '가구',
                    'zh': '傢俱',
                    'en': 'furniture',
                    'ja': '家具',
                    'de': 'Möbel (Tische und Stühle)',
                    'fr': 'meubles (tables et chaises)',
                    'pl': 'meble (stół i krzesła)'}},
            {'vi': 'màu sắc',
             'kr': {'ko': '색깔', 'zh': '顏色', 'en': 'color', 'ja': '色', 'de': 'Farbe', 'fr': 'couleur', 'pl': 'kolor'}}]},
 {'t1': 'huyen',
  't2': 'huyen',
  't1_kr': {'ko': '장평성',
            'zh': '玄聲',
            'en': 'falling tone',
            'ja': '玄声',
            'de': 'Fallender Ton',
            'fr': 'Ton descendant',
            'pl': 'Ton opadający'},
  't2_kr': {'ko': '장평성',
            'zh': '玄聲',
            'en': 'falling tone',
            'ja': '玄声',
            'de': 'Fallender Ton',
            'fr': 'Ton descendant',
            'pl': 'Ton opadający'},
  't1_mark': 'à',
  't2_mark': 'à',
  'words': [{'vi': 'chào mừng',
             'kr': {'ko': '환영하다',
                    'zh': '歡迎',
                    'en': 'to welcome',
                    'ja': '歓迎する',
                    'de': 'willkommen heißen',
                    'fr': 'souhaiter la bienvenue',
                    'pl': 'witać, powitanie'}},
            {'vi': 'bà già',
             'kr': {'ko': '노파',
                    'zh': '奶奶',
                    'en': 'grandmother',
                    'ja': '祖母',
                    'de': 'alte Frau, Großmutter',
                    'fr': 'vieille femme, grand-mère',
                    'pl': 'starsza pani, babcia'}},
            {'vi': 'tình cờ',
             'kr': {'ko': '우연히',
                    'zh': '偶然',
                    'en': 'by chance',
                    'ja': '偶然に',
                    'de': 'zufällig',
                    'fr': 'par hasard',
                    'pl': 'przypadkowo'}},
            {'vi': 'nhà nghèo',
             'kr': {'ko': '가난한 집',
                    'zh': '貧窮的家',
                    'en': 'a poor household',
                    'ja': '貧しい家',
                    'de': 'arme Familie, armer Haushalt',
                    'fr': 'famille pauvre, foyer modeste',
                    'pl': 'uboga rodzina'}}]},
 {'t1': 'huyen',
  't2': 'hoi',
  't1_kr': {'ko': '장평성',
            'zh': '玄聲',
            'en': 'falling tone',
            'ja': '玄声',
            'de': 'Fallender Ton',
            'fr': 'Ton descendant',
            'pl': 'Ton opadający'},
  't2_kr': {'ko': '회성',
            'zh': '問聲',
            'en': 'dipping tone',
            'ja': '問声',
            'de': 'Frageton (fallend-steigend)',
            'fr': 'Ton descendant-montant',
            'pl': 'Ton pytający'},
  't1_mark': 'à',
  't2_mark': 'ả',
  'words': [{'vi': 'chào hỏi',
             'kr': {'ko': '인사하다',
                    'zh': '打招呼',
                    'en': 'to greet',
                    'ja': '挨拶する',
                    'de': 'grüßen, begrüßen',
                    'fr': 'saluer',
                    'pl': 'witać się, pozdrawiać'}},
            {'vi': 'tìm hiểu',
             'kr': {'ko': '알아보다',
                    'zh': '打聽、查詢',
                    'en': 'to find out',
                    'ja': '調べる',
                    'de': 'sich informieren, herausfinden',
                    'fr': 'se renseigner, découvrir',
                    'pl': 'dowiadywać się, badać'}},
            {'vi': 'nhà cửa',
             'kr': {'ko': '집',
                    'zh': '家',
                    'en': 'house',
                    'ja': '家',
                    'de': 'Haus, Wohnung',
                    'fr': 'maison, logement',
                    'pl': 'dom, mieszkanie'}},
            {'vi': 'già cả',
             'kr': {'ko': '늙은',
                    'zh': '老的',
                    'en': 'old',
                    'ja': '老いた',
                    'de': 'alt, bejahrt',
                    'fr': 'âgé, vieux',
                    'pl': 'stary, podeszły w wieku'}}]},
 {'t1': 'huyen',
  't2': 'nga',
  't1_kr': {'ko': '장평성',
            'zh': '玄聲',
            'en': 'falling tone',
            'ja': '玄声',
            'de': 'Fallender Ton',
            'fr': 'Ton descendant',
            'pl': 'Ton opadający'},
  't2_kr': {'ko': '거성',
            'zh': '跌聲',
            'en': 'creaky-rising tone',
            'ja': '跌声',
            'de': 'Unterbrochen steigender Ton',
            'fr': 'Ton montant interrompu',
            'pl': 'Ton łamany'},
  't1_mark': 'à',
  't2_mark': 'ã',
  'words': [{'vi': 'buồn bã',
             'kr': {'ko': '슬픈',
                    'zh': '悲傷的',
                    'en': 'sad',
                    'ja': '悲しい',
                    'de': 'traurig',
                    'fr': 'triste',
                    'pl': 'smutny'}},
            {'vi': 'nhàn rỗi',
             'kr': {'ko': '한가한',
                    'zh': '空閒的',
                    'en': 'free/leisurely',
                    'ja': '暇な',
                    'de': 'Muße haben, untätig',
                    'fr': 'oisif, avoir du temps libre',
                    'pl': 'bezczynny, mający czas wolny'}},
            {'vi': 'tình nghĩa',
             'kr': {'ko': '정·의리',
                    'zh': '情誼·義氣',
                    'en': 'affection · loyalty',
                    'ja': '情·義理',
                    'de': 'Zuneigung und Loyalität',
                    'fr': 'affection et loyauté',
                    'pl': 'przywiązanie i lojalność'}},
            {'vi': 'còn nữa',
             'kr': {'ko': '더 있다',
                    'zh': '再多待一會兒',
                    'en': 'to stay longer',
                    'ja': 'もっといる（滞在する）',
                    'de': 'noch mehr / noch da sein',
                    'fr': 'rester encore, être encore là',
                    'pl': 'zostać dłużej, jeszcze jest'}}]},
 {'t1': 'huyen',
  't2': 'nang',
  't1_kr': {'ko': '장평성',
            'zh': '玄聲',
            'en': 'falling tone',
            'ja': '玄声',
            'de': 'Fallender Ton',
            'fr': 'Ton descendant',
            'pl': 'Ton opadający'},
  't2_kr': {'ko': '하성',
            'zh': '重聲',
            'en': 'heavy tone',
            'ja': '重声',
            'de': 'Schwerer fallender Ton',
            'fr': 'Ton lourd',
            'pl': 'Ton ciężki'},
  't1_mark': 'à',
  't2_mark': 'ạ',
  'words': [{'vi': 'bà ngoại',
             'kr': {'ko': '외할머니',
                    'zh': '外婆',
                    'en': 'maternal grandmother',
                    'ja': '母方の祖母',
                    'de': 'Großmutter mütterlicherseits',
                    'fr': 'grand-mère maternelle',
                    'pl': 'babcia macierzysta'}},
            {'vi': 'làm việc',
             'kr': {'ko': '일하다',
                    'zh': '工作',
                    'en': 'to work',
                    'ja': '働く',
                    'de': 'arbeiten',
                    'fr': 'travailler',
                    'pl': 'pracować'}},
            {'vi': 'chờ đợi',
             'kr': {'ko': '기다리다',
                    'zh': '等待',
                    'en': 'to wait',
                    'ja': '待つ',
                    'de': 'warten',
                    'fr': 'attendre',
                    'pl': 'czekać'}},
            {'vi': 'già dặn',
             'kr': {'ko': '노련한',
                    'zh': '老練的',
                    'en': 'experienced / skilled',
                    'ja': '老練な',
                    'de': 'erfahren, reif',
                    'fr': 'expérimenté, mûr',
                    'pl': 'doświadczony, dojrzały'}}]},
 {'t1': 'hoi',
  't2': 'ngang',
  't1_kr': {'ko': '회성',
            'zh': '問聲',
            'en': 'dipping tone',
            'ja': '問声',
            'de': 'Frageton (fallend-steigend)',
            'fr': 'Ton descendant-montant',
            'pl': 'Ton pytający'},
  't2_kr': {'ko': '단평성',
            'zh': '橫聲',
            'en': 'level tone',
            'ja': '横声',
            'de': 'Ebener Ton',
            'fr': 'Ton égal',
            'pl': 'Ton równy'},
  't1_mark': 'ả',
  't2_mark': 'a',
  'words': [{'vi': 'của tôi',
             'kr': {'ko': '나의',
                    'zh': '我的',
                    'en': 'my',
                    'ja': '私の',
                    'de': 'mein, meine',
                    'fr': 'mon, ma, le mien',
                    'pl': 'mój, moja, moje'}},
            {'vi': 'hỏi thăm',
             'kr': {'ko': '안부 묻다',
                    'zh': '問候',
                    'en': 'to send regards',
                    'ja': '安否を尋ねる',
                    'de': 'sich erkundigen, Grüße ausrichten',
                    'fr': 'demander des nouvelles',
                    'pl': 'dowiadywać się o zdrowie, pozdrawiać'}},
            {'vi': 'kể tên',
             'kr': {'ko': '이름을 말하다',
                    'zh': '說出名字',
                    'en': "to say (one's) name",
                    'ja': '名前を言う',
                    'de': 'Namen nennen',
                    'fr': 'énumérer des noms',
                    'pl': 'wymieniać nazwiska'}},
            {'vi': 'nhỏ con',
             'kr': {'ko': '체구가 작은',
                    'zh': '體格矮小的',
                    'en': 'small in stature',
                    'ja': '体が小さい',
                    'de': 'von kleiner Statur',
                    'fr': 'de petite taille',
                    'pl': 'drobnej postury'}}]},
 {'t1': 'hoi',
  't2': 'sac',
  't1_kr': {'ko': '회성',
            'zh': '問聲',
            'en': 'dipping tone',
            'ja': '問声',
            'de': 'Frageton (fallend-steigend)',
            'fr': 'Ton descendant-montant',
            'pl': 'Ton pytający'},
  't2_kr': {'ko': '상성',
            'zh': '銳聲',
            'en': 'rising tone',
            'ja': '鋭声',
            'de': 'Steigender Ton',
            'fr': 'Ton montant',
            'pl': 'Ton wznoszący'},
  't1_mark': 'ả',
  't2_mark': 'á',
  'words': [{'vi': 'cả nước',
             'kr': {'ko': '전국',
                    'zh': '全國',
                    'en': 'the whole country',
                    'ja': '全国',
                    'de': 'das ganze Land, landesweit',
                    'fr': 'tout le pays, national',
                    'pl': 'cały kraj, ogólnokrajowy'}},
            {'vi': 'quả táo',
             'kr': {'ko': '사과', 'zh': '蘋果', 'en': 'apple', 'ja': 'りんご', 'de': 'Apfel', 'fr': 'pomme', 'pl': 'jabłko'}},
            {'vi': 'chỉ số',
             'kr': {'ko': '지수(指數)',
                    'zh': '指數',
                    'en': 'index',
                    'ja': '指数',
                    'de': 'Index, Kennzahl',
                    'fr': 'indice, indicateur',
                    'pl': 'wskaźnik, indeks'}},
            {'vi': 'chỉ có',
             'kr': {'ko': '오직',
                    'zh': '只',
                    'en': 'only',
                    'ja': 'ただ',
                    'de': 'nur, einzig',
                    'fr': 'seulement, uniquement',
                    'pl': 'tylko, wyłącznie'}}]},
 {'t1': 'hoi',
  't2': 'huyen',
  't1_kr': {'ko': '회성',
            'zh': '問聲',
            'en': 'dipping tone',
            'ja': '問声',
            'de': 'Frageton (fallend-steigend)',
            'fr': 'Ton descendant-montant',
            'pl': 'Ton pytający'},
  't2_kr': {'ko': '장평성',
            'zh': '玄聲',
            'en': 'falling tone',
            'ja': '玄声',
            'de': 'Fallender Ton',
            'fr': 'Ton descendant',
            'pl': 'Ton opadający'},
  't1_mark': 'ả',
  't2_mark': 'à',
  'words': [{'vi': 'cả nhà',
             'kr': {'ko': '온 가족',
                    'zh': '全家人',
                    'en': 'the whole family',
                    'ja': '家族全員',
                    'de': 'die ganze Familie',
                    'fr': 'toute la famille',
                    'pl': 'cała rodzina'}},
            {'vi': 'chỉ là',
             'kr': {'ko': '단지 ~이다',
                    'zh': '只是~',
                    'en': 'to be just ~ / only ~',
                    'ja': 'ただ〜だ',
                    'de': 'nur ... sein',
                    'fr': "n'être que ...",
                    'pl': 'być tylko...'}},
            {'vi': 'hiểu lầm',
             'kr': {'ko': '오해하다',
                    'zh': '誤會',
                    'en': 'to misunderstand',
                    'ja': '誤解する',
                    'de': 'missverstehen',
                    'fr': 'malentendu, mal comprendre',
                    'pl': 'nieporozumienie, źle zrozumieć'}},
            {'vi': 'để dành',
             'kr': {'ko': '아껴두다',
                    'zh': '留著、節省下來',
                    'en': 'to save (for later)',
                    'ja': '取っておく',
                    'de': 'aufsparen, zurücklegen',
                    'fr': 'mettre de côté, économiser',
                    'pl': 'odkładać, oszczędzać'}}]},
 {'t1': 'hoi',
  't2': 'hoi',
  't1_kr': {'ko': '회성',
            'zh': '問聲',
            'en': 'dipping tone',
            'ja': '問声',
            'de': 'Frageton (fallend-steigend)',
            'fr': 'Ton descendant-montant',
            'pl': 'Ton pytający'},
  't2_kr': {'ko': '회성',
            'zh': '問聲',
            'en': 'dipping tone',
            'ja': '問声',
            'de': 'Frageton (fallend-steigend)',
            'fr': 'Ton descendant-montant',
            'pl': 'Ton pytający'},
  't1_mark': 'ả',
  't2_mark': 'ả',
  'words': [{'vi': 'thỉnh thoảng',
             'kr': {'ko': '가끔',
                    'zh': '偶爾',
                    'en': 'sometimes',
                    'ja': 'たまに',
                    'de': 'manchmal, ab und zu',
                    'fr': 'parfois, de temps en temps',
                    'pl': 'czasami, od czasu do czasu'}},
            {'vi': 'ảnh hưởng',
             'kr': {'ko': '영향을 미치다',
                    'zh': '影響',
                    'en': 'to influence, to affect',
                    'ja': '影響を及ぼす',
                    'de': 'beeinflussen, Auswirkung',
                    'fr': 'influencer, influence',
                    'pl': 'wpływać, wpływ'}},
            {'vi': 'bảo hiểm',
             'kr': {'ko': '보험',
                    'zh': '保險',
                    'en': 'insurance',
                    'ja': '保険',
                    'de': 'Versicherung',
                    'fr': 'assurance',
                    'pl': 'ubezpieczenie'}},
            {'vi': 'tổng thể',
             'kr': {'ko': '전체',
                    'zh': '全體',
                    'en': 'whole/entirety',
                    'ja': '全体',
                    'de': 'Gesamtheit',
                    'fr': 'ensemble, globalité',
                    'pl': 'całość, ogół'}}]},
 {'t1': 'hoi',
  't2': 'nga',
  't1_kr': {'ko': '회성',
            'zh': '問聲',
            'en': 'dipping tone',
            'ja': '問声',
            'de': 'Frageton (fallend-steigend)',
            'fr': 'Ton descendant-montant',
            'pl': 'Ton pytający'},
  't2_kr': {'ko': '거성',
            'zh': '跌聲',
            'en': 'creaky-rising tone',
            'ja': '跌声',
            'de': 'Unterbrochen steigender Ton',
            'fr': 'Ton montant interrompu',
            'pl': 'Ton łamany'},
  't1_mark': 'ả',
  't2_mark': 'ã',
  'words': [{'vi': 'hiểu rõ',
             'kr': {'ko': '확실히 알다',
                    'zh': '確切知道',
                    'en': 'to know for certain',
                    'ja': '確実に知る',
                    'de': 'deutlich verstehen',
                    'fr': 'bien comprendre',
                    'pl': 'dobrze rozumieć'}},
            {'vi': 'cảm nghĩ',
             'kr': {'ko': '느낌',
                    'zh': '感覺',
                    'en': 'feeling',
                    'ja': '感じ',
                    'de': 'Gefühl, Gedanke',
                    'fr': 'impression, sentiment',
                    'pl': 'wrażenie, odczucie'}},
            {'vi': 'chủ nghĩa',
             'kr': {'ko': '주의',
                    'zh': '注意',
                    'en': 'caution/attention',
                    'ja': '注意',
                    'de': 'Lehre / Prinzip / Grundsatz',
                    'fr': 'principe, doctrine',
                    'pl': 'zasada, doktryna'}},
            {'vi': 'thẩm mỹ',
             'kr': {'ko': '미용',
                    'zh': '美容',
                    'en': 'beauty care',
                    'ja': '美容',
                    'de': 'Schönheitspflege, Kosmetik',
                    'fr': 'esthétique, beauté',
                    'pl': 'uroda, pielęgnacja urody'}}]},
 {'t1': 'hoi',
  't2': 'nang',
  't1_kr': {'ko': '회성',
            'zh': '問聲',
            'en': 'dipping tone',
            'ja': '問声',
            'de': 'Frageton (fallend-steigend)',
            'fr': 'Ton descendant-montant',
            'pl': 'Ton pytający'},
  't2_kr': {'ko': '하성',
            'zh': '重聲',
            'en': 'heavy tone',
            'ja': '重声',
            'de': 'Schwerer fallender Ton',
            'fr': 'Ton lourd',
            'pl': 'Ton ciężki'},
  't1_mark': 'ả',
  't2_mark': 'ạ',
  'words': [{'vi': 'bảo vệ',
             'kr': {'ko': '보호하다',
                    'zh': '保護',
                    'en': 'to protect',
                    'ja': '保護する',
                    'de': 'beschützen',
                    'fr': 'protéger',
                    'pl': 'chronić, strażnik'}},
            {'vi': 'thể dục',
             'kr': {'ko': '체육',
                    'zh': '體育',
                    'en': 'physical education',
                    'ja': '体育',
                    'de': 'Sport, Gymnastik',
                    'fr': 'gymnastique, sport',
                    'pl': 'gimnastyka, sport'}},
            {'vi': 'cảm động',
             'kr': {'ko': '감동적인',
                    'zh': '感人的',
                    'en': 'moving; touching',
                    'ja': '感動的な',
                    'de': 'berührend, bewegend',
                    'fr': 'émouvant, touchant',
                    'pl': 'poruszający, wzruszający'}},
            {'vi': 'kỷ niệm',
             'kr': {'ko': '추억',
                    'zh': '回憶',
                    'en': 'memory',
                    'ja': '思い出',
                    'de': 'Erinnerung, Andenken',
                    'fr': 'souvenir, commémoration',
                    'pl': 'wspomnienie, pamiątka'}}]},
 {'t1': 'nga',
  't2': 'ngang',
  't1_kr': {'ko': '거성',
            'zh': '跌聲',
            'en': 'creaky-rising tone',
            'ja': '跌声',
            'de': 'Unterbrochen steigender Ton',
            'fr': 'Ton montant interrompu',
            'pl': 'Ton łamany'},
  't2_kr': {'ko': '단평성',
            'zh': '橫聲',
            'en': 'level tone',
            'ja': '横声',
            'de': 'Ebener Ton',
            'fr': 'Ton égal',
            'pl': 'Ton równy'},
  't1_mark': 'ã',
  't2_mark': 'a',
  'words': [{'vi': 'cũng như',
             'kr': {'ko': '~처럼',
                    'zh': '像~一樣',
                    'en': 'like ~',
                    'ja': '~のように',
                    'de': 'ebenso wie',
                    'fr': 'tout comme, ainsi que',
                    'pl': 'tak jak, równie jak'}},
            {'vi': 'đã lâu',
             'kr': {'ko': '오래전에',
                    'zh': '很久以前',
                    'en': 'long ago',
                    'ja': 'ずっと前に',
                    'de': 'vor langer Zeit',
                    'fr': 'il y a longtemps',
                    'pl': 'dawno temu'}},
            {'vi': 'sẽ đi',
             'kr': {'ko': '갈 것이다',
                    'zh': '將會去',
                    'en': 'will go',
                    'ja': '行くつもりだ',
                    'de': 'wird gehen',
                    'fr': 'ira, va partir',
                    'pl': 'pójdzie, pojedzie'}},
            {'vi': 'giữa trưa',
             'kr': {'ko': '한낮',
                    'zh': '正午',
                    'en': 'midday',
                    'ja': '真昼',
                    'de': 'am Mittag, mittags',
                    'fr': 'midi, en plein midi',
                    'pl': 'w samo południe'}}]},
 {'t1': 'nga',
  't2': 'sac',
  't1_kr': {'ko': '거성',
            'zh': '跌聲',
            'en': 'creaky-rising tone',
            'ja': '跌声',
            'de': 'Unterbrochen steigender Ton',
            'fr': 'Ton montant interrompu',
            'pl': 'Ton łamany'},
  't2_kr': {'ko': '상성',
            'zh': '銳聲',
            'en': 'rising tone',
            'ja': '鋭声',
            'de': 'Steigender Ton',
            'fr': 'Ton montant',
            'pl': 'Ton wznoszący'},
  't1_mark': 'ã',
  't2_mark': 'á',
  'words': [{'vi': 'nữ tính',
             'kr': {'ko': '여성스러움',
                    'zh': '女性化、女人味',
                    'en': 'femininity',
                    'ja': '女性らしさ',
                    'de': 'Weiblichkeit',
                    'fr': 'féminité',
                    'pl': 'kobiecość'}},
            {'vi': 'cũng tốt',
             'kr': {'ko': '그래도 괜찮다',
                    'zh': '那樣也沒關係。',
                    'en': "It's okay even so.",
                    'ja': 'それでも大丈夫だ。',
                    'de': 'auch gut / trotzdem in Ordnung',
                    'fr': "c'est bien aussi / convenable quand même",
                    'pl': 'też dobrze, w porządku'}},
            {'vi': 'dễ tính',
             'kr': {'ko': '무난함',
                    'zh': '不錯，尚可',
                    'en': 'acceptable / not bad',
                    'ja': '無難さ',
                    'de': 'umgänglich, gutmütig',
                    'fr': 'facile à vivre, accommodant',
                    'pl': 'ugodowy, łatwy we współżyciu'}},
            {'vi': 'sẽ có',
             'kr': {'ko': '있을 것이다',
                    'zh': '會有/將會存在',
                    'en': 'will be / there will be',
                    'ja': 'あるだろう',
                    'de': 'wird geben / vorhanden sein',
                    'fr': 'il y aura, sera présent',
                    'pl': 'będzie, pojawi się'}}]},
 {'t1': 'nga',
  't2': 'huyen',
  't1_kr': {'ko': '거성',
            'zh': '跌聲',
            'en': 'creaky-rising tone',
            'ja': '跌声',
            'de': 'Unterbrochen steigender Ton',
            'fr': 'Ton montant interrompu',
            'pl': 'Ton łamany'},
  't2_kr': {'ko': '장평성',
            'zh': '玄聲',
            'en': 'falling tone',
            'ja': '玄声',
            'de': 'Fallender Ton',
            'fr': 'Ton descendant',
            'pl': 'Ton opadający'},
  't1_mark': 'ã',
  't2_mark': 'à',
  'words': [{'vi': 'mỗi ngày',
             'kr': {'ko': '매일',
                    'zh': '每天',
                    'en': 'every day',
                    'ja': '毎日',
                    'de': 'jeden Tag, täglich',
                    'fr': 'chaque jour, quotidiennement',
                    'pl': 'każdego dnia, codziennie'}},
            {'vi': 'cũng là',
             'kr': {'ko': '역시 ~이다',
                    'zh': '也是～',
                    'en': 'is also ~',
                    'ja': 'やはり〜だ',
                    'de': 'ist auch ...',
                    'fr': 'est également ...',
                    'pl': 'jest również...'}},
            {'vi': 'vẫn còn',
             'kr': {'ko': '아직도',
                    'zh': '仍然',
                    'en': 'still',
                    'ja': 'まだ',
                    'de': 'immer noch da sein',
                    'fr': 'être toujours là, encore',
                    'pl': 'wciąż jest, nadal'}},
            {'vi': 'nữa là',
             'kr': {'ko': '하물며',
                    'zh': '何況',
                    'en': 'let alone / much less',
                    'ja': 'まして',
                    'de': 'geschweige denn',
                    'fr': 'à plus forte raison',
                    'pl': 'tym bardziej, a cóż dopiero'}}]},
 {'t1': 'nga',
  't2': 'hoi',
  't1_kr': {'ko': '거성',
            'zh': '跌聲',
            'en': 'creaky-rising tone',
            'ja': '跌声',
            'de': 'Unterbrochen steigender Ton',
            'fr': 'Ton montant interrompu',
            'pl': 'Ton łamany'},
  't2_kr': {'ko': '회성',
            'zh': '問聲',
            'en': 'dipping tone',
            'ja': '問声',
            'de': 'Frageton (fallend-steigend)',
            'fr': 'Ton descendant-montant',
            'pl': 'Ton pytający'},
  't1_mark': 'ã',
  't2_mark': 'ả',
  'words': [{'vi': 'vẫn khỏe',
             'kr': {'ko': '여전히 건강하다',
                    'zh': '依然健康',
                    'en': 'still healthy',
                    'ja': '依然として健康だ',
                    'de': 'immer noch gesund',
                    'fr': 'toujours en bonne santé',
                    'pl': 'wciąż zdrowy'}},
            {'vi': 'dễ hiểu',
             'kr': {'ko': '이해하기 쉬운',
                    'zh': '容易理解的',
                    'en': 'easy to understand',
                    'ja': '理解しやすい',
                    'de': 'leicht verständlich',
                    'fr': 'facile à comprendre',
                    'pl': 'łatwy do zrozumienia'}},
            {'vi': 'nghĩ thử',
             'kr': {'ko': '생각해보다',
                    'zh': '考慮一下',
                    'en': 'to think it over',
                    'ja': '考えてみる',
                    'de': 'nachdenken, überlegen',
                    'fr': 'réfléchir, y penser',
                    'pl': 'pomyśleć, zastanowić się'}},
            {'vi': 'vẫn ổn',
             'kr': {'ko': '여전히 괜찮다',
                    'zh': '依然還好',
                    'en': 'still okay',
                    'ja': '依然として大丈夫だ',
                    'de': 'immer noch in Ordnung',
                    'fr': 'toujours bien, ça va toujours',
                    'pl': 'nadal w porządku'}}]},
 {'t1': 'nga',
  't2': 'nga',
  't1_kr': {'ko': '거성',
            'zh': '跌聲',
            'en': 'creaky-rising tone',
            'ja': '跌声',
            'de': 'Unterbrochen steigender Ton',
            'fr': 'Ton montant interrompu',
            'pl': 'Ton łamany'},
  't2_kr': {'ko': '거성',
            'zh': '跌聲',
            'en': 'creaky-rising tone',
            'ja': '跌声',
            'de': 'Unterbrochen steigender Ton',
            'fr': 'Ton montant interrompu',
            'pl': 'Ton łamany'},
  't1_mark': 'ã',
  't2_mark': 'ã',
  'words': [{'vi': 'mãi mãi',
             'kr': {'ko': '영원히',
                    'zh': '永遠',
                    'en': 'forever',
                    'ja': '永遠に',
                    'de': 'für immer, ewig',
                    'fr': 'pour toujours, éternellement',
                    'pl': 'na zawsze, wiecznie'}},
            {'vi': 'dễ vỡ',
             'kr': {'ko': '깨지기 쉬운',
                    'zh': '易碎的',
                    'en': 'fragile, easily broken',
                    'ja': '壊れやすい',
                    'de': 'zerbrechlich',
                    'fr': 'fragile',
                    'pl': 'kruchy, łatwo tłukący się'}},
            {'vi': 'cũng vẫn',
             'kr': {'ko': '그래도 여전히',
                    'zh': '即便如此,依然',
                    'en': 'even so, still',
                    'ja': 'それでも依然として',
                    'de': 'trotzdem noch',
                    'fr': 'toujours quand même',
                    'pl': 'mimo to nadal'}},
            {'vi': 'vũ nữ',
             'kr': {'ko': '무녀(舞女), 무희(舞姬), 춤추는 여인',
                    'zh': '舞蹈演員',
                    'en': 'dancer',
                    'ja': '舞踊家（ダンサー）',
                    'de': 'Tänzerin',
                    'fr': 'danseuse',
                    'pl': 'tancerka'}}]},
 {'t1': 'nga',
  't2': 'nang',
  't1_kr': {'ko': '거성',
            'zh': '跌聲',
            'en': 'creaky-rising tone',
            'ja': '跌声',
            'de': 'Unterbrochen steigender Ton',
            'fr': 'Ton montant interrompu',
            'pl': 'Ton łamany'},
  't2_kr': {'ko': '하성',
            'zh': '重聲',
            'en': 'heavy tone',
            'ja': '重声',
            'de': 'Schwerer fallender Ton',
            'fr': 'Ton lourd',
            'pl': 'Ton ciężki'},
  't1_mark': 'ã',
  't2_mark': 'ạ',
  'words': [{'vi': 'nỗ lực',
             'kr': {'ko': '노력',
                    'zh': '努力',
                    'en': 'effort',
                    'ja': '努力',
                    'de': 'Bemühung, Anstrengung',
                    'fr': 'effort',
                    'pl': 'wysiłek, staranie'}},
            {'vi': 'cũng được',
             'kr': {'ko': '그것도 괜찮다',
                    'zh': '那樣也可以。',
                    'en': "That's fine too.",
                    'ja': 'それでもいい。',
                    'de': 'geht auch, ist auch in Ordnung',
                    'fr': "ça convient aussi, c'est d'accord",
                    'pl': 'też w porządku, zgoda'}},
            {'vi': 'nghĩ lại',
             'kr': {'ko': '다시 생각하다',
                    'zh': '重新考慮',
                    'en': 'to think again / to reconsider',
                    'ja': '考え直す',
                    'de': 'nochmals überlegen, umdenken',
                    'fr': 'reconsidérer, y repenser',
                    'pl': 'przemyśleć ponownie'}},
            {'vi': 'cũng vậy',
             'kr': {'ko': '마찬가지다',
                    'zh': '一樣',
                    'en': 'to be the same',
                    'ja': '同じだ',
                    'de': 'genauso, ebenfalls',
                    'fr': 'pareil, de même',
                    'pl': 'tak samo, podobnie'}}]},
 {'t1': 'nang',
  't2': 'ngang',
  't1_kr': {'ko': '하성',
            'zh': '重聲',
            'en': 'heavy tone',
            'ja': '重声',
            'de': 'Schwerer fallender Ton',
            'fr': 'Ton lourd',
            'pl': 'Ton ciężki'},
  't2_kr': {'ko': '단평성',
            'zh': '橫聲',
            'en': 'level tone',
            'ja': '横声',
            'de': 'Ebener Ton',
            'fr': 'Ton égal',
            'pl': 'Ton równy'},
  't1_mark': 'ạ',
  't2_mark': 'a',
  'words': [{'vi': 'học sinh',
             'kr': {'ko': '학생',
                    'zh': '學生',
                    'en': 'student',
                    'ja': '学生',
                    'de': 'Schüler',
                    'fr': 'élève',
                    'pl': 'uczeń'}},
            {'vi': 'đẹp trai',
             'kr': {'ko': '잘생긴',
                    'zh': '帥氣的',
                    'en': 'handsome',
                    'ja': 'ハンサムな',
                    'de': 'gut aussehend',
                    'fr': 'bel homme, beau',
                    'pl': 'przystojny'}},
            {'vi': 'tự nhiên',
             'kr': {'ko': '자연',
                    'zh': '自然',
                    'en': 'nature',
                    'ja': '自然',
                    'de': 'Natur, natürlich',
                    'fr': 'nature, naturel',
                    'pl': 'natura, naturalny'}},
            {'vi': 'nội tâm',
             'kr': {'ko': '내면',
                    'zh': '內心,內部',
                    'en': 'inside, inner side',
                    'ja': '内面',
                    'de': 'Innenleben',
                    'fr': 'vie intérieure',
                    'pl': 'życie wewnętrzne'}}]},
 {'t1': 'nang',
  't2': 'sac',
  't1_kr': {'ko': '하성',
            'zh': '重聲',
            'en': 'heavy tone',
            'ja': '重声',
            'de': 'Schwerer fallender Ton',
            'fr': 'Ton lourd',
            'pl': 'Ton ciężki'},
  't2_kr': {'ko': '상성',
            'zh': '銳聲',
            'en': 'rising tone',
            'ja': '鋭声',
            'de': 'Steigender Ton',
            'fr': 'Ton montant',
            'pl': 'Ton wznoszący'},
  't1_mark': 'ạ',
  't2_mark': 'á',
  'words': [{'vi': 'hạnh phúc',
             'kr': {'ko': '행복',
                    'zh': '幸福',
                    'en': 'happiness',
                    'ja': '幸福',
                    'de': 'Glück',
                    'fr': 'bonheur',
                    'pl': 'szczęście'}},
            {'vi': 'nhiệt đới',
             'kr': {'ko': '열대',
                    'zh': '熱帶',
                    'en': 'tropical',
                    'ja': '熱帯',
                    'de': 'Tropen, tropisch',
                    'fr': 'tropical',
                    'pl': 'tropikalny'}},
            {'vi': 'trực tiếp',
             'kr': {'ko': '직접',
                    'zh': '直接/親自',
                    'en': 'directly / in person',
                    'ja': '直接',
                    'de': 'direkt, persönlich',
                    'fr': 'directement, en personne',
                    'pl': 'bezpośrednio, osobiście'}},
            {'vi': 'hạ cánh',
             'kr': {'ko': '착륙하다',
                    'zh': '著陸',
                    'en': 'to land',
                    'ja': '着陸する',
                    'de': 'landen',
                    'fr': 'atterrir',
                    'pl': 'lądować'}}]},
 {'t1': 'nang',
  't2': 'huyen',
  't1_kr': {'ko': '하성',
            'zh': '重聲',
            'en': 'heavy tone',
            'ja': '重声',
            'de': 'Schwerer fallender Ton',
            'fr': 'Ton lourd',
            'pl': 'Ton ciężki'},
  't2_kr': {'ko': '장평성',
            'zh': '玄聲',
            'en': 'falling tone',
            'ja': '玄声',
            'de': 'Fallender Ton',
            'fr': 'Ton descendant',
            'pl': 'Ton opadający'},
  't1_mark': 'ạ',
  't2_mark': 'à',
  'words': [{'vi': 'nhiệt tình',
             'kr': {'ko': '열정적인',
                    'zh': '熱情的',
                    'en': 'passionate',
                    'ja': '情熱的な',
                    'de': 'begeistert, leidenschaftlich',
                    'fr': 'enthousiaste, passionné',
                    'pl': 'entuzjastyczny, pełen zapału'}},
            {'vi': 'vội vàng',
             'kr': {'ko': '서두르는',
                    'zh': '匆忙的',
                    'en': 'hurried',
                    'ja': '急いでいる',
                    'de': 'hastig, eilig',
                    'fr': 'précipité, pressé',
                    'pl': 'pośpieszny, w pośpiechu'}},
            {'vi': 'nặng nề',
             'kr': {'ko': '무거운',
                    'zh': '重的',
                    'en': 'heavy',
                    'ja': '重い',
                    'de': 'schwerfällig, drückend',
                    'fr': 'lourd, pesant',
                    'pl': 'ciężki, ociężały'}},
            {'vi': 'lạnh lùng',
             'kr': {'ko': '냉정한',
                    'zh': '冷靜的,冷淡的',
                    'en': 'cold-hearted, calm',
                    'ja': '冷静な、冷淡な',
                    'de': 'kalt, distanziert',
                    'fr': 'froid, distant',
                    'pl': 'zimny, obojętny'}}]},
 {'t1': 'nang',
  't2': 'hoi',
  't1_kr': {'ko': '하성',
            'zh': '重聲',
            'en': 'heavy tone',
            'ja': '重声',
            'de': 'Schwerer fallender Ton',
            'fr': 'Ton lourd',
            'pl': 'Ton ciężki'},
  't2_kr': {'ko': '회성',
            'zh': '問聲',
            'en': 'dipping tone',
            'ja': '問声',
            'de': 'Frageton (fallend-steigend)',
            'fr': 'Ton descendant-montant',
            'pl': 'Ton pytający'},
  't1_mark': 'ạ',
  't2_mark': 'ả',
  'words': [{'vi': 'hạnh kiểm',
             'kr': {'ko': '품행',
                    'zh': '品行',
                    'en': 'conduct',
                    'ja': '品行',
                    'de': 'Betragen, Führung',
                    'fr': 'conduite, comportement',
                    'pl': 'sprawowanie, zachowanie'}},
            {'vi': 'cụ thể',
             'kr': {'ko': '구체적인',
                    'zh': '具體的',
                    'en': 'concrete; specific',
                    'ja': '具体的な',
                    'de': 'konkret',
                    'fr': 'concret, précis',
                    'pl': 'konkretny, szczegółowy'}},
            {'vi': 'vật thể',
             'kr': {'ko': '물체',
                    'zh': '物體',
                    'en': 'object',
                    'ja': '物体',
                    'de': 'Gegenstand, Objekt',
                    'fr': 'objet',
                    'pl': 'przedmiot, obiekt'}},
            {'vi': 'kịch bản',
             'kr': {'ko': '대본',
                    'zh': '台本',
                    'en': 'script',
                    'ja': '台本',
                    'de': 'Drehbuch, Skript',
                    'fr': 'scénario, script',
                    'pl': 'scenariusz'}}]},
 {'t1': 'nang',
  't2': 'nga',
  't1_kr': {'ko': '하성',
            'zh': '重聲',
            'en': 'heavy tone',
            'ja': '重声',
            'de': 'Schwerer fallender Ton',
            'fr': 'Ton lourd',
            'pl': 'Ton ciężki'},
  't2_kr': {'ko': '거성',
            'zh': '跌聲',
            'en': 'creaky-rising tone',
            'ja': '跌声',
            'de': 'Unterbrochen steigender Ton',
            'fr': 'Ton montant interrompu',
            'pl': 'Ton łamany'},
  't1_mark': 'ạ',
  't2_mark': 'ã',
  'words': [{'vi': 'nhạc sĩ',
             'kr': {'ko': '음악가',
                    'zh': '音樂家',
                    'en': 'musician',
                    'ja': '音楽家',
                    'de': 'Musiker, Komponist',
                    'fr': 'musicien, compositeur',
                    'pl': 'muzyk, kompozytor'}},
            {'vi': 'trọng nghĩa',
             'kr': {'ko': '도리를 중시하다, 의리있다',
                    'zh': '講義氣的',
                    'en': 'loyal',
                    'ja': '義理堅い',
                    'de': 'loyal, pflichtbewusst',
                    'fr': 'loyal, attaché au devoir',
                    'pl': 'lojalny, ceniący sprawiedliwość'}},
            {'vi': 'hiện hữu',
             'kr': {'ko': '존재하다',
                    'zh': '存在的',
                    'en': 'existing',
                    'ja': '存在する',
                    'de': 'existieren, vorhanden sein',
                    'fr': 'exister, être présent',
                    'pl': 'istnieć, obecny'}},
            {'vi': 'tự mãn',
             'kr': {'ko': '자만하다',
                    'zh': '自滿的',
                    'en': 'conceited',
                    'ja': '自惚れた',
                    'de': 'selbstgefällig, arrogant',
                    'fr': 'suffisant, prétentieux',
                    'pl': 'zarozumiały, zadowolony z siebie'}}]},
 {'t1': 'nang',
  't2': 'nang',
  't1_kr': {'ko': '하성',
            'zh': '重聲',
            'en': 'heavy tone',
            'ja': '重声',
            'de': 'Schwerer fallender Ton',
            'fr': 'Ton lourd',
            'pl': 'Ton ciężki'},
  't2_kr': {'ko': '하성',
            'zh': '重聲',
            'en': 'heavy tone',
            'ja': '重声',
            'de': 'Schwerer fallender Ton',
            'fr': 'Ton lourd',
            'pl': 'Ton ciężki'},
  't1_mark': 'ạ',
  't2_mark': 'ạ',
  'words': [{'vi': 'nhiệt độ',
             'kr': {'ko': '온도',
                    'zh': '溫度',
                    'en': 'temperature',
                    'ja': '温度',
                    'de': 'Temperatur',
                    'fr': 'température',
                    'pl': 'temperatura'}},
            {'vi': 'hiện tại',
             'kr': {'ko': '현재',
                    'zh': '現在',
                    'en': 'present',
                    'ja': '現在',
                    'de': 'Gegenwart, gegenwärtig',
                    'fr': 'présent, actuel',
                    'pl': 'teraźniejszość, obecny'}},
            {'vi': 'lịch sự',
             'kr': {'ko': '예의 바른',
                    'zh': '有禮貌的',
                    'en': 'polite',
                    'ja': '礼儀正しい',
                    'de': 'höflich',
                    'fr': 'poli, courtois',
                    'pl': 'uprzejmy, kulturalny'}},
            {'vi': 'hoạt động',
             'kr': {'ko': '활동하다',
                    'zh': '活動',
                    'en': 'to be active',
                    'ja': '活動する',
                    'de': 'aktiv sein, Tätigkeit',
                    'fr': 'être actif, activité',
                    'pl': 'być aktywnym, działać'}}]}]
