# Auto-generated study plan that partitions every word/entry across all vocabulary
# subtabs (한자음, 어순반대, 동일음, 기본, 반의, 상용, 신권, 인명, 끝말, 남북 단어) into 16 weekly
# chunks (and each week's chunk into 5 weekday chunks), so 베트남어 기본단어 테스트 covers the
# WHOLE 어휘 tab rather than only the 기본 subtab. 'start'/'end' are a 0-based, exclusive-end
# local index range into that subtab's own natural item order (same order the vocab render
# functions build internally), matching applyVocabFocus()'s slicing in app_logic.js.
VOCAB_PLAN = [
 {'week': 1,
  'segments': [{'subVal': 'rhyme', 'start': 0, 'end': 212}],
  'days': [
   {'segments': [{'subVal': 'rhyme', 'start': 0, 'end': 42}]},
   {'segments': [{'subVal': 'rhyme', 'start': 42, 'end': 84}]},
   {'segments': [{'subVal': 'rhyme', 'start': 84, 'end': 127}]},
   {'segments': [{'subVal': 'rhyme', 'start': 127, 'end': 169}]},
   {'segments': [{'subVal': 'rhyme', 'start': 169, 'end': 212}]},
  ]},
 {'week': 2,
  'segments': [{'subVal': 'rhyme', 'start': 212, 'end': 316}, {'subVal': 'orderrev', 'start': 0, 'end': 15}, {'subVal': 'groups', 'start': 0, 'end': 105}],
  'days': [
   {'segments': [{'subVal': 'rhyme', 'start': 212, 'end': 254}]},
   {'segments': [{'subVal': 'rhyme', 'start': 254, 'end': 297}]},
   {'segments': [{'subVal': 'rhyme', 'start': 297, 'end': 316}, {'subVal': 'orderrev', 'start': 0, 'end': 15}, {'subVal': 'groups', 'start': 0, 'end': 19}]},
   {'segments': [{'subVal': 'groups', 'start': 19, 'end': 62}]},
   {'segments': [{'subVal': 'groups', 'start': 62, 'end': 105}]},
  ]},
 {'week': 3,
  'segments': [{'subVal': 'groups', 'start': 105, 'end': 317}],
  'days': [
   {'segments': [{'subVal': 'groups', 'start': 105, 'end': 147}]},
   {'segments': [{'subVal': 'groups', 'start': 147, 'end': 189}]},
   {'segments': [{'subVal': 'groups', 'start': 189, 'end': 232}]},
   {'segments': [{'subVal': 'groups', 'start': 232, 'end': 274}]},
   {'segments': [{'subVal': 'groups', 'start': 274, 'end': 317}]},
  ]},
 {'week': 4,
  'segments': [{'subVal': 'groups', 'start': 317, 'end': 530}],
  'days': [
   {'segments': [{'subVal': 'groups', 'start': 317, 'end': 359}]},
   {'segments': [{'subVal': 'groups', 'start': 359, 'end': 402}]},
   {'segments': [{'subVal': 'groups', 'start': 402, 'end': 444}]},
   {'segments': [{'subVal': 'groups', 'start': 444, 'end': 487}]},
   {'segments': [{'subVal': 'groups', 'start': 487, 'end': 530}]},
  ]},
 {'week': 5,
  'segments': [{'subVal': 'groups', 'start': 530, 'end': 620}, {'subVal': 'basic', 'start': 0, 'end': 113}, {'subVal': 'antonym', 'start': 0, 'end': 10}],
  'days': [
   {'segments': [{'subVal': 'groups', 'start': 530, 'end': 572}]},
   {'segments': [{'subVal': 'groups', 'start': 572, 'end': 615}]},
   {'segments': [{'subVal': 'groups', 'start': 615, 'end': 620}, {'subVal': 'basic', 'start': 0, 'end': 37}]},
   {'segments': [{'subVal': 'basic', 'start': 37, 'end': 80}]},
   {'segments': [{'subVal': 'basic', 'start': 80, 'end': 113}, {'subVal': 'antonym', 'start': 0, 'end': 10}]},
  ]},
 {'week': 6,
  'segments': [{'subVal': 'antonym', 'start': 10, 'end': 99}, {'subVal': 'freq', 'start': 0, 'end': 123}],
  'days': [
   {'segments': [{'subVal': 'antonym', 'start': 10, 'end': 52}]},
   {'segments': [{'subVal': 'antonym', 'start': 52, 'end': 94}]},
   {'segments': [{'subVal': 'antonym', 'start': 94, 'end': 99}, {'subVal': 'freq', 'start': 0, 'end': 38}]},
   {'segments': [{'subVal': 'freq', 'start': 38, 'end': 80}]},
   {'segments': [{'subVal': 'freq', 'start': 80, 'end': 123}]},
  ]},
 {'week': 7,
  'segments': [{'subVal': 'freq', 'start': 123, 'end': 336}],
  'days': [
   {'segments': [{'subVal': 'freq', 'start': 123, 'end': 165}]},
   {'segments': [{'subVal': 'freq', 'start': 165, 'end': 208}]},
   {'segments': [{'subVal': 'freq', 'start': 208, 'end': 250}]},
   {'segments': [{'subVal': 'freq', 'start': 250, 'end': 293}]},
   {'segments': [{'subVal': 'freq', 'start': 293, 'end': 336}]},
  ]},
 {'week': 8,
  'segments': [{'subVal': 'freq', 'start': 336, 'end': 549}],
  'days': [
   {'segments': [{'subVal': 'freq', 'start': 336, 'end': 378}]},
   {'segments': [{'subVal': 'freq', 'start': 378, 'end': 421}]},
   {'segments': [{'subVal': 'freq', 'start': 421, 'end': 463}]},
   {'segments': [{'subVal': 'freq', 'start': 463, 'end': 506}]},
   {'segments': [{'subVal': 'freq', 'start': 506, 'end': 549}]},
  ]},
 {'week': 9,
  'segments': [{'subVal': 'freq', 'start': 549, 'end': 761}],
  'days': [
   {'segments': [{'subVal': 'freq', 'start': 549, 'end': 591}]},
   {'segments': [{'subVal': 'freq', 'start': 591, 'end': 633}]},
   {'segments': [{'subVal': 'freq', 'start': 633, 'end': 676}]},
   {'segments': [{'subVal': 'freq', 'start': 676, 'end': 718}]},
   {'segments': [{'subVal': 'freq', 'start': 718, 'end': 761}]},
  ]},
 {'week': 10,
  'segments': [{'subVal': 'freq', 'start': 761, 'end': 974}],
  'days': [
   {'segments': [{'subVal': 'freq', 'start': 761, 'end': 803}]},
   {'segments': [{'subVal': 'freq', 'start': 803, 'end': 846}]},
   {'segments': [{'subVal': 'freq', 'start': 846, 'end': 888}]},
   {'segments': [{'subVal': 'freq', 'start': 888, 'end': 931}]},
   {'segments': [{'subVal': 'freq', 'start': 931, 'end': 974}]},
  ]},
 {'week': 11,
  'segments': [{'subVal': 'freq', 'start': 974, 'end': 1186}],
  'days': [
   {'segments': [{'subVal': 'freq', 'start': 974, 'end': 1016}]},
   {'segments': [{'subVal': 'freq', 'start': 1016, 'end': 1058}]},
   {'segments': [{'subVal': 'freq', 'start': 1058, 'end': 1101}]},
   {'segments': [{'subVal': 'freq', 'start': 1101, 'end': 1143}]},
   {'segments': [{'subVal': 'freq', 'start': 1143, 'end': 1186}]},
  ]},
 {'week': 12,
  'segments': [{'subVal': 'freq', 'start': 1186, 'end': 1399}],
  'days': [
   {'segments': [{'subVal': 'freq', 'start': 1186, 'end': 1228}]},
   {'segments': [{'subVal': 'freq', 'start': 1228, 'end': 1271}]},
   {'segments': [{'subVal': 'freq', 'start': 1271, 'end': 1313}]},
   {'segments': [{'subVal': 'freq', 'start': 1313, 'end': 1356}]},
   {'segments': [{'subVal': 'freq', 'start': 1356, 'end': 1399}]},
  ]},
 {'week': 13,
  'segments': [{'subVal': 'freq', 'start': 1399, 'end': 1503}, {'subVal': 'theo', 'start': 0, 'end': 109}],
  'days': [
   {'segments': [{'subVal': 'freq', 'start': 1399, 'end': 1441}]},
   {'segments': [{'subVal': 'freq', 'start': 1441, 'end': 1484}]},
   {'segments': [{'subVal': 'freq', 'start': 1484, 'end': 1503}, {'subVal': 'theo', 'start': 0, 'end': 23}]},
   {'segments': [{'subVal': 'theo', 'start': 23, 'end': 66}]},
   {'segments': [{'subVal': 'theo', 'start': 66, 'end': 109}]},
  ]},
 {'week': 14,
  'segments': [{'subVal': 'theo', 'start': 109, 'end': 283}, {'subVal': 'names', 'start': 0, 'end': 38}],
  'days': [
   {'segments': [{'subVal': 'theo', 'start': 109, 'end': 151}]},
   {'segments': [{'subVal': 'theo', 'start': 151, 'end': 193}]},
   {'segments': [{'subVal': 'theo', 'start': 193, 'end': 236}]},
   {'segments': [{'subVal': 'theo', 'start': 236, 'end': 278}]},
   {'segments': [{'subVal': 'theo', 'start': 278, 'end': 283}, {'subVal': 'names', 'start': 0, 'end': 38}]},
  ]},
 {'week': 15,
  'segments': [{'subVal': 'names', 'start': 38, 'end': 184}, {'subVal': 'chain', 'start': 0, 'end': 67}],
  'days': [
   {'segments': [{'subVal': 'names', 'start': 38, 'end': 80}]},
   {'segments': [{'subVal': 'names', 'start': 80, 'end': 123}]},
   {'segments': [{'subVal': 'names', 'start': 123, 'end': 165}]},
   {'segments': [{'subVal': 'names', 'start': 165, 'end': 184}, {'subVal': 'chain', 'start': 0, 'end': 24}]},
   {'segments': [{'subVal': 'chain', 'start': 24, 'end': 67}]},
  ]},
 {'week': 16,
  'segments': [{'subVal': 'chain', 'start': 67, 'end': 232}, {'subVal': 'dialect', 'start': 0, 'end': 48}],
  'days': [
   {'segments': [{'subVal': 'chain', 'start': 67, 'end': 109}]},
   {'segments': [{'subVal': 'chain', 'start': 109, 'end': 152}]},
   {'segments': [{'subVal': 'chain', 'start': 152, 'end': 194}]},
   {'segments': [{'subVal': 'chain', 'start': 194, 'end': 232}, {'subVal': 'dialect', 'start': 0, 'end': 5}]},
   {'segments': [{'subVal': 'dialect', 'start': 5, 'end': 48}]},
  ]},
]
