# [어순반대] 탭 전용 추가 데이터 -- 한자음(RHYME_GROUPS)에 이미 포함된 두 항목(gia 加 "gia tăng",
# đơn 單 "đơn giản") 외에, 한국어·중국어(표준중국어)·일본어가 모두 같은 한자 어순을 쓰는데 베트남어만
# 어순이 반대인, 실제로 자주 쓰이는 단어들을 추가로 모았다. RHYME_GROUPS는 받침(끝소리)·모음별로
# 분류된 한자음 대응표라서 이 단어들을 억지로 그 분류 체계에 끼워 넣지 않고 별도 목록으로 관리한다.
#
# 각 항목의 구조는 RHYME_GROUPS의 단어 항목과 동일하게 맞췄다: word/hanja/kr/pinyin/bopomofo/gloss는
# 실제 베트남어 단어의 "첫 음절"에 대응하는 한자 1자를, second_word/second_hanja/second_kr/
# second_pinyin/second_bopomofo/second_gloss는 "둘째 음절"에 대응하는 한자 1자를 각각 소개한다
# (RHYME_GROUPS 쪽의 word_order_reversed:True 두 항목에도 동일하게 second_* 필드가 추가돼 있다 --
# app_logic.js의 renderVocabOrderReversed()가 [어순반대] 탭에서 두 항목 모두 같은 형식으로 보여준다).
# example은 그 두 음절이 실제로 이어진(즉 표준 한자 어순과 반대인) 베트남어 단어, example_kr은
# 한국어에서 실제로 쓰이는 "표준 어순" 발음과 한자(참고용, [한자음] 탭에서만 쓰임), example_mean은
# 그 단어의 뜻이다. [어순반대] 탭 자체는 word/second_word/hanja/second_hanja/kr/second_kr로부터
# "word+second_word 어순 그대로의" 한자음 표기(예: 가증(加增))를 직접 계산해서 보여주고, 그 뒤에
# example_mean(예: 증가)을 붙인다 -- 즉 예문 줄은 "실제 단어 어순대로 읽은 한자음 — 표준 뜻" 형태다.
#
# 이 현상은 언어학적으로 드문 현상이다(베트남어 한자어 중 순서를 바꿀 수 있는 것은 약 0.67%,
# 그중에서도 한중일 세 언어가 모두 일치하는 표준 어순과 정확히 반대인 경우는 극소수라는 것이
# 선행 연구(La Văn Thanh, 2010; Võ Thị Mai Hoa, 2019)로 확인됨) -- 그래서 목록이 짧다. 확실하지
# 않거나 실생활에서 잘 안 쓰이는 단어는 넣지 않았다.
#
# alt_order_word (일부 항목에만 있음): 그 베트남어 단어를 어순만 뒤집은 형태로도 실제로 쓰는
# 경우(예: diệu kỳ ↔ kỳ diệu) 그 "뒤집힌 형태" 단어 자체만 저장하는 필드 -- 언어별 문구("...도 씀"/
# "also used as ..."/"也用..."/"...も使う")는 app_logic.js의 altOrderNoteText()가 currentLang에 맞춰
# 조립하므로 여기엔 한국어 문구를 넣지 않는다. app_logic.js의 렌더링에서 줄 맨 끝에 괄호로 붙는다 --
# example 필드 자체에는 넣지 않는다.
WORD_ORDER_REVERSED_EXTRA = [{'word': 'bảo',
  'hanja': '保',
  'kr': '보',
  'pinyin': 'bǎo',
  'bopomofo': 'ㄅㄠˇ',
  'gloss': {'ko': '지킬 보',
            'zh': '保護',
            'en': 'protect, guarantee',
            'ja': '守る',
            'de': 'schützen, sichern',
            'fr': 'protéger, garantir'},
  'second_word': 'đảm',
  'second_hanja': '擔',
  'second_kr': '담',
  'second_pinyin': 'dān',
  'second_bopomofo': 'ㄉㄢ',
  'second_gloss': {'ko': '멜 담',
                   'zh': '擔',
                   'en': 'carry, bear',
                   'ja': '担う',
                   'de': 'tragen, übernehmen',
                   'fr': 'porter, assumer'},
  'example': 'bảo đảm',
  'example_kr': '담보(擔保)',
  'example_mean': {'ko': '담보/보장하다',
                   'zh': '擔保',
                   'en': 'to guarantee, ensure',
                   'ja': '担保',
                   'de': 'garantieren, bürgen',
                   'fr': 'garantir, assurer'},
  'word_order_reversed': True},
 {'word': 'ngoại',
  'hanja': '外',
  'kr': '외',
  'pinyin': 'wài',
  'bopomofo': 'ㄨㄞˋ',
  'gloss': {'ko': '바깥 외', 'zh': '外面', 'en': 'outside', 'ja': '外', 'de': 'außen, außerhalb', 'fr': 'extérieur, dehors'},
  'second_word': 'lệ',
  'second_hanja': '例',
  'second_kr': '례',
  'second_pinyin': 'lì',
  'second_bopomofo': 'ㄌㄧˋ',
  'second_gloss': {'ko': '법식 례',
                   'zh': '例',
                   'en': 'example, precedent',
                   'ja': '例',
                   'de': 'Beispiel, Regel',
                   'fr': 'exemple, règle'},
  'example': 'ngoại lệ',
  'example_kr': '예외(例外)',
  'example_mean': {'ko': '예외', 'zh': '例外', 'en': 'exception', 'ja': '例外', 'de': 'Ausnahme', 'fr': 'exception'},
  'word_order_reversed': True},
 {'word': 'độ',
  'hanja': '度',
  'kr': '도',
  'pinyin': 'dù',
  'bopomofo': 'ㄉㄨˋ',
  'gloss': {'ko': '법도 도', 'zh': '程度', 'en': 'degree, extent', 'ja': '度合い', 'de': 'Grad, Maß', 'fr': 'degré, mesure'},
  'second_word': 'cao',
  'second_hanja': '高',
  'second_kr': '고',
  'second_pinyin': 'gāo',
  'second_bopomofo': 'ㄍㄠ',
  'second_gloss': {'ko': '높을 고', 'zh': '高', 'en': 'high, tall', 'ja': '高い', 'de': 'hoch', 'fr': 'haut'},
  'example': 'độ cao',
  'example_kr': '고도(高度)',
  'example_mean': {'ko': '고도',
                   'zh': '高度',
                   'en': 'height, altitude',
                   'ja': '高度',
                   'de': 'Höhe, Höhenlage',
                   'fr': 'altitude, hauteur'},
  'word_order_reversed': True},
 {'word': 'độc',
  'hanja': '毒',
  'kr': '독',
  'pinyin': 'dú',
  'bopomofo': 'ㄉㄨˊ',
  'gloss': {'ko': '독 독',
            'zh': '毒',
            'en': 'poison, malicious',
            'ja': '毒',
            'de': 'Gift, boshaft',
            'fr': 'poison, malveillant'},
  'second_word': 'ác',
  'second_hanja': '惡',
  'second_kr': '악',
  'second_pinyin': 'è',
  'second_bopomofo': 'ㄜˋ',
  'second_gloss': {'ko': '악할 악',
                   'zh': '惡',
                   'en': 'evil, wicked',
                   'ja': '悪い',
                   'de': 'böse, übel',
                   'fr': 'mauvais, méchant'},
  'example': 'độc ác',
  'example_kr': '악독(惡毒)',
  'example_mean': {'ko': '악독',
                   'zh': '惡毒',
                   'en': 'cruel, wicked',
                   'ja': '悪毒',
                   'de': 'grausam, boshaft',
                   'fr': 'cruel, méchant'},
  'word_order_reversed': True},
 {'word': 'phóng',
  'hanja': '放',
  'kr': '방',
  'pinyin': 'fàng',
  'bopomofo': 'ㄈㄤˋ',
  'gloss': {'ko': '놓을 방',
            'zh': '放',
            'en': 'release, let go',
            'ja': '放す',
            'de': 'loslassen, freilassen',
            'fr': 'relâcher, libérer'},
  'second_word': 'thích',
  'second_hanja': '釋',
  'second_kr': '석',
  'second_pinyin': 'shì',
  'second_bopomofo': 'ㄕˋ',
  'second_gloss': {'ko': '풀 석',
                   'zh': '釋放',
                   'en': 'release, explain',
                   'ja': '釈放',
                   'de': 'lösen, erklären',
                   'fr': 'délier, expliquer'},
  'example': 'phóng thích',
  'example_kr': '석방(釋放)',
  'example_mean': {'ko': '석방',
                   'zh': '釋放',
                   'en': 'to release (a prisoner)',
                   'ja': '釈放',
                   'de': 'freilassen (Gefangenen)',
                   'fr': 'libérer (un prisonnier)'},
  'word_order_reversed': True},
 {'word': 'an',
  'hanja': '安',
  'kr': '안',
  'pinyin': 'ān',
  'bopomofo': 'ㄢ',
  'gloss': {'ko': '편안 안', 'zh': '安', 'en': 'peace, safety', 'ja': '安らか', 'de': 'Frieden, Ruhe', 'fr': 'paix, sécurité'},
  'second_word': 'bình',
  'second_hanja': '平',
  'second_kr': '평',
  'second_pinyin': 'píng',
  'second_bopomofo': 'ㄆㄧㄥˊ',
  'second_gloss': {'ko': '평평할 평',
                   'zh': '平',
                   'en': 'flat, peaceful',
                   'ja': '平ら',
                   'de': 'flach, friedlich',
                   'fr': 'plat, paisible'},
  'example': 'an bình',
  'example_kr': '평안(平安)',
  'example_mean': {'ko': '평안',
                   'zh': '平安',
                   'en': 'peaceful, at peace',
                   'ja': '平安',
                   'de': 'friedlich, voller Frieden',
                   'fr': 'paisible, en paix'},
  'alt_order_word': 'bình an',
  'word_order_reversed': True},
 {'word': 'ác',
  'hanja': '惡',
  'kr': '악',
  'pinyin': 'è',
  'bopomofo': 'ㄜˋ',
  'gloss': {'ko': '악할 악', 'zh': '惡', 'en': 'evil, wicked', 'ja': '悪い', 'de': 'böse, übel', 'fr': 'mauvais, méchant'},
  'second_word': 'hiểm',
  'second_hanja': '險',
  'second_kr': '험',
  'second_pinyin': 'xiǎn',
  'second_bopomofo': 'ㄒㄧㄢˇ',
  'second_gloss': {'ko': '험할 험',
                   'zh': '危險',
                   'en': 'dangerous, steep',
                   'ja': '険しい',
                   'de': 'gefährlich, steil',
                   'fr': 'dangereux, abrupt'},
  'example': 'ác hiểm',
  'example_kr': '험악(險惡)',
  'example_mean': {'ko': '험악',
                   'zh': '險惡',
                   'en': 'sinister, treacherous',
                   'ja': '険悪',
                   'de': 'heimtückisch, finster',
                   'fr': 'sinistre, perfide'},
  'word_order_reversed': True},
 {'word': 'diệu',
  'hanja': '妙',
  'kr': '묘',
  'pinyin': 'miào',
  'bopomofo': 'ㄇㄧㄠˋ',
  'gloss': {'ko': '묘할 묘',
            'zh': '奇妙',
            'en': 'marvelous, wondrous',
            'ja': '妙',
            'de': 'wunderbar, kunstvoll',
            'fr': 'merveilleux, subtil'},
  'second_word': 'kỳ',
  'second_hanja': '奇',
  'second_kr': '기',
  'second_pinyin': 'qí',
  'second_bopomofo': 'ㄑㄧˊ',
  'second_gloss': {'ko': '기이할 기',
                   'zh': '奇異',
                   'en': 'strange, marvelous',
                   'ja': '奇妙',
                   'de': 'seltsam, wunderbar',
                   'fr': 'étrange, merveilleux'},
  'example': 'diệu kỳ',
  'example_kr': '기묘(奇妙)',
  'example_mean': {'ko': '기묘한, 신비로운',
                   'zh': '奇妙',
                   'en': 'marvelous, wondrous',
                   'ja': '奇妙な',
                   'de': 'wunderbar, geheimnisvoll',
                   'fr': 'merveilleux, mystérieux'},
  'alt_order_word': 'kỳ diệu',
  'word_order_reversed': True},
 {'word': 'thủy',
  'hanja': '水',
  'kr': '수',
  'pinyin': 'shuǐ',
  'bopomofo': 'ㄕㄨㄟˇ',
  'gloss': {'ko': '물 수', 'zh': '水', 'en': 'water', 'ja': '水', 'de': 'Wasser', 'fr': 'eau'},
  'second_word': 'triều',
  'second_hanja': '潮',
  'second_kr': '조',
  'second_pinyin': 'cháo',
  'second_bopomofo': 'ㄔㄠˊ',
  'second_gloss': {'ko': '밀물 조', 'zh': '潮汐', 'en': 'tide', 'ja': '潮', 'de': 'Flut, Gezeiten', 'fr': 'marée, flux'},
  'example': 'thủy triều',
  'example_kr': '조수(潮水)',
  'example_mean': {'ko': '조수, 밀물썰물',
                   'zh': '潮汐',
                   'en': 'tide',
                   'ja': '潮',
                   'de': 'Gezeiten, Ebbe und Flut',
                   'fr': 'marée'},
  'word_order_reversed': True},
 {'word': 'hao',
  'hanja': '耗',
  'kr': '모',
  'pinyin': 'hào',
  'bopomofo': 'ㄏㄠˋ',
  'gloss': {'ko': '소모할 모',
            'zh': '耗',
            'en': 'consume, waste',
            'ja': '減る',
            'de': 'verbrauchen, verschwenden',
            'fr': 'consommer, gaspiller'},
  'second_word': 'tổn',
  'second_hanja': '損',
  'second_kr': '손',
  'second_pinyin': 'sǔn',
  'second_bopomofo': 'ㄙㄨㄣˇ',
  'second_gloss': {'ko': '덜 손',
                   'zh': '損失',
                   'en': 'lose, decrease',
                   'ja': '損する',
                   'de': 'mindern, schaden',
                   'fr': 'perdre, diminuer'},
  'example': 'hao tổn',
  'example_kr': '손모(損耗)',
  'example_mean': {'ko': '손모, 소모되어 줄어듦',
                   'zh': '損耗',
                   'en': 'wear and loss, wastage',
                   'ja': '損耗',
                   'de': 'Verschleiß, Verlust',
                   'fr': 'usure, déperdition'},
  'word_order_reversed': True},
 {'word': 'ái',
  'hanja': '愛',
  'kr': '애',
  'pinyin': 'ài',
  'bopomofo': 'ㄞˋ',
  'gloss': {'ko': '사랑 애',
            'zh': '愛',
            'en': 'love, affection',
            'ja': '愛',
            'de': 'Liebe, Zuneigung',
            'fr': 'amour, affection'},
  'second_word': 'ân',
  'second_hanja': '恩',
  'second_kr': '은',
  'second_pinyin': 'ēn',
  'second_bopomofo': 'ㄣ',
  'second_gloss': {'ko': '은혜 은',
                   'zh': '恩惠',
                   'en': 'grace, kindness',
                   'ja': '恩恵',
                   'de': 'Gnade, Güte',
                   'fr': 'grâce, bonté'},
  'example': 'ái ân',
  'example_kr': '은애(恩愛)',
  'example_mean': {'ko': '은애, 부부간의 정',
                   'zh': '恩愛',
                   'en': 'conjugal love, affection',
                   'ja': '恩愛',
                   'de': 'eheliche Liebe, Zuneigung',
                   'fr': 'amour conjugal, affection'},
  'alt_order_word': 'ân ái',
  'word_order_reversed': True},
 {'word': 'biệt',
  'hanja': '別',
  'kr': '별',
  'pinyin': 'bié',
  'bopomofo': 'ㄅㄧㄝˊ',
  'gloss': {'ko': '다를/이별할 별',
            'zh': '別',
            'en': 'separate, part',
            'ja': '別',
            'de': 'trennen, Abschied',
            'fr': 'séparer, adieu'},
  'second_word': 'ly',
  'second_hanja': '離',
  'second_kr': '리',
  'second_pinyin': 'lí',
  'second_bopomofo': 'ㄌㄧˊ',
  'second_gloss': {'ko': '떠날 리',
                   'zh': '離開',
                   'en': 'leave, depart',
                   'ja': '離れる',
                   'de': 'verlassen, scheiden',
                   'fr': 'quitter, s’éloigner'},
  'example': 'biệt ly',
  'example_kr': '이별(離別)',
  'example_mean': {'ko': '이별, 헤어짐',
                   'zh': '離別',
                   'en': 'separation, parting',
                   'ja': '離別',
                   'de': 'Trennung, Abschied',
                   'fr': 'séparation, adieu'},
  'alt_order_word': 'ly biệt',
  'word_order_reversed': True},
 {'word': 'kiến',
  'hanja': '見',
  'kr': '견',
  'pinyin': 'jiàn',
  'bopomofo': 'ㄐㄧㄢˋ',
  'gloss': {'ko': '볼 견', 'zh': '看見', 'en': 'see, view', 'ja': '見る', 'de': 'sehen, Ansicht', 'fr': 'voir, apercevoir'},
  'second_word': 'thức',
  'second_hanja': '識',
  'second_kr': '식',
  'second_pinyin': 'shí',
  'second_bopomofo': 'ㄕˊ',
  'second_gloss': {'ko': '알 식',
                   'zh': '知識',
                   'en': 'know, knowledge',
                   'ja': '知る',
                   'de': 'wissen, erkennen',
                   'fr': 'savoir, connaître'},
  'example': 'kiến thức',
  'example_kr': '식견(識見)',
  'example_mean': {'ko': '식견, 지식',
                   'zh': '見識，知識',
                   'en': 'knowledge, insight',
                   'ja': '見識、知識',
                   'de': 'Wissen, Urteilsvermögen',
                   'fr': 'connaissances, savoir'},
  'word_order_reversed': True},
 {'word': 'giới',
  'hanja': '界',
  'kr': '계',
  'pinyin': 'jiè',
  'bopomofo': 'ㄐㄧㄝˋ',
  'gloss': {'ko': '지경 계',
            'zh': '界限',
            'en': 'boundary, realm',
            'ja': '境界',
            'de': 'Grenze, Bereich',
            'fr': 'limite, frontière'},
  'second_word': 'hạn',
  'second_hanja': '限',
  'second_kr': '한',
  'second_pinyin': 'xiàn',
  'second_bopomofo': 'ㄒㄧㄢˋ',
  'second_gloss': {'ko': '제한할 한',
                   'zh': '限制',
                   'en': 'limit, restrict',
                   'ja': '限る',
                   'de': 'beschränken, Limit',
                   'fr': 'restreindre, borner'},
  'example': 'giới hạn',
  'example_kr': '한계(限界)',
  'example_mean': {'ko': '한계',
                   'zh': '限界，界限',
                   'en': 'limit',
                   'ja': '限界',
                   'de': 'Grenze, Begrenzung',
                   'fr': 'limite, restriction'},
  'word_order_reversed': True},
 {'word': 'giá',
  'hanja': '價',
  'kr': '가',
  'pinyin': 'jià',
  'bopomofo': 'ㄐㄧㄚˋ',
  'gloss': {'ko': '값 가', 'zh': '價格', 'en': 'price, value', 'ja': '値段', 'de': 'Preis, Wert', 'fr': 'prix, valeur'},
  'second_word': 'chuộc',
  'second_hanja': '贖',
  'second_kr': '속',
  'second_pinyin': 'shú',
  'second_bopomofo': 'ㄕㄨˊ',
  'second_gloss': {'ko': '속죄할 속',
                   'zh': '贖罪',
                   'en': 'redeem, atone',
                   'ja': '贖う',
                   'de': 'loskaufen, erlösen',
                   'fr': 'racheter, expier'},
  'example': 'giá chuộc',
  'example_kr': '속가(贖價)',
  'example_mean': {'ko': '속가, 대속물',
                   'zh': '贖價，代贖物',
                   'en': 'ransom, ransom price',
                   'ja': '贖い、代贖物',
                   'de': 'Lösegeld, Loskaufpreis',
                   'fr': 'rançon'},
  'word_order_reversed': True},
 {'word': 'nhân',
  'hanja': '人',
  'kr': '인',
  'pinyin': 'rén',
  'bopomofo': 'ㄖㄣˊ',
  'gloss': {'ko': '사람 인', 'zh': '人', 'en': 'person, human', 'ja': '人', 'de': 'Mensch, Person', 'fr': 'homme, personne'},
  'second_word': 'chứng',
  'second_hanja': '證',
  'second_kr': '증',
  'second_pinyin': 'zhèng',
  'second_bopomofo': 'ㄓㄥˋ',
  'second_gloss': {'ko': '증거 증',
                   'zh': '證據',
                   'en': 'evidence, prove',
                   'ja': '証',
                   'de': 'Beweis, Zeugnis',
                   'fr': 'preuve, témoin'},
  'example': 'nhân chứng',
  'example_kr': '증인(證人)',
  'example_mean': {'ko': '증인', 'zh': '證人', 'en': 'witness', 'ja': '証人', 'de': 'Zeuge', 'fr': 'témoin'},
  'word_order_reversed': True},
 {'word': 'viên',
  'hanja': '員',
  'kr': '원',
  'pinyin': 'yuán',
  'bopomofo': 'ㄩㄢˊ',
  'gloss': {'ko': '인원 원',
            'zh': '人員',
            'en': 'member, personnel',
            'ja': '員',
            'de': 'Mitglied, Personal',
            'fr': 'membre, personnel'},
  'second_word': 'quan',
  'second_hanja': '官',
  'second_kr': '관',
  'second_pinyin': 'guān',
  'second_bopomofo': 'ㄍㄨㄢ',
  'second_gloss': {'ko': '벼슬 관',
                   'zh': '官',
                   'en': 'official, officer',
                   'ja': '官',
                   'de': 'Beamter, Amt',
                   'fr': 'fonctionnaire, magistrat'},
  'example': 'viên quan',
  'example_kr': '관원(官員)',
  'example_mean': {'ko': '관원',
                   'zh': '官員',
                   'en': 'government official',
                   'ja': '官吏',
                   'de': 'Beamter, Amtsträger',
                   'fr': 'fonctionnaire, dignitaire'},
  'word_order_reversed': True},
 {'word': 'bản',
  'hanja': '本',
  'kr': '본',
  'pinyin': 'běn',
  'bopomofo': 'ㄅㄣˇ',
  'gloss': {'ko': '근본 본',
            'zh': '本',
            'en': 'root, origin, book',
            'ja': '本',
            'de': 'Ursprung, Buch',
            'fr': 'origine, livre'},
  'second_word': 'in',
  'second_hanja': '印',
  'second_kr': '인',
  'second_pinyin': 'yìn',
  'second_bopomofo': 'ㄧㄣˋ',
  'second_gloss': {'ko': '찍을 인',
                   'zh': '印',
                   'en': 'print, stamp',
                   'ja': '印',
                   'de': 'drucken, stempeln',
                   'fr': 'imprimer, tamponner'},
  'example': 'bản in',
  'example_kr': '인본(印本)',
  'example_mean': {'ko': '인본, 인쇄본',
                   'zh': '印本，印刷本',
                   'en': 'printed edition, printed copy',
                   'ja': '印本、印刷版',
                   'de': 'Druckausgabe, Druckversion',
                   'fr': 'édition imprimée, exemplaire imprimé'},
  'word_order_reversed': True},
 {'word': 'kinh',
  'hanja': '經',
  'kr': '경',
  'pinyin': 'jīng',
  'bopomofo': 'ㄐㄧㄥ',
  'gloss': {'ko': '경전 경',
            'zh': '經典',
            'en': 'classic, scripture',
            'ja': '経典',
            'de': 'heilige Schrift, Kanon',
            'fr': 'livre sacré, canon'},
  'second_word': 'thánh',
  'second_hanja': '聖',
  'second_kr': '성',
  'second_pinyin': 'shèng',
  'second_bopomofo': 'ㄕㄥˋ',
  'second_gloss': {'ko': '거룩할 성', 'zh': '聖', 'en': 'holy, sacred', 'ja': '聖', 'de': 'heilig', 'fr': 'saint, sacré'},
  'example': 'Kinh Thánh',
  'example_kr': '성경(聖經)',
  'example_mean': {'ko': '성경',
                   'zh': '聖經',
                   'en': 'the Bible, Holy Scripture',
                   'ja': '聖書',
                   'de': 'die Bibel, Heilige Schrift',
                   'fr': 'la Bible, Saintes Écritures'},
  'word_order_reversed': True},
 {'word': 'niềm',
  'hanja': '念',
  'kr': '념',
  'pinyin': 'niàn',
  'bopomofo': 'ㄋㄧㄢˋ',
  'gloss': {'ko': '생각할 념',
            'zh': '念',
            'en': 'to think of, to long for',
            'ja': '念',
            'de': 'denken, hegen',
            'fr': 'penser, éprouver'},
  'second_word': 'tin',
  'second_hanja': '信',
  'second_kr': '신',
  'second_pinyin': 'xìn',
  'second_bopomofo': 'ㄒㄧㄣˋ',
  'second_gloss': {'ko': '믿을 신',
                   'zh': '信',
                   'en': 'to believe, trust',
                   'ja': '信じる',
                   'de': 'glauben, vertrauen',
                   'fr': 'croire, avoir confiance'},
  'example': 'niềm tin',
  'example_kr': '신념(信念)',
  'example_mean': {'ko': '신념, 믿음',
                   'zh': '信念，信仰',
                   'en': 'belief, faith, conviction',
                   'ja': '信念、信仰',
                   'de': 'Glaube, Überzeugung',
                   'fr': 'croyance, foi, conviction'},
  'word_order_reversed': True}]
