# -*- coding: utf-8 -*-
"""
Bundles the regional admin worker and its dependencies into ONE standalone ES module (_worker.js)
for Cloudflare Pages Advanced Mode. Only the jeonju and ulsan builds call this; GENERAL and JW never do.

The bundle is a tiny CommonJS registry: every source file is wrapped, unmodified, in
`function (module, exports, require) { ... }` and resolved through __require(), so the shipped code is
exactly the code the tests exercise. The only text substitution is the two region placeholders in worker.js.
The static site is served by falling through to env.ASSETS.fetch(request) inside worker.js.
"""
import json
from pathlib import Path

ADMIN_DIR = Path(__file__).parent

# (module id used by require(), source file). Order is irrelevant: modules resolve lazily.
_CODE_MODULES = (
    ("./schedule_engine", "schedule_engine.js"),
    ("./distribution_engine", "distribution_engine.js"),
    ("./auth", "auth.js"),
    ("./db", "db.js"),
    ("./admin_ui", "admin_ui.js"),
    ("./worker", "worker.js"),
)

# Browser-side sources embedded as string modules (admin_ui.js inlines them into /admin).
_STRING_MODULES = (
    ("./admin_client_source", "admin_client.js"),
    ("./schedule_engine_source", "schedule_engine.js"),
    ("./distribution_engine_source", "distribution_engine.js"),
)

REGION_NAMES = {
    "jeonju": "전주 베트남어 학습반",
    "ulsan": "울산 베트남어 학습반",
}


def _read(name: str) -> str:
    return (ADMIN_DIR / name).read_text(encoding="utf-8")


def _replace_placeholder(source: str, placeholder: str, value: str) -> str:
    token = json.dumps(placeholder)
    if source.count(token) != 1:
        raise RuntimeError(f"worker.js must contain exactly one {token} placeholder")
    return source.replace(token, json.dumps(value, ensure_ascii=False))


def bundle_regional_worker(region_id: str, region_name: str = None) -> str:
    if region_id not in REGION_NAMES:
        raise ValueError(f"no regional worker for region {region_id!r} (known: {sorted(REGION_NAMES)})")
    if region_name is None:
        region_name = REGION_NAMES[region_id]

    defs = []
    for module_id, filename in _CODE_MODULES:
        source = _read(filename)
        if module_id == "./worker":
            source = _replace_placeholder(source, "__REGION_ID__", region_id)
            source = _replace_placeholder(source, "__REGION_NAME__", region_name)
        defs.append(
            "  " + json.dumps(module_id) + ": function (module, exports, require) {\n" + source + "\n  },"
        )
    for module_id, filename in _STRING_MODULES:
        defs.append(
            "  " + json.dumps(module_id) + ": function (module, exports, require) {\n"
            "    module.exports = " + json.dumps(_read(filename), ensure_ascii=False) + ";\n  },"
        )

    return (
        "// Standalone Cloudflare Pages Advanced Mode worker (generated by regional_admin/bundle_worker.py; do not edit).\n"
        "// Region: " + region_id + ". Requires a D1 binding named DB. Static files are served via env.ASSETS.\n"
        "const __defs = {\n" + "\n".join(defs) + "\n};\n"
        "const __cache = Object.create(null);\n"
        "function __require(name) {\n"
        "  if (__cache[name]) return __cache[name].exports;\n"
        "  const def = __defs[name];\n"
        "  if (!def) throw new Error('regional-admin bundle: unknown module ' + name);\n"
        "  const module = { exports: {} };\n"
        "  __cache[name] = module;\n"
        "  def(module, module.exports, __require);\n"
        "  return module.exports;\n"
        "}\n"
        "const __worker = __require('./worker');\n"
        "export default {\n"
        "  fetch(request, env, ctx) {\n"
        "    return __worker.fetch(request, env, ctx);\n"
        "  },\n"
        "};\n"
    )


if __name__ == "__main__":
    import argparse

    ap = argparse.ArgumentParser(description="Write a regional _worker.js bundle (used by tests); no args prints sizes.")
    ap.add_argument("--region", choices=sorted(REGION_NAMES))
    ap.add_argument("--out", help="output file for --region")
    args = ap.parse_args()
    if args.region and args.out:
        with open(args.out, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(bundle_regional_worker(args.region))
    else:
        for reg in REGION_NAMES:
            print(f"Bundled worker for {reg}: {len(bundle_regional_worker(reg).encode('utf-8'))} bytes")
