-- -*- coding: utf-8 -*-
-- Regional Administration D1 Database Schema
-- Multi-profile isolation for Jeonju, Ulsan, and future regions.

CREATE TABLE IF NOT EXISTS regions (
    id TEXT PRIMARY KEY,               -- 'jeonju', 'ulsan', etc.
    name TEXT NOT NULL,                -- e.g. '전주 베트남어 학습반'
    name_en TEXT,                      -- e.g. 'Jeonju Vietnamese Class'
    domain TEXT NOT NULL,              -- e.g. 'https://jeonju.hoc.tieng.viet.mobile'
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS regional_settings (
    region_id TEXT PRIMARY KEY REFERENCES regions(id) ON DELETE CASCADE,
    preliminary_meeting_date TEXT,     -- ISO YYYY-MM-DD (e.g. '2026-10-03' or NULL)
    course_start_date TEXT,            -- ISO YYYY-MM-DD, first class opportunity (NULL = unconfigured)
    course_end_date TEXT,              -- ISO YYYY-MM-DD, last possible class opportunity (NULL = unconfigured)
    interval_days INTEGER NOT NULL DEFAULT 7 CHECK (interval_days IN (7, 14)),  -- weekly or fortnightly classes
    meeting_weekday TEXT DEFAULT '매주 토요일',
    welcome_title TEXT,
    welcome_body TEXT,                 -- JSON array of paragraphs
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS class_cancellations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    region_id TEXT NOT NULL REFERENCES regions(id) ON DELETE CASCADE,
    date TEXT NOT NULL,                -- ISO YYYY-MM-DD
    reason TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(region_id, date)
);

CREATE INDEX IF NOT EXISTS idx_cancellations_region_date ON class_cancellations(region_id, date);

-- ---------------------------------------------------------------------------------------------
-- DATA MODEL (regional course)
--   1. SOURCE CURRICULUM  curriculum_weeks / curriculum_learning_items / curriculum_assignment_items
--        The authoritative total learning load, organised as 16 source units (week_number 1..16). It is edited only
--        by administrators (add/remove/edit/reorder) and is NEVER rewritten by a schedule change. Every atomic item
--        has a stable `uid` that survives edits and reordering.
--   2. COURSE CONFIGURATION  regional_settings (start, end, interval) + class_cancellations (date, reason)
--        Draft configuration. The number of instructional sessions is DERIVED from it (schedule_engine.js).
--   3. ACTIVE PLAN  course_plans + course_plan_items
--        What the public site shows: a snapshot of the configuration that was applied (config_json) and the
--        item -> session mapping (course_plan_items). origin = 'auto' (generated by distribution_engine.js) or
--        'manual' (administrator pin). Replaced only by an explicit, atomic "apply" (or a pin / restore).
-- ---------------------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS curriculum_weeks (
    region_id TEXT NOT NULL REFERENCES regions(id) ON DELETE CASCADE,
    week_number INTEGER NOT NULL CHECK (week_number BETWEEN 1 AND 16),
    title_ko TEXT,
    title_en TEXT,
    note_ko TEXT,
    note_en TEXT,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (region_id, week_number)
);

CREATE TABLE IF NOT EXISTS curriculum_learning_items (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    uid TEXT NOT NULL,                 -- stable item identity (referenced by course_plan_items)
    region_id TEXT NOT NULL,
    week_number INTEGER NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0 CHECK (sort_order >= 0),
    text_ko TEXT NOT NULL,
    text_en TEXT,
    page TEXT,
    link_json TEXT,                    -- JSON { tab, subAttr, subVal, ... }
    FOREIGN KEY (region_id, week_number) REFERENCES curriculum_weeks(region_id, week_number) ON DELETE CASCADE
);

-- One position per item in a week: a reorder can never leave duplicate order_index values.
CREATE UNIQUE INDEX IF NOT EXISTS uq_learning_items_uid ON curriculum_learning_items(region_id, uid);
CREATE UNIQUE INDEX IF NOT EXISTS uq_learning_items_order ON curriculum_learning_items(region_id, week_number, sort_order);

CREATE TABLE IF NOT EXISTS curriculum_assignment_items (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    uid TEXT NOT NULL,                 -- stable item identity (referenced by course_plan_items)
    region_id TEXT NOT NULL,
    week_number INTEGER NOT NULL,
    day_name TEXT NOT NULL CHECK (day_name IN ('월', '화', '수', '목', '금')),
    category TEXT NOT NULL CHECK (category IN ('review', 'preview', 'vocab')),
    sort_order INTEGER NOT NULL DEFAULT 0 CHECK (sort_order >= 0),
    text_ko TEXT NOT NULL,
    text_en TEXT,
    link_json TEXT,
    FOREIGN KEY (region_id, week_number) REFERENCES curriculum_weeks(region_id, week_number) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_assignment_items_uid ON curriculum_assignment_items(region_id, uid);
CREATE UNIQUE INDEX IF NOT EXISTS uq_assignment_items_order ON curriculum_assignment_items(region_id, week_number, day_name, category, sort_order);

CREATE TABLE IF NOT EXISTS course_plans (
    region_id TEXT PRIMARY KEY REFERENCES regions(id) ON DELETE CASCADE,
    config_json TEXT NOT NULL,         -- applied configuration: {preliminaryMeetingDate, courseStartDate, courseEndDate, intervalDays, cancellations:[{date,reason}]}
    session_count INTEGER NOT NULL CHECK (session_count >= 0),
    applied_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    applied_by TEXT
);

CREATE TABLE IF NOT EXISTS course_plan_items (
    region_id TEXT NOT NULL REFERENCES course_plans(region_id) ON DELETE CASCADE,
    kind TEXT NOT NULL CHECK (kind IN ('learning', 'assignment')),
    item_uid TEXT NOT NULL,            -- curriculum_*_items.uid (source item)
    session_number INTEGER NOT NULL CHECK (session_number >= 1),
    position INTEGER NOT NULL CHECK (position >= 0),
    origin TEXT NOT NULL DEFAULT 'auto' CHECK (origin IN ('auto', 'manual')),
    PRIMARY KEY (region_id, kind, item_uid)          -- an item is placed exactly once
);

-- One position per slot inside a session: an apply can never leave duplicate order indexes.
CREATE UNIQUE INDEX IF NOT EXISTS uq_plan_items_order ON course_plan_items(region_id, kind, session_number, position);

CREATE TABLE IF NOT EXISTS admin_users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,        -- pbkdf2:sha256:100000:<salt_hex>:<hash_hex>
    email TEXT,                         -- Cloudflare Access integration
    allowed_region TEXT NOT NULL,       -- 'jeonju', 'ulsan', or '*' (superadmin)
    is_active INTEGER DEFAULT 1,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS admin_sessions (
    token TEXT PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES admin_users(id) ON DELETE CASCADE,
    region_id TEXT NOT NULL,
    csrf_token TEXT NOT NULL,
    expires_at DATETIME NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_sessions_token ON admin_sessions(token);
CREATE INDEX IF NOT EXISTS idx_sessions_expires ON admin_sessions(expires_at);

CREATE TABLE IF NOT EXISTS audit_logs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    region_id TEXT NOT NULL REFERENCES regions(id) ON DELETE CASCADE,
    user_id INTEGER,
    username TEXT NOT NULL,
    action TEXT NOT NULL,               -- 'update_settings', 'add_cancellation', 'update_cancellation', 'delete_cancellation', 'update_curriculum', 'apply_plan', 'update_plan_pin', 'restore_version'
    details TEXT,                       -- JSON payload or snapshot
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_audit_region ON audit_logs(region_id, created_at DESC);

CREATE TABLE IF NOT EXISTS login_attempts (
    ip TEXT PRIMARY KEY,               -- opaque limiter key: 'ip:<cf-connecting-ip>' or 'user:<username>'
    fail_count INTEGER DEFAULT 0,
    locked_until DATETIME,
    last_attempt DATETIME DEFAULT CURRENT_TIMESTAMP
);

