# -*- coding: utf-8 -*-
"""Writes watchtower_vocab_translations_fr_de_pl.py from the frozen fr / de / pl translation set of the Watchtower study words.

    python scripts/import_wt_translations_fr_de_pl.py          # verify the freeze, validate, (re)write the module
    python scripts/import_wt_translations_fr_de_pl.py --check  # verify the freeze + that the module is exactly what this would write

The frozen files (tests/reports/watchtower_vocab_translation_fr_de_pl/, freeze_manifest.json) are read, never changed; every
file's SHA-256 and size must equal the manifest first, otherwise nothing is written. The target words are whatever the set
holds (824 words new to [단어] and 12 already registered ones whose Watchtower-list meaning had no fr / de / pl); nothing here
hard-codes a count. MANUAL_REVIEW is this repository's own review of the cells the report marked MEDIUM / REVIEW (the only
edits to the frozen text, each with its reason).
"""
import hashlib
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "tests", "reports", "watchtower_vocab_translation_fr_de_pl")
OUT = os.path.join(ROOT, "watchtower_vocab_translations_fr_de_pl.py")
LANGS = ("fr", "de", "pl")

MANUAL_REVIEW = {
    ("bỏ qua", "fr"): ("négliger", "Mt 23:23 'neglect' (ko 등한시하다); 'fermer les yeux sur' is 'turn a blind eye'"),
    ("bỏ qua", "de"): ("vernachlässigen", "'neglect', not 'übersehen' (overlook)"),
    ("bỏ qua", "pl"): ("zaniedbywać", "'neglect', not 'przymykać oczy na' (turn a blind eye)"),
    ("mịt mù", "fr"): ("flou", "en 'unclear' (the way ahead is unclear), not 'brumeux' (foggy)"),
    ("mịt mù", "de"): ("unklar", "en 'unclear'; 'verschwommen' is 'blurred'"),
    ("mịt mù", "pl"): ("niejasny", "en 'unclear'; 'zamglony' is 'misted over'"),
    ("thấp kém", "de"): ("niedrig", "lowly / menial work; 'bescheiden' is 'modest'"),
    ("thấp kém", "pl"): ("podrzędny", "lowly / menial work; 'skromny' is 'modest'"),
    ("ám ảnh", "de"): ("verfolgen", "past mistakes 'haunt' us; 'heimsuchen' is 'to afflict / visit'"),
    ("ám ảnh", "pl"): ("dręczyć", "to haunt / torment the mind; 'prześladować myśli' is not idiomatic"),
    ("bị bó rễ", "de"): ("eingeengte Wurzeln haben", "a verb phrase like the other languages, not a bare participle"),
    ("thức ăn đặc", "de"): ("feste Nahrung", "Heb 5:14 in the German New World Translation: 'feste Nahrung' ('feste Speise' is Luther)"),
}


def verify_freeze():
    manifest = json.load(open(os.path.join(SRC, "freeze_manifest.json"), encoding="utf-8"))
    for name, meta in manifest.items():
        data = open(os.path.join(SRC, name), "rb").read()
        if hashlib.sha256(data).hexdigest() != meta["sha256"] or len(data) != meta["size_bytes"]:
            raise SystemExit("FREEZE MISMATCH: %s changed since it was frozen -- stop" % name)
    return manifest


def build():
    manifest = verify_freeze()
    rows = json.load(open(os.path.join(SRC, "wt_fr_de_pl_combined.json"), encoding="utf-8"))
    if len(rows) != manifest["wt_fr_de_pl_combined.json"]["records"]:
        raise SystemExit("record count %d does not match the manifest" % len(rows))
    out, seen = {}, set()
    for r in rows:
        key = r["canonical_key"]
        if key in seen:
            raise SystemExit("duplicate canonical key " + key)
        seen.add(key)
        cells = {}
        for lang in LANGS:
            text = (r.get(lang) or "").strip()
            if (key, lang) in MANUAL_REVIEW:
                text = MANUAL_REVIEW[(key, lang)][0]
            if not text:
                raise SystemExit("empty %s cell for %s" % (lang, key))
            cells[lang] = text
        out[key] = cells
    # every manual review entry must point at a real cell
    for (key, lang) in MANUAL_REVIEW:
        if key not in out:
            raise SystemExit("manual review of an unknown word: " + key)
    cjk = re.compile(r"[぀-ヿ㐀-鿿가-힯]")
    for key, cells in out.items():
        for lang in LANGS:
            if cjk.search(cells[lang]) or re.search(r"<[^>]+>", cells[lang]):
                raise SystemExit("%s: %s cell has CJK / Hangul / markup: %r" % (key, lang, cells[lang]))
    digest = hashlib.sha256(open(os.path.join(SRC, "wt_fr_de_pl_combined.json"), "rb").read()).hexdigest()
    conf = {}
    for r in rows:
        conf[r.get("confidence")] = conf.get(r.get("confidence"), 0) + 1
    lines = ['# -*- coding: utf-8 -*-',
             '"""Meanings of Watchtower study words in fr / de / pl.',
             '',
             'Generated by scripts/import_wt_translations_fr_de_pl.py from the frozen translation set',
             'tests/reports/watchtower_vocab_translation_fr_de_pl/wt_fr_de_pl_combined.json',
             '(sha256 %s, %d words x %d languages = %d cells; %s).' % (digest, len(out), len(LANGS), len(out) * len(LANGS), ", ".join("%d %s" % (conf[k], k) for k in sorted(conf, key=lambda x: str(x)))),
             'The MEDIUM / REVIEW words were reviewed by hand; the %d cells that were changed are listed in MANUAL_REVIEW of the script.' % len(MANUAL_REVIEW),
             'Do not edit by hand: change the script / the frozen set and regenerate.',
             '',
             'apply_wt_translations_fr_de_pl(watchtower_vocab) fills these into WATCHTOWER_VOCAB[].words[].mean -- only a language',
             'the word has no meaning in yet; an existing meaning is never overwritten. The key is the canonical word key',
             '(NFC, lower case, single spaces); canonical keys, ids, Korean meanings, cs / hu / id / zh_cn and tags are not touched.',
             '"""',
             '',
             'WT_TRANSLATIONS_FR_DE_PL = {']
    for key, cells in out.items():
        lines.append('    %s: {%s},' % (json.dumps(key, ensure_ascii=False), ", ".join('%s: %s' % (json.dumps(l), json.dumps(cells[l], ensure_ascii=False)) for l in LANGS)))
    lines += ['}', '',
              'WT_TRANSLATION_FR_DE_PL_LANGS = %s' % (tuple(LANGS),), '',
              '',
              'def _key(vi):',
              '    import re',
              '    import unicodedata',
              '    return re.sub(r"\\s+", " ", unicodedata.normalize("NFC", str(vi or ""))).strip().lower()',
              '',
              '',
              'def apply_wt_translations_fr_de_pl(watchtower_vocab):',
              '    """Fill the missing fr / de / pl meanings of the Watchtower words in place; returns how many cells it filled."""',
              '    filled = 0',
              '    for wk in watchtower_vocab:',
              '        for w in wk.get("words", []):',
              '            cells = WT_TRANSLATIONS_FR_DE_PL.get(_key(w.get("vi")))',
              '            if not cells or not isinstance(w.get("mean"), dict):',
              '                continue',
              '            for lang in WT_TRANSLATION_FR_DE_PL_LANGS:',
              '                if not w["mean"].get(lang):',
              '                    w["mean"][lang] = cells[lang]',
              '                    filled += 1',
              '    return filled',
              '']
    return "\n".join(lines)


def main():
    text = build()
    if "--check" in sys.argv:
        current = open(OUT, encoding="utf-8", newline="").read().replace("\r\n", "\n") if os.path.exists(OUT) else None
        if current != text:
            print("watchtower_vocab_translations_fr_de_pl.py is not what the frozen set produces")
            return 1
        print("OK: freeze verified, watchtower_vocab_translations_fr_de_pl.py matches")
        return 0
    open(OUT, "w", encoding="utf-8", newline="\n").write(text)
    print("freeze verified; wrote %s (%d words)" % (os.path.basename(OUT), text.count('\n    "')))
    return 0


if __name__ == "__main__":
    sys.exit(main())
