# -*- coding: utf-8 -*-
"""Writes watchtower_vocab_translations.py from the frozen 823-word translation set (cs / hu / id / zh_cn).

    python scripts/import_wt_translations.py        # verify the freeze, validate, (re)write the module
    python scripts/import_wt_translations.py --check  # verify the freeze + that the module is exactly what this would write

The frozen files (tests/reports/watchtower_vocab_translation/, freeze_manifest.json) are read, never changed. They are
verified first: every deliverable's SHA-256 and size must equal the manifest, otherwise nothing is written.
MANUAL_REVIEW is this repository's own review of the cells the translation report marked MEDIUM (the only edits to the
frozen text, each with its reason); nothing else is touched.
"""
import hashlib
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "tests", "reports", "watchtower_vocab_translation")
OUT = os.path.join(ROOT, "watchtower_vocab_translations.py")
LANGS = ("cs", "hu", "id", "zh_cn")

# (canonical key, language) -> (reviewed text, why). Reviewed against the Korean / English / Traditional Chinese meanings
# and the example sentence of WATCHTOWER_VOCAB.
MANUAL_REVIEW = {
    ("bị nhiễm tinh thần", "hu"): ("megfertőződik a szellemtől", "'megfertőzi a szellem' is active (the spirit infects it); the word is passive: be infected by a spirit"),
    ("bị nhiễm tinh thần", "id"): ("terpengaruh oleh roh dunia", "'pikiran dunia' is 'the world's thinking'; tinh thần here is the spirit (roh) of the world"),
    ("bị nhiễm tinh thần", "zh_cn"): ("受影响沾染", "the existing Traditional Chinese meaning is 受影響沾染; 精神腐化 (spiritual corruption) says something else"),
    ("bị bó rễ", "hu"): ("beszorul a gyökere", "'kinövi a cserepét' is 'outgrows its pot'; the word is root-bound: its root is stuck"),
}


def verify_freeze():
    manifest = json.load(open(os.path.join(SRC, "freeze_manifest.json"), encoding="utf-8"))
    if manifest.get("status") != "FROZEN":
        raise SystemExit("freeze manifest status is %r, not FROZEN" % manifest.get("status"))
    for name, meta in manifest["deliverables"].items():
        data = open(os.path.join(SRC, name), "rb").read()
        if hashlib.sha256(data).hexdigest() != meta["sha256"] or len(data) != meta["size_bytes"]:
            raise SystemExit("FREEZE MISMATCH: %s changed since it was frozen -- stop" % name)
    return manifest


def build():
    manifest = verify_freeze()
    rows = json.load(open(os.path.join(SRC, "wt_translation_combined.json"), encoding="utf-8"))
    if len(rows) != manifest["total_canonical_records"]:
        raise SystemExit("record count %d != %d" % (len(rows), manifest["total_canonical_records"]))
    out, seen = {}, set()
    for r in rows:
        key = r["canonical_key"]
        if key in seen:
            raise SystemExit("duplicate canonical key " + key)
        seen.add(key)
        cells = {}
        for lang in LANGS:
            text = (r.get(lang) or "").strip()
            if (key, lang) in MANUAL_REVIEW:
                text = MANUAL_REVIEW[(key, lang)][0]
            if not text:
                raise SystemExit("empty %s cell for %s" % (lang, key))
            cells[lang] = text
        out[key] = cells
    # script sanity: Latin-script languages hold no CJK / Hangul, Simplified Chinese no Hangul / kana
    cjk = re.compile(r"[぀-ヿ㐀-鿿가-힯]")
    for key, cells in out.items():
        for lang in ("cs", "hu", "id"):
            if cjk.search(cells[lang]):
                raise SystemExit("%s: %s cell has CJK/Hangul: %r" % (key, lang, cells[lang]))
        if re.search(r"[぀-ヿ가-힯]", cells["zh_cn"]) or not re.search(r"[一-鿿]", cells["zh_cn"]):
            raise SystemExit("%s: zh_cn cell is not Chinese: %r" % (key, cells["zh_cn"]))
    digest = hashlib.sha256(open(os.path.join(SRC, "wt_translation_combined.json"), "rb").read()).hexdigest()
    lines = ['# -*- coding: utf-8 -*-',
             '"""Meanings of the 823 Watchtower study words that were new to [단어], in cs / hu / id / zh_cn.',
             '',
             'Generated by scripts/import_wt_translations.py from the frozen translation set',
             'tests/reports/watchtower_vocab_translation/wt_translation_combined.json',
             '(sha256 %s, %d words x %d languages = %d cells; 821 HIGH, 2 MEDIUM, 0 REVIEW).' % (digest, len(out), len(LANGS), len(out) * len(LANGS)),
             'The MEDIUM words were reviewed by hand; the cells that were changed are listed in MANUAL_REVIEW of the script.',
             'Do not edit by hand: change the script / the frozen set and regenerate.',
             '',
             'apply_wt_translations(watchtower_vocab) fills these into WATCHTOWER_VOCAB[].words[].mean -- only a language the',
             'word has no meaning in yet; an existing meaning is never overwritten. The key is the canonical word key',
             '(NFC, lower case, single spaces); canonical keys, ids, Korean meanings and tags are not touched.',
             '"""',
             '',
             'WT_TRANSLATIONS = {']
    for key, cells in out.items():
        lines.append('    %s: {%s},' % (json.dumps(key, ensure_ascii=False), ", ".join('%s: %s' % (json.dumps(l), json.dumps(cells[l], ensure_ascii=False)) for l in LANGS)))
    lines += ['}', '',
              'WT_TRANSLATION_LANGS = %s' % (tuple(LANGS),), '',
              '',
              'def _key(vi):',
              '    import re',
              '    import unicodedata',
              '    return re.sub(r"\\s+", " ", unicodedata.normalize("NFC", str(vi or ""))).strip().lower()',
              '',
              '',
              'def apply_wt_translations(watchtower_vocab):',
              '    """Fill the missing cs / hu / id / zh_cn meanings of the Watchtower words in place; returns how many cells it filled."""',
              '    filled = 0',
              '    for wk in watchtower_vocab:',
              '        for w in wk.get("words", []):',
              '            cells = WT_TRANSLATIONS.get(_key(w.get("vi")))',
              '            if not cells or not isinstance(w.get("mean"), dict):',
              '                continue',
              '            for lang in WT_TRANSLATION_LANGS:',
              '                if not w["mean"].get(lang):',
              '                    w["mean"][lang] = cells[lang]',
              '                    filled += 1',
              '    return filled',
              '']
    return "\n".join(lines)


def main():
    text = build()
    if "--check" in sys.argv:
        current = open(OUT, encoding="utf-8", newline="").read().replace("\r\n", "\n") if os.path.exists(OUT) else None
        if current != text:
            print("watchtower_vocab_translations.py is not what the frozen set produces")
            return 1
        print("OK: freeze verified, watchtower_vocab_translations.py matches")
        return 0
    open(OUT, "w", encoding="utf-8", newline="\n").write(text)
    print("freeze verified; wrote %s (%d words)" % (os.path.basename(OUT), text.count("\n    \"")))
    return 0


if __name__ == "__main__":
    sys.exit(main())
